civiform/civiform

bin/run-dev
docker-compose.yml

Docker swarm (`stack.yml`) is the go-to if you need multiple machines to coordinate but want something lighter weight than kubernetes.  Docker compose (`docker-compose.yml`) runs only on one machine but is much simpler want to be able to inspect it as it goes.
Before, we thought we'd need to run on-prem, so created the compose file with the intention of using it in a swarm, but we are newly confident we can count on a cloud provider, so we can change it back to the default name.

file naming convention change: Docker Swarm -> Docker Compose

---

.github/workflows/format.yaml
README.md
bin/fmt
formatter.Dockerfile
universal-application-tool-0.0.1/app/Module.java
universal-application-tool-0.0.1/app/controllers/AsyncController.java
universal-application-tool-0.0.1/app/controllers/CountController.java
universal-application-tool-0.0.1/app/controllers/HomeController.java
universal-application-tool-0.0.1/app/filters/ExampleFilter.java
universal-application-tool-0.0.1/project/plugins.sbt
universal-application-tool-0.0.1/test/BrowserTest.java
universal-application-tool-0.0.1/test/FunctionalTest.java
universal-application-tool-0.0.1/test/UnitTest.java

This PR revises the rules for formatting to include sorted imports, sorts existing imports, and switches from using an sbt plugin to using the google java formatter directly in a docker container.  This gives us more control.  `bin/fmt` continues to work correctly.

Include formatting imports.

---

universal-application-tool-0.0.1/build.sbt

This adds the library dependency for [pac4j](https://github.com/pac4j/play-pac4j), so that we can start building our auth support
Tested by running bin/run-dev and verifying app started and was reachable
Fixes #54

Add library dependency for pac4j

---

infra/containers.yaml

Targets 75% CPU utilization, scales up to 5 containers, or down to 2.  Fewer than 2 would be bad because it leaves the entire application down with a single failure, and higher than 5 is just unlikely.  Might increase that number for launch / public announcement?

Add container autoscaling based on CPU utilization

---

bin/deploy-prod
infra/containers.yaml
infra/database.yaml
infra/secrets.yaml
infra/stack.yaml

Formerly we were generating these things client-side, which meant we altered the password and secret key on every redeploy - this stores and generates them server-side which is much more appropriate.

Store the password and secret key in secrets manager

---

universal-application-tool-0.0.1/conf/application.conf

Turn off database logSql to avoid confusion in test output. This should be fine since we use Ebean to manage our database interaction.

Turn off database logSql

---

infra/database.yaml
infra/load_balancer.yaml
infra/monitoring.yaml
infra/stack.yaml

This adds a handful of alerts, described in comments in the file.
Page on:
* no db connections
* no healthy containers
* 5xx > 5%
Send ticket on:
* lots of 4xxs
* db free space low
* db cpu usage high
This doesn't actually hook up any sms or email or pager hooks, but you can do that in the UI - also we don't want those until we're live anyway.

Add monitoring to ELB and DB, add alert channels, do not populate them.

---

.gitignore
universal-application-tool-0.0.1/app/models/Applicant.java
universal-application-tool-0.0.1/app/services/applicant/ApplicantData.java
universal-application-tool-0.0.1/build.sbt
universal-application-tool-0.0.1/package-lock.json
universal-application-tool-0.0.1/test/models/ApplicantTest.java
universal-application-tool-0.0.1/test/repository/ApplicantRepositoryTest.java

Create ApplicantData class that abstracts the applicant entity stored in the database and add a way to access that ApplicantData through ebean Applicant entity.
Note that the ApplicantData class is very rough for now. We will add nicer methods that hide away the specifics of dealing with jsonpath types.
Contributes to #100

Access applicant data through ApplicantData class initialized by ebean Applicant entity

---

docker-compose.yml

Now that we have a prod db that doesn't use docker-compose, we can trust this is just for dev and can expose the port for dev purposes.

Make db dev a little easier - expose database on default port in dev mode.

---

.github/workflows/pr.yaml
bin/check-cfn-change
infra/monitoring.yaml
infra/stack.yaml

If you make a change to a file under `infra/`, we will create a CFN changeset, which we will check to see which resources will be replaced.  This will crash if your cfn configuration is invalid or would require permissions we don't have, but will succeed regardless of the impact of your change.
It does print the likely impact of the change, which might help to keep updates safe, but I'll also add some stack rules later to keep us from accidentally deleting the database, for instance.
Hopefully, you'll see the message on this PR, due to the dummy file - which I will remove after testing to show that it works.  There's a chance there will be some back-and-forth since we don't control the creds used here - they may be invalid for this sort of operation.  But it works on my fork: …

Github action to validate correct configuration of cloudformation

---

bin/sbt

You might try putting this on your `PATH` so that you can just type `sbt`!  Acts just like SBT but it runs in the container so you don't have anything weird going on with SBT versions.

Add bin/sbt which acts like regular SBT but runs in a docker container.

---

universal-application-tool-0.0.1/test/FunctionalTest.java
universal-application-tool-0.0.1/test/repository/WithPostgresContainer.java

Add @Before method to truncate the database in WithPostgresContainer.
Fixes test cases in `FunctionalTest` that rely on database state by explicitly inserting into the DB in each test.
[Fixes] #157

Add @Before truncate to WithPostgresContainer

---

.github/workflows/format.yaml
universal-application-tool-0.0.1/app/services/program/ProgramServiceImpl.java
universal-application-tool-0.0.1/app/services/program/test/FakeProgramService.java

Make sure the Java formatter in GitHub uses the same version of JDK as our app (currently 11.0.10), so the formatter version is correctly selected (v1.9).

Setup correct java version in GitHub formatter check

---

universal-application-tool-0.0.1/project/plugins.sbt

Because this produces format different from our `bin/fmt`. This happens every we run our dev server.

remove sbt java auto fmt

---

universal-application-tool-0.0.1/app/auth/FakeAdminClient.java
universal-application-tool-0.0.1/app/auth/ProfileFactory.java
universal-application-tool-0.0.1/app/auth/Roles.java
universal-application-tool-0.0.1/app/controllers/admin/AdminProgramController.java
universal-application-tool-0.0.1/app/modules/SecurityModule.java
universal-application-tool-0.0.1/app/views/LoginForm.java
universal-application-tool-0.0.1/test/app/BrowserTest.java

Lock down the admin endpoints to admin accounts, and provide a way for us to create and assume an admin role in testing.
Looking for a review from both @natsid and @AWBaumann - @natsid for security & @AWBaumann as an FYI for the admin flow.

Create an admin account test client.

---

universal-application-tool-0.0.1/app/forms/QuestionForm.java
universal-application-tool-0.0.1/app/models/Question.java
universal-application-tool-0.0.1/app/services/question/AddressQuestionDefinition.java
universal-application-tool-0.0.1/app/services/question/NameQuestionDefinition.java
universal-application-tool-0.0.1/app/services/question/QuestionDefinition.java
universal-application-tool-0.0.1/app/services/question/QuestionDefinitionBuilder.java
universal-application-tool-0.0.1/app/services/question/TextQuestionDefinition.java
universal-application-tool-0.0.1/test/controllers/admin/QuestionControllerTest.java
universal-application-tool-0.0.1/test/forms/QuestionFormTest.java
universal-application-tool-0.0.1/test/models/ProgramTest.java
universal-application-tool-0.0.1/test/models/QuestionTest.java
universal-application-tool-0.0.1/test/repository/QuestionRepositoryTest.java
universal-application-tool-0.0.1/test/services/applicant/ApplicantServiceImplTest.java
universal-application-tool-0.0.1/test/services/program/ProgramServiceImplTest.java
universal-application-tool-0.0.1/test/services/question/QuestionDefinitionTest.java
universal-application-tool-0.0.1/test/services/question/QuestionServiceImplTest.java
universal-application-tool-0.0.1/test/services/question/ReadOnlyQuestionServiceImplTest.java
universal-application-tool-0.0.1/test/support/ResourceFabricator.java

It's not necessary to have an `Optional<ImmutableList>` so we're unwrapping it.
#237
In order to close #237 we should implement `QuestionDefinition.getPreferredQuestionText()` and `QuestionDefinition.getPreferredQuestionHelpText()` that uses a global `preferredLocale` variable so we're not passing around `Locale.ENGLISH` everywhere.

Convert QuestionHelpText to ImmutableMap, unwrapping the unnecessary Optional.

---

universal-application-tool-0.0.1/app/controllers/admin/AdminProgramBlocksController.java
universal-application-tool-0.0.1/app/controllers/admin/AdminProgramController.java
universal-application-tool-0.0.1/app/services/program/ProgramDefinition.java
universal-application-tool-0.0.1/app/views/admin/AdminLayout.java
universal-application-tool-0.0.1/app/views/admin/ProgramBlockEditView.java
universal-application-tool-0.0.1/app/views/admin/ProgramEditView.java
universal-application-tool-0.0.1/app/views/admin/ProgramIndexView.java
universal-application-tool-0.0.1/app/views/admin/ProgramNewOneView.java
universal-application-tool-0.0.1/conf/routes
universal-application-tool-0.0.1/test/controllers/admin/AdminProgramBlocksControllerTest.java
universal-application-tool-0.0.1/test/controllers/admin/AdminProgramControllerTest.java
universal-application-tool-0.0.1/test/support/ResourceFabricator.java

Add button to /admin/programs/:id/edit to "manage questions". The button goes to "/admin/programs/:pid/blocks/index".
`index`, if there are blocks to show, redirects to `/admin/programs/:pid/blocks/:bid/edit` for the first block. If there are no blocks to index, redirects to `/admin/programs/:pid/blocks/create`.
`create` creates an empty block and redirects to `/admin/programs/:pid/blocks/:bid/edit` for the last (latest) block.
`edit` has nothing but a button that goes to `create`.
Manage questions button
Edit view is just an "add block" button.

Add program block controllers and views, but no forms.

---

formatter.Dockerfile

The formatter used to use a debian derived OS, which provided a different default version of NPM, which wrote incompatible lockfiles, since `tsfmt` actually reads and rewrites the lockfile.  Now we use the same version in `uat` and `fmt`.  This will fix the issue raised in https://github.com/seattle-uat/universal-application-tool/pull/259.

Swap to alpine.  Ran and confirmed no changes on main.

---

bin/fmt

Always pull the most up-to-date version of the formatter from AWS.
If you are logged in to AWS and have configured docker creds for the formatter, it might not let you pull the most up to date version because your creds are old.  However, if you have *no* creds, it works fine.  This just deletes your creds if they are not working.  All our creds are temporary so it's not too surprising that this would happen sometimes.  Should be harmless, never delete anything that's still working.

Ensure we always run the most up-to-date formatter.

---

universal-application-tool-0.0.1/app/controllers/applicant/ApplicantProgramBlocksController.java
universal-application-tool-0.0.1/app/views/applicant/ApplicantProgramBlockEditView.java
universal-application-tool-0.0.1/conf/routes
universal-application-tool-0.0.1/test/controllers/applicant/ApplicantProgramBlocksControllerTest.java

`ApplicantProgramBlocksController` was added to the `controllers` package after a PR moved `ApplicantProgramsController` to a new `controllers.applicant` package. This PR puts them in the same package.

Move ApplicantProgramBlocksController to new `controllers.applicant` package

---

universal-application-tool-0.0.1/conf/logback.xml

Turn off the logs for all the javascript and css failures in unit tests.  They're not helpful and they clutter output.

These logs are super noisy, shut them all off.

---

.github/workflows/pr.yaml
.github/workflows/push.yaml

Use latest trilom version 1.2.4. This should fix a problem we're having with cloudformation.
See: https://github.com/trilom/file-changes-action/issues/93 and https://github.com/trilom/file-changes-action/pull/99

Use latest trilom version.

---

universal-application-tool-0.0.1/app/controllers/admin/AdminProgramBlockQuestionsController.java
universal-application-tool-0.0.1/app/services/program/DuplicateProgramQuestionException.java
universal-application-tool-0.0.1/app/services/program/ProgramBlockNotFoundException.java
universal-application-tool-0.0.1/app/services/program/ProgramDefinition.java
universal-application-tool-0.0.1/app/services/program/ProgramService.java
universal-application-tool-0.0.1/app/services/program/ProgramServiceImpl.java
universal-application-tool-0.0.1/app/services/question/QuestionNotFoundException.java
universal-application-tool-0.0.1/app/views/BaseHtmlView.java
universal-application-tool-0.0.1/app/views/admin/programs/ProgramBlockEditView.java
universal-application-tool-0.0.1/conf/routes
universal-application-tool-0.0.1/test/app/BaseBrowserTest.java
universal-application-tool-0.0.1/test/app/ProgramAdministrationBrowserTest.java
universal-application-tool-0.0.1/test/services/program/ProgramDefinitionTest.java
universal-application-tool-0.0.1/test/services/program/ProgramServiceImplTest.java

Adds `ProgramService` methods `addQuestionsToBlock` and `removeQuestionsFromBlock.
Adds `DuplicateProgramQuestionException` to be thrown when `addQuestionsToBlock` attempts to add a question that is already in the program.
Adds `AdminProgramBlockQuestionsController` for POST methods to add and remove questions to a block.
Adds forms to `ProgramBlockEditView` to add and remove questions to a block. 
[Fixes] #110 
[Fixes] #111 
[Fixes] #83 
[Fixes] #88 
[Fixes] #139

Controllers and views for adding/removing questions to blocks

---

universal-application-tool-0.0.1/app/export/PdfMapAssistant.java
universal-application-tool-0.0.1/test/export/PdfMapAssistantTest.java

This produces a PDF which is nearly identical to the input PDF, except that instead of text boxes / checkboxes, all the fields are lists of questions to map.
This will be useful in ring 3, especially for #181.

Convert a form-fill PDF to a "config" PDF.

---

universal-application-tool-0.0.1/app/controllers/admin/AdminProgramBlocksController.java
universal-application-tool-0.0.1/app/controllers/dev/DatabaseSeedController.java
universal-application-tool-0.0.1/app/models/Program.java
universal-application-tool-0.0.1/app/services/program/ProgramNeedsABlockException.java
universal-application-tool-0.0.1/app/services/program/ProgramService.java
universal-application-tool-0.0.1/app/services/program/ProgramServiceImpl.java
universal-application-tool-0.0.1/app/views/admin/programs/ProgramBlockEditView.java
universal-application-tool-0.0.1/conf/routes
universal-application-tool-0.0.1/test/controllers/admin/AdminProgramBlocksControllerTest.java
universal-application-tool-0.0.1/test/controllers/applicant/ApplicantProgramsControllerTest.java
universal-application-tool-0.0.1/test/services/program/ProgramServiceImplTest.java
universal-application-tool-0.0.1/test/support/ResourceCreator.java

A Program now must always have one block. That means a new `Program` includes an empty block, and the `ProgramService` prevents the last block from being delete. 
This allows for:
* `POST /admin/program/:pid/blocks` to create new blocks, which used to be a `GET` method.
* The `Add Block` button is now a form that uses the new POST method.
Due to a Program now coming with an empty Block, the following changes were made:
* `DatabaseSeedController` now updates and adds questions to the default empty block, and then adds block 2.
* `ProgramService` throws a `ProgramNeedsABlockException` when trying to delete the last block.
* Tests had to be changed to account for the new default empty block.
Bion
one_of(natalie or caroline) for the `ApplicantProgramsControllerTest`.

Program always has one block.

---

universal-application-tool-0.0.1/app/controllers/admin/QuestionController.java
universal-application-tool-0.0.1/app/controllers/dev/DatabaseSeedController.java
universal-application-tool-0.0.1/app/services/ErrorAnd.java
universal-application-tool-0.0.1/app/services/question/QuestionDefinition.java
universal-application-tool-0.0.1/app/services/question/QuestionService.java
universal-application-tool-0.0.1/app/services/question/QuestionServiceError.java
universal-application-tool-0.0.1/app/services/question/QuestionServiceImpl.java
universal-application-tool-0.0.1/test/controllers/admin/QuestionControllerTest.java
universal-application-tool-0.0.1/test/services/ErrorAndTest.java
universal-application-tool-0.0.1/test/services/applicant/ApplicantServiceImplTest.java
universal-application-tool-0.0.1/test/services/program/ProgramServiceImplTest.java
universal-application-tool-0.0.1/test/services/question/QuestionDefinitionTest.java
universal-application-tool-0.0.1/test/services/question/QuestionServiceImplTest.java
universal-application-tool-0.0.1/test/support/ResourceCreator.java

Instead of throwing exceptions, we return an ErrorAnd object that contains either a valid result or a set of errors, or both if meaningful.

Surface question validation failure

---

universal-application-tool-0.0.1/app/services/program/ProgramService.java
universal-application-tool-0.0.1/build.sbt

sbt compiles doc with scaladoc and does not properly render javadoc links when referring to classes outside the package. Suppress the warning as we cannot do anything about it.

Turn off sbt scala doc link warnings

---

universal-application-tool-0.0.1/app/services/applicant/ApplicantQuestion.java
universal-application-tool-0.0.1/app/services/applicant/Block.java
universal-application-tool-0.0.1/app/services/applicant/ValidationErrorMessage.java
universal-application-tool-0.0.1/app/views/BaseHtmlView.java
universal-application-tool-0.0.1/app/views/questiontypes/AddressQuestionRenderer.java
universal-application-tool-0.0.1/app/views/questiontypes/NameQuestionRenderer.java
universal-application-tool-0.0.1/test/services/applicant/ApplicantQuestionTest.java

* Add methods on question types, ApplicantQuestion, and Block for determining whether there are any validation errors.
* Render field-level (e.g., first name or zip code) error messages on address and name questions.
Works toward #361 and #100

Implement question- and field-level validation error interfaces.

---

universal-application-tool-0.0.1/app/models/Applicant.java
universal-application-tool-0.0.1/app/repository/ApplicantRepository.java
universal-application-tool-0.0.1/app/services/applicant/ApplicantData.java
universal-application-tool-0.0.1/app/services/applicant/ApplicantService.java
universal-application-tool-0.0.1/app/services/applicant/ApplicantServiceImpl.java
universal-application-tool-0.0.1/app/services/applicant/Block.java
universal-application-tool-0.0.1/app/services/applicant/Update.java
universal-application-tool-0.0.1/app/services/program/BlockDefinition.java
universal-application-tool-0.0.1/app/services/program/PathNotInBlockException.java
universal-application-tool-0.0.1/app/services/question/ScalarType.java
universal-application-tool-0.0.1/app/services/question/UnsupportedScalarTypeException.java
universal-application-tool-0.0.1/test/repository/ApplicantRepositoryTest.java
universal-application-tool-0.0.1/test/services/applicant/ApplicantServiceImplTest.java
universal-application-tool-0.0.1/test/services/program/BlockDefinitionTest.java

Rename `ApplicantService.update` to `ApplicantService.stageAndUpdateIfValid`, and then implement it.
Started from https://github.com/seattle-uat/universal-application-tool/pull/331.
The `stageAndUpdateIfValid` method tries to stage updates for a block. If there are unexpected problems with the program, block, or updates, then errors are returned with `ErrorAnd`. If there updates are staged, then a `ReadOnlyApplicantService` is returned that may contain invalid applicant data. 
Not implemented: the `ApplicantQuestion`s will be responsible for validating the staged applicant data. When available, `Block.isValid` is check if its `ApplicantQuestion`s are in a valid state. For now it just returns `true`.
[Fixes] #100  
ALL_OF(natsid, carolinedanzi)

Implement `ApplicantService.stageAndUpdateIfValid`.

---

bin/refresh-secrets
bin/run-dev

Follow-on to #383.  Adds a binary to download the secrets and updates `bin/run-dev` to use them if present.

Download secrets / provide secrets to uat container.

---

universal-application-tool-0.0.1/app/auth/AdfsProfileAdapter.java
universal-application-tool-0.0.1/app/auth/IdcsProfileAdapter.java
universal-application-tool-0.0.1/app/auth/ProfileMergeConflictException.java
universal-application-tool-0.0.1/app/auth/UatProfile.java
universal-application-tool-0.0.1/test/auth/ProfileMergeTest.java

As follow-up to #383, handle email merges, initially by ensuring that no email merges take place.
[Fixes] #385

Raise exception if merging profiles that use different email addresses.

---

universal-application-tool-0.0.1/test/repository/WithPostgresContainer.java
universal-application-tool-0.0.1/test/support/Questions.java

This means only one of each question can be created for each test. This is important because question paths need to be unique so if two applicant name questions are created without caching the ReadOnlyQuestionService will be unhappy.
`support.Questions` caches the `Question`s to prevent duplicate `Path`s in the core data model.

Cache questions made with support.Questions for testing. 

---

universal-application-tool-0.0.1/app/services/applicant/ApplicantQuestion.java
universal-application-tool-0.0.1/app/views/questiontypes/TextQuestionRenderer.java
universal-application-tool-0.0.1/test/views/questiontypes/TextQuestionRendererTest.java

Also fix a bug in `TextQuestion#getQuestionErrors`: if the value isn't present, should return empty set of errors.
Add tests.
Works toward #390

Render question errors in TextQuestionRenderer

---

universal-application-tool-0.0.1/test/controllers/applicant/ApplicantProgramBlocksControllerTest.java
universal-application-tool-0.0.1/test/repository/WithPostgresContainer.java
universal-application-tool-0.0.1/test/support/TestQuestionBank.java

Rename and add to docstring describing that the questions here may not be completely representative of questions defined by CiviForm administrators.

Rename support.Questions to support.TestQuestionBank 

---

.github/pull_request_template.md

I noticed that this template used to put `[Fixed]` in brackets, so if anyone kept the template, their PR wouldn't actually close the issue in question. The `Fixed` has to be freed from brackets for this to work. Thus, updating the template.

Update PR template so `Fixed` works properly

---

universal-application-tool-0.0.1/app/repository/QuestionRepository.java
universal-application-tool-0.0.1/test/repository/QuestionRepositoryTest.java

Appended delimiter to distinguish paths by key names
Fixes #476

Prevent path conflict on prefix

---

universal-application-tool-0.0.1/app/controllers/applicant/ApplicantProgramBlocksController.java
universal-application-tool-0.0.1/app/controllers/applicant/ApplicantProgramsController.java
universal-application-tool-0.0.1/app/models/Applicant.java
universal-application-tool-0.0.1/app/models/Application.java
universal-application-tool-0.0.1/app/models/Program.java
universal-application-tool-0.0.1/app/repository/ApplicationRepository.java
universal-application-tool-0.0.1/app/views/applicant/ProgramIndexView.java
universal-application-tool-0.0.1/conf/evolutions/default/8.sql
universal-application-tool-0.0.1/test/app/ApplicantProgramBrowserTest.java
universal-application-tool-0.0.1/test/controllers/applicant/ApplicantProgramBlocksControllerTest.java

Creates a new table - applications - which contains snapshots of a user's entire applicant object at the time that an application is submitted.  It links to a program and an applicant.
Moved some of the async logic around since now a request to the "next block" button might create this new DB object.  On that note, I'm sorry that this diff is borderline incomprehensible, I have _not_ figured out how to make java async code look good.  Suggestions welcome...
Fixes #205 
Fixed #209

Store applications in the database as a snapshot, display the ID of the snapshot

---

universal-application-tool-0.0.1/app/controllers/applicant/ApplicantProgramBlocksController.java
universal-application-tool-0.0.1/app/services/applicant/ApplicantData.java
universal-application-tool-0.0.1/app/services/applicant/ApplicantQuestion.java
universal-application-tool-0.0.1/app/services/applicant/ApplicantService.java
universal-application-tool-0.0.1/app/services/applicant/ApplicantServiceImpl.java
universal-application-tool-0.0.1/app/services/question/AddressQuestionDefinition.java
universal-application-tool-0.0.1/app/services/question/NameQuestionDefinition.java
universal-application-tool-0.0.1/app/services/question/QuestionDefinition.java
universal-application-tool-0.0.1/app/services/question/ScalarType.java
universal-application-tool-0.0.1/app/services/question/TextQuestionDefinition.java
universal-application-tool-0.0.1/test/controllers/applicant/ApplicantProgramBlocksControllerTest.java
universal-application-tool-0.0.1/test/services/applicant/ApplicantDataTest.java
universal-application-tool-0.0.1/test/services/applicant/ApplicantServiceImplTest.java
universal-application-tool-0.0.1/test/services/question/QuestionDefinitionTest.java
universal-application-tool-0.0.1/test/views/questiontypes/TextQuestionRendererTest.java

1. Add `updated_at` and `updated_in_program` metadata to questions themselves (i.e. they are scalars)
1. _QuestionDefinition, NameQuestionDefinition, AddressQuestionDefinition, TextQuestionDefinition_
2. Change `ScalarType.INT` to `ScalarType.LONG` - we will represent all whole numbers as longs
1. _ScalarType, ApplicantData (methods for int --> long)_
3. For each question path in updates for a block, write two pieces of metadata (updated time and program ID)
1. _ApplicantServiceImpl + Test_
4. Remove `stageAndUpdateIfValid` method on `ApplicantService` that exposes internal `Update` details, and instead only expose the method which uses `ImmutableMap`
1. _ApplicantService, ApplicantServiceImpl (reordered methods)_
5. Update `ApplicantData` methods to avoid writing the empty string
6. …

Write metadata for every question an applicant answered

---

bin/pull-image
bin/run-dev
bin/run-test
bin/sbt

Separate the logic pulling docker dev image in `bin/run-dev` and reuse it across `bin/run-test` and `bin/sbt`.

Have a script to pull dev image

---

universal-application-tool-0.0.1/app/controllers/applicant/ApplicantProgramBlocksController.java
universal-application-tool-0.0.1/app/models/Application.java
universal-application-tool-0.0.1/app/models/LifecycleStage.java
universal-application-tool-0.0.1/app/models/Program.java
universal-application-tool-0.0.1/app/models/Question.java
universal-application-tool-0.0.1/app/repository/ApplicationRepository.java
universal-application-tool-0.0.1/app/services/WellKnownPaths.java
universal-application-tool-0.0.1/app/services/program/ProgramDefinition.java
universal-application-tool-0.0.1/app/services/program/ProgramServiceImpl.java
universal-application-tool-0.0.1/app/views/admin/programs/ProgramApplicationListView.java
universal-application-tool-0.0.1/conf/evolutions/default/9.sql
universal-application-tool-0.0.1/test/app/ApplicantProgramBrowserTest.java
universal-application-tool-0.0.1/test/repository/ApplicationRepositoryTest.java
universal-application-tool-0.0.1/test/support/ResourceCreator.java

This makes the necessary database changes for applications, programs, and questions to have lifecycle states.  All three go `DRAFT` (editable but not visible to others) -> `ACTIVE` (visible to others, not editable) -> `OBSOLETE` (usable by in-progress or existing apps / programs, not visible to new ones) -> `DELETED` (no longer visible to anyone).
Also updates application submit logic to use these states, since that's the easiest of the three!  Doesn't do anything to UX yet.
Related to #508.

Add notion of lifecycle stages to backend - predecessor to versioning

---

universal-application-tool-0.0.1/app/services/program/ProgramDefinition.java
universal-application-tool-0.0.1/test/controllers/admin/AdminProgramBlocksControllerTest.java
universal-application-tool-0.0.1/test/services/program/ProgramDefinitionTest.java
universal-application-tool-0.0.1/test/services/program/ProgramServiceImplTest.java
universal-application-tool-0.0.1/test/support/ProgramBuilderTest.java

getBlockDefinition was overloaded by two signatures, one with an int argument (index) and one with a long argument (id). Rename getting by index to distinguish two semantics. This function is only used in tests.

Rename getBlockDefinitionByIndex to distinguish getting by index from getting by id

---

docker-compose.yml

Following advice from joshuasuereth:
> I think your caching issues are 100% related to your docker setup.  While I love docker, sbt relies on access to "global directories" where it caches things between invocations. If you can local-mount the following it should help:
> - `*/target directories`
> - `~/.coursier`
> - `~/.sbt`
> - `~/.ivy`

Mount sbt cache volumes in dev container

---

universal-application-tool-0.0.1/build.sbt
universal-application-tool-0.0.1/test/services/applicant/ApplicantQuestionTest.java
universal-application-tool-0.0.1/test/services/question/QuestionDefinitionTest.java
universal-application-tool-0.0.1/test/views/admin/question/QuestionConfigTest.java
universal-application-tool-0.0.1/test/views/components/IconsTest.java
universal-application-tool-0.0.1/test/views/questiontypes/ApplicantQuestionRendererFactoryTest.java

Adds tests that fail if a new `QuestionType` enum is added, so that it is harder to miss files that should be changed when adding a new question type.
Fixes #581 
Sample test failure (added a NEW_TYPE enum):

Add tests that fail if a new QuestionType enum is added

---

universal-application-tool-0.0.1/app/services/Path.java
universal-application-tool-0.0.1/app/services/applicant/ApplicantData.java
universal-application-tool-0.0.1/test/services/PathTest.java

The order of paths was very specific and felt dangerous to use, and it was only used in one place (ApplicantData.put) which can be done with recursion.
Path.parentPaths() is removed in favor for recursion, which is not dependent on the order of paths.

Remove Path.parentPaths()

---

universal-application-tool-0.0.1/app/services/Path.java
universal-application-tool-0.0.1/app/services/applicant/ApplicantData.java

We actually don't need to check parent path is empty because hasPath(...) is true.

Revert last change to remove Path.parentPaths.

---

universal-application-tool-0.0.1/app/services/Path.java
universal-application-tool-0.0.1/app/services/applicant/ApplicantData.java
universal-application-tool-0.0.1/test/services/applicant/ApplicantDataTest.java

`put` methods in `ApplicantData` should be able to handle paths at the JSON root

Allow adding paths that do not begin  with applicant

---

universal-application-tool-0.0.1/app/controllers/applicant/ApplicantProgramsController.java
universal-application-tool-0.0.1/app/repository/ApplicantRepository.java
universal-application-tool-0.0.1/app/services/applicant/ApplicantService.java
universal-application-tool-0.0.1/app/services/applicant/ApplicantServiceImpl.java
universal-application-tool-0.0.1/test/app/ApplicantProgramBrowserTest.java
universal-application-tool-0.0.1/test/app/ApplicationReviewBrowserTest.java
universal-application-tool-0.0.1/test/app/BaseBrowserTest.java
universal-application-tool-0.0.1/test/controllers/applicant/ApplicantProgramsControllerTest.java
universal-application-tool-0.0.1/test/support/ProgramBuilder.java
universal-application-tool-0.0.1/test/support/ResourceCreator.java

Adds a new query to the applicant repository (and service, as a pass-through) to show only the programs that are relevant to the user - published non-obsolete programs, and programs that are in-progress.
Related to #508.

Only show published programs (or in-progress ones) to applicants.

---

bin/localstack/mk-s3
bin/localstack/purge-s3
bin/localstack/wait
bin/run-dev
bin/stop-dev
docker-compose.yml
universal-application-tool-0.0.1/app/repository/AmazonS3Client.java
universal-application-tool-0.0.1/build.sbt
universal-application-tool-0.0.1/conf/application.conf

Adds docker-compose file to set up basic localstack, as well as commands to create local s3 bucket
Defines a `DEV_ENV=1` environment var in dev docker-compose.yaml to inform app whether too look for local s3 buck and (attempts to) add java code in to hook up app backend to local s3 bucket
- Note: *I haven't been able to test whether the browser tests actually work though, since I can't seem to get a UI set up on my system. Will have to look at that further*
Fixes #482

Local s3 - Closes #482

---

bin/localstack/wait
docker-compose.yml
universal-application-tool-0.0.1/conf/logback.xml

- Use `curl` instead of `wget` as `curl` is more platform-portable
- Set AWS keys to `test` if not provided for localstack to function correctly
- Minor cleanup of docker-compose file

Enhance waiting logic for localstack

---

universal-application-tool-0.0.1/app/services/applicant/ApplicantData.java
universal-application-tool-0.0.1/app/services/applicant/IllegalDataException.java
universal-application-tool-0.0.1/app/services/applicant/JsonPathProvider.java
universal-application-tool-0.0.1/test/services/applicant/ApplicantDataTest.java

We will want the ability to record which options an applicant selected from a list of things (useful for dropdown, checkbox, etc. questions). To do this, we need the ability to write and read lists at paths.
1) Changes JsonPath's JsonProvider to Jackson, which supports `TypeRef` reading
2) Reorders tests to keep those for the same type together

Add ability to write and read lists in ApplicantData

---

bin/run-dev
docker-compose.yml
universal-application-tool-0.0.1/app/repository/AmazonS3Client.java
universal-application-tool-0.0.1/conf/application.conf

Add a few settings to easily disable aws and localstack.
To disable S3 connection from civiform:
- set aws.enable to false in application.conf
To disable localstack from our docker compose
- run `bin/stop-dev`
- set environment variable 
```shell
export DISABLE_LOCALSTACK=1
```

Add a knob to easily disable localstack/s3

---

universal-application-tool-0.0.1/app/auth/AdfsProfileAdapter.java
universal-application-tool-0.0.1/app/auth/IdcsProfileAdapter.java
universal-application-tool-0.0.1/app/auth/UatProfileAdapter.java

Correctly add roles to profiles when a profile already exists.

Add roles on merge correctly.

---

.github/workflows/format.yaml

The latest version upgraded to 1.10 today and causes inconsistency between our local formatter and github actions.

Fix java formatter version to 1.9

---

bin/build-and-push
bin/build-browser-tests
bin/fmt
bin/localstack/mk-s3
bin/localstack/purge-s3
bin/npm
bin/run-browser-test-env
bin/run-browser-tests
bin/run-browser-tests-ci
bin/run-browser-tests-local
bin/run-dev
bin/run-test
bin/sbt
browser-test/bin/fmt

Scripts that parsed PWD or BASH_SOURCE now use `pushd` with `git rev-parse --show-toplevel` and end with a `popd`.
A `set -e` was added to `bin/run-dev` to error early because that one has been prone to errors.
Tested by running the scripts from `universal-applicantion-tool_0.0.1/app`.
ALL

Scripts that need to be in specific directories are `pushd`ed to the right place.

---

universal-application-tool-0.0.1/app/services/question/ReadOnlyQuestionService.java
universal-application-tool-0.0.1/app/services/question/ReadOnlyQuestionServiceImpl.java
universal-application-tool-0.0.1/test/services/question/ReadOnlyQuestionServiceImplTest.java

Cleaned up Read Only Question Service (#651)
For `ReadOnlyQuestionService.getQuestionDefinition` I removed:
* 3 test cases
* 2 methods from interface and implementation
Before reviewing the changes, if desired I believe the `ReadOnlyQuestionService` can be further cleaned up as a few more functions are only used in test cases or just the implementation itself:
* `getAllScalars()`
* `getPathScalars()`
* `getPathType()`
* `isValid()`
* `setPreferredLocale(Locale)`
* `getPreferredLocale()`
Fixes #651

Cleaned up Read Only Question Service (#651)

---

universal-application-tool-0.0.1/app/services/Path.java
universal-application-tool-0.0.1/app/services/applicant/ApplicantData.java
universal-application-tool-0.0.1/app/services/applicant/ApplicantServiceImpl.java
universal-application-tool-0.0.1/app/services/question/AddressQuestionDefinition.java
universal-application-tool-0.0.1/app/services/question/MultiOptionQuestionDefinition.java
universal-application-tool-0.0.1/app/services/question/NameQuestionDefinition.java
universal-application-tool-0.0.1/app/services/question/NumberQuestionDefinition.java
universal-application-tool-0.0.1/app/services/question/QuestionDefinition.java
universal-application-tool-0.0.1/app/services/question/TextQuestionDefinition.java
universal-application-tool-0.0.1/test/controllers/applicant/ApplicantProgramsControllerTest.java
universal-application-tool-0.0.1/test/services/PathTest.java
universal-application-tool-0.0.1/test/services/applicant/ReadOnlyApplicantProgramServiceImplTest.java

Please explain the changes you made here:
* Replaced `path.toBuilder().append(XYZ).build()` with `path.join(XYZ)`.
* All builder append usages were inside `ApplicantServiceImpl`.
* Added `pathJoin()` unit test to `PathTest`.
* Verified passing unit tests for `PathTest` & `ApplicantServiceImplTest`.
* Removed todo documentation above `Path.join()`.
Fixes #638.

Use the new Path.join method to append to a path. (#638)

---

docker-compose.yml

Turns on listening for the debug port, but continues if no one connects to debug.  Instructions for setting up the debugger are at https://github.com/seattle-uat/civiform/wiki/Java-Debugging.

Enable debugging in bin/run-dev.

---

infra/filestorage.yaml

Only allow get object from s3 through our task role.

Allow presigned url access to s3

---

.github/workflows/cron.yaml

No need to build app, prober is run against staging.

Remove app build in prober cron

---

universal-application-tool-0.0.1/app/views/admin/questions/QuestionEditView.java

We should create the correct type of `QuestionForm` instead of a generic `QuestionForm` when rendering the view-only form
Staging currently throws this error: https://slack-files.com/T01Q6PJQAES-F01TELG2D1V-c8346a1fe0

Use `getQuestionFormForType` in `renderViewQuestionForm`

---

.github/workflows/cron.yaml
bin/deploy-prod
bin/deploy-staging

Deploy-prod marks latest as prod, rather than building from scratch.  Both deploy-prod and deploy-staging now include hupping the containers, which does not happen reliably in cloudformation.

Ensure that deploy-prod and deploy-staging update things correctly.

---

bin/check-cfn-change
infra/load_balancer.yaml

Remove the http path on port 80, leaving only https on port 443.
Related to #742.

Only use https.

---

universal-application-tool-0.0.1/conf/application.conf

Like it says in the comment - don't auto apply database downs (so we can't dump the prod db anymore).

Do not allow us to automatically apply db DOWNs.

---

universal-application-tool-0.0.1/app/controllers/admin/QuestionController.java
universal-application-tool-0.0.1/app/views/admin/questions/QuestionEditView.java

A few minor refactoring of the `QuestionEditView` public methods before adding repeater/repeated question things. Got rid of curly brackets in switch statements, and move some `QuestionType` logic closer to where the TODOs have more context.
**ONE MAJOR CHANGE**: the `QuestionController.update` now throws a runtime exception for unsupported question types because we should never been in a situation where we update a question that were able to create, but aren't able to update. This _really_ helps make the repeater/repeated questions thing easier.

Minor refactor of QuestionEditView and QuestionController.

---

universal-application-tool-0.0.1/app/controllers/admin/QuestionController.java
universal-application-tool-0.0.1/app/repository/QuestionRepository.java
universal-application-tool-0.0.1/app/services/Path.java
universal-application-tool-0.0.1/app/services/question/QuestionServiceImpl.java
universal-application-tool-0.0.1/app/services/question/ReadOnlyQuestionService.java
universal-application-tool-0.0.1/app/views/admin/questions/QuestionEditView.java
universal-application-tool-0.0.1/conf/routes
universal-application-tool-0.0.1/test/controllers/admin/QuestionControllerTest.java
universal-application-tool-0.0.1/test/controllers/applicant/ApplicantProgramBlocksControllerTest.java
universal-application-tool-0.0.1/test/repository/QuestionRepositoryTest.java
universal-application-tool-0.0.1/test/services/PathTest.java
universal-application-tool-0.0.1/test/services/export/CsvExporterTest.java
universal-application-tool-0.0.1/test/services/program/BlockDefinitionTest.java
universal-application-tool-0.0.1/test/services/question/QuestionServiceImplTest.java
universal-application-tool-0.0.1/test/services/question/ReadOnlyQuestionServiceImplTest.java
universal-application-tool-0.0.1/test/support/TestQuestionBank.java

The `String.startsWith` cannot be used with repeated questions.
Question invariants are now: name, path, repeater id, and question type.
Updated the `TestQuestionBank` paths to what they should be based on their names.
Also got rid of an unused `Request` argument.

Change how path conflicts are caught, and add repeater id and path to question invariants.

---

universal-application-tool-0.0.1/app/controllers/admin/QuestionController.java
universal-application-tool-0.0.1/app/forms/AddressQuestionForm.java
universal-application-tool-0.0.1/app/forms/MultiOptionQuestionForm.java
universal-application-tool-0.0.1/app/forms/QuestionForm.java
universal-application-tool-0.0.1/app/forms/TextQuestionForm.java
universal-application-tool-0.0.1/app/views/admin/questions/QuestionEditView.java
universal-application-tool-0.0.1/test/controllers/admin/QuestionControllerTest.java
universal-application-tool-0.0.1/test/forms/AddressQuestionFormTest.java
universal-application-tool-0.0.1/test/forms/CheckboxQuestionFormTest.java
universal-application-tool-0.0.1/test/forms/DropdownQuestionFormTest.java
universal-application-tool-0.0.1/test/forms/MultiOptionQuestionFormTest.java
universal-application-tool-0.0.1/test/forms/QuestionFormTest.java
universal-application-tool-0.0.1/test/forms/RadioButtonQuestionFormTest.java
universal-application-tool-0.0.1/test/forms/TextQuestionFormTest.java

Remove 'questionParentPath' from `QuestionForm`.
Adds an explicit `Path` argument to `QuestionForm.getBuilder` with a temporary method that generates a path based on just the name.
This is some pre-work for #781

Get rid of "questionParentPath" from `QuestionForm`.

---

universal-application-tool-0.0.1/app/services/applicant/question/NumberQuestion.java
universal-application-tool-0.0.1/test/services/applicant/question/NumberQuestionTest.java

#769 inadvertently created a new bug where an exception is thrown when a user attempts to submit an empty value for questions of type `number`. This PR makes it so that number fields are not required by default. In other words, the field will pass validation on the applicant side if it is left blank.
However, if the admin has configured a minimum or maximum value on the `number` question, we now *do* require a value, and return a `"Must be at least %d"` or `"Must be at most %d"` validation error message if it is left blank.
Fixes #409

Make empty number value inputs pass validation, unless there is a configured minimum or maximum value

---

universal-application-tool-0.0.1/app/services/applicant/question/NumberQuestion.java
universal-application-tool-0.0.1/test/services/applicant/question/NumberQuestionTest.java

We should not consider a number question that is answered with an empty value to be invalid if there is a min and/or max set.
This is because a question's required-ness is set at the program definition level, rather than at the question level.
Required questions at the program definition level is not yet implemented.

Don't test number value against min or max if it's empty

---

universal-application-tool-0.0.1/app/views/admin/questions/QuestionConfig.java

The checkbox input needs value=true.
From /dev/seed, an address question without pobox checkbox checked
From /dev/seed, an address question with pobox checkbox checked
Fixes #817

[BUGFIX-817] Set checkbox input value to true.

---

browser-test/src/dev_file_upload.test.ts

The test wouldn't pass when running locally, so skip the check.

Skip download browser test in localhost

---

universal-application-tool-0.0.1/app/views/admin/questions/QuestionsListView.java

Move new question button to top left of page, below page title.
Fixes #813#813

[BUGFIX-813] Move new question button to top left of page, below page title.

---

universal-application-tool-0.0.1/app/services/question/types/MultiOptionQuestionDefinition.java
universal-application-tool-0.0.1/test/services/question/types/MultiOptionQuestionDefinitionTest.java

Another instance of the error fixed in #827.

Add another place where we find the correct string via locale lookup.

---

universal-application-tool-0.0.1/test/support/TestQuestionBank.java

`computeIfAbsent` can only update one key at a time. Make sure we create the question we need before we call `computeIfAbsent`

Fix a synchronization bug in test question bank

---

infra/containers.yaml
infra/filestorage.yaml
infra/stack.yaml

Use separate roles for staging and prod so they cannot access each other's resources, specifically S3 buckets.

Separate ECS task roles between staging and prod

---

browser-test/src/application_csv_download.test.ts
browser-test/src/application_review.test.ts
browser-test/src/support/index.ts
universal-application-tool-0.0.1/app/controllers/HomeController.java
universal-application-tool-0.0.1/app/controllers/applicant/ApplicantInformationController.java
universal-application-tool-0.0.1/app/forms/ApplicantInformationForm.java
universal-application-tool-0.0.1/app/models/Applicant.java
universal-application-tool-0.0.1/app/services/applicant/ApplicantData.java
universal-application-tool-0.0.1/app/views/applicant/ApplicantInformationView.java
universal-application-tool-0.0.1/conf/routes
universal-application-tool-0.0.1/test/app/SecurityBrowserTest.java
universal-application-tool-0.0.1/test/controllers/applicant/ApplicantInformationControllerTest.java
universal-application-tool-0.0.1/test/controllers/applicant/ApplicantProgramBlocksControllerTest.java
universal-application-tool-0.0.1/test/controllers/applicant/ApplicantProgramsControllerTest.java
universal-application-tool-0.0.1/test/controllers/applicant/WithMockedApplicantProfiles.java
universal-application-tool-0.0.1/test/models/ApplicantTest.java
universal-application-tool-0.0.1/test/services/applicant/ApplicantDataTest.java

Add an information form to get an applicant's preferred language the first time they log in. After they select their preferred language, we set the `PLAY_LANG` cookie so all requests are localized
This also refactors the applicant controller tests to extend a `WithMockedApplicantProfiles` class, so that the controller tests can share code to pass the authorization check for applicants
Fixes #787

Allow an applicant to set their preferred language

---

universal-application-tool-0.0.1/test/auth/UatProfileTest.java
universal-application-tool-0.0.1/test/controllers/admin/AdminProgramBlocksControllerTest.java
universal-application-tool-0.0.1/test/controllers/admin/QuestionControllerTest.java
universal-application-tool-0.0.1/test/controllers/applicant/ApplicantInformationControllerTest.java
universal-application-tool-0.0.1/test/controllers/applicant/ApplicantProgramBlocksControllerTest.java
universal-application-tool-0.0.1/test/controllers/applicant/ApplicantProgramsControllerTest.java
universal-application-tool-0.0.1/test/controllers/applicant/WithMockedApplicantProfiles.java
universal-application-tool-0.0.1/test/repository/ProgramRepositoryTest.java
universal-application-tool-0.0.1/test/repository/QuestionRepositoryTest.java
universal-application-tool-0.0.1/test/repository/VersionRepositoryTest.java
universal-application-tool-0.0.1/test/repository/WithPostgresContainer.java
universal-application-tool-0.0.1/test/services/applicant/BlockTest.java
universal-application-tool-0.0.1/test/services/applicant/ReadOnlyApplicantProgramServiceImplTest.java
universal-application-tool-0.0.1/test/services/export/CsvExporterTest.java
universal-application-tool-0.0.1/test/services/program/BlockDefinitionTest.java
universal-application-tool-0.0.1/test/services/program/ProgramDefinitionTest.java
universal-application-tool-0.0.1/test/services/program/ProgramServiceImplTest.java
universal-application-tool-0.0.1/test/services/question/QuestionServiceImplTest.java
universal-application-tool-0.0.1/test/services/question/ReadOnlyQuestionServiceImplTest.java
universal-application-tool-0.0.1/test/support/ResourceCreator.java
universal-application-tool-0.0.1/test/support/TestQuestionBank.java
universal-application-tool-0.0.1/test/support/TestQuestionBankTest.java

There was a conflict in tests that used `TestQuestionBank`. The source of the problem was the `maybeSave` method, which attempted to `save` and catch errors if there was no database present. For some reason, this wasn't working well and caused tests to fail with a strange error when a test *with* a database was run sequentially after a test *without* a database.
The fix is to specify upon construction whether the `TestQuestionBank` `canSave` questions.
This bug was discovered in #812.

Bug fix: Update TestQuestionBank to use non-static methods

---

browser-test/src/support/admin_programs.ts
universal-application-tool-0.0.1/app/controllers/admin/AdminProgramController.java
universal-application-tool-0.0.1/app/controllers/dev/DatabaseSeedController.java
universal-application-tool-0.0.1/app/forms/ProgramForm.java
universal-application-tool-0.0.1/app/models/Program.java
universal-application-tool-0.0.1/app/services/LocalizationUtils.java
universal-application-tool-0.0.1/app/services/program/ProgramDefinition.java
universal-application-tool-0.0.1/app/services/program/ProgramService.java
universal-application-tool-0.0.1/app/services/program/ProgramServiceImpl.java
universal-application-tool-0.0.1/app/views/BaseHtmlView.java
universal-application-tool-0.0.1/app/views/admin/programs/ProgramEditView.java
universal-application-tool-0.0.1/app/views/admin/programs/ProgramFormBuilder.java
universal-application-tool-0.0.1/app/views/admin/programs/ProgramNewOneView.java
universal-application-tool-0.0.1/test/controllers/admin/AdminProgramControllerTest.java
universal-application-tool-0.0.1/test/repository/ApplicationRepositoryTest.java
universal-application-tool-0.0.1/test/repository/ProgramRepositoryTest.java
universal-application-tool-0.0.1/test/services/applicant/ApplicantServiceImplTest.java
universal-application-tool-0.0.1/test/services/program/ProgramDefinitionTest.java
universal-application-tool-0.0.1/test/services/program/ProgramServiceImplTest.java

1. The non-block information for a program now contains: `adminName`, `adminDescription`, `localizedName`, and `localizedDescription`
2. When an admin edits a program, the `adminName` is not an editable field - we use this name internally to find versions of programs
3. Up next: actually provide a way for admins to enter localized names and descriptions for supported languages
#777

Add `localizedName` and `localizedDescription` to the admin Program form

---

universal-application-tool-0.0.1/app/controllers/dev/DatabaseSeedController.java
universal-application-tool-0.0.1/app/services/question/types/MultiOptionQuestionDefinition.java
universal-application-tool-0.0.1/app/services/question/types/QuestionDefinition.java
universal-application-tool-0.0.1/app/views/admin/questions/QuestionsListView.java
universal-application-tool-0.0.1/test/forms/CheckboxQuestionFormTest.java
universal-application-tool-0.0.1/test/forms/DropdownQuestionFormTest.java
universal-application-tool-0.0.1/test/forms/MultiOptionQuestionFormTest.java
universal-application-tool-0.0.1/test/forms/RadioButtonQuestionFormTest.java
universal-application-tool-0.0.1/test/services/question/types/MultiOptionQuestionDefinitionTest.java
universal-application-tool-0.0.1/test/services/question/types/QuestionDefinitionTest.java

Allow an admin to quickly see which languages/locales are supported for a given question.
1. Adds a `getSupportedLanguages` method to `QuestionDefinition`
2. Adds a table column in the question list for supported locales
#221, #778

Display supported languages for each question in admin view

---

browser-test/browser-test-compose.yml
docker-compose.yml
universal-application-tool-0.0.1/conf/application.conf
universal-application-tool-0.0.1/conf/application.dev.conf
universal-application-tool-0.0.1/conf/application.test.conf

Fixing cookie related items in #837

Use secure cookies in prod

---

universal-application-tool-0.0.1/app/services/question/ReadOnlyQuestionService.java
universal-application-tool-0.0.1/app/services/question/ReadOnlyQuestionServiceImpl.java
universal-application-tool-0.0.1/app/services/question/types/QuestionDefinition.java
universal-application-tool-0.0.1/test/services/question/QuestionServiceImplTest.java
universal-application-tool-0.0.1/test/services/question/ReadOnlyQuestionServiceImplTest.java
universal-application-tool-0.0.1/test/services/question/types/QuestionDefinitionTest.java

Deleted:
* `QuestionDefinition#getScalarType(Path)`
* `ReadOnlyQuestionService#getAllScalars()`
* `ReadOnlyQuestionService#getPathScalars(Path)`
* `ReadOnlyQuestionService#getPathType(Path)`
* `ReadOnlyQuestionService#isValid(Path)`
This cleanup is being done in preparation for a large refactor required for #783.

Delete `QuestionDefinition#getScalarType` and `ReadOnlyQuestionService` methods that were only used in tests.

---

universal-application-tool-0.0.1/app/controllers/admin/AdminProgramController.java
universal-application-tool-0.0.1/app/controllers/applicant/ApplicantProgramBlocksController.java
universal-application-tool-0.0.1/app/forms/ApplicantInformationForm.java
universal-application-tool-0.0.1/app/forms/MultiOptionQuestionForm.java
universal-application-tool-0.0.1/app/forms/QuestionForm.java
universal-application-tool-0.0.1/app/models/Program.java
universal-application-tool-0.0.1/app/services/LocalizationUtils.java
universal-application-tool-0.0.1/app/services/applicant/ApplicantData.java
universal-application-tool-0.0.1/app/services/applicant/ReadOnlyApplicantProgramService.java
universal-application-tool-0.0.1/app/services/applicant/ReadOnlyApplicantProgramServiceImpl.java
universal-application-tool-0.0.1/app/services/applicant/question/ApplicantQuestion.java
universal-application-tool-0.0.1/app/services/applicant/question/MultiSelectQuestion.java
universal-application-tool-0.0.1/app/services/applicant/question/SingleSelectQuestion.java
universal-application-tool-0.0.1/app/services/program/ProgramDefinition.java
universal-application-tool-0.0.1/app/services/question/ReadOnlyQuestionServiceImpl.java
universal-application-tool-0.0.1/app/services/question/types/MultiOptionQuestionDefinition.java
universal-application-tool-0.0.1/app/services/question/types/QuestionDefinition.java
universal-application-tool-0.0.1/app/services/question/types/QuestionDefinitionBuilder.java
universal-application-tool-0.0.1/app/views/admin/questions/QuestionsListView.java
universal-application-tool-0.0.1/app/views/applicant/ApplicantProgramBlockEditView.java
universal-application-tool-0.0.1/conf/messages.en-US
universal-application-tool-0.0.1/conf/messages.es-US
universal-application-tool-0.0.1/test/services/applicant/ReadOnlyApplicantProgramServiceImplTest.java
universal-application-tool-0.0.1/test/services/applicant/question/MultiSelectQuestionTest.java
universal-application-tool-0.0.1/test/services/applicant/question/SingleSelectQuestionTest.java
universal-application-tool-0.0.1/test/services/question/types/QuestionDefinitionTest.java

Currently, we throw an error if a question cannot be displayed in an applicant's preferred locale. This changes this behavior by:
1. Set a global default locale for CiviForm and use across app
2. Add methods to `QuestionDefinition` to fall back to the default locale text
3. Update `ApplicantQuestion` to use new fallback methods
4. Add a method to `ReadOnlyApplicantService` to determine whether the given program fully supports the applicant's preferred locale
4. Display a toast message to applicants when they apply to a program that is not fully localized to their preferred language
Fixes #856

Fix i18n bug #856 - do not throw when locale not found

---

universal-application-tool-0.0.1/app/services/program/BlockDefinition.java
universal-application-tool-0.0.1/test/services/program/BlockDefinitionTest.java

We're trying to keep most/all `Path` related things in the `services.applicant` package or subpackages since a real `Path` should have applicant context. 
Also, this method isn't even being used.

Remove unused BlockDefinition#hasPaths

---

universal-application-tool-0.0.1/app/assets/javascripts/main.ts
universal-application-tool-0.0.1/app/views/questiontypes/RepeaterQuestionRenderer.java

Update `RepeaterQuestionRenderer` and add a typescript function for clicking the add field button.
The html form for the repeater question should have two parts: an array of string values for repeated entity name, and an array of repeated entities to delete, which is quite different from all of our other question types.
Fixes #705

Improve the repeater question renderer

---

universal-application-tool-0.0.1/app/services/question/ReadOnlyQuestionService.java
universal-application-tool-0.0.1/app/services/question/ReadOnlyQuestionServiceImpl.java

`ReadOnlyQuestionService` had methods to get and set the preferred locale - this is done in the applicant service, so these methods are unused.

Remove unused methods from ReadOnlyQuestionService

---

universal-application-tool-0.0.1/app/services/applicant/ApplicantData.java
universal-application-tool-0.0.1/app/services/applicant/ReadOnlyApplicantProgramServiceImpl.java
universal-application-tool-0.0.1/test/services/applicant/ApplicantDataTest.java
universal-application-tool-0.0.1/test/services/applicant/ReadOnlyApplicantProgramServiceImplTest.java

Add `ApplicantData#lock` and use it in `ReadOnlyApplicantProgramServiceImpl`.

Lock down `ApplicantData` in `ReadOnlyApplicantProgramServiceImpl`

---

universal-application-tool-0.0.1/app/repository/ProgramRepository.java
universal-application-tool-0.0.1/app/repository/VersionRepository.java

It's not beautiful but it does work!  It also fixes a sort of incipient problem - there's no transactionality around creating new drafts, so we need to be able to handle multiple drafts accidentally existing.  The first fix exposed that problem so I fixed that also.

dev/seed lists too many programs - make it list only active and draft ones

---

universal-application-tool-0.0.1/app/services/Path.java
universal-application-tool-0.0.1/app/services/applicant/ApplicantServiceImpl.java
universal-application-tool-0.0.1/app/services/applicant/question/Scalar.java
universal-application-tool-0.0.1/app/services/question/types/QuestionDefinition.java
universal-application-tool-0.0.1/test/controllers/applicant/ApplicantProgramBlocksControllerTest.java
universal-application-tool-0.0.1/test/services/PathTest.java
universal-application-tool-0.0.1/test/services/applicant/ApplicantServiceImplTest.java

`Scalar#name()` is more appropriate to use as keys in the JSON data.
Also makes and uses `Scalar#getMetadataScalarKeys()`.

Use Scalar#name instead of toString().toLowerCase().

---

browser-test/src/admin_program_translation.test.ts
browser-test/src/support/index.ts

Originally, we skipped the select language page for the test IDCS user. For now, we want to:
1. Check if we are on the select language page before selecting a language, and skip if not.
2. Use the guest if we want to force a particular language, since the test user already has preferred language set.

Check that we see the select language page before selecting a language

---

universal-application-tool-0.0.1/app/services/applicant/ApplicantData.java
universal-application-tool-0.0.1/test/services/applicant/ApplicantDataTest.java

Initially we had applicant data JSON structured like:
```
{
"applicant": {},
"metadata": {}
}
```
However a recent change made metadata live alongside applicant data answers (i.e., within the `"applicant"` object), so now this top-level `"metadata"` object is no longer needed.
Also create new constants that refers to the "applicant" path in the applicant data JSON.
Paired with @kendrickt on this.

Remove `"metadata"` from initial applicant data and put `"applicant"` in a constant

---

universal-application-tool-0.0.1/app/services/applicant/Block.java
universal-application-tool-0.0.1/app/services/applicant/ReadOnlyApplicantProgramService.java
universal-application-tool-0.0.1/app/services/applicant/ReadOnlyApplicantProgramServiceImpl.java
universal-application-tool-0.0.1/app/services/applicant/question/ApplicantQuestion.java
universal-application-tool-0.0.1/test/services/applicant/BlockTest.java
universal-application-tool-0.0.1/test/services/applicant/ReadOnlyApplicantProgramServiceImplTest.java

* Change the `Block` constructor to take a `contextualizedPath`.
* Expose new method `ReadOnlyApplicantProgramService#getAllBlocks`.
Works toward #783

Contextualize paths for `Block`s

---

universal-application-tool-0.0.1/app/controllers/applicant/ApplicantProgramBlocksController.java
universal-application-tool-0.0.1/app/services/applicant/ApplicantServiceImpl.java
universal-application-tool-0.0.1/app/services/applicant/Block.java
universal-application-tool-0.0.1/app/services/applicant/ProgramBlockNotFoundException.java
universal-application-tool-0.0.1/app/services/applicant/question/ApplicantQuestion.java
universal-application-tool-0.0.1/app/services/program/BlockDefinition.java
universal-application-tool-0.0.1/app/services/program/PathNotInBlockException.java
universal-application-tool-0.0.1/test/services/applicant/ApplicantServiceImplTest.java
universal-application-tool-0.0.1/test/services/applicant/BlockTest.java
universal-application-tool-0.0.1/test/services/applicant/question/ApplicantQuestionTest.java
universal-application-tool-0.0.1/test/services/program/BlockDefinitionTest.java

* Add new `Block#getScalarType` and `ApplicantQuestion#getContextualizedScalars`.
* Remove the concept of scalars and other unused methods from `BlockDefinition`.
* Add new `ApplicantServiceImpl.UpdateMetadata` AutoValue type.
Works toward #783
Paired with @kendrickt

Use `Block#getScalarType` instead of `BlockDefinition#getScalarType` to make updates to `ApplicantData`

---

infra/security_groups.yaml

At city's request, lb should only be accessible on the ports it serves traffic on.

Only allow accesses on ports 80 and 443.

---

universal-application-tool-0.0.1/app/services/applicant/ReadOnlyApplicantProgramService.java
universal-application-tool-0.0.1/app/services/applicant/ReadOnlyApplicantProgramServiceImpl.java
universal-application-tool-0.0.1/app/services/program/ProgramDefinition.java
universal-application-tool-0.0.1/test/services/applicant/ReadOnlyApplicantProgramServiceImplTest.java

Useful for displaying program title to applicants in #871.
Fixes #914

Add `ReadOnlyApplicantProgramService#getProgramTitle` method

---

universal-application-tool-0.0.1/test/controllers/applicant/WithMockedApplicantProfiles.java
universal-application-tool-0.0.1/test/support/ProgramBuilder.java

All tests that use `ProgramBuilder` have the database in scope, so I didn't add methods to allow using `ProgramBuilder` without the database in scope.
Instead, the change was to call `Program#save()` directly, without catching errors, and set the `ProgramBuilder#injector` in `WithMockedApplicantProfiles` tests.

Add injector to ProgramBuilder for WithMockedApplicantProfiles tests.

---

browser-test/src/dev_file_upload.test.ts

Temporarily disable fileupload probe in staging for emergent prod promotion.

Disable dev file upload in staging temporarily.

---

universal-application-tool-0.0.1/app/models/Models.java
universal-application-tool-0.0.1/test/app/BaseBrowserTest.java
universal-application-tool-0.0.1/test/controllers/applicant/ApplicantInformationControllerTest.java
universal-application-tool-0.0.1/test/controllers/applicant/ApplicantProgramBlocksControllerTest.java
universal-application-tool-0.0.1/test/controllers/applicant/ApplicantProgramsControllerTest.java
universal-application-tool-0.0.1/test/controllers/applicant/WithMockedApplicantProfiles.java
universal-application-tool-0.0.1/test/repository/WithPostgresContainer.java
universal-application-tool-0.0.1/test/support/Models.java
universal-application-tool-0.0.1/test/support/ResourceCreator.java

Instead of truncating a manually curated custom list, truncate from a shared global constant.
Almost everything needs an active version in the database, so `truncate` methods are renamed to `reset` if they create an active version.

Truncate all tables

---

universal-application-tool-0.0.1/test/app/SecurityBrowserTest.java

small change to make the error messages a bit more readable/consistent when things fail.

Don't use assertTrue in SecurityBrowserTest.

---

universal-application-tool-0.0.1/app/repository/ProgramRepository.java
universal-application-tool-0.0.1/app/repository/QuestionRepository.java
universal-application-tool-0.0.1/app/repository/VersionRepository.java

Removed the handle-after-the-fact of creating new drafts - which was sloppy and never desirable, it was a hack to avoid a problem I introduced - and instead use the normal database thing for that problem, which is transactions.  ebeans transactions aren't perfect, but they do work for this use case - `requiresNew` suspends a parent transaction which can be revived after the fact.
Addresses the problem referenced here:
https://civiform.slack.com/archives/C02022VFNCF/p1619731485002800

Ensure transactionality of creating new drafts.

---

universal-application-tool-0.0.1/app/controllers/applicant/ApplicantInformationController.java

Secure applicant language selection page.
If an applicant clears the cookies, they should be redirected to login page again. Without this guard, the server throws an error.

Secure applicant language selection page

---

universal-application-tool-0.0.1/app/services/applicant/question/AddressQuestion.java
universal-application-tool-0.0.1/app/services/applicant/question/Scalar.java
universal-application-tool-0.0.1/test/services/applicant/ReadOnlyApplicantProgramServiceImplTest.java
universal-application-tool-0.0.1/test/services/applicant/question/AddressQuestionTest.java
universal-application-tool-0.0.1/test/support/QuestionAnswerer.java
universal-application-tool-0.0.1/test/support/QuestionAnswererTest.java

… value in QuestionAnswerer and read its value in AddressQuestion.
* Add ability to set the address line 2 value in `QuestionAnswerer`
* Add ability to read the address line 2 value in `AddressQuestion`
To satisfy #844, we still need to make changes to the address question renderer and form binding, as well as include it in the PO box validation check (see TODO in `AddressQuestion`).
Works toward #844

Add new `Scalar.LINE2` for Address question type and ability to read and write its value

---

infra/containers.yaml
infra/load_balancer.yaml
infra/stack.yaml

Each load balancer rule can only use one certificate.  This will mean people accessing seattle.civiform.com will get an SSL error - is that okay, do you think?  Or should I pursue another solution?

Use civiform.seattle.gov certificate instead of seattle.civiform.com.

---

universal-application-tool-0.0.1/conf/application.conf

If you set the "DATABASE_APPLY_DESTRUCTIVE_CHANGES" in the environment variable console, the destructive changes will be automatically applied.

Allow us to configure auto-apply-down in the environment variables.

---

universal-application-tool-0.0.1/app/auth/AdfsProfileAdapter.java
universal-application-tool-0.0.1/app/auth/IdcsProfileAdapter.java
universal-application-tool-0.0.1/app/auth/UatProfileAdapter.java
universal-application-tool-0.0.1/app/modules/SecurityModule.java

This is pretty confusing, sorry.
The token that we receive back from IDCS is signed by the server we redirected the user to.  This is for good, obvious security reasons - if anybody could just post whatever login data they wanted, we'd be vulnerable to people sending us callbacks that didn't reflect genuinely successful logins (if they could, for instance, intercept the outgoing redirect which sets the nonce).
So, there's a signing key which the server uses to prove that it is genuinely itself sending us a genuine login.  The only way to be sure we have the right key is for us to request it from the server.  This is all part of the spec and should be handled entirely behind the scenes.
IDCS, for no good reason, introduces an authentication check in order to fetch this (public) key.  This …

Use access token to get jwt in prod.

---

universal-application-tool-0.0.1/conf/application.conf

This prevents the issue described in this long slack thread: https://civiform.slack.com/archives/C02022VFNCF/p1620100996051500.
tl;dr: if one statement in an evolution is broken, we should wind up as if it were never applied, not with it partially applied.  This make cleanup easier and safer.

Use transactions to apply evolutions so we don't ever wind up unable to access the DB.

---

browser-test/src/dev_file_upload.test.ts

This test is flaky and it is testing a dev page that is not critical. Since it is causing more harm than providing value, removing the test. We will have the actual file upload question ready soon so this is fine.

Remove dev_file_upload download test

---

universal-application-tool-0.0.1/app/services/program/BlockDefinition.java

Rollback the BlockDefinition JsonProperty changes that break production from #986

Go back to using repeaterId in BlockDefinition json properties.

---

bin/list-incomplete-messages

Add a bash script to diff the message translation files. 
Without any arguments, this script will generate a diff of each localized message
file with the default `messages` file. Missing translations will be presented
first, followed by weird stuff. The weird stuff may be
1. message keys in the localized file that do not exist in the default file
2. duplicated message keys
You can run this script with a single argument like "en-US" which will generate the
diff of just that one translation.
Example output:
List all the missing messages
List missing messages for one localization
File not found message
Fixes #983

List the incomplete translation messages!

---

universal-application-tool-0.0.1/app/services/applicant/ApplicantService.java
universal-application-tool-0.0.1/app/services/applicant/ApplicantServiceImpl.java

Allow creating a RO applicant program service from an application, which has a snapshot of applicant data, and a program associated with it.
Progress towards #665

RO applicant program service from an application

---

bin/build-and-push
bin/deploy-prod
bin/deploy-staging

Wait for 15mins instead of default 10mins (40 * 15 secs)

Wait staging to stabilize before running prober

---

browser-test/src/admin_program_translation.test.ts
universal-application-tool-0.0.1/app/controllers/admin/QuestionController.java

When any part of a question was edited, it would overwrite the entire translation map for question text and help text. This merges the existing localizations with the new ones, so that we don't lose all the translation work on a question if (for example) the description is updated.
Fixes #1021

Stop clobbering translations when questions are edited

---

universal-application-tool-0.0.1/app/services/applicant/Block.java
universal-application-tool-0.0.1/app/services/applicant/ReadOnlyApplicantProgramServiceImpl.java
universal-application-tool-0.0.1/app/services/applicant/RepeatedEntity.java
universal-application-tool-0.0.1/test/services/applicant/BlockTest.java
universal-application-tool-0.0.1/test/services/applicant/ReadOnlyApplicantProgramServiceImplTest.java
universal-application-tool-0.0.1/test/support/TestQuestionBank.java

Blocks now has a list of the (nested) repeated entities associated with it. This should be helpful for styling applicant views, and giving more context to the summary page, and csv export.
Progress towards #665

More enumerator/repeated context in block

---

universal-application-tool-0.0.1/app/repository/ProgramRepository.java
universal-application-tool-0.0.1/test/repository/ProgramRepositoryTest.java

This prevents people from guessing draft program slugs or getting errors when several versions of a program exist.
The test is a little weird but it's meant to simulate the migration from v19 to v20.

Deeplinking: only return active programs.

---

universal-application-tool-0.0.1/app/controllers/LoginController.java
universal-application-tool-0.0.1/app/modules/SecurityModule.java

This will ensure we can tell whether a user is meant to be a UAT admin or program admin - once it is configured on the ADFS side.  It's a no-op for now.

Ensure that we request roles from ADFS.

---

universal-application-tool-0.0.1/app/models/Account.java
universal-application-tool-0.0.1/conf/evolutions/default/21.sql
universal-application-tool-0.0.1/test/models/AccountTest.java

1. `Account` has an array of program names of programs they administer
2. Create a [GIN index](https://www.compose.com/articles/take-a-dip-into-postgresql-arrays/) on `admin_of` so that querying which programs are administered by which account is cheaper
Worked with @ndmckinley

Accounts have names of programs they administer

---

universal-application-tool-0.0.1/app/repository/ProgramRepository.java
universal-application-tool-0.0.1/test/repository/ProgramRepositoryTest.java

This makes sure we can track which program admins should be allowed to administer a given program as the versions increment, without relying on flaky transaction logic.

Return all administrators of a given program - independent of version.

---

universal-application-tool-0.0.1/app/services/program/ProgramQuestionDefinition.java
universal-application-tool-0.0.1/app/services/question/QuestionOption.java

We don't need @JsonIgnore on properties that Jackson doesn't automatically detect as getters.

Remove unnecessary JsonIgnore

---

browser-test/package.json

Prober frequently times out, increase the timeout limit to match test.

Increase prober timeout

---

browser-test/src/application_csv_download.test.ts
universal-application-tool-0.0.1/app/services/applicant/AnswerData.java
universal-application-tool-0.0.1/app/services/applicant/ApplicantServiceImpl.java
universal-application-tool-0.0.1/app/services/applicant/ReadOnlyApplicantProgramServiceImpl.java
universal-application-tool-0.0.1/app/services/export/CsvExporter.java
universal-application-tool-0.0.1/app/services/export/ExporterService.java
universal-application-tool-0.0.1/test/services/applicant/ReadOnlyApplicantProgramServiceImplTest.java
universal-application-tool-0.0.1/test/services/export/CsvExporterTest.java
universal-application-tool-0.0.1/test/support/ProgramBuilder.java

Update the CSV exporter to handle repeated answers.
NOTE: the CSV will not include answers to enumerator questions. The entity names picked by the applicant shouldn't matter to the admins.
Progress towards #665

Feature 665 - Export repeated data in CSVs

---

universal-application-tool-0.0.1/app/repository/ProgramRepository.java
universal-application-tool-0.0.1/app/repository/QuestionRepository.java
universal-application-tool-0.0.1/app/repository/VersionRepository.java
universal-application-tool-0.0.1/test/repository/VersionRepositoryTest.java

This creates a new transaction, suspends the one that's pending, and ensures that the pending one is reactivated when we return from this function.

Transactionality of drafts

---

universal-application-tool-0.0.1/app/assets/javascripts/main.ts
universal-application-tool-0.0.1/app/controllers/admin/ProgramAdminManagementController.java
universal-application-tool-0.0.1/app/models/Account.java
universal-application-tool-0.0.1/app/views/admin/programs/ManageProgramAdminsView.java
universal-application-tool-0.0.1/app/views/admin/programs/ProgramIndexView.java
universal-application-tool-0.0.1/app/views/components/FieldWithLabel.java
universal-application-tool-0.0.1/app/views/style/ReferenceClasses.java
universal-application-tool-0.0.1/conf/routes
universal-application-tool-0.0.1/test/controllers/admin/ProgramAdminManagementControllerTest.java
universal-application-tool-0.0.1/test/models/AccountTest.java
universal-application-tool-0.0.1/test/views/components/FieldWithLabelTest.java

1. Adds a "Manage Admins" link on each program card for the CiviForm admin index view
1. Implements `ManageProgramAdminsController#edit`
2. Adds a `ManageProgramAdminsView` that provides email inputs for UAT admins to add or remove program admins on a given program
3. Updates our TypeScript to make the add/remove input functions re-usable
#1051

Render a view for managing program admins for a given program

---

universal-application-tool-0.0.1/app/repository/ProgramRepository.java
universal-application-tool-0.0.1/app/services/program/ProgramService.java
universal-application-tool-0.0.1/app/services/program/ProgramServiceImpl.java
universal-application-tool-0.0.1/test/repository/ProgramRepositoryTest.java
universal-application-tool-0.0.1/test/services/program/ProgramServiceImplTest.java

With versioning, list all programs are not useful. Getting all programs regardless versions is at best misleading, if not causing any harm. The method is only used in test so it is safe to remove.

Remove list all programs

---

browser-test/src/admin_program_admins.test.ts
browser-test/src/support/admin_programs.ts
universal-application-tool-0.0.1/app/repository/UserRepository.java
universal-application-tool-0.0.1/test/repository/UserRepositoryTest.java

1. If an account for a given email address is not present, we create a new one. This allows the CiviForm admin to designate program admins before those PAs have logged in for the first time (i.e. they do not have an account yet)
2. Adds a browser test to verify we can add admins and they will still be there when we view them again
#1051

Allow an admin to add program admins before they have logged in

---

browser-test/src/support/admin_questions.ts
browser-test/src/support/applicant_questions.ts
universal-application-tool-0.0.1/app/forms/EnumeratorQuestionForm.java
universal-application-tool-0.0.1/app/services/question/types/EnumeratorQuestionDefinition.java
universal-application-tool-0.0.1/app/services/question/types/QuestionDefinitionBuilder.java
universal-application-tool-0.0.1/app/views/admin/questions/QuestionConfig.java
universal-application-tool-0.0.1/app/views/questiontypes/ApplicantQuestionRendererFactory.java
universal-application-tool-0.0.1/test/forms/EnumeratorQuestionFormTest.java
universal-application-tool-0.0.1/test/services/question/types/QuestionDefinitionBuilderTest.java
universal-application-tool-0.0.1/test/views/admin/question/QuestionConfigTest.java

Allow the admin to configure a custom entity type name for enumerator questions. This adds a field to the question form and pipes it through.

Allow admins to configure the entity name for enumerator questions

---

universal-application-tool-0.0.1/app/auth/AdfsProfileAdapter.java
universal-application-tool-0.0.1/app/auth/Authorizers.java
universal-application-tool-0.0.1/app/auth/IdcsProfileAdapter.java
universal-application-tool-0.0.1/app/auth/ProfileFactory.java
universal-application-tool-0.0.1/app/auth/UatProfile.java
universal-application-tool-0.0.1/app/auth/UatProfileAdapter.java
universal-application-tool-0.0.1/app/controllers/CiviFormController.java
universal-application-tool-0.0.1/app/controllers/HomeController.java
universal-application-tool-0.0.1/app/controllers/admin/AdminApplicationController.java
universal-application-tool-0.0.1/app/controllers/admin/AdminProgramController.java
universal-application-tool-0.0.1/app/controllers/admin/ProgramAdminController.java
universal-application-tool-0.0.1/app/models/Account.java
universal-application-tool-0.0.1/app/modules/SecurityModule.java
universal-application-tool-0.0.1/app/repository/ProgramRepository.java
universal-application-tool-0.0.1/app/repository/UserRepository.java
universal-application-tool-0.0.1/app/services/role/RoleService.java
universal-application-tool-0.0.1/app/views/admin/programs/ProgramAdministratorProgramListView.java
universal-application-tool-0.0.1/app/views/admin/programs/ProgramIndexView.java
universal-application-tool-0.0.1/conf/application.conf
universal-application-tool-0.0.1/conf/evolutions/default/25.sql
universal-application-tool-0.0.1/conf/routes

This adds the view for admins (program and global) to view / download applications.
It also does all the auth plumbing.  the rule is that if there are any admins assigned to a program, global admins are not able to view applications.  If there are no admins assigned to a program, global admins are the fallback - they can view the applications.
Global admin state is extracted from ADFS membership in a particular group.  That group is currently configured to be the TEST version of the city's ADFS group for admins, but we'll swap it to prod (in prod) shortly before go-live.

Program Admins (views and auth)

---

universal-application-tool-0.0.1/app/views/components/FieldWithLabel.java

This fixes a potential bug that I introduced in a previous PR.
The `id` attribute is no longer defaults to the `name` attribute, and `for` is only set if the `id` attribute is specified.
Before this PR, if no ID was set on a `FieldWithLabel`, then `FieldWithLabel` tried to be clever by setting the `id` to whatever the `name` was. At the same time, the `id` was used to register the `for` attribute on the `label`.
The problem was If the caller of `FieldWithLabel` had set the same `name` for multiple fields in the same page (and not set unique IDs for them), then multiple fields would have the same `id`, and then clicking the label of one might end up triggering another field. Normally, having more than one field with the same `name` doesn't make sense, but this is how form binding works for …

Don't set `id` in `FieldWithLabel` if it wasn't explicitly set

---

infra/containers.yaml
infra/stack.yaml
universal-application-tool-0.0.1/app/views/BaseHtmlLayout.java
universal-application-tool-0.0.1/app/views/admin/AdminLayout.java
universal-application-tool-0.0.1/app/views/applicant/ApplicantLayout.java
universal-application-tool-0.0.1/conf/application.conf

Enable Google Analytics measurement ID to be defined in containers.yaml
Fixes #1100

Enables Google Analytics measurement ID to be defined in containers.yaml

---

universal-application-tool-0.0.1/app/auth/AdfsProfileAdapter.java

Prod instance is returning null pointer when we get group. This print all attributes ADFS returns in prod.

Log ADFS attributes for debug

---

universal-application-tool-0.0.1/app/services/MessageKey.java
universal-application-tool-0.0.1/app/services/applicant/question/EnumeratorQuestion.java
universal-application-tool-0.0.1/conf/messages
universal-application-tool-0.0.1/test/services/applicant/question/EnumeratorQuestionTest.java

Enumerator question validation now makes sure applicant-provided entity names are unique.

Require unique entity names

---

.gitignore
bin/breakglass-db-access

- The database is in private subnets so we need to create an EC2 instance in a public subnet and relay our access to it
- We create a new security group allowing only our own IP and attach it to the DB security group ingress
- Create a new key pair for the EC2 instance and store private key locally
- Launch the instance in the public subnet with the new security group, wait for it, and connect to it
- Install `psql` client in the new instance and use it to access the database
- Clean up everything after the access
- The script connects to staging right now, not prod

Enable ability to breakglass access AWS database

---

universal-application-tool-0.0.1/app/controllers/applicant/ApplicantProgramBlocksController.java
universal-application-tool-0.0.1/app/services/applicant/ReadOnlyApplicantProgramService.java
universal-application-tool-0.0.1/app/services/applicant/ReadOnlyApplicantProgramServiceImpl.java
universal-application-tool-0.0.1/app/views/applicant/ApplicantProgramBlockEditView.java
universal-application-tool-0.0.1/test/services/applicant/ReadOnlyApplicantProgramServiceImplTest.java

* Update the `ReadOnlyApplicantProgramService` interface to provide the index of a block (rather than the percentage, which is more of a UI-oriented detail that can be computed from the index and size of block list)
* Change the formula for computing the percentage. Add one to both the index and the total block count (see code comments for why).
This update will also be useful for showing, e.g, "3 of 10" as shown in the new UX mocks. Will add this UI feature in a separate PR.

Update the way we compute "completion percentage"

---

browser-test/src/security.test.ts
universal-application-tool-0.0.1/app/auth/UatProfile.java
universal-application-tool-0.0.1/test/auth/UatProfileTest.java

Remove the permission for admins to access all applicant's pages.

Admins aren't meant to access all applicants anymore.

---

infra/containers.yaml
universal-application-tool-0.0.1/app/services/applicant/ApplicantServiceImpl.java
universal-application-tool-0.0.1/app/services/aws/SimpleEmail.java
universal-application-tool-0.0.1/app/services/program/ProgramService.java
universal-application-tool-0.0.1/app/services/program/ProgramServiceImpl.java
universal-application-tool-0.0.1/test/services/program/ProgramServiceImplTest.java

- Notify real program admins instead of a static mailing list
- Notify global admin if no program admins are configured
- Use @seattle.gov email domain in prod
#193

Notify program admins

---

universal-application-tool-0.0.1/app/services/applicant/RepeatedEntity.java
universal-application-tool-0.0.1/app/services/applicant/question/ApplicantQuestion.java
universal-application-tool-0.0.1/test/services/applicant/question/ApplicantQuestionTest.java
universal-application-tool-0.0.1/test/support/TestQuestionBank.java

Question text and help text can be contextualized by the question's repeated entity by using `$this` and `$this.parent` (and `this.parent.parent`, ad infinitum) in the admin-configured strings.
Progress towards #1083

Contextualize applicant question text and help text with its repeated entity

---

browser-test/src/application_csv_download.test.ts
browser-test/src/application_review.test.ts
browser-test/src/end_to_end_enumerators.test.ts
browser-test/src/support/applicant_questions.ts
universal-application-tool-0.0.1/app/assets/javascripts/radio.ts
universal-application-tool-0.0.1/app/services/applicant/ReadOnlyApplicantProgramServiceImpl.java
universal-application-tool-0.0.1/app/services/applicant/question/ApplicantQuestion.java
universal-application-tool-0.0.1/app/views/BaseHtmlView.java
universal-application-tool-0.0.1/app/views/applicant/ApplicantProgramBlockEditView.java
universal-application-tool-0.0.1/app/views/applicant/ProgramIndexView.java
universal-application-tool-0.0.1/app/views/components/FieldWithLabel.java
universal-application-tool-0.0.1/app/views/questiontypes/AddressQuestionRenderer.java
universal-application-tool-0.0.1/app/views/questiontypes/ApplicantQuestionRenderer.java
universal-application-tool-0.0.1/app/views/questiontypes/CheckboxQuestionRenderer.java
universal-application-tool-0.0.1/app/views/questiontypes/DropdownQuestionRenderer.java
universal-application-tool-0.0.1/app/views/questiontypes/EnumeratorQuestionRenderer.java
universal-application-tool-0.0.1/app/views/questiontypes/FileUploadQuestionRenderer.java
universal-application-tool-0.0.1/app/views/questiontypes/NameQuestionRenderer.java
universal-application-tool-0.0.1/app/views/questiontypes/NumberQuestionRenderer.java
universal-application-tool-0.0.1/app/views/questiontypes/RadioButtonQuestionRenderer.java
universal-application-tool-0.0.1/app/views/questiontypes/TextQuestionRenderer.java
universal-application-tool-0.0.1/app/views/style/ApplicantStyles.java
universal-application-tool-0.0.1/app/views/style/BaseStyles.java
universal-application-tool-0.0.1/conf/messages
universal-application-tool-0.0.1/conf/messages.en-US
universal-application-tool-0.0.1/conf/messages.es-US
universal-application-tool-0.0.1/tailwind.config.js
universal-application-tool-0.0.1/test/controllers/applicant/ApplicantProgramBlocksControllerTest.java

Previously each question type's renderer was rendering its own question text, help text, and errors. This puts all of that logic in a common `ApplicantQuestionRenderer#renderInternal` method.
Based on Figma mocks. Also slightly improve Block and question error rendering.
Works toward #1016

Standardize the way questions are rendered

---

universal-application-tool-0.0.1/app/services/applicant/AnswerData.java
universal-application-tool-0.0.1/app/services/applicant/ReadOnlyApplicantProgramServiceImpl.java
universal-application-tool-0.0.1/app/services/applicant/RepeatedEntity.java
universal-application-tool-0.0.1/app/views/applicant/ApplicantProgramSummaryView.java

Put sections with repeated entity names before each group of repeated entity answers.
Fixes #1083

Put repeated entity context in applicant summary review page.

---

browser-test/src/admin_program_creation.test.ts
universal-application-tool-0.0.1/app/repository/QuestionRepository.java
universal-application-tool-0.0.1/test/repository/QuestionRepositoryTest.java

This is a stopgap to prevent civiform from breaking by changing `QuestionRepository#findConflictingQuestion` to include questions with question name collisions.
I think we should allow name collisions, but the `ActiveAndDraftQuestions` rely on unique names and we can address that later.
Stopgap for #1163

Temporary fix to #1163 by not allowing name collisions

---

infra/containers.yaml

See long conversation in #prod-issues starting with https://civiform.slack.com/archives/C02022VFNCF/p1621273583148200.
Tested in staging, works there.

YAML doesn't escape backslashes the same way as JSON.

---

browser-test/src/support/admin_programs.ts
universal-application-tool-0.0.1/app/views/BaseHtmlView.java
universal-application-tool-0.0.1/app/views/applicant/ProgramIndexView.java
universal-application-tool-0.0.1/build.sbt
universal-application-tool-0.0.1/test/views/BaseHtmlViewTest.java

Extract urls, use their exact text (but their expanded url) using the normal linkedin library that does this exact thing we want.
Fixes #886.

Display URLs correctly in program view.

---

universal-application-tool-0.0.1/app/services/question/types/MultiOptionQuestionDefinition.java
universal-application-tool-0.0.1/app/services/question/types/QuestionDefinition.java
universal-application-tool-0.0.1/test/services/question/types/QuestionDefinitionTest.java

Admins were being sent a 500 if they didn't add options to multi option questions.
Now they get a validation toast if a multi-option question has no options, or it has blank ones.

Don't throw a runtime exception when a multi-option question has no options

---

universal-application-tool-0.0.1/app/repository/ProgramRepository.java
universal-application-tool-0.0.1/app/repository/QuestionRepository.java

Right now, the program update can't see the updated question, since the transactions are running in parallel.  This makes it so they CAN see each other because the program update runs as a savepoint nested inside the question update.
Proof:
```
civiform      | [debug] io.ebean.SUM - txn[1254] sp[0] Updated [Program] [12]                                                                                                                             
civiform      | [debug] io.ebean.TXN - txn[1254] sp[0] Commit                                                                                                                                             
civiform      | [debug] io.ebean.TXN - txn[1254] Commit
```
(`sp[0]` stands for "savepoint 0", you can see it's part of transaction 1254, which then …

Just use a savepoint for our nested transactions.

---

universal-application-tool-0.0.1/app/auth/AdfsProfileAdapter.java
universal-application-tool-0.0.1/app/auth/IdcsProfileAdapter.java
universal-application-tool-0.0.1/app/auth/ProfileFactory.java
universal-application-tool-0.0.1/app/auth/UatProfileAdapter.java

Right now you're a global admin as you first log in because we automatically create a new admin account for you.
After this change we don't do that - instead we make the right account for you.
Also a little cleanup.  I never liked that we did mutations during the `getRoles` call, gross - now it's extracted a little.
Thanks to @hmhsu for finding it.

Make people the right amount of admin.

---

universal-application-tool-0.0.1/app/controllers/admin/AdminQuestionTranslationsController.java
universal-application-tool-0.0.1/app/services/question/types/QuestionDefinition.java
universal-application-tool-0.0.1/app/views/admin/questions/QuestionTranslationView.java
universal-application-tool-0.0.1/test/services/question/types/QuestionDefinitionTest.java

1. Only shows the help text localization input if there is help text to localize
2. A question is considered to support a locale if
a. It has help text and both question text and help text support the locale OR
b. It does not have help text and the question text supports the locale
Fixes #1186

Help text should be optional when translating

---

bin/list-incomplete-messages

Not sure why but unix doesn't like the regex used.
In unix, 
`echo " 1111" | grep -o 1*` doesn't work, but `echo " 1111" | grep -o 11*` does work. :confused: 
So the regex is changed from `[^<]*` to `[^<][a-zA-Z.]*`

Make greps for finding missing and weird translations unix compatible.

---

prod.Dockerfile

we have no root cause for this, but it seemed to be related to finding application.conf.
a search of the internet suggests that play's many mechanisms for building a
distributable version of an application often fail to find application.conf.
We don't know why it failed in this case, but the play docs recommend providing
the config.file parameter on the command line just in case.  It happens to work.

Around 10 am today, our docker builds started failing.

---

prod.Dockerfile

`adoptopenjdk/openjdk11:alpine-slim` updates frequently and is unstable, i.e. it broke us today terribly, change to a fixed version

Fixed our docker base image

---

universal-application-tool-0.0.1/app/assets/javascripts/preview.ts

Add regex `/(\$this(\.parent)*)/g` and use it to highlight matching strings in the preview text and help text divs. It does not use `innerHTML` so raw html won't get rendered.
Fixes #1198

Add a regex for \$this and \$this.parent etc etc to highlight it in preview.ts

---

universal-application-tool-0.0.1/app/auth/IdcsProfileAdapter.java

It's not a _great_ theory, but it would explain the transience.  One thread can affect the resource retriever used by another thread here - as noted by the comment about thread safety - but one thing I forgot to consider was that if an invalid redirect happened, we might not have the creds we expected and so might break the resource retriever.
Even if wrong, it should be safe anyway.

My current best theory for the root cause of the 401s earlier today.

---

universal-application-tool-0.0.1/app/services/question/types/QuestionDefinitionBuilder.java
universal-application-tool-0.0.1/test/services/question/types/QuestionDefinitionBuilderTest.java

Enumerator question's entity type was being lost during a `QuestionService.update(QuestionDefinition)` because the `QuestionDefinitionBuilder(QuestionDefinition)` constructor was not using the input `QuestionDefinition`'s entity type.

Set question entity type when builder a question definition from a question definition.

---

universal-application-tool-0.0.1/app/services/MessageKey.java
universal-application-tool-0.0.1/app/views/applicant/ApplicantInformationView.java
universal-application-tool-0.0.1/app/views/style/ApplicantStyles.java
universal-application-tool-0.0.1/conf/messages

* Put the select label in the actual label - this is good for a11y, connecting the form field label with the form input.
* Added some padding
* Updated button style
Mobile
Desktop

Slight style improvements to "select a language" page

---

universal-application-tool-0.0.1/app/views/admin/questions/QuestionEditView.java

When creating a new question, the name field was being locked down if the admin tried to create an invalid question. Now the name field is locked when it isn't for question creation.
Fixes #1099

Don't lock down the name field when creating a new question.

---

browser-test/src/admin_program_translation.test.ts
browser-test/src/support/admin_translations.ts
universal-application-tool-0.0.1/app/controllers/admin/AdminQuestionController.java
universal-application-tool-0.0.1/app/controllers/admin/AdminQuestionTranslationsController.java
universal-application-tool-0.0.1/app/forms/translation/EnumeratorQuestionTranslationForm.java
universal-application-tool-0.0.1/app/forms/translation/MultiOptionQuestionTranslationForm.java
universal-application-tool-0.0.1/app/services/question/types/QuestionDefinitionBuilder.java
universal-application-tool-0.0.1/app/views/admin/questions/QuestionTranslationView.java
universal-application-tool-0.0.1/test/forms/translation/EnumeratorQuestionTranslationFormTest.java

1. Allows an admin to localize the enumerator entity type name (i.e. the text that appears as "Add **entity**" and similar)
2. Adds an `EnumeratorQuestionTranslationForm` to capture changes made to the entity name

Add ability for admin to translate enumerator entity

---

universal-application-tool-0.0.1/app/auth/IdcsProfileAdapter.java

This way we can make sure that we're fetching the key while this token is active, and caching it indefinitely.

Maybe we should try caching this key and fetching it only once per server

---

browser-test/src/support/applicant_questions.ts
universal-application-tool-0.0.1/app/services/MessageKey.java
universal-application-tool-0.0.1/app/views/applicant/ApplicantLayout.java
universal-application-tool-0.0.1/app/views/applicant/ApplicantUpsellCreateAccountView.java
universal-application-tool-0.0.1/app/views/style/ApplicantStyles.java
universal-application-tool-0.0.1/conf/messages
universal-application-tool-0.0.1/conf/messages.en-US
universal-application-tool-0.0.1/conf/messages.es-US

Edited the text and styles of this page.
Still needs work: It's kind of a confusing user experience that this page is shown _before_ the "application confirmation" page. I think we should try to show this info and these buttons _on_ the confirmation page (combine both into one). That will be done as a follow-up.

Update the look of the "upsell" account creation page

---

browser-test/src/end_to_end_enumerators.test.ts
browser-test/src/support/admin_questions.ts
browser-test/src/support/applicant_questions.ts
universal-application-tool-0.0.1/app/repository/QuestionRepository.java
universal-application-tool-0.0.1/app/repository/VersionRepository.java

When we create a new version of an enumerator question, we want to update all references to it in its repeated questions and update programs that contain the repeated questions besides just updating the enumerator question itself. If we don't do this, old version of the enumerator becomes obsolete in the next version (when we hit publish all programs next time), and the server throws an error because it cannot find a valid enumerator question definition in the current active (and draft) version.

Update repeated questions and programs when enumerator question has a new draft

---

universal-application-tool-0.0.1/app/views/questiontypes/DateQuestionRenderer.java

Previously, date questions were being rendered in an inconsistent way from the other questions.
Works toward #1016

Update `DateQuestionRenderer` to use the `ApplicantQuestionRenderer#renderInternal`

---

browser-test/src/end_to_end_enumerators.test.ts
browser-test/src/support/admin_programs.ts
universal-application-tool-0.0.1/app/views/admin/programs/ProgramBlockEditView.java

An enumerator block cannot be deleted from a program if it has repeated blocks. Similarly, the enumerator question cannot be removed from the block if there are still repeated blocks.
#1259 
Block able to be removed
Block not able to be removed (delete button grayed out, enumerator question button also grayed out)

Fix enumerator block delete issue

---

universal-application-tool-0.0.1/app/services/Path.java
universal-application-tool-0.0.1/app/services/applicant/predicate/ConcretePredicateExpressionNode.java
universal-application-tool-0.0.1/app/services/applicant/predicate/LeafOperationExpressionNode.java
universal-application-tool-0.0.1/app/services/applicant/predicate/Operator.java
universal-application-tool-0.0.1/app/services/applicant/predicate/PredicateExpressionNode.java
universal-application-tool-0.0.1/app/services/applicant/predicate/PredicateExpressionNodeType.java
universal-application-tool-0.0.1/app/services/applicant/predicate/PredicateValue.java
universal-application-tool-0.0.1/app/views/admin/questions/QuestionTranslationView.java
universal-application-tool-0.0.1/test/services/applicant/predicate/LeafOperationExpressionNodeTest.java

Adds initial data classes for block show/hide logic, including:
1. `PredicateExpressionNodeType` - the type of expression node (either AND, OR, or LEAF)
1. `PredicateExpressionNode` - acts as a oneof for AND, OR, and LEAF nodes
2. `LeafOperatorExpressionNode` - a single JsonPath expression on a single question
4. `PredicateValue` - a class for formatting values as JsonPath expression value strings
5. `Operator` - an enum for JsonPath operators
#1001

Create initial data classes for predicates

---

browser-test/src/admin_program_translation.test.ts
universal-application-tool-0.0.1/app/services/program/ProgramServiceImpl.java
universal-application-tool-0.0.1/test/services/program/ProgramServiceImplTest.java

Program names NEED to be unique for `ActiveAndDraftProgram`, but the `ProgramService` was not checking that they were unique. Now it does.

Require unique program names.

---

universal-application-tool-0.0.1/app/auth/FakeAdminClient.java
universal-application-tool-0.0.1/app/auth/ProfileFactory.java

This makes a new admin properly rather than using the test path.
This was preventing any new (blank) non-global admins from signing in.

Fake code used for tests was accidentally being called from prod.

---

universal-application-tool-0.0.1/app/views/admin/programs/ProgramBlockEditView.java

The form was moved into a modal, but it never got deleted. It was completely unused.

Delete unused `blockInfoForm` variable.

---

universal-application-tool-0.0.1/app/views/admin/programs/ProgramApplicationListView.java
universal-application-tool-0.0.1/app/views/admin/programs/ProgramApplicationView.java

I looked through and the only controller methods raising UnsupportedOperationException is the PDF download one and the profile page one, and we never link to the profile page.  Just stick a hidden tag on these to make them easy to put back if the time comes.
Fixes #1106.

Hide PDF buttons.

---

browser-test/src/admin_program_admins.test.ts

My current theory is that the selector is too generic that when the page loads, before styles are applied (we've seen this happened elsewhere), the selector selects the hidden template (wrong element) and thus fails the assertion. Using a more specific selector appears to work. Tested in staging with 10 successful runs.

Deflake program admin browser test

---

universal-application-tool-0.0.1/app/services/applicant/predicate/PredicateEvaluator.java
universal-application-tool-0.0.1/app/services/program/predicate/AndNode.java
universal-application-tool-0.0.1/app/services/program/predicate/OrNode.java
universal-application-tool-0.0.1/app/services/program/predicate/PredicateExpressionNode.java
universal-application-tool-0.0.1/test/services/applicant/predicate/PredicateEvaluatorTest.java

1. Adds `AndNode` and `OrNode` definitions
2. Implements evaluation logic in `PredicateEvaluator`
#1001

Implement AND and OR nodes on the backend

---

browser-test/package.json
browser-test/src/admin_dropdown_create_and_edit.test.ts
browser-test/src/admin_program_admins.test.ts
browser-test/src/application_csv_download.test.ts
browser-test/src/application_review.test.ts
browser-test/src/end_to_end_enumerators.test.ts
browser-test/src/support/admin_programs.ts
browser-test/src/support/admin_questions.ts
browser-test/src/support/applicant_questions.ts
browser-test/src/ti_group.test.ts

It is really hard to tell why our browser tests are flakey. A few things I noticed are listed below.
- `:above` seems to be unstable and could select wrong elements so I went and changed all usage of it to more specific selectors. 
- I also increased the timeout since `question_lifecycle.test.ts` is so large that it frequently times out on my machine locally.
- `:visible` also seems to be unstable so I replace it in one place to increase stability.
- Make sure when we are on admin question page to create a new question, we wait until the page is fully loaded and the javascript dropdown event listener is attached. This breaks sometimes as you can see in one of the failed test in this PR.

Deflake browser tests take 2

---

.github/ISSUE_TEMPLATE/bug_report.md

This makes bugs reported by community members easier to find and identify.
Community members will be encouraged to report bugs even past June 2021. They'll be directed to use the "Bug Report" Issue template. This PR simply has gives issues made with that template the `bug` label so they're easier to find and search for later.

Make Bug Report issues use the `bug` label

---

universal-application-tool-0.0.1/app/repository/VersionRepository.java
universal-application-tool-0.0.1/app/services/program/predicate/LeafOperationExpressionNode.java
universal-application-tool-0.0.1/test/repository/VersionRepositoryTest.java
universal-application-tool-0.0.1/test/support/ResourceCreator.java

1. Updates leaf nodes in the `PredicateDefinition` to use updated question IDs
2. Please scrutinize my recursive predicate tree update - it's been awhile since I've worked with tree structures!
3. Adds unit tests for `updateQuestionVersions`
#1001

Update predicate question references when publishing

---

universal-application-tool-0.0.1/app/services/program/ProgramService.java
universal-application-tool-0.0.1/app/services/program/ProgramServiceImpl.java
universal-application-tool-0.0.1/test/services/program/ProgramServiceImplTest.java

Add a helper method for `ProgramServiceImpl#addBlockDefinition` and `ProgramServiceImpl#addRepeatedBlockDefinition` so they get added in the right place.
Progress towards #1228

ProgramService methods that add blocks add them in the right place.

---

universal-application-tool-0.0.1/app/services/applicant/question/Scalar.java
universal-application-tool-0.0.1/app/services/program/ProgramDefinition.java
universal-application-tool-0.0.1/app/views/admin/programs/ProgramBlockPredicatesEditView.java
universal-application-tool-0.0.1/app/views/style/BaseStyles.java

Also:
* Fix the "Value" field for multi-option questions. Now the admin will see a dropdown of options for the "Value" instead of a freeform input box.
* Don't include enumerator questions in the list of available predicate question definitions. This is because enumerators do not have any "scalar" values associated with them. If we want to support predicates based on enumerator questions, it will take a bit more design and special case implementation. This is not in scope for the current goal.
- Will add browser tests for this flow once it's working e2e. 

Admin predicate form: Display the right scalars for question type

---

universal-application-tool-0.0.1/app/services/MessageKey.java
universal-application-tool-0.0.1/app/views/components/SelectWithLabel.java
universal-application-tool-0.0.1/app/views/questiontypes/DropdownQuestionRenderer.java
universal-application-tool-0.0.1/conf/messages
universal-application-tool-0.0.1/test/views/components/SelectWithLabelTest.java
universal-application-tool-0.0.1/test/views/questiontypes/DropdownQuestionRendererTest.java

I added an option to the dropdown with text "Choose an option:" that will only show when nothing is selected.  Once a user has selected an option, the "choose" option will be not be visible or selectable any more.  The user is able to skip the dropdown question and submit the application if they leave the "choose" option selected.
Fixes #1244

Added Dropdown null state

---

universal-application-tool-0.0.1/app/controllers/FileController.java
universal-application-tool-0.0.1/app/views/applicant/ApplicantProgramBlockEditView.java
universal-application-tool-0.0.1/test/controllers/FileControllerTest.java

- Only file keys that contain the explicit applicant id or program id can be accessed through file controller.
#1355

Restrict file access to the explicit applicant or program

---

universal-application-tool-0.0.1/app/assets/javascripts/main.ts
universal-application-tool-0.0.1/app/services/applicant/ApplicantServiceImpl.java
universal-application-tool-0.0.1/app/services/applicant/question/Scalar.java
universal-application-tool-0.0.1/app/services/program/predicate/Operator.java
universal-application-tool-0.0.1/app/services/question/types/ScalarType.java
universal-application-tool-0.0.1/app/views/admin/programs/ProgramBlockPredicatesEditView.java
universal-application-tool-0.0.1/app/views/components/SelectWithLabel.java
universal-application-tool-0.0.1/app/views/style/ReferenceClasses.java

1. Allow setting custom options in `SelectWithLabel`
2. Add a `LIST_OF_STRINGS` scalar type - this is only used by multi-select questions but helps when filtering operators to just those that operate on lists
2. Add the `ScalarType` as a data attribute to each `Scalar`. When a scalar is selected, show only the operators that can act on that scalar's type
3. Add two operators for dates - we compare timestamps, so in reality they are just < and >, but are clearer to use for the admin
#322

Only show relevant `Operator`s in predicate builder

---

universal-application-tool-0.0.1/app/models/Application.java
universal-application-tool-0.0.1/conf/evolutions/default/32.sql

While applicant has preferred lang field, they could change it anytime they like. This change locks in the language an applicant set while they applied for a program.
#1220

Application records preferred language

---

universal-application-tool-0.0.1/app/controllers/applicant/ApplicantProgramsController.java
universal-application-tool-0.0.1/app/repository/UserRepository.java
universal-application-tool-0.0.1/app/services/MessageKey.java
universal-application-tool-0.0.1/app/services/applicant/ApplicantService.java
universal-application-tool-0.0.1/app/services/applicant/ApplicantServiceImpl.java
universal-application-tool-0.0.1/app/views/applicant/ProgramIndexView.java
universal-application-tool-0.0.1/app/views/style/ApplicantStyles.java
universal-application-tool-0.0.1/conf/messages
universal-application-tool-0.0.1/conf/messages.en-US
universal-application-tool-0.0.1/conf/messages.es-US
universal-application-tool-0.0.1/test/services/applicant/ApplicantServiceImplTest.java

If an applicant started a program but did not submit it, it would appear twice in the applicant's program index view. This is because it would appear as a program that the applicant had a draft application open for, and then again as an active program. This PR dedupes the list of programs an applicant sees, prioritizing programs that they have draft applications open for.
* center the main content
* distinguish between applications the applicant can continue, or new programs they can apply for
This PR does not fix the bug that's being fixed by #1368. If an applicant has a draft program open, and then a new version is published with updated questions, the applicant is currently unable to access their draft application because some questions in that program are now obsolete and cannot be …

Dedupe active programs and programs with draft applications

---

universal-application-tool-0.0.1/app/controllers/admin/AdminProgramBlocksController.java
universal-application-tool-0.0.1/app/services/program/IllegalBlockMoveException.java
universal-application-tool-0.0.1/app/services/program/ProgramDefinition.java
universal-application-tool-0.0.1/app/services/program/ProgramService.java
universal-application-tool-0.0.1/app/services/program/ProgramServiceImpl.java
universal-application-tool-0.0.1/app/services/program/predicate/PredicateDefinition.java
universal-application-tool-0.0.1/app/services/program/predicate/PredicateExpressionNode.java
universal-application-tool-0.0.1/app/views/admin/programs/ProgramBlockEditView.java
universal-application-tool-0.0.1/test/services/program/ProgramDefinitionTest.java
universal-application-tool-0.0.1/test/services/program/predicate/PredicateExpressionNodeTest.java

Moving a block fails and gives an error in the following cases:
1. I try to move a block with a predicate before its predicate question(s)
1. I try to move block A, which has predicate question(s), after block B that has the predicate which depends on block A's questions
Details
1. Adds `getQuestions` to predicate definition, so we can get all the questions used for a particular block's predicate
2. Shows an error message if a block move fails
#322

Reordering block with predicate gives warning for illegal move

---

browser-test/src/application_previous_version.test.ts
browser-test/src/support/admin_programs.ts
universal-application-tool-0.0.1/app/services/program/ProgramService.java
universal-application-tool-0.0.1/app/services/program/ProgramServiceImpl.java
universal-application-tool-0.0.1/app/services/question/QuestionService.java
universal-application-tool-0.0.1/app/services/question/QuestionServiceImpl.java
universal-application-tool-0.0.1/app/services/question/ReadOnlyCurrentQuestionServiceImpl.java
universal-application-tool-0.0.1/app/services/question/ReadOnlyVersionedQuestionServiceImpl.java
universal-application-tool-0.0.1/test/services/question/ReadOnlyCurrentQuestionServiceImplTest.java
universal-application-tool-0.0.1/test/services/question/ReadOnlyVersionedQuestionServiceImplTest.java

Create `ReadOnlyVersionedQuestionServiceImpl.java` to load all questions in a particular version. This enables loading inactive programs and questions.
Unblock #1334

Load inactive program definitions properly

---

universal-application-tool-0.0.1/app/controllers/admin/AdminProgramBlockPredicatesController.java
universal-application-tool-0.0.1/app/services/program/ProgramService.java
universal-application-tool-0.0.1/app/services/program/ProgramServiceImpl.java
universal-application-tool-0.0.1/conf/routes
universal-application-tool-0.0.1/test/controllers/admin/AdminProgramBlockPredicatesControllerTest.java
universal-application-tool-0.0.1/test/services/program/ProgramServiceImplTest.java

This is part one of allowing admins to remove predicates. The next and final part is to add a button to the UI that calls the new `destroy` endpoint.

Add service method and routing endpoint for removing a block visibility predicate

---

universal-application-tool-0.0.1/app/views/applicant/ProgramIndexView.java
universal-application-tool-0.0.1/app/views/style/ApplicantStyles.java
universal-application-tool-0.0.1/app/views/style/StyleUtils.java

Actually center the applicant program index view by using a grid and using responsive grid column size. The reason for the `programCardsContainerStyles` method is to limit how many columns the program cards container can have when there are only 1-5 programs.

Center the applicant program index view

---

universal-application-tool-0.0.1/app/services/question/types/QuestionDefinition.java
universal-application-tool-0.0.1/test/services/question/types/QuestionDefinitionTest.java

QuestionDefinition validation now checks that multi-option question options have unique default localizations.

Check uniqueness of multi-option question options

---

universal-application-tool-0.0.1/app/services/applicant/Block.java
universal-application-tool-0.0.1/app/services/applicant/question/ApplicantQuestion.java
universal-application-tool-0.0.1/app/services/applicant/question/PresentsErrors.java
universal-application-tool-0.0.1/app/views/questiontypes/ApplicantQuestionRendererFactory.java
universal-application-tool-0.0.1/test/services/applicant/question/AddressQuestionTest.java
universal-application-tool-0.0.1/test/services/applicant/question/DateQuestionTest.java
universal-application-tool-0.0.1/test/services/applicant/question/EmailQuestionTest.java
universal-application-tool-0.0.1/test/services/applicant/question/EnumeratorQuestionTest.java
universal-application-tool-0.0.1/test/services/applicant/question/FileUploadQuestionTest.java
universal-application-tool-0.0.1/test/services/applicant/question/MultiSelectQuestionTest.java
universal-application-tool-0.0.1/test/services/applicant/question/NameQuestionTest.java
universal-application-tool-0.0.1/test/services/applicant/question/NumberQuestionTest.java
universal-application-tool-0.0.1/test/services/applicant/question/SingleSelectQuestionTest.java
universal-application-tool-0.0.1/test/services/applicant/question/TextQuestionTest.java
universal-application-tool-0.0.1/test/views/questiontypes/CheckboxQuestionRendererTest.java
universal-application-tool-0.0.1/test/views/questiontypes/DropdownQuestionRendererTest.java
universal-application-tool-0.0.1/test/views/questiontypes/RadioButtonQuestionRendererTest.java
universal-application-tool-0.0.1/test/views/questiontypes/TextQuestionRendererTest.java

`Block` has `ProgramQuestionDefinition`s instead of just `QuestionDefinition`s, so that the blocks can eventually use the `ProgramQuestionDefinition#optiona()` field.
Question definition samples need to be created with a fake question definition ID so they can be turned into `ProgramQuestionDefinition`s for `ApplicantQuestion`. Similarly, tests had to be updated so `ApplicantQuestion`s were created with `QuestionDefinition`s with IDs so they could be turned into real `ProgramQuestionDefinition`s.
Progress towards #1307

Store ProgramQuestionDefinition in Block

---

browser-test/src/admin_dropdown_create_and_edit.test.ts
browser-test/src/application_csv_download.test.ts
browser-test/src/application_review.test.ts
browser-test/src/support/admin_programs.ts
universal-application-tool-0.0.1/app/controllers/admin/AdminQuestionController.java
universal-application-tool-0.0.1/app/controllers/dev/DatabaseSeedController.java
universal-application-tool-0.0.1/app/forms/EmailQuestionForm.java
universal-application-tool-0.0.1/app/forms/MultiOptionQuestionForm.java
universal-application-tool-0.0.1/app/models/Question.java
universal-application-tool-0.0.1/app/services/question/LocalizedQuestionOption.java
universal-application-tool-0.0.1/app/services/question/QuestionOption.java
universal-application-tool-0.0.1/app/services/question/types/QuestionDefinitionBuilder.java
universal-application-tool-0.0.1/app/views/admin/questions/QuestionConfig.java
universal-application-tool-0.0.1/app/views/admin/questions/QuestionEditView.java
universal-application-tool-0.0.1/app/views/questiontypes/ApplicantQuestionRendererFactory.java
universal-application-tool-0.0.1/app/views/questiontypes/CheckboxQuestionRenderer.java
universal-application-tool-0.0.1/app/views/questiontypes/DropdownQuestionRenderer.java
universal-application-tool-0.0.1/app/views/questiontypes/RadioButtonQuestionRenderer.java
universal-application-tool-0.0.1/test/controllers/admin/AdminQuestionControllerTest.java
universal-application-tool-0.0.1/test/forms/CheckboxQuestionFormTest.java
universal-application-tool-0.0.1/test/forms/DropdownQuestionFormTest.java
universal-application-tool-0.0.1/test/forms/MultiOptionQuestionFormTest.java
universal-application-tool-0.0.1/test/forms/RadioButtonQuestionFormTest.java
universal-application-tool-0.0.1/test/forms/translation/MultiOptionQuestionTranslationFormTest.java
universal-application-tool-0.0.1/test/services/applicant/question/SingleSelectQuestionTest.java
universal-application-tool-0.0.1/test/services/question/types/MultiOptionQuestionDefinitionTest.java
universal-application-tool-0.0.1/test/services/question/types/QuestionOptionTest.java
universal-application-tool-0.0.1/test/support/TestQuestionBank.java

Maintain the ids of question options, as they change, using an ordering number instead.
Fixes #1273.

ensure that updates to multi-option questions do not invalidate previous answers.

---

universal-application-tool-0.0.1/app/assets/javascripts/main.ts
universal-application-tool-0.0.1/app/views/admin/programs/ProgramBlockPredicatesEditView.java
universal-application-tool-0.0.1/app/views/style/ReferenceClasses.java

This makes it so that the "compared value" that the admin enters on the right hand side will match the "scalar" or "field" type on the left hand side.
The type will change on the fly. Meaning that if the "Field" dropdown has more than one different type of scalar listed, the "Value" input type will change as you change the "Field" dropdown.
Random other change: Use single quote (`'`) instead of double quote (`"`) throughout `main.ts` to match the [Google TypeScript Style Guide](https://google.github.io/styleguide/tsguide.html). I can't find exactly where it says that, but if you look at all the code snippets, they use single quotes.

Predicate form: Change the input type of the "Value" field, depending on the scalar type

---

universal-application-tool-0.0.1/app/controllers/admin/AdminProgramBlockPredicatesController.java
universal-application-tool-0.0.1/app/services/program/predicate/AndNode.java
universal-application-tool-0.0.1/app/services/program/predicate/ConcretePredicateExpressionNode.java
universal-application-tool-0.0.1/app/services/program/predicate/LeafOperationExpressionNode.java
universal-application-tool-0.0.1/app/services/program/predicate/OrNode.java
universal-application-tool-0.0.1/app/services/program/predicate/PredicateDefinition.java
universal-application-tool-0.0.1/app/services/program/predicate/PredicateExpressionNode.java
universal-application-tool-0.0.1/app/services/program/predicate/PredicateValue.java
universal-application-tool-0.0.1/app/services/question/types/MultiOptionQuestionDefinition.java
universal-application-tool-0.0.1/app/views/admin/programs/ProgramBlockPredicatesEditView.java
universal-application-tool-0.0.1/test/services/program/predicate/PredicateDefinitionTest.java
universal-application-tool-0.0.1/test/services/program/predicate/PredicateExpressionNodeTest.java
universal-application-tool-0.0.1/test/services/program/predicate/PredicateValueTest.java

1. Adds `toDisplayString` methods for predicate nodes that are human-readable
2. Uses question definitions to convert values to readable representations
3. Shows pretty-printed phrase in block predicate edit view
#322

Pretty print existing predicates

---

universal-application-tool-0.0.1/app/services/applicant/question/ApplicantQuestion.java
universal-application-tool-0.0.1/app/services/applicant/question/Scalar.java
universal-application-tool-0.0.1/app/views/admin/programs/ProgramBlockPredicatesEditView.java
universal-application-tool-0.0.1/test/controllers/admin/AdminProgramBlockPredicatesControllerTest.java

This is an overdue cleanup from when I updated `Scalar` in a previous PR to take its `ScalarType` in the constructor.

Clean up `Scalar` enum to use its new built-in scalar types

---

universal-application-tool-0.0.1/app/views/components/FieldWithLabel.java
universal-application-tool-0.0.1/test/views/components/FieldWithLabelTest.java

User can only input integer in number input fields.
#1391

Parse number into integer on client-side

---

universal-application-tool-0.0.1/app/views/admin/programs/ProgramBlockEditView.java

If a block has a predicate, display  a section in the edit view with the predicate
#322

Display predicate in block edit view

---

universal-application-tool-0.0.1/app/services/program/predicate/PredicateValue.java
universal-application-tool-0.0.1/app/views/components/FieldWithLabel.java
universal-application-tool-0.0.1/test/services/program/predicate/PredicateValueTest.java
universal-application-tool-0.0.1/test/views/components/FieldWithLabelTest.java

Fixes a bug introduced in #1430 - we need to convert the option ID to option text for single-select questions, as well as multi-select
#322

Display the option text rather than ID for single-select questions

---

browser-test/browser-test-compose.yml
docker-compose.yml
universal-application-tool-0.0.1/app/views/admin/programs/ProgramBlockEditView.java
universal-application-tool-0.0.1/conf/application.conf

Hide optional question toggle behind feature flag.
Feature is enabled by setting `CF_OPTIONAL_QUESTIONS` environment variable to any value.
turned on:
turned off:

Hide optional question toggle behind feature flag

---

bin/refresh-styles
universal-application-tool-0.0.1/app/views/style/BaseStyles.java
universal-application-tool-0.0.1/app/views/style/Styles.java
universal-application-tool-0.0.1/project/TailwindBuilder.scala
universal-application-tool-0.0.1/tailwind.config.js
universal-application-tool-0.0.1/tailwindbuilder.sbt

This reverts commit a2d9bfe95a788daef5255a6ee5d05972fc574e6c.
This solution is only okay.  Because we have copied every class - including very many that we do not use - into `Styles.java`, and because we programmatically create utility classes, we have to keep an awful lot of CSS that we don't actually need.  Still, this brings us from 4.6 MB to 1.6 MB, which is something - and eliminates the prod/dev distinction, so we can see if we're about to screw up the styles in prod.
It also adds a tool to refresh styles without restarting `bin/run-dev`, which is a little helpful for development here.
We can get down to below a megabyte by removing all the styles from `Styles.java` that we do not use.  What we cannot do is analyze that file at minification-time to see which variables are in use. …

Revert "Revert "Minify prod css (#1386)" (#1392)"

---

universal-application-tool-0.0.1/app/controllers/dev/DatabaseSeedController.java
universal-application-tool-0.0.1/app/repository/VersionRepository.java
universal-application-tool-0.0.1/app/services/applicant/question/ApplicantQuestion.java
universal-application-tool-0.0.1/app/services/export/ExporterService.java
universal-application-tool-0.0.1/app/services/program/ProgramQuestionDefinition.java
universal-application-tool-0.0.1/app/services/program/ProgramServiceImpl.java
universal-application-tool-0.0.1/app/views/questiontypes/ApplicantQuestionRendererFactory.java
universal-application-tool-0.0.1/test/models/ProgramTest.java
universal-application-tool-0.0.1/test/services/applicant/BlockTest.java
universal-application-tool-0.0.1/test/services/program/BlockDefinitionTest.java
universal-application-tool-0.0.1/test/services/program/ProgramDefinitionTest.java
universal-application-tool-0.0.1/test/services/program/ProgramServiceImplTest.java
universal-application-tool-0.0.1/test/support/ProgramBuilder.java

Larger than I had hoped... but this gets a `program id` reference into a `ProgramQuestionDefinition`. The main change is `ProgramQuestionDefinition#setQuestionDefinition` turned into `ProgramQuestionDefinition#loadCompletely`.
Most other changes change how objects are constructed in tests.
Progress towards #1417

Add program id to program question definition

---

universal-application-tool-0.0.1/app/services/applicant/question/FileUploadQuestion.java
universal-application-tool-0.0.1/app/views/applicant/ApplicantProgramBlockEditView.java
universal-application-tool-0.0.1/app/views/questiontypes/FileUploadQuestionRenderer.java
universal-application-tool-0.0.1/test/services/applicant/question/FileUploadQuestionTest.java

Record the filename and show user the file they have uploaded.
In file upload question block:
In review page:
#1312 
#1428

Record and show uploaded filename

---

browser-test/src/application_previous_version.test.ts
browser-test/src/application_review.test.ts
universal-application-tool-0.0.1/app/auth/CiviFormProfile.java
universal-application-tool-0.0.1/app/auth/ProfileFactory.java
universal-application-tool-0.0.1/test/controllers/FileControllerTest.java

Admins should in fact not have access to programs, even if there are no program admins.
Fixes #1461.

Remove admin access for global admins to programs which don't have admins

---

browser-test/src/application_review.test.ts
browser-test/src/end_to_end_enumerators.test.ts
browser-test/src/support/applicant_questions.ts
universal-application-tool-0.0.1/app/controllers/applicant/ApplicantProgramBlocksController.java
universal-application-tool-0.0.1/app/services/MessageKey.java
universal-application-tool-0.0.1/app/services/applicant/ApplicantData.java
universal-application-tool-0.0.1/app/services/applicant/ApplicantServiceImpl.java
universal-application-tool-0.0.1/app/services/applicant/Block.java
universal-application-tool-0.0.1/app/services/applicant/question/AddressQuestion.java
universal-application-tool-0.0.1/app/services/applicant/question/ApplicantQuestion.java
universal-application-tool-0.0.1/app/services/applicant/question/EnumeratorQuestion.java
universal-application-tool-0.0.1/app/services/applicant/question/NameQuestion.java
universal-application-tool-0.0.1/app/services/applicant/question/PresentsErrors.java
universal-application-tool-0.0.1/app/services/program/ProgramQuestionDefinition.java
universal-application-tool-0.0.1/app/views/admin/programs/ProgramBlockEditView.java
universal-application-tool-0.0.1/app/views/applicant/ApplicantProgramBlockEditView.java
universal-application-tool-0.0.1/app/views/questiontypes/ApplicantQuestionRenderer.java
universal-application-tool-0.0.1/conf/messages
universal-application-tool-0.0.1/conf/messages.en-US
universal-application-tool-0.0.1/conf/messages.es-US
universal-application-tool-0.0.1/test/controllers/applicant/ApplicantProgramBlocksControllerTest.java
universal-application-tool-0.0.1/test/services/applicant/ApplicantDataTest.java
universal-application-tool-0.0.1/test/services/applicant/ApplicantServiceImplTest.java
universal-application-tool-0.0.1/test/services/applicant/BlockTest.java
universal-application-tool-0.0.1/test/services/applicant/question/ApplicantQuestionTest.java
universal-application-tool-0.0.1/test/support/ProgramBuilder.java

Before, updates with empty values ("") would be stored in applicant data json. Now we don't store empty values, and updates with empty values delete the value that was stored.
Metadata is updated for every question, which we can use to mark whether a question has been visited even though it is unanswered. 
Arrays (enumerator and multi select questions) with empty updates get deleted, but the metadata is still updated.
Questions are "answered" if any of their scalars have a value in applicant data. There might be weird behavior with old applicant data that is storing blank values, but blank values shouldn't exist in the future.
Scalar specific errors for multi-field questions (address and name) for each of their fields are present if the question is answered, not just if the field is …

Stop storing blank values in applicant data.

---

universal-application-tool-0.0.1/app/assets/javascripts/main.ts
universal-application-tool-0.0.1/app/controllers/admin/AdminProgramBlockPredicatesController.java
universal-application-tool-0.0.1/app/forms/BlockVisibilityPredicateForm.java
universal-application-tool-0.0.1/app/views/admin/programs/ProgramBlockPredicatesEditView.java
universal-application-tool-0.0.1/app/views/style/BaseStyles.java
universal-application-tool-0.0.1/test/controllers/admin/AdminProgramBlockPredicatesControllerTest.java

Now predicates based on multi-options questions can actually have lists as the `values` field on the right hand side! Works for both single select (radios, dropdowns) and multi select questions.
* Use a set of checkbox inputs for the `value` field when the left hand side of the predicate operator is a selection or selections from a multi-option question.
* Parse these checkbox values differently than if we were getting one string value.
* Removed  "is equal to" and "is not equal to" operator options from single-select predicates. This is because then we'd need to limit the number of checkboxes selected in that case. We could have added extra validation to enforce selecting only a single option in that case. But, since "is one of" with just one value is equivalent to "is equal to" and …

Allow a list of values for multi-option question predicates

---

universal-application-tool-0.0.1/app/views/admin/programs/ManageProgramAdminsView.java
universal-application-tool-0.0.1/app/views/admin/programs/ProgramBlockEditView.java
universal-application-tool-0.0.1/app/views/admin/programs/ProgramTranslationView.java
universal-application-tool-0.0.1/app/views/admin/questions/QuestionConfig.java
universal-application-tool-0.0.1/app/views/admin/questions/QuestionEditView.java
universal-application-tool-0.0.1/app/views/components/FieldWithLabel.java
universal-application-tool-0.0.1/app/views/questiontypes/DateQuestionRenderer.java
universal-application-tool-0.0.1/app/views/questiontypes/DropdownQuestionRenderer.java
universal-application-tool-0.0.1/app/views/questiontypes/EmailQuestionRenderer.java
universal-application-tool-0.0.1/app/views/questiontypes/EnumeratorQuestionRenderer.java
universal-application-tool-0.0.1/app/views/questiontypes/NumberQuestionRenderer.java
universal-application-tool-0.0.1/app/views/questiontypes/TextQuestionRenderer.java

Multi-part questions are rendered with their labels adjacent and content-ful - but for the single-part questions where we don't, this PR adds the content.  It also associates all the labels with the inputs.  for the ones where the associated label would be duplicative, apply `sr-only` class.
Tested by adding an assert - browser tests all pass - removed the assert because a ton of unit tests would have needed to be updated to no real benefit.
Addresses #1456.

Add labels to every field so that screen readers can interact with them.

---

universal-application-tool-0.0.1/app/assets/stylesheets/styles.css
universal-application-tool-0.0.1/app/views/admin/questions/QuestionEditView.java
universal-application-tool-0.0.1/app/views/components/LinkElement.java

Simple change to make the default buttons darker. Applicant buttons don't use default button style, so this should only change admin facing buttons.
Not all the buttons have the same color on the admin side. I don't want to spend too much time standardizing everything since we have UX mocks that will totally change everything eventually.
Fixes #1476

more constrast for buttons in admin UI

---

universal-application-tool-0.0.1/app/assets/javascripts/main.ts
universal-application-tool-0.0.1/app/views/admin/programs/ProgramBlockPredicatesEditView.java
universal-application-tool-0.0.1/app/views/style/ReferenceClasses.java

Also fixed a small bug in another part of the JavaScript where we should have checked for "SELECTIONS" _in addition to "SELECTION". Before this PR there was a null error being printed in the console in some cases.

Admin predicate UI: Add help text for entering "comma-separated values" in some cases

---

universal-application-tool-0.0.1/app/views/style/BaseStyles.java

Made base style for link text `text-blue-600`. Tested with Lighthouse in chrome developer tools.
Fixes #1472

Make base style for link text darker.

---

browser-test/src/end_to_end_enumerators.test.ts
browser-test/src/support/applicant_questions.ts
universal-application-tool-0.0.1/app/services/MessageKey.java
universal-application-tool-0.0.1/app/views/questiontypes/EnumeratorQuestionRenderer.java
universal-application-tool-0.0.1/conf/messages

I added a browser confirmation that shows when a user deletes an enumerator entity.  If the user clicks "cancel", the click event is not propagated to the normal entity-deleting listener.
The styling of the dialog isn't very pretty, because it's the default browser confirm dialog that we don't have control over.
Tested locally.
Fixes #1117

Add confirmation dialog to enumerator deletion.

---

universal-application-tool-0.0.1/app/views/applicant/ProgramIndexView.java

Use h3 headers for things under the h2 header in applicants `ProgramIndexView`.
Fixes #1523

Use h3 for in progress and active program headers.

---

universal-application-tool-0.0.1/app/controllers/admin/AdminProgramBlockPredicatesController.java

Admin predicate UI: Fix toast message for multi-option questions

---

universal-application-tool-0.0.1/app/services/MessageKey.java
universal-application-tool-0.0.1/app/views/applicant/ApplicantProgramSummaryView.java
universal-application-tool-0.0.1/conf/messages

The "Edit" link does not provide enough context to know what you are editing. This adds an `aria-label` so screen readers will read out the question you are editing 
Verified with a Chrome screen reader
Fixes #1464

Add an aria-label to the Edit link in application review page

---

universal-application-tool-0.0.1/app/forms/QuestionForm.java
universal-application-tool-0.0.1/app/services/export/ExporterService.java
universal-application-tool-0.0.1/app/services/question/QuestionServiceImpl.java
universal-application-tool-0.0.1/app/views/admin/questions/QuestionEditView.java

Enumerators are not exported, so the admin shouldn't have to see options for configuring their export.
Fixes #1533. Static questions also do not have export options in the question edit view, but when updating it checks for export state which is problematic because it doesn't exist in the form. The changes should fix the bug for both enumerators and static questions.

Leave export options out of the enumerator question edit view

---

universal-application-tool-0.0.1/app/services/MessageKey.java
universal-application-tool-0.0.1/app/views/applicant/ApplicantLayout.java
universal-application-tool-0.0.1/conf/messages

Adds an aria-label to the language select in applicant header
The screen reader reads "Tagalog, Choose a language, menu pop up collapsed, button"
Fixes #1471

Add an aria-label for the language select in applicant header

---

universal-application-tool-0.0.1/app/views/applicant/ProgramIndexView.java

Fixes https://github.com/seattle-uat/civiform/issues/1465.
From
To

Remove redundant '- CiviForm' in main page title.

---

universal-application-tool-0.0.1/app/views/components/Modal.java
universal-application-tool-0.0.1/app/views/style/BaseStyles.java

Use `flex-grow` and `gap-4` to make sure there is space between the modal header and the "x" that closes the modal.
OLD
NEW

Fix modal header spacing between title and close button

---

browser-test/src/application_csv_download.test.ts
browser-test/src/application_review.test.ts
browser-test/src/support/admin_programs.ts

Use more specific selectors to avoid selecting hidden elements, causing browser tests to time out.

Use more specific selector in browser tests

---

browser-test/src/end_to_end_enumerators.test.ts
universal-application-tool-0.0.1/app/services/applicant/AnswerData.java
universal-application-tool-0.0.1/app/services/applicant/ReadOnlyApplicantProgramServiceImpl.java
universal-application-tool-0.0.1/app/views/applicant/ApplicantProgramSummaryView.java

Rendering summary data checks the timestamp to see if it answered. That isn't how it works anymore. Metadata exists if a question is visited - whether it is answered or not. 
This PR adds an explicit `isAnswered` member to `SummaryData` which is used instead of checking the timestamp metadata.
Problem:

Summary data + unanswered questions

---

browser-test/src/support/admin_questions.ts

An attempt to improve browser test reliability. Many flaky test failures seem to involve checks for content on pages that get navigated to after some action, but the failures suggest that the navigation hasn't happened yet. Unfortunately, a reliable local repro has been elusive so I'm proposing we submit this test only change to evaluate impact on our prober runs which are much flakier. 
Made admin question creation/update tests wait for navigation back to the main questions page after clicking the submit button before processing checks for next page content. If this works, there are other tests that have similar failures, so this is not a complete fix for #1309.
#1309

Wait for navigation after click to make next page checks reliable (#1309)

---

browser-test/src/support/admin_questions.ts
universal-application-tool-0.0.1/app/views/admin/questions/QuestionsListView.java

Previously, error toasts were displaying on redirect to the questions page. When the render function on the QuestionListView file is called with the optional "maybeFlash" set, it always should be a success message (since we only render to this page with that set on "Create" or "Update"). I also considered having a "maybeToastType" optional param that can be passed along with the type (success / error / etc.) that the toast should be, but this seems like over-engineering considering we don't know if there would be an error case where we navigate to the questions list (all error cases right now we stay on the question page).  
Fixes #1356

Success toast should appear when action is completed successfully

---

browser-test/src/application_review.test.ts
browser-test/src/support/admin_questions.ts
browser-test/src/support/applicant_questions.ts
universal-application-tool-0.0.1/app/services/applicant/Block.java
universal-application-tool-0.0.1/app/services/applicant/ReadOnlyApplicantProgramServiceImpl.java
universal-application-tool-0.0.1/test/services/applicant/BlockTest.java
universal-application-tool-0.0.1/test/services/applicant/ReadOnlyApplicantProgramServiceImplTest.java

Change the logic to return blocks so that if a block contains a static question it is always shown to the user.  This is regardless of whether there are other questions on the block that have already been answered and would not have been shown again beforehand.  See issue #1555 for more detail.
Includes:
- unit tests for all scenarios that could arise
- Changed logic
- browser test for a static question block to make sure it is shown to the user.
Fixes #1555
Peer programmed with ettengererin and dkatzz

Make sure static questions are always shown

---

browser-test/src/application_review.test.ts

Browser tests seemed to be failing since the question bank clears out after a file upload question and sometimes 'second-static-q' was getting chosen instead of 'static-q' because of similarities in the name. Updated and it seems to pass now

Fix browser tests

---

universal-application-tool-0.0.1/app/views/applicant/ProgramIndexView.java
universal-application-tool-0.0.1/app/views/style/ApplicantStyles.java

Seattle logo was covering h1 text - changed logo from absolute positioning and added padding to child elements instead of parent. See more info about padding with tailwind [here](https://tailwindcss.com/docs/padding) and see screenshots below for updated versions on mobile and web.
Fixes #1566

Fix styles so that Seattle logo isn't covering h1 text

---

universal-application-tool-0.0.1/app/views/style/BaseStyles.java

Text in a checkbox and radio button option in an application was overflowing if there was too much text for the size of the screen. This bug occurred on desktop and mobile.
We removed the height specification (H_12) for radio button and checkbox inputs. We kept the height tag for all other inputs to be safe. We may be able to remove the height tag in the future once we verify it doesn't break any other experiences.
Before:
After:
Fixes #1572

Fix sizing of box around a radio or checkbox input

---

universal-application-tool-0.0.1/app/views/applicant/ApplicantProgramSummaryView.java
universal-application-tool-0.0.1/app/views/style/BaseStyles.java

Bug addressed: Text does not wrap for long words, like copy/pasted URLs, in the application summary rows. We added custom CSS to break long words in order to wrap text. 
There is a similar tailwind.css property - https://tailwindcss.com/docs/word-break#break-words. However, the tailwind css does not actually behave as expected and does not solve the issue (looks like this property is not maintained by tailwind anymore).
Adding Bion as a reviewer here to confirm that adding custom css in this way is safe and to recommend any alternatives.
Before: 
After:
Fixes #1567

Fix text wrapping on program summary and preview view.

---

universal-application-tool-0.0.1/app/views/components/TextFormatter.java
universal-application-tool-0.0.1/test/views/components/TextFormatterTest.java

The UrlDetector class we're using includes some types of trailing punctuation characters in detected URLs. While these are legal URL path characters, in the context of Civiform free text fields, these are more likely to be part of the surrounding text instead of the URL. This PR strips typical trailing punctuation from detected URLs.
Fixes #1579

Don't include trailing punctuation in parsed URLs.

---

universal-application-tool-0.0.1/app/controllers/applicant/ApplicantProgramBlocksController.java
universal-application-tool-0.0.1/app/services/applicant/ReadOnlyApplicantProgramService.java
universal-application-tool-0.0.1/app/services/applicant/ReadOnlyApplicantProgramServiceImpl.java
universal-application-tool-0.0.1/test/services/applicant/ReadOnlyApplicantProgramServiceImplTest.java
universal-application-tool-0.0.1/test/support/TestQuestionBank.java

Usually, static questions are incomplete so that the screens will pop up for users to take notice of.  However, when an applicant selects 'Review', consider static questions to be complete.  Once an applicant selects 'Review', static questions will only be shown if they are on the same screen as an incomplete question that needs to be answered.  This will allow for the screen to be progressed from and the application submitted.
- [X ] Created tests which fail without the change (if possible)
Done in collaboration with dkatzz

Ignore static questions while in review

---

universal-application-tool-0.0.1/app/views/LoginForm.java

There's an error message that currently shows when the user is re-directed to the login page, which is unexpected. When a user is redirected to the login page, we don't want to show an error message.
Fixes #1595

Remove error message on login page

---

universal-application-tool-0.0.1/app/controllers/admin/AdminApplicationController.java
universal-application-tool-0.0.1/app/models/Program.java
universal-application-tool-0.0.1/app/services/export/ExporterService.java
universal-application-tool-0.0.1/app/services/program/ProgramService.java
universal-application-tool-0.0.1/app/services/program/ProgramServiceImpl.java
universal-application-tool-0.0.1/app/views/admin/programs/ProgramApplicationListView.java

Updated the program getApplications to be getSubmittedApplications, filtering by lifecycleStage.Active.  This makes it so that draft applications, as well as deleted or obsolete applications, will not be shown.  They will not show up on the program admin view page or in the downloaded csv
- May need a follow up cl with a browser test replicating this.  The ProgramServiceImplTest file only makes changes from the program admin perspective; there is no mocking the program to return apps or actually filling out apps in that file.  Adding tests would require a larger test system refactor here, or adding something such as browser test that can cover both the admin roles and applicant roles in one file.  Changes to other files are all trivial; renaming so it is clear what the function provides …

Only include submitted applications in the program admin view and download

---

universal-application-tool-0.0.1/app/controllers/admin/AdminApplicationController.java
universal-application-tool-0.0.1/app/services/applicant/ApplicantServiceImpl.java
universal-application-tool-0.0.1/app/views/admin/programs/ProgramApplicationListView.java
universal-application-tool-0.0.1/app/views/admin/programs/ProgramApplicationView.java

Using applicant IDs to alert admins of new applications, and to describe applications in admin list/detail views was confusing since the CSV export uses application IDs and there can be many applications for the same applicant. This PR switches to using application IDs instead if applicant IDs in most places, or makes it clear which one is being referenced.
Closes #1605

Switch to application IDs for admin application review UI.

---

browser-test/src/support/admin_questions.ts
browser-test/src/support/applicant_questions.ts
universal-application-tool-0.0.1/app/views/admin/AdminLayout.java
universal-application-tool-0.0.1/app/views/admin/programs/ProgramAdministratorProgramListView.java
universal-application-tool-0.0.1/app/views/admin/programs/ProgramApplicationListView.java
universal-application-tool-0.0.1/app/views/admin/programs/ProgramApplicationView.java
universal-application-tool-0.0.1/app/views/admin/programs/ProgramIndexView.java

Nav bar not displaying correctly for civiform admins.
Run formatting script on browser tests
Previously: Nav bar is not present for civiform admin.  No way to select 'Questions', 'Versions', etc
Now: nav bar for civiform admins is restored
One Open Q; Why didn't browser tests catch this broken nav bar? Locally and in past PRs browser tests all passed, only the prober successfully caught it

Fix Nav bar error

---

docker-compose.yml
universal-application-tool-0.0.1/app/views/LoginForm.java
universal-application-tool-0.0.1/app/views/applicant/ProgramIndexView.java
universal-application-tool-0.0.1/conf/application.conf

Allows specifying a civic entity and logos other than Seattle via config file.
There is still hard-coded codepaths for serving the local asset files for the Seattle logos. We could avoid this by asking Seattle to make the logos available somewhere else and providing URLs for them. I'm inclined to not bother with them that though. If someone feels differently we can change this.

Whitelabel civic entity name and logos

---

browser-test/src/application_csv_download.test.ts
universal-application-tool-0.0.1/app/services/applicant/ReadOnlyApplicantProgramServiceImpl.java

Dates were appearing as long numbers (i.e. 1631404800000) on the CSV exports, but these should show in the MM/dd/yyyy format (i.e. 05/21/2021). 
Fixes #1611
Worked on with @ettengererin

Dates should display correctly on CSV exports

---

browser-test/src/admin_dropdown_create_and_edit.test.ts
browser-test/src/end_to_end_enumerators.test.ts
browser-test/src/support/admin_predicates.ts
browser-test/src/support/admin_programs.ts
browser-test/src/support/admin_questions.ts
browser-test/src/support/applicant_questions.ts
browser-test/src/support/index.ts
browser-test/src/support/wait.ts
universal-application-tool-0.0.1/app/assets/javascripts/main.ts
universal-application-tool-0.0.1/app/assets/javascripts/modal.ts

Browser tests were flaky because they would start running while civiform JS would still be initializing (e.g., attaching event handlers). This PR adds some attributes for main.ts and modal.ts (the main causes of flakiness) to signal when they're done, and some browser test functions to wait for our pages to be ready and modals to be shown. Also tweaked a few selectors to make sure that playwright is waiting for DOM elements that signal when the page is actually ready for its next actions.
Fixes #1309

Fix browser test flakiness from page JS load race conditions.

---

browser-test/src/support/index.ts

Attempt to make browser tests more reliable around IDCS test user login by explicitly waiting for pages to load. Difficult to verify locally (though it should be benign), so proposing we optimistically see if it's effective in staging.

Added waitForNavigation to IDCS login to address flakiness

---

universal-application-tool-0.0.1/conf/messages
universal-application-tool-0.0.1/conf/messages.en-US

Updated messages and messages.en-US with requested replacement text for "Address line 2" address field prompt. Translations should be handled by #1629.
Fixes #1622

Updated text for 2nd address line prompt.

---

browser-test/src/admin_program_hidden.test.ts

Logging in and out multiple times in the same test is causing flakiness when running probe and deploy.  Separating into two for better reliability.

Separate hidden browser test to two tests; avoid login flakiness

---

universal-application-tool-0.0.1/app/services/role/RoleService.java
universal-application-tool-0.0.1/test/services/role/RoleServiceTest.java

This change reverts the change in https://github.com/seattle-uat/civiform/pull/1641. 
This will allow Seattle city admins to be added as program admins and they will be case sensitive. This means that Seattle city admins will have to be added with title case.
This fix is a step in the right direction of figuring out how Civiform will handle case sensitivity for accounts. We still need to make a larger design decision about how Civiform will handle case sensitivity for accounts. Until then, this fix will do!
Addresses #1612, #1665

Make email addresses case sensitive when promoting accounts to Program Admin Role

---

bin/localstack/wait

Localstack used to say services were "running", but they have updated to use "available" instead. We debugged by adding  logs to the healthy() check in the wait script and saw that all services were appearing as "available".  Tested and this fixes the browser test failures. 
Paired with @bion

Fix localstack failure

---

infra/containers.yaml

Updated registration URL after new IDCS deployment to fix redirect back to civiform after registration.
#1585

Update registration URI for new IDCS deployment

---

bin/localstack/wait

Make localstack change backwards compatible by accepting "running" and "available". Since localstack is cached locally, we have the old version but github has the new one

Make localstack change backwards compatible

---

universal-application-tool-0.0.1/app/services/program/ProgramServiceImpl.java
universal-application-tool-0.0.1/test/services/program/ProgramServiceImplTest.java

Closes #1698
Makes display mode a required field for the front end when an admin creates a new program.
In the past, when an admin tried to add a program without setting the display mode (public or hidden in index), they would be able to hit create, then they would see a generic backend error message. Now, while usesr are still on the program page, they will get an error message "display mode must be set".
Screenshot: 
Fixes #1698

Closes #1698

---

cloud/azure/locals.tf
cloud/azure/main.tf
cloud/azure/outputs.tf

Change database configuration to block public access to Postgres server and set up private link.
Note: This will need to be rebased and merged after #1726 is merged
Fixes #1728

Terraform: Access PostgreSQL server through private link

---

universal-application-tool-0.0.1/app/controllers/applicant/ApplicantProgramsController.java
universal-application-tool-0.0.1/test/controllers/applicant/ApplicantProgramsControllerTest.java

Deduplicate programs with draft applications. This PR addresses #1713 - it is a temporary fix but not a root cause fix. This change deduplicates programs that fall under the applicants "Continue" section, meaning they have a draft application for that program. 
To determine the root cause of the issue, I needed to add logging to help determine if the duplicate programs with draft applications are coming from the query response.
Addresses #1713

Deduplicate programs with draft applications.

---

browser-test/src/application_csv_download.test.ts
universal-application-tool-0.0.1/app/models/Application.java
universal-application-tool-0.0.1/app/repository/ApplicationRepository.java
universal-application-tool-0.0.1/app/services/export/CsvExporter.java
universal-application-tool-0.0.1/test/repository/ApplicationRepositoryTest.java
universal-application-tool-0.0.1/test/services/export/CsvExporterTest.java

Previously, the submit date would get updated each time the db row was updated, which included when a new version of an application was submitted and the old one was marked as obsolete. Now, the submit time is updated when an application is first submitted and when a draft application is submitted, but not when an application changes from active to obsolete or when an application draft is saved. 
Fixes #1711

Correct submit time to only update on application submit

---

universal-application-tool-0.0.1/app/services/export/ExporterService.java

Cache program definition database lookups to reduce export time.
This saves most of the per-row processing time.  Locally 4300 rows went from ~60s to 10s to export.
exportCsv method maintains a cache of Program data so that it's not looked up for every row that pertains to the Program.
Fixes #1747

Cache program definition database lookups to reduce export time.

---

universal-application-tool-0.0.1/build.sbt
universal-application-tool-0.0.1/tailwindbuilder.sbt

The `in` keyword is deprecated in sbt in favor of `/` syntax. This updates our build files to the newer syntax.

Use updated dependency syntax

---

universal-application-tool-0.0.1/package-lock.json
universal-application-tool-0.0.1/package.json

[caniuse-lite](https://github.com/browserslist/caniuse-lite) keeps an eye on our in-browser JS dependencies and let's us know when polyfills are no longer needed as browsers implement new features, among other helpful things.
This PR updates the caniuse database and in the process updates the main package.lock file which appears to be out of sync with main declared dependencies.
The process for updating caniuse is:
1. run `docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd)/universal-application-tool-0.0.1:/usr/src/universal-application-tool-0.0.1 --entrypoint /bin/bash civiform-dev`
1. from inside the container run `npx browserslist@latest --update-db`
Also added a wiki entry for doing this: https://github.com/seattle-uat/civiform/wiki/Updating-caniuse

Update caniuse DB and main package-lock.json file

---

.github/workflows/pr.yaml
bin/build-browser-tests
bin/build-dev
bin/deploy-staging
bin/npm
bin/pull-image
browser-test/browser-test-compose.yml
docker-compose.yml
universal-application-tool-0.0.1/test/app/SecurityBrowserTest.java

Stage 2 of 3 for moving away from AWS ECR. Stage 1 was uploading logging in to docker hub and uploading our main image. 
This PR switches to using docker hub for all day-to-day docker image management while continuing to upload images to AWS ECR in case there's a problem with our docker hub approach.
The final stage will be removing ECR from the regular development cycle altogether.

Use docker hub container registry for everything except deployment

---

universal-application-tool-0.0.1/app/auth/ProfileUtils.java
universal-application-tool-0.0.1/app/controllers/SupportController.java
universal-application-tool-0.0.1/app/filters/ValidAccountFilter.java
universal-application-tool-0.0.1/app/views/support/UnconfirmedIdcsEmailBugView.java
universal-application-tool-0.0.1/conf/routes

WORK IN PROGRESS
Doc on the filter feature used in this PR: https://www.playframework.com/documentation/2.8.x/JavaHttpFilters
Screencap of the support page:

Fix placeholder account bug

---

.github/workflows/direct-deploy.yaml

Adds a new github actions workflow for performing a prod deployment without first running the staging probers. Hopefully we won't need this, but some recent turbulence on staging along with an urgent prod incident may require it.

Add github workflow for deploying prod without first running probers

---

browser-test/src/address.test.ts
universal-application-tool-0.0.1/app/assets/javascripts/validation.ts

Error validation shows on optional question if it is empty and the required question has error. This change ensures errors only show when a question is required or (if it's optional), the errors will only show if that question is partially filled in.
Fixes #1652

Only show errors when a question is required or partially filled in

---

bin/build-and-push

Tagging builds uploaded to Docker Hub as per [CiviForm Federated Deployment Design](https://docs.google.com/document/d/1xLlKwq-2lkAOFPpgu0t1HQgbzkBwXBfdsICdo0udf48/edit):
> All merged pull requests trigger a snapshot image build tagged with SNAPSHOT-[short commit SHA]-[date in unix seconds].

Tag builds with commit SHA and timestamp

---

browser-test/package.json
browser-test/src/application_review.test.ts
browser-test/src/support/admin_questions.ts
browser-test/yarn.lock
universal-application-tool-0.0.1/app/views/admin/questions/QuestionEditView.java

Pass in the submittable param to the buildDemographicFields function which makes the radio's uneditable in the view only mode and editable in the edit question mode. 
Fixes #1746

Disable the export/no export/ export obfuscated radio buttons in View Mode

---

.github/workflows/push.yaml

It used to be we deployed to staging as part of the build-and-push task. I removed that code since it seemed a poor place to do it given the name and responsibility of the task and didn't notice that the deploy-staging task only run if there were changes in `infra/*`. This PR makes that step run on every merge into main.

Deploy staging on all merges into main

---

universal-application-tool-0.0.1/conf/application.conf

To show the buttons on staging we need to pass in the staging url to the application, adding this to pass that in

Allowig the staging hostname to be set from the application conf

---

bin/sbt
universal-application-tool-0.0.1/app/services/export/CsvExporter.java
universal-application-tool-0.0.1/app/services/export/ExporterService.java
universal-application-tool-0.0.1/app/services/program/ColumnType.java
universal-application-tool-0.0.1/test/services/export/CsvExporterTest.java

column type enum renaming:
`APPLICANT` -> `APPLICANT_ANSWER`
`ID` -> `APPLICATION_ID`
and added a new column type of `APPLICANT_ID`
fixes https://github.com/seattle-uat/civiform/issues/1735

Include applicant ID in program CSV export

---

Dockerfile

A [recent change to openjdk11](https://bugs.openjdk.java.net/browse/JDK-8278221?jql=project%20%3D%20JDK%20AND%20fixVersion%20%3D%2013-pool) changed some behavior related to "." in directory names. It now throws an exception if it finds one.
I attempted to fix this by removing the "."s from the java app directory name [see PR](https://bugs.openjdk.java.net/browse/JDK-8278221?jql=project%20%3D%20JDK%20AND%20fixVersion%20%3D%2013-pool) but that did not apparently do the trick.
For now this fix specifies the version of openjdk we'd been using successfully. Eventually we'll need to figure out how to upgrade but this unblocks CI for the time being.

Specify specific openjdk11 image version

---

.github/workflows/cron.yaml
.github/workflows/direct-deploy.yaml
.github/workflows/push.yaml

Allows manually triggering the CI workflow from the GitHub web UI. See https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow

Enable manually triggering CI workflow

---

bin/dev-restore-db
bin/dump-dev-program-config

The dump script appeared to work but actually generates a corrupted binary archive, I think because docker might be doing something to stdout output. This change fixes that by mounting the project directory into the docker image and writing the archive file in there instead of from the output from docker.
The line continuation in the restore script was wrong.

Fix dev dump and restore scripts

---

.github/workflows/pr.yaml
.github/workflows/push.yaml
.gitignore
cloud/shared/validate_variable_definitions.py
cloud/shared/validate_variable_definitions_test.py
cloud/shared/variable_definitions.json

Adds a CI check that runs for each PR and `main` merge to ensure that each deployment variable definition:
1. uses a unique name
2. has the required fields for its type

Validate deployment variable definitions

---

cloud/azure/modules/app/locals.tf
cloud/azure/modules/app/main.tf
cloud/azure/modules/app/variables.tf
cloud/deploys/staging_azure/README.md
cloud/deploys/staging_azure/main.tf
cloud/deploys/staging_azure/variables.tf

Remove `postgres_admin_password` and `app_secret_key` variables and instead retrieve these values from Azure Key Vault
Fixes #1839

Store database password and app secret key in Azure Key Vault

---

browser-test/src/application_review.test.ts
universal-application-tool-0.0.1/app/services/applicant/Block.java

To determine if an application is ok to submit or requires more answers from the applicant, we count the number of active blocks (i.e. blocks that are not hidden by predicate logic) and compare that with the number of active blocks that are completed (answered) or skipped if Optional. This caused a bug where blocks that have no questions would count towards the total of active but incomplete blocks, making it impossible to complete the application.
This change alters the logic for calculating block completion state to be true if the block has no questions.
Verified the updated test catches this bug:
Fixes #1877

Blocks are complete in program if they have no questions

---

.github/workflows/pr.yaml
Dockerfile
browser-test/bin/wait_for_server_start_and_run_tests.sh
formatter.Dockerfile
prod.Dockerfile
universal-application-tool-0.0.1/app/controllers/dev/DatabaseSeedController.java
universal-application-tool-0.0.1/app/models/Application.java
universal-application-tool-0.0.1/app/models/EbeanServerConfigStartup.java
universal-application-tool-0.0.1/app/models/Models.java
universal-application-tool-0.0.1/app/models/Version.java
universal-application-tool-0.0.1/app/repository/ApplicationRepository.java
universal-application-tool-0.0.1/app/repository/ProgramRepository.java
universal-application-tool-0.0.1/app/repository/QuestionRepository.java
universal-application-tool-0.0.1/app/repository/StoredFileRepository.java
universal-application-tool-0.0.1/app/repository/UserRepository.java
universal-application-tool-0.0.1/app/repository/VersionRepository.java
universal-application-tool-0.0.1/app/services/applicant/JsonPathProvider.java
universal-application-tool-0.0.1/app/services/cloud/aws/SignedS3UploadRequest.java
universal-application-tool-0.0.1/app/services/question/types/QuestionDefinition.java
universal-application-tool-0.0.1/build.sbt
universal-application-tool-0.0.1/project/build.properties
universal-application-tool-0.0.1/project/plugins.sbt
universal-application-tool-0.0.1/test/app/BaseBrowserTest.java
universal-application-tool-0.0.1/test/repository/WithPostgresContainer.java
universal-application-tool-0.0.1/test/support/ResourceCreator.java

Upgrades:
SBT versions higher than 1.3.13 (current project version) are not compatible with play-ebean 6.0.0 (current project version) so these need to be upgraded together.
outstanding issues:
closes https://github.com/seattle-uat/civiform/issues/1942

Upgrade deps: sbt and play-ebean

---

cloud/azure/main.tf
cloud/azure/modules/app/main.tf
cloud/azure/modules/app/variables.tf
cloud/deploys/dev_azure/main.tf
cloud/deploys/dev_azure/variables.tf
cloud/deploys/staging_azure/README.md
cloud/deploys/staging_azure/main.tf
cloud/deploys/staging_azure/variables.tf

Fixes permissions and expands README for setting up keyvault integration. The biggest change was creating the key vault in a separate resource group, since in a real deployment, it will be set up before the terraform-managed resources.

Update permissions and expand README for keyvault

---

universal-application-tool-0.0.1/app/views/dev/DatabaseSeedView.java

The new version of play-ebean configures the object serializer to by default throw an exception if a bean is missing. Most of these were caught in https://github.com/seattle-uat/civiform/pull/1860 but this one got missed.
fixes https://github.com/seattle-uat/civiform/issues/1953

Allow empty beans in db seed view object mapper

---

bin/lib.sh
cloud/azure/bin/deploy
cloud/azure/bin/lib.sh
cloud/shared/bin/deploy
cloud/shared/bin/lib.sh
cloud/shared/bin/validate_cloud_provider

Puts the pieces in place to delegate deployment commands from the deployment repo to executables in the main repo and ensures the delegated command has access to shell script library code. See also https://github.com/civiform/civiform-deploy/pull/2
The order of operations for a command run from the deployment repo is:
1. load the deployment repo's shell library code
1. load the deployment repo's civiform configuratoin
1. resolve the git revision for the main repo the command should run in
1. exec the `cloud/shared` version of the command in the main repo
1. resolve the cloud provider (report an error if the cloud provider is invalid or missing)
1. exec the provider-specific version of the command in the main repo
1. load the shell library code in bin/lib.sh
1. load the cloud …

Scaffolding for deployment command delegation

---

cloud/azure/modules/app/locals.tf
cloud/azure/modules/app/main.tf
cloud/azure/modules/app/variables.tf

We recently discovered that this firewall prevents SAS URLs from working from any IP address that isn't explicitly allowlisted (like an end user's IP address) which is not what we want. We should secure our storage account using user permissions instead.

Remove firewall for Azure Storage

---

Dockerfile

I recently discovered that our dev server doesn't run properly on M1 macs due to an incompatibility between the AdoptOpenJDK image we're using and the M1 Mac's ARM64 architecture. This workaround allows us to use an alternative base image by passing in a platform argument when building the image. M1 Mac users will need to use the `USE_LOCAL_CIVIFORM=1` environment variable, and build the local docker image using `docker build --build-arg PLATFORM=arm64 -t  civiform-dev .`. This info will be added to the wiki once the PR is merged.

Add option to build local docker image for ARM architecture

---

Dockerfile
bin/dev-bash
prod.Dockerfile
universal-application-tool-0.0.1/package-lock.json

Pin NPM version and use latest package versions

---

cloud/azure/modules/app/main.tf

Currently our terraform configs don't send http logs from the app so this configures the http logs to be correctly generated (otherwise we only generate logs on start up failures)

adding the http logs config

---

universal-application-tool-0.0.1/app/models/Account.java
universal-application-tool-0.0.1/conf/evolutions/default/36.sql

Adds a new authority_id field to Accounts to serve as a unique ID. Email is not unique in OIDC but that has been assumed and relied on.
Part of addressing #1793

Add accounts.authority_id to serve as a new unique account identifier.

---

universal-application-tool-0.0.1/app/auth/oidc/IdcsProfileAdapter.java
universal-application-tool-0.0.1/app/auth/oidc/OidcCiviFormProfileAdapter.java
universal-application-tool-0.0.1/app/controllers/SupportController.java
universal-application-tool-0.0.1/app/repository/ApplicationRepository.java
universal-application-tool-0.0.1/app/repository/VersionRepository.java
universal-application-tool-0.0.1/app/services/cloud/aws/SimpleEmail.java
universal-application-tool-0.0.1/app/views/components/TextFormatter.java

Make all java loggers be private static final and use lowercase naming as they are not immutable objects per the style guide.
Fixes #2012

Fix java logger naming and keywords.

---

universal-application-tool-0.0.1/app/services/applicant/ApplicantData.java
universal-application-tool-0.0.1/test/services/applicant/ApplicantServiceImplTest.java

In the case of the applicant having at least four names or just one name, simply the first name (display name) is returned as-is instead of "Anonymous Applicant." 
Added additional unit tests to correspond to the four cases of the setUserName() method: getApplicantName() returns "Name" if the display name has 1 name (0 spaces), "Last, First" for 1 space (2 names), "Last, First" for 2 spaces (3 names), and "First Second Third Fourth [...]" for 3+  spaces (4+ names).
Fixes #2000

Fix display of long names and single names

---

cloud/azure/bin/lib/key_vault.sh
cloud/azure/bin/lib/storage.sh

Noticed a bug where the script wouldn't assign a role to a user if they had that role in a different resource group. This will scope the assigned roles list to the given resource group.

scope role assignments to resource group

---

universal-application-tool-0.0.1/test/auth/ProfileMergeTest.java

Test data wasn't setting the correct object, though it indirectly had the correct intent I believe.
Renamed to allow for more tests later.

Fix bug in testFailedProfileMerge for incorrect setup

---

bin/dev-pgadmin

This script will pull the docker version of pgadmin and set it up to connect to the dev environment database.

Adding script to load docker version of pgadmin against the dev database

---

cloud/azure/bin/lib/key_vault.sh

This function wasn't working because we were searching stdout while the string we were targeting is logged to stderr.

fix key_vault::has-secret funtion to grep stderr

---

cloud/shared/bin/lib/setup.py

we should not not set the backend config argument

Set backend-config arg when use_backend_config is set to true

---

universal-application-tool-0.0.1/app/assets/javascripts/azure_upload.ts
universal-application-tool-0.0.1/app/services/cloud/azure/BlobStorage.java

Previously, azure file uploads didn't have a content type set so extensions were lost. For whatever reason, Azure SDK defaults to MIME type "application/octet-stream". This PR sets the MIME type to preserve extensions. 
Issue was found in bug bash, not sure if there is an issue number.
Fixes #2101

Set content type for azure file uploads so downloads have a file extension

---

universal-application-tool-0.0.1/app/forms/MultiOptionQuestionForm.java
universal-application-tool-0.0.1/test/controllers/admin/AdminQuestionControllerTest.java
universal-application-tool-0.0.1/test/forms/MultiOptionQuestionFormTest.java

Issue #2013: After a CiviForm admin edits a question to have more options, whether that be adding options to a dropdown or a radio button, that selection is able to be chosen by the applicant initially but is not actually saved when the applicant goes to the review page or the admin exports the user data.
In MultiOptionQuestionForm, there's a field called "nextAvailableId". This field is set with "setNextAvailableId", which is never actually called. To fix this, I set the nextAvailableId every time the question options are updated. 
To test, I recreated the question linked in that bug. 
Here, I am picking Grandparent, which was added later on as the 4th option: 
I do the same with this edited radio button question:
As you can see here, Grandparent now shows up in both places instead of …

Correctly set next ID for MultiOptionQuestionForm

---

universal-application-tool-0.0.1/app/auth/oidc/OidcCiviFormProfileAdapter.java
universal-application-tool-0.0.1/app/repository/UserRepository.java
universal-application-tool-0.0.1/test/auth/oidc/OidcCiviFormProfileAdapterTest.java
universal-application-tool-0.0.1/test/repository/UserRepositoryTest.java

OidcCiviFormProfileAdapter looks up users based on their authority_id now, falling back to email in legacy situations where users don't have an authority_id.
The UserRepository.java lookup has a behavior of creating an Applicant if missing when an Account exists. This is copied forward for the lookup by Authority ID case.  The existing behavior is not well understood, but in theory if a TI lookup up a resident email and there's an Account but not Applicant, then the code thinks that should be corrected.  It's unclear how that situation would actually occur and may be WAI for an old design from what we actually have.  So in theory that correction flow may never happen, but doing it in both cases shouldn't be able to cause harm either.
Fixes #1793

Add primary OIDC user lookup by Account.authority_id

---

Dockerfile

Reverts seattle-uat/civiform#2130
Going to need to revert this, since I started seeing this error. Rolling back the version fixes it:
```
civiform  | [error]   ZIP file can't be opened as a file system because an entry has a '.' or '..' element in its name
civiform  | [error] com.typesafe
civiform  | [error] /usr/src/universal-application-tool-0.0.1/app/auth/FakeAdminClient.java:6:1: cannot access com.typesafe.config
civiform  | [error]   ZIP file can't be opened as a file system because an entry has a '.' or '..' element in its name
civiform  | [error] com.typesafe.config
civiform  | [error] /usr/src/universal-application-tool-0.0.1/app/auth/FakeAdminClient.java:10:1: cannot access org.pac4j.core
civiform  | [error]   ZIP file can't be opened as a file system because an entry has a '.' …
```

Revert "Update dependency bellsoft/liberica-openjdk-alpine to v11.0.14"

---

universal-application-tool-0.0.1/app/auth/saml/InvalidSamlProfileException.java
universal-application-tool-0.0.1/app/auth/saml/SamlCiviFormProfileAdapter.java
universal-application-tool-0.0.1/test/auth/ProfileMergeTest.java

SamlCiviFormProfileAdapter looks up users based on their authority_id now. This ID is built by combining the subject and issuer ID.
- [ X] Created tests which fail without the change (if possible)

Add authority_id to SAML profile and use as primary identifier

---

cloud/shared/bin/lib.sh

I was getting an error message ```cloud/shared/bin/lib.sh: line 9: CLOUD_LIB_DIR: readonly variable``` when I tried to run the Azure deploy command. This is potentially a fix

Fix for Azure deploy script

---

cloud/azure/modules/app/main.tf
cloud/azure/templates/azure_saml_ses/main.tf
cloud/deploys/dev_azure/main.tf

Also pinning the provider version and letting renovatebot manage it so we won't get unexpected changes like this again.
https://github.com/hashicorp/terraform-provider-azurerm/blob/4bea503e4bce5978f9b822fb9eb32b45de70d89f/website/docs/guides/3.0-upgrade-guide.html.markdown

Update Azure terraform code for compatibility with v3 azurerm provider

---

cloud/azure/bin/lib/key_vault.sh
cloud/azure/bin/setup-keyvault

(otherwise re-running the script fails)
Use the azure cli to test if the keyvault already exists before attempting to recreate it. 
If your deploy setup fails partway through, trying to re-create an already existing keyvault returns an error and causes the script to fail.

Check if the keyvault already exists before creating 

---

browser-test/src/question_delete.test.ts
universal-application-tool-0.0.1/app/repository/QuestionRepository.java
universal-application-tool-0.0.1/app/services/question/QuestionServiceImpl.java
universal-application-tool-0.0.1/test/services/question/QuestionServiceImplTest.java

1. Fixes discardDraft to also update Questions that reference the discarded draft, and prevents discarding the very first draft.
The code already handled programs but didn't account for enumeration references which leaves those in an invalid state.
2. The behavior of non-existent -> DRAFT -> discard was allowable on all drafts and largely undefined.  This could create invalid state if the draft was referenced before discard.  EG programs or enumerated questions if one referenced the discard question.
The code now disallows discarding the very first draft (through exception) rather than allowing invalid state to be silently created. We can allow it in the future but it'd be more complicate code, as we would have to detect tif he situation is or is not permissible.  
Fixes #2249

Fix behavior of discardDraft(Question) to remove silent creation of invalid data.

---

cloud/azure/bin/lib/azure.sh

The canary hard coded the civiform container name but we actually want to use the env variables
Fixes #2266

Use Env Variables for deploy script

---

cloud/azure/bin/lib/key_vault.sh
cloud/azure/bin/lib/storage.sh
cloud/azure/bin/setup-keyvault
cloud/azure/bin/setup-saml-keystore
cloud/azure/templates/azure_saml_ses/bin/setup.py

Update the generation of secrets to be more resilient, and not re-generate secrets that already exist
-Allow the deploy script to be re-run to account for errors (without it re-creating the login radius cert or overriding set secrets)
-Don't accept blank lines for secrets
-Lint files

Make dev secret generation a little easier

---

universal-application-tool-0.0.1/build.sbt
universal-application-tool-0.0.1/conf/application.conf

- Changes the sbt incremental compile options to fully recompile if >10% of files have changes (vs the default of 50%)
- Changes the max number of transitive steps to 2 (vs 3)
- Avoids triggering repeated unnecessary recompilation when the tailwinds generator reruns (whenever build.sbt gets reloaded)
Attempts to fix #2230

Adjust sbt compile options to avoid incremental compile loops

---

universal-application-tool-0.0.1/test/services/program/ProgramDefinitionTest.java

Make test actually evaluate something.  A new linter will fail on this.  #2256

Make no-op test evaluate something to appease linter.

---

universal-application-tool-0.0.1/app/views/admin/questions/QuestionsListView.java

Add a `<BR>` after each question action for clearer alignment and usability.
Before:
After:

Line break question action items to be clearer.

---

cloud/deploys/seattle/bin/pull-prod-admin-config

Fixing the pull-prod-admin-config script which has an incorrect parameter for pg_dump. Finally remembered to check this back in. The script fails before this fix.

The pull-prod-admin-config script an incorrect parameter

---

universal-application-tool-0.0.1/app/repository/ApplicationRepository.java
universal-application-tool-0.0.1/app/services/applicant/ApplicantService.java
universal-application-tool-0.0.1/app/services/export/CsvExporter.java
universal-application-tool-0.0.1/app/services/export/ExporterFactory.java
universal-application-tool-0.0.1/test/services/export/AbstractExporterTest.java
universal-application-tool-0.0.1/test/services/export/CsvExporterTest.java
universal-application-tool-0.0.1/test/support/ResourceCreator.java

This attempts to improve the demography CSV export performance a bit. This PR eager loads program, applicant, and account data for each application, removing several N+1 queries.
Another area for improvement is in reducing the number of queries to load a program definition, specifically syncing the program definition's questions. I'm electing to address that in a separate PR.
Meant to improve https://github.com/seattle-uat/civiform/issues/2267 but won't necessarily fix it

Reduce N+1 queries for CSV export

---

browser-test/src/file.test.ts
universal-application-tool-0.0.1/app/assets/javascripts/azure_upload.ts
universal-application-tool-0.0.1/app/assets/javascripts/validation.ts
universal-application-tool-0.0.1/app/views/dev/AzureStorageDevViewStrategy.java

On-page file upload validation now validates ALL file upload questions in a block rather than assuming there is just one. Also fixes issue where Azure uploads threw an uncaught exception if a required file hadn't been uploaded (rather than showing a validation error to the user).
Note: Only one file upload is allowed per block by the admin controller. That said, there's not a strong need to bake that in at the validation level.
While here, I also:
1) Renamed `validateFooQuestion` method names to `validateFooQuestions` to indicate they would validate all questions rather than just a single question.
2) Added focused tests for file upload questions (which exposed a bug in the Azure file upload path, also fixed here).
Fixes #1695; Fixes #1696

Validate all file upload inputs

---

universal-application-tool-0.0.1/app/views/admin/versions/VersionListView.java
universal-application-tool-0.0.1/app/views/style/AdminStyles.java

- Increase the max width of the `main` element for the admin so Seattle's question content doesn't require a horizontal scrollbar
- Reverse the list of versions so most recent is at the top

Admin UI tweaks

---

bin/localstack/mk-s3

Localstack appears to be rejecting these in CI.

Set a locationConstraint when creating an S3 bucket for CI tests

---

test-support/test_oidc_provider.js

Conditionally uses a supplied port instead of the default 3380.  This is necessary to address #1938 so that the local server can specify a different port than the unit tests.

Add ability to specify the port the test OIDC provider runs on

---

universal-application-tool-0.0.1/app/services/applicant/question/ApplicantQuestion.java
universal-application-tool-0.0.1/app/services/applicant/question/EnumeratorQuestion.java
universal-application-tool-0.0.1/app/services/applicant/question/IdQuestion.java
universal-application-tool-0.0.1/app/services/applicant/question/TextQuestion.java
universal-application-tool-0.0.1/app/views/questiontypes/AddressQuestionRenderer.java
universal-application-tool-0.0.1/app/views/questiontypes/ApplicantQuestionRenderer.java
universal-application-tool-0.0.1/app/views/questiontypes/ApplicantQuestionRendererImpl.java
universal-application-tool-0.0.1/app/views/questiontypes/CheckboxQuestionRenderer.java
universal-application-tool-0.0.1/app/views/questiontypes/CurrencyQuestionRenderer.java
universal-application-tool-0.0.1/app/views/questiontypes/DateQuestionRenderer.java
universal-application-tool-0.0.1/app/views/questiontypes/DropdownQuestionRenderer.java
universal-application-tool-0.0.1/app/views/questiontypes/EmailQuestionRenderer.java
universal-application-tool-0.0.1/app/views/questiontypes/EnumeratorQuestionRenderer.java
universal-application-tool-0.0.1/app/views/questiontypes/FileUploadQuestionRenderer.java
universal-application-tool-0.0.1/app/views/questiontypes/IdQuestionRenderer.java
universal-application-tool-0.0.1/app/views/questiontypes/NameQuestionRenderer.java
universal-application-tool-0.0.1/app/views/questiontypes/NumberQuestionRenderer.java
universal-application-tool-0.0.1/app/views/questiontypes/RadioButtonQuestionRenderer.java
universal-application-tool-0.0.1/app/views/questiontypes/StaticContentQuestionRenderer.java
universal-application-tool-0.0.1/app/views/questiontypes/TextQuestionRenderer.java
universal-application-tool-0.0.1/test/services/applicant/question/EnumeratorQuestionTest.java
universal-application-tool-0.0.1/test/services/applicant/question/IdQuestionTest.java
universal-application-tool-0.0.1/test/services/applicant/question/TextQuestionTest.java

Inverting ApplicantQuestionRenderer pattern from having implementations call renderInternal, which creates the wrapping div to instead have them implement renderTag.
Why? Simpler to ensure all input-providing question types are wrapped in the same div.
ApplicantQuestionRenderer was converted to an interface since static questions don't render with any input values.
For consistency, also switched error validation for a few question types from `getQuestionErrors` to `getAllTypeSpecificErrors`. The former errors are shown above any specific field, while the latter are shown for specific fields.
Noticed this as part of #1944, since server-side rendering of errors will likely be updated for various question types.

ApplicationQuestionRenderer refactoring to make subclasses responsible for providing a method to render form content

---

bin/localstack/mk-s3

Now that we potentially reuse the same Docker container for `bin/run-dev`, it's possible that the S3 bucket might already exist in the `localstack` container. This leads to the following error:
`An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it.`
Per @kmcnellis, we can simply check for the existence of the bucket prior to trying to create it.

Check for existence of S3 bucket prior to creating it in localstack.

---

bin/pull-image

OIDC and localstack have more recent versions right now specifically, that aren't being pulled down without this.

Add dev dependency images as they aren't automatically updated.  

---

universal-application-tool-0.0.1/build.sbt

bintray.com is not maintained and getting turned down. it doesn't appear we actually need it for resolving dependencies anyway.
fixes https://github.com/seattle-uat/civiform/issues/2250

Remove bintray resolver

---

universal-application-tool-0.0.1/app/services/applicant/Block.java
universal-application-tool-0.0.1/app/services/applicant/ReadOnlyApplicantProgramServiceImpl.java
universal-application-tool-0.0.1/app/services/applicant/question/AddressQuestion.java
universal-application-tool-0.0.1/app/services/applicant/question/ApplicantQuestion.java
universal-application-tool-0.0.1/app/services/applicant/question/CurrencyQuestion.java
universal-application-tool-0.0.1/app/services/applicant/question/DateQuestion.java
universal-application-tool-0.0.1/app/services/applicant/question/EmailQuestion.java
universal-application-tool-0.0.1/app/services/applicant/question/EnumeratorQuestion.java
universal-application-tool-0.0.1/app/services/applicant/question/FileUploadQuestion.java
universal-application-tool-0.0.1/app/services/applicant/question/IdQuestion.java
universal-application-tool-0.0.1/app/services/applicant/question/MultiSelectQuestion.java
universal-application-tool-0.0.1/app/services/applicant/question/NameQuestion.java
universal-application-tool-0.0.1/app/services/applicant/question/NumberQuestion.java
universal-application-tool-0.0.1/app/services/applicant/question/Question.java
universal-application-tool-0.0.1/app/services/applicant/question/QuestionImpl.java
universal-application-tool-0.0.1/app/services/applicant/question/SingleSelectQuestion.java
universal-application-tool-0.0.1/app/services/applicant/question/StaticContentQuestion.java
universal-application-tool-0.0.1/app/services/applicant/question/TextQuestion.java
universal-application-tool-0.0.1/app/services/export/ExporterService.java

Introducing a base class for this since the majority of question types implement this as confirming that a value exists for any of the paths returned by `getAllPaths`. This also allowed for consolidating similar implementations of `assertQuestionType`. 
Noticed this as part of Issue #1944, since server-side rendering of errors will likely be updated for various question types.

Create base class for applicant Question to reduce duplicate implementation of isAnswered

---

universal-application-tool-0.0.1/app/services/question/types/QuestionDefinition.java
universal-application-tool-0.0.1/app/views/admin/questions/QuestionConfig.java
universal-application-tool-0.0.1/app/views/admin/questions/QuestionEditView.java
universal-application-tool-0.0.1/test/services/question/types/QuestionDefinitionTest.java
universal-application-tool-0.0.1/test/views/admin/question/QuestionConfigTest.java

Questions that allow multiple selections (e.g. checkbox) presently allow configuration of the minimum / maximum number of selectable choices where:
1) Negative inputs are allowed
2) Minimum number of selections can be greater than the maximum number of selections
3) Minimum / maximum selections can be greater than the number of choices
This adds additional error validation / tests for this and makes a few additional improvements I noticed while testing the issue:
* Toasts with the validation errors were disappearing after 3 seconds (the default behavior). Now we show it indefinitely (but still dismissable) under the assumption that the admin will dismiss the toast after fixing the errors or resubmitting the form.
* When a validation error occurred, any newly added choices for the …

More validation of the multi-select question type

---

browser-test/browser-test-compose.yml
browser-test/src/dev_file_upload.test.ts
universal-application-tool-0.0.1/app/views/AzureFileUploadViewStrategy.java
universal-application-tool-0.0.1/app/views/ViewUtils.java
universal-application-tool-0.0.1/app/views/dev/AzureStorageDevViewStrategy.java
universal-application-tool-0.0.1/build.sbt

We've been using https://webjars.org to load javascript libraries (just one so far) but the azure blob storage library specifically causes a Java compilation error on the latest patch version of Java 11.
This change is to unblock upgrading to Java 11.0.14 [while we figure out how to resolve the webjar problem](https://github.com/webjars/webjars/issues/1967).
Unblocks https://github.com/seattle-uat/civiform/pull/2316, https://github.com/seattle-uat/civiform/issues/2315

Use CDN to load azure blob browser lib

---

Dockerfile
prod.Dockerfile

See Issue #2315 for context. This only updates  the x86/amd64 version, and does not bump the arm64 version, since it is [not yet available](https://hub.docker.com/r/bellsoft/liberica-openjdk-alpine/tags). arm64 is not urgent (to my knowledge) since it is only used for local Mac M1 development.
Fixes (in part) issue #2315.

Update OpenJDK to 11.0.14.1

---

cloud/azure/bin/setup-keyvault

Accidentally removed the temporary secret generation of "adfs-client-id" in  #2280

Re-add the missing temp adfs-client-id 

---

.dockerignore

We have a reference to universal-application-tool in our `.dockerignore` file. This performs the same rename as in https://github.com/seattle-uat/civiform/pull/2360.

Updating dangling reference to universal-application-tool

---

cloud/azure/modules/app/role-assignments.tf

Looks like azure changed the name of this role so we also need to change it in our terraform. [AzRole Website with Details of role name change](https://www.azadvertizer.net/azrolesadvertizer/e5e2a7ff-d759-4cd2-bb51-3152d37e2eb1.html#:~:text=Lets%20you%20perform%20backup%20and,Backup%20on%20the%20storage%20account.&text=Old%20DisplayName%3A%20'Storage%20Account%20Backup,Backup%20on%20the%20storage%20account.)

Storage Account Backup Contributor Role -> Storage Account Backup Contributor

---

.github/workflows/pr.yaml
cloud/azure/README.md
cloud/azure/bin/lib/azure.sh
cloud/azure/modules/bastion/main.tf
cloud/azure/templates/azure_saml_ses/bin/setup.py
cloud/shared/bin/lib/terraform.sh

Terraform deploys are failing due to not being able to find a file, there's a terraform resource that lets us create the initial key so we can use that here. note this is purely to make the azure terraform code happy as we prevent all ingres to the machine and then to access the bastion you have to manually add your own key to it via the scripts
Fixes #2383

Using Terraform Resource to generate ssh key

---

server/app/views/HtmlBundle.java

Removed a duplicate metadata element in the header tag that was already in the head tag.
Fixes #2258

Remove duplicated metadata in header tag

---

bin/vscode-setup
civiform.code-workspace
server/build.sbt

**bin/vscode-setup**
*   Updated the Maven properties indicating that this is Java 11. Fixes a host of problems reported by VSCode around our use of lambdas and other language features. If unspecified, this defaults to Java 5.
**civiform.code-workspace** 
*   Inverted the order of project definitions. Prior to this, Metals didn't detect a SBT and didn't automatically compile.
*   Added .bloop / target files to list of exemptions for searching. This prevents these files from showing in the quick file open candidate list.
**server/build.sbt**
*   Marked auto-value-parent as [pomOnly](https://stackoverflow.com/q/45608473) since it doesn't have a corresponding JAR. Without this, the call to makePom from vscode-setup adds this as a dependency and VSCode fails to resolve it, preventing any …

Updates to make VSCode work by default with Metals.

---

server/app/controllers/admin/AdminProgramBlockQuestionsController.java
server/app/repository/VersionRepository.java
server/test/controllers/admin/AdminProgramBlockQuestionsControllerTest.java

The Question Bank contains revision IDs, currently when one is added to a program that specific ID is added even if is old and not an Active or Draft revision. This happens if the UI has been loaded, but Question changes have occurred external to it.
We now lookup the latest revision of the question and add that instead.
Fixes #2375

Question bank additions now use latest revision of the question

---

.github/workflows/pr.yaml
browser-test/browser-test-compose.yml
browser-test/src/support/index.ts
server/app/views/ApplicantUtils.java
server/app/views/admin/programs/ProgramApplicationListView.java

The program application review page displays a list of applications identified by applicant name and application ID. [A previous PR](https://github.com/seattle-uat/civiform/pull/2353) changed the way applicant name is handled in the system, which introduced a bug where a missing applicant name is displayed as `optional.empty`:
This PR fixes that to display the en-US message for `GUEST` when the applicant name is missing:
Additionally, [another recent PR](https://github.com/seattle-uat/civiform/pull/2348) changed the browser test compose to using the `civiform-dev` image, which doesn't match what CI builds to run the server for browser tests. This prevented the correct code from running in the server for the test run, allowing the tests to pass on the PR that introduced the regression.

Fix rendering applicant name in program application review

---

server/app/auth/ApiKeyGrants.java
server/app/models/Account.java
server/app/models/ApiKey.java
server/app/models/Models.java
server/app/repository/ApiKeyRepository.java
server/conf/evolutions/default/38.sql
server/test/auth/ApiKeyGrantsTest.java
server/test/repository/ApiKeyRepositoryTest.java

Persistence layer for API keys

---

server/build.sbt

Adds the -q flag to tests, which allows standard out to be printed to the command line if a test fails 
[docs](https://github.com/sbt/junit-interface)

Allow the stdout to be seen when a test fails

---

server/app/repository/ProgramRepository.java
server/app/services/program/ProgramServiceImpl.java
server/test/repository/ProgramRepositoryTest.java
server/test/services/program/ProgramServiceImplTest.java

When a program is created, CiviForm checks to ensure there isn't already a program with the same name. This is critical because the program name is immutable, and used to link multiple program records as versions of the same program.
The program slug -- the name formatted for use in a URL -- must also be unique for the deep link feature to work. However it is possible to have two name strings that are different that slugify to the same value. This change adds a validation check to ensure new program names do not slugify to slugs that collide with existing program slugs.

Prevent program name slug collisions

---

server/build.sbt

fixes a CVE related to spring, which we don't use: https://github.com/pac4j/pac4j/blob/master/documentation/docs/release-notes.md

Bump pac4j patch version

---

bin/remove-test-env
bin/sbt-test

Adds a script for sbt to run in the unit test environment, and changes `bin/run-test` to use it.
You can run this using `bin/sbt-test` to get the command line, or pass arguments like `bin/sbt-test testOnly <test name>`.
It will start the docker containers needed for the tests in the background, and keep them running so you can do multiple commands without re-loading.  
Run `bin/remove-test-env` to shut down the docker containers.
- Ran scripts to test

Add a script for sbt to run in the unit test environment

---

browser-test/src/question_lifecycle.test.ts
browser-test/src/support/admin_questions.ts
server/app/controllers/admin/AdminQuestionController.java
server/app/forms/QuestionForm.java
server/app/services/question/QuestionServiceImpl.java
server/app/views/admin/questions/QuestionEditView.java
server/test/controllers/admin/AdminQuestionControllerTest.java

Previously, we were only persisting the selected export option when updating a question. We now do this as part of creation as well.
While here, I also updated the UI to preselect the "No Export" option since that's what happens in practice.
Finally, added a browser test to catch regressions in this area.
Fixes #1889

Persist selected export state upon question creation.

---

bin/fmt
bin/pull-image
bin/refresh-styles
bin/run-browser-tests
bin/run-prober
browser-test/bin/fmt

The browser-test and formatter images don't get auto-refreshed.  Add them to the pull-image command and use the pull-image command in their respective scripts.

Make sure all docker containers get refreshed

---

browser-test/browser-test-compose.dev.yml

Running browser-tests locally should use the civiform-dev container, to allow java debugging ports to connect.
- Tested locally by purging all docker images & running
Fixes error introduced in #2297

Use the civiform-dev image for local browsertest

---

cloud/shared/bin/doctor_impl

- Check for Docker installation in cloud/shared/bin/doctor for both AWS and Azure.
- Fix should_skip check for AWS CLI. Previously, we were skipping this check for AWS and Azure. We should be checking this for both.

Fix cloud/shared/bin/doctor checks based on selected cloud provider.

---

server/app/services/applicant/ReadOnlyApplicantProgramServiceImpl.java
server/app/services/applicant/RepeatedEntity.java
server/test/services/applicant/ReadOnlyApplicantProgramServiceImplTest.java
server/test/services/applicant/predicate/JsonPathPredicateGeneratorTest.java
server/test/services/applicant/question/ApplicantQuestionTest.java

When assembling a program, pass a repeated entity's block's visibility to the entity.  Then when testing if a repeated entity block is visible, test all its parent's conditions as well.
Fixes #1886

Add a check for the visibility of repeated entity's parents

---

bin/vscode-setup

Adapts the `bin/vscode-setup` script to handle that containers generated by `bin/sbt` have a new naming convention since https://github.com/seattle-uat/civiform/pull/2297.

Fix vscode-setup to use the docker compose name.

---

server/app/auth/CiviFormProfileAdapterHelper.java
server/app/auth/CiviFormProfileMerger.java
server/app/auth/oidc/AdfsProfileAdapter.java
server/app/auth/oidc/IdcsProfileAdapter.java
server/app/auth/oidc/OidcCiviFormProfileAdapter.java
server/app/auth/saml/SamlCiviFormProfileAdapter.java
server/test/auth/CiviFormProfileMergerTest.java
server/test/auth/ProfileMergeTest.java

SamlCiviFormProfileAdapter and OidcCiviFormProfileAdapter both conduct a 3 way merge between the database, session context, and authentication provider. This PR extracts the 3 way merge logic into a new class, CiviFormProfileAdapterHelper
Fixes #2229

Refactored ProfileAdapter 3 way merge logic into separate class

---

cloud/shared/bin/lib/terraform.sh

The quotes and command substitution `$()` weren't allowing the terraform command to execute correctly.  Instead, it was trying to run (as a command) the results of the terraform command (which was an error, due to a stray missing `\`).
Instead, lets use the recommended solution for storing simple commands, which is bash arrays, evaluated using `"${CMD[@]}"`
- Tested scripts using the github/civiform/civiform-deploy deploy script

Change the terraform command to use arrays so it evaluates properly

---

server/app/assets/javascripts/main.ts
server/app/views/applicant/ApplicantProgramSummaryView.java
server/app/views/style/ReferenceClasses.java

This change disables the submit button on the application review page for 5 seconds after it has been clicked.
See https://github.com/seattle-uat/civiform/issues/2469#issuecomment-1124077383 for rationale.
Note: A nice cleanup on the server side would also be to throw a 500 in these cases rather than creating duplicate applications. That said, we'd still want to prevent the bad data from coming in from the client-side so that the applicant doesn't see a 500.
Fixes #2469

Prevent double-clicking the submit button from submitting multiple applications

---

bin/run-test-ci
server/test/services/MessageKeyTest.java
test-support/unit-test-docker-compose.yml

This serves as a regression test for the issue fixed by https://github.com/seattle-uat/civiform/pull/2459, where `sbt test` returned successful immediately when it couldn't find any files to build. Here we ensure that the evaluated targets includes a well-known test.
Even though the compile steps are cached between invocations of `docker exec sbt`, it still adds ~1 minute to the successful case on my machine. In my opinion, this is acceptable since 1) unit tests still take a fraction of the time for browser tests and 2) we're only performing this assertion in CI (not in `bin/run-test`).
Alternative considered:
* Modifying the GitHub action to have an extra step that performs the grep on the output of the `run-test-ci` command. While possible, this involved some combination of `tee`, …

Adding assertion to run-test-ci that test targets are actually found.

---

server/app/auth/FakeAdminClient.java
server/app/auth/ProfileFactory.java

Some features, such as creating API keys, require user profiles to have an authority_id, even in demo mode. This PR sets a randomized authority_id with the prefix "fake-admin-" so that the value is present in demo mode. The randomness is to prevent collisions when logging in repeatedly as a fake admin.

Set authority_id for fake admins

---

server/app/views/components/FieldWithLabel.java
server/test/views/components/FieldWithLabelTest.java

This pattern is described here: https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA21
Before: When using VoiceOver on Mac, a field with validation errors wouldn't be announced.
After: A field with validation errors is announced as "invalid data".
Fixes #1878

Add aria-describedBy and aria-invalid attributes for FieldWithLabel errors.

---

.github/workflows/scorecards.yml

Move dependencies to explicit version numbers.
This provides better documentation and we update for full releases not every merge as we seem to be getting.

Update scorecards config to use fixed version numbers and not digests

---

.github/workflows/scorecards.yml

I got the version wrong in trying to pin digest hashes to version numbers.  Note this is 1 incremental version behind just to verify depend bot will do the right thing with these version numbers.

Fix upload-sarif version

---

server/app/assets/stylesheets/styles.css

Note: This removes the steppers globally since the original concern was expressed both for applicant UI and admin-facing UI.
Before: <img width="1101" alt="Screen Shot 2022-05-23 at 10 42 07 AM" src="https://user-images.githubusercontent.com/1870301/169877043-39a36f3f-a092-413d-8ac8-51ebb94f2f79.png">
After: 
#1900

Remove number steppers for input[type='number']

---

server/conf/application.conf

Allows configuring the database connection pool size with an environment variable: DATABASE_CONNECTION_POOL_SIZE

Make DB connection pool size configurable

---

server/app/assets/stylesheets/styles.css
server/app/views/components/TextFormatter.java
server/test/views/components/TextFormatterTest.java

Per #1903, light gray isn't accessible. This updates ALL links rendered through the text formatter, including links in:
* Static question content rendered on a "screen"
* Question text / help text
* Program description shown in the list view for applicants
Before: 
After:
Fixes #1903

Update link styling from light gray to action color

---

.github/workflows/tests.yml

It looks like the browser tests can't be run from a fork because the fork doesn't have access to the right secrets. This PR disables requiring secrets to see if that fixes it.
See Slack thread: https://civiform.slack.com/archives/C01QKN2UNMA/p1653350605357309
Fixes Slack thread: https://civiform.slack.com/archives/C01QKN2UNMA/p1653350605357309

Disabled requiring secrets to run CI tests, which should allow the tests to be run from a fork.

---

server/app/views/admin/programs/ProgramApplicationListView.java

This also has the effect of rendering submission dates in the CiviForm time zone rather than UTC.
Before:
After:
Fixes #1905

Render application submission date format consistent with other dates rendered in Admin UI

---

browser-test/src/admin_program_list.test.ts
browser-test/src/support/admin_programs.ts
server/app/assets/javascripts/admin_programs.ts
server/app/views/admin/programs/ProgramIndexView.java
server/app/views/style/ReferenceClasses.java

This is a reland of #2499, which was rolled back due to CI failures stemming from fast updates and EBean's rounding of timestamps to millisecond precision ([details](https://github.com/seattle-uat/civiform/pull/2499#issuecomment-1133325484)).
We fixed the ordering issue in #2524 by ensuring that "publish all drafts" doesn't update Program timestamps. As such, this is purely a reland without the changes `VersionRepository` / `VersionRepositoryTest`. Copying the original description for posterity.
Previously, the program list had no explicit ordering. In practice, this meant that programs were ordered based on their database ID. This meant that the most recently created programs appeared at the end of the list.
As part of #1238, we'll be updating the program list UI and potentially adding …

Order programs by the last modification date in the program admin view

---

.github/workflows/push.yaml
.github/workflows/tests.yml
bin/run-browser-tests-ci
bin/run-prober
browser-test/src/support/index.ts

**Test names**
The current suffix is the name from the `describe` clause. In an ideal world, we'd use something like the test file name (e.g. `admin_program_list.test.ts`), but I haven't figured that out yet. We use a distinct suffix since Playwright gives each video a random UUID name by default. This helps to disambiguate which test corresponds to which video.
**Scripts / GitHub actions**
The necessary plumbing to make the browser video directory available from the container was also added to each script. While debugging our current CI failures, I temporarily enabled video recording so that we can see what's going wrong. We may want to consider enabling this by default and saving on test failure, but I'd like to get a bit more experience with this mechanism prior to doing that.

Add a suffix for video name based on current test. Enable video recording for CI tests

---

docker-compose.dev.yml

In order for your browser to access dev-oidc, it needs to expose a fixed port to the host.  Added this to the dev docker-compose overrides.

Make sure to map dev-oidc to a fixed port when running locally

---

.github/workflows/push.yaml

Attempted to run ci workflow manually. The trilom/file-changes-action failed because the payload was empty since it didn't come from a push action. This should now only run that step if the event is from a push.
```Run trilom/file-changes-action@v1.2.4
Error: There was an issue inferring inputs to the action.
Exception: {
"error": "500/inferInput Error",
"from": "inferInput",
"message": "Received event from workflow_dispatch, but received no inputs. {event_name:workflow_dispatch, pr: NaN, before:false, after:false}",
"payload": ""
}
(node:1516) UnhandledPromiseRejectionWarning: Error: {"error":"500/inferInput Error","from":"inferInput","message":"Received event from workflow_dispatch, but received no inputs. {event_name:workflow_dispatch, pr: NaN, before:false, after:false}","payload":""} …
```

Manually running CI workflow failed

---

browser-test/src/support/index.ts

I had a test failure in the probers during a staging deploy likely due to a network hiccup. The IDCS login timed out waiting for the IDCS. Re-running the tests all passed. This just adds some comments to give tips if this fails.
The error:
```
Summary of all failing tests
FAIL src/application_download.test.ts (24.632 s)
● normal application flow › all major steps
page.waitForURL: Timeout 4000ms exceeded.
=========================== logs ===========================
waiting for navigation to "**/#/login*" until "load"
============================================================
99 |     await page.click('#idcs')
100 |     // Wait for the IDCS login page to make sure we've followed all redirects.
> 101 |     await page.waitForURL('**/#/login*')
|                ^
102 |     await …
```

Adding Comment on Browser Test IDCS Login

---

server/app/services/applicant/ApplicantData.java

Guest users always get this logged as an error. Lowering to warning to make it easier to filter logs and adding a note in the logged message.

Make filtering errors in logs slightly easier

---

server/app/views/AwsFileUploadViewStrategy.java
server/app/views/AzureFileUploadViewStrategy.java
server/app/views/FileUploadViewStrategy.java

We now move the input field generation into each specific provider and document that order is input for S3 (as well as the field name of "file").
Fixes #2653; #2589

Fix form field ordering issue that breaks AWS S3 uploads.

---

browser-test/src/file.test.ts
browser-test/src/support/applicant_questions.ts
server/app/assets/javascripts/azure_upload.ts
server/app/services/cloud/azure/BlobStorage.java

Setting content-disposition header for Azure file uploads. This cause…s clicking 'download' to actually download the file as an attachment rather than opening the content in the browser tab.
For more context, see https://github.com/seattle-uat/civiform/issues/2656#issue-1261985761
Fixes #2656; #2589

Downloading an uploaded file (for Azure) now downloads as an attachment rather than opening the content

---

bin/fmt

This is breaking the formatter for some devs and does not appear necessary

Don't specify user when running formatter

---

cloud/aws/modules/custom_domain/main.tf
cloud/aws/modules/custom_domain/variables.tf

This should probably be in post_terraform step in our deploy scripts. Also depends on how the dns records are managed (current setup assumes route53 zone, which may not always be the case).

move custom domain into a module. don't do it by default

---

browser-test/browser-test-compose.dev.yml
docker-compose.dev.yml
test-support/unit-test-docker-compose.dev.yml

They were getting copied only when the container was built, then ignored when edited
- [ x] Ran each env

Make sure that the sbt config files in server/project get live-synced to the docker image

---

server/conf/application.conf

Use mimetypes to decide which files can be gzipped, instead of blacklisting the image asset directory
Leftover change from #2612 (https://github.com/seattle-uat/civiform/pull/2612#discussion_r889610985).

Change gzip blacklist to whitelist using mime types

---

browser-test/src/question_lifecycle.test.ts
server/app/modules/DatabaseSeedModule.java
server/app/repository/QuestionRepository.java
server/app/services/LocalizedStrings.java
server/app/services/question/QuestionService.java
server/app/services/question/QuestionServiceImpl.java
server/app/services/question/types/QuestionDefinitionBuilder.java
server/app/tasks/DatabaseSeedTask.java
server/conf/application.conf
server/conf/application.test.conf
server/test/repository/QuestionRepositoryTest.java
server/test/tasks/DatabaseSeedTaskTest.java

Binds a `DatabaseSeedTask` instance as an eager singleton, which has a constructor that implements seeding logic.
Runs the seeds in a serializable transaction and retries upon failure.
closes https://github.com/seattle-uat/civiform/issues/2484

Find or create canonical questions on server start

---

Dockerfile
bin/build-dev
browser-test/browser-test-compose.dev.yml
docker-compose.dev.yml
server/build.sbt
test-support/unit-test-docker-compose.dev.yml

Runs a full sbt compile on the docker image build, and saves the assets locally (outside of the server directory, so docker volumes don't shadow/override it).  Then on sbt load, pulls from the "remote" (really local) cache into our build directory. 
Seems to reuse ~80% of assets, and speeds up the build more than 50%

Enable the sbt remote cache

---

browser-test/src/delete_database.ts
browser-test/src/support/index.ts
server/app/controllers/dev/DatabaseSeedController.java
server/app/controllers/dev/DevController.java
server/app/views/dev/DatabaseSeedView.java
server/conf/routes

Running probers does not cause an app restart, but it does wipe the database. As a result the canonical questions are missing since they are automatically created when missing only on server start. This change adds a controller action that runs the database seed task and updates the browser tests to do so after wiping the database.

Seed canonical questions before prober runs

---

formatter/fmt

The python formatter is finding python files in dependencies, which clutters the output and takes extra time. This change restricts it to only formatting files in the `cloud/` and `bin/` directories.
```
Start format python
Reformatting ./bin/run-browser-tests-ci-batch
Reformatting ./server/project/target/node-modules/webjars/npm/node_modules/node-gyp/gyp/gyptest.py
Reformatting ./server/project/target/node-modules/webjars/npm/node_modules/node-gyp/gyp/gyp_main.py
Reformatting ./server/project/target/node-modules/webjars/npm/node_modules/node-gyp/gyp/PRESUBMIT.py
Reformatting ./server/project/target/node-modules/webjars/npm/node_modules/node-gyp/gyp/setup.py
Reformatting ./server/project/target/node-modules/webjars/npm/node_modules/node-gyp/gyp/buildbot/buildbot_run.py
Reformatting …
```

Only run python formatter on cloud/ and bin/ dirs

---

browser-test/src/support/index.ts
browser-test/src/trusted_intermediary.test.ts
server/app/auth/FakeAdminClient.java
server/app/auth/ProfileFactory.java
server/app/views/LoginForm.java
server/app/views/applicant/ApplicantLayout.java

Adds a button to the demo mode login page for logging in as a trusted intermediary. Also renames the other buttons to be more clear.
Should help with investigation into https://github.com/seattle-uat/civiform/pull/2722

Add debug button to login as TI

---

.github/workflows/tests.yaml
browser-test/browser-test-compose.dev.yml
browser-test/browser-test-compose.yml

They are using the civiform-dev dockerfile, so the tag should be consistant .

browser tests should use the civiform-dev tag

---

formatter/fmt

Fix a bug where deleting a file caused the formatter to run on the deleted file and get a path not exists. This was discovered when running `bin/fmt` on the deleted file from #2734.
Tested locally by building a new formatter image and confirming that the deleted file from #2734 didn't cause an error.
#1743

Formatter skips deleted files.

---

browser-test/src/trusted_intermediary.test.ts

Fixing test failing due to casing differences in the rendered output

Fixing test failing due to casing differences in the rendered output

---

.github/workflows/tests.yaml
bin/run-browser-tests-ci-batch
browser-test/src/security.test.ts

The ci browser tests batch script is failing silently. The python script always returns 0 so it doesn't trigger the failure on the github action step.
[Example](https://github.com/seattle-uat/civiform/runs/6905881953) see "run_all_tests / run_browser_tests_aws (4)"
[Python docs](https://docs.python.org/3/library/subprocess.html) indicate that the check parameter will cause the subprocess to throw an exception if the exit code is not 0 which in turn has the main process fail with exit code 1.

Browser tests batch script doesn't fail if the subprocess fails

---

browser-test/src/application_download.test.ts
browser-test/src/delete_database.ts
browser-test/src/question_lifecycle.test.ts

Apparently [dropTables](https://github.com/seattle-uat/civiform/blob/main/browser-test/jest.config.js#L7)  is only being run once at the beginning of the test suite, and it seems that messes up `question_lifecycle.test.ts` and `application_download.test.ts` when the whole test suite is run so I added dropTables before both and got a passing test run locally

Fix local browser tests

---

server/app/views/BaseHtmlView.java

Noticed this while investigating adding date filtering to the existing Program Admin applications view. I could also see a case for rendering "Page 0 of 0" and rendering "No results" further down. If there's a strong preference, I can convert to that.
Also, I looked into making the buttons show as disabled when there were no results since they currently give the illusion that clicking them will do something. I didn't pursue that since the styles being used are "private" to LinkElement and I didn't have a good sense of how / where we'd want to break those out. As it stands, this currently seems like a small usability improvement.
Before:
After: 
#1743

Fixing pagination rendering when there are no pages (previously was "Page 1 of 0")

---

cloud/aws/templates/aws_oidc/bin/setup.py

Remove stray $ resulting in invalid bucket names

python string templates don't use $

---

browser-test/src/support/admin_programs.ts

We have a bug where GitHub action test runs don't use the locally built server image. That fix is in progress. #2749 was submitted and needed browser test changes, but we couldn't submit them in the same PR since updating the test code would have failed due to using an old server image. While we fix the root issue, we decided to submit the server-side code and browser test code separately.
#1743

Fix browser test code for clicking download CSV, broken (intentionally) by #2749

---

.github/workflows/format.yaml
.github/workflows/tests.yaml
bin/fmt-sbt
bin/pull-image
bin/run-browser-test-env

See #2810 for detailed description / motivation behind --force-recreate.
At a high-level, this:
* Skips calling `bin/pull-image` in CI mode since that script unsafely overwrites locally built tags (such as the `civiform-dev` image)
* Removes setting the `USE_LOCAL_CIVIFORM` env variable in GitHub actions since the `bin/pull-image` change will cause that behavior to occur automatically
* Fixes long-standing issue where the timing change associated with pulling images on demand when running docker compose caused `localstack` to be restarted, losing the associated bucket state ([detailed description](https://github.com/seattle-uat/civiform/issues/2810#issuecomment-1168993637)).
Fixes #2810

Attempt to use local images within CI so that pull-images doesn't overwrite them

---

server/app/assets/javascripts/dev_icons.ts
server/app/controllers/dev/IconsController.java
server/app/views/BaseHtmlView.java
server/app/views/admin/programs/ProgramIndexViewV2.java
server/app/views/applicant/ProgramIndexView.java
server/app/views/components/Accordion.java
server/app/views/components/Icons.java
server/app/views/components/QuestionBank.java
server/app/views/components/TextFormatter.java
server/app/views/dev/IconsView.java
server/conf/routes

Moving this to an enum makes it easier to categorize what icons we actually have. Additionally, I've been dealing with issues where I try and scale an existing SVG path up and down and running into issues where the content gets clipped. This is due to the fact that the SVG paths we have have inherent sizes. We'll need to set the viewBox property to this inherent size in order to properly scale the icon up/down using the width/height properties. Having the `/dev/icons` view is a first step to determining which icons need to be updated (and is also generally useful for seeing what icons are available).
See https://css-tricks.com/scale-svg/.

Make SVG icons into an enum rather than const. Also add /dev/icons view to determine the size of each icon.

---

server/app/repository/ApplicationRepository.java
server/app/services/applicant/ApplicantService.java

This is causing flakes of the ApplicationRepositoryTest, which assumes that applications have an explicit order. Since this is consumed for export purposes, it'd be nice to have a stable order. I had thought that the query planner would choose the "natural" order ascending by ID, but it appears to be choosing a different order for unit tests in GitHub actions.
I considered sorting the results in-memory at the server, but discarded that since ordering by ID should already be fast (due to the implicit index in the DB) and is likely what callers would expect.
#1743

Modifying getApplications explicitly order results by ID

---

server/app/controllers/applicant/ApplicantProgramBlocksController.java
server/app/repository/StoredFileRepository.java
server/test/controllers/applicant/ApplicantProgramBlocksControllerTest.java

When an applicant uploads a file for a given program-block, the file is stored in cloud storage keyed by the applicant-program-block-originalFileName -- a four-part composite key. If they upload another file (or the same file) with the same filename for the same program-block, the bytes in cloud storage are overwritten, but CiviForm creates a duplicate `StoredFile` entry with a colliding `name` value, resulting in two (or more) database entries for a single file in cloud storage.
This change prevents CiviForm from creating a duplicate as a result of this applicant behavior.
Fixes https://github.com/seattle-uat/civiform/issues/2818

Don't create duplicate stored files

---

.gitignore
.prettierignore
cloud/aws/modules/custom_domain/main.tf
cloud/aws/modules/setup/backend_storage.tf
cloud/aws/modules/setup/secrets.tf
cloud/aws/templates/aws_oidc/main.tf
cloud/aws/templates/aws_oidc/variable_definitions.json
cloud/deploys/dev_aws/bin/terraform
cloud/deploys/dev_aws/bin/terraform-setup
cloud/shared/bin/lib/setup.py

- Make deploys more reliable by adjusting the auto-generated passwords/user names to work regardless of the prefix and special characters chosen at random.
- Adds terraform files to the gitignore
- Don't try to delete the terraform state bucket (It causes unrecoverable errors) when changing prefix
- Instead, run `cloud/deploys/dev_aws/bin/terraform-setup state rm module.setup.aws_s3_bucket.backend_state_bucket` to remove it from the state
- Add scripts to run terraform directly, when needed. 
- Pipe SES_SENDER_EMAIL into terraform.

Small fixes for AWS deploy

---

server/app/repository/ProgramRepository.java
server/app/services/program/ProgramService.java
server/app/views/admin/programs/ProgramApplicationListView.java
server/test/repository/ProgramRepositoryTest.java
server/test/support/ResourceCreator.java

Noticed this as part of pending PR #2826.
Previously, program admins could search by the applicant's first name, last name, email, or application ID. This augments the functionality to allow additionally searching using the following forms:
* First Last
* Last First
* Last, First
A couple of additional improvements were also added, including:
* Searching by email is case insensitive (even if the stored email has mixed casing)
* Updated the search field label to indicate that email is a valid search option
* Adding unit test coverage that wasn't previously present
#1743

Program admin applicant search improvements to allow full name search

---

server/app/views/admin/ti/EditTrustedIntermediaryGroupView.java

Changed `.input()` to `.email()` in EditTrustedIntermediaryGroupView.java file.
Fixes [#2762](https://github.com/seattle-uat/civiform/issues/2762) emailField should call .email() instead of .input() in EditTrustedIntermediaryGroupView.java

change .input to .email in EditTrustedIntermediaryGroupView file

---

cloud/aws/modules/custom_domain/main.tf
cloud/aws/modules/setup/backend_storage.tf
cloud/aws/modules/setup/logbucket.tf
cloud/aws/modules/setup/main.tf
cloud/aws/modules/setup/secrets.tf
cloud/aws/modules/setup/variables.tf
cloud/aws/templates/aws_oidc/aim.tf
cloud/aws/templates/aws_oidc/autoscaling.tf
cloud/aws/templates/aws_oidc/filestorage.tf
cloud/aws/templates/aws_oidc/main.tf
cloud/aws/templates/aws_oidc/providers.tf
cloud/aws/templates/aws_oidc/setup/main.tf
cloud/aws/templates/aws_oidc/setup/variables.tf
cloud/aws/templates/aws_oidc/variables.tf
cloud/aws/templates/aws_oidc/vpc.tf
cloud/shared/bin/lib/config_loader.py
cloud/shared/bin/lib/setup.py
cloud/shared/bin/lib/terraform.py
cloud/shared/variable_definitions.json

Uses the AWS tagging mechanism to more clearly communicate that this resource is part of civiform, which app_prefix this resource is for, and also what function it is for.
Uses the default tags terraform setting for the app prefix group, civiform label, and environment.  Individual resources are tagged with a name to show their purpose

Tag the AWS terraform resources for easier identification

---

browser-test/src/question_lifecycle.test.ts
server/app/controllers/dev/DatabaseSeedController.java
server/app/services/WellKnownPaths.java
server/app/tasks/DatabaseSeedTask.java
server/app/views/applicant/TrustedIntermediaryDashboardView.java
server/test/tasks/DatabaseSeedTaskTest.java

Switching the canonical seed task from 'Applicant Name' to 'Name' since our internal code expects the well-known name question to be called 'Name' rather than 'Applicant Name'.
Left a TODO to remove a duplicative 'name' question from the `/dev/seed` endpoint since the QuestionService doesn't presently expose sufficient plumbing to retrieve the canonical `QuestionDefinition`.
#2843

Update canonical question identifier from "Applicant Name" to "Name"

---

browser-test/src/checkbox.test.ts
browser-test/src/support/admin_questions.ts

Add a browser level test for the checkbox question type. For all question types, I propose we have a browser level test that covers these high level scenarios:
- Single question of that type:
- Test that submits successfully
- Test that errors when required and was not answered
- Test any question type specific errors
- Multiple questions:
- Test that submits successfully
- Test that an unanswered optional question allows submission
- Test that first invalid Q prevents submission
- Test that second invalid Q prevents submission
After this looks good and we get alignment, I will send out additional PRs to address all other missing question types.
#1937

Add a browser level test for the checkbox question type

---

server/app/tasks/StoredFileAclMigrationTask.java

The slf4j does not do string formatting, despite it's method signature suggesting it does. This PR fixes formatting errors encountered during the stored file migration and stops the migration if an error is encountered.

Better logging for stored file migration

---

server/app/auth/StoredFileAcls.java
server/app/tasks/StoredFileAclMigrationTask.java
server/test/repository/StoredFileRepositoryTest.java

If a file was created before the migration to using StoredFileAcls, programReadAcls will be null on initial load. This caused a NullPointerException when loading the record in the migration task. This PR sets the internal state of the ACLs to an empty collection so the migration task can populate them.

File migration fix

---

server/app/views/applicant/ApplicantProgramSummaryView.java
server/app/views/applicant/ProgramIndexView.java
server/app/views/style/ApplicantStyles.java

Add padding so that text doesn't start immediately at the border. 
Before: 
After:
Reworked question DOM layout. Each question now consists of 2 columns. The left column contains question text with optional answer underneath. The right column contains optional answer timestamp with optional action link (edit/continue) vertically centered. That layout works better on mobile and avoids overlapping of text (see on screenshots). Most screens didn't change, only the second before/after pair is affected.
Before:
After: 
Before:
After:
Before:
After:
Before:
After:

Improve application index and preview look on mobile

---

server/app/views/admin/programs/ProgramStatusesView.java
server/app/views/admin/programs/ProgramTranslationView.java

Adding UI for translation application statuses and email, guarded behind the status tracking feature flag. Presently, this only uses hard-coded data and isn't yet incorporated into the controllers.
#2752

Adding localization of email content and status name.

---

server/app/auth/oidc/OidcProvider.java

Pac4j doesn't properly verify the issuer when `authorization_response_iss_parameter_supported` is set in the metadata for `token` or `id_token` response types with the `form_post` method (it does work for `code` response type).  This manually disables it in those cases.
When using `token`/`id_token` response types, and the OIDC provider has `authorization_response_iss_parameter_supported` enabled, disable the issuer checking, since it's not supported by pac4j.

Disable authorization_response_iss_parameter_supported for form_post token/id_token methods

---

server/app/controllers/FileController.java
server/test/controllers/FileControllerTest.java

Program admins clicking on a file to download would see a blank screen. In the browser console you'd see
`The resource from “https://civiform.seattle.gov/admin/programs/625/fi...” was not rendered due to an unknown, incorrect or missing MIME type (X-Content-Type-Options: nosniff).`
This console output appears to be a misnomer. I was able to repro locally. The FileController.acledAdminShow method fileKey parameter is URL Encoded. It isn't getting decoded before trying to look it up. This is causing it to not find the StoredFile object in the database. I'm decoding the string earlier in the method and passing the decoded value to be used to lookup the StoredFile object.
Examples
fileKey = "applicant-15%2Fprogram-13%2Fblock-1%2FTest.png"
decodedFileKey = …

Fix File Download Not Downloading

---

browser-test/src/checkbox.test.ts
browser-test/src/date.test.ts
browser-test/src/dropdown.test.ts
browser-test/src/email.test.ts
browser-test/src/id.test.ts
browser-test/src/radio_button.test.ts
browser-test/src/static_text.test.ts
browser-test/src/support/admin_questions.ts
browser-test/src/support/applicant_questions.ts
browser-test/src/text.test.ts

Add focused browser tests for date, dropdown, email, id, radio button, static text, text questions.
Will send a followup PR to update the existing question type browser tests to align with this structure.
#1937

Add all missing browser test coverage for remaining question types

---

server/build.sbt
server/test/auth/ApiAuthenticatorTest.java
server/test/auth/oidc/OidcProviderTest.java
server/test/controllers/admin/AdminProgramBlockPredicatesControllerTest.java
server/test/controllers/admin/AdminProgramBlockQuestionsControllerTest.java
server/test/controllers/admin/AdminProgramStatusesControllerTest.java
server/test/repository/ApiKeyRepositoryTest.java
server/test/repository/ApplicationRepositoryTest.java
server/test/services/apikey/ApiKeyServiceTest.java

We use Junit 4 to execute tests and AssertJ for performing assertions. Yes we include Junit 5 as test dependency. Some tests use `assertThrows` provided by it. AssertJ has similar method `assertThatThrownBy` and should be used instead for consistency. Plus it removes potential confusion that project is using Junit 5.

Remove dependency on junit 5.

---

server/app/services/question/ActiveAndDraftQuestions.java
server/app/views/admin/questions/QuestionsListView.java
server/test/controllers/admin/AdminQuestionControllerTest.java

Presently, the "Total Questions" area displays `active version questions + draft version questions`. The number of rows displayed has a single entry for each unique question identifier.
Consider the starting scenario where 12 questions exist:
* `Total questions: 12`
* 12 entries in the table
Now assume an edit is made to a single question:
* `Total questions: 13`
* 12 entries in the table
There are still logically 12 questions in this case. This PR fixes that and adds a regression test.
Fixes "Total questions" count the questions view to not include edits to existing questions.
#2788

Fix question count to reflect the number of rows in the table

---

server/app/models/Version.java
server/app/services/question/QuestionServiceImpl.java
server/test/services/question/QuestionServiceImplTest.java

Presently, the `/archive` and `/restore` handlers don't do any validation beyond the question ID existing. This means that a question that is still referenced by a program can be archived.
This could definitely occur for a stale tab scenario where an admin has the archive option, then references the question from a separate program (rendering it unarchivable).
Additionally, we should always rely on validation before we mutate state rather than relying on links being generated at the appropriate time.
Currently, this returns a 400 error. As part of #2788, I may adjust the controller to redirect to the main question page with an error message.
Fix issue where UI could allow accidental archival of questions that were still referenced.
#2788

Prevent archiving / restoring questions that aren't in a valid state.

---

server/conf/application.test.conf
server/test/support/CfTestHelpers.java

It's hard to write tests when the applicant icsc client name & secret are always required.  This disables it by default.

Disable applicant auth by default in tests

---

browser-test/src/question_lifecycle.test.ts
browser-test/src/support/admin_questions.ts
server/app/controllers/admin/AdminQuestionController.java
server/test/controllers/admin/AdminQuestionControllerTest.java

It's possible for global admins to edit question in parallel: in one tab create a new version of an existing question and then, in the second tab, try to edit the original question. Currently if that happens the admin sees the original question data even though a new draft version exists. This PR handles this case and redirects admin to the draft version.
Redirect to the draft version if exists when trying to edit a published question.
Fixes #2497

Redirect to draft question when trying to edit published.

---

server/app/annotations/FeatureFlags.java
server/app/modules/FeatureFlagsModule.java
server/app/services/role/RoleService.java
server/conf/application.conf
server/test/services/role/RoleServiceTest.java

New config value is introduced: ALLOW_GLOBAL_ADMINS_BE_PROGRAM_ADMINS. When set to true it allows Civiform Global Admin to also be a Program Admin. 
Fixes #2916

Add a flag to allow global admins to be program admins

---

server/build.sbt

Rather than including all AWS SDK libs use only the one that we need (s3 and simple email) It reduces AWS deps:
367MB => 8MB
336 libs => 27 libs
Fixes #2921

Import individual AWS SDK libraries.

---

.github/workflows/push_build_ci.yaml
.github/workflows/push_cloud_tests.yaml
.github/workflows/push_tests.yaml

Switch to using a matrix to run dockerfile builds, to avoid as much duplicated logic as possible.  Also avoid some potential race conditions around building dependancy images only on file changes (we don't want to cancel a workflow that does build the image in favor of one that skips the build).
also update the workflow names to be more descriptive

Use a matrix to run CI builds

---

cloud/aws/templates/aws_oidc/bin/setup.py

The function should return string and not Process python object. The implementation is copied from the azure implementation.

Fix get_current_user function in AWS setup.py

---

server/app/auth/ProfileMergeConflictException.java
server/app/controllers/ErrorHandler.java
server/app/controllers/LoginController.java
server/test/controllers/ErrorHandlerTest.java

This unwraps completion exceptions and uses the custom civiform exception handler for logins.
Also updates the ProfileMergeConflictException to store the error message in the exception, rather than using the non-functioning redirect action from pac4j.
Previously, errors were getting wrapped and rendered useless.  This enables the underlying exception message to be displayed.

Use the underlying exception when completable futures error

---

bin/run-browser-tests

Having `--ipc=host` has issues for engineers using linux. Reading docs, ipc is related to memory sharing and shouldn't be needed for browser tests. Tried on macos and linux - tests work fine with the param removed.

Remove --ipc param when running browser tests.

---

.github/pull_request_template.md

When creating a PR, added a note to the template to remind people to add a label for use during releases.

Added reminder to add labels to the PR checklist

---

bin/run-browser-tests
bin/run-browser-tests-ci
browser-test/bin/wait_for_server_start_and_run_tests.sh
browser-test/jest.config.js
browser-test/playwright.Dockerfile
browser-test/src/tsconfig.json

With this change browser tests will use configuration files (`package.json`, `jest.config.js`) from local directory rather than using the ones provided in the image. That makes sure that changes to configs immediately take effect. 
Additionally this change sets up `ts-jest` to use `tsconfig.json` provided in the tests. Until now `tsconfig.json` hasn't been used at all.
Related to #2955

Use tsconfig.json for TS transformation when running browser tests

---

prod.Dockerfile

Switch to using the smaller JRE alpine image for the final prod docker image base.
Use eclipse-temurin:11.0.15_10-jre-alpine for the production image

Use the JRE for the final prod image build

---

bin/run-prober
browser-test/package-lock.json
browser-test/playwright.Dockerfile

In #2956 changed build image instructions to not run `yarn install`. Instead it runs `yarn install` actual test. That helps to ensure that libraries match package.json and test code. I missed probe tests during that update.

Fix probe tests

---

server/app/annotations/FeatureFlags.java
server/app/modules/FeatureFlagsModule.java
server/app/services/role/RoleService.java
server/conf/application.conf
server/test/services/role/RoleServiceTest.java

I've kept the test that was missing to validate expected behavior.
Removing config value: ALLOW_GLOBAL_ADMINS_BE_PROGRAM_ADMINS. After consideration, this is not a use case that we need to support.

Revert "Add a flag to allow global admins to be program admins (#2928)" 

---

server/app/views/LoginForm.java

Negative margin causes overlap of text with the logo if the logo doesn't have extra whitespace. Generally we shouldn't expect logos to have whitespace. 
Before:
After:
Fixes overlapping of title and logo on login form.

Remove negative margin from site title

---

server/app/models/Version.java
server/app/repository/VersionRepository.java
server/app/services/question/ActiveAndDraftQuestions.java
server/test/repository/VersionRepositoryTest.java
server/test/services/question/ActiveAndDraftQuestionsTest.java

As part of #2788, I'll be modifying the logic for how we determine how many programs reference a question. A follow-on from this will hopefully simplify the logic for whether a question can be archived. Prior to this refactoring, I've added tests for the existing functionality in `ActiveAndDraftQuestions` and left TODOs for places where the resulting behavior actually is a bug in the intended design. These will be fixed in a follow-on PR.
I also augmented the correctness tests for publishing a draft version (which I'll also be touching as part of #2788.
While here, I also:
* Added `Versions.addQuestion` to update the M2M from the Version side. This made tests much simpler to write and I eventually intend to modify VersionRepository to call this when publishing a version.
* Marked …

Add test coverage for ActiveAndDraftQuestions and extend publish draft test coverage

---

.github/workflows/tests.yaml

Unblocks PR runs while we wait for codecov integration to be re-enabled. Left a TODO against https://github.com/civiform/civiform/issues/2976 to ensure that we consider these blocking after the integration has been fixed.
N/A
#2976

Temporarily marking code coverage upload failures as non-blocking.

---

.github/workflows/push_build_ci.yaml
Dockerfile
bin/build-dev
bin/build-dev-oidc
bin/build-formatter
bin/build-localstack-env
bin/build-prod
browser-test/playwright.Dockerfile
formatter/formatter.Dockerfile
localstack/localstack.Dockerfile
prod.Dockerfile
test-support/oidc.Dockerfile

Use the base Alpine image (since eclipse-temurin doesn't build alpine for arm), and docker buildx to enable multiplatform builds for the dev & formatter docker images.
n/a

Build dev images for arm

---

server/app/views/components/FieldWithLabel.java
server/test/views/components/FieldWithLabelTest.java

Always set FieldWithLabel id. If missing, generates a random one.
We used to always generate a random ID if one was not set, but this was accidentally removed due to some refactoring in #2281.
One known issue this causes is that labels are no longer linked to inputs, which is a problem for screen readers.
Fix screenreader bug where labels and inputs are not linked with ID.
#2388

Always set FieldWithLabel id

---

bin/build-prod
prod.Dockerfile

Adding an immutable label indicating the GIT commit SHA associated with the built image (from  https://github.com/civiform/civiform/issues/2926#issuecomment-1195759925).
Adding the immutable `civiform.git.commit_sha_label` to the built image.
https://github.com/civiform/civiform/issues/2926#issuecomment-1195808099
#2926

Add civiform.git.commit_sha label when building an image.

---

cloud/aws/templates/aws_oidc/variables.tf
cloud/aws/templates/aws_oidc/vpc.tf

The variable is misleading. Description and value says it's related to RDS while in fact it's used for the main VPC created in deployment.

Improve description of vpc_name varaible

---

.github/workflows/build_push_ci.yaml
.github/workflows/push_build_ci.yaml
Dockerfile
bin/build-browser-tests
bin/build-dev
bin/build-dev-oidc
bin/build-formatter
bin/build-localstack-env
bin/build-prod
bin/remove-dev

Docker buildx requires explicit loading into the local image cache (which is what push uses to find image)
We need to use the --load command to be able to use the image locally, and --push to push the mutli-platform image remotly.
Modifies the scripts to use these commands explicitly (and cache between the build).
Also adds clarifying comments to the github action, and runs the build whenever the github action file or build script changes.
n/a 

Fix multi-platform image pushing

---

server/app/views/admin/programs/ProgramApplicationView.java
server/app/views/components/LinkElement.java

Fixes the layout of the User name and Export to PDF button column
Currently:
* User name: H1 which consumes the max width
* Button has a large negative margin to account for the H1 taking the full width.
A key change is that the User name should not be an H1 as it comes after a H2 (the program name) H tags need to be in numerical order, it is now a `<p>` with the same styling as the Screen headers.  If anything the screen names should be headers I think.
Put the row items in a div with flex layout.
Changes the rendering process for the Program Admin Application view for the User name and Export button.

Fix layout for User name and Export to PDF button row

---

bin/run-browser-tests
bin/run-browser-tests-ci

Currently, when browser tests run, dependencies pulled from the docker container are stored in local `browser-test/node_modules` directory which might cause issues and conflict when running npm/yarn commands locally from that directory. This change introduces dedicated volume where node_modules will be stored and shared between browser test runs.

Use dedicated volume for node_modules when running browser test

---

browser-test/jest.config.js
browser-test/package.json
browser-test/src/address.test.ts
browser-test/src/checkbox.test.ts
browser-test/src/currency.test.ts
browser-test/src/date.test.ts
browser-test/src/dropdown.test.ts
browser-test/src/email.test.ts
browser-test/src/end_to_end_enumerators.test.ts
browser-test/src/file.test.ts
browser-test/src/id.test.ts
browser-test/src/name.test.ts
browser-test/src/number_input.test.ts
browser-test/src/radio_button.test.ts
browser-test/src/static_text.test.ts
browser-test/src/support/applicant_questions.ts
browser-test/src/support/index.ts
browser-test/src/support/setup-jest.ts
browser-test/src/text.test.ts

Add axe (https://github.com/dequelabs/axe-core) accessibility browser tests. This also adds a custom expect matcher, that outputs the accessibility violations on failure. Here is an example of how the test failure message looks:
This PR just adds it for all question types. I will send a separate PR to cover the overall applicant's experience (e.g. a11y testing per page). I will also update the docs with debugging instructions.
Add Axe accessibility testing framework to browser tests.
#2388

Add axe accessibility tests to browser tests for question types

---

cloud/aws/templates/aws_oidc/variable_definitions.json
cloud/aws/templates/aws_oidc/variables.tf
cloud/aws/templates/aws_oidc/vpc.tf

The following variables are now created in AWS Secret manager and are not passed from terraform config: `APPLICANT_OIDC_CLIENT_ID`, `APPLICANT_OIDC_CLIENT_SECRET`, `APPLICANT_OIDC_DISCOVERY_URI`.
Also removes `aws_apprunner_vpc_connector` resource that no longer used since deployment was moved to fargate.

Remove OIDC TF variables that were moved to secret manager.

---

.github/workflows/build_push_ci.yaml

We haven't been pushing new images to DockerHub in the past 2 days since we're not setting the `PUSH_IMAGE` environment variable expected by [`bin/build-prod`](https://github.com/civiform/civiform/blob/2fefe4065d9422a64f6beb43c40ffadaff0b53fa/bin/build-prod#L39) / [`bin/build-dev`](https://github.com/civiform/civiform/blob/2fefe4065d9422a64f6beb43c40ffadaff0b53fa/bin/build-dev#L30).
It appears that #2982 accidentally set the `PUSH` environment variable instead.
Fix bug where CI no longer pushes new images to DockerHub.

Setting PUSH_IMAGE env variable for bin/build-[dev|prod] scripts.

---

server/app/controllers/admin/AdminProgramStatusesController.java
server/app/services/program/StatusDefinitions.java
server/test/controllers/admin/AdminProgramStatusesControllerTest.java
server/test/services/program/ProgramServiceImplTest.java

This is necessary since these setters are used by Jackson when deserializing. If 'null' is persisted, then deserialization using the non-optional variants will pass null to the builder, which will throw a runtime exception. Added a regression test as well.
Fixes error when creating a status with an empty email.
#2752

Update email-related setters for StatusDefinitions.Status.Builder to take an Optional<> instead of the raw value

---

server/app/controllers/CiviFormController.java
server/app/controllers/admin/AdminApplicationController.java
server/test/controllers/admin/AdminApplicationControllerTest.java

Updates AdminApplicationController to issue an unauthorized response if no user profile is present.
Adds an effectively empty test file for AdminApplicationController, to set the baseline code coverage before adding new ones.  A test is necessary to do so.
NA

Handle unauth better and add an empty test file for AdminApplicationController

---

cloud/aws/templates/aws_oidc/app.tf
cloud/aws/templates/aws_oidc/secrets.tf
cloud/aws/templates/aws_oidc/variable_definitions.json
cloud/shared/variable_definitions.json

`applicant_oidc_discovery_uri` is passed from civiform_config.sh and shouldn't be stored as secret. 
Additionally make BASE_URL required param over CUSTOM_HOSTNAME as the latter doesn't seem to provide useful functionality.

Make applicant_oidc_discovery_uri a regular variable instead of secret

---

cloud/aws/templates/aws_oidc/app.tf

Adds option to treat all lines that start with whitespace (space, tab) as part of the previous line. It collapses stacktraces to a single event. Ideally we would use something more versatile, like making sure that single logging call in java gets propagated as single logging event in CloudWatch. But that requires more custom integration. 
Here is example of how errors look in CloudWatch after this change:

Stitch lines of stacktrace to a single log even in AWS deployment

---

browser-test/src/application_download.test.ts
browser-test/src/application_navigation.test.ts
browser-test/src/application_optional_questions.test.ts
browser-test/src/application_review.test.ts
browser-test/src/static_text.test.ts
browser-test/src/support/applicant_questions.ts

Add axe accessibility testing for each page of the applicant flow. Per question tests were added in #2989, and documentation was added in https://github.com/civiform/docs/pull/84
N/A - adding testing.
Fixes #2388

Add axe a11y testing for overall applicant flow

---

cloud/aws/templates/aws_oidc/app.tf
cloud/aws/templates/aws_oidc/variable_definitions.json
cloud/aws/templates/aws_oidc/variables.tf
cloud/shared/validate_variable_definitions.py

Certificate at the moment is created outside of terraform. So it should be passed as a config variable rather than hardcoded in app.tf.
Desired task count is used to stop/start services and useful during development to stop crashing service.

Move certificate and task count variables from app.tf to config.

---

cloud/shared/bin/lib/destroy.py
cloud/shared/bin/lib/setup.py

This helps with local development, for example to abort execution early by adding "return" and generally having a main function is more conventional compared to having all code on top-level.

Move top-level code to main() functions in setup.py and destroy.py

---

cloud/shared/bin/lib/setup.py
cloud/shared/validate_variable_definitions.py

Currently setup.py auto-approves and applies any changes when mode is staging or prod. It's dangerous as user should review those changes before applying them. The auto-approve seems to have been added for automation (CI tests) which currently are not implemented. In future, when we implement the tests, we can add this option back guarded by some flag or environment variable used only in tests.

Remove auto-approve from setup.py

---

cloud/aws/modules/setup/variables.tf
cloud/aws/templates/aws_oidc/app.tf
cloud/aws/templates/aws_oidc/secrets.tf
cloud/aws/templates/aws_oidc/setup/main.tf
cloud/aws/templates/aws_oidc/setup/variables.tf
cloud/aws/templates/aws_oidc/variable_definitions.json
cloud/aws/templates/aws_oidc/variables.tf

`ADFS_DISCOVERY_URI` is currently a secret. It should be a regular variable instead, similar to `APPLICANT_OIDC_DISCOVERY_URI`. 
`AWS_REGION` is currently hardcoded to us-east-1 and user can't change it without updating `variables.tf` which should be considered immutable to deployers. This PR reads `AWS_REGION` from the `civiform_config.sh` if it's present and defaults to us-east-1 if it's absent.

Move ADFS_DISCOVERY_URI and AWS_REGION to civiform_config.sh

---

cloud/aws/bin/lib/backend_setup.py
cloud/shared/bin/lib/config_loader.py

Currently it's hardcoded to us-east-1. With this change it is now can be read from civiform_config.sh

Pass AWS_REGION to terraform backend config

---

server/test/controllers/admin/AdminProgramBlocksControllerTest.java
server/test/controllers/admin/AdminProgramControllerTest.java
server/test/controllers/api/ProgramApplicationsApiControllerTest.java
server/test/services/applicant/ApplicantDataTest.java

We use AssertJ in java unit tests to perform assertions, including for asserting exceptions. There are few places where we use Junit's `assertThrows` though. This PR migrates those calls to use `assertThatThrownBy`. Improves consistency. Downside is that it's harder to remember compared to simple `assertThrows` :/

Replace assertThrows with assertThatThrownBy

---

browser-test/src/support/admin_programs.ts

Fix 2 expect utilities to actually call expect
NA

Fix expect Program state utilities to actually expect.

---

cloud/shared/bin/lib/terraform.py

PR contains multiple changes:
1. Remove `-json` param so that terraform outputs progress in a user-friendly way. Currently we don't consume terraform output by any tooling so json is unnecessary.
2. Remove `plan`/`apply` split and do everything in `apply`. This introduces confirmation step so that before changes are applied user need to confirm it. This is useful especially for running destroy.

Simplify terraform.py

---

cloud/shared/bin/lib/terraform.py

Currently pre-terraform setup stage which creates s3 bucket for the state shows warning because we pass non-existing -`-backend-config` param.

Remove warning when running setup.py

---

server/app/controllers/api/ProgramApplicationsApiController.java
server/app/controllers/applicant/RedirectController.java
server/app/repository/ProgramRepository.java
server/app/services/applicant/ApplicantServiceImpl.java
server/app/services/program/ProgramService.java
server/app/services/program/ProgramServiceImpl.java
server/app/views/admin/programs/ProgramAdministratorProgramListView.java
server/app/views/admin/programs/ProgramIndexView.java
server/conf/routes
server/test/controllers/RedirectControllerTest.java
server/test/services/program/ProgramServiceImplTest.java

This fixes a bug wherein an applicant could have multiple drafts for the same program. This would happen when:
1. applicant answers a question for version A of a program, creating draft application A
1. CF admin publishes a new version of the program, version B
1. applicant navigates to the program using its deep link (e.g. from the index page), the deep link (previously) always links to the most recent version of the program, now version B
1. applicant answers a question for version B of the program, creating a second draft
1. applicant attempts to submit their application, encounter an error due to logic that asserts only one draft of a program at a time
The fix implemented here is to change the logic for deep links to redirect to the version of the program the applicant already has a …

Using deep link does not create duplicate applications

---

server/app/views/applicant/ApplicantProgramBlockEditView.java

Based on feedback from accessibility experts, this PR updates the page title to indicate the progress, to better reflect the content of the page. e.g.
* Before: "Recreation Scholarship Program — CiviForm"
* After: "Recreation Scholarship Program — 3 of 8 — CiviForm"
Manually verified this change.
Add progress indication to page title for accessibility.
Fixes #2628

Add more descriptive page title for application blocks

---

browser-test/src/application_navigation.test.ts
server/app/views/applicant/ApplicantProgramInfoView.java

This bumps up the existing h2 heading to an h1. Manually verified UI is not affected. Also enabled the accessibility test for this page.
Add heading level one to program details page for a11y.
Fixes #3016

Add heading level one to applicant facing program details page.

---

browser-test/src/file.test.ts
server/app/views/AwsFileUploadViewStrategy.java
server/app/views/AzureFileUploadViewStrategy.java
server/app/views/FileUploadViewStrategy.java
server/app/views/questiontypes/FileUploadQuestionRenderer.java

Adds a screenreader `label` for the file input field. This follows the existing pattern from other fields ([code](https://github.com/civiform/civiform/blob/main/server/app/views/components/FieldWithLabel.java#L399-L407)). Manually verified behavior.
Also enables the file accessibility test.
Add screenreader label for file uploads.
Fixes #2988

Add screen reader label for file upload field

---

browser-test/src/admin_application_statuses.test.ts
browser-test/src/civiform_admin_program_statuses.test.ts

Status Tracking is behind a feature flag, but we've been relying on the feature being enabled in the dev environments, which however means they fail in other environments.
Will disable until we can control the feature flag in the test.

Disable Status tests

---

browser-test/src/admin_application_statuses.test.ts
browser-test/src/support/admin_programs.ts
server/app/views/admin/programs/ProgramApplicationView.java
server/app/views/style/ReferenceClasses.java

When no status is specified for an Application, add an empty selected option.
NA
Fixes #2911

When no status is set on an application show an empty option.

---

browser-test/src/admin_program_translation.test.ts
browser-test/src/support/admin_programs.ts
browser-test/src/support/admin_questions.ts
browser-test/src/support/admin_translations.ts
server/app/controllers/admin/AdminProgramTranslationsController.java
server/app/views/admin/TranslationFormView.java
server/app/views/admin/programs/ProgramTranslationView.java
server/app/views/admin/questions/QuestionTranslationView.java
server/test/controllers/admin/AdminProgramTranslationsControllerTest.java
server/test/controllers/admin/AdminQuestionTranslationsControllerTest.java

As part of adding translatable content for status tracking, we discussed improving the usability of the current translation views. Note that in a follow-on PR we'll be removing the English translation tab since it's duplicative with the existing content in the program/question configuration screens.
The UI changes here include (see screenshots below):
* Adding the program / question name to the title so one knows which entity translations are being edited for
* Add a consistent label for each field for what's being set. Previously, question translations used the English text for the field label
* Using fieldsets for better information organization
* Add a small section below the field that indicates the English version of the text (hidden for the English translation tab)
While updating, a …

Update question/program translation views for consistency and usability

---

server/app/views/questiontypes/EnumeratorQuestionRenderer.java

Moves enumerator placeholder to be a permanent label. Verified with UX (@rahaghas) that this looks OK.
This is part of a larger change to remove placeholder text. Address and date still need to be updated, but since these come with additional localization/translation considerations, they will come in a separate PR.
Before:
After:
Add label for individual enumerator fields.
#2617

Move enumerator placeholder to be a permanent label

---

docker-compose.yml

Disable dev-oidc configuration as it is failing which block CiviForm from working..
NA - dev only

Disable local OIDC testing due to issue #3102

---

.github/workflows/release.yaml

The create release action needs the github auth token to run

Pass github token to release script in action

---

cloud/aws/templates/aws_oidc/main.tf

This param is required when KMS is used.
- [s] Added the correct label: < feature | bug | dependencies | infrastructure | ignore-for-release >

Add `storage_encrypted` param to AWS DB

---

bin/create-release

When the release script is run using GH actions, there is no configured git user name or email so instead we use the GITHUB_ACTOR environment variable.

Use GITHUB_ACTOR name when release script is run on GH

---

server/app/views/questiontypes/RadioButtonQuestionRenderer.java
server/test/views/questiontypes/RadioButtonQuestionRendererTest.java

Explicit labels (where `label` and `input` are linked by IDs) are better supported by assistive technology than implicit labels (where the `label` element wraps the `input` element). See [link](https://www.w3.org/WAI/tutorials/forms/labels/#associating-labels-implicitly). This PR does not affect styling.
Also updates the input id to be randomly generated instead of using the text. The text is not unique per page (e.g. we could have 2 different radio questions with the same answer).
Before:
After (no change in UI):
Change label from implicit to explicit for radio buttons for accessibility.

Change label from implicit to explicit for radio buttons

---

cloud/aws/templates/aws_oidc/bin/aws_cli.py
cloud/aws/templates/aws_oidc/bin/resources.py
cloud/aws/templates/aws_oidc/bin/setup.py
cloud/aws/templates/aws_oidc/secrets.tf

Original DB password generated by the Terraform is stored in the Terraform state. We want to avoid exposing such info in the state even though access to the state should be limited. To achieve that we now regenerate password. Update database to use the new password, update the secret value and restart ECS service to pickup the new secret value.
Fixes #2918

Change DB password after initial terraform setup is done.

---

cloud/aws/templates/aws_oidc/bin/aws_cli.py
cloud/aws/templates/aws_oidc/bin/destroy.py
cloud/aws/templates/aws_oidc/bin/resources.py

1. Pass command line as a string instead of list of parameters as it's easier to read that way.
2. Extract s3 bucket name to a constant in resources.py so that more terraform-related constants in that file.
3. Move code that builds urls for AWS console to AwsCli.

Style improvements in deploy AWS python scripts

---

browser-test/.eslintrc.json
browser-test/src/admin_application_statuses.test.ts
browser-test/src/application_download.test.ts
browser-test/src/support/admin_predicates.ts
browser-test/src/support/admin_questions.ts
browser-test/src/support/applicant_questions.ts

1. Use for-of instead of for-in.
2. Remove unused function arguments. Either delete them if they are not needed or add missing code that uses them.

Fix TS style warnings and add few missing checks in assertions

---

cloud/shared/bin/lib/destroy.py
cloud/shared/bin/lib/setup.py
cloud/shared/bin/lib/setup_class_loader.py
cloud/shared/bin/lib/setup_template.py

There are changes in this PR. 
1. Make `SetupTemplate` class to be explicit base class for Setup and Destroy AWS/Azure classed by adding `pre_terraform_destroy` and `post_terraform_destroy` methods there. Both AWS Destroy and Azure Destroy classes inherit from `SetupTemplate`. Maybe we should redo inheritance in this case. For example have single AWS and single Azure classes which encapsulate both setup and destroy logic.
2. Create instances of AWS/Azure Setup/Destroy classes in setup_class_loaders instead of returning class objects. That allows to specify return type and improve type inference for IDEs. And generally hides that non-standard reflection logic within that file.

Refactors templates handling in python deploy script

---

cloud/aws/bin/deploy.py
cloud/aws/templates/aws_oidc/bin/aws_cli.py
cloud/aws/templates/aws_oidc/bin/resources.py
cloud/aws/templates/aws_oidc/bin/setup.py
cloud/azure/templates/azure_saml_ses/bin/setup.py
cloud/shared/bin/lib/setup.py

1. The links should help deployer verify whether deployment was successful or not. 
2. At the end of setup we remind to update domain CNAME record to point to the freshly created load balancer url where civiform app is running.
3. Move second run of `terraform apply` to azure-specific post-terraform step. It's not needed by AWS and messes up "print final message" code which is done in post-terraform setup.

Print some few links at the end of AWS setup and deploy

---

server/app/controllers/admin/AdminProgramStatusesController.java
server/app/forms/admin/ProgramStatusesForm.java

It makes sense to trim the text from user-provided status texts and emails. However, the `configuredStatusText` field used to identify the original status when editing / deleting is essentially a key into what is in the DB directly. Additionally, it's populated based on the DB value. Performing a trim here will cause issues if a status makes it's way into a program that hasn't been trimmed.
N/A
#2752

No longer trimming configuredStatusText since it corresponds directly to what is in the DB

---

browser-test/src/question_delete.test.ts
browser-test/src/support/admin_questions.ts
server/app/views/admin/questions/QuestionsListView.java

To aid in discoverability of the "Archive" feature, we always present the option in the action list. If there are still programs referencing the question, clicking "Archive" causes the referenced program modal to be popped up with a warning indicating that the question can't be archived. This implements the proposal in https://github.com/civiform/civiform/issues/2788#issuecomment-1184751742.
Always surface the "archive question" option. When the operation can't be performed, show a a modal explaining why.
#2788

Always present the "archive" option and show a modal if the operation can't be performed

---

browser-test/src/support/admin_program_statuses.ts
server/app/views/admin/programs/ProgramStatusesView.java

This is post-merge feedback from https://github.com/civiform/civiform/pull/3150.
N/A.
#2752

Update warning text shown when email body for a status is cleared.

---

server/app/views/admin/programs/ProgramStatusesView.java

Per feedback from @rahaghas, there's no reason to change the background color when hovering over an application status row since clicking it wouldn't do anything.
N/A
#2752

Removing hover state from application status row.

---

server/app/controllers/admin/AdminApplicationController.java
server/app/services/applications/ProgramAdminApplicationService.java
server/test/services/applications/ProgramAdminApplicationServiceTest.java

Added further validation that the retrieved application's associated program name matches the one from the request. Introduced a new service for program admin access of applications to mediate access.
Preventing program admins from accessing applications that aren't part of the provided program

Preventing program admins from accessing applications that aren't part of the provided program

---

browser-test/src/admin_dropdown_create_and_edit.test.ts
server/app/views/BaseHtmlView.java
server/app/views/admin/programs/ProgramFormBuilder.java
server/app/views/admin/questions/QuestionConfig.java
server/app/views/admin/questions/QuestionEditView.java

While here, I put the program visibility mode / question export mode options inside a fieldset for better grouping (and a place to put field requiredness).
Program creation:
Question creation:
Add indicators for which fields are required when editing/creating questions and programs.
Fixes #3023

Add field requiredness indicators to program/question UIs.

---

browser-test/src/support/admin_programs.ts
server/app/views/admin/programs/ProgramFormBuilder.java
server/app/views/admin/programs/ProgramIndexView.java

Change "Manage Admins" to "Manage Program Admins"
Change "Link for additional program information" to "Link to program website"
Change "Manage Admins" to "Manage Program Admins"
Change "Link for additional program information" to "Link to program website"
Fixes #3034 Fixes #3082;

Rename Manage Admin, Link to program website

---

.github/workflows/tests.yaml
bin/run-browser-tests-ci

This way it can help us understand the root cause of intermittent azure failures.

Upload videos on browser test failures when running on CI

---

.github/workflows/aws-oidc-deploy-test.yaml
.github/workflows/azure-saml-ses-deploy-test.yaml

They got broken by https://github.com/civiform/civiform-staging-deploy/pull/7

Fix deploy staging actions broken by moving configs around

---

server/app/views/BaseHtmlView.java
server/app/views/admin/programs/ProgramBlockEditView.java
server/app/views/admin/programs/ProgramBlockPredicatesEditView.java
server/app/views/admin/programs/ProgramIndexView.java
server/app/views/admin/programs/ProgramStatusesView.java
server/app/views/admin/questions/QuestionsListView.java
server/app/views/applicant/ProgramIndexView.java
server/app/views/components/Accordion.java
server/app/views/components/Icons.java
server/app/views/components/QuestionBank.java
server/app/views/components/TextFormatter.java

Original icon size is part of the icon definition enum now so passing it explicitly is unnecessary. I manually checked that size that passed explicitly matches icon size so this is a no-op.
Fixes #3148

Cleanup calls that pass icon size explicitly

---

.github/workflows/release.yaml

The script needs to log in to Docker Hub in able to push tags.

Release GH action logs in to Docker Hub

---

browser-test/src/support/admin_programs.ts
server/app/views/admin/programs/ProgramApplicationListView.java

On the admin program list view this makes the download modal automatically close after clicking the download button for csv or json.
Automatically close Program Application List popup after clicking json or csv download button.
Fixes #3095

Automatically close modal after clicking download

---

server/conf/evolutions/default/43.sql
server/test/repository/ApplicationEventRepositoryTest.java

Fix issue in #3020 where the foreign key indexes were unique when they should not be.  Added a test to verify multiple events can be saved for the same Application and Account.
Remove and Recreate indexes on the new application_events table.

Remove uniqueness from application_events indexes

---

cloud/aws/templates/aws_oidc/app.tf
cloud/aws/templates/aws_oidc/variables.tf
cloud/azure/modules/app/locals.tf
cloud/azure/modules/app/variables.tf
cloud/azure/templates/azure_saml_ses/main.tf
cloud/azure/templates/azure_saml_ses/variables.tf
cloud/shared/variable_definitions.json
server/app/controllers/monitoring/MetricsController.java
server/build.sbt
server/conf/application.conf
server/conf/routes

Allows exporting of Prometheus metrics from the CiviForm server, must be enabled with the `CIVIFORM_SERVER_METRICS_ENABLED` environment variable.
Allows exporting of Prometheus metrics from the CiviForm server, must be enabled with the `CIVIFORM_SERVER_METRICS_ENABLED` environment variable.

Instrument server for Prometheus metrics

---

browser-test/src/admin_application_statuses.test.ts
browser-test/src/support/admin_programs.ts
server/app/views/admin/programs/ProgramApplicationView.java

No email configured for the status:
No email provided by applicant: 
Adding warnings when no email will be sent as part of updating a program's status

Adding warnings when no email will be sent as part of updating a program's status

---

browser-test/src/application_navigation.test.ts

Browser tests are currently failing in CI due to interaction between tests. This clears the database before running the screenshot tests to fix the issue.
N/A

Clear database before running application_navigation screenshot tests

---

server/test/controllers/admin/AdminApplicationControllerTest.java

Created a ProfileUtils fake for testing.  Admin Application features are guarded behind ACLs that we currently don't have a pattern for creating the data or faking otherwise.  This utility just bypasses all checks so subsequent code can be tested.
NA/ testing only

Add ProfileUtils tester to unlock testing being an admin/program ACL.

---

browser-test/src/question_lifecycle.test.ts
browser-test/src/support/admin_questions.ts
server/app/views/admin/questions/QuestionEditView.java

Updated the link text for these options per https://github.com/civiform/civiform/issues/1914#issuecomment-1220890859 and adding a link to the documentation that explains the options in further detail.
Before:
After:
Change data privacy settings option text and add link to documentation.
Fixes #1914

Change data privacy settings option text and add link to documentation

---

server/app/controllers/admin/AdminApplicationController.java
server/app/models/Application.java
server/app/services/applications/ProgramAdminApplicationService.java
server/app/views/admin/programs/ProgramApplicationView.java
server/test/controllers/admin/AdminApplicationControllerTest.java

Pipe the UI selected status to the BE and into the DB.
UI selection of a status by a Project Admin is now saved into the database.
Fixes #3263

Pass the UI select application status to the BE and save it.

---

server/app/controllers/dev/FeatureFlagOverrideController.java
server/app/featureflags/FeatureFlags.java
server/conf/routes

Adds a simple view to understand if feature flag overriding is enabled.
Display is of the form
```
Overrides are allowed if all are true:
Server environment: true
Configuration: true
```
Add a way for Admins to understand if feature flag overriding is configured.

Add display of Feature Flag overriding allowance configuration.

---

server/conf/application.conf

Adding the option to override the feature_flag_overrides_enabled via environment variable in Staging file. Adding this since the container uses application.conf only.

Override the feature_flag_overrides_enabled in application.conf

---

server/app/assets/javascripts/main.ts
server/app/views/BaseHtmlView.java
server/app/views/admin/programs/ProgramIndexView.java
server/app/views/admin/programs/ProgramStatusesView.java
server/app/views/admin/questions/QuestionEditView.java
server/app/views/admin/questions/QuestionsListView.java

1. Rename it to `asRedirectElement` and update types to take any element. This is needed as we are planning to make some other elements, for example divs that act as rows, clickable.
2. Handle clicks using JS instead of inline `onclick` attribute. That gives us more flexibility in future as we can add extra JS in listener, for example call to `e.stopPropagation()`
Issue #3033

Refactor asRedirectButton method

---

browser-test/src/support/admin_programs.ts
server/app/assets/javascripts/admin_programs.ts
server/app/views/BaseHtmlView.java
server/app/views/ViewUtils.java
server/app/views/admin/programs/ProgramAdministratorProgramListView.java
server/app/views/admin/programs/ProgramIndexView.java
server/app/views/components/ProgramCardFactory.java

Program admins also see a program list with distinct options from a CiviForm admin. That said, the styling is largely the same. This PR factors out the "render a program with a set of actions" logic from the CiviForm admin view into `ProgramCardFactory`. It is then reused by the program admin view to display program cards containing actions for 1) viewing applications and 2) making a shareable program link.
While here, I also adapted the TS code to attach the copy to clipboard behavior to any elements with the specified data attribute rather than just those inside of a program card list.
The only visual change was that we would previously show program admins data that a draft existed, which doesn't seem pertinent since program admins have no ability to affect a draft version.
Before: …

Program admin list view reuses the card styling that the CiviForm admin sees

---

server/app/views/admin/programs/ProgramAdministratorProgramListView.java

This was a conflict where #3311 renamed `asRedirectButton` to `asRedirectElement`. A new reference was added in #3310 and was merged to main without merging in the changes from #3311.
Fixing build breakage due to merge conflict.
#1238

Change asRedirectButton to asRedirectElement (due to the rename from #3311)

---

server/app/controllers/admin/AdminApplicationController.java
server/app/controllers/api/ProgramApplicationsApiController.java
server/app/repository/ProgramRepository.java
server/app/repository/SubmittedApplicationFilter.java
server/app/services/export/ExporterService.java
server/app/services/export/JsonExporter.java
server/app/services/program/ProgramService.java
server/app/services/program/ProgramServiceImpl.java
server/test/repository/ProgramRepositoryTest.java
server/test/services/export/JsonExporterTest.java

As part of #3269, we'll be adding a new filter option for application status. Presently, we plumb both the search fragment and submit time filter through all code that filters applications. This change allows future changes to be made without plumbing the same values everywhere. Instead the filters are created at the top-level call site and consumed from the relevant ProgramRepository method.
Internal code change to make adding more program admin application filtering options more maintainable.

Factor out SubmittedApplicationFilter type to allow more options to be added without updating all callsites

---

browser-test/src/admin_application_statuses.test.ts
server/app/controllers/admin/AdminApplicationController.java
server/app/models/Application.java
server/app/views/admin/programs/ProgramApplicationView.java
server/conf/evolutions/default/44.sql
server/test/models/ApplicationEventTest.java
server/test/models/ApplicationTest.java

Adds a `Application.latest_status` column corresponding to the most recent `ApplicationEvent` with type `status_change`. This value is precomputed via a database trigger.
The rationale for using a database trigger is documented [here](https://github.com/civiform/civiform/issues/3269#issuecomment-1232193163) (also linked in the database evolution).
This value is then consumed to populate the selected status value when the program admin is viewing an application. It is additionally used to in the status change confirmation dialog as the "previous status value".
This value will also be used in a subsequent PR to add filtering of applications via relevant statuses.
Adds a column indicating the application's current status that has been set by a program admin. 
Fixes #3020; Fixes #3267; #3264; …

Surface latest status within the UI, backed by a DB trigger to populate the value

---

server/app/repository/ApplicationRepository.java
server/app/services/applicant/ApplicantService.java

We have generic naming in our notification flow for what is in effect a TI flow; which is confusing and errorprone.
Also the current naming of "submitter" is ambiguous as the code flows explicitly mean "not the applicant", but applicants most often are the ones submitting applications. 
The code flows _could_ work if the submitter was a program admin, but the product does not allow for that, so I didn't aim to find a term that encompassed "not an applicant" and went with TI specifically.
The effective code flow root of the changes is [ApplicationService.submitApplication](https://github.com/civiform/civiform/pull/3329/files#diff-163cd8467b46ba09a916370044f5c51a2955bc56c2ee4650fb62ca66ccdd0d26R274)
NA, just code renaming.
Fixes #<issue_number>; Fixes #<issue_number>; Fixes …

Update code naming for TI notification in the submit flow

---

server/app/controllers/admin/AdminApplicationController.java
server/app/models/ApplicationEvent.java
server/app/services/applications/ProgramAdminApplicationService.java
server/app/views/admin/programs/ProgramApplicationView.java
server/test/controllers/admin/AdminApplicationControllerTest.java
server/test/models/ApplicationEventTest.java
server/test/models/ApplicationTest.java
server/test/repository/ApplicationEventRepositoryTest.java

Save the Application Note into the database.
Add an Id and name to the existing UI elements and have the Controller/Service save it as an ApplicationEvent.
Program Application Notes are now saved into the database. 
Addresses #3020 #3264

Pass the Application Note to the BE and save to the DB

---

browser-test/src/admin_application_statuses.test.ts

Fixes failing Seattle staging prober runs ([example](https://github.com/seattle-civiform/civiform-deploy/runs/8135343650?check_suite_focus=true)). This was due to the fact that we use `userDisplayName`, which returns "Guest" for non-prober runs and the test account's name when running against Seattle staging.
The test code had copied this from elsewhere, which meant that it was expecting the test user when run as a prober, even though it had completed the application as a guest.
N/A.

Updating assertions to expect 'Guest', since we log in as guest when completing applications

---

browser-test/src/question_lifecycle.test.ts
browser-test/src/support/index.ts
server/app/assets/javascripts/main.ts

The function simplifies managing browser-related, session stuff: it resets session between tests and launches/shutdowns browser once per test file. Using this function test writers don't need to worry about initialization of browser. Example usage:
```ts
describe('some test', () => {
const ctx = createTestContext();
it('does something', async () => {
// do something with ctx.page
})
})
```
By default it clears database between tests. Many tests rely on database not being cleared so for those tests I disable DB clearing. In future we should rework them so that each re-creates data from scratch. Doing it now will increase test runtime significantly. Once we have some batch approach to create data we can revisit it.
Issue #3323

Introduce createTestContext() function

---

server/app/services/export/CsvExporter.java
server/conf/evolutions/default/45.sql
server/test/repository/ProgramRepositoryTest.java

Confirmed with deployers that this is now safe to remove in https://github.com/civiform/civiform/issues/2821#issuecomment-1238321345.
Corresponding docs change is https://github.com/civiform/docs/pull/122.
Dropping a no-longer used database column for custom export code.
Fixes #2821

Creating evolution that drops programs.export_definitions, removed in #2814.

---

browser-test/src/support/index.ts

Staging probers are failing ([sample link](https://github.com/civiform/civiform-staging-deploy/runs/8206635473?check_suite_focus=true)) due to an axe accessibility test failing on the "Do not enter actual or personal data in this demo site" pop up dialog. This dialog is never show in prod, so is not a real issue.
We don't show the warning pop up message when running the browser tests in non-staging environments ([code link](https://github.com/civiform/civiform/blob/7f88bb7fa2ae2c8a790c462d8983953ceb066c2f/server/app/views/BaseHtmlLayout.java#L79)), so this was failing on staging but passing everywhere else.
This PR should hopefully fix the staging failures.
N/A

Close warning message dialog when resetting context in browser tests

---

server/app/views/admin/programs/ProgramApplicationListView.java
server/app/views/admin/programs/ProgramBlockPredicatesEditView.java
server/app/views/admin/questions/QuestionConfig.java
server/app/views/admin/questions/QuestionEditView.java
server/app/views/components/SelectWithLabel.java
server/app/views/questiontypes/DropdownQuestionRenderer.java
server/test/views/components/SelectWithLabelTest.java

Previously, an ImmutableMap<String, String> was passed in. Enumeration order isn't guaranteed for maps and relying on the implementation isn't scalable. Additionally, having an autovalue type improves readability of what each string value means and leaves us open to add more functionality in the future (e.g. a "disabled" selection option that we can use for grouping options).
This was noticed as part of #3320.
N/A
#3269

Convert SelectWithLabel to take a list of options rather than a map.

---

server/app/views/admin/programs/ProgramApplicationListView.java
server/app/views/components/SelectWithLabel.java
server/test/views/components/SelectWithLabelTest.java

This allows for visual separation of different application status filters (e.g. "General" filters such as all applications) vs for a specific status.
Better organize application status filter options within the program admin view.
Fixes #3269

Add separate optgroups for application status filtering for program admin.

---

server/app/views/admin/programs/ProgramApplicationView.java

This is a regression from https://github.com/civiform/civiform/pull/3191 where we incorrectly added the overflow-hidden class to the application content (thus disabling scrolling).
Before (not scrollable):
After (scrollable):
Fix issue where program admins viewing an application could not scroll through all of the content.
Fixes #3362

Removing overflow-hidden that prevented application viewing from being scrollable.

---

browser-test/src/admin_program_creation.test.ts
browser-test/src/admin_program_hidden.test.ts
browser-test/src/application_download.test.ts
browser-test/src/application_previous_version.test.ts
browser-test/src/application_review.test.ts
browser-test/src/error_pages.test.ts
browser-test/src/question_delete.test.ts
browser-test/src/question_lifecycle.test.ts
browser-test/src/support/index.ts

This will help with local test development as today we often wait for 30sec before test times out and fails. We shouldn't places where we wait for more than 5 sec for some elements to render/become visible.

Set browser test timeout to 5 sec for all tests

---

.github/workflows/tests.yaml
server/test/app/SecurityBrowserTest.java

Fixing CI breakage described in https://github.com/civiform/civiform/issues/3326#issuecomment-1239971757.
In addition to fixing the test assertions, I also updated CI to build the test OIDC container (similar to browser-tests below) prior to running unit tests so that the version used matches the test code.
N/A
#3326

Fix CI breakage where unit test assertion doesn't match the updated OIDC image from #3334

---

browser-test/src/admin_application_statuses.test.ts
browser-test/src/application_download.test.ts
browser-test/src/security.test.ts
browser-test/src/support/admin_programs.ts

Add type definition for the application JSON object that can be downloaded by program admins. It doesn't guarantee that type definition doesn't become stale but at least it provides TS code with better centralized type checking. Needed for #3361

Improve typing of TS browser tests

---

server/app/views/components/CreateQuestionButton.java
server/app/views/components/QuestionBank.java

Dropdown for "create-new-question" doesn't have a scroll option. So Admins cannot choose other options.
Dropdown for "create-new-question" doesn't have a scroll option. So Admins cannot choose other options.
Fixes #3365 ; 
Screenshots
Before:
After:

fixing Create-new-question dropdown (as the scroll bar isn't working)

---

server/app/filters/DisableCachingFilter.java
server/build.sbt
server/test/views/BaseHtmlLayoutTest.java

This improves speed of browser tests. For quesiton_lifecycle.test.ts duration goes from 250s to 140s. Fingerprinting guarantees that when while changes - a new version will be requested. The downside of that approach is that it adds an extra step (fingerprinting) into incremental rebuild of static assets (TS files). But that adds only around 1-2s so it's practically unnoticeable. It might become an issue in future if we have bigger static files, but with current guidelines (minimum JS) that unlikely to happen soon.

Enable fingerpriting and caching for static files even on dev mode

---

browser-test/src/support/index.ts

Noticed when starting to manually test using a new test user with AWS staging (https://github.com/civiform/civiform/issues/3326#issuecomment-1244021249).
Auth0's login URL is of the form `.../u/login?state=<elided>`, whereas the test assertion was assuming that there'd be a trailing slash in the URL (e.g. `.../u/login/?state=<elided>`). This fixes that assumption and also adds a positive assertion that a successful login flow indicates it in the UI as well.
Manually tested by running `bin/build-browser-tests` then running:
```
docker run \
-e TEST_USER_AUTH_STRATEGY="aws-staging" \
-e TEST_USER_LOGIN="<elided>" \
-e TEST_USER_PASSWORD='<elided>' \
-e TEST_USER_DISPLAY_NAME="<elided>" \
-e BASE_URL="https://staging-aws.civiform.dev" \
-e DISABLE_SCREENSHOTS=true …
```

Fixing incorrect URL assumption for AWS staging prober login (not yet used)

---

browser-test/src/support/admin_programs.ts
server/app/views/admin/programs/ProgramFormBuilder.java

New text per https://github.com/civiform/civiform/issues/1910#issuecomment-1222781451.
Updating the visibility option text shown when a CiviForm admin creates or edits a program.
Fixes #1910

Updating the visibility option text shown when a CiviForm admin creates or edits a program.

---

server/app/services/applicant/AnswerData.java
server/app/services/applicant/ReadOnlyApplicantProgramServiceImpl.java
server/app/services/export/PdfExporter.java
server/app/views/admin/programs/ProgramApplicationView.java
server/app/views/applicant/ApplicantProgramSummaryView.java
server/test/services/applicant/ReadOnlyApplicantProgramServiceImplTest.java
server/test/views/BaseHtmlLayoutTest.java

Moved EncodedFileKet as a memeber of the AnswerData class. It will be a common field like the FileKey(). 
EncodedFileKey is moved a universal location. So all file downloads should be using it.
Fixes #3409

Moving getEncodedFileKey to common function and fixing unit tests

---

server/app/views/components/ProgramCardFactory.java
server/test/controllers/admin/AdminProgramControllerTest.java

The name associated with the draft version of the program is preferred over the name associated with the active version of the program.
This is the first step in de-emphasing the internal-facing name / description described in https://github.com/civiform/civiform/issues/3085#issuecomment-1246008757.
The "internal description" has been relabeled as "Admin note", similar to what we now do on the question list page.
CiviForm admin / program admin program list now displays the "Display name / description" for a program rather than the internal admin name / description.
#3085

Switching to use external name / description for the program card in the program list view
