civiform/civiform

browser-test/src/admin_program_creation.test.ts
browser-test/src/end_to_end_enumerators.test.ts
browser-test/src/support/admin_programs.ts
server/app/views/components/QuestionBank.java

Renaming "Filter questions" to "Search questions",
Renaming "Question bank" to "Add question"
Renaming "Filter questions" to "Search questions",
Renaming "Question bank" to "Add question"
Fixes #3031; Fixes #3084; Fixes #<issue_number>...

Change text in question bank

---

cloud/aws/templates/aws_oidc/bin/setup.py

Add a note about verifying email address at the end of setup

Add a note about verifying email address at the end of setup

---

cloud/aws/templates/aws_oidc/app.tf
cloud/aws/templates/aws_oidc/variables.tf
cloud/azure/modules/app/locals.tf
cloud/azure/modules/app/variables.tf
cloud/azure/templates/azure_saml_ses/main.tf
cloud/azure/templates/azure_saml_ses/variables.tf
cloud/shared/variable_definitions.json

Needs to be set to false in staging to make our browser tests pass.

add CIVIFORM_API_KEYS_BAN_GLOBAL_SUBNET to terraform

---

cloud/aws/templates/aws_oidc/bin/setup.py

Fix fargate tasks links due to updated resource names

---

server/app/assets/javascripts/dev_icons.ts
server/app/views/BaseHtmlView.java
server/app/views/admin/programs/ProgramStatusesView.java
server/app/views/applicant/ProgramIndexView.java
server/app/views/components/Icons.java
server/app/views/components/QuestionBank.java
server/app/views/components/TextFormatter.java
server/app/views/dev/IconsView.java
server/test/views/components/IconsTest.java

SVG stored in Icons.java all developed for certain sizes (20, 24, 48). This size has been lost when adding SVG to Icons enum. Currently callers of icons have to know that size and pass it explicitly, which is error-prone and unnecessary. Instead callers should not care about original SVG size, they should care only about what size they want to render in their specific case on a page. They should treat `SvgTag` returned by Icons.svg() as any other DOM element that needs to be styled using classes. Example recommended usage:
```
Icons.svg(Icons.ICON_NAME).withClasses(Styles.H_4, Styles.W_4)
```
This PR includes several changes:
1. Remove all svg() methods that take separate width and height arguments. At the moment all icons are square and that's very likely going to be that way going …

Enforce consistent sizing in icons svg

---

README.md

Update AWS and Azure staging badges with the new repo

---

server/app/views/admin/programs/ProgramStatusesView.java

Repoint status tracking TODO at a more scoped bug.

---

cloud/aws/bin/deploy.py

Fixing the naming of fargate cluster in the url to include suffix.

fix task name for fargate

---

browser-test/src/question_lifecycle.test.ts

drop tables before canonical questions test

---

browser-test/src/admin_application_statuses.test.ts

Repoint status tracking TODO at a more appropriate issue.

---

.github/workflows/release.yaml
bin/create-release

git branch now works, action needed extra param to checkout history. 
Better error messaging.

Fix git branch issue + Better error messaging for release script

---

browser-test/src/address.test.ts
browser-test/src/checkbox.test.ts
browser-test/src/currency.test.ts
browser-test/src/date.test.ts
browser-test/src/dropdown.test.ts
browser-test/src/email.test.ts
browser-test/src/end_to_end_enumerators.test.ts
browser-test/src/file.test.ts
browser-test/src/id.test.ts
browser-test/src/name.test.ts
browser-test/src/number_input.test.ts
browser-test/src/radio_button.test.ts
browser-test/src/static_text.test.ts
browser-test/src/support/index.ts
browser-test/src/text.test.ts

Migrate applicant question tests to use TestContext

---

browser-test/src/application_download.test.ts
browser-test/src/application_navigation.test.ts
browser-test/src/application_previous_version.test.ts
browser-test/src/application_review.test.ts
browser-test/src/civiform_admin_program_statuses.test.ts
browser-test/src/civiform_admin_question_references.test.ts
browser-test/src/support/index.ts

Migrate more tests to use TestContext

---

cloud/azure/bin/lib/azure.sh
cloud/azure/modules/app/main.tf
cloud/azure/modules/app/variables.tf
cloud/azure/templates/azure_saml_ses/variable_definitions.json
cloud/deploys/dev_azure/bin/docker-build-tag-push
cloud/deploys/dev_azure/civiform_config.example.sh

Motivation: reducing number of variables that client needs to fill out. 
I don't think we have a big use case for testing with a custom build image that this was supposed to help with. 
We're also not using it for AWS.

hardcode civiform docker

---

server/app/views/admin/programs/ProgramApplicationListView.java

Feedback from UX as part of unrelated work on status tracking. Specifically:
* Replace "Application submitted" to "Applications submitted"
* Change the casing of from/until to lowercase
Before:
After:

Copy edits to the "application submitted" time filter that the program admin sees

---

.github/workflows/aws-oidc-deploy-test.yaml
.github/workflows/azure-saml-ses-deploy-test.yaml
.github/workflows/pr_cloud_skip.yaml
.github/workflows/pr_server_skip.yaml

Found by code scanning: https://github.com/civiform/civiform/security/code-scanning/244

Add permissions to actions that don't have them yet

---

.github/workflows/aws-oidc-deploy-test.yaml
.github/workflows/azure-saml-ses-deploy-test.yaml
.github/workflows/pr_cloud_skip.yaml
.github/workflows/pr_server_skip.yaml

Reverts civiform/civiform#3423
Reverting out of suspicion that this is preventing some checks from running

Revert "Add permissions to actions that don't have them yet"

---

cloud/aws/templates/aws_oidc/filestorage.tf

Fix role arn

---

cloud/azure/bin/db-connection

Without this role, I was getting: `ERROR: Caller is not authorized to perform action on resource.`
N/A

Update db-connection comment with instructions on correct credentials

---

server/test/services/applicant/ApplicantServiceTest.java

Repoint TODO at a more appropriate issue.

---

server/app/controllers/admin/AdminProgramBlockQuestionsController.java
server/app/controllers/admin/AdminQuestionController.java
server/app/services/applicant/Currency.java
server/app/services/export/PdfExporter.java
server/app/services/ti/TrustedIntermediaryService.java
server/app/views/admin/questions/QuestionEditView.java
server/app/views/admin/questions/QuestionPreview.java
server/app/views/components/ToastMessage.java

IntelliJ identified unused initializations.
NA Code cleanup

Remove unused assignments.

---

browser-test/src/support/admin_programs.ts

Follow-on feedback from @nbeloglazov in https://github.com/civiform/civiform/pull/3498#discussion_r980409817.
We can simplify the selector used to add a question from the question bank.
N/A
#3075

Simplifying the locator used to add a question from the question bank.

---

server/app/forms/translation/QuestionTranslationForm.java
server/app/services/applicant/question/ApplicantQuestion.java
server/app/services/program/StatusDefinitions.java
server/test/forms/translation/QuestionTranslationFormTest.java

Follow-on to https://github.com/civiform/civiform/pull/3537 for a few more classes that can be marked final / abstract. 
N/A

Marking more classes as final

---

server/app/assets/javascripts/admin_applications.ts

Fix another style conflict that breaking a style in https://github.com/civiform/civiform/pull/2630

fix style conflict in admin application cards

---

server/app/services/question/QuestionService.java

Fix string message found by #3636 
Fix obscure-error message templating.

Fix templating in Precondition message

---

browser-test/src/support/index.ts

Apply comment from https://github.com/civiform/civiform/pull/3671 which got auto-merged before I could fix it.

Fix wording in comment

---

server/app/views/applicant/TrustedIntermediaryDashboardView.java

Updating Email Placeholder text for adding new TI Clients
Updating Email Placeholder text for adding new TI Clients
Fixes #3731

Updating Email Placeholder text for adding new TI Clients

---

browser-test/src/admin_program_creation.test.ts
browser-test/src/civiform_admin_question_list.test.ts
browser-test/src/support/admin_programs.ts

Add browser test for filtering questions in question bank

---

bin/docker-reset

Add a new `bin/` script for destroying all docker resources.

Add bin/docker-reset

---

formatter/fmt

We already do a check for java files, adding check for ts files. 
Inspired by https://github.com/civiform/civiform/issues/2985.

only run prettier and eslint if TS files were modified

---

server/app/controllers/applicant/ApplicantProgramBlocksController.java

Add docs and clean up code a little.
NA - cleanup

Doc and code cleanup ApplicantProgramBlocksController.update()

---

server/app/services/applicant/ReadOnlyApplicantProgramServiceImpl.java

code cleanup for ReadOnlyApplicantProgramServiceImpl

---

.github/workflows/assign_issues_to_project.yaml
.github/workflows/pr_server_skip.yaml
.github/workflows/release.yaml

This fixes some high level alerts in github actions token permissions on the security tab
This fixes some high level alerts in github actions token permissions on the security tab
Fixes #3846

Fixing security alerts

---

server/app/assets/javascripts/admin_applications.ts
server/app/assets/javascripts/azure_delete.ts
server/app/assets/javascripts/azure_upload.ts
server/app/assets/javascripts/dev_icons.ts
server/app/modules/CloudStorageModule.java
server/app/views/AwsFileUploadViewStrategy.java
server/app/views/AzureFileUploadViewStrategy.java
server/app/views/FileUploadViewStrategy.java
server/app/views/dev/IconsView.java
server/app/views/style/ReferenceClasses.java

Most JS files today use initialization pattern where they check whether certain DOM element is present on the page and if so - initialize themselves. This PR updates all files to use the same pattern. This is required for upcoming JS bundling change where we'll compile all files together for admins and for applicants. So each JS file must handle the case where it's loaded on a page that doesn't actually "need" that file.
No-op refactoring of JS files for upcoming JS bundling chnage.
Issue #3864

Refactor JS files to use consistent initialization pattern

---

server/app/models/PersistedDurableJob.java
server/conf/evolutions/default/46.sql
server/test/models/PersistedDurableJobTest.java

Adds the database layer for the [durable background jobs](https://docs.google.com/document/d/1pSKbJXrQz-qtq-ZNkS4x1Zbwa8Y3pkRU6pBDkA-lv7s/edit) system.
Part of https://github.com/civiform/civiform/issues/3899

Add model PersistedDurableJob

---

server/app/assets/javascripts/admin_validation.ts
server/app/assets/javascripts/enumerator.ts
server/app/assets/javascripts/preview.ts
server/app/assets/javascripts/toast.ts

Currently some JS files rely on the fact that JS files loaded individually and that they execute in global environment. With JS bundling that will no longer be the case as there each JS file ends up being executed in its own function scope (imitating execution within a module). 
This PR fixes 2 cases where we rely on files being loaded in global environment. Also removes few unnecessary local variables during controller instantiations. 
Issue #3864

Refactor JS to prepare for JS bundling migrationg

---

server/test/services/program/ProgramDefinitionTest.java

These test build complicated programs but use unhelpful names and hard coded identifiers; this PR makes them more readable and less error prone

Clarify naming in complicated program building tests

---

server/app/services/program/ProgramDefinition.java
server/app/services/program/ProgramServiceImpl.java
server/test/repository/VersionRepositoryTest.java
server/test/services/applicant/ReadOnlyApplicantProgramServiceImplTest.java
server/test/services/program/ProgramDefinitionTest.java
server/test/services/program/ProgramServiceImplTest.java
server/test/support/ProgramBuilder.java

ProgramDefinition cleanups and additional testing

---

browser-test/src/admin_program_translation.test.ts

Uncomment test that required browser control of feature flags
Fixes #3071

Uncomment Status Tracking test

---

server/app/services/MessageKey.java
server/app/views/questiontypes/FileUploadQuestionRenderer.java
server/conf/messages
server/conf/messages.en-US

Add a translation for "Choose FIle". I'll plan to create a localization request for this text as well.
#3371

Add translation for "Choose File" button

---

browser-test/src/application_navigation.test.ts
browser-test/src/support/applicant_questions.ts
server/app/services/applicant/AnswerData.java
server/app/views/applicant/ApplicantProgramSummaryView.java

Fixes an issue in the application review page where unanswered questions are marked ineligible.
Fixes #4124

Fix bug where unanswered question shows as Not Eligible

---

server/conf/messages

This creates keys for the new eligibility text from this [copy doc](https://docs.google.com/document/d/14zPxWA-TrjCmyxEgSkawYYUfDYxQPgY9DKQVQBRgfhc/edit?resourcekey=0-_QBYpeXQPsCN_ZyX_SuumA#heading=h.wm8dmtm3jyp0). Next steps will be sending this out for translation and using these keys when applicable. I will also add this to the english file, once the comments are finalized.
#4127

Add messages for new eligibility text

---

server/conf/messages.am
server/conf/messages.es-US
server/conf/messages.ko
server/conf/messages.so
server/conf/messages.tl
server/conf/messages.vi
server/conf/messages.zh-TW

Added translations for strings in messages files
Fixes #4003, #3371, #4127

Add translations

---

server/app/durablejobs/DurableJobName.java
server/app/durablejobs/DurableJobRegistry.java
server/app/durablejobs/RecurringJobExecutionTimeResolvers.java
server/app/durablejobs/RecurringJobScheduler.java
server/app/modules/DurableJobModule.java
server/app/repository/PersistedDurableJobRepository.java
server/test/durablejobs/DurableJobRegistryTest.java
server/test/durablejobs/DurableJobRunnerTest.java
server/test/durablejobs/DurableJobSchedulerTest.java
server/test/durablejobs/RecurringJobExecutionTimeResolversTest.java
server/test/repository/PersistedDurableJobRepositoryTest.java

See [design doc](https://docs.google.com/document/d/1pSKbJXrQz-qtq-ZNkS4x1Zbwa8Y3pkRU6pBDkA-lv7s/edit#heading=h.fknq0a9xnthm) for context. This PR implements scheduling recurring jobs.
I will hold off on adding to the docs repo until the system is ready for use.
Contributes to https://github.com/civiform/civiform/issues/3899

Recurring job scheduler

---

server/app/views/admin/programs/ProgramBlockEditView.java

See [here](https://docs.google.com/document/d/14zPxWA-TrjCmyxEgSkawYYUfDYxQPgY9DKQVQBRgfhc/edit?resourcekey=0-_QBYpeXQPsCN_ZyX_SuumA) for copy update
#3744

Update admin eligibility info copy

---

.github/workflows/auto-author-assign.yml

Looks like this broke a few days ago.

Add v to version specification for auto-author-assign.

---

server/app/services/applicant/ApplicantService.java
server/test/services/applicant/ApplicantServiceTest.java

Use getSerializationFormat() instead of toString() on Enum

Use getSerializationFormat() instead of toString() on Enum

---

server/app/views/admin/programs/ProgramBlockEditView.java

Add gating/non-gating explanation to admin eligibility text.

---

.github/workflows/build_push_ci.yaml
.github/workflows/release.yaml
.github/workflows/tests.yaml

Moves docker hub user name into a secret after converting civiform to an organization.

updates docker hub username

---

server/conf/messages.am
server/conf/messages.es-US
server/conf/messages.ko
server/conf/messages.so
server/conf/messages.tl
server/conf/messages.vi
server/conf/messages.zh-TW

Add translations for final eligibility string
#3744

Add translations for eligibility string

---

browser-test/src/applicant_application_index.test.ts
server/app/controllers/applicant/ApplicantProgramReviewController.java
server/app/services/MessageKey.java
server/app/services/applicant/ReadOnlyApplicantProgramService.java
server/app/services/applicant/ReadOnlyApplicantProgramServiceImpl.java
server/app/views/applicant/ApplicantProgramSummaryView.java
server/conf/messages

Change the title of the program summary page for the intake form.
Fixes #4384

Change the title of the program summary page for the intake form.

---

server/app/views/admin/programs/ProgramBlockEditView.java

This got excluded from a previous PR by accident.

Formatting tweak.

---

server/conf/messages
server/conf/messages.am
server/conf/messages.en-US
server/conf/messages.es-US
server/conf/messages.ko
server/conf/messages.so
server/conf/messages.tl
server/conf/messages.vi
server/conf/messages.zh-TW

Added translations for string from the 3/1/2023 batch of translations, from the Sheet linked in go/civiform-translations.
N/A
Fixes #4395

Add 3/1 Translations Batch

---

server/test/featureflags/FeatureFlagsTest.java

Parameterizes `FeatureFlagsTest.java` so that we test all flags. Cleans up the tests to be much more readable than before.

Parameterize `FeatureFlagsTest.java`

---

server/app/views/admin/programs/ProgramAdministratorProgramListView.java
server/app/views/admin/programs/ProgramBlockEditView.java
server/app/views/admin/programs/ProgramIndexView.java

Update a few Common Intake Form strings based on UX audit.

Update common intake form strings based on UX audit.

---

docker-compose.yml
localstack/localstack.Dockerfile

Reverts civiform/civiform#4538

Revert "Update localstack/localstack Docker tag to v2"

---

README.md

Removing until we get the Azure deploy working again.

Removing the Azure Staging deploy badge

---

.github/workflows/release.yaml

Adding persmissions to "update_environment_variable_documentation_markdown" section in release.yaml
Adding persmissions to "update_environment_variable_documentation_markdown" section in release.yaml

Adding persmissions to "update_environment_variable_documentation_markdown" section in release.yaml

---

.github/ISSUE_TEMPLATE/oncall-rotation.md

Update on call bug template after discussion in eng chat to make rotations M-F

Update oncall bug template

---

server/test/controllers/RedirectControllerTest.java
server/test/controllers/WithMockedProfiles.java

Add missing tests for RedirectController.
Fixes #4590

Add tests for RedirectController.

---

.github/workflows/assign_issues_to_project.yaml
.github/workflows/build_push_ci.yaml
.github/workflows/generate_env_var_docs_markdown_for_release.yaml
.github/workflows/pr_env_var_docs.yaml
.github/workflows/pr_server.yaml
.github/workflows/pr_server_skip.yaml
.github/workflows/push_tests.yaml
.github/workflows/release.yaml
.github/workflows/tests.yaml
.github/workflows/tests_skip.yaml

The names of our github actions can be cryptic and some are the same. I renamed them to be more descriptive and to give some at a glance context of what they do.

Giving descriptive names to actions

---

server/app/auth/ApiAuthenticator.java
server/test/auth/ApiAuthenticatorTest.java

Fixes https://github.com/civiform/civiform/issues/4775, see last comment

Parse X-Forwarded-For header

---

docker-compose.dev.yml

Need civiform/ prefix to be added. This was causing an issue with running locally

Update mock-web-services image

---

browser-test/src/program_deep_link.test.ts
browser-test/src/support/index.ts
server/app/controllers/applicant/RedirectController.java

Fix program by slug when BYPASS_LOGIN_LANGUAGE_SCREENS is on.

---

server/test/repository/VersionRepositoryTest.java

These assertions are duplicated right above and are extraneous.

Remove duplicate assertions.

---

server/conf/i18n/README.md
server/conf/i18n/messages
server/conf/i18n/messages.am
server/conf/i18n/messages.es-US
server/conf/i18n/messages.ko
server/conf/i18n/messages.so
server/conf/i18n/messages.tl
server/conf/i18n/messages.vi
server/conf/i18n/messages.zh-TW

Adds a `README.md` file to the `i18n` folder. Modifies `messages.xx` files to reference it.
None.
None.
None.

Add `README.md` to i18n folder

---

server/app/repository/VersionRepository.java
server/test/repository/VersionRepositoryTest.java

Follow up to #4898. I missed this edge case that happens when no programs have ever been created and you try to publish questions.

Allow publishing questions without programs.

---

renovate.json

[Microsoft recommends that the docker image](https://mcr.microsoft.com/en-us/product/playwright/about#configuration) be kept in sync with the packages used external from it. This should aid in mitigating version differences.

Update renovate to group playwright

---

server/app/services/reporting/ReportingService.java
server/test/services/reporting/ReportingServiceTest.java

Sorts reporting data by timestamp descending for data that is broken out chronologically by month.
Fixes https://github.com/civiform/civiform/issues/4985

Sort reporting data by timestamp

---

browser-test/src/support/admin_programs.ts

Change the ordering of the await statements to see if this fixes the issue with Seattle probers.

Attempt to fix Seattle prober

---

server/app/auth/oidc/CiviformOidcProfileCreator.java
server/app/auth/oidc/admin/AdfsProfileCreator.java
server/app/auth/oidc/applicant/ApplicantProfileCreator.java
server/app/controllers/admin/TrustedIntermediaryManagementController.java
server/app/repository/UserRepository.java
server/app/services/ti/NotEligibleToBecomeTiError.java
server/app/views/admin/ti/EditTrustedIntermediaryGroupView.java
server/test/auth/oidc/CiviformOidcProfileCreatorTest.java

This PR opens the door to trusted intermediaries to log in with ADFS in addition to the applicant backend. Based on the requirements discussed, we do not need to account for users that are both TIs and CiviForm/Program admins. Therefore, we implement a rejection of adding TIs if they are already in one of these roles.
Trusted Intermediaries can now use ADFS to log in to CiviForm.
- Since we don't have a fake ADFS the same way we have fake OIDC, I don't know how we could test that logging in as a TI with ADFS works correctly.
- Not possible to authenticate with ADFS in a browser test so we cannot directly test logging in
- Not possible to test the rejection of new TIs if they are already a program/civiform admin, because we need their email address (like …

Allow TIs to authenticate with ADFS, in addition to the applicant identity provider

---

browser-test/src/admin_program_visibility.test.ts

Changing email address to be unique in TI visibility tests.
Fixes https://github.com/civiform/civiform/issues/5050

Prober fix for timeout failures related to TI visibility tests

---

.github/pull_request_template.md

Add 18n reminder to pull request template

Update pull request template to add i18n reminder

---

.github/workflows/assign_issues_to_project.yaml

Updating token used in action
Fixes #4112

Updating token used in action

---

server/app/assets/javascripts/main.ts

Fix issue where users were unable to create a new line when creating/editing a static text question as a CF admin.
Fixes #5173

Fix issue where users could not add newlines to questions.

---

server/app/models/Version.java
server/app/repository/VersionRepository.java
server/app/services/program/ProgramServiceImpl.java
server/test/models/VersionTest.java

Add tests for Version.java since it didn't have any. Also makes a minor tweak to a method name (getProgramsNames -> getProgramNames) to make it more readable and consistent with other names and re-arranges a few of the methods so that related methods are grouped.
Fixes #4912

Add tests for Version.java.

---

server/test/controllers/admin/AdminApplicationControllerTest.java
server/test/durablejobs/DurableJobRegistryTest.java
server/test/repository/VersionRepositoryTest.java
server/test/services/DateConverterTest.java
server/test/services/applications/ProgramAdminApplicationServiceTest.java

Replace assertThrows with assertThrownBy for consistency.
Part of #5223

Replace assertThrows with assertThrownBy.

---

server/app/controllers/dev/seeding/DevDatabaseSeedTask.java

Use consistent capitalization for sample program names.

Use consistent capitalization for sample program names.

---

server/conf/logback.xml

Modify `logback.xml` to log `services` at `INFO` level.
Modify `logback.xml` to log `services` at `INFO` level.

Log "services" at INFO level.

---

server/app/services/applicant/question/PhoneQuestion.java

Updating logger.error to logger.warn for phone formatting errors
Fixes #5258

Removing logger.error for phone question formatting errors

---

env-var-docs/generate_markdown.py
env-var-docs/generate_markdown_test.py
env-var-docs/parser-package/README.md
server/conf/helper/feature-flags.conf

Enables the admin settings panel for all users and updates the automatic variable doc generation script to include each variable's mode.

Admin settings panel enabled for all deployments

---

.github/workflows/tests.yaml
test-support/prod-simulator-compose.yml

Enables devices running ARM chips to run the prod simulator. Also cleans up the prod simulator compose a bit for clarity.

Support prod simulator for ARM devices

---

server/app/services/applicant/RepeatedEntity.java

Changes `visibiity` to `visibility` throughout.
n/a
- [n/a] Followed steps to [internationalize new strings](https://docs.civiform.us/contributor-guide/developer-guide/internationalization-i18n#internationalization-for-application-strings)
- [n/a] Wrote browser tests using the [validateAccessibility](https://sourcegraph.com/github.com/civiform/civiform/-/blob/browser-test/src/support/index.ts?L437:14&subtree …

Fix typo in RepeatedEntity.java

---

server/app/services/applicant/ApplicantService.java

Fetch account asynchronously when submitting application.

Get account asynchronously when submitting application.

---

browser-test/package-lock.json
browser-test/package.json
browser-test/src/application_navigation.test.ts
formatter/package-lock.json
formatter/package.json
server/package-lock.json
server/package.json

needed to use lowercase `"submit"` button type to appease type checker

Upgrade typescript

---

server/app/services/program/ProgramServiceImpl.java

Sort the slugs in getAllProgramSlugs

Adding sort on getAllProgramSlugs

---

server/package-lock.json

Update packages identified by `npm audit`
n/a
n/a
n/a

Update packages identified by `npm audit`

---

server/app/services/export/JsonExporter.java
server/app/services/export/QuestionJsonPresenter.java
server/test/services/export/AbstractExporterTest.java
server/test/services/export/JsonExporterTest.java

Adds enumerator questions to JSON export
Previously, the answers to enumerator questions themselves (the names of the repeated entities) were not included in the JSON export.
After this change, they are included in the response.
Also:
- Updates `MultiSelectJsonPresenter` to return an empty `Optional` when unanswered, to be consistent with how unanswered enumerator questions are handled.
- Adds additional tests for nested repeated entities.
- Updates some variable names in `JsonExporter`.
- Updates some `QuestionJsonPresenter`s to use the contextualized path builder built in to the `Question`, when available, instead of building it ourselves.
This does not add enumerator question to the sample API documentation. That is #5238.
The names of repeated entities (eg the name of a household …

Add enumerator questions to JSON export

---

server/app/repository/ProgramRepository.java
server/test/repository/ProgramRepositoryTest.java

Currently, searching for applications as a Program Admin only returns applications where the email being searched matches the email of the TI who submitted the application on behalf of an applicant. This PR adds the logic to also search the applicant's email on the accounts table which will be filled in if an applicant has created an account and logged in, or if the TI included an email for the applicant when adding them. This PR also adds the ability to search TI and applicant email by a partial string, similar to how name search functionality works now.
Applying as a TI
1. Create a program and publish it
2. As a TI, add a client …

Allow searching by applicant email in Program Admin application search

---

server/conf/routes

Fix column alignment in routes file

---

server/app/services/settings/SettingsManifest.java
server/conf/env-var-docs.json

Eng docs have moved to the [wiki](https://github.com/civiform/civiform/wiki/) so we need to update the links here.

Update docs links in env-var-docs.json

---

server/app/services/program/ProgramServiceImpl.java

We look up question data on the program admin page in order to determine eligibility status, but we don't need to do this if the program doesn't have eligibility configured and we should only look up the questions once for each version. 
This reduces the number of question calls from 1x per program to 1x per program version where eligibility applies.
#5514

Only load question data on index page for programs with eligibility conditions

---

server/app/services/applicant/ReadOnlyApplicantProgramServiceImpl.java

Updates the CSV export to use the new `adminName` field on QuestionOptions, instead of retrieving the localized user-facing text.
Details:
- Similar to #5566 is not a user facing change, as the `QuestionOption` still just sets the admin name to the default locale's text for now.
- As the option text itself hasn't changed, the tests do not currently need updating. They'll be updated as part of the remainder of #4862.
n/a - This is not a user-facing change.
n/a
n/a
n/a
This is part of #4862

Update CSV to use admin names

---

.github/ISSUE_TEMPLATE/oncall-rotation.md

Link was pointing to docs.civiform.us, but we moved it to github wiki.

Update Oncall Rotation Release Docs Link

---

.github/ISSUE_TEMPLATE/feature_flag.md

Updating as we moved this from docs.civiform.us to the github wiki.

Update Link in feature_flag.md

---

server/app/services/applicant/ApplicantService.java
server/test/services/applicant/ApplicantServiceTest.java

The link on the program admin's new submission email now points to the search screen with new application automatically loaded. The current link points to the page that is rendered in a iframe and doesn't have any navigation capabilities.
Fixes #5594

Change program admin email link

---

.github/workflows/pr_server_skip.yaml

This will ensure we don't introduce breaking changes by upgrading one of our docker image versions.
Fixes https://github.com/civiform/civiform/issues/5705

Run server tests even on docker file change

---

server/app/services/applicant/ReadOnlyApplicantProgramServiceImpl.java
server/app/services/applicant/question/MultiSelectQuestion.java
server/app/services/export/QuestionJsonPresenter.java
server/app/services/question/types/MultiOptionQuestionDefinition.java
server/app/services/question/types/QuestionDefinition.java
server/app/views/api/ApiDocsView.java
server/test/forms/MultiOptionQuestionFormTest.java
server/test/services/applicant/question/MultiSelectQuestionTest.java
server/test/services/question/types/MultiOptionQuestionDefinitionTest.java

Fix the pluralization on method names.
n/a
n/a
n/a
n/a
n/a - it was just bugging me

Fix method name pluralization

---

server/app/services/MessageKey.java
server/conf/i18n/messages

Updating the copy for the duplicate submission redirect screen as the designs changed slightly. Related to https://github.com/civiform/civiform/issues/4869

Update copy to be translated for duplicate submission screen

---

server/conf/i18n/messages

This is an attempt to add context string within the messages file to see if transifex rewrites it.

Try adding a context string in the messages file

---

.github/ISSUE_TEMPLATE/translations_rotation.md

Fix formatting of file based on bin/fmt.

Update formatting on translation template

---

server/app/controllers/ErrorHandler.java

Replace some injected instances with providers in `ErrorHandler`.
While developing [Create filter to store a session id](https://github.com/civiform/civiform/pull/5695), the `test_prod` check was failing when trying to start the server.
The cause was that PR added a `Filter`, for which the constructor took a `Materializer` as a parameter. This caused the `Materializer` to be instantiated earlier than it would have otherwise, which causes it to create an `ErrorHandler`. This class has some injected dependencies that themselves have transient dependencies on the database, which is not yet initialized.
The fix is to inject `Provider`s for those dependencies so that they can be dereferenced after server startup. …

Inject Providers into ErrorHandler

---

server/conf/i18n/messages

Updated copy for the duplicate submissions screen to be added in this PR: https://github.com/civiform/civiform/pull/5752

Update copy for duplicates screen

---

.github/workflows/format.yaml
.github/workflows/pr_env_var_docs.yaml
.github/workflows/pr_server_skip.yaml

Catching the ones I missed in #5780

Run presubmits on all PRs

---

server/app/services/MessageKey.java
server/conf/i18n/messages

Adds "Close" to messages and MessageKey for translation.
N/A
N/A
N/A
Helps with #5520 but does not fix it yet.

Add a "Close" message.

---

server/conf/helper/auth.conf

Now that our developer docs are on the GH wiki, this link needs to be updated.

Update link to point to wiki

---

browser-test/src/support/index.ts
server/app/auth/CiviFormProfileMerger.java
server/app/auth/ProfileFactory.java
server/app/controllers/HomeController.java
server/app/controllers/applicant/ApplicantInformationController.java
server/app/controllers/applicant/ApplicantProgramReviewController.java
server/app/controllers/applicant/ApplicantProgramsController.java
server/app/controllers/applicant/UpsellController.java
server/app/repository/AccountRepository.java
server/app/views/applicant/ApplicantCommonIntakeUpsellCreateAccountView.java
server/app/views/applicant/ApplicantUpsellCreateAccountView.java
server/app/views/applicant/ApplicantUpsellView.java
server/app/views/applicant/IneligibleBlockView.java
server/app/views/applicant/PreventDuplicateSubmissionView.java
server/app/views/applicant/TrustedIntermediaryDashboardView.java
server/conf/routes
server/test/controllers/HomeControllerTest.java
server/test/controllers/HomeControllerWithProfileTest.java
server/test/controllers/applicant/ApplicantProgramsControllerTest.java

Remove applicant id from URLs for index action

---

.github/pull_request_template.md
.github/release.yml

Add 'Enhancements' as a new section of the release notes
This PR is tagged as enhancement so we know it's working on the next release.

Add 'Enhancements' as a new section of the release notes

---

bin/create-release

Updating create-release script with note on how labels are managed

Updating create-release script with note on how labels are managed

---

server/app/filters/SessionIdFilter.java
server/test/filters/SessionIdFilterTest.java

Exclude `/playIndex` from `SessionIdFilter`.
This route gets hit as part of determining server health. Failure to exclude this route will cause an endless stream of `303` responses, preventing the server from ever properly answering the health check.

Exclude /playIndex from SessionIdFilter

---

server/test/controllers/HomeControllerTest.java

Add a unit test that routes a request to `/playIndex`. This route is used for server health checking.
This unit test can catch problems that would otherwise only be revealed upon deployment, when health checking is operative.

Add a unit test that hits the /playIndex route

---

server/app/repository/AccountRepository.java
server/app/repository/ProgramRepository.java

This is a followup to some of the PRs to refactor model classes with the Model suffix. 
#5961

Update a few more references to new Model classes

---

README.md

Changing link to new location for Seattle Staging builds.

Fix broken Seattle Staging Badge

---

.eslintignore
.prettierignore

Add .git folder to .eslintignore and .prettierignore so those tools don't scan that folder

Add .git folder to .eslintignore and .prettierignore

---

bin/build-browser-tests
bin/build-dev
bin/build-dev-oidc
bin/build-formatter
bin/build-localstack-env
bin/build-mock-web-services
bin/build-prod

Updating these flags to more verbose option for better readability
- `-f` :arrow_right: `--file`
- `-t` :arrow_right: `--tag`

Updating flags to more verbose option

---

browser-test/src/support/index.ts

Specify regex with slashes rather than quotes.

Specify regex with slashes rather than quotes

---

.github/ISSUE_TEMPLATE/oncall-rotation.md

Update release day to tuesday instead of wednesday

Update release day to Tuesday

---

server/app/filters/LoggingFilter.java

Log the redirect location, if present.
```
[info] loggingfilter - GET	/logout	65ms	302 -> http://localhost:9000/
[info] loggingfilter - GET	/	83ms	303 -> /programs
[info] loggingfilter - GET	/programs	131ms	200
```

Log redirect location, if applicable

---

browser-test/src/civiform_admin_program_statuses.test.ts
server/app/forms/admin/ProgramStatusesForm.java

Reverts civiform/civiform#6242
Related: #5000 
Reverting because of https://github.com/civiform/civiform/issues/5000#issuecomment-1875752440

Revert "Added character length limit of program status"

---

.github/ISSUE_TEMPLATE/oncall-rotation.md

Update the year in the oncall issue template

Update the year in the oncall issue template

---

.github/ISSUE_TEMPLATE/oncall-rotation.md

Update release date in oncall issue template from Wednesday to Tuesday

Update release date in oncall issue template

---

.github/workflows/tests.yaml

When I added the run attempt number I forgot were are in the matrix so it still fails with the http code 409. This should now make it a unique value.

Further Fine Tune Artifact Numbering

---

server/app/controllers/applicant/ApplicantProgramBlocksController.java
server/app/services/applicant/ApplicantService.java
server/app/services/applicant/ReadOnlyApplicantProgramService.java
server/app/services/applicant/ReadOnlyApplicantProgramServiceImpl.java
server/test/services/applicant/ReadOnlyApplicantProgramServiceImplTest.java

Renamed getBlock(String blockId) to getActiveBlock(String blockId) since it's only getting active block via its blockId. Making this refactor to prepare for a new function getHiddenBlock() for feature - adding hidden questions to pdf.
Part of #6288

refactoring method getBlock()

---

bin/build-browser-tests
bin/build-dev
bin/build-dev-oidc
bin/build-formatter
bin/build-localstack-env
bin/build-mock-web-services
bin/build-prod

Despite my previous comments, you can in fact push to an alternate registry.

Updating comments on the docker image build scripts

---

test-support/prod-simulator-compose.yml
test-support/unit-test-docker-compose.yml

Seems renovatebot misses these two files.

Updating postgres version in test compose files

---

server/app/controllers/FileController.java
server/app/services/cloud/ApplicantFileNameFormatter.java
server/test/services/cloud/ApplicantFileNameFormatterTest.java

Moves filekey calculation to related class and removes dead link

Cleanup for dead link

---

server/app/controllers/FileController.java

The comment above this method details that is was made a legacy call a year and a half ago. Seattle would be the only deployment affected. Adding this `warning` in order to see if there is anything really call it still.

Adding logging to monitor endpoint

---

server/conf/i18n/messages

This adds the context strings for all TI messages, including the context strings that @melanie-exygy added to Transifex
#5535

Add context strings for TI messages

---

.github/pull_request_template.md

We should make it clearer the steps to look out for when making / reviewing i18n updates.
Added to the PR template so it is more explicit. 

Update PR template to be more specific about i18n requirements

---

browser-test/src/applicant_application_index.test.ts
server/app/controllers/admin/AdminProgramImageController.java
server/app/views/admin/programs/ProgramImageView.java

Removes some TODOs for program card images that have been fixed or are no longer needed. I added comments to each change explaining why the TODO can be removed.
Related to #5676

[Program Card Images] Remove unneeded TODOs

---

mock-web-services/README.md

Add some directions for how to make changes to Mock Web Services and test them locally.

Add directions for testing Mock Web Services locally

---

server/app/services/program/ProgramService.java

In ProgramService, we should use the full program definition cache wherever possible. We create a function to use the cache if its available and if not sync the question data. We also remove the getQuestionCacheEnabled() check in the ProgramService file, since we check if it is enabled as part of the setFullProgramDefinitionCache method.
Fixes #6466

Utilize the full program definition cache in more places where its possible

---

server/app/views/dev/DatabaseSeedView.java

Adding a link to the oft forgotten dev icons page.

Add link to icons page

---

.github/workflows/tests.yaml
.github/workflows/tests_skip.yaml

Disabling Azure tests in the build until we are at a point of needing to fully support it.

Disable running azure tests

---

.github/ISSUE_TEMPLATE/feature_flag.md

It wasn't immediately obvious to me how to enable a feature flag in staging. This PR updates the feature flag issues template to link to an example PR about how to do it.

Update feature flag issue template with example PR for enabling in staging

---

server/conf/i18n/messages

Add context strings to two strings that were missing them.

Add context strings to recent translations

---

browser-test/.eslintrc.json
browser-test/package-lock.json
browser-test/package.json
formatter/eslintrc_base.json
formatter/package-lock.json
formatter/package.json

Adding in the [eslint playwright plugin](https://github.com/playwright-community/eslint-plugin-playwright). Turning off a number of rules for now until we're able to fix them.
Additional rules can be disabled if they cause issues until we have time to fix them.
https://github.com/playwright-community/eslint-plugin-playwright?tab=readme-ov-file#rules

Adding Eslint Playwright

---

bin/dev-show-trace-file

Adding initial script to download and run traces from branch artifacts

Adding initial script to download and run traces from branch artifacts

---

renovate.json

Group `@playwright/test` in renovate config

Group `@playwright/test` in renovate config

---

browser-test/.eslintrc.json

Disable the `playwright/valid-valid` lint error.

Disable the `playwright/valid-valid` lint error.

---

server/app/views/applicant/TrustedIntermediaryDashboardView.java

Fix the TI Dashboard Timeout. Swapping back to the full program definition option. It performs plenty fine. The shallow version of getting a program never loads for some reason. We can do further work later, but this will unblock.
Fixes #6813

Fix tidashboard timeout

---

mock-web-services/README.md
server/app/views/applicant/AddressCorrectionBlockView.java

Adding some documentation to `mock-web-services` and `AddressCorrectionBlockView` based on [the slack discussion](https://civiform.slack.com/archives/C01QKN2UNMA/p1709665362791919).

Add more documentation about address correction and service area validation

---

server/conf/i18n/messages.am
server/conf/i18n/messages.es-US
server/conf/i18n/messages.ko
server/conf/i18n/messages.lo
server/conf/i18n/messages.so
server/conf/i18n/messages.tl
server/conf/i18n/messages.vi
server/conf/i18n/messages.zh-TW

Reverts removal of translations from civiform/civiform#6785 and https://github.com/civiform/civiform/pull/6760/

Revert "Updates for file server/conf/i18n/messages"

---

renovate.json

Just updating deprecated renovate settings.
https://docs.renovatebot.com/release-notes-for-major-versions/#breaking-changes_1

Update deprecated renovate config settings

---

bin/localstack/wait
browser-test/src/support/index.ts
docker-compose.yml
localstack/localstack.Dockerfile

Updates localstack to the latest version
Closes #6135

Update localstack to v3.2.0

---

server/app/views/dev/DatabaseSeedView.java

Adds links to localstack SES/S3 on the dev tools page. UI formatting.

Adding links to localstack

---

server/app/repository/ProgramRepository.java

Remove unnecessary fetches from application export query
Details:
- As long as we're only accessing the id of the related entity (eg `applicationModel.getProgram().id`) we don't need to eagerly fetch the whole related entity.
- We only need the program id and applicant ids for export, so we don't need to eagerly fetch them.
- I confirmed this didn't induce a n+1 query situation. If instead we fetched the program id through the ProgramDefinition (eg `applicationModel.getProgram().getProgramDefinition().id()`) it does.
n/a
- [n/a] Extended the README / documentation, if …

Remove unnecessary fetches from application export query

---

browser-test/playwright.config.ts
browser-test/src/header.test.ts
browser-test/src/support/civiform_fixtures.ts

Extends Playwright test with custom fixtures and updates the header tests to use them.

Updating header tests to use custom civiform fixtures

---

formatter/fmt
server/app/views/applicant/ApplicantBaseFragment.html
server/app/views/applicant/ApplicantProgramBlockEditTemplate.html
server/app/views/applicant/ApplicantQuestionFragment.html
server/app/views/questiontypes/CheckboxQuestionFragment.html
server/app/views/questiontypes/CurrencyQuestionFragment.html
server/app/views/questiontypes/IdQuestionFragment.html
server/app/views/questiontypes/NameQuestionFragment.html
server/app/views/questiontypes/NumberQuestionFragment.html
server/app/views/questiontypes/QuestionBaseFragment.html
server/app/views/questiontypes/RadioButtonQuestionFragment.html
server/app/views/questiontypes/StaticTextQuestionFragment.html
server/app/views/questiontypes/TextQuestionFragment.html

bin/fmt wasn't running on any html files, so the files weren't being linted. This runs prettier over modified HTML files. I also ran it once on existing html files so that we're starting from a consistent state

Update bin/fmt to run on html files

---

server/app/services/openapi/v2/ApiKeyLocation.java
server/app/services/openapi/v2/Contact.java
server/app/services/openapi/v2/Definition.java
server/app/services/openapi/v2/DefinitionType.java
server/app/services/openapi/v2/Format.java
server/app/services/openapi/v2/Header.java
server/app/services/openapi/v2/HttpStatusCode.java
server/app/services/openapi/v2/In.java
server/app/services/openapi/v2/Info.java
server/app/services/openapi/v2/MimeType.java
server/app/services/openapi/v2/Operation.java
server/app/services/openapi/v2/OperationType.java
server/app/services/openapi/v2/Parameter.java
server/app/services/openapi/v2/PathItem.java
server/app/services/openapi/v2/Paths.java
server/app/services/openapi/v2/Response.java
server/app/services/openapi/v2/Scheme.java
server/app/services/openapi/v2/SecurityDefinition.java
server/app/services/openapi/v2/SecurityRequirement.java
server/app/services/openapi/v2/SecurityType.java
server/app/services/openapi/v2/Swagger.java
server/app/services/openapi/v2/Tag.java

[Swagger v2 specification](https://swagger.io/specification/v2) model. Not an exhaustive implementation; only the parts we'll be using.
Related to #5358

Adding Swagger v2 models

---

server/app/services/openapi/v2/serializers/ContactSerializer.java
server/app/services/openapi/v2/serializers/DefinitionSerializer.java
server/app/services/openapi/v2/serializers/HeaderSerializer.java
server/app/services/openapi/v2/serializers/InfoSerializer.java
server/app/services/openapi/v2/serializers/OpenApiSchemaSerializer.java
server/app/services/openapi/v2/serializers/OperationSerializer.java
server/app/services/openapi/v2/serializers/ParameterSerializer.java
server/app/services/openapi/v2/serializers/PathsSerializer.java
server/app/services/openapi/v2/serializers/ResponseSerializer.java
server/app/services/openapi/v2/serializers/SecurityDefinitionSerializer.java
server/app/services/openapi/v2/serializers/SecurityRequirementSerializer.java
server/app/services/openapi/v2/serializers/Swagger2YamlMapper.java
server/app/services/openapi/v2/serializers/SwaggerSerializer.java
server/app/services/openapi/v2/serializers/TagSerializer.java
server/build.sbt
server/test/services/openapi/v2/serializers/ContactSerializerTest.java
server/test/services/openapi/v2/serializers/DefinitionSerializerTest.java
server/test/services/openapi/v2/serializers/HeaderSerializerTest.java
server/test/services/openapi/v2/serializers/InfoSerializerTest.java
server/test/services/openapi/v2/serializers/OpenApiSerializationAsserter.java
server/test/services/openapi/v2/serializers/OperationSerializerTest.java
server/test/services/openapi/v2/serializers/ParameterSerializerTest.java
server/test/services/openapi/v2/serializers/PathsSerializerTest.java
server/test/services/openapi/v2/serializers/ResponseSerializerTest.java
server/test/services/openapi/v2/serializers/SecurityDefinitionSerializerTest.java
server/test/services/openapi/v2/serializers/SecurityRequirementSerializerTest.java
server/test/services/openapi/v2/serializers/SwaggerSerializerTest.java
server/test/services/openapi/v2/serializers/TagSerializerTest.java
server/test/services/openapi/v2/serializers/TestObjectContainer.java
server/test/services/openapi/v2/serializers/TestObjectContainerSerializer.java

Adding serializer classes for their related models and tests.
Related to https://github.com/civiform/civiform/issues/5358

Adding swagger v2 model serializers and tests

---

server/app/auth/CiviFormProfile.java
server/app/auth/ProfileFactory.java
server/app/controllers/FileController.java
server/app/controllers/HomeController.java
server/app/controllers/ProfileController.java
server/app/controllers/admin/AdminQuestionController.java
server/app/controllers/api/ProgramApplicationsApiController.java
server/app/controllers/applicant/ApplicantInformationController.java
server/app/controllers/applicant/ApplicantProgramBlocksController.java
server/app/controllers/applicant/ApplicantProgramReviewController.java
server/app/controllers/applicant/ApplicantProgramsController.java
server/app/controllers/applicant/ProgramSlugHandler.java
server/app/controllers/applicant/UpsellController.java
server/app/services/applicant/ApplicantService.java
server/app/services/applicant/ServiceAreaUpdateResolver.java
server/app/services/program/ProgramService.java
server/test/controllers/admin/AdminApplicationControllerTest.java

Renames httpExecutionContext variable names to classLoaderExecutionContext. This is the new class name and not changing it has made keeping the Play 2.9 branch in sync with changes to main more difficult. I should have done this ages ago.

Prep step for play 2.9

---

browser-test/src/auth.test.ts
browser-test/src/error_pages.test.ts
browser-test/src/program_deep_link.test.ts
browser-test/src/security.test.ts

Migrates tests to using fixtures, adding steps, and a bit of cleanup.
Recommend ignoring whitespace in the diff

Migrating to fixtures 2

---

.github/ISSUE_TEMPLATE/feature_flag.md

Update feature flag template with direct link to tracking spreadsheet

Update feature flag template with direct link to tracking spreadsheet

---

.devcontainer/devcontainer.json

Reverts civiform/civiform#7141

Revert "Remove terraform from codespace dependencies"

---

server/app/views/admin/programs/ProgramFormBuilder.java

Refactor code to move the last radio button to the same group as the other options.
Relates to #6995

[Disabled Programs] refactor radio button

---

.github/labeler.yml

Any changes to this folder can be ignored by releases

Ignore devcontainer dir

---

browser-test/src/applicant/application_address_correction.test.ts

Use test steps per https://github.com/civiform/civiform/wiki/Playwright-Feature-Migration-Guide#steps

Convert application_address_correction.test.ts to use test steps

---

.devcontainer/devcontainer.json

Add a postCreateCommand to devcontainer.json to automatically enable git completion in codespaces.

Automatically enable git completion in codespaces

---

server/app/controllers/admin/AdminApiKeysController.java
server/app/views/admin/apikeys/ApiKeyCredentialsView.java

Fix package for ApiKeyCredentialsView

Fix package for ApiKeyCredentialsView

---

browser-test/src/trusted_intermediary.test.ts

Migrate TI tests to use fixtures

Migrate TI Tests to use Playwright Fixtures

---

.devcontainer/devcontainer.json

This adds the remaining ports to the devcontainer, as well as descriptions for each of them.
https://github.com/civiform/civiform/issues/6999

Add all ports to be forwarded in the devcontainer

---

.devcontainer/devcontainer.json

Developers using codespaces were running into issues and slowness. This increase seemed to help, so we should change the default. 

Increase size of codespaces by default

---

server/app/controllers/admin/AdminProgramBlockPredicatesController.java
server/app/views/admin/programs/ProgramPredicatesEditView.java

Rename ProgramPredicatesEditViewV2 to ProgramPredicatesEditView

Rename ProgramPredicatesEditViewV2 to ProgramPredicatesEditView

---

server/app/services/settings/SettingsManifest.java
server/conf/env-var-docs.json
server/conf/helper/esri.conf

Add Setting for ArcGis Online API Token

Add Setting for ArcGis Online API Token

---

.github/renovate.json5
test-support/prod-simulator-compose.yml
test-support/unit-test-docker-compose.yml

Setting the new pg version on test compose files and allowing renovate to update to v16

Additional pg updates

---

server/app/services/question/types/QuestionDefinitionConfig.java

The step builder pattern is very confusing if you haven't seen it before, so add a comment to help explain.

Add a comment about QuestionDefinitionConfig.Builder being a step builder

---

browser-test/src/admin/admin_predicates.test.ts
browser-test/src/admin/admin_program_admins.test.ts
browser-test/src/admin/admin_program_creation.test.ts
browser-test/src/admin/admin_program_image.test.ts
browser-test/src/admin/admin_program_translation.test.ts
browser-test/src/admin/admin_program_visibility.test.ts
browser-test/src/primary_applicant_info.test.ts
browser-test/src/question_delete.test.ts

Migrating more tests to use fixtures
To the reviewer, you should hide whitespace in the diff.

Migrating more tests to use fixtures

---

server/app/views/applicant/ApplicantBaseFragment.html
server/app/views/applicant/ApplicantProgramBlockEditTemplate.html
server/app/views/applicant/ApplicantProgramFileUploadBlockEditTemplate.html
server/app/views/applicant/ApplicantProgramSummaryTemplate.html
server/app/views/applicant/ApplicantQuestionFragment.html
server/app/views/applicant/ProgramIndexTemplate.html
server/app/views/components/ToastFragment.html
server/app/views/questiontypes/AddressQuestionFragment.html
server/app/views/questiontypes/CheckboxQuestionFragment.html
server/app/views/questiontypes/CurrencyQuestionFragment.html
server/app/views/questiontypes/DateQuestionFragment.html
server/app/views/questiontypes/DropdownQuestionFragment.html
server/app/views/questiontypes/EmailQuestionFragment.html
server/app/views/questiontypes/EnumeratorQuestionFragment.html
server/app/views/questiontypes/FileUploadQuestionFragment.html
server/app/views/questiontypes/IdQuestionFragment.html
server/app/views/questiontypes/NameQuestionFragment.html
server/app/views/questiontypes/NumberQuestionFragment.html
server/app/views/questiontypes/PhoneQuestionFragment.html
server/app/views/questiontypes/QuestionBaseFragment.html
server/app/views/questiontypes/RadioButtonQuestionFragment.html
server/app/views/questiontypes/TextQuestionFragment.html

Replaces standard html comments with thymeleaf block comments so the thymeleaf parser will remove them
Fixes #7385

replace html comments with thymeleaf comment blocks

---

.github/renovate.json5

Have renovate group guava dependencies

Have renovate group guava

---

server/app/views/admin/programs/ProgramPredicateConfigureView.java

By creating a bunch of Optionals (maybePredicateValue, maybeScalar, maybeOperator) based on the existence of the root Optional (maybeLeafNode), it obfuscates the reason that they are optional, and then required an unchecked .get() (for maybeScalar) and handling of an impossible Optional.empty case (for maybeOperator).

Fix poor optional handling in ProgramPredicateConfigureView

---

.github/ISSUE_TEMPLATE/oncall-rotation.md

This is to align with the docs change in https://github.com/civiform/docs/pull/433 and based on a conversation in the tech weekly

Update on call list to check needs triage for p0s and upgrade demo sites

---

server/app/assets/javascripts/admin_predicate_configuration.ts

Fix typos in admin_predicate_configuration.ts

Fix typos in admin_predicate_configuration.ts

---

formatter/eslintrc_base.json
server/app/assets/javascripts/util.ts
server/app/services/settings/SettingsManifest.java
server/conf/env-var-docs.json
server/conf/i18n/messages
server/conf/i18n/messages.am
server/conf/i18n/messages.es-US
server/conf/i18n/messages.ko
server/conf/i18n/messages.lo
server/conf/i18n/messages.so
server/conf/i18n/messages.tl
server/conf/i18n/messages.vi
server/conf/i18n/messages.zh-TW

Fix contribution-guide links

---

server/app/views/admin/programs/ProgramPredicateConfigureView.java

Formatting predicate values based on the supported right hand types for the given operator makes two assumptions:
1. That each operator supports at most one right hand type for a given scalar type. This isn't true for AGE_BETWEEN, which supports both LONG and DOUBLE for the scalar type DATE. So the existing logic `operator.getRightHandTypes().contains(OperatorRightHandType.LONG)` for scalar type DATE obfuscated the fact that the value might be LONG or DOUBLE and only happened to work correctly by chance.
2. That an operator that supports a given right hand type supports it for the scalar where it's being checked. This assumption is probably okay today, but it opens a vector for bugs. For example, Operator LESS_THAN could support LONG for LONG scalar types and DATE for DATE scalars (today …

Refactor ProgramPredicateConfigureView.formatPredicateValue

---

server/app/assets/javascripts/admin_predicate_configuration.ts

* Remove unnecessary `Array.from`s
* Change ? to ! because #predicate-config-value-row-container should always exist and is an error if it doesn't, rather than failing silently
* Condition the missing value logic on whether the input is a checkbox type, rather than whether there is more than one input
* Remove unnecessary early returns that are barely optimizing anything and add complexity
* Re-work the logic to show the error message to flow more naturally
In addition to being cleaner this enables #6109 where we will have more than one non-checkbox input box.

Refactor validateSubmit in admin_predicate_configuration.ts

---

server/app/services/program/predicate/PredicateGenerator.java

Refactor PredicateGenerator form key parsing:
* Combine the logic shared between the single-value and multi-value matchers so it's not repeated
* Move the address question validation outside the value type conditional, because while service area is always a single value today, there's no technical reason it has to be (i.e. it could support a multi-select operator)
* Split getScalarAndOperator into separate methods because the two parts are not interdependent
* Inline getGroupIdAndQuestionId because again the two parts are not interdependent, and the extra layer of indirection detracts from readability

Refactor PredicateGenerator form key parsing

---

server/app/views/admin/programs/ProgramPredicateConfigureView.java

Combine duplicate conditional branches based on the presence of the Optional by constructing a Map that may or may not be empty.
Also change columnNumber counter to start at 0 to avoid confusion.

Refactor ProgramPredicateConfigureView.renderQuestionHeaders

---

browser-test/src/applicant/application_review.test.ts

Disable test step that fails intermittently.
For more details see: https://github.com/civiform/civiform/issues/7554

Disable new test step

---

browser-test/src/setup/global-setup.ts
browser-test/src/support/index.ts

Removes unused methods and code.

Removing obsolete browser test code

---

server/test/conf/MessagesTest.java

Parse the messages files as UTF-8.
Previously, in the messages tests they were parsed as the default ISO-8859-1 encoding, which did not include all international characters.
n/a
Fixes #7568

Add UTF8 support to messages tests

---

browser-test/src/applicant/application_review.test.ts

Fix test due to time zone issue

---

browser-test/src/admin/admin_program_migration.test.ts
browser-test/src/admin/admin_question_references.test.ts
browser-test/src/applicant/navigation/application_navigation_buttons.test.ts
browser-test/src/applicant/navigation/application_navigation_flow.test.ts
browser-test/src/support/admin_programs.ts

Update addProgramBlockUsingSpec BlockSpec instead of just QuestionSpec

Update addProgramBlockUsingSpec in admin_programs.ts to use BlockSpec

---

browser-test/src/support/admin_programs.ts

has-text matches a substring, so it would match the first question that is prefixed with the desired question name. It's much cleaner to use the data attribute which has the exact question name.

Fix AdminPrograms.addQuestionFromQuestionBank test helper

---

server/app/services/settings/SettingsManifest.java
server/conf/application.dev-browser-tests.conf
server/conf/application.dev.conf
server/conf/env-var-docs.json
server/conf/helper/feature-flags.conf

Creating a new feature flag to guard user-facing aspects of the Program Category Filtering feature while it is under development.  This is the first step for #7610.  The name of the flag is "PROGRAM_FILTERING_ENABLED".  It is for use while the filtering feature is under development and will be removed once the feature is released in production.
Creating a new feature flag to guard user-facing aspects of the Program Category Filtering feature while it is under development.  The name of the flag is "PROGRAM_FILTERING_ENABLED".

Creating the PROGRAM_FILTERING feature flag

---

browser-test/src/reporters/file_placement_reporter.ts

When a browser test fails, but has no related snapshots, there's a error because it's still trying to move test image files around. This handles that case.

Handle error when no images are present in failed test

---

browser-test/src/applicant/questions/currency.test.ts

Move northstar tag up to describe

Move northstar tag in currency test

---

browser-test/src/applicant/applicant_application_index.test.ts
server/app/assets/javascripts/applicant_entry_point.ts
server/app/assets/javascripts/north_star_modal.ts
server/app/views/applicant/AddressCorrectionBlockTemplate.html
server/app/views/applicant/ApplicantProgramBlockEditTemplate.html
server/app/views/applicant/ApplicantProgramFileUploadBlockEditTemplate.html
server/app/views/applicant/ApplicantProgramSummaryTemplate.html
server/app/views/applicant/ApplicantUpsellTemplate.html
server/app/views/applicant/ModalFragment.html

This adds some typescript logic to only show the login modal dialog once per session. It lives separately from the pre-northstar modal typescript logic because it operates differently.
USWDS has javascript that adds event handlers that handle the opening and closing of the dialog already, so this logic:
1) on load, check if dialog has already been seen (via localstorage), and if so, update the href of the anchor tag that launched the dialog to go straight to the bypass URL
2) when the modal dialog is launched, update localstorage and then update buttons that link to that dialog
There is a bit of weirdness because USWDS makes changes/adds event listeners on load, so merely changing the href of the anchor element isn't enough. Instead, we need to make a new <a> tag and replace the old one …

Only show login dialogs once per session

---

browser-test/src/support/admin_programs.ts
browser-test/src/support/index.ts

Clean up some spots to use locators. Add some options for performance. Prep for a new test suite I have coming.

Clean up test helpers

---

server/app/services/settings/SettingsManifest.java
server/conf/env-var-docs.json
server/conf/helper/feature-flags.conf

Add feature flag for multiple uploads. This is for Issue #6961.

Add feature flag for multiple uploads

---

server/test/services/applicant/question/AddressQuestionTest.java
server/test/services/applicant/question/ApplicantQuestionTest.java
server/test/services/applicant/question/CurrencyQuestionTest.java
server/test/services/applicant/question/DateQuestionTest.java
server/test/services/applicant/question/EmailQuestionTest.java
server/test/services/applicant/question/EnumeratorQuestionTest.java
server/test/services/applicant/question/FileUploadQuestionTest.java
server/test/services/applicant/question/IdQuestionTest.java
server/test/services/applicant/question/MultiSelectQuestionTest.java
server/test/services/applicant/question/NameQuestionTest.java
server/test/services/applicant/question/NumberQuestionTest.java
server/test/services/applicant/question/PhoneQuestionTest.java
server/test/services/applicant/question/SingleSelectQuestionTest.java
server/test/services/applicant/question/StaticContentQuestionTest.java
server/test/services/applicant/question/TextQuestionTest.java

Use AssertJ's isEmpty rather than asserting Map.isEmpty is true

Use AssertJ's isEmpty rather than asserting Map.isEmpty is true

---

server/app/controllers/applicant/ApplicantProgramsController.java
server/app/views/applicant/NorthStarProgramIndexView.java
server/app/views/applicant/ProgramIndexTemplate.html
server/app/views/components/ToastFragment.html

Add toasts to the program index page
- alert
- session ended
Progress towards #7228

Create toasts for program index page

---

server/app/models/ApplicationStatusesModel.java
server/app/models/Models.java
server/app/repository/ApplicationStatusesRepository.java
server/test/repository/ApplicationStatusesRepositoryTest.java

Adding UpdateStatusDefinitions function in ApplicationsStatusRepository.
Fixes #7040

[Status Migration] - Adding UpdateStatusDefinitions function in ApplicationsStatusRepository 

---

server/test/controllers/applicant/ApplicantProgramBlocksControllerTest.java

There were a series of tests that seemed to copy and paste the same mistake, that being that they weren't testing the methods they intended. This fixes that.

Fix some tests to call the correct methods.

---

bin/vscode-setup

Update bin/vscode-setup for Java 17, so it generates a pom.xml with the correct language level.
Part of #4166

Update bin/vscode-setup for Java 17

---

server/app/models/CategoryModel.java
server/app/models/Models.java
server/app/models/ProgramModel.java
server/app/repository/CategoryRepository.java
server/test/models/CategoryModelTest.java
server/test/models/ProgramModelTest.java
server/test/repository/CategoryRepositoryTest.java

Setting up the data model and repository classes for program categories.  This is foundational work without any user-facing changes.  It is part of the "Allow residents and TIs to filter all available programs based on key criteria" epic.  [TDD](https://docs.google.com/document/d/1hNL6r1JdauL5xjGRIw1dlDD3m81h9g0vUSiqlXOGDCs/edit#heading=h.y8f0f3g5k38q)
Fixes #7691

Setting up the data model and repository classes for program categories

---

.github/workflows/regression_test.yaml

This creates the workflow to integrate with latency lingo. This is a first step to create the workflow - we'll update it to use the jmeter action as a follow up. It also tests uses the general landing page. We'll update the test that's used as a follow up
https://github.com/civiform/civiform/issues/7800

Add a performance regression testing workflow

---

server/app/auth/ProfileUtils.java
server/app/controllers/CiviFormController.java
server/test/controllers/WithMockedProfiles.java

Just moving the function contents from source class to destination class. Will be need to call this later elsewhere.
Related to #5541

Moving function logic from CiviFormController to ProfileUtils

---

server/app/views/questiontypes/CheckboxQuestionFragment.html
server/app/views/questiontypes/QuestionBaseFragment.html
server/app/views/questiontypes/RadioButtonQuestionFragment.html

Classes are necessary for updating content on the question preview page in real-time.
This PR is part of issue https://github.com/civiform/civiform/issues/7490.
The full PR is #7835. It is being split into smaller pieces for easier review.
n/a
n/a
None

Add CiviForm classes to some HTML elements

---

server/app/forms/FileUploadQuestionForm.java
server/app/forms/IdQuestionForm.java
server/app/forms/MultiOptionQuestionForm.java
server/app/forms/NumberQuestionForm.java
server/app/forms/TextQuestionForm.java

Use ternary operator to assign min/max fields in QuestionForms

Use ternary operator to assign min/max fields in QuestionForms

---

server/test/services/program/ProgramServiceTest.java

Fixing calls to deprecated methods

Fixing calls to deprecated methods

---

browser-test/src/reporters/file_placement_reporter.ts
browser-test/src/support/index.ts

Using soft assertions on the screenshots will allow for all of the desktop, mobile, and medium sized screenshots to run together as a group for a single call. This will cut out the need to keep re-running in CI to get more images.
Everything else is still normal/hard asserts so if you have multiple different calls to take screenshots it will still end the test at the first screenshot failure.

Use soft asserts on screenshots

---

.github/ISSUE_TEMPLATE/oncall-rotation.md

Updated list to include links to PRs from renovate for different repos.

Add links to other repos needing to be checked by renovate

---

Dockerfile
browser-test/playwright.Dockerfile
formatter/formatter.Dockerfile
prod.Dockerfile

These recently started showing as warnings when building the Docker images.

Fixing Dockerfile warnings

---

server/test/services/export/AbstractExporterTest.java

Alphabetize FakeApplicationFiller test methods
n/a
Part of #5257

Alphabetize FakeApplicationFiller test methods

---

.github/ISSUE_TEMPLATE/translations_rotation.md

Update translations ticket template year

Update template date

---

server/app/services/export/QuestionJsonPresenter.java

Alphabetize QuestionJsonPresenter
n/a
Part of #6805

Alphabetize QuestionJsonPresenter

---

browser-test/src/applicant/application_version_fast_forward.test.ts
server/app/controllers/applicant/ApplicantProgramsController.java
server/app/controllers/applicant/ProgramSlugHandler.java
server/app/controllers/applicant/UpsellController.java
server/app/services/applicant/ApplicantService.java
server/test/controllers/applicant/ProgramSlugHandlerTest.java
server/test/services/applicant/ApplicantServiceTest.java

The main PR with the final fast-forward changes was getting busy having this added together. Plumb in changes to use the flag here to make it easier to review.

Plumb in changes for feature flag

---

server/test/support/FakeRequestBuilderTest.java

Fix FakeRequestBuilderTest package to match the package of FakeRequestBuilder which was updated in #8050

Fix FakeRequestBuilderTest package

---

server/app/services/export/CsvExporter.java
server/app/services/export/CsvExporterService.java

[Bug Fix] Pulling admin not from cached program definition 
[Bug Fix] Pulling admin not from cached program definition 
Fixes #8081

[Bug Fix] Pulling admin not from cached program definition 

---

server/test/controllers/applicant/ApplicantProgramReviewControllerTest.java
server/test/controllers/applicant/ProgramSlugHandlerTest.java
server/test/services/applicant/ApplicantServiceFastForwardEnabledTest.java

A change occurred right before my previous merge to main. Fixing some breakage.

Fixing merge issue

---

server/test/controllers/admin/AdminProgramBlocksControllerTest.java
server/test/controllers/admin/AdminProgramControllerTest.java
server/test/controllers/admin/AdminQuestionControllerTest.java
server/test/controllers/applicant/ApplicantProgramsControllerTest.java
server/test/controllers/applicant/ProgramSlugHandlerTest.java
server/test/controllers/applicant/UpsellControllerTest.java
server/test/controllers/ti/TrustedIntermediaryControllerTest.java

Replace FakeRequestBuilder.fakeRequestBuilder().build() with FakeRequestBuilder.fakeRequest() for brevity.
This supports https://github.com/civiform/civiform/issues/8046.

Replace fakeRequestBuilder().build() with fakeRequest()

---

server/app/services/settings/SettingsManifest.java
server/conf/env-var-docs.json
server/conf/helper/feature-flags.conf

Adding feature flag for enabling name suffix dropdown field
Fixes #8118

[Name Suffix] add feature flag for enabling name suffix dropdown field

---

formatter/fmt

Copied from #8187 since I messed that PR up. Please comment if I should add the CSS bit back in.
n/a
n/a
n/a

Enable autoformatting for SCSS files

---

server/conf/logback.xml

Adding sql to logs

---

server/app/views/CspUtil.java
server/app/views/HtmlBundle.java
server/app/views/admin/programs/ProgramImageView.java
server/app/views/applicant/ApplicantFileUploadRenderer.java
server/app/views/fileupload/FileUploadViewStrategy.java
server/test/views/BaseHtmlLayoutTest.java
server/test/views/CspUtilTest.java
server/test/views/HtmlBundleTest.java

Add the CSP nonce to all script tags so that the browser knows they are approved to load. This is for #7574.

Add CSP nonce to j2html script tags

---

.github/ISSUE_TEMPLATE/feature_flag.md

Update the feature flag issue template to match changes in the [feature flag wiki](https://github.com/civiform/civiform/wiki/Feature-Flags) for #8169.
Fixes #8169

Update feature flag issue template

---

.github/workflows/scan_for_secrets.yaml

Disabled daily runs until I can investigate the repeated failures.

Disable scan_for_secrets.yaml

---

server/conf/evolutions/default/72.sql

Adding a column `suffix` to applicant table. More details see [design doc](https://docs.google.com/document/d/1g46P_NbLAyhTgTY68NkMjHKidejWrTaqtkSMyH4IIrk/edit#heading=h.ejzgy1onfx7q).
Fixes #8167

[Suffix] Add suffix as a column to applicants table

---

server/app/auth/CiviFormProfile.java

Adding more detailed info to error message

Adding better error message

---

server/app/services/export/PdfExporter.java
server/test/services/export/AbstractExporterTest.java
server/test/services/export/PdfExporterTest.java

Add multiple file upload answers to the PdfExporter.

[Multiple File Upload] PDF export for multiple file uploads

---

server/app/services/MessageKey.java
server/conf/i18n/messages

Prepare strings for "application submitted" page
n/a
n/a
Part of #7683

Prepare strings for "application submitted" page

---

server/app/repository/AccountRepository.java
server/test/repository/AccountRepositoryTest.java

Alphabetical sorting of the TI organization list on load, A - Z, based on the Name of the organization.
Alphabetical sorting of the TI organization list load, A - Z, based on the Name of the organization.
Fixes #7570;

Added sorting on load for Ti Groups

---

server/test/services/export/AbstractExporterTest.java
server/test/services/export/JsonExporterServiceTest.java

Adds tests for application metadata in the JSON export.
Also
- Adds a method to the `FakeApplicationBuilder` that sets program statuses
It'll be easier to review with the whitespace changes hidden.
Fixes #5257

Add metadata tests for JSON export

---

browser-test/src/support/index.ts

This fixes the issues with the prober tests, which aren't working because there is a hidden continue button that's getting selected. 
@gwendolyngoetz THANK YOU for figuring this out!! (I did nothing here but put in the solution Gwen found)

Fix prober test

---

server/app/annotations/BindingAnnotations.java
server/app/durablejobs/AbstractDurableJobRunner.java
server/app/durablejobs/AbstractJobScheduler.java
server/app/durablejobs/DurableJobRegistry.java
server/app/durablejobs/RecurringDurableJobRunner.java
server/app/durablejobs/RecurringJobScheduler.java
server/app/modules/DurableJobModule.java
server/app/repository/PersistedDurableJobRepository.java
server/test/durablejobs/DurableJobRegistryTest.java
server/test/durablejobs/RecurringDurableJobRunnerTest.java
server/test/durablejobs/RecurringJobSchedulerTest.java
server/test/repository/PersistedDurableJobRepositoryTest.java

Prepare the existing job runner to handle running the new job types. Move some existing classes into abstract base classes and the current job runners unique needs are handling in a subclass.

Prepare for multiple job types

---

server/app/annotations/BindingAnnotations.java
server/app/durablejobs/AbstractJobScheduler.java
server/app/durablejobs/DurableJobRegistry.java
server/app/durablejobs/JobExecutionTimeResolver.java
server/app/durablejobs/RecurringJobExecutionTimeResolvers.java
server/app/durablejobs/RecurringJobScheduler.java
server/app/durablejobs/StartupDurableJobRunner.java
server/app/durablejobs/StartupJobScheduler.java
server/app/modules/DurableJobModule.java
server/app/repository/PersistedDurableJobRepository.java
server/test/durablejobs/JobExecutionTimeResolversTest.java
server/test/durablejobs/StartupDurableJobRunnerTest.java
server/test/durablejobs/StartupJobSchedulerTest.java
server/test/repository/PersistedDurableJobRepositoryTest.java

Adding Startup Job Runner

---

browser-test/src/applicant/questions/file.test.ts
server/app/assets/javascripts/file_upload.test.ts
server/app/assets/javascripts/file_upload.ts
server/app/views/applicant/ApplicantFileUploadRenderer.java

Appends "-2" to the end of a file if another file with exactly the same name is uploaded. (Or -"n+1" if it already ends in a -#).

[MultipleFileUpload] Avoid duplicate file names

---

server/app/repository/ProgramRepository.java
server/test/repository/ProgramRepositoryTest.java

The error with the JSON / API export presented (https://github.com/civiform/civiform/issues/8360) itself when a question was null and we think this happened when a question in the program definition cache was null specifically. This change will check if there are any null questions before setting the cache and only set it if no questions are null.
https://github.com/civiform/civiform/issues/8360

Add logging and don't set cache when question in the program definition is null

---

server/app/durablejobs/jobs/MigratePrimaryApplicantInfoJob.java
server/test/durablejobs/jobs/MigratePrimaryApplicantInfoJobTest.java

Modified PAI migration job so that it takes name suffix when migrating PAI, if suffix is provided.
[#8380](https://github.com/civiform/civiform/wiki/Durable-Jobs#testing-a-durable-job-during-development)
Fixes #8380

[Suffix] PAI migration job

---

.github/pull_request_template.md

This includes data migration updates and more clarity around the release notes section
https://docs.google.com/spreadsheets/d/1jXuOWl9TxssHh3A1AkmKi2gva9LRUhE0PQStJa-4yWs/edit?gid=586038575#gid=586038575

Update Pull Request template based on eng team discussion

---

server/app/services/question/types/QuestionDefinition.java

Memoize `getQuestionNameKey()` to reduce repeated regex computation.
Details:
- `getQuestionNameKey()`  is called 1000s of times (30063 when exporting a single application to Minimal Sample Program), and we currently recompile and re-run the regex to compute the name key from the immutable name every time we need it.
- Eventually, we should do #6597, but for now we just memoize this method on the QuestionDefinition.
- This saves ~2 seconds, or 10-20% of the export time, when exporting 2000 applications to Comprehensive Sample Program as JSON.
Progress toward #8147, stop gap for #6597

Memoize getQuestionNameKey() to reduce repeated regex computation

---

server/app/repository/ProgramRepository.java

The params were in the wrong place and the error was a little unclear. Updated for clarity.

Make null question error more clear

---

server/app/modules/ThymeleafModule.java
server/app/views/tags/CiviFormProcessorDialect.java
server/app/views/tags/IconElementTagProcessor.java
server/test/views/tags/IconElementTagProcessorTest.java

Custom icon tag. See javadoc for usage.

Custom Icon Tag

---

browser-test/src/applicant/navigation/northstar_application_navigation_buttons.test.ts
browser-test/src/support/applicant_questions.ts

Copy a basic test case for North Star navigation buttons on the block edit page.
This is part of #8065. Further PRs will implement the modal and add additional tests.

Branch application_navigation_buttons.test.ts for North Star

---

server/app/filters/CiviFormProfileFilter.java

Update CiviFormProfileFilter:
* Move the javadoc that explains when this filter applies to the shouldRedirect method, since that's where the logic is, so hopefully they stay in better sync
* Update that javadoc to reflect changes I made in #8445
* Rename shouldApplyThisFilter to shouldRedirect since redirecting is what the filter does
* Inline the profileIsMissing method because it's pretty readable and not reused
* Refactor the apply method to swap the order so it's more intuitive
* Add a TODO for #8504

Refactor CiviFormProfileFilter and update javadoc

---

browser-test/src/applicant/northstar_upsell.test.ts
server/app/controllers/applicant/UpsellController.java

On the "Application Submitted" page, do not show programs that the user has already applied to.
While testing this change, I noticed another possible bug (#8531). If the bug should be fixed, I will fix it in a follow-up PR. (My guess is that the common intake page should also use `unappliedAndPotentiallyEligible()`.)
1. Have at least 2 programs in the instance
1. Submit application to program A
1. Submit application to program B
1. [FIXED] On the "Application submitted" page, observe the related programs section. Program A may appear.
Fixes #8493

Fix showing programs the user already applied to

---

server/app/repository/VersionRepository.java

This is the publish individual program flow. Updating to be consistent with the publish all flow. This doesn't change anything, just adds consistency.
https://github.com/civiform/civiform/issues/8360

Don't read from cache in individual program publish flow

---

.github/pull_request_template.md

Adding screen reader testing to the PR template checklist, for resident-facing features only.

Add screen reader testing to the PR template checklist

---

bin/dev-pgadmin

Adding a step to removing temp/servers.json in pgadmin script
Fixes #8669

Adding a step to removing temp/servers.json in pgadmin script

---

test-support/test_oidc_provider.js

Update the dev oidc script to allow returning `phone_number` and `phone_number_verified` values if the `phone` scope is one of the additional scopes.
Related: #5461

Adding optional scope for phone on dev oidc

---

server/app/auth/oidc/CiviformOidcProfileCreator.java
server/app/repository/AccountRepository.java
server/test/repository/AccountRepositoryTest.java

* Rename updateIdTokens to addIdTokenAndPrune to more clearly describe what the method does
* Update the javadoc description

Rename AccountRepository method

---

formatter/fmt

Only include python files that have changed when calling yapf to format.

Only format changed python files

---

server/app/assets/stylesheets/styles.css
server/app/assets/stylesheets/uswds/_uswds-theme-custom-styles.scss
server/app/views/applicant/ProgramIndexView.java

Varying program filter chip HTML element ids so that we have valid HTML.
Fixes #8632

Vary program filter chip HTML element ids

---

server/app/auth/oidc/StandardClaimsAttributeNames.java
server/app/auth/oidc/applicant/ApplicantProfileCreator.java
server/app/auth/oidc/applicant/GenericApplicantProfileCreator.java
server/app/auth/oidc/applicant/GenericOidcClientProvider.java
server/app/auth/oidc/applicant/IdcsApplicantProfileCreator.java
server/app/auth/oidc/applicant/LoginGovClientProvider.java
server/test/auth/oidc/applicant/GenericApplicantProfileCreatorTest.java
server/test/auth/oidc/applicant/GenericOidcClientProviderTest.java

Simplify passing around claims attribute names. Clean up prep to add phone number.
Prep for #5461

Simplify passing around claims attribute names

---

server/app/services/export/CsvExporter.java
server/app/services/export/CsvExporterService.java

Don't check question visibility when building CSV export.
We stop this check for two reasons:
- Checking question visibility is expensive, and slows down the export process
- Only including a column if the applicants on this page happened to see the question makes the columns in the CSV unpredictable. Always including them keeps the CSV more stable.
For more see the [TDD](https://docs.google.com/document/d/1gmD0hTmys7sWKUSxxKVhYpZGgiY8FWsmCClk9Jzg4ng/edit?tab=t.0).
Fixes #8805

Include hidden questions in CSV export

---

server/app/controllers/applicant/ApplicantProgramsController.java
server/app/controllers/applicant/ApplicantRoutes.java
server/app/views/applicant/NorthStarApplicantIneligibleView.java
server/app/views/applicant/ProgramCardsSectionParamsFactory.java
server/conf/routes
server/test/controllers/applicant/ApplicantProgramsControllerTest.java
server/test/controllers/applicant/ApplicantRoutesTest.java

This view isn't referenced anymore, so can be removed. People may still have links to it (or for example, search engine indices might still point to it), so redirect if anyone hits the route.

Remove now-unused program info view

---

.github/pull_request_template.md

Updating PR checks for evolutions scripts

Updating PR checks for evolutions scripts

---

server/app/controllers/admin/AdminApplicationController.java
server/app/services/applicant/ReadOnlyApplicantProgramServiceImpl.java
server/app/services/export/CsvExporterService.java
server/test/services/applicant/ReadOnlyApplicantProgramServiceImplTest.java
server/test/services/export/CsvExporterServiceTest.java

Mirror data from the `file_key` column to the `file_urls` column in the CSV, to prepare for multi-file upload.
Also
- Updates the multiple file upload column format to be easier to parse. The new column format is a comma separated list, formatted like `civiform.mycity.gov/file1, civiform.mycity.gov/file2`
- Removes the `file_key` column when multiple file upload is enabled, to prevent anyone using a column with incomplete behavior. This mirrors the behavior in the JSON export.
To prepare for multi-file-upload, users of the CSV should transition to using the new `file_urls` column in the CSV. It currently mirrors the data in `file_key` but in the new format.
Once the MULTIPLE_FILE_UPLOAD_ENABLED flag is turned on, the `file_key` column will be removed, so users of the CSV should transition …

 Add data to file_urls column in CSV export

---

server/test/app/EvolutionsTest.java

Adding test to run all evolutions ups and downs.
Fixes #8883

Add unit test to exercise evolutions

---

server/conf/application.dev.conf
server/test/services/applicant/ApplicantServiceFastForwardEnabledTest.java
server/test/services/applicant/ApplicantServiceTest.java

Enable multi-file upload flag for dev

Enable multi-file upload on dev

---

server/app/auth/oidc/admin/GenericOidcProfileCreator.java

Debug won't appear in the deployment logs, so updating to info. See original PR https://github.com/civiform/civiform/pull/8964
https://github.com/civiform/civiform/issues/8965

Change log level for okta troubleshooting

---

.github/workflows/contributor_response.yml

This is a Github action that will respond automatically to comments made by community contributors, inviting them to consult our Wiki page.

Automatic response for community contributors

---

.github/workflows/contributor_response.yml

Fixing the contributor response

Contributor response fix

---

.github/workflows/contributor_response.yml

The workflow replied to codecov. Updating bot name.
https://github.com/civiform/civiform/pull/9010#issuecomment-2434199169

Update bot name

---

server/app/views/applicant/NorthStarAnswerData.java

Delete obsolete comment. We didn't need to do anything extra to support enumerator questions.
Fixes #8795

Delete obsolete comment

---

browser-test/src/applicant/questions/northstar_dropdown.test.ts
browser-test/src/applicant/questions/northstar_name.test.ts

Fix North Star tag.
When I added the tag to the dropdown test, running bin/fmt indents the rest of the file. This is the cause of the large diff.
Part of #8791

Fix North Star tag

---

server/app/durablejobs/AbstractDurableJobRunner.java
server/app/durablejobs/RecurringDurableJobRunner.java
server/app/durablejobs/StartupDurableJobRunner.java
server/app/modules/EmailSendModule.java
server/app/services/applicant/ApplicantService.java
server/app/services/applications/ProgramAdminApplicationService.java
server/app/services/email/EmailSendClient.java
server/app/services/email/EmailSendProvider.java
server/app/services/email/aws/SimpleEmail.java
server/conf/application.conf
server/conf/helper/cloud.conf
server/conf/helper/email.conf
server/test/durablejobs/RecurringDurableJobRunnerTest.java
server/test/durablejobs/StartupDurableJobRunnerTest.java
server/test/services/applicant/ApplicantServiceFastForwardEnabledTest.java
server/test/services/applicant/ApplicantServiceTest.java
server/test/services/applications/ProgramAdminApplicationServiceTest.java

This creates the new interface and module for email sending. Right now, it will always use the SimpleEmail class, but in the future, we'll have a graph api email sending class that will implement the same interface. This should not have any functional changes
Fixes https://github.com/civiform/civiform/issues/8970

Create EmailSendClient interface and associated module and refactor references to use

---

server/app/forms/admin/BlockEligibilityMessageForm.java
server/test/forms/admin/BlockEligibilityMessageFormTest.java

Build a form for eligibility message of a block.
Fixes #9083

[Eligibility Message] build eligibility msg form

---

server/conf/i18n/messages
server/test/conf/MessagesTest.java

This will add the same text in all the messages files, then I'll add the translations for all the category strings through transifex, which will then update the associated messages files. 
We're leaving the existing /categories/messages paths until all of the other messages files are complete and we update the parser to read from the normal messages files.
https://github.com/civiform/civiform/issues/9103

Add categories to main messages file

---

server/app/services/MessageKey.java
server/app/views/applicant/NavigationFragment.html
server/conf/i18n/messages

In this PR I'm updating the `aria-label` format, so it can be translated.  (th:aria-label instead of aria-label).
#7954

Issue #7954: Updating aria labels so they are translated accordingly

---

server/conf/i18n/messages

Add two additional categories to messages file
https://github.com/civiform/civiform/issues/8485

Add additional categories to messages file

---

server/app/services/MessageKey.java
server/conf/i18n/messages
server/conf/i18n/messages.am
server/conf/i18n/messages.ar
server/conf/i18n/messages.es-US
server/conf/i18n/messages.fr
server/conf/i18n/messages.ko
server/conf/i18n/messages.lo
server/conf/i18n/messages.so
server/conf/i18n/messages.tl
server/conf/i18n/messages.vi
server/conf/i18n/messages.zh-TW

Delete "View details" string. It was made obsolete in #9097.
Part of https://github.com/civiform/civiform/issues/8157

Delete "View details" string since it's no longer used

---

server/conf/evolutions/default/81.sql

This PR adds an evolution to create the two new columns needed for the program overview page - short description and application steps.
Fixes #9084;

[Program Overview] Add new columns for program overview page

---

.github/pull_request_template.md

Add note to our pull request template about updating the db documentation when you make a database update.

Add note about updating the db documentation to our pull request template

---

browser-test/src/applicant/northstar_applicant_application_statuses.test.ts

I accidentally clicked "Resolve conversation" before I uploaded the intended change. Then the PR auto-merged.
Context: https://github.com/civiform/civiform/pull/9140/files#r1829735079

Fix test name

---

server/app/durablejobs/DurableJobName.java
server/app/durablejobs/jobs/AddCategoryAndTranslationsJob.java
server/app/modules/DurableJobModule.java
server/app/repository/CategoryRepository.java
server/test/durablejobs/jobs/AddCategoryAndTranslationsTest.java
server/test/support/ResourceCreator.java

Category translations were initially designed to be similar to admin translation fields, where the localized strings are stored in the database. This is because the categories weren't supposed to change and we plan to make them admin defined in the future. This PR creates a background job to ensure the translations are updated, since there have been a couple of new categories added. I have it as a job that runs on each startup, so if future categories are added, we can handle them. We could also consider making this a one time job or keeping it a startup job but removing the run once all translations for categories are complete. 
We don't plan to create a rollback plan and a job to undo the data changes, since this isn't any data being used in the applicant flow, but let me know if you …

Create a durable job to ensure categories are up to date

---

browser-test/src/northstar_security.test.ts

Convert security browser tests to northstar.
> [!TIP]
> Hey Reviewer!!!
>
> The first commit contains a copy of the original file, this will allow you to diff the changes if you look at the second commit and not the full changes.
>
> Also ignore whitespace when diffing, to make it fast for you.
> ![image](https://github.com/user-attachments/assets/db20a1f1-b9f5-4ffd-ab04-7880767529b7)
Fixes #9079

Convert security browser tests to northstar

---

server/.sbtopts
server/build.sbt

Enables Java Assertions in dev and unit tests

Enable Java Assertions

---

browser-test/src/northstar_program_deep_link.test.ts

Convert deeplink tests for northstar
> [!TIP]
> Hey Reviewer!!!
>
> The first commit contains a copy of the original file, this will allow you to diff the changes if you look at the second commit and not the full changes.
>
> Also ignore whitespace when diffing, to make it fast for you.
> ![image](https://github.com/user-attachments/assets/db20a1f1-b9f5-4ffd-ab04-7880767529b7)
Fixes: #9078

Convert deeplink tests for northstar

---

browser-test/src/applicant/navigation/northstar_application_navigation_buttons.test.ts
browser-test/src/support/applicant_questions.ts
server/app/views/applicant/ModalFragment.html
server/app/views/applicant/QuestionSummaryFragment.html
server/app/views/questiontypes/IdQuestionFragment.html

Migrate application_navigation_buttons.test.ts to North Star.
The tests were copy/pasted from `navigation_buttons.test.ts`. I did not try and optimize the tests. I only adapted them to North Star (e.g. replace "clickNext()" with "clickContinue()")
To see the diffs, use an external diff tool to check the differences between this test file and [application_navigation_buttons.test.ts](https://github.com/civiform/civiform/blob/main/browser-test/src/applicant/navigation/application_navigation_buttons.test.ts)
Fixes #8896

Migrate application_navigation_buttons.test.ts to North Star

---

browser-test/src/applicant/northstar_application_previous_version.test.ts

Migrate application_previous_version.test.ts to North Star
Fixes #8900

Migrate previous version test to North Star

---

browser-test/playwright.config.ts

Staging had a timeout after lowering the time. Reverting for now. Will make it configurable later

Change playwright timeout back to 90s

---

server/app/controllers/FileController.java
server/app/controllers/admin/AdminApplicationController.java
server/app/services/applicant/AnswerData.java
server/app/services/applicant/ApplicantService.java
server/app/services/applicant/ReadOnlyApplicantProgramServiceImpl.java
server/app/services/applicant/question/Question.java
server/app/services/export/Column.java
server/app/services/export/CsvColumnFactory.java
server/app/services/export/CsvExporter.java
server/app/services/export/CsvExporterService.java
server/app/services/export/ExportFormatUtils.java
server/app/services/export/QuestionJsonPresenter.java
server/test/services/applicant/ReadOnlyApplicantProgramServiceImplTest.java
server/test/services/export/AbstractExporterTest.java
server/test/services/export/CsvExporterServiceTest.java
server/test/services/export/ExportFormatUtilsTest.java
server/test/services/export/JsonExporterServiceTest.java
server/test/services/export/PdfExporterTest.java

Further optimize CSV export by replacing generating `AnswerData` with a `CsvColumnFactory`.
Details:
- With a warm program definition cache, exporting 2000 applications, without eligibility, now takes 1-2 seconds on my local.
- Each `Column` contains a new `answerExtractor` field that's a function that takes a `Question` subclass and returns a `String` answer for insertion into a CSV.
- We remove `getSummaryData()` from `ReadOnlyApplicantProgramService` and the `summaryData` field from `AnswerData`, as they're no longer used.
- Tests in `CsvExporterServiceTest` are rewritten to use a similar format as the `JsonExporterService` tests.
Also:
- Moves lat/long, number, and file url formatting logic into a shared `ExportFormatUtils` class.
- Updates file urls in the CSV to use the newest …

Replace AnswerData with CsvColumnFactory for additional speed improvements in CSV export

---

.github/ISSUE_TEMPLATE/oncall-rotation.md

Update oncall issue with a step to let admin know when a release will be late.

Add step to oncall issue to update admins when a release will be late.

---

browser-test/package-lock.json
server/package-lock.json

Fix a dependency of a dependency that `npm audit` was warning about.

Update dependency with DDOS vulnerability

---

server/app/durablejobs/DurableJobName.java

Adding a link to the wiki on job naming

Adding link to job naming in the wiki

---

server/app/services/cloud/azure/AzurePublicStorage.java

Adds the storage client object that enables file uploads in Azure to the public blob container.

Enable public file uploads for Azure production deployments (Program Images)

---

browser-test/src/northstar_meta_tags.test.ts
server/app/views/NorthStarBaseView.java
server/app/views/applicant/ApplicantBaseFragment.html

Add robots, build-tag, and thanks meta tags to northstar base fragment
Note that this doesn't add tests for the robots tag. This is somewhat difficult to test, and it wasn't tested in the legacy frontend, so this is not a regression.
Fixes #9403

Add robots and build meta tags to northstar

---

server/app/services/openapi/OpenApiSchemaGenerator.java
server/app/services/openapi/OpenApiSchemaSettings.java
server/app/services/openapi/QuestionDefinitionNode.java
server/build.sbt
server/test/services/openapi/QuestionDefinitionNodeTest.java

Adding some foundational support for openapi and related openapi libraries 
Related to #5358, #5359

Adding foundational support for openapi

---

browser-test/src/admin/admin_bulk_update_statuses.test.ts
server/app/views/admin/programs/ProgramApplicationTableView.java

Adding browser tests for Bulk status update.
Adding browser tests for Bulk status update.
Fixes #9017

Bulk status browser tests

---

browser-test/src/admin/admin_application_statuses_bulkstatus.test.ts
browser-test/src/admin/admin_bulk_update_statuses.test.ts

Fix browser tests to make aws staging pass.

Fix browser tests to make aws staging pass

---

server/app/views/applicant/NavigationFragment.html

This is for security to prevent tab-nabbing
https://github.com/civiform/civiform/issues/9406

Add noopener noreferrer to northstar link

---

server/app/services/openapi/AbstractOpenApiSchemaGenerator.java
server/app/services/openapi/DefinitionType.java
server/app/services/openapi/Format.java
server/app/services/openapi/OpenApiSchemaGeneratorFactory.java
server/app/services/openapi/OpenApiVersion.java
server/app/services/openapi/v2/Swagger2SchemaGenerator.java
server/app/services/openapi/v3/OpenApi3SchemaGenerator.java
server/test/services/openapi/v3/OpenApi3SchemaGeneratorTest.java

Adding openapi 3.0.x output for programs
Related to https://github.com/civiform/civiform/issues/5358, https://github.com/civiform/civiform/issues/5359

Adding openapi 3.0.x

---

server/app/modules/CiviFormLogoutLogic.java

This is a small update to https://github.com/civiform/civiform/pull/9471 to update the params to be consistent with the parent class.

Fix params in logout logic class

---

server/app/services/applicant/AnswerData.java
server/app/services/applicant/Block.java
server/app/services/applicant/question/AbstractQuestion.java
server/app/services/applicant/question/AddressQuestion.java
server/app/services/applicant/question/ApplicantQuestion.java
server/app/services/applicant/question/CurrencyQuestion.java
server/app/services/applicant/question/DateQuestion.java
server/app/services/applicant/question/EmailQuestion.java
server/app/services/applicant/question/EnumeratorQuestion.java
server/app/services/applicant/question/FileUploadQuestion.java
server/app/services/applicant/question/IdQuestion.java
server/app/services/applicant/question/MultiSelectQuestion.java
server/app/services/applicant/question/NameQuestion.java
server/app/services/applicant/question/NullQuestion.java
server/app/services/applicant/question/NumberQuestion.java
server/app/services/applicant/question/PhoneQuestion.java
server/app/services/applicant/question/SingleSelectQuestion.java
server/app/services/applicant/question/StaticContentQuestion.java
server/app/services/applicant/question/TextQuestion.java
server/app/services/export/Column.java
server/app/services/export/QuestionJsonPresenter.java
server/app/services/export/QuestionJsonSampler.java
server/app/services/question/types/QuestionType.java

`Question` is an overloaded word in CiviForm and it's hard to know exactly what you're holding when working with it. Renaming it to `AbstractQuestion` makes it clear you'll need to convert it to a specific question type to do anything with it.
N/A it's just been bothering me.

rename Question to AbstractQuestion

---

browser-test/src/applicant/questions/file.test.ts
server/app/views/questiontypes/FileUploadQuestionFragment.html

For North Star mult-file upload questions, disables & greys out the file upload modal when the maximum number of files has been hit.
To test out, you'll need a question that has the maximum file setting on it. To do so:
1. Set MULTIPLE_FILE_UPLOAD_ENABLED to true in dev settings
2. Log in as civiform admin and add/edit a file upload question
3. Under "Question settings", set a maximum number of file uploads.
Fixes #9383

Disable file upload modal in North Star when maximum number of file uploads has been reached

---

bin/build-browser-tests
bin/build-dev
bin/build-dev-oidc
bin/build-formatter
bin/build-localstack-env
bin/build-mock-web-services
bin/build-prod
bin/sync-failed-browser-test-images
bin/vscode-setup

Fix typos in scripts

---

server/app/views/docs/SchemaView.java
server/conf/routes

Fixing asset path. This should find the paths now when the app is deployed.

Fixing asset path

---

server/app/views/docs/SchemaView.java
server/conf/routes

Another attempt to get the asset route correct.

Another attempt on the assets

---

server/app/controllers/LogoutAllSessionsController.java
server/app/filters/CiviFormProfileFilter.java
server/app/filters/NonUserRoutes.java
server/conf/routes
server/test/controllers/LogoutAllSessionsControllerTest.java

Remove this section if the title of the pull request can be used as the default release notes description. If more detail is needed to communicate to partners the scope of the PR's changes, use this release notes section (and remove this placeholder text).

Updates to use authorityId

---

server/app/assets/stylesheets/northstar/_uswds-theme.scss
server/app/views/applicant/NavigationFragment.html

Minor fixes replace tailwind classes with USWDS ones.
Fixes: #7951

Enable uswds colors. Fixes header link formatting. Fixes 'top content' color

---

server/app/views/applicant/AddressCorrectionBlockTemplate.html
server/app/views/applicant/ProgramFiltersFragment.html

Minor fixes replace tailwind classes with USWDS ones.

Remove border on category filters and from fieldset

---

server/app/assets/stylesheets/northstar/_uswds-theme-custom-styles.scss
server/app/views/applicant/ProgramCardsSectionFragment.html

Minor fixes replace tailwind classes with USWDS ones.

Fix category layout

---

server/app/services/openapi/v3/OpenApi3SchemaGenerator.java

Removing obsolete comment

---

browser-test/src/applicant/applicant_application_index.test.ts
server/app/views/applicant/ProgramCardsSectionParamsFactory.java

For submitted applications in North Star, update the URL to lead to the review page instead of the edit page for program cards.
Fixes part of https://github.com/civiform/civiform/issues/9389 ("1. Clicking edit on a program after you've submitted takes you to a program page, instead of the review page.")
1. Make sure north star is enabled
2. Go to program overview page, and fill out and submit an application.
3. Go back to home page and click "edit".
4. Verify you're taken to the edit page.
5. Fill out a few answers but don't submit, and go back to the home page.
6. Click "Edit" on your in-progress application.
7. Verify you're taken to the edit page for …

Go to the review page when clicking on submitted applications.

---

.github/ISSUE_TEMPLATE/oncall-rotation.md

Just updating the default year

Update default year

---

server/app/models/EligibilityDetermination.java

This PR creates an EligibilityDetermination enum in /models, with the values [ELIGIBLE, INELIGIBLE, NOT_COMPUTED, NO_ELIGIBILITY_CRITERIA].
Part of #8852

[Pre-compute eligibility]create eligibility determination enum

---

server/app/views/applicant/IneligibleBlockView.java

Fix line breaks and comment syntax checking

IneligibleBlockView - Formatting

---

server/app/views/applicant/NorthStarProgramOverviewView.java

Cleanup - NorthStarProgramOverviewView

---

browser-test/src/applicant/application_version_fast_forward.test.ts
browser-test/src/applicant/northstar_application_version_fast_forward.test.ts
browser-test/src/support/civiform_fixtures.ts
browser-test/src/support/index.ts
browser-test/src/support/seeding.ts
server/app/controllers/dev/DevToolsController.java
server/conf/routes

This will bypass clicking through the UI to clear database and directly call a new endpoint. The time savings will probably be less noticeable in dev, but should be helpful against deployed staging sites.

Small optimization clearing db

---

env-var-docs/parser-package/src/env_var_docs/settings_manifest.py
env-var-docs/parser-package/tests/settings_manifest_test.py
formatter/fmt
server/app/services/settings/SettingsManifest.java

This was using `ImmutableMap.of(...)` to build the map, but that has a limit of 10 items. Like Ariel, I want more, so I'm changing this to generate as a builder.

Updating env-var-docs to generate Maps larger than 10 items

---

server/app/controllers/applicant/ApplicantProgramReviewController.java
server/app/models/ApplicationModel.java
server/app/repository/ApplicationRepository.java
server/app/services/applicant/ApplicantService.java
server/test/models/ApplicationModelTest.java
server/test/repository/ApplicationRepositoryTest.java
server/test/services/applicant/ApplicantServiceFastForwardEnabledTest.java
server/test/services/applicant/ApplicantServiceTest.java

Add `eligibilityDetermination` as part of ApplicationModel. This PR computes eligibility determination when the application gets submitted.  The default value for `eligibilityDetermination` is `NOT_COMPUTED`. 
Create a program with eligibility criteria, apply to the program and either meet or not meet the eligibility criteria. Once submitting the application, go to `applications` table and look up the `eligibility_determination` column with the application id provided. You should see the expected result. 
Part of #8852

[Pre-compute eligibility]compute eligibility at submission

---

server/app/controllers/applicant/ApplicantProgramBlocksController.java

Fix to a catch block which wasn't returning the object it computed to return.

Add missing return to catch in ApplicantProgramBlocksController.renderErrorOrRedirectToRequestedPage 

---

server/conf/i18n/messages

Remove space in messages file

---

server/app/controllers/SessionController.java
server/app/filters/SessionTimeoutFilter.java
server/app/filters/SettingsFilter.java
server/app/filters/ValidAccountFilter.java
server/app/services/settings/SettingsManifest.java
server/app/views/HtmlBundle.java
server/app/views/ViewUtils.java
server/conf/application.conf
server/conf/env-var-docs.json
server/test/controllers/SessionControllerTest.java
server/test/filters/SessionTimeoutFilterTest.java
server/test/filters/ValidAccountFilterTest.java
server/test/views/HtmlBundleTest.java
server/test/views/ViewUtilsTest.java

USWDS modals will be used to display the session timeout warnings(Since Modal.java is marked deprecated). This change adds attributes on modal html elements so that we can use event delegation when handling events. Also added support for adding USWDS modal in HtmlBundle. We are also marking session timeout enabled as admin writeable which simplify browser tests.

[SessionTimeout][part4]Prepare USWDS modal rendering for session timeout warnings

---

.github/workflows/build_push_ci.yaml
.github/workflows/format.yaml

Disabling tj-actions in github actions

Disabling tj-actions

---

server/app/assets/javascripts/file_upload.ts
server/app/assets/javascripts/north_star_modal.ts
server/app/assets/javascripts/toast.ts

Add early return in various typescript files. No behavior changed.

[Cleanup] Add early returns in ts files

---

server/test/repository/VersionRepositoryTest.java
server/test/services/program/ProgramServiceTest.java
server/test/support/ProgramBuilder.java
server/test/support/ResourceCreator.java

ProgramBuilder has lots of methods for creating a new active program. Consolidate three methods into one that receives `DisplayMode`. Non functionality changed

[Cleanup] Combine ProgramBuilder.newActiveProgram to one method that receives DisplayMode

---

server/app/services/CfJsonDocumentContext.java
server/app/services/applicant/Block.java
server/app/services/applicant/question/ApplicantQuestion.java
server/app/services/cloud/generic_s3/AbstractS3StorageUtils.java
server/app/services/question/types/QuestionDefinition.java

Updates to patterns needed to support the latest version of Errorprone.

Updates Instanceof Pattern Matching For Errorprone 2

---

server/app/auth/ApiAuthenticator.java
server/app/auth/oidc/CiviformOidcLogoutActionBuilder.java
server/app/controllers/LoginController.java
server/app/controllers/api/ApiPaginationTokenPayload.java
server/app/repository/ReportingRepository.java
server/app/views/fileupload/AzureFileUploadViewStrategy.java
server/app/views/fileupload/GenericS3FileUploadViewStrategy.java

Updates to patterns needed to support the latest version of Errorprone.

Updates Instanceof Pattern Matching For Errorprone 1

---

server/app/auth/ClientIpResolver.java
server/app/auth/oidc/CiviformOidcLogoutActionBuilder.java
server/app/auth/oidc/CiviformOidcProfileCreator.java
server/app/controllers/admin/AdminApplicationController.java
server/app/controllers/admin/AdminReportingController.java
server/app/forms/QuestionFormBuilder.java
server/app/services/AlertSettings.java
server/app/services/ProgramBlockValidation.java
server/app/views/admin/programs/ProgramImageView.java
server/app/views/admin/programs/ProgramPredicateConfigureView.java
server/app/views/admin/settings/AdminSettingsIndexView.java
server/app/views/questiontypes/ApplicantQuestionRendererFactory.java

Updates to patterns needed to support the latest version of Errorprone.
There may be some defaults that are gone. This is normal because all the enum cases would be covered by the pattern matching. 

Updates Switch Pattern Matching For Errorprone 1

---

server/app/services/applicant/ApplicantService.java
server/app/services/applicant/ReadOnlyApplicantProgramService.java
server/app/services/applicant/predicate/PredicateEvaluator.java
server/app/services/applicant/question/ApplicantQuestion.java
server/app/services/export/CsvColumnFactory.java
server/app/services/export/JsonExporterService.java
server/app/services/export/QuestionJsonPresenter.java
server/app/services/export/QuestionJsonSampler.java
server/app/services/export/enums/QuestionTypeExternal.java
server/app/services/openapi/OpenApiVersion.java
server/app/services/pagination/PageNumberPaginationSpec.java
server/app/services/program/predicate/PredicateDefinition.java
server/app/services/program/predicate/PredicateExpressionNode.java
server/app/services/question/types/MultiOptionQuestionDefinition.java
server/app/services/settings/AbstractSettingsManifest.java
server/app/services/settings/SettingsService.java

Updates to patterns needed to support the latest version of Errorprone.
There may be some defaults that are gone. This is normal because all the enum cases would be covered by the pattern matching

Updates Switch Pattern Matching For Errorprone 2

---

browser-test/src/admin/admin_application_download.test.ts
browser-test/src/applicant/application_download.test.ts
browser-test/src/applicant/northstar_application_download.test.ts
browser-test/src/question_lifecycle.test.ts
browser-test/src/support/index.ts
browser-test/src/support/seeding.ts
server/app/controllers/dev/DevToolsController.java
server/conf/routes

Cut out the UI parts to seed questions and just call an endpoint directly.

Optimize question seeding

---

server/app/services/export/PdfExporter.java
server/test/services/export/AbstractExporterTest.java
server/test/services/export/PdfExporterTest.java
server/test/support/ProgramBuilder.java

Adding program related fields to program pdf export.
This PR will only add the following fields to the pdf. Rest of the fields will be tackled in another PR.
* New short description.
* How to apply Step title and description
* Submission confirmation message
Adding program related fields to program pdf export
Program pdf downloads will look like the following-
Fixes #10126

Adding program related fields to program pdf export

---

browser-test/src/admin/admin_program_creation.test.ts
browser-test/src/admin/admin_program_image.test.ts
browser-test/src/admin/admin_program_list.test.ts
browser-test/src/admin/admin_program_migration.test.ts
browser-test/src/admin/admin_program_viewing.test.ts
browser-test/src/api_docs.test.ts
browser-test/src/api_docs_schema_viewer.test.ts
browser-test/src/applicant/applicant_application_index.test.ts
browser-test/src/applicant/northstar_applicant_application_index.test.ts
browser-test/src/auth.test.ts
browser-test/src/header.test.ts
browser-test/src/northstar_auth.test.ts
browser-test/src/northstar_header.test.ts
browser-test/src/northstar_trusted_intermediary.test.ts
browser-test/src/support/index.ts
browser-test/src/support/seeding.ts
server/app/controllers/dev/DevToolsController.java
server/conf/routes

Move program seeding to the the seeding class and call the new seeding endpoint to avoid having to click through the UI.

Optimize program seeding

---

browser-test/src/support/applicant_file_question.ts

Remove unused uploadedFilesLocator variable. No functionality changed.

[Cleanup] Remove unused uploadedFilesLocator variable

---

server/app/controllers/admin/AdminProgramBlocksController.java
server/app/controllers/admin/ProgramAdminManagementController.java
server/app/controllers/applicant/ApplicantRoutes.java
server/app/models/ProgramModel.java
server/app/services/AlertSettings.java
server/app/services/applicant/ApplicantService.java
server/app/services/cloud/azure/AzurePublicStorage.java
server/app/services/program/ActiveAndDraftPrograms.java
server/app/services/program/ProgramService.java
server/app/views/BaseHtmlView.java
server/app/views/admin/migration/AdminImportViewPartial.java
server/app/views/admin/programs/FormattedPredicateValue.java
server/app/views/admin/programs/ProgramIndexView.java
server/app/views/admin/programs/ProgramNewOneView.java
server/app/views/admin/questions/NorthStarQuestionPreview.java
server/app/views/admin/questions/QuestionTranslationView.java
server/app/views/docs/ApiDocsView.java
server/app/views/docs/SchemaView.java

Adds errorprone checker comments for some Optional.empty() usages in the code base.

Add errorprone param names to Optional.empty() magic parameters

---

server/app/services/export/PdfExporter.java
server/test/services/export/PdfExporterTest.java

Adding program's long description to program pdf export
Adding program's long description to program pdf export
Fixes #10126

Adding program's long description to program pdf export

---

server/app/repository/AccountRepository.java
server/app/repository/ApplicationEventRepository.java
server/app/repository/ApplicationRepository.java
server/app/repository/ExportServiceRepository.java
server/app/repository/ProgramRepository.java
server/app/repository/QuestionRepository.java
server/app/repository/VersionRepository.java

Move Transactions into try-with-resource
Chain setters and extract reused getter into a var
Replace functional anonymous methods with method references
Remote unneeded try

Readability cleanup for Repository classes

---

humans.md

Add list of the great people that help build CiviForm

Adding humans.md

---

humans.md

Adding names to humans.md

---

server/app/repository/QuestionRepository.java
server/test/controllers/admin/AdminImportControllerTest.java

I had a scary moment where I couldn't remember how/where we were removing PAI tags from imported questions and realized the test for that didn't actually include any PAI tags! This PR adds a comment to make it obvious where we're removing the PAI tags from questions when importing them and also adds PAI tags to the json that runs through the relevant test.

[Program Migration] Fix test for primary applicant info test case

---

server/app/repository/TransactionManager.java
server/test/repository/TransactionManagerTest.java

TransactionManger does not work on Async code, updated docs.

Update TransactionManager doc to reflect it does not work on Async code

---

server/app/filters/ValidAccountFilter.java
server/test/filters/ValidAccountFilterTest.java

Removing session timeout code from ValidAccountFilter
Related to #10330

Remove session timeout code from ValidAccountFilter

---

load-test/applicant_submit_application.jmx

This updates the submit application test to do the following:
- Instead of using a PROGRAM_ID argument (which wasn't even included for specification in the github action, we will use the minimal-sample-program that gets seeded in the seed action
- Parses the program id from the minimal-sample-program pre-screener page to use in the edit URLs
- Answers the name question (which is what is included in the minimal sample program) with first name + threadnum and last name + threadnum
Tested: https://github.com/civiform/civiform/actions/runs/14541718396/job/40800883137
Note: I specifically used northstar for this, but can test on legacy UI as well if we think that's important.
See program admin page after a run of 10 applications:
Note: I used GenAI to help with some of the syntax in this PR …

Update JMeter submit application test to use minimal-sample-program

---

server/app/controllers/HomeController.java
server/app/repository/HealthCheckRepository.java
server/test/controllers/HomeControllerTest.java
server/test/controllers/HomeControllerWithProfileTest.java

Doing a simple select as health check
Doing a simple select as health check

Doing a simple select as health check

---

browser-test/src/admin/admin_question_list.test.ts
server/app/controllers/admin/AdminQuestionController.java
server/app/controllers/admin/AdminQuestionTranslationsController.java
server/app/views/admin/AdminLayout.java
server/app/views/admin/questions/QuestionEditView.java
server/app/views/admin/questions/QuestionsListView.java
server/app/views/components/QuestionBank.java
server/conf/routes
server/test/controllers/admin/AdminQuestionControllerTest.java
server/test/controllers/admin/AdminQuestionTranslationsControllerTest.java

Adds a URL param to the admin question-list (question bank) page `/admin/questions?filter=someFilter` to allow admins to autopopulate a filter/search term in the search bar using a URL param. This will be very helpful in the future to cross-link other pages to a limited list of questions that are filtered by some term, and show all the info that is usually present on the question bank page, such as the programs those questions are used in, a button to edit the questions, etc.
This is related to work on https://github.com/civiform/civiform/issues/10293 and https://github.com/civiform/civiform/issues/9628, and closes #10356 
Adds an optional URL param to the admin question bank page to support pre-populating the filter/search bar with some query. Usage: `/admin/questions?filter=Some-Filter …

Add URL param for question bank search

---

server/app/controllers/dev/DevToolsController.java

Add extra logging when tests clear memory Caches and the Database to help address the flakey browser test issue.
Fixed naming style on LOGGER to be logger since it is a mutable object and not a constant.

Add logging to clearInternal()

---

server/app/controllers/dev/DevToolsController.java

Deployments don't show INFO level.

Up clearInternal() logging level to warn

---

server/app/controllers/dev/DevToolsController.java

Fleshed out docs around clearing the database and caches based on testing and other observations.
For instance, in Staging through numerous prober runs which clear the DB, the program IDs increment indicating that the PK generators don't reset when truncate() is called.

Update docs on clearInternal and related methods.

---

browser-test/src/applicant/northstar_applicant_application_index.test.ts
server/conf/application.dev.conf

Following https://github.com/civiform/civiform/wiki/Feature-Flags#releasing-your-feature, enabling custom color theming in dev env.
#9882

Enable color theming in dev

---

server/test/conf/MessagesTest.java

Fixes errorprone issue for this test

Fix MessagesTest for errorprone

---

server/app/repository/AccountRepository.java
server/app/repository/TransactionManager.java
server/test/repository/TransactionManagerTest.java

Wraps methods in `TransactionManager` utilities and adds `executeWithRetry(Runnable)`
Improve data consistency by adding database transactions in Account management DB managers.
Addresses: #10188

Add transactions to AccountRepository, and utility methods to TransactionManager

---

server/app/repository/TransactionManager.java

When we retry a concurrency exception log it.   
This is most useful for detecting coding errors as retries are OK and should resolve with the retry.

TransactionManager: Log Concurrency exceptions that are retried

---

server/app/modules/DurableJobModule.java
server/app/repository/AccountRepository.java
server/app/repository/ApiKeyRepository.java
server/app/repository/ApplicationEventRepository.java
server/app/repository/ApplicationRepository.java
server/app/repository/ProgramRepository.java
server/app/repository/QuestionRepository.java
server/app/repository/StoredFileRepository.java

We use 3 different ExecutionContexts in the code, but some variable names are too generic to understand which is being used.  This hopefully will help ensure the correct one is used and improve readability.

Specify ExecutionContext variable names for clarity

---

server/test/auth/oidc/OidcClientProviderTest.java
server/test/services/program/ProgramServiceTest.java
server/test/services/session/SessionTimeoutServiceTest.java
server/test/services/statuses/StatusServiceTest.java
server/test/views/applicant/ProgramCardsSectionParamsFactoryTest.java

Various Error-prone flagged fixes in tests.  Tests had not been having Errorprone ran against them.
Addresses: #10471 10471

Error-prone fixes in tests

---

server/test/filters/ValidAccountFilterTest.java

Fix for error prone 
https://github.com/civiform/civiform/issues/10471

Fix WildcardImport error in ValidAccountFilterTest

---

server/app/repository/ApplicationEventRepository.java
server/app/repository/ApplicationStatusesRepository.java
server/test/repository/ApplicationEventRepositoryTest.java

Replace direct uses of Transactions with the TransactionManager utility.
Addresses: #10188

Convert direct transaction usage to TransactionManager

---

server/test/repository/ProgramRepositoryTest.java
server/test/services/applicant/ApplicantServiceTest.java

Error prone fixes in tests.  This fixes some asserts so they do their actual checks.
Addresses #10471

Fix ErrorProne issues.

---

server/conf/i18n/messages

Found a small typo in comment section in message file while filing for translation.
Part of ##10429

Correct small in message file

---

server/test/services/export/JsonExporterServiceTest.java

Fix errorprone issues.
Addresses #10471

Fix errorprone issues in JsonExporterServiceTest

---

server/app/repository/ApplicationRepository.java

Swap over manual transactions to the TransactionManager.  This elevates the isolation level of the changed lines to be more isolated too.
Some small readability tweaks
Addresses: #10188

ApplicationRepository: Change manual transaction usage to TranactionManager

---

server/test/services/email/graph/GraphApiEmailClientTest.java

Fix error prone issues
Addresses #10471

Fix unchecked throw error prone in GraphApiEmailClientTest

---

server/test/models/ApplicantModelTest.java
server/test/models/ApplicationModelTest.java
server/test/repository/ApplicationRepositoryTest.java
server/test/services/applicant/question/EnumeratorQuestionTest.java

Fix asserts that were not actually testing their conditions.
Addresses #10471

Fix malformed assert statements for errorprone

---

server/test/services/applicant/question/NumberQuestionTest.java

Fix NumberQuestionTest errorprone by removing unused variables
related: https://github.com/civiform/civiform/issues/10471

NumberQuestionTest errorprone fix

---

server/build.sbt
test-support/unit-test-docker-compose.yml

Get errorprone working in sbt test.
Fixes: #10471

Errorprone working under sbt-test

---

server/app/views/admin/programs/ProgramIndexView.java

Avoid unnecessarily copying an ImmutableList by creating the list directly with the element needed and building it when it's added to the builder.
None

[Cleanup] Remove unnecessary copy when building program actions

---

server/conf/logback.xml

Adds default logging for `repository` files at `INFO` level, and adds a line for `io.ebean.SUM` (lazy loading and transaction logging) that can be edited by users to easily log helpful info from ebean.

Log repository at INFO, and ebean.SUM at OFF

---

server/app/views/docs/ApiDocsView.java

Fix the issue when logged in as Program Admin, clicking 'API docs' changes the header items to the header items corresponding to CiviForm Admins.
This is fixed by setting the admin type for the layout in ApiDocsView. Not setting the admin type was causing to use the CiviForm admin by default.
https://github.com/user-attachments/assets/185110ff-307b-4a5a-87ff-8a1405b50153
AI was used to spot what was the issue. The solution was entirely coded by the author.
For reference, this was the task:
> server/app/views/admin/AdminLayout.java is used to render the header. The header depends on admin type.
> When the admin type is PROGRAM_ADMIN, header should only include programAdminProgramsHeaderLink, reportingHeaderLink and apiDocsHeaderLink (if enabled)
> Clicking on 'API Docs' in the header …

Show correct header for Program Admins when API docs is selected

---

server/test/controllers/api/ProgramApplicationsApiControllerTest.java

The current unit tests in ProgramApplicationsApiControllerTest don’t cover all the cases (e.g there are not tests for error handling). This PR refactors and adds tests to improve the test coverage.
Current tests:
1. list_success_dateRange
2. list_success_timedDateRange
3. list_success_multipleResultsInAPage
4. list_success_multiplePages
5. list_unauthorized
New tests:
1. list_success_allApplications
2. list_success_fromDateOnly
3. list_success_toDateOnly
4. list_success_dateRange
5. list_success_pageSize
6. list_success_multiplePages
7. list_error_invalidFromDate
8. list_error_invalidToDate
9. list_error_unauthorizedProgram
10. list_error_mismatchedPaginationTokenDateParam
11. list_error_mismatchedPaginationTokenPageSizeParam
**AI usage**
AI was used to come up with a unit test list for …

Improve ProgramApplicationsApiController unit test coverage

---

server/test/support/ResourceCreator.java

Removes unused `insertDraftProgram()` method
None

[Cleanup] Remove unused insertDraftApplication()

---

browser-test/src/admin/admin_program_migration.test.ts
server/conf/application.dev.conf
server/test/controllers/admin/AdminImportControllerTest.java

Enable the duplicate-handling flag in dev env. Also removes tests that are irrelevant after enabling this flag by default. #9628 #10293

Enable duplicate-handling in dev

---

server/conf/routes

The `routes` file has become an unruly mess. Formatting it some to make it easier to scan through without being too obtuse. There are only whitespace and new line changes.

Formatting routes file

---

.devcontainer/devcontainer.json
.devcontainer/onCreateCommand.sh

There was an issue installing pre-commit, but this works when using the dev-container feature. Seems like there was an update that impacted our setup.
Error looked like this:
[1G[0K\2025-06-27 17:00:47.726Z: [1G2025-06-27 17:00:47.727Z: [0K2025-06-27 17:00:48.125Z: error: externally-managed-environment2025-06-27 17:00:48.130Z:
× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
python3-xyz, where xyz is the package you are trying to
install
Setup codespace from this branch

Fix issue with codespaces

---

server/app/views/components/Icons.java

Set the icon for yes/no questions; used on the dropdown of questions from the "Create new question" button.
#10775
1. Set YES_NO_QUESTION_ENABLED to true.
2. Log in as an admin.
3. Click "Create new question" button.
4. Verify the Yes/No option has a radio button icon.

[Yes/No] Use radio button icon for yes/no questions

---

server/conf/application.conf

Add Arabic to the list of supported languages for testing.
#6142

Add Arabic to the list of supported languages in application.conf

---

server/build.sbt

Adding JSON Schema Validator library. Dependency [approved here](https://docs.google.com/document/d/1_5Ki3nrhAkdlbeDt11rmU6dvREAYT-ZlXGRXthKjO6Q/edit?tab=t.0).
Related to: #10555

Adding JSON Schema Validator Dependency

---

.github/pull_request_template.md

Adding RTL testing to PR checklist

Adding RTL testing to PR checklist

---

browser-test/src/admin/admin_program_list.test.ts
server/app/views/admin/programs/ProgramIndexView.java

External programs are programs hosted outside of CiviFrom, which means they don't have questions.
Therefore, on this PR we remove information referencing universal questions for external programs in the admin panel. Specifically:
1. On the publish modal, remove the 'universal question' warning and text that references 'draft questions' 
2. On the program card, remove universal question text
For a next PR, consider removing '0 questions' from the program card for external programs.
- Publish modal:
- Program card:
As a CiviForm admin
1. Add a universal question
2. Create a program with external program type
3. Verify 'Contains 0 of 1 universal questions' …

[External Program Cards] Remove universal question warning for external programs in admin panel

---

server/app/views/admin/AdminLayoutBaseView.java
server/app/views/admin/BaseView.java
server/test/views/admin/AdminLayoutBaseViewTest.java

Align admin thymeleaf with docs

Align admin thymeleaf with docs

---

server/app/services/ObjectMapperProvider.java

This fixes a serialization exception when viewing /dev/seed/data and there's a date question present with a custom date in its validation parameters. This was module added to `QuestionDefinition` specifically in #10957 but also needs to be available more broadly.
Part of #5677

[Date Validation] Install JavaTimeModule in default ObjectMapper

---

server/app/assets/javascripts/admin_entry_point.ts
server/app/assets/javascripts/applicant_entry_point.ts
server/app/assets/javascripts/config.d.ts
server/app/assets/javascripts/map.ts
server/app/views/components/CreateQuestionButton.java
server/app/views/questiontypes/MapQuestionFragment.html
server/app/views/questiontypes/QuestionFragment.html

Lay out the framework for how we will render maps on pages using client side scripting.
Set `map_question_enabled = true` in `application.dev.conf`
Insert test data into the database:
```
INSERT INTO geo_json_data (geojson, endpoint, update_time, create_time)
VALUES (
'{"test": "test"}',
'test', // should match the value you use for geojson endpoint
NOW(),
NOW()
);
```
Create a map question.
Part of #11003

[Maps] Set up map.ts for rendering the map

---

.github/ISSUE_TEMPLATE/oncall-rotation.md

Added a link to the new On Call issue board to our On Call issue template/checklist.

add link to oncall board to oncall issue

---

server/app/services/settings/SettingsManifest.java
server/conf/env-var-docs.json
server/conf/helper/feature-flags.conf

Adding a feature flag for Translation management improvement phase one: https://docs.google.com/document/d/17dVJN4bxzmuIzhV2MEla0fe51MZ_6h39lw-srUEZUhY/edit?pli=1&tab=t.0

[Translation Management]add feature flag for phase one

---

.github/ISSUE_TEMPLATE/oncall-rotation.md

Oncall template: Link to generated PR to update the demo site

---

server/conf/i18n/messages

Adding new message configs for two new categories: Military and Veterans. This is step 1 of [Adding-a-new-category](https://github.com/civiform/civiform/wiki/Adding-a-new-category). 
Related  #10989

Add new category messages for military and veterans

---

browser-test/src/admin/northstar_admin_bulk_update_statuses.test.ts
browser-test/src/support/admin_programs.ts
browser-test/src/support/seeding.ts
server/app/controllers/dev/DevToolsController.java
server/app/controllers/dev/seeding/DevDatabaseSeedTask.java
server/conf/routes

Uses headless seeding to create the data needed for a test that is hitting a timeout in the CI.

Use headless seeding for creating applications in browser tests

---

browser-test/src/admin/northstar_admin_application_download.test.ts

Added `northstar_admin_application_download.test.ts` as a north star counterpoint to `admin_application_download.test.ts`
Fixes #10969;

[North Star] add northstar_admin_application_download.test.ts

---

server/app/assets/javascripts/admin_entry_point.ts
server/app/assets/stylesheets/uswds/_uswds-theme-custom-styles.scss
server/app/controllers/admin/apibridge/DiscoveryController.java
server/app/repository/ApiBridgeConfigurationRepository.java
server/app/views/admin/AdminLayout.html
server/app/views/admin/AdminLayout.java
server/app/views/admin/AdminLayoutBaseView.java
server/app/views/admin/shared/AdminCommonHeader.html
server/app/views/admin/shared/AdminCommonHeader.java
server/conf/routes
server/test/repository/ApiBridgeConfigurationRepositoryTest.java

This fixes some bugs and adds some dependencies needed by the child branch (which has the discovery edit page). Trying to not have one giant PR so splitting. Gets the menu, routes, and empty controller in place.
Related to: #10555

Base dependencies and bug fixes for api bridge discovery

---

server/app/services/applicant/question/MapQuestion.java
server/app/services/export/CsvColumnFactory.java
server/app/services/export/QuestionJsonPresenter.java
server/app/services/export/QuestionJsonSampler.java
server/app/services/export/enums/QuestionTypeExternal.java
server/app/services/question/QuestionAnswerer.java
server/app/views/questiontypes/MapQuestionFragment.html
server/test/services/export/QuestionJsonSamplerTest.java

1. Change the submission for map question selections to json that includes the unique ID of the feature and the location name.
2. Allow exporting applicant data in the API for the map question. The API should return selected feature ids.
3. Allow downloading CSVs and JSON for the map question. The CSV and JSON should return both selected feature ids and names.
Continued development of the map question.
1. Create a map question and attach it to a program. (`https://api.mapbox.com/datasets/v1/tahloohluh/cmapwjjtr432o1nmf4bf1x007/features?access_token=pk.eyJ1IjoidGFobG9vaGx1aCIsImEiOiJjbWFlaThkaWwwODN3MmlvY3E3ZDVhMHAxIn0.6GNB-VIpL1yL4Diw2cOzLQ` for a testing …

[Maps] allow exporting map question as json csv and in api

---

server/conf/i18n/messages

Removing duplicated key in message root file. `link.edit` already exists. 

[Translation Infra Migration]removing duplicated key in message root file

---

server/app/auth/oidc/CiviformOidcProfileCreator.java
server/test/auth/oidc/CiviformOidcProfileCreatorTest.java

We should handle TI sessions the same way as applicants, so we create an active session for them and clear their active sessions if needed. This was an issue Swathi noticed in staging when turning on enhanced logout + session replay
- Enabled enhanced logout for applicants and session replay protection
- Add your email as a trusted intermediary for a program
- Login and logout should now work as expected
Fixes https://github.com/civiform/civiform/issues/11515

Add enhanced logout logic for TIs
