civiform/civiform

server/tailwindbuilder.sbt
server/test/views/BaseHtmlLayoutTest.java

Previously it was enabled only when developer runs all java unit tests locally. This PR adds tailwind building hook to the following test commands: `jococo` - used to run tests on CI, `testOnly`/`testQuick` - used to iteratively run individual tests locally.

Enable tailwind css building for unit tests

---

browser-test/src/support/index.ts

Removing fallback code in place for probers now that we set the appropriate environment variables for all environments ([AWS staging](https://github.com/civiform/civiform/issues/3326#issuecomment-1245809004) / [Seattle staging](https://github.com/civiform/civiform/issues/3326#issuecomment-1247203184)).
N/A
Fixes #3326

Throwing errors when test user environment variables aren't set instead of silently falling back on previous behaviors.

---

browser-test/src/admin_program_list.test.ts
browser-test/src/civiform_admin_question_list.test.ts

Removing test assertions that dealt with DBs not being previously cleared between test cases

---

server/app/services/question/ActiveAndDraftQuestions.java
server/test/services/question/ActiveAndDraftQuestionsTest.java

In #3431, we now perform sorting of questions in the list view itself (https://github.com/civiform/civiform/blob/4e6f220eb78cc84ef0e239aa0bcc39392d715937/server/app/views/admin/questions/QuestionsListView.java#L135-L142).
N/A
#3029

Removing ordering from ActiveAndDraftQuestions since the sorting occurs elsewhere

---

server/app/assets/javascripts/file_upload.ts
server/app/views/AwsFileUploadViewStrategy.java
server/app/views/AzureFileUploadViewStrategy.java
server/app/views/components/FieldWithLabel.java
server/app/views/questiontypes/ApplicantQuestionRendererImpl.java
server/test/views/components/FieldWithLabelTest.java
server/test/views/questiontypes/CheckboxQuestionRendererTest.java
server/test/views/questiontypes/CurrencyQuestionRendererTest.java
server/test/views/questiontypes/DropdownQuestionRendererTest.java
server/test/views/questiontypes/IdQuestionRendererTest.java
server/test/views/questiontypes/RadioButtonQuestionRendererTest.java
server/test/views/questiontypes/TextQuestionRendererTest.java

Use all lowercase for `aria-describedby`. In practice, any casing is fine, since it just all gets lowercased anyway. This is to avoid developer confusion.
N/A

Update casing on aria-describedby to use all lowercase

---

server/app/controllers/applicant/RedirectController.java

The previous implementation of `relevantPrograms` had to account for multiple draft applications for different versions of the program being returned. We now filter these out in the [service method](https://github.com/civiform/civiform/blob/75a6d6c1c558cf8e7bebbeb4ba8665e52f828e77/server/app/services/applicant/ApplicantService.java#L527-L537).
N/A
#2573

Redirect controller no longer grabs the latest draft application explicitly since the underlying method does it

---

bin/create-release

Latest fail was complaining about releaser email - setting it explicitly in the script.
Remove check for civiform login name that doesn't work locally depending on docker version.
Should help with [#3436](https://github.com/civiform/civiform/issues/3436)

set releaser email in the script. Remove check for civiform login name

---

browser-test/src/application_download.test.ts
server/build.sbt

Addressed browser test not handling when Status tracking is enabled.
Browser tests environments vary including what features are enabled or not.
Normally browser tests could force the feature flag state, however for export that isn't available as it doesn't fit the other usage patters for feature flags.  We could update that with a bit of extra complexity, but this is blocking releases to taking a more dynamic approach here.
NA - testing only

Update export test to account for Status being enabled or not.

---

server/app/repository/ApplicationRepository.java
server/test/repository/ApplicationRepositoryTest.java
server/test/services/applicant/ApplicantServiceTest.java

This was a regression introduced by #2695.
Fixes issue where the applicant-facing program index page errantly categorized programs as in-progress / submitted if any applicant had an in-progress / submitted application for that program.
In addition, the application submission date and current application status could be shown for these programs, but no other application data would have been visible.

Fix call for program index page to properly filter to the set associated with the applicant

---

bin/create-release

Script failed since git config user.name wasn't set. This will now set it.
Sets the git config user.name to the github_actor value in the release script

Set value for user.name

---

browser-test/src/support/index.ts

See https://github.com/civiform/civiform/issues/3302#issuecomment-1258429591. Since we're already using a regex in the callsite and specifying `/g`, `replace` is equivalent to `replaceAll` and is already available in the current TypeScript bindings.
N/A
#3302

Use `replace` since `replaceAll` can cause TypeScript compiler issues

---

server/app/views/questiontypes/AddressQuestionRenderer.java
server/app/views/questiontypes/ApplicantCompositeQuestionRenderer.java
server/app/views/questiontypes/ApplicantQuestionRendererImpl.java
server/app/views/questiontypes/ApplicantSingleQuestionRenderer.java
server/app/views/questiontypes/CheckboxQuestionRenderer.java
server/app/views/questiontypes/CurrencyQuestionRenderer.java
server/app/views/questiontypes/DateQuestionRenderer.java
server/app/views/questiontypes/DropdownQuestionRenderer.java
server/app/views/questiontypes/EmailQuestionRenderer.java
server/app/views/questiontypes/EnumeratorQuestionRenderer.java
server/app/views/questiontypes/FileUploadQuestionRenderer.java
server/app/views/questiontypes/IdQuestionRenderer.java
server/app/views/questiontypes/NameQuestionRenderer.java
server/app/views/questiontypes/NumberQuestionRenderer.java
server/app/views/questiontypes/RadioButtonQuestionRenderer.java
server/app/views/questiontypes/TextQuestionRenderer.java

Adds another layer of superclasses to the question renderer. Composite questions (contains multiple input fields) use fieldset and legends for rendering, while single input questions (contains only one input field) do not.
N/A - internal refactor
Fixes #3392

Refactor question renderer classes to have a composite and single parent class

---

server/app/services/MessageKey.java
server/app/views/BaseHtmlLayout.java
server/app/views/admin/AdminLayout.java
server/app/views/applicant/ApplicantInformationView.java
server/app/views/applicant/ApplicantLayout.java
server/conf/messages
server/conf/messages.am
server/conf/messages.en-US
server/conf/messages.es-US
server/conf/messages.ko
server/conf/messages.so
server/conf/messages.tl
server/conf/messages.vi
server/conf/messages.zh-TW
server/test/views/BaseHtmlLayoutTest.java

We had logic to suffix the page title with text depending on the layout (e.g. `- CiviForm` for applicants and `- CiviForm Admin Console` for program/CiviForm admins).
Our login page wasn't make use of either of those specific layouts. This pushes the "suffix the page title" logic down to the `BaseHtmlLayout` class with a default value of "CiviForm".
Note: While here, I also filed #3548 to track the fact that the "Login" text is not localized.
This had an incorrect set of text. Since it wasn't localized, I also removed it from the translations files and inlined it directly with a comment. Finally, I moved the `<h1>` SR-only tag above the content that it was describing for clarity.
Updating the titles for the login page and language selection page to be more accessible.
Fixes #3545

Fix login / select language page titles to be more accessible

---

server/build.sbt
server/package-lock.json
server/package.json
server/project/TypescriptBuilder.scala
server/project/plugins.sbt
server/tsconfig.json

[sbt-web](https://github.com/joost-de-vries/sbt-typescript) plugin we are using is no longer maintained and 5 years old. It uses Typescript 2 while current one is Typescript 4. Which means we can't use latest features and improvements. 
This PR removes sbt-web and instead adds custom TypescriptBuilder.scala file, similar to TailwindBuilder.scala. That file defines a task that calls `tsc` (typescript compiler) to compile our few TS files. Code is a bit complicated due to sbt APIs which aren't very straightforward. 
That task is hooked into sbt-web pipeline in `build.sbt` and runs before digest/gzip tasks. In dev mode, upon recompilation TS files will be recompiled only if some of them was changed. TS files are not recompiled on java file updates.
Additionally this PR updates TS version to …

Replace sbt-web with custom task

---

.github/workflows/tests.yaml
browser-test/src/address.test.ts

jest-image-snapshot automatically adds image snapshot if it's missing during test run. That's good for local development but for CI it's undesired: we want test to fail in cases of missing snapshots. This PR adds extra step to github action workflow which ensures that no screenshots being added after test run.
Here is how failure looks:

Fail on new images being added

---

server/app/views/LanguageSelector.java
server/app/views/applicant/ApplicantLayout.java

Add language hints to the applicant-facing language selection screen, language dropdown, and brand ID.
Fixes #3546

Setting lang for language radio select, dropdown, and the always-English brand

---

server/app/views/applicant/ProgramIndexView.java
server/conf/messages

Once these are available, we can use them as the screen reader text to address #3552.
N/A
Fixes #3552; #3577

Adding new strings to translate for screen readers for the Edit and Continue buttons

---

server/app/assets/javascripts/admin_application_view.ts
server/app/assets/javascripts/admin_applications.ts
server/app/controllers/admin/AdminApplicationController.java
server/app/views/admin/programs/ProgramApplicationListView.java
server/app/views/admin/programs/ProgramApplicationView.java
server/test/controllers/admin/AdminApplicationControllerTest.java

Protect against outdated Application views UIs.
When the Frontend sends a request to update an Application's status, we now send the UIs believed current status and check that it is in fact the current one.  If it isn't we reload the page with an error toast.
Application status updates have extra consistency verification.
Fixes #3263

Status Tracking: Verify user request is based on latest data

---

server/app/services/MessageKey.java
server/app/views/applicant/ProgramIndexView.java
server/conf/messages
server/conf/messages.am
server/conf/messages.en-US
server/conf/messages.es-US
server/conf/messages.ko
server/conf/messages.so
server/conf/messages.tl
server/conf/messages.vi
server/conf/messages.zh-TW
server/test/controllers/applicant/ApplicantProgramsControllerTest.java

Notably this removes the screen-reader only `<h4>` tag used in each program card. Previously, this text included the relative index of the program within the list. By putting each section of programs inside of a `<ol>` and having each card be a `<li>`, we can instead just use the program title in the `<h4>` and screen readers will have sufficient context to give us the "2 of 5" announcement "for free".
Manually tested by enabling the screenreader. Using the shortcuts from https://dequeuniversity.com/screenreaders/voiceover-keyboard-shortcuts, I:
* Used "Next heading" until I reached the "Not started" section
* Used "Next List", which selected all of the programs in that section
* Used right arrow to navigate through the list
* The `<h4>` was announced as "Heading level 4 <program name> 1 …

Accessibility improvements for the program index page

---

browser-test/src/end_to_end_enumerators.test.ts
server/app/assets/javascripts/main.ts
server/app/views/questiontypes/EnumeratorQuestionRenderer.java

We generate a "template" for the enumerated entity server-side. Previously this was generated a random ID. However, when the JavaScript in main.ts cloned the node, it also carried the ID along, generating a non-unique ID.
This keeps a global counter and replaces the ID each time a new entity is added.
Also updated integration tests to test these scenarios as well. I manually validated that it failed when I:
* Didn't update the input element's ID
* Didn't update the `label` element's `for` attribute
* Didn't update the error div's ID
Fix accessibility violations when applicants were adding answers to an enumerated question.
Fixes #3565

Making cloned enumerator field entries have unique IDs

---

server/app/views/LoginForm.java

Also, while here, we had the "DEBUG MODE" warning at `<h1>`. I've downgraded that to a `<p>` tag.
Adding an `<h1>` tag to the login page to improve accessibility for applicants with screen readers.
Fixes #3572

Adding an h1 to the login page

---

server/app/views/applicant/ApplicantProgramInfoView.java

Manually used screen reader and confirmed that the less-than sign is no longer announced when focusing the link back to Programs & Services.
Less than sign in link back to Programs & Services is no longer announced for screenreaders.
Fixes #3589

Less than sign in program details page is no longer announced for screenreaders

---

server/app/modules/SecurityModule.java

This mitigates a vulnerability in the logout process described here: https://groups.google.com/g/pac4j-security/c/poWGfZKo-ww/m/S-h4ggaSAgAJ
At the time of the vulnerability announcement, upgrading to the next version of pac4j is causing a build failure: https://github.com/civiform/civiform/pull/3575
This can be removed after upgrading to pac4j v5.6.1
Mitigate vulnerability in pac4j logout logic [reported here](https://groups.google.com/g/pac4j-security/c/poWGfZKo-ww/m/S-h4ggaSAgAJ)

Set pac4j logout URL pattern

---

.github/workflows/format.yaml
formatter/fmt
formatter/formatter.Dockerfile

Have the tests run when their formatter changes.
Include the terraform package in the formatter dockerfile for use in the cloud-deploy-infra repo.
n/a

Run fmt test when formatters change

---

server/app/controllers/admin/AdminApplicationController.java
server/app/forms/QuestionForm.java
server/app/services/export/CsvExporterService.java
server/app/services/question/QuestionService.java
server/app/views/admin/questions/QuestionEditView.java
server/test/controllers/admin/AdminApplicationControllerTest.java
server/test/services/export/CsvExporterTest.java

We have various Export classes [Csv/Pdf/Json]Exporter, but only one ExportService and it happens to only use CsvExporter.
This is likely a historical artifact of Csv being the first exporter, and a pattern that was not maintained for the Pdf and Json ones. 
The rename makes the package clearer that ExportService does not help with or handle all Export formats.
NA - Class renaming

Rename ExporterService to CsvExporterService

---

browser-test/jest.config.js

Warning: 
```
ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
transform: {
<transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
},
```

Fix jest warning

---

server/app/assets/javascripts/admin_applications.ts
server/app/controllers/admin/AdminApplicationController.java
server/test/controllers/admin/AdminApplicationControllerTest.java

The redirect is used more generally now (for errors and showing toasts also), so renaming the url param and cleaning up the code a tad.
Renames a url parameter used in the application view page.

Rename successRedirectUri to redirectUri

---

server/app/assets/javascripts/radio.ts
server/app/views/LanguageSelector.java
server/app/views/components/FieldWithLabel.java
server/app/views/style/ApplicantStyles.java
server/app/views/style/BaseStyles.java
server/app/views/style/StyleUtils.java

*NOTE: This is a dependency of [upgrade tailwind css](https://github.com/civiform/civiform/pull/3438) and  [replace Styles.java calls with style literals](https://github.com/civiform/civiform/pull/2630), i.e. this PR needs to be merged before either of those are merged*
Needed to fix broken styles in [replace Styles.java calls with style literals](https://github.com/civiform/civiform/pull/2630)
Some of our elements have conflicting tailwind styles
Which one ends up being shown depends on their order in the tailwind.css file
The order of styles in tailwind.css depends on the order they were found during extraction
Before it just so happened that when the Styles.java was parsed, conflicting style classes didn't have an effect
But when style classes are scattered throughout the UI code, it …

Remove style conflicts

---

server/app/services/MessageKey.java
server/conf/messages

Add copy to be translated. Message is used to denote required fields will be marked with a *.
Part of #3381

Add required field annotation msg for translation

---

server/app/auth/oidc/CiviformOidcLogoutActionBuilder.java
server/app/auth/oidc/applicant/LoginGovProvider.java
server/test/auth/oidc/applicant/LoginGovProviderTest.java

Login.gov requires passing `client_id` in logout request: https://developers.login.gov/oidc/#logout-request This PR changes civiform to add such param automatically instead of each deployment using login.gov having to add extra environment variable. 
Support login.gov logout out-of-box. 
Issue #3621

Add `client_id` to logout url when using login.gov

---

server/app/controllers/applicant/RedirectController.java

Unsure why this was originally favored but it is seemingly unnecessary and doesn't work with the new version of AutoValue 1.10 in #3635 
`
/usr/src/server/app/controllers/applicant/RedirectController.java:3:1: package autovalue.shaded.com.google$.common.base does not exist
`
Was added in https://github.com/civiform/civiform/commit/68db4b29dc31de11c764ef469c47f9ebb3472eca#diff-f4a4a51a33b341f6a641a7e55f3ca6b53da6af19bc2083ff114d04113cfc16c4
Fix import by removing shaded checkNotNull usage in AutoValue

Remove shaded Preconditions import

---

browser-test/src/support/index.ts

Null check value as caught in new version of ts-jest v29.0.3 #3574 
```
Error: Jest: Got error running globalSetup - /usr/src/***-browser-tests/src/delete_database.ts, reason: [TSError: src/support/index.ts:64:24 - error TS2532: Object is possibly 'undefined'.
64       const testFile = testPath.substring(testPath.lastIndexOf('/') + 1)
~~~~~~~~
src/support/index.ts:64:43 - error TS2532: Object is possibly 'undefined'.
64       const testFile = testPath.substring(testPath.lastIndexOf('/') + 1)
~~~~~~~~
src/support/index.ts:70:[19](https://github.com/civiform/civiform/actions/runs/3149234497/jobs/5120631108#step:9:20) - error TS2532: Object is possibly 'undefined'.
70         dirs.push(expect.getState().currentTestName.replace(/[:"<>|*?]/g, ''))
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]
```
NA - …

Null check value

---

bin/run-browser-tests
bin/run-browser-tests-ci
bin/run-browser-tests-local
browser-test/bin/wait_for_server_start_and_run_tests.sh

Today we have 2 scripts that run browser tests: `bin/run-browser-tests-local` and `wait_for_server_start_and_run_tests.sh`. They do basically the same thing with the only difference in server urls they use to call CiviForm. This PR updates `bin/run-browser-tests-local` to call `wait_for_server_start_and_run_tests.sh` and have the latter the meaty logic of running tests. 
Additionally removes --debug option from `wait_for_server_start_and_run_tests.sh`. That option outputs extra API logs which I don't believe we use. We have different debugging approach described in https://docs.civiform.us/contributor-guide/developer-guide/testing#debugging-browser-tests that allows to run playwright inspector and step-through the code.
If some engineer will need to go deep into playwright debugging they …

Deduplicate browser test scripts

---

server/app/modules/DatabaseSeedModule.java

The exception is caused when seed database task runs before evolutions applied. This is not a great fix, but should be ok given that within the first five seconds unlikely anyone will be meaningfully using the app.
Error:
```
[error] a.d.TaskInvocation - Query threw SQLException:ERROR: relation "questions" does not exist
Position: 335 Bind values:[] Query was:select t0.id, t0.name, t0.enumerator_id, t0.description, t0.legacy_question_text, t0.question_text, t0.legacy_question_help_text, t0.question_help_text, t0.question_type, t0.validation_predicates, t0.legacy_question_options, t0.question_options, t0.enumerator_entity_type, t0.question_tags, t0.create_time, t0.last_modified_time from questions t0 where t0.name = any(?) order by t0.id
javax.persistence.PersistenceException: Query threw …
```

Fix SQL-related error that shows up when starting CiviForm with empty DB

---

browser-test/src/support/index.ts

During logout we need to have extra logic only when user was properly logged through OIDC. In those cases we need to click on "Yes" button on OIDC logout page. In other cases we should just continue.
Also removes timeout from `textContent` call. That timeout caused errors sometimes that could explain flakiness. 
Ran github actions 3 times and no failures in browser tests
Fixes #3669

Improve logout handling in browser tests

---

.github/workflows/format.yaml
browser-test/.npmrc
browser-test/bin/wait_for_server_start_and_run_tests.sh
browser-test/package-lock.json
browser-test/playwright.Dockerfile
formatter/fmt
formatter/formatter.Dockerfile

See https://github.com/civiform/civiform/issues/3678 for more details. This PR adds `.npmrc` with option that ignores version mismatch. This is required for rennovate bot to be happy. Currently it fails to update some npm dependencies because it trips over that warning.

Add option to ignore npm version mismatch

---

.github/workflows/build_push_ci.yaml
.github/workflows/release.yaml
.github/workflows/tests.yaml

Dockerhub username is well known - "civiform". There is no security benefit if having it as secret. The only benefit it provides is sharing it across multple github action files, simplifying its update if we even need to use a different account.
However the downside is that github clears all mentions of string "civiform" from logs replacing them with *** which makes logs confusing and hard to read. Example:

Don't use github secrets for dockerhub username

---

formatter/eslintrc_base.json
server/app/assets/javascripts/admin_application_view.ts
server/app/assets/javascripts/admin_validation.ts
server/app/assets/javascripts/modal.ts
server/app/assets/javascripts/preview.ts
server/app/assets/javascripts/toast.ts

We've been using standard check that's intended for JS code. But our codebase is 95% TS and the standard check triggers false positives on some TS code. This PR updates config to use TS check. Additionally removes few unused parameters that were detected when the check was enabled.

Fix no-unused-vars eslint check

---

server/app/services/MessageKey.java
server/conf/messages

This will be used to announce that errors are present for screen reader users. I checked with UX that this text sounds good.
N/A
#3563

Add screen reader text for errors for translation

---

Dockerfile
formatter/formatter.Dockerfile

Version 11.0.7 should contain fixes for https://openjdk.org/groups/vulnerability/advisories/2022-10-18. This images are used only for development images. For production image we are still using 11.0.16 because amd64/eclipse-temurin haven't pushed updated version yet. 
Issue #3674

Update openjdk image to 11.0.17

---

server/app/auth/oidc/admin/AdfsProfileAdapter.java
server/build.sbt

Pac4j update pulls in slf4j API 2.0. Which breaks logging as logback 1.2 used by Play framework by default is not compatible with slf4j 2.0. Updating logback to 1.3 seems to just work. I tried it few months ago and there were still some issues. But not it looks ok. Things I tested:
1. Deployed civiform with updated logback and pac4j dependencies.
2. Logged in as admin to make sure that upated AdfsProfileAdapter works.
3. Ensured that logs are emitted and available in AWS console.  
Update pac4j to 5.6.1 and logback to 1.3.4
Fixes #3260

Update pac4j to 5.6.1 and logback to 1.3.4

---

.github/ISSUE_TEMPLATE/oncall-rotation.md

Because we renamed #Deployment-Bot to #CI in Slack

Update Oncall Template to use #CI Slack Channel

---

server/app/controllers/admin/AdminProgramBlockPredicatesController.java
server/app/views/admin/programs/ProgramBlockPredicatesEditView.java

Updated docs, coding and naming for clarity.
NA

PredicateController and View code and comment clarity

---

docker-compose.dev.yml
docker-compose.yml
init_postgres.sql
server/conf/application.dev-browser-tests.conf
server/conf/application.test.conf
test-support/unit-test-docker-compose.yml

This PR adds an `init_postgres.sql` script that is mapped to postgres container upon startup. The script creates additional database to be used by unit tests. That way same database can be used by multiple users without overriding each other data. For example for local development and for unit testing which wipes out data between runs. 
In follow up PRs I'm going to change unit tests to use the same environment as dev.
Issue #3727

Add new database for unit and browser tests to dev postgres

---

server/test/app/SecurityBrowserTest.java
server/test/auth/ProfileMergeTest.java
server/test/auth/oidc/OidcProfileAdapterTest.java
server/test/auth/oidc/OidcProviderTest.java
server/test/auth/oidc/applicant/Auth0ProviderTest.java
server/test/auth/oidc/applicant/GenericOidcProfileAdapterTest.java
server/test/auth/oidc/applicant/GenericOidcProviderTest.java
server/test/auth/oidc/applicant/IdcsProviderTest.java
server/test/auth/oidc/applicant/LoginGovProviderTest.java
test-support/unit-test-docker-compose.yml

This allows to run unit tests during development from the same sbt instance from which developer run server. Removed exposing port to host as I don't see the use case. The comment said for debugging, but I struggle to think of a usecase where one might need to debug specifically unit test environment and not from the container, but from the developer host machine.
Issue #3727

Use same dev-oidc host/port in unit tests as in dev

---

server/app/services/MessageKey.java
server/conf/messages

Add new sr text to be translated. Not used yet.
This will be used for the program preview page links. Currently it always reads "Edit" to screen readers, even when the visual labels are "Start here" and "Continue".
N/A
#3559

Add screen reader text describing program preview page links

---

server/app/repository/VersionRepository.java
server/test/repository/VersionRepositoryTest.java

Updates updatePredicateNode to updatePredicateNodeVersions for clarity and consistency with other sibling methods.
Remove default in switch handling for node types.  We should explicitly handle each type; currently all 3 are so removal has no effect and ErrorProne will detect new ones that aren't explicitly handled in MissingCasesInEnumSwitch
NA

Clean up updatePredicateNode

---

server/app/views/components/CreateQuestionButton.java

When creating a new question from the question bank, the bottom-most question is not visible. This is due implementation details of question bank where bottom 48px are always below the screen. To fix it we add 48px padding to the question type list to make all questions visible.
I didn't add/update any tests. I tried using playwright's `isVisible()` to check whether the bottom-most question is visible but it returns true even if it's below the screen. 
Before:
After: 
Fixes inaccessible question type when creating a new question from question bank.
Fixes #3748.

Fix scrolling issue with question bank question

---

browser-test/browser-test-compose.dev.yml
browser-test/browser-test-compose.yml
docker-compose.dev.yml
docker-compose.yml
server/build.sbt
server/conf/application.dev-browser-tests.conf

This makes it possible to switch between servers from sbt shell. 
Issue #3727

Add two sbt commands to run civiform and dev and browser test modes

---

server/app/services/applicant/ApplicantData.java

During browser test run there is a lot of warnings in console like
```
[warn] s.a.ApplicantData - Application {} does not include an applicant name. This is expected for guest users.
```
They are misleading as they don't indicate that something is wrong or should be fixed. Additionally it uses incorrect template with missing application id. Reading the code there is no application id attached to ApplicantData as it is expected to contain answers to all questions. That's why I decided to remove this warning message altogether as it doesn't give any useful information.

Remove noisy " Application {} does not include an applicant name" warning

---

browser-test/src/support/index.ts

Fix the timezone in screenshot diffs to be static. The recent daylight savings change surfaced this issue.
NA - testing

Normalize image diff Timezones to PDT

---

.github/workflows/format.yaml

Changes skipCommit to skip-commit to fix a deprecation warning. 
Set the googlejavaformat-action to v3 instead of master. Technically they are the same (right now), but seems safer to use the official tagged release version over master.

Fix deprecation warning; Specify action version

---

.github/workflows/tests.yaml

We're getting intermittent issues with codecov trying to upload lately. Disabling it from failing the entire pipeline for now.

Don't fail on codecov

---

server/app/auth/AuthIdentityProviderName.java
server/app/controllers/LoginController.java
server/app/views/LoginForm.java
server/test/auth/AuthIdentityProviderNameTest.java

The bug was in LoginController.java calling toString() instead of getString() on the enum. That resulted in the comparison to always be False and registration url never used.
Renamed the method to be getValue() to avoid confusion in the future.
"Create account" link now correctly leads to registration page.

Fix "Create account" link for idcs use case

---

renovate.json

Removing the ending `:` which is preventing the com.fasterxml.jackson libraries from being correctly grouped by renovatebot.

Renovate not grouping Jackson

---

server/app/views/ViewUtils.java
server/app/views/components/Icons.java

This is tech debt cleanup. In #3148 I refactored icons so that callers always explicitly set size of icon element instead of relying on whatever `Icons.svg()` sets. Setting width/height is no longer necessary and removing it makes it clear that callers must set desired size themselves.

Don't explicitly set width/height on svg elements

---

browser-test/src/landing_page.test.ts

Don't check for "Create account" button on AWS staging since that value is not set.

fix prober to not check for create on aws staging

---

.github/release.yml

At the moment all pull requests considered to be a Feature as they all match * label. This PR changes it so that only PRs with `feature` label considered Features. PR with no label now go to "Other changes".

Update release.yml to better handle labels

---

.github/workflows/format.yaml
browser-test/.npmrc
browser-test/bin/wait_for_server_start_and_run_tests.sh
browser-test/package-lock.json
browser-test/playwright.Dockerfile
formatter/fmt
formatter/formatter.Dockerfile

We added `--force` due to incompatibility of jest-image-snapshot library with jest 29. It has been fixed and we no longer need it. 
Fixes #3678

Remove `--force` from npm install

---

server/conf/application.conf

Remove deprecated idcs_register_uri flag once Seattle prod has switched.

remove idcs_register_uri in favor of applicant_register_uri

---

bin/run-browser-test-env

For browser test setup
1. Stop clearing the output to the console as it hides compile errors.
2. Add a lazy load loop to fully initialize the server sooner.
NA testing only

Don't clear cml output and lazy load browser test server

---

server/app/controllers/dev/FeatureFlagOverrideController.java
server/app/featureflags/FeatureFlags.java
server/test/controllers/dev/FeatureFlagOverrideControllerTest.java

Show feature flag settings on the /dev/feature  page
Show feature flag settings on the /dev/feature  page

Show flag settings on the dev feature flag page

---

server/app/auth/oidc/CustomOidcLogoutRequest.java
server/conf/application.conf
server/test/auth/oidc/CustomOidcLogoutRequestTest.java

For some environments the standard OIDC logout flow is not working well. For them we need to use custom logout url. For example for Seattle we need to use the following URL (with no extra URL params): `https://login.seattle.gov/#/logout?appName=CIVIFORM`. This PR improves CiviForm logic to support this use case. In particular it does:
1. Allow custom logout URL to have fragment `#`. Default pac4j logic removes everything after the fragment. Unclear whether it's intentional or it just was implemented that way, before client-side rendering/routing became popular. For context here is pac4j logic: [link](https://sourcegraph.com/maven/com.nimbusds/oauth2-oidc-sdk/-/blob/com/nimbusds/openid/connect/sdk/LogoutRequest.java?L266). 
2. Handle empty `auth.oidc_post_logout_param` config setting as …

Improve custom logout url support

---

browser-test/src/admin_predicates.test.ts
server/app/controllers/admin/AdminProgramBlockPredicatesController.java
server/app/services/program/predicate/LeafOperationExpressionNode.java
server/app/services/program/predicate/Operator.java
server/app/services/program/predicate/PredicateValue.java
server/test/controllers/admin/AdminProgramBlockPredicatesControllerTest.java
server/test/services/program/predicate/PredicateValueTest.java

Allows currency question types to be used in Predicates.  Currently they are selectable but have no operators.
Note: currency is stored as a cents value. This PR takes the user provided predicate dollars/cents value and converts it to cents for storage, and likewise converts cents to dollars/cents when displayed.
`PredicateValue.toDisplayString()` is updated to now require the question the predicate is on.  The method only has one caller and it now directly handles the case where the question is not available.  (This situation is likely indicative of a coding/data bug though)
Currency questions are now available for visibility predicate logic conditions.
Fixes #3854

Add currency to predicate options

---

browser-test/src/admin_predicates.test.ts
browser-test/src/support/applicant_questions.ts

Predicate browser tests only test positive assertions which could be achieved by the server just evaluating true on everything, this adds a negative assertion at each step.
This discovered #3859 in Date evaluations.
NA testing.

Expand predicate test to evaluate negative assertions.

---

browser-test/src/auth.test.ts

Until now we've been relying on implicit navigation event wait. That wait is added by `page.click()` and assumes that the next page that will be fully loaded is the loginForm page. That assumption comes from the fact that logout usually involves a series of redirects that end up on loginForm and that all redirects are server-side using 3xx responses. In Seattle staging one of those redirects is implemented client-side and that page fires navigation event violating our expectation.
In this PR I explicitly wait for browser to end up on the /loginForm page.
Issue #3621

Explicitly wait for browser to end up on login page after logout

---

Dockerfile
bin/lib/docker.sh
bin/run-dev
bin/sbt
browser-test/browser-test-compose.yml
docker-compose.dev.yml
docker-compose.yml
entrypoint.sh
server/entrypoint.sh

Changes docker files so that civiform container doesn't launch server upon start. Instead civiform server is launched by running `docker exec` on the running container. This allows to run different commands on the same environment. For example we can launch sbt shell and then launch server or run unit tests from the shell. 
This change should have no affect on current developer workflows. Running `bin/run-dev` will still launch civiform server as it does today. 
This PR moves `entrypoint.sh` from root directory to `server` as that file makes sense within the context of server. Additionally it's no longer used as default entry point for the image. Instead we call it directly in `docker exec`. 
Issue #3727

Refactor run-dev and sbt commands

---

server/app/views/BaseHtmlLayout.java
server/conf/application.conf
server/test/views/BaseHtmlLayoutTest.java

By default we should not be including Google Analytics and only deployments that want it need to enable it.

Remove default hardcoded google analytics id and allow it to be empty

---

server/app/views/admin/questions/QuestionEditView.java

The code base commonly uses ReadOnly to indicate uneditable things.  This renames the only use of ViewOnly to that.
All of our UI rendering classes are called View regardless of if the content is editable or not so using ViewOnly for a different use of "View" in them is confusing.

Rename only use of ViewOnly to common ReadOnly

---

server/app/models/Application.java
server/app/repository/ApplicationRepository.java
server/test/repository/ApplicationRepositoryTest.java
server/test/services/export/AbstractExporterTest.java

When an applicant answers their first question on a program application, CiviForm creates an application record for them associating them with the specific version of the program they're applying to. This application record would also get updated with the contents of the applicant's `ApplicantData` each time they answered a question. When the applicant submitted the application, CiviForm would change its status from `DRAFT` to `ACTIVE`.
This caused a bug where if Program A and Program B shared Question C and an applicant answered Question C in Program A but did not submit the application, then went to program B and changed their answer to Question C, then finally went back to Program A and submitted their application, their application to Program A would contain their original answer to …

Ensure application data consistency at submit time

---

browser-test/src/admin_program_creation.test.ts
browser-test/src/support/admin_programs.ts
server/app/views/admin/programs/ProgramIndexView.java

This updates the edit program link to go to `/blocks` which gets the last block in a program and redirects to `/edit` with the last block ID.
Updates the edit program link to go to `/blocks` which gets the last block in a program and redirects to `/edit` with the last block ID.
Fixes #3887

updates edit program link to redirect to last block

---

browser-test/src/support/config.ts
browser-test/src/support/index.ts

It is useful for staging prober tests where we don't control some sites such as auth providers and they might cause JS or network errors that don't fail test but trigger the error watcher. The main goal of brower error watcher to catch errors in civiform and that is covered well enough by browser tests.

Add flag to disable browser error watcher

---

browser-test/src/text.test.ts
server/app/assets/javascripts/main.ts

The form can be submitted only by clicking on the submit button or hitting "Enter" while focused on the button. 
Hitting "Enter" button while filling text fields or checkbox no longer triggers submission when editing a question or filling a form.
Fixes #3872

Disable "submit form on Enter" behavior

---

server/app/featureflags/FeatureFlags.java
server/app/views/AzureFileUploadViewStrategy.java
server/app/views/BaseHtmlLayout.java
server/app/views/HtmlBundle.java
server/app/views/JsBundle.java
server/app/views/admin/AdminLayout.java
server/app/views/admin/AdminLayoutFactory.java
server/app/views/admin/programs/ProgramAdministratorProgramListView.java
server/app/views/admin/programs/ProgramApplicationListView.java
server/app/views/admin/programs/ProgramApplicationView.java
server/app/views/admin/programs/ProgramIndexView.java
server/app/views/applicant/ApplicantLayout.java
server/app/views/applicant/ApplicantProgramBlockEditView.java
server/app/views/dev/IconsView.java
server/conf/application.conf
server/test/views/BaseHtmlLayoutTest.java
server/test/views/HtmlBundleTest.java

When the flag is enabled JS bundles will be served instead of individual JS files. The plan is to add the flag, flip the default value to true, ensuring that all tests pass, and wait for a release or two. After that I'll clean up the flag and the old approach.
Introduce `USE_JS_BUNDLES ` flag for controlling JS serving mode. 
Issue #3864

Add `use_js_bundles` feature flag

---

browser-test/src/file.test.ts
server/app/assets/javascripts/azure_upload.ts

During file upload on azure JS code doesn't check whether user actually chose a file which leads to the following error:
```
azure_upload.ts:44 Uncaught TypeError: Cannot read properties of undefined (reading 'type')
at AzureUploadController.attemptUpload (azure_upload.ts:44:48)
at HTMLFormElement.<anonymous> (azure_upload.ts:20:12)
```
Fixes #3896

Fix JS error during file upload on azure

---

server/app/controllers/admin/AdminProgramBlockPredicatesController.java
server/app/services/program/ProgramDefinition.java
server/test/services/program/ProgramDefinitionTest.java

Adds lookup for which questions are available for eligibility conditions for a given block.
refactors the logic used to make the same determination for visibility so that the main method effectively finds all visible questions up to and including a given block.  Visibility then looks for the questions available through the block before it, and eligibility through its block.
No-op Refactor of logic to determine which questions are available to Visibility conditions to support the in-development eligibility feature.

Refactor evaluation of Visibility questions and add getting of Eligibility questions

---

browser-test/src/support/browser_error_watcher.ts

Looks like we can't reliably get response from request objects on playwright's `requestfinished` event as those request can belong to sessions that has been closed. It's not a big deal and just means that we might not detect some corner-case failures that don't affect test success anyway. 
I noticed this error while running browser tests locally.

Ignore sporadic failures coming from browser error watcher

---

docker-compose.yml
server/app/services/cloud/aws/SimpleStorage.java
server/build.sbt
server/conf/application.conf

AWS S3 supports two styles of addressing buckets ([docs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html)). For production we use hosted-styled (recommended). For tests we've been using path-styled (not recommended). With the awssdk deps 2.18.0 update they updated underlying endpoint providers that changed our localstack setup to use hosted-styled URLs:
Instead of `http://localstack:4566/civiform-local-s3` 
It now uses `http://civiform-local-s3.localstack:4566/`
It broke tests as that new domain was not setup in Docker. This PR updates docket network and uses `civiform-local-s3.localhost.localstack.cloud` domain for localstack as it explicitly wants `localhost.localstack.cloud` ([docs](https://docs.localstack.cloud/user-guide/aws/s3/)) in order to read Host …

Update AWS java deps and change S3 setup for localstack

---

server/app/controllers/dev/FeatureFlagOverrideController.java

For browser and manual tests of applicant flows they need to set feature flags via HTTP.
The system still requires a env configuration to be set as well doesn't allow overrides for prod environments.

Remove admin restriction to allow applicant flows to set feature flags

---

server/app/services/applicant/ApplicantService.java
server/test/services/applicant/ApplicantServiceTest.java

Presumably this method tried to set the applicant ID at some point, but that is determined by the Database.

Remove unused param in ApplicantService.createApplicant()

---

server/app/featureflags/FeatureFlags.java
server/app/views/AzureFileUploadViewStrategy.java
server/app/views/BaseHtmlLayout.java
server/app/views/HtmlBundle.java
server/app/views/admin/AdminLayout.java
server/app/views/admin/programs/ProgramAdministratorProgramListView.java
server/app/views/admin/programs/ProgramApplicationListView.java
server/app/views/admin/programs/ProgramApplicationView.java
server/app/views/admin/programs/ProgramIndexView.java
server/app/views/applicant/ApplicantProgramBlockEditView.java
server/app/views/dev/IconsView.java
server/conf/application.conf
server/project/TypescriptBuilder.scala
server/test/views/BaseHtmlLayoutTest.java
server/test/views/HtmlBundleTest.java

Its default value was set to true and ran for a week in production (Seattle). No issues were raised so I consider it to be safe for the cleanup. 
Clean up USE_JS_BUNDLES flags since JS bundles have been launched. 
Issue #3864

Clean up USE_JS_BUNDLES flags

---

server/app/controllers/admin/AdminProgramBlockPredicatesController.java
server/app/controllers/dev/DatabaseSeedController.java
server/app/services/program/ProgramService.java
server/app/services/program/ProgramServiceImpl.java
server/app/views/admin/programs/ProgramBlockEditView.java
server/app/views/admin/programs/ProgramBlockPredicatesEditView.java
server/conf/routes
server/test/controllers/admin/AdminProgramBlockPredicatesControllerTest.java
server/test/services/program/ProgramServiceImplTest.java

'Visibility' was the implicit value for these routes, and when 'Eligibility' was added we created similar paths with explicit naming for those.  This makes the implicit Visibility paths explicit.
Cleaned up the edit/predicate/edit pattern in the routes too.

Explicitly name Visibility predicate routes

---

server/project/TypescriptBuilder.scala
server/webpack.config.js

We want webpack to only print errors skipping all other stats info. Having `--no-stats` hides all webpack output including error. Instead we set stats to output only errors.

Fix webpack error output

---

bin/sbt

It got broken by https://github.com/civiform/civiform/pull/3892

Fix bin/sbt

---

browser-test/src/support/index.ts

At the moment if test finished but there is an error detected then BrowserContext isn't closed properly. It leads to video not being saved or potentially other inconveniences.

Always close BrowserContext after test finishes 

---

server/app/assets/javascripts/admin_programs.ts
server/app/assets/javascripts/toast.ts

1. Remove instance variables and methods from ToastController class. All methods can be static as they don't use any state stored in class instance.
2. Change admin_programs.ts to call `ToastController.showToastMessage` static method rather than getting untyped instance from window object. 
3. Rename static variables to use UPPER_CASE as they are const.
4. Add `private` modifiers to most methods/variables.

Refactor admin_programs.ts and toast.ts

---

browser-test/.eslintrc.json
formatter/eslintrc_base.json
server/app/assets/javascripts/admin_application_view.ts
server/app/assets/javascripts/admin_applications.ts
server/app/assets/javascripts/admin_validation.ts
server/app/assets/javascripts/azure_delete.ts
server/app/assets/javascripts/azure_upload.ts
server/app/assets/javascripts/enumerator.ts
server/app/assets/javascripts/file_upload.ts
server/app/assets/javascripts/main.ts
server/app/assets/javascripts/preview.ts
server/app/assets/javascripts/questionBank.ts
server/app/assets/javascripts/radio.ts
server/app/assets/javascripts/toast.ts
server/app/assets/javascripts/util.test.ts
server/app/assets/javascripts/util.ts
server/jest.config.js
server/tsconfig.json

The main change is that accessing (calling methods or accessing properties) on nullable variables is now an error. Developer either have to explicitly check that value is not-null or add non-null assertion. For that I introduced `assert()` helper function that ensures that provided value is non-null and throws error otherwise. It required me to add it in a lot of places, mainly around `querySelector()` and `getElementById()` calls. It's quite annoying but provides extra safety. 
We can also implement something like `safeQuerySelector` described here: https://effectivetypescript.com/2020/07/27/safe-queryselector/ But I decided to go simpler, more universal approach (we'd need to have `assert()` for other cases as well).  

Enable typescript strict checks on server code

---

server/app/featureflags/FeatureFlags.java
server/conf/application.conf
server/test/featureflags/FeatureFlagsTest.java

Add `PREDICATES_MULTIPLE_QUESTIONS_ENABLED` feature flag for admin multi-question predicate UI, default to `false`.

Add feature flag

---

browser-test/src/support/browser_error_watcher.ts

Adding `try/catch` around `request.response()` didn't help. I still see errors locally sometimes and in staging prober tests. I think the reason is that the error is thrown as inside promise: the promise is rejected and that rejection is failing the tests. Promise rejections can't be caught by try/catch, instead they need to be handled in `.then()` or `.catch()`.
Ran all tests locally and nothing failed.

Rework handling of errors in BrowserErrorWatcher

---

browser-test/src/auth.test.ts

The assertion expected month and day to always be two digits, both are single digits depends on the date.

Fix browser auth test date assertion

---

server/app/services/applicant/question/MultiSelectQuestion.java
server/test/services/applicant/question/MultiSelectQuestionTest.java
server/test/views/questiontypes/CheckboxQuestionRendererTest.java

The validation error message when a user has selected too many checkboxes (more than the max number set by the program admin) says "Please select fewer than {maxNumber}". Instead, this should be: "Please select fewer than {maxNumber + 1}"
Fixes #3335

Update checkbox validation error message to include the correct number when too many selected

---

.github/workflows/build_push_ci.yaml

Use of set-output in github action is deprecated. Updating to new format. See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands.

Update set-output in github action to new format

---

server/app/repository/VersionRepository.java
server/app/services/applicant/predicate/PredicateEvaluator.java
server/app/services/program/BlockDefinition.java
server/app/services/program/predicate/AndNode.java
server/app/services/program/predicate/ConcretePredicateExpressionNode.java
server/app/services/program/predicate/LeafAddressServiceAreaExpressionNode.java
server/app/services/program/predicate/LeafOperationExpressionNode.java
server/app/services/program/predicate/OrNode.java
server/app/services/program/predicate/PredicateAddressServiceAreaNodeExtractor.java
server/app/services/program/predicate/PredicateExpressionNode.java
server/app/services/program/predicate/PredicateExpressionNodeType.java
server/app/services/program/predicate/PredicateExpressionNodeVisitor.java
server/test/repository/VersionRepositoryTest.java
server/test/services/program/BlockDefinitionTest.java
server/test/services/program/predicate/PredicateAddressServiceAreaNodeExtractorTest.java
server/test/services/program/predicate/PredicateExpressionNodeTest.java

Adds `LeafAddressServiceAreaExpressionNode` along with `BlockDefinition` methods for retrieving them.
Closes https://github.com/civiform/civiform/issues/4047 https://github.com/civiform/civiform/issues/4045

Add LeafAddressServiceAreaExpressionNode

---

.github/workflows/format.yaml

Currently we use actionsx/prettier@v2 to do some formatting. The v2 release is very old and uses the deprecated node12. The action has been updated to use node16 however there is no tagged release version. Setting to the [specific commit hash](https://github.com/actionsx/prettier/commit/e90ec5455552f0f640781bdd5f5d2415acb52f1a) here so we can keep using the action.

Use commit sha for prettier action version

---

.github/workflows/build_push_ci.yaml
.github/workflows/format.yaml

The [trilom/file-changes-action](https://github.com/trilom/file-changes-action) hasn't been updated in years. It now uses deprecated github features that will be sunset later this spring. This replaces it with [tj-actions/changed-files](https://github.com/tj-actions/changed-files) which has a thriving community around it and is being maintained.
The only difference I see in output is that each file is surrounded by double-quotes in the new action. 
**Examples**
Before with _Trilom_ `[bin/bin0341_1.txt,bin/bin0341_2.txt,bin/bin1.txt]`
After with _tj-actions_ `["bin/bin0341_1.txt","bin/bin0341_2.txt","bin/bin1.txt"]`
I've tried simple examples in an empty repository similar to how we use the list of changed files. This looks like it should do the job, but it needs to be tested in our full …

Replace abandoned file-changes-action with one that is still maintained

---

browser-test/src/admin_legacy_predicates.test.ts
browser-test/src/support/index.ts

The multiple predicates experiment changes the legacy UI in a way that fails the tests, so explicitly disable it for environments where the experiment has been enabled.

Explicitly disable the multiple predicates experiment for legacy tests

---

browser-test/src/admin_legacy_predicates.test.ts
browser-test/src/application_navigation.test.ts
browser-test/src/support/index.ts

For environments with the Predicate v2 feature enabled the legacy tests need to explicitly disable it.

Explicitly disable predicate editor v2 for environments with it on.

---

server/app/services/DateConverter.java
server/app/views/applicant/ApplicantProgramSummaryView.java
server/test/services/DateConverterTest.java

Using ZoneId.systemDefault() will show the timezone as GMT. By initializing the View with ZoneId and then calling this.zoneId, the zone is "America/Los_Angeles". This also seems to be how this is done in other files, so this seems consistent with other places where we localize a timestamp or date. 
It doesn't seem like there is currently a browser test that checks whether "previously answered state" is set correctly. I was thinking of filing a separate bug for that, but let me know if this seems in scope for this bug. 
#3379

Update timezone of previously answered on text

---

server/conf/messages
server/conf/messages.en-US

Add missing label and fix ordering/comment on others.

Add missing ariaLabel.begin to default language file

---

server/app/views/components/TextFormatter.java
server/build.sbt
server/test/views/components/TextFormatterTest.java

Avoid parsing emails as URLs in TextFormatter.
The UrlDetector library has a known issue where it does not detect emails correctly. As a result, something like "first.last@example.com" gets converted to `<a href="http://first.last">first.last</a><a href="http://example.com">example.com</a>` and "first@example.com" gets converted to `<a href="http://first@example.com">first@example.com</a>`. The library appears to be unmaintained, however, and I was unable to find a good alternative. As a workaround, this adds a check before converting a substring that was detected as a URL into a link to see if it's likely actually an email, in which case it gets parsed as plain text instead. This won't handle all cases but should fix the most common cases.
Fixes #2930.

Avoid parsing emails as URLs in TextFormatter.

---

server/app/assets/javascripts/enumerator.ts

Set focus to add button or remove button for enumerators after an enumerator entity is removed. Setting focus is important for keyboard only / screenreader users.
Accessibility - Set focus to add button or remove button for enumerators after an enumerator entity is removed.
Fixes #3566

Set focus after removing an enumerator for applicant view

---

browser-test/src/admin_application_statuses.test.ts
browser-test/src/admin_program_translation.test.ts
browser-test/src/applicant_application_statuses.test.ts
browser-test/src/civiform_admin_program_statuses.test.ts
server/app/controllers/admin/AdminApplicationController.java
server/app/controllers/admin/AdminProgramStatusesController.java
server/app/featureflags/FeatureFlags.java
server/app/services/export/CsvExporterService.java
server/app/services/export/JsonExporter.java
server/app/services/export/PdfExporter.java
server/app/views/admin/programs/ProgramIndexView.java
server/app/views/admin/programs/ProgramTranslationView.java
server/conf/application.conf
server/conf/application.dev-browser-tests.conf
server/conf/application.dev.conf
server/conf/application.test.conf
server/test/controllers/admin/AdminApplicationControllerTest.java
server/test/controllers/admin/AdminProgramStatusesControllerTest.java
server/test/featureflags/FeatureFlagsTest.java
server/test/services/export/CsvExporterTest.java
server/test/services/export/JsonExporterTest.java
server/test/services/export/PdfExporterTest.java

Makes status tracking an always on feature and removes the control to enable/disable it.
The application.conf values are maintained though have no effect, as removal will cause errors in deployments that have them configured.
Promotes the Status Tracking feature to be always available.  Exported data will now include "Status" fields if the feature had not been enabled already.
Fixes #3942

Promote status tracking to a default feature.

---

server/app/services/geo/esri/EsriClient.java
server/test/resources/esri/findAddressCandidates.json
server/test/services/geo/esri/EsriClientTest.java

Our address control uses a dropdown for state. The dropdown is configured solely as two character state abbreviations. Currently the ESRI client is returning the full name of the state. This switches it from using the field `Region` to `RegionAbbr` in the ESRI reponse. 
So going from using `Washington` to just `WA`.

Switching from using full state name to state abbreviation

---

server/app/services/geo/esri/EsriClient.java
server/test/services/geo/esri/EsriClientTest.java

Calling toString gets the value surrounded by double quotes. Switching to call asText which returns the value from the json object without being surrounded by quotes.

Call asText and not toString to get value from json

---

server/app/controllers/applicant/ApplicantProgramReviewController.java
server/app/services/MessageKey.java
server/conf/messages
server/conf/messages.en-US

This adds i18n support for the 'Error saving application' banner, which shows when an exception occurs while saving the application.
https://github.com/civiform/civiform/issues/4071

i18n for 'Error saving application' banner

---

bin/sbt
bin/vscode-setup

Previously, bin/sbt was not taking any additional arguments and passing them along to docker::dev_and_test_server_sbt_command. This meant that when vscode-setup tried running 'bin/sbt makePom', it wouldn't actually do that and it would just sit in the shell. Also, for some reason, docker compose can't seem to figure out what the 'civiform-shell' service is, even though it's defined in docker-compose.dev.yml.  However, we're just using the civiform service anyway, so this fixes the cp command to use the civiform service to copy the target directory to the local server directory so we can munge the pom file appropriately.
The title of the pull request will be used as the default release notes description. If more detail is needed to communicate to partners the scope of the PR's changes, use …

Fix vscode-setup

---

bin/build-browser-tests
bin/build-dev
bin/build-dev-oidc
bin/build-localstack-env
bin/build-prod

Somehow, formatting lists of arguments that included unescaped newlines did not previously cause the docker CLI problems but now it does. At least on linux. Unfortunately for us our shell autoformatter, [shfmt](https://github.com/mvdan/sh), removes backslashes inside array declarations, which would have been the simpler fix for this.
Instead, to appease *both* docker and shfmt, the fix here uses a format string instead of an array to hold the args, formats the docker buildx command into a format string as well, and then invokes it. I don't know why the second step was necessary instead of being able to invoke `docker buildx` directly, but attempting the latter resulted in an argument error from the docker CLI tool.
The end.
Fixes https://github.com/civiform/civiform/issues/4106

Fix image building scripts for Docker CLI on linux

---

server/app/repository/ApplicationRepository.java
server/test/repository/ApplicationRepositoryTest.java

This PR addresses this bug: https://github.com/civiform/civiform/issues/3227
The program admin UI shows all non-draft, non-deleted applications for a given program ([query](https://github.com/civiform/civiform/blob/bionj-missing-submission-time-bug/server/app/repository/ProgramRepository.java#L224-L233)), meaning all `ACTIVE` and `OBSOLETE` applications are considered submitted. This is a reasonable assumption given submitting an application updates it from `DRAFT` to `ACTIVE` and marks all other applications to the same program as `OBSOLETE`, throwing an exception if more than one `DRAFT` is found for the program ([that happens here](https://github.com/civiform/civiform/blob/main/server/app/repository/ApplicationRepository.java#L86-L123)).
However, the logic to throw an exception if …

Ensure applicant uses existing application

---

browser-test/src/admin_predicates.test.ts
browser-test/src/support/admin_predicates.ts
server/app/services/applicant/predicate/JsonPathPredicateGenerator.java
server/app/services/applicant/predicate/PredicateEvaluator.java
server/app/services/applicant/question/Scalar.java
server/app/services/geo/ServiceAreaState.java
server/app/services/program/predicate/LeafAddressServiceAreaExpressionNode.java
server/app/services/program/predicate/Operator.java
server/app/services/program/predicate/PredicateGenerator.java
server/test/services/applicant/predicate/JsonPathPredicateGeneratorTest.java
server/test/services/program/predicate/PredicateGeneratorTest.java

Evaluates `LeafAddressServiceAreaExpressionNode`s using the JsonPath library.
Fixes https://github.com/civiform/civiform/issues/4028

Evaluate address service area predicates

---

browser-test/src/support/admin_questions.ts
server/app/views/admin/questions/QuestionsListView.java

Add a confirmation modal when admins discard a question draft.
Fixes #2105

Add discard draft confirmation

---

server/app/controllers/dev/FeatureFlagOverrideController.java
server/app/featureflags/FeatureFlags.java
server/app/views/dev/FeatureFlagView.java
server/test/controllers/dev/FeatureFlagOverrideControllerTest.java

Add a proper View class for Feature Flags which includes a more exhaustive view of their values and an easy ability to toggle the value.
Default state:
With Session values:

Add a more robust UI for feature flags

---

browser-test/src/admin_predicates.test.ts
server/app/assets/javascripts/admin_predicate_configuration.ts

Fixes a bug in the multi-value predicate configure view (enabled by `PREDICATES_MULTIPLE_QUESTIONS_ENABLED` feature flag). Address service area values are specified using a `select` element, whereas all other scalar values use an `input`. Since the JS code that creates new value rows only looks for `input` elements, it didn't update the `name` attribute of the `select` for address service areas.

Fix multiple service area values bug

---

browser-test/src/landing_page.test.ts

Test added in https://github.com/civiform/civiform/pull/4205.  Was discovered that the test does not pass on Seattle staging, which uses an image build with bin/build-prod.

Fixes landing_page test when run on prod CiviForm image

---

server/app/services/MessageKey.java
server/conf/messages

Adding new strings that will be used in the address correction ui. Submitting separately to get the ball rolling on translations. Related to #4044

Adding english default strings for address correction ui

---

.github/workflows/format.yaml

Attempt at fixing occasional format action failures. The googlejavaformat-action tries to get release info differently based on if it has a github-token or not. WIthout it uses curl. Adding the token to the action here because we might be hitting the failure due to api rate limit being exceeded.
See https://github.com/axel-op/googlejavaformat-action#github-token. While their comments are specific about macOS it could still be a rate limit issue.
Example of failure
```
Run axel-op/googlejavaformat-action@v3
with:
version: 1.9
skip-commit: true
args: --replace
files: **/*.java
env:
JAVA_HOME: /opt/hostedtoolcache/Java_Zulu_jdk/11.0.10-9/x64
JAVA_HOME_11_X64: /opt/hostedtoolcache/Java_Zulu_jdk/11.0.10-9/x64
Error: TypeError: releases.find is not a function
```

Pass github token to googlejavaformat action

---

browser-test/fonts.conf
browser-test/playwright.Dockerfile

Add a fonts.conf to the browser-tests docker container. Part 1/2. 
Details:
- Part 2 is #4239 and updates the goldens.
- This is split into two parts so that the presubmits don't break, since there's an issue where they're using the old docker container for the presubmit run.
- The font used by Chromium in the browser-tests docker image did not have a full range of bolds, so bold fonts were rendered as normal weights.
- To fix this, we override the font picked by the OS for the `system-ui` font-family to be `Ubuntu`, which has a full range of bold weights.
- Additional debugging and context for why this was the best choice for the fix are in #3225.
n/a
- [n/a] Created tests which fail without the change (if possible)
- [n/a] Wrote …

Fix missing bold fonts in screenshot tests (1/2)

---

server/app/auth/CiviFormProfile.java
server/app/auth/ProfileFactory.java
server/app/auth/Role.java
server/app/auth/oidc/OidcProfileAdapter.java
server/app/auth/oidc/admin/AdfsProfileAdapter.java
server/app/auth/oidc/applicant/OidcApplicantProfileAdapter.java
server/app/auth/saml/SamlProfileAdapter.java
server/app/modules/SecurityModule.java
server/app/services/role/RoleService.java
server/app/views/applicant/ApplicantLayout.java

`Roles` represents a single role, so it should be renamed to `Role`.
In some uses like `ImmutableSet<Roles> roles`, this is especially confusing.

Rename `Roles` enum to `Role`.

---

browser-test/src/admin_predicates.test.ts
server/app/controllers/applicant/ApplicantProgramBlocksController.java
server/app/controllers/applicant/ApplicantProgramReviewController.java
server/app/views/applicant/IneligibleBlockView.java

ProgramDetails link in Applicant's Ineligible page should point to the program's external link.
ProgramDetails link in Applicant's Ineligible page should point to the program's external link.
Fixes #4240

ProgramDetails link in Applicant's Ineligible page should point to the program's external link

---

server/app/services/program/ProgramServiceImpl.java
server/test/services/program/ProgramServiceImplTest.java

Allows links to be blank, which should automatically send users to the `/programs` page when clicked.
Fixes #4188

Allow URLs to be blank as part of program creation validation.

---

server/app/controllers/applicant/ApplicantProgramBlocksController.java
server/app/controllers/applicant/ApplicantProgramReviewController.java
server/app/views/applicant/IneligibleBlockView.java

Moved the call to get the ReadOnlyApplicantProgramService towards the beginning, so its available to us later on. 
I also realized I could make the call to get applicantName in the inEligibleBlockView instead of passing it, so I did that as well.
By doing this, we're better following the development standards to implement applicant code asynchronously - https://docs.civiform.us/contributor-guide/developer-guide/development-standards#async-request-handling
#3744

Make applicant code async when showing the IneligiblePage from a submit exception

---

server/app/modules/DurableJobModule.java
server/conf/application.conf

Add DurableJobModule to the list of enabled modules, which will cause the server to poll for scheduled jobs and run them.
Fixes https://github.com/civiform/civiform/issues/4191

Enable new background job processing system

---

server/app/durablejobs/DurableJobRunner.java
server/app/models/PersistedDurableJob.java
server/conf/application.conf
server/test/durablejobs/DurableJobRunnerTest.java
server/test/models/PersistedDurableJobTest.java

Sends an email to the support staff email address or IT staff email address when durable jobs fail with no attempts remaining.
Introduces a new config var `IT_EMAIL_ADDRESS`. If set, error notifications will go there. If unset, error notifications will go to `SUPPORT_EMAIL_ADDRESS`.
Fixes [#3899](https://github.com/civiform/civiform/issues/3899)

Error notification emails for durable jobs

---

.github/workflows/auto-author-assign.yml

Github doesn't recognize `uses` directive as an action without the `@[version number]` portion

Add version ref to autoassign workflow

---

server/app/views/admin/TranslationFormView.java

Change `pre` tag to `p` tag to allow text to wrap within div.
before
after
Fixes #4233

Wrap english text on translations page

---

server/app/services/MessageKey.java
server/app/views/LoginForm.java
server/conf/messages
server/conf/messages.am
server/conf/messages.en-US
server/conf/messages.es-US
server/conf/messages.ko
server/conf/messages.so
server/conf/messages.tl
server/conf/messages.vi
server/conf/messages.zh-TW

Adds translations for the "Login" page title. References them with a new `MessageKey` `TITLE_LOGIN`.
I used a free language translation service since the translation is trivial.
First step towards #3548 - based on [Mikita's comment](https://github.com/civiform/civiform/issues/3548#issuecomment-1264087589) we should also detect users' preferred language so that we can actually localize the login page *before* they log in and select a language.

Add translations for login title

---

server/app/auth/AuthIdentityProviderName.java
server/app/auth/CiviFormProfile.java
server/app/auth/oidc/CiviformOidcProfileCreator.java
server/app/auth/oidc/OidcClientProvider.java
server/app/auth/oidc/admin/AdfsClientProvider.java
server/app/auth/oidc/admin/AdfsProfileCreator.java
server/app/auth/oidc/applicant/ApplicantProfileCreator.java
server/app/auth/oidc/applicant/Auth0ClientProvider.java
server/app/auth/oidc/applicant/GenericApplicantProfileCreator.java
server/app/auth/oidc/applicant/GenericOidcClientProvider.java
server/app/auth/oidc/applicant/IdcsApplicantProfileCreator.java
server/app/auth/oidc/applicant/IdcsClientProvider.java
server/app/auth/oidc/applicant/LoginGovClientProvider.java
server/app/auth/saml/LoginRadiusClientProvider.java
server/app/auth/saml/SamlProfileCreator.java
server/app/modules/SecurityModule.java
server/test/auth/ProfileMergeTest.java
server/test/auth/oidc/CiviformOidcProfileCreatorTest.java
server/test/auth/oidc/OidcClientProviderTest.java
server/test/auth/oidc/applicant/Auth0ProviderTest.java
server/test/auth/oidc/applicant/GenericApplicantProfileCreatorTest.java
server/test/auth/oidc/applicant/GenericOidcClientProviderTest.java
server/test/auth/oidc/applicant/IdcsClientProviderTest.java
server/test/auth/oidc/applicant/LoginGovClientProviderTest.java

Many classes in the `auth` package are confusingly named. This PR renames many of them to make it easier to read and understand code in the future.
For example, our `OidcProfileAdapter` extends pac4j's `OidcProfileCreator`, which mainly has a `Optional<UserProfile> create()` method. We should be calling our class `CiviformOidcProfileCreator` to (1) differentiate it from pac4j's and (2) more importantly, continue suggesting that it does in fact create, not adapt, profiles.
Also, implement some trivial fixes in the auth package that IntelliJ suggests
Steps towards #4280

Rename auth classes

---

server/app/auth/oidc/CiviformOidcProfileCreator.java
server/app/auth/oidc/admin/AdfsProfileCreator.java
server/app/auth/oidc/applicant/ApplicantProfileCreator.java
server/app/auth/oidc/applicant/IdcsApplicantProfileCreator.java

Remove `possiblyModifyConfigBasedOnCred` base method on `CiviformOidcProfileCreator`. This only applies to one concrete class, so it should be a helper method of that class.
Relates to #4280.

Remove `possiblyModifyConfigBasedOnCred` base method

---

server/app/repository/ProgramRepository.java
server/app/services/program/ActiveAndDraftPrograms.java
server/app/services/program/ProgramServiceImpl.java
server/test/repository/ProgramRepositoryTest.java
server/test/services/program/ProgramServiceImplTest.java
server/test/support/ProgramBuilder.java

Previously, the uniqueness validation logic for the common intake form looked at all programs. This included obsolete programs and active programs for which there was a draft, however, which meant that you couldn't actually change which program was the common intake form. This change fixes it by only checking for the common intake form among draft programs and active programs that don't have a draft.

Fix intake form uniqueness logic to look at active and draft programs.

---

server/app/repository/VersionRepository.java
server/test/repository/VersionRepositoryTest.java

Eligibility definitions need to be updated with latest question IDs for the questions they reference when new question versions are published.
Fixes https://github.com/civiform/civiform/issues/4290

Bugfix: Update eligibility definition question versions

---

server/app/services/program/predicate/PredicateDefinition.java
server/app/services/program/predicate/PredicateGenerator.java
server/app/views/admin/programs/ProgramBlockBaseView.java
server/app/views/admin/programs/ProgramBlockPredicateConfigureView.java
server/test/models/ProgramTest.java
server/test/repository/VersionRepositoryTest.java
server/test/services/program/predicate/PredicateGeneratorTest.java
server/test/views/admin/programs/ProgramBlockBaseViewTest.java

Format detection for predicates previously relied on detecting and then persisting in the database a value representing the format. This was involved in the attached bug when the value wasn't copied over to new versions of the predicate when the predicate's question version references are updated.
This bugfix removes the behavior of persisting the format in favor of programmatically detecting the format whenever needed.
Fixes https://github.com/civiform/civiform/issues/4294

Bugfix: editing multi-question predicates

---

server/app/services/program/predicate/PredicateDefinition.java

This change was intended to be included in https://github.com/civiform/civiform/pull/4296
By default, Jackson will throw an exception if it finds an unmapped JSON property when marshalling a mapped class. Since "predicateFormat" is already in some production databases, we need to tell Jackson to ignore those properties.

Ignore "predicateFormat" when loading PredicateDefinition

---

server/test/repository/ReportingRepositoryTest.java
server/test/repository/ResetPostgres.java
server/test/services/reporting/ReportingServiceTest.java

The reporting tests used `Instant.now()` as the basis for creating test dates. This caused tests to fail when it got far enough away from the month when the tests were written.

Use stubbed clock for reporting tests

---

server/app/services/geo/esri/EsriClient.java

This adds the inSR parameter to the call to Esri in `fetchServiceAreaFeatures`, which allows the endpoint to use the coordinates from address suggestions if the well known ID/spatial reference is different than the service's default. In this case the public findAddressCandidates returns 4326 by default and Seattle's service area validation endpoint is 2926 by default.

Fixes public Esri findAddressCandidates compatability with civic entity service area validation endpoints

---

browser-test/src/admin_program_creation.test.ts

This test expects the esri address correction feature to be disabled. If the feature is enabled the test fails. This explicitly makes it disabled.

Force address correction feature to be disabled

---

server/app/auth/oidc/CustomOidcLogoutRequest.java

`CustomOidcLogoutRequest` overrides `toParameters()`. The way it is done adds duplicate code for some built-in `toParameters` logic, and removes other logic that we could use, like `id_token_hint`.
This does not fix #3863, but will help when we use the param later on since pac4j adds `id_token_hint` for us [here](https://github.com/hidglobal/oauth-2.0-sdk-with-openid-connect-extensions/blob/0a7fa5785ce8ac17ac95ce5294a24c8743794a6f/src/main/java/com/nimbusds/openid/connect/sdk/LogoutRequest.java#L172).

Simplify toParameters override

---

browser-test/src/application_navigation.test.ts

Disable some address correction browser tests in non-dev environments. Should be re-enabled once we have a mock service in place. Issue to track re-enabling them is #4340

Disable some address correction browser tests in non-dev environments

---

server/app/auth/oidc/CiviformOidcLogoutActionBuilder.java
server/app/auth/oidc/applicant/LoginGovClientProvider.java

Remove state generator param from `CiviformOidcLogoutActionBuilder`. We already have it in the `OidcConfiguration`.
Progress towards #4280

Remove state generator param from CiviformOidcLogoutActionBuilder

---

bin/build-prod

Our prod image currently doesn't support arm. This causes confusion if you don't know that is the case. Adding a check and message to alert if trying to build an unsupported platform. We can remove this later when we get arm support added.

Show message and exit if trying to build prod image on Mac

---

server/app/auth/oidc/CiviformOidcLogoutActionBuilder.java
server/app/auth/oidc/CustomOidcLogoutRequest.java
server/test/auth/oidc/CustomOidcLogoutRequestTest.java

Remove unused `extraParams` from `CiviformOidcLogoutActionBuilder`.
Relates to #4280.

Remove unused `extraParams` from `CiviformOidcLogoutActionBuilder`.

---

browser-test/playwright.Dockerfile

Pin the playwright image to a specific version matching the version in the package.json file per recommendations from Microsoft.
https://mcr.microsoft.com/en-us/product/playwright/about
> It is recommended to use Docker image version that matches Playwright version. If the Playwright version in your Docker image does not match the version in your project/tests, Playwright will be unable to locate browser executables.

Pin playwright image to specific version

---

browser-test/src/application_navigation.test.ts
browser-test/src/support/admin_programs.ts
server/app/controllers/applicant/ApplicantProgramBlocksController.java
server/app/controllers/applicant/ApplicantProgramReviewController.java
server/app/models/Program.java
server/app/services/applicant/AnswerData.java
server/app/services/applicant/ApplicantService.java
server/app/services/applicant/ReadOnlyApplicantProgramServiceImpl.java
server/app/views/applicant/ApplicantProgramSummaryView.java
server/app/views/applicant/ProgramIndexView.java
server/conf/application.dev-browser-tests.conf
server/test/services/applicant/ApplicantServiceTest.java
server/test/support/ProgramBuilder.java

Updates the application logic for non-gating eligibility so that application submission is never blocked and text about the applicant not qualifying is removed.

Always allow submitting an application if eligibility is non-gating.

---

server/app/auth/oidc/admin/AdfsGroupAccessor.java
server/app/auth/oidc/admin/AdfsProfileCreator.java
server/test/auth/oidc/admin/AdfsGroupAccessorTest.java

Fixes an issue where if AD sends in a string instead of a list of groups (in the case of a single or 0 groups), we can handle it.
Previously, we could only handle:
* A list of groups returned by ADFS
Now we can handle:
* A list of groups
* A string that represents one group
* An empty string
I've sent a Docker image of commit 0ca3a7 to Cliff at Bloomington and he verified it is working correctly.
Fixes #4295

Fix crash when ADFS sends a single group

---

formatter/fmt

Updates formatter script to only format python files if there are changes to them.
Part of https://github.com/civiform/civiform/issues/2985.
Tested: build the formatter image with this change, ran with no python changes.  "No modified python files found" was printed.  I changed a python file and re-ran, python formatting was triggered.

Only format python files if they have changes

---

bin/lib/docker.sh
bin/run-browser-test-env
bin/run-browser-tests-local
browser-test/browser-test-compose.dev_local.yml
browser-test/browser-test-compose.yml
test-support/test_oidc_provider.js

This fixes several issues found with running `bin/run-browser-tests-local`.
1. Adds a `--local` flag to `bin/run-browser-test-env`, which sets `BASE_URL` to `http://localhost:9999`, which the local browser tests expect. Otherwise, upon logout, it will attempt to go to `civiform:9000` instead and fail. It also includes an additional compose file that exposes port 3390, as local tests will need to be able to talk to dev-oidc directly for redirects. Because this will conflict with `bin/run-dev`, this is not enabled by default.
2. Sets `LOCALSTACK_URL` to point to port 6645 in `bin/run-browser-tests-local`, which is what is specified in `browser-test-compose.yml`.
3. Adds the flag for starting the JVM debugger on port 9457 to allow connecting the debugger during browser tests.
4. Updates the …

Fixes for bin/run-browser-tests-local

---

browser-test/src/admin_program_creation.test.ts
server/app/views/admin/programs/ProgramBlockEditView.java

If a program is marked as the common intake form, the admin should not be able to add eligibility criteria to it.
Fixes #4386

Remove the option to set eligibility criteria from the common intake form.

---

server/app/controllers/applicant/ApplicantProgramReviewController.java

Eligibility toast shouldn't get hidden automatically. It should only get hidden if manually dismissed by applicant.
Fixes #4412

Eligibility toast shouldn't be hidden unless manually dismissed

---

server/app/controllers/applicant/ApplicantProgramReviewController.java
server/app/views/admin/programs/ProgramBlockEditView.java
server/app/views/admin/programs/ProgramBlockPredicatesEditViewV2.java
server/app/views/admin/programs/ProgramIndexView.java
server/app/views/admin/programs/ProgramStatusesView.java
server/app/views/admin/questions/QuestionEditView.java
server/app/views/components/ToastMessage.java

Toasts should default to remain open, instead of auto hiding after 3 seconds.
Toasts should default to remain open, instead of auto hiding after 3 seconds.
Fixes #4433

Toasts should not auto hide by default

---

server/app/services/applicant/ApplicantService.java
server/app/services/export/CsvExporterService.java
server/app/views/admin/programs/ProgramApplicationListView.java
server/test/services/applicant/ApplicantServiceTest.java

See #4414 for a description of the bug. The code was using applicant.applicantData() instead of application.applicantData() in some places, causing the applicant's latest answers to be evaluated for eligibility rather than their answers on the specific application.
Fixes #4414

Evaluate eligibility based on application rather than latest applicant data

---

server/app/auth/CiviFormProfile.java
server/app/controllers/admin/AdminProgramController.java
server/app/controllers/applicant/ApplicantProgramBlocksController.java
server/app/controllers/applicant/ApplicantProgramReviewController.java
server/app/featureflags/FeatureFlags.java
server/app/views/LoginForm.java
server/app/views/admin/programs/ProgramBlockEditView.java
server/app/views/admin/programs/ProgramFormBuilder.java
server/app/views/admin/programs/ProgramIndexView.java
server/app/views/applicant/ApplicantProgramSummaryView.java
server/app/views/applicant/ProgramIndexView.java
server/app/views/components/ProgramCardFactory.java
server/test/featureflags/FeatureFlagsTest.java

A follow-up to #4437. To further simplify the feature flag codebase and remove duplication, we remove all `getXEnabled()` style methods here.
Note we leave `isAdminReportingUiEnabled()` for a future PR as this is slightly more complex.

Remove FeatureFlag per-flag methods

---

server/app/controllers/applicant/ApplicantProgramBlocksController.java

Hotfix for `isProgramEligibilityConditionsEnabled()` call still in repo after #4447. Not clear how this was able to be submitted.

Hotfix: Fix flag method

---

browser-test/src/admin_program_settings.test.ts
browser-test/src/support/admin_programs.ts
server/app/views/admin/programs/ProgramIndexView.java

The only setting available currently is for non-gating eligibility, but eligibility criteria can't be set for the common intake form. So, this hides the settings link to avoid confusion.

Hide settings link for common intake form.

---

server/test/durablejobs/DurableJobRunnerTest.java

We will temporarily disable the equality check on `runCount` as it seems to be non-deterministic and can cause GitHub Actions to fail on PRs unrelated to this.

Remove `runCount` check

---

server/app/featureflags/FeatureFlag.java
server/app/views/LoginForm.java
server/conf/helper/feature-flags.conf

This PR adds a feature flag for the upcoming Login Form changes that are part of #4366. Since this change will significantly overhaul the login page, it's best to put it behind a flag we can easily turn off.
None.
Relates to #4366.

Add Feature Flag for New Login Form

---

server/app/featureflags/FeatureFlags.java
server/app/views/admin/AdminLayout.java
server/app/views/dev/FeatureFlagView.java

A follow up to #4447 where we remove the final helper method for flags. Since we don't want to check the request for session overrides for Admin UI, we allow the request to be null in `getFlagEnabled()`.

Remove `isAdminReportingUiEnabled()`

---

.github/workflows/pr_env_var_docs.yaml
bin/env-var-docs-check-vars
bin/env-var-docs-run-tests
env-var-docs/README.md
env-var-docs/check_vars_documented.py
env-var-docs/check_vars_documented_test.py
env-var-docs/parser-package/src/env_var_docs/errors_formatter.py
env-var-docs/parser-package/tests/errors_formatter_test.py
env-var-docs/run_regex_tests.py
env-var-docs/run_regex_tests_test.py
formatter/fmt
server/conf/application.conf
server/conf/env-var-docs.json
server/conf/helper/feature-flags.conf

Followup to https://github.com/civiform/civiform/pull/4225.  Adds the env-var-docs.json documentation file and the scripts that ensure it has all the proper variables and that any provided regex_tests pass.

Add env-var-docs.json and PR automation scripts

---

bin/fmt
formatter/fmt
formatter/formatter.Dockerfile

Adds the ability to override the diffbase when running `bin/fmt` by passing in a `-d <diffbase>` flag
Sometimes there are a lot of diffs between your local changes and `origin/main`, which causes `bin/fmt` to format extra files unnecessarily. There's a workaround of rebasing before running the script, but this gives you more control since it also allows the diffbase to be a specific commit. For example, you could use this to just run the formatter on your most recently modified files after a code review. See https://github.com/civiform/civiform/issues/2985#issuecomment-1472559643 for full context.
Note that with the current implementation there are some ways this could be misused, e.g. if you run `bin/fmt -d --help`, it will think that `--help` is the diffbase and this won't work. This is …

Add option to customize the diffbase for bin/fmt.

---

browser-test/src/application_navigation.test.ts
browser-test/src/support/applicant_questions.ts
server/app/views/ApplicationBaseView.java
server/app/views/applicant/AddressCorrectionBlockView.java

Added an override method for `renderPreviousButton` so that when the user clicks "Previous" it takes them back to the address entry page, and not to the previous question.
Before:
https://user-images.githubusercontent.com/24319951/226769050-a304315b-791c-4243-8b70-b2d3361286f5.mov
Now:
https://user-images.githubusercontent.com/24319951/226769068-497216d0-4237-4948-a81b-5153cb625c25.mov
Fixes [#4442](https://github.com/civiform/civiform/issues/4442)

Address correction - previous button returns to address entry screen

---

docker-compose.yml

The latest version of the localstack image broke file uploads during tests. It appears to be due to some networking changes (https://github.com/localstack/localstack/commit/02c9b8ff2d0e6c38ae6f32f5dd44fdd33f4c4f99). Others are also having networking issues with this image. If it doesn't get resolved, we'll dig deeper to figure out how to unpin this.

Pin localstack image to 1.4.0

---

browser-test/browser-test-compose.yml
docker-compose.dev.yml
server/app/featureflags/FeatureFlag.java
server/app/views/admin/AdminLayout.java
server/conf/env-var-docs.json
server/conf/helper/feature-flags.conf

The reporting page has been available behind the `CIVIFORM_ADMIN_REPORTING_UI_ENABLED` feature flag for a few weeks. Feedback has been positive so we are removing the feature flag and enabling it for all deployments.

Enable reporting page for all deployments

---

localstack/localstack.Dockerfile

This also pins localstack to 1.4.0 for the creation of our localstack image that includes nginx in the container.

Pin localstack to 1.4.0 in our localstack dockerfile

---

server/app/controllers/applicant/ApplicantProgramsController.java
server/app/services/applicant/ApplicantService.java
server/test/controllers/applicant/ApplicantProgramsControllerTest.java
server/test/services/applicant/ApplicantServiceTest.java

The default program details link on the applicant program index view was broken because the common intake form was excluded from the list of programs used to generate the link.
Fixes #4480

Fix broken program details link for Common Intake Form.

---

server/conf/messages.am
server/conf/messages.en-US
server/conf/messages.es-US
server/conf/messages.ko
server/conf/messages.so
server/conf/messages.tl
server/conf/messages.vi
server/conf/messages.zh-TW

Removes comments and whitespace, and alphabetizes lines in non-primary (not `messages`) messages files. `conf/MessagesTest.java` in the base branch enforces that no keys were lost in this process.
Although this review diffs against `mzetune/messages-test`, I will merge this PR into `main` once that base is merged in upon approval of #4516.
* While we would like to enforce this in `MessagesTest.java`, it is not possible because the Java `Properties` class reads in the keys into a HashMap. So we alphabetize them now and can maintain this on a best-effort basis.

Clean up `messages` files

---

.github/workflows/tests.yaml
.github/workflows/tests_skip.yaml
bin/run-browser-tests-ci-batch

This should improve our browser test runtime which has been taking upwards of 30 minutes on some PRs. We simply parallelize with 10 actions instead of 4.

Update browser test batch count to 10

---

server/app/services/program/ProgramServiceImpl.java
server/test/services/applicant/ApplicantServiceTest.java

Because some of the programs are not in the active version, and we need to sync the questions for each program to calculate eligibility state, we must sync each program with a version it is associated with. This is a quick fix to utilize the ReadOnlyVersionedQuestionService instead of the ReadOnlyCurrentQuestionService.
Fixes https://github.com/civiform/civiform/issues/4507

Temporary fix for program index page

---

browser-test/src/support/index.ts

Prober tests have been [consistently failing on AWS staging deploys](https://github.com/civiform/civiform-staging-deploy/actions/runs/4556703251) because of an issue related to submitting applications. This PR bumps the timeout of tests to 8 seconds to unblock staging deploys. 
See latency spikes for the submit action in [this Grafana dashboard](https://g-f50cfd0cff.grafana-workspace.us-east-1.amazonaws.com/d/p5kGWLV4z/civiform-server?orgId=1). Spikes have not passed 8 seconds.

bumped test timeout to 8 seconds

---

server/test/conf/MessagesTest.java

Previously in #4516, we only tested that all keys in `messages` appeared in other messages files. Now, we test that all keys are exactly the same in all files, except for the `IGNORE_LIST`.
The new error message looks something like this:
`[error] Test conf.MessagesTest.messages_keysInPrimaryFileInAllOtherFiles(conf/messages.so) [4] failed: org.junit.ComparisonFailure: [content.submittedDate] found in primary language file but not in conf/messages.so. Add these keys to conf/messages.so or to the ignore list in conf.MessagesTest to resolve this issue.`
`[error] [content.requiredFieldsAnnotation] found in conf/messages.so file but not in primary language file. Add these keys to primary language file or to the ignore list in conf.MessagesTest to resolve this issue.`
Fixes …

Test full key equality in `MessagesTest.java`

---

server/app/controllers/admin/AdminProgramBlockPredicatesController.java
server/app/services/program/EligibilityNotValidForProgramTypeException.java
server/app/services/program/ProgramService.java
server/app/services/program/ProgramServiceImpl.java
server/test/services/program/ProgramServiceImplTest.java

Fix for #4512.
1. Clears eligibility conditions when a program is set as the common intake form.
2. Adds some safeguards when adding eligibility conditions to make sure that they're not being set on the CIF -- there's no UI for this so it shouldn't ever happen, but just to be safe.
3. Adds a test for adding eligibility conditions in general since there was none.
Fixes #4512

Remove eligibility criteria for the common intake form.

---

browser-test/src/application_navigation.test.ts

This test has been flaking, [waiting for the popup event to fire](https://github.com/civiform/civiform/actions/runs/4557075631/jobs/8038245538). The problem is that the click event to open the popup was happening before the listener waiting for the popup event was registering, resulting in a race condition between the two. This PR registers the listener for the event before clicking the element to fire it, ensuring a consistent ordering of listener registration and event firing.
Confirmed fix by running the test 10x in a row with `bin/find-flakey-browser-tests -t src/application_navigation.test.ts`
Contributes to https://github.com/civiform/civiform/issues/4217

Listen for popup event before clicking to fire it

---

.github/workflows/generate_env_var_docs_markdown_for_release.yaml
bin/env-var-docs-generate-markdown
env-var-docs/generate_markdown.py

Fixes https://github.com/civiform/civiform/actions/runs/4577666227
```
[Invalid workflow file: .github/workflows/generate_env_var_docs_markdown_for_release.yaml#L13](https://github.com/civiform/civiform/actions/runs/4577666227/workflow)
The workflow is not valid. .github/workflows/generate_env_var_docs_markdown_for_release.yaml (Line: 13, Col: 9): Required property is missing: type
```
Tested: https://github.com/civiform/civiform/actions/runs/4578474596/jobs/8085130230

Add missing type field in generate markdown action

---

browser-test/src/admin_predicates.test.ts

Based on #4217, `admin_predicates.test.ts` has been known to be flaky. Unfortunately, running `bin/find-flakey-browser-tests -n 5 -t src/admin_predicates.test.ts` does not expose the flakiness on my local machine.
However, this is the same problem we observed in `application_navigation.test.ts`, so apply the same exact fix as in #4539; hopefully it will do the trick.
Relates to #4217

Fix flakiness in `admin_predicates_test.ts` by waiting for the popup before clicking a link

---

server/app/controllers/applicant/ApplicantProgramBlocksController.java
server/app/services/applicant/ApplicantService.java
server/app/services/applicant/question/AddressQuestion.java
server/test/services/applicant/question/AddressQuestionTest.java

Allows re-triggering address validation if the user makes a change to their address. The corrected, lat, long, and wellKnownId values are reset, which clears the flow to be picked up as normal by the address correction process.
Fixes #4310

Re-trigger address validation upon change to address

---

bin/run-browser-tests-ci-batch

There's a bug in `bin/run-browser-tests-ci-batch`. When the `len(tests)` is a multiple of the `BATCH_SIZE`, the last batch does not get any tests assigned to it. In other words, `batch_contents` is empty.
This would not be a big deal except for this code:
```
shell_command = ["./bin/run-browser-tests-ci"] + batch_contents
subprocess.run(shell_command, check=True)
```
which would run `./bin/run-browser-tests-ci` alone if `batch_contents` were empty, running all tests. In this PR, we skip running the command if `batch_contents` is empty.

Fix batch test logic

---

server/app/views/ViewUtils.java
server/app/views/admin/programs/ProgramBlockEditView.java

This adds a "Learn more" link to the address correction tooltip when AC is not enabled, pointing to the docs page that describes how to enable it. It also reduces the top margin to zero in this case so that the tooltip doesn't disappear when a user mouses away from the tooltip icon to go to click the link.
Fixes https://github.com/civiform/civiform/issues/4473

Add "Learn more" link to address correction tooltip

---

bin/run-browser-tests-ci-batch

This cleans up the `bin/run-browser-tests-ci-batch` script to:
* Modularize logic in functions
* Ensure that each GitHub runner participates in running tests.
Prior to this PR, if there were 45 tests and 10 runners, we would calculate the tests per runner as `batch_size = 45 // 10 = 5`. The first 9 runners would take 5 tests each, and the **10th runner would get none**.
Now, we assign a test to a given runner `N` if the index of the test index `i` satisfies the condition `i % BATCH_COUNT == N - 1`. For example if there are 45 tests and 10 runners,
* The "0th" runner will get tests 0, 10, 20, 30, and 40
* The "1st" runner will get tests 1, 11, 21, 31, 41
* ...
* The "8th" runner will get tests 8, 18, 28, 38
* The "9th" runner will get tests 9, 19, 29, 39
[Paste of all tests per batch after …

Evenly distribute tests in `bin/run-browser-tests-ci-batch`

---

server/app/controllers/admin/AdminProgramController.java
server/app/services/program/ActiveAndDraftPrograms.java
server/app/services/program/ProgramService.java
server/app/services/program/ProgramServiceImpl.java
server/test/services/program/ProgramServiceImplTest.java

Create a version of ActiveAndDraftPrograms that doesn't load the question data. This is called to load the CiviForm admin program index page, but we don't need the questions when we load the programs there.
This makes the page load ~150 ms, which is over a 10X improvement.
This change reduces the number of database calls for an index page with 31 programs from [671](https://docs.google.com/document/d/13FqPvA1yUoEuCw8DNAMEalM2wq8eCUU1DsSFOUBbRlM/edit) to [14](https://docs.google.com/document/d/1JHvo17lyPmRRQ_EyYsqKdNgUsfoJ0-IiPmy2A11R6Jo/edit).
Improve load time of the CiviForm admin index page
Fixes #4608

Limit number of calls on program admin index page

---

.github/workflows/tests_skip.yaml

This adds the run_typescript_unit_tests job to the test skip workflow. Currently the test skip route is getting blocked because of that new test is missing.

Adding job to handle typescript tests

---

bin/stop-dev

Running bin/run-dev starts all the needed containers. When running bin/stop-dev the localstack/azurite container was not stopping.

Set stop-dev script to stop localstack/azurite

---

.github/ISSUE_TEMPLATE/oncall-rotation.md

Update the year in the oncall rotation template from 2022 to 2023

Update the year in the oncall rotation template

---

browser-test/src/applicant_application_index.test.ts

We check the regex for `dev-oidc`, but this is a mistake because it varies between environments. Avoid checking the URL. Originally appeared in #4619 
Fixes issue related to #4619.

Hotfix for Seattle staging

---

server/app/views/admin/AdminLayout.java

For program admins, the Programs header link should link to the Program Admin's programs page, not the admin's program page.
- [n/a] Added the correct label: < feature | bug | dependencies | infrastructure | ignore-for-release >
- [n/a] Created tests which fail without the change (if possible)
- [n/a] Manually tested at 200% size
- [n/a] Manually evaluated tab order
Fixes #4643

Fix program admin header link

---

bin/fmt

The formatter code passes in the path to the code to docker. This would work fine if the code is cloned in the more common way with `git clone` and then selecting the active branch.
However if the repository were cloned as a bare repository and branches added as a separate `git worktree` the formatter wouldn't have access to the git repository metadata and would thus fail. This change checks if on a worktree or not and passes in the path to the git metadata if needed.

Update bin/fmt to Handle Git Worktrees

---

server/app/views/admin/programs/ProgramFormBuilder.java
server/app/views/admin/questions/QuestionEditView.java
server/app/views/components/FieldWithLabel.java
server/app/views/components/SelectWithLabel.java
server/app/views/questiontypes/AddressQuestionRenderer.java
server/app/views/questiontypes/ApplicantCompositeQuestionRenderer.java
server/app/views/questiontypes/ApplicantQuestionRendererImpl.java
server/app/views/questiontypes/ApplicantSingleQuestionRenderer.java
server/app/views/questiontypes/CheckboxQuestionRenderer.java
server/app/views/questiontypes/CurrencyQuestionRenderer.java
server/app/views/questiontypes/DateQuestionRenderer.java
server/app/views/questiontypes/DropdownQuestionRenderer.java
server/app/views/questiontypes/EmailQuestionRenderer.java
server/app/views/questiontypes/EnumeratorQuestionRenderer.java
server/app/views/questiontypes/FileUploadQuestionRenderer.java
server/app/views/questiontypes/IdQuestionRenderer.java
server/app/views/questiontypes/NameQuestionRenderer.java
server/app/views/questiontypes/NumberQuestionRenderer.java
server/app/views/questiontypes/PhoneQuestionRenderer.java
server/app/views/questiontypes/RadioButtonQuestionRenderer.java
server/app/views/questiontypes/TextQuestionRenderer.java

Set aria-required for required questions to help screen reader users be able to tell which questions are required. The file upload question type is an exception since it doesn't have any non-hidden input tags to be able to set the aria-required attribute.
The html required attribute was proposed as another solution here, but that causes the browser to show a built-in "Please fill out this field" tooltip on form submit. We already do our own validation, so I'm using aria-required to avoid side effects on the UI.
Fixes #3955

Set aria-required for required questions.

---

server/app/views/components/ButtonStyles.java
server/app/views/style/AdminStyles.java

The second step towards removing button styles in `AdminStyles` - we want all button styling for both applicants and admins to be in `ButtonStyles`.
Here, we set `AdminStyles.SECONDARY_BUTTON_STYLES` to a new style, `ButtonStyles.OUTLINED_WHITE_WITH_ICON`. In a future PR we will remove the former variable altogether.
None.
None.

Replace `AdminStyles.SECONDARY_BUTTON_STYLES` with new `ButtonStyles.OUTLINED_WHITE_WITH_ICON`

---

server/app/views/admin/TranslationFormView.java
server/app/views/admin/apikeys/ApiKeyIndexView.java
server/app/views/admin/apikeys/ApiKeyNewOneView.java
server/app/views/admin/programs/ManageProgramAdminsView.java
server/app/views/admin/programs/ProgramAdministratorProgramListView.java
server/app/views/admin/programs/ProgramApplicationListView.java
server/app/views/admin/programs/ProgramApplicationView.java
server/app/views/admin/programs/ProgramBaseView.java
server/app/views/admin/programs/ProgramBlocksView.java
server/app/views/admin/programs/ProgramFormBuilder.java
server/app/views/admin/programs/ProgramIndexView.java
server/app/views/admin/programs/ProgramPredicatesEditViewV2.java
server/app/views/admin/programs/ProgramStatusesView.java
server/app/views/admin/questions/QuestionConfig.java
server/app/views/admin/questions/QuestionEditView.java
server/app/views/admin/questions/QuestionsListView.java
server/app/views/admin/ti/EditTrustedIntermediaryGroupView.java
server/app/views/admin/ti/TrustedIntermediaryGroupListView.java
server/app/views/components/CreateQuestionButton.java
server/app/views/components/ProgramCardFactory.java
server/app/views/components/QuestionBank.java
server/app/views/style/AdminStyles.java

The last change for moving Admin button styles to `ButtonStyles.java`. Inlines the usages of `AdminStyles.x` to the appropriate `ButtonStyles` vars and deletes the `AdminStyles` ones.
None.
None.
None.

Inline `ButtonStyles` from `AdminStyles`

---

.github/workflows/tests.yaml
.gitignore
browser-test/src/support/index.ts

Currently if you run screenshot tests and there are failures, we store the diffs but not the new screenshot. The only way to update the accepted screenshots is to run the browser test again with "-u". Sometimes it would be useful to just be able to grab the updated screenshots directly rather than having to run the tests a second time. For example, if you see a test failing in CI and want to accept the screenshot without running the browser test environment and running the test locally.
Unfortunately the library names the updated screenshot with a "-received" suffix and doesn't allow you to change this, so you'll have to rename the screenshots manually. I'm going to look into ways to make this easier in a follow up.

Store updated snapshots from running screenshot tests.

---

server/app/views/admin/programs/ProgramIndexView.java
server/app/views/components/ButtonStyles.java

Allows dropdown buttons to be non-rounded to stay consistent with the previous style, to address #4688.
* Decided this wasn't necessary; feel free to push back.
None.
Fixes #4688

Add new `CLEAR_WITH_ICON_FOR_DROPDOWN` button style for dropdowns

---

server/conf/helper/auth.conf

The ADFS discovery URIs were hard-coded to default to Seattle. I've updated Seattle's deployment to pass in the values now so we can remove these.
The app still loads on localhost after removing them. Any deployment other than Seattle should have already been setting these as environment variables otherwise those auth options shouldn't be working.
Fixes #4683

Removing Hard-coded Seattle Discovery URIs

---

renovate.json

Partial matches with matchPaths is deprecated. Switching to their minimatch glob pattern.
https://docs.renovatebot.com/configuration-options/#matchpaths

Use minimatch glob pattern for renovate matchPaths

---

renovate.json

Have Renovate group updates for the amd64 and ARM releases of the JRE/JDK. The goal is to try to keep them updated together in a single PR if they release at the same time.
This also sets the allowed version to stay below version 12 until we can and are ready to move to a newer major version of Java.

Group jdk/jre dependency updates and enforce max version

---

server/app/featureflags/FeatureFlag.java

Add link to FeatureFlag class. This will help us remember to pipe flags through the deploy system.

Add link to FeatureFlag class

---

server/app/auth/ApiAuthenticator.java
server/app/auth/ClientIpType.java
server/conf/application.conf
server/conf/env-var-docs.json

We currently use [WebContext.getRemoteAddr](https://github.com/civiform/civiform/blob/main/server/app/auth/ApiAuthenticator.java#L117) to determine the remote IP address when authenticating API requests. When CiviForm is deployed on AWS, this value will refer to internal AWS resources (such as load balancers) rather than the actual API client IP address.
When CiviForm is deployed in AWS it should instead refer to the [X-Forwarded-For](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For) header for retrieving the client's IP address.
Deploy system PR for setting the value in AWS: https://github.com/civiform/cloud-deploy-infra/pull/165
Fixes https://github.com/civiform/civiform/issues/4775

Resolve HTTP client IP addresses by CLIENT_IP_TYPE

---

bin/build-prod

Includes a link in the bin/build-prod warning message to the issue tracking adding Arm support to the prod image build.

Add link to bin/build-prod warning message

---

server/app/views/components/Modal.java

In `Modal.java`, we use `AutoValue` [stepped builders](https://github.com/google/auto/blob/main/value/userguide/builders-howto.md#-create-a-step-builder) to enforce inclusion of required properties at compile-time. I originally forgot to include the title, even though AutoValue is enforcing them at runtime anyways.

Make Modal title required at compile-time

---

otel-config.yaml

We're noticing issues with the metrics writer when using non-default aws region (us-east-2)
Saw that some configuration has changed with OpenTelemetry (see https://aws-otel.github.io/docs/sigv4), so I'm thinking maybe that could be it.
Update OpenTelemetry config
#4789

Update OpenTelemetry setup

---

server/app/views/applicant/ApplicantLayout.java

Previously, the entity logo would be stretched thin on mobile devices. This PR fixes that.
I'm thinking of making some simple mobile tests, just for the landing page and perhaps 1-2 other mission-critical pages, and putting it in a fast follow-up to this PR. I've noticed we (often me) neglect mobile views because of forgetting to check on them when testing so a few screenshots would be a great value add and easy to create.
Fixes logo rendering on mobile
- [n/a] Created tests which fail without the change (if possible)
No new features
Fixes #4796

Make entity logo not stretch on mobile

---

server/app/services/program/ProgramDefinition.java
server/test/services/program/ProgramDefinitionTest.java

Before this change, there was a bug in which the list of questions eligible for a block's visibility predicates would be incorrect after blocks had been reordered. The `getAvailableVisibilityPredicateQuestionDefinitions()` was assuming that the block IDs were in order, but after blocks are reordered or removed the IDs no longer correspond to the block indices.

Fix visibility predicates questions bug.

---

server/app/auth/CiviFormProfileMerger.java
server/test/auth/CiviFormProfileMergerTest.java

This PR avoids merging a guest with a user logging in if the guest has no submitted applications. This resolves a bug where if `BYPASS_LOGIN_LANGUAGE_SCREENS` is set, a TI creates an applicant, and the applicant later logs in to CiviForm with the same email, then a duplicate applicant will be created.
Before the login changes, this wasn't a possibility because users would see the login screen first, and directly log in with their email that matches the one the TI used. Now, since they start as a guest upon loading CiviForm, this issue in the merging logic is manifesting.
None.
- `CiviFormProfileMergerTest.java` is updated to account for that fact that we should not merge guests with no applications. 
- There are browser tests are in …

Fix guest merge logic

---

server/app/controllers/applicant/ApplicantInformationController.java
server/test/controllers/applicant/ApplicantInformationControllerTest.java

**Apparently**, there is a difference between a language code and short language string itself. We've been retrieving the language string (like `es`) instead of the language code (like `es-US`).
None.
None.
None.

Store language code instead of language on initial page load

---

bin/pull-image

This was skipping if you had USE_LOCAL_CIVIFORM set at all making overriding back to 0 impossible. Now it will only skip if the env variable is set to 1.

Make bin/pull-image better handle USE_LOCAL_CIVIFORM

---

server/app/controllers/HomeController.java

Takes TIs directly to their dashboard instead of the programs index page. Previously, we would take TIs to the programs index page, and this causes confusion as they often apply for programs under their own account instead of their managed users. See #4816
Takes TIs directly to their dashboard instead of the programs index page.
1. Create a new user `myuser` in the test environment.
2. Set `member_of_group_id` with `UPDATE accounts SET member_of_group_id = 1 WHERE id = 123;`
3. Log in as `myuser` and expect to be taken directly to TI dashboard.
- Not possible to unit test this behavior directly, as our test helper `loginAsTrustedIntermediary` uses the fake admin login, which is not the same as a true TI. The other conditional routes in `HomeController.index()` aren't unit tested for this …

Take TIs directly to their dashboard instead of the programs index page

---

.github/workflows/build_push_ci.yaml
.github/workflows/pr_server.yaml
.github/workflows/pr_server_skip.yaml
.github/workflows/tests.yaml
.gitignore
bin/build-mock-web-services
bin/pull-image
docker-compose.dev.yml
docker-compose.yml
formatter/fmt
mock-web-services/README.md
mock-web-services/app.py
mock-web-services/esri/__init__.py
mock-web-services/mock-web-services.Dockerfile
mock-web-services/requirements.txt
mock-web-services/webservice/__init__.py
server/app/modules/EsriModule.java
server/conf/application.dev.conf
server/conf/application.test.conf
server/conf/helper/esri.conf
test-support/prod-simulator-compose.yml

Adding new container for development time use to provide mock web service endpoints, such as for ESRI. It's able to deal with other possible endpoints in the future so we don't have to make multiple different containers.
It's a very light Flask app that just serves up specific json responses based on a handful of known inputs. I built it to mimic that FakeEsriService.java file so they can be used interchangeably. Everything is plumbed into the build with a container already.

Adding new container for mock web services

---

bin/pull-image
docker-compose.dev.yml

Making sure to correctly tag mock-web-service in docker
The main problem was that I forgot to tag the image after pulling it. I'm making a switch to the docker-compose.dev.yml back to it's prior value. The reason I'm doing so is because the rest of the dev compose file looks for the dash tagged version whereas the docker-compose.yml version runs the one directly from docker hub.
It's a nuance I'm not 100% certain I understand other than for overriding, but seems important to maintain without knowing if there would be side effects.
If anyone wants to try it before merge you'll want to remove any running containers and images based on the mock web services. Then run `USE_LOCAL_CIVIFORM=0 bin/run-dev`. I've tried different combos of having and not having the image already and no longer get …

Making sure to correctly tag mock-web-service in docker

---

browser-test/src/program_deep_link.test.ts
server/app/controllers/applicant/ApplicantProgramReviewController.java
server/app/controllers/applicant/RedirectController.java
server/app/views/components/Modal.java

In #4859, we introduce an issue where logging in to an existing account after going to a program slug breaks CiviForm because the redirect link is in the form `BASE_URL/applicants/123/programs/456`. Now, we redirect the user to the original program slug itself so there is no coupling with the applicant ID.
None.
- Validated the test fails when the source code changes are reverted.
None.
Fixes #4856

Fix redirects when users go to program slugs

---

server/test/durablejobs/DurableJobRunnerTest.java
server/test/support/TestRetry.java

DurableJobRunnerTest fails occasionally, probably due to a threading issue. I've been unable to figure out why exactly as I've been unable to reproduce the failure on my local machine. It does not take long to run and it's somewhat rare for it to fail so I propose re-running automatically to prevent the annoyance of re-running the entire JUnit suite in github when it flaps.

Retry DurableJobRunnerTest up to 5x on failure

---

server/conf/i18n/transifex.yml

Adds `transifex.yml`, which configures how Transifex will recognize our `messages` files. See [Transifex's help article](https://help.transifex.com/en/articles/6265125-github-via-transifex-ui#h_b827747da8) on GitHub.
None.
- Tested manually on Transifex UI:
- <img width="662" alt="image" src="https://github.com/civiform/civiform/assets/30369272/8f475a6b-8556-4d9c-87bd-f1213d31af99">
None.
None.
Relates to #4891.

Add `transifex.yml`

---

server/conf/helper/feature-flags.conf

Sets the flag that enables the feature to allow publishing a single program at a time to true by default. Will wait for #4882 to be merged before merging this.
After this change, you will be able to publish a single program's draft instead of only being able to publish all programs and questions at the same time. If the program has any draft questions, those questions will also be published. If the draft questions are also used by other programs, however, the program will not be able to be published individually.
You can find this feature by clicking on the dropdown menu for a draft program to see the new "Publish program" button.
Fixes #1589

Enable individual program publishing by default.

---

server/app/views/admin/programs/ProgramIndexView.java
server/test/repository/VersionRepositoryTest.java

Previously, the publish button was only shown if there was at least one draft program. This meant that questions could not be published unless you first created a draft of a program. The main case where this is a problem is when archiving questions that are no longer used in programs. You'd have to edit a program if you were trying to archive questions just so that you could publish the change.
The functionality to publish questions already existed on the backend, the button was just hidden. I added a test for that anyway to validate the behavior since it's being exposed now.
Fixes #4868

Allow publishing draft questions when there are no draft programs.

---

server/test/conf/MessagesTest.java

The current `MessagesTest` checks to make sure that all keys in `messages` are present in all foreign language files.
We can't keep this check in as-is, because in the new [internationalization process](https://docs.civiform.us/contributor-guide/developer-guide/internationalization-i18n#internationalization-for-application-strings), we allow developers to insert strings into `messages` and wait for Transifex to update `messages.xx` files itself. That means `MessagesTest` would break until Transifex adds the translations.
Instead, we check that every key in the *foreign language file* is in the primary language file. While a subtle change, it still helps us check that Transifex is not making any errors in its pull requests.
None.
-  Extended the README / documentation, if necessary
- …

Allow keys in `messages` to not be present in foreign language `messages.xx` files

---

server/conf/i18n/messages

We are no longer going to use the [Google Sheet](https://docs.google.com/spreadsheets/d/1x9xq-X61Gev2c470dPYe69tzI4azLTerZu-jfzFHmTE/edit?resourcekey=0-6T7y1Mv3Rr_u1rkmhGCeuQ#gid=276759783) for translations. In this PR, we move the last remaining in-progress keys, `error.internalServerTitle` and `error.internalServerDescription`, and deprecate the Google Sheet.
These keys will appear on Transifex as untranslated upon submission of this PR
None.
None.
None.

Add remaining translations keys from Google Sheet

---

server/app/controllers/admin/AdminApiKeysController.java
server/app/services/apikey/ApiKeyCreationResult.java
server/app/services/apikey/ApiKeyService.java
server/app/views/admin/apikeys/ApiKeyCredentialsView.java
server/test/services/apikey/ApiKeyServiceTest.java

Adds API key username and password to API key confirmation screen, to enable clients that require a username/password for Basic Auth, instead of a single token.
Adds API key's username and password to the API key confirmation screen. This enables support for API clients that require a username and password for Basic Auth.
Partially completes #4861

Display API username/password along with key

---

.github/reviewers.yml
.github/workflows/auto_request_review.yml
server/conf/i18n/messages.tl

Creates a [GitHub Action](https://github.com/marketplace/actions/auto-request-review) that automatically requests a review from CiviForm/Developers for any Transifex PRs. Also adds me, for now, so I can monitor this for a bit while we get used to using it.
None.
None.
None.

Automatically assign reviewers to Transifex PRs

---

.github/reviewers.yml

`reviewers.yml` isn't recognizing `transifex-integration` as a username. Let's use the glob of `messages.xx` files instead.
- Test out manually
- Not neccessary
None.
None.

Fix `reviewers.yml`

---

server/conf/i18n/README.md
server/conf/i18n/messages

Removes the comments from `messages`. These have been moved to Transifex [context strings](https://help.transifex.com/en/articles/6244125-the-complete-guide-to-adding-context-to-strings):
Also adds a comment to the top of `messages` reminding developers to add a context string to Transifex.
None.
- `MessagesTest` already checks this
None.
None.

Remove comments from `messages` file

---

server/conf/application.dev.conf

The output is encrypted json so it's not really useful to have on all the time.

Disable request session logging on dev/test/browser tests as default

---

server/app/controllers/applicant/ApplicantProgramsController.java
server/app/controllers/applicant/RedirectController.java
server/app/repository/UserRepository.java
server/app/services/applicant/ApplicantService.java
server/test/services/applicant/ApplicantServiceTest.java

The TI_ONLY program visibility condition displayed the program to TI Clients who could create an account with the email address shared with the TI. This PR fixes the bug. 
Applicants who are managed by a TI cannot see TI_ONLY programs
Fixes #4857

Making TI_ONLY display mode visible to TI Members not TI clients

---

.github/workflows/auto_request_review.yml

This fixes a 'high' code scanning alert. Setting default permissions to read. Also adding a comment on the token being used.

Fixing code scanning alert on permissions

---

server/app/controllers/HomeController.java
server/app/controllers/applicant/ApplicantInformationController.java
server/app/controllers/applicant/RedirectController.java
server/app/views/applicant/ApplicantLayout.java
server/conf/routes
server/test/controllers/HomeControllerWithProfileTest.java
server/test/controllers/RedirectControllerTest.java
server/test/controllers/applicant/ApplicantInformationControllerTest.java

Renames some `ApplicantInformationController` methods to make them be more in line with what they are doing. Reflects some changes in the Login/Languages project.
None.
None.
None.
Relates to #4705

Rename `ApplicantInformationController` methods

---

server/app/auth/ProfileUtils.java
server/app/controllers/admin/AdminQuestionController.java
server/app/controllers/admin/AdminReportingController.java
server/app/featureflags/FeatureFlag.java
server/app/filters/DisableCachingFilter.java
server/app/modules/SecurityModule.java
server/app/services/CfJsonDocumentContext.java
server/app/services/applicant/predicate/JsonPathPredicateGenerator.java
server/app/services/application/ApplicationEventDetails.java
server/app/services/export/CsvExporterService.java
server/app/services/question/types/QuestionType.java
server/app/views/admin/programs/ProgramPredicateConfigureView.java
server/app/views/admin/programs/ProgramPredicatesEditViewV2.java
server/app/views/admin/questions/QuestionEditView.java
server/app/views/admin/questions/QuestionsListView.java
server/app/views/applicant/IneligibleBlockView.java
server/app/views/components/CreateQuestionButton.java
server/app/views/components/Modal.java
server/app/views/components/ProgramCardFactory.java
server/app/views/components/QuestionBank.java
server/app/views/questiontypes/AddressQuestionRenderer.java
server/build.sbt

Updating errorprone to 2.19.1 and fixing new errors. 
Errors were javadocs comments used in invalid locations and use of tolowercase/touppercase without a locale.
Fixes #4842

Updating errorprone to 2.19.1 and fixing new errors

---

.github/labeler.yml
.github/release.yml
.github/workflows/labeler.yaml

- Adds a new Github Action to automatically tag sql files in the evolutions folder with the `database` label.
- Adds a category in the release notes generator config for database.
- If PR has multiple labels the release notes get put in the first matching category.

Call out database changes in release notes

---

env-var-docs/check_vars_documented_test.py
env-var-docs/generate_markdown_test.py
env-var-docs/parser-package/README.md
env-var-docs/parser-package/src/env_var_docs/parser.py
env-var-docs/parser-package/tests/parser_test.py
env-var-docs/run_regex_tests_test.py
server/conf/env-var-docs.json

Per [Admin Settings Panel TDD](https://docs.google.com/document/d/1FK5YLJd6jVu1O1uuu2OOR2mXTs3yVEXkzyfjVwnkz8s/edit), this PR adds a `mode` attribute to the `Variable` type in the env var docs system.
For now it only supports `HIDDEN` and `ADMIN_READABLE` modes, since the first phase of this feature is read-only.
Contributes to https://github.com/civiform/civiform/issues/4948

Add support for mode prop to env variables

---

.github/workflows/scorecards.yaml

There is a bug v2.3.4 of github/codql-action/upload-sarif that doesn't allow it to upload. They are aware of the issue and recommend using the previous version for now. This affects the uploading of the OSSF Score Card only.

Revert action

---

server/conf/env-var-docs.json

As a part of the validation work required for auto-generating server vars, we need to be able to throw an error if a required var is missing from the config ([code](https://github.com/civiform/cloud-deploy-infra/blob/2284e9b6dd86b09369443216da7be77490f1a466/cloud/shared/bin/lib/config_loader.py#L274)). This PR adds the required field to the appropriate vars in `env-var-docs.json` for use in validation.
I determined which vars are required by looking at the values for "required" in the `variable_definitions` files in our infra repository:
- [shared](https://github.com/civiform/cloud-deploy-infra/blob/main/cloud/shared/variable_definitions.json)
- [aws](https://github.com/civiform/cloud-deploy-infra/blob/main/cloud/aws/templates/aws_oidc/variable_definitions.json)
- …

Add "required" field to vars required on startup

---

server/conf/env-var-docs.json

Setting "required" to true for these vars is throwing a validation error because they are named differently in the config file (see Jessica's [variable analysis ](https://docs.google.com/spreadsheets/d/1-Of-wrlN-bMo-3bEFqLoUJRx-LNtIETOPgbeiiSGr1U/edit#gid=899649178) spreadsheet for a list of vars with different names). 
Once server var auto-generation in the deploy system is enabled for all deployments we will be able to update these vars to have the same name as those in the config files and can toggle them back to "required" at that time.
Related to: https://github.com/civiform/civiform/issues/4612

Remove required from duplicate vars

---

server/app/auth/ApiAuthenticator.java
server/test/auth/ApiAuthenticatorTest.java
server/test/support/ResourceCreator.java

Updates API logging to log the correct client IP address, and adds additional details to error logs.
Additional details that are now logged for 401 errors are:
- The `CLIENT_IP_TYPE`
- The value of the `X-Forwarded-For` header
- The allowed subnet set for the key.
Also adds additional tests for the logs, and requests with the `X-Forwarded-For` header set.
Updates API logging to log the correct client IP address, as well as additional debugging information.
n/a
n/a
Fixes #4998

Fix API client IP logging

---

.github/workflows/format.yaml
bin/fmt

The settings manifest needs to be formatted after codegen, since it runs quickly we run it on every call to bin/fmt.

Generate settings manifest on calls to bin/fmt

---

server/app/auth/ApiAuthenticator.java
server/app/auth/ClientIpResolver.java
server/app/filters/ApiKeyUsageFilter.java
server/test/auth/ApiAuthenticatorTest.java
server/test/auth/ClientIpResolverTest.java
server/test/auth/FakeRequestBuilder.java
server/test/auth/FakeRequestBuilderTest.java

Displays correct client IP in admin API key view, based on setting for CLIENT_IP_TYPE
Also
- Refactors IP resolution logic into a `ClientIpResolver`
- Refactors FakeRequestBuilder into a separate class and adds tests for it
Use the CLIENT_IP_TYPE setting to decide which IP address to show in the "Last used by" line of the admin API key list view.
- [n/a] Tested on mobile view. See [mobile device mode](https://developer.chrome.com/docs/devtools/device-mode/)
- [n/a] Manually tested at 200% size
- [n/a] Manually evaluated tab order
- [n/a] Add new …

Display correct client IP in API key view

---

server/app/controllers/applicant/ApplicantInformationController.java
server/app/controllers/applicant/ApplicantProgramBlocksController.java
server/app/controllers/applicant/ApplicantProgramReviewController.java
server/app/controllers/applicant/ApplicantProgramsController.java
server/app/controllers/applicant/RedirectController.java
server/app/controllers/ti/TrustedIntermediaryController.java
server/app/services/applicant/ApplicantPersonalInfo.java
server/app/services/applicant/ApplicantService.java
server/app/services/applications/ProgramAdminApplicationService.java
server/app/views/ApplicantUtils.java
server/app/views/ApplicationBaseView.java
server/app/views/applicant/AddressCorrectionBlockView.java
server/app/views/applicant/ApplicantCommonIntakeUpsellCreateAccountView.java
server/app/views/applicant/ApplicantLayout.java
server/app/views/applicant/ApplicantProgramBlockEditView.java
server/app/views/applicant/ApplicantProgramInfoView.java
server/app/views/applicant/ApplicantProgramSummaryView.java
server/app/views/applicant/ApplicantUpsellCreateAccountView.java
server/app/views/applicant/IneligibleBlockView.java
server/app/views/applicant/ProgramIndexView.java
server/app/views/applicant/TrustedIntermediaryDashboardView.java
server/test/services/applicant/ApplicantPersonalInfoTest.java
server/test/services/applicant/ApplicantServiceTest.java
server/test/support/ResourceCreator.java

`ApplicantUtils.isGuest` is a hacky way of determining whether an applicant is a guest:
https://github.com/civiform/civiform/blob/0ed40707f7e79645c1cea546ebf5463f57e15940/server/app/views/ApplicantUtils.java#L33-L40
Instead, let's address this at the source, `ApplicantService.getNameOrEmail()`:
https://github.com/civiform/civiform/blob/8b4053b383ba759053e2522aeca3ae749f561c9c/server/app/services/applicant/ApplicantService.java#L731-L751
In that method, we return an `Optional<String>` and rely on the "empty-ness" of that object to determine whether a user is a guest. Instead, let's return a new `ApplicantPersonalInfo` that encapsulates whether the applicant is a guest and therefore doesn't have a name or email. 
`ApplicantPersonalInfo` contains an (email and/or  name) ** **or** ** a marker …

Introduce `ApplicantPersonalInfo` to abstract out email and name for applicants

---

server/app/repository/ProgramRepository.java
server/app/services/program/ProgramServiceImpl.java
server/test/controllers/applicant/ApplicantProgramBlocksControllerTest.java
server/test/controllers/applicant/ApplicantProgramReviewControllerTest.java
server/test/controllers/applicant/ApplicantProgramsControllerTest.java
server/test/repository/ProgramRepositoryTest.java
server/test/services/applicant/ApplicantServiceTest.java
server/test/services/program/ProgramServiceImplTest.java

If you knew the id of the draft program, you were able to access it by putting its ID into the URL. The method to get the active program was not actually checking if the program was active.

Fix issue that allowed applicants to access draft programs.

---

server/conf/application.dev.conf
server/conf/helper/feature-flags.conf

Enable the non-gating eligibility feature flag by default. This does not set eligibility to non-gating, it just gives admins the ability to choose whether eligibility is gating or non-gating.
This feature gives admins the ability to choose whether eligibility is gating or non-gating. If eligibility is set to gating for a program, applicants will not be able to submit applications to that program unless they meet the eligibility requirements. If it's set to non-gating, applicants will not be blocked from submission, but their eligibility status will be visible to program admins when reviewing applications.
Part of #5036

Enable non-gating eligibility feature by default.

---

.github/reviewers.yml

Removes me from localization PR reviews. Now it will just be the Civiform/Developers group.

Remove MichaelZetune from `reviewers.yml` for localization PRs

---

server/app/views/admin/programs/ProgramIndexView.java
server/app/views/admin/questions/QuestionsListView.java

Fix the shape of the gray background when hovering over some buttons
- The shape on hover for the publish button should be an oval like the edit button.
- The shape on hover for the dropdown buttons in the Questions page should be a rectangle.
Fixes #4881

Fix hover shape for some buttons.

---

server/app/repository/ProgramRepository.java
server/app/services/program/ProgramServiceImpl.java
server/test/controllers/applicant/ApplicantProgramBlocksControllerTest.java
server/test/controllers/applicant/ApplicantProgramReviewControllerTest.java
server/test/controllers/applicant/ApplicantProgramsControllerTest.java
server/test/repository/ProgramRepositoryTest.java
server/test/services/applicant/ApplicantServiceTest.java
server/test/services/program/ProgramServiceImplTest.java

Reverts civiform/civiform#5007. I realized that this breaks the case where an applicant has an in-progress application, a new version is published, and then the applicant tries to continue their application which is tied to the now-obsolete program. Reverting before the next release to avoid breaking applicant flows while I work on a fix.

Revert "Fix issue that allowed applicants to access draft programs."

---

browser-test/src/admin_program_visibility.test.ts

Fix for SELECT_TI Visibility Browser tests failures.
Previously to create a logged in TI experience, the TI Client's email 'testuser@example.com' was hard coded in the browser tests which ended up breaking the test runs in staging environments. Ideally it should be pulled from the environment variables (part of  Github secrets). This fix, instead of having a hard-coded value, will use the export value from config, so that the browser test runs for all environment pass successfully. 
Fixes #5050

Fix for SELECT_TI Visibility Browser tests failures

---

server/app/controllers/dev/DatabaseSeedController.java

While the existing mock program is useful because it shows a lot of question types and blocks, it's often kind of difficult to use since it has so many required questions. This adds a much simpler program with just a single optional program that can be filled out quickly.

Add a simpler seeded mock program.

---

server/conf/helper/auth.conf

Adding additional environment variable checks for idcs client_id/secret using the common ones we use elsewhere. If empty it will fall back to the existing environment variable.

Adding additional environment variable checks for idcs client_id/secret

---

server/app/services/applicant/question/MultiSelectQuestion.java
server/app/services/applicant/question/SingleSelectQuestion.java

The only MultiSelectQuestion type is a checkbox, and the SingleSelectQuestion types are radio button and dropdown. However, these aren't currently reflected in the `ImmutableSet<QuestionType> validQuestionTypes()` implementations of `Question`:
https://github.com/civiform/civiform/blob/7ce5f689d8f1f1b9d99717c9d448750dfa4b38b8/server/app/services/applicant/question/MultiSelectQuestion.java#L34-L37
https://github.com/civiform/civiform/blob/7ce5f689d8f1f1b9d99717c9d448750dfa4b38b8/server/app/services/applicant/question/SingleSelectQuestion.java#L31-L34
This PR fixes that. Notably the only use of `validQuestionTypes()` is here:
https://github.com/civiform/civiform/blob/7ce5f689d8f1f1b9d99717c9d448750dfa4b38b8/server/app/services/applicant/question/Question.java#L27-L40
None.
- No, but tested …

Correct single/multi select `QuestionType`s

---

server/conf/env-var-docs.json

This pr removes the "required" field from variables that are specific to a cloud provider (AWS or Azure) so that Azure vars are not required for AWS deployments and vice versa.
AWS vars are listed in our deployment system [here](https://github.com/civiform/cloud-deploy-infra/blob/main/cloud/aws/templates/aws_oidc/variable_definitions.json)
Azure vars are listed in our deployment system [here](https://github.com/civiform/cloud-deploy-infra/blob/main/cloud/azure/templates/azure_saml_ses/variable_definitions.json)
More details in this Slack thread: https://civiform.slack.com/archives/C04QU24UJSF/p1686850489864139
Follow-up work to allow "required" vars by cloud provider is captured in this issue: https://github.com/civiform/civiform/issues/5092

remove "required" from cloud specific vars

---

bin/generate-settings-manifest
bin/lib.sh
bin/lib/python.sh

This reduces developer toil by creating and activating the var-env-docs [python venv](https://docs.python.org/3/library/venv.html) when `bin/generate-settings-manifest` is invoked so that developers don't have to manually run the creation and activation scripts when they use `bin/fmt`.

Activate python venv when running settings manifest generator

---

server/app/controllers/CiviFormController.java
server/app/controllers/FileController.java
server/app/controllers/admin/AdminApiKeysController.java
server/app/controllers/admin/AdminApplicationController.java
server/app/controllers/admin/AdminProgramBlockPredicatesController.java
server/app/controllers/admin/AdminProgramBlocksController.java
server/app/controllers/admin/AdminProgramController.java
server/app/controllers/admin/AdminProgramStatusesController.java
server/app/controllers/admin/AdminProgramTranslationsController.java
server/app/controllers/admin/AdminQuestionController.java
server/app/controllers/admin/AdminQuestionTranslationsController.java
server/app/controllers/admin/AdminReportingController.java
server/app/controllers/admin/AdminSettingsController.java
server/app/controllers/admin/ProgramAdminController.java
server/app/controllers/api/CiviFormApiController.java
server/app/controllers/api/ProgramApplicationsApiController.java
server/app/controllers/applicant/ApplicantInformationController.java
server/app/controllers/applicant/ApplicantProgramBlocksController.java
server/app/controllers/applicant/ApplicantProgramReviewController.java
server/app/controllers/applicant/ApplicantProgramsController.java
server/app/controllers/applicant/RedirectController.java
server/app/controllers/monitoring/MetricsController.java
server/app/repository/VersionRepository.java
server/test/controllers/RedirectControllerTest.java
server/test/controllers/WithMockedProfiles.java
server/test/controllers/admin/AdminApplicationControllerTest.java
server/test/controllers/applicant/ApplicantProgramBlocksControllerTest.java
server/test/controllers/applicant/ApplicantProgramReviewControllerTest.java
server/test/controllers/applicant/ApplicantProgramsControllerTest.java
server/test/controllers/monitoring/MetricsControllerTest.java

Check that the user is a CiviForm Admin before allowing access to a draft program's application pages.
This is a bug fix but is also set-up work for #240.

Stop non-CiviForm Admin users from applying to draft programs.

---

server/app/modules/MainModule.java
server/conf/application.dev-browser-tests.conf
server/conf/application.test.conf
server/conf/helper/auth.conf
server/test/services/settings/SettingsServiceTest.java

This PR changes the code for resolving the login portal name so that "TestPortal" is only used if `applicant_portal_name` and `whitelabel_civic_entity_full_name` are both not present.
See https://github.com/civiform/civiform/issues/5134
Fixes https://github.com/civiform/civiform/issues/5134

Only use applicant_portal_name if whitelabel_civic_entity_full_name is not present

---

browser-test/src/admin_settings.test.ts

Because we have ESRI_ADDRESS_CORRECTION_ENABLED on staging, while this test would pass in the hermetic test env, it would fail on staging since it would be trying to enable something that's already enabled. This switches it to use the CF_OPTIONAL_QUESTIONS setting instead, since this should probably always be enabled, and to test disabling, re-enabling, then saving with it still enabled.
This has been tested against probers manually and passes, along with running in the hermetic env.

Fix admin_settings test for probers

---

server/app/controllers/applicant/ApplicantProgramsController.java
server/test/controllers/applicant/ApplicantProgramsControllerTest.java

This is a patch for #5167. The REDIRECT_TO_SESSION_KEY is set when the navigating to a program by the slug and doesn't get cleared properly. This is only a temporary fix that clears it if the user goes to the index page. We should follow up with a solution that fixes the underlying problem. Filed #5171 to track that.
Fixes #5167

Clear the redirect target if the user navigates to the index page.

---

browser-test/src/program_deep_link.test.ts
server/app/controllers/applicant/RedirectController.java
server/test/controllers/RedirectControllerTest.java

`RedirectController.programBySlug` inserts a `REDIRECT_TO_SESSION_KEY` if the user doesn't have a profile yet, so that they are redirected to the `/programs/slug-link` URL again after getting a guest profile.
Previously we did not clear this out after sending the user to the full program link, which led to #5171. This fixes that by `removingFromSession` the `REDIRECT_TO_SESSION_KEY` before redirecting them to the full program link.
Fixes a bug with program slug links.
None.
None.
Fixes #5171

Fix Program Slug Redirect

---

server/app/services/export/PdfExporter.java
server/test/services/export/PdfExporterTest.java

Add eligibility status to questions on PDF export when eligibility conditions are applied to the program and question.
Fixes #4455

Add eligibility status to questions on PDF export

---

server/build.sbt

`AutoValue` has been used in the project and working for a while, but IntelliJ has had trouble recognizing the symbols for many developers (including myself).
Notably, AutoValue is generating `.class` files for all AutoValue classes, but `.java` files are missing. This seems to be an intentional feature of AutoValue to clean up files unnecessary to compilation.
It's not clear to me why some developers have their IDE recognize the `.class` files and some don't, but this PR introduces a "hack" that keeps those `.java` files around, even though this is not `AutoValue`'s intent.
In my testing, making this change and then running `bin/build-dev` or running `compile` in the IntelliJ sbt shell fixes all red AutoValue errors.
Debugged using [ChatGPT …

Fix AutoValue generation in `build.sbt`

---

server/conf/application.dev-browser-tests.conf

Missed this last reference to a feature flag when removing it.

Remove dangling reference to deleted feature flag.

---

server/app/services/apikey/ApiKeyService.java
server/test/services/apikey/ApiKeyServiceTest.java

Strip whitespace from the API key the user enters into the form.
Fixes #5157

Strip whitespace from API key

---

browser-test/src/question_lifecycle.test.ts
server/app/controllers/dev/seeding/DevDatabaseSeedController.java
server/app/controllers/dev/seeding/DevDatabaseSeedTask.java
server/app/controllers/dev/seeding/SampleQuestionDefinitions.java
server/app/services/seeding/DatabaseSeedTask.java
server/test/controllers/dev/seeding/DevDatabaseSeedTaskTest.java

This cleans up and centralizes the database seeding logic further, building on #5213 in preparation for API docs testing.
Changes include:
* Create `DevDatabaseSeedTask` and (mostly) leave `DatabaseSeedTask` alone. The former is only for dev, and the latter is only for prod. Previously, `DevDatabaseSeedController` would use `DatabaseSeedTask` for seeding some questions, commingling these two functions; we remove that dependency.
* Remove all unnecessary `dateQuestionDefininition()` methods in `SampleQuestionDefinitions`. The only one we need is the one that helps create enumerated date questions.
* Move `insertMinimalSampleProgram` and `insertComprehensiveSampleProgram` from `DatabaseSeedController` to `DevDatabaseSeedTask`.
* Remove the need for this code:
```java
QuestionDefinition …
```

More Database Seeding Logic Cleaning

---

env-var-docs/parser-package/src/env_var_docs/settings_manifest.py
env-var-docs/parser-package/tests/settings_manifest_test.py
server/app/services/settings/SettingDescription.java
server/app/services/settings/SettingsManifest.java
server/test/services/settings/SettingDescriptionTest.java
server/test/services/settings/SettingsManifestTest.java
server/test/services/settings/SettingsSectionTest.java
server/test/services/settings/SettingsServiceTest.java

Passes the `required` attribute through from variables in env-var-docs.json to `SettingDescription` in the server. The value of the attribute will be consumed in upcoming PRs.
Contributes to https://github.com/civiform/civiform/issues/5217

Include required attribute on SettingDescription

---

browser-test/src/address.test.ts
browser-test/src/admin_api_keys.test.ts
browser-test/src/admin_program_list.test.ts
browser-test/src/admin_program_preview.test.ts
browser-test/src/admin_program_viewing.test.ts
browser-test/src/admin_program_visibility.test.ts
browser-test/src/applicant_application_index.test.ts
browser-test/src/application_navigation.test.ts
browser-test/src/auth.test.ts
browser-test/src/checkbox.test.ts
browser-test/src/civiform_admin_publish.test.ts
browser-test/src/civiform_admin_question_list.test.ts
browser-test/src/civiform_admin_question_references.test.ts
browser-test/src/currency.test.ts
browser-test/src/date.test.ts
browser-test/src/dropdown.test.ts
browser-test/src/email.test.ts
browser-test/src/file.test.ts
browser-test/src/id.test.ts
browser-test/src/mobile_views.test.ts
browser-test/src/name.test.ts
browser-test/src/number_input.test.ts
browser-test/src/phone.test.ts
browser-test/src/program_deep_link.test.ts
browser-test/src/radio_button.test.ts
browser-test/src/support/admin_programs.ts
browser-test/src/text.test.ts

Clean up outdated comment that claimed questions could only be published if a program was edited. Also rename `*publishAllPrograms*` methods to be more accurate since questions can be published without program edits.
Fixes #5222

Fix incorrect comment and make method names more accurate.

---

server/test/controllers/geo/AddressSuggestionJsonSerializerTest.java
server/test/models/QuestionTest.java
server/test/services/applicant/BlockTest.java
server/test/services/applicant/ReadOnlyApplicantProgramServiceImplTest.java
server/test/services/applicant/ServiceAreaUpdateResolverTest.java
server/test/services/geo/ServiceAreaInclusionGroupTest.java
server/test/services/geo/esri/EsriClientTest.java
server/test/services/geo/esri/EsriServiceAreaValidationConfigTest.java
server/test/services/geo/esri/EsriServiceAreaValidationOptionTest.java
server/test/services/geo/esri/FakeEsriClientTest.java
server/test/services/geo/esri/RealEsriClientTest.java
server/test/views/style/StyleUtilsTest.java

Make assertion library usage consistent across the codebase.
Fixes #5223

Replace assertEquals with assertThat.

---

server/conf/evolutions/default/54.sql
server/test/repository/QuestionRepositoryTest.java

Adds a DB trigger that runs before inserting new entries in the `questions` table and raises an exception if there already exists a row with the given question name associated with the current draft version.
contributes to https://github.com/civiform/civiform/issues/5209

Validate question draft uniqueness with DB trigger

---

server/app/views/applicant/ApplicantLayout.java

This pr removes aria-hidden true from the CE logo so that the alt text can be read by screen readers.
Run the app and load the home page. Inspect the logo on the homepage. The `aria-hidden=true` label should not be present. 
Alternatively, turn on screen reader, navigate to logo, and confirm that the logo alt text is read out loud.
Fixes #3569

remove aria-hidden true from logo

---

server/app/auth/DefaultToGuestRedirector.java
server/app/controllers/HomeController.java
server/app/controllers/applicant/DeepLinkController.java

When an unauthenticated user opens CiviForm, we use the `CallbackController` to create a guest profile for them and redirect them back to the page they were on.
Centralize this logic in a new `DefaultToGuestRedirector` class. Primary motivation is that the API generated docs will need this soon, and I don't want to further increase the duplication.
None.
- Not needed; refactor
None.
None.
None.
None.

Centralize new guest logic

---

server/app/assets/javascripts/admin_predicate_configuration.ts

Before this change, the admin would see a server error if they save an eligibility condition for question types that have multiple options, e.g. checkbox questions, without selecting an option. This updates the validation logic, using the number of input tags within a question group as a heuristic for determining if the question needs a `.checked` field versus needing a `.value`.
I think we should try to refactor this validation logic in the future so that it happens in the Java code rather than in the Typescript code to make testing easier and to make sure we're covering all question types. Filed #5265 for that.
Fixes #5101

Fix eligibility condition validation for multi option input types.

---

server/conf/evolutions/default/55.sql

Sets the applications.is_admin field to value based on if the account is an admin. The [previous script](https://github.com/civiform/civiform/blob/main/server/conf/evolutions/default/53.sql) has an incorrect join.
Sets the applications.is_admin field to value based on if the account is an admin.
Fixes : #5268

Adding script to set the applications.is_admin field values

---

server/app/services/applicant/ReadOnlyApplicantProgramServiceImpl.java
server/app/services/applicant/question/ApplicantQuestion.java
server/app/services/export/CsvExporterService.java
server/app/views/questiontypes/AddressQuestionRenderer.java
server/app/views/questiontypes/ApplicantQuestionRendererImpl.java
server/app/views/questiontypes/CheckboxQuestionRenderer.java
server/app/views/questiontypes/CurrencyQuestionRenderer.java
server/app/views/questiontypes/DateQuestionRenderer.java
server/app/views/questiontypes/DropdownQuestionRenderer.java
server/app/views/questiontypes/EmailQuestionRenderer.java
server/app/views/questiontypes/EnumeratorQuestionRenderer.java
server/app/views/questiontypes/FileUploadQuestionRenderer.java
server/app/views/questiontypes/IdQuestionRenderer.java
server/app/views/questiontypes/NameQuestionRenderer.java
server/app/views/questiontypes/NumberQuestionRenderer.java
server/app/views/questiontypes/PhoneQuestionRenderer.java
server/app/views/questiontypes/RadioButtonQuestionRenderer.java
server/app/views/questiontypes/TextQuestionRenderer.java
server/test/services/applicant/BlockTest.java
server/test/services/applicant/question/ApplicantQuestionTest.java

Rename `errorsPresenter()` to more descriptive `getQuestions()`.
Rename `errorsPresenter()` to more descriptive `getQuestions()`. With only that substitution, there were several examples of `question.getQuestion()`, so in these cases, the variables have been renamed to `applicantQuestion` to make the relationship clearer.

Rename `errorsPresenter()` to more descriptive `getQuestions()`.

---

server/app/services/export/PdfExporter.java
server/test/services/export/AbstractExporterTest.java
server/test/services/export/PdfExporterTest.java

Previously the applicant name in an exported PDF looked like `"Optional[applicant name]"` or `"Optional.empty"`. This change fixes the formatting and handles the missing `Optional` case explicitly. The formatted name is contained in the PDF contents as well as forming part of the file name.
A PDF generated with this fix is attached.
Fixes the applicant name in the generated PDF contents and file name.
- n/a
- n/a
- n/a
- n/a
- n/a
- n/a
Fixes #5066
[User, Test (1)-2023-07-10T11_20_41.181890.pdf](https://github.com/civiform/civiform/files/12005148/User.Test.1.-2023-07-10T11_20_41.181890.pdf)

Fix name formatting for PDF export.

---

server/app/services/CfJsonDocumentContext.java
server/app/services/applicant/question/MultiSelectQuestion.java
server/test/services/CfJsonDocumentContextTest.java
server/test/services/applicant/ApplicantServiceTest.java
server/test/support/QuestionAnswererTest.java

Adds `readStringList()` and  `hasNullValueAtPath()` to `CfJsonDocumentContext` to facilitate tests, and renames the existing `readList()` to `readLongList()`.
n/a
- [n/a] Followed steps to [internationalize new strings](https://docs.civiform.us/contributor-guide/developer-guide/internationalization-i18n#internationalization-for-application-strings)
- [n/a] Wrote browser tests using the [validateAccessibility](https://sourcegraph.com/github.com/civiform/civiform/-/blob/browser-test/src/support …

Add additional accessor methods to CfJsonDocumentContext

---

server/app/repository/VersionRepository.java

We are continuing to see bugs related to inconsistent data in newly published versions.

Publish versions in a serializable transaction

---

server/app/services/question/types/QuestionDefinition.java
server/app/services/question/types/QuestionDefinitionBuilder.java
server/app/services/question/types/QuestionDefinitionConfig.java

`QuestionDefinitionBuilder` exists as technical debt, now that `QuestionDefinition` is constructed with a `QuestionDefinitionConfig.Builder`.
It's very hard to remove, since it has so many usages throughout CiviForm. This PR works towards making `QuestionDefinitionBuilder` use `QuestionDefinitionConfig` internally, so that there is at least less risk of divergence in behavior.
Changes:
* Instead of storing all of the `QuestionDefinition` vars in `QuestionDefinitionBuilder`, we now just store a `QuestionDefinitionConfig.Builder`.
* Stop constructing the `QuestionDefinitionConfig` for each question type; reuse the original one in the switch statement.
* In `QuestionDefinition`, use `config` as little as possible (i.e. use `this.getName()` instead of `config.getName()`.
Note: …

Simplify `QuestionDefinitionBuilder`

---

server/app/services/settings/SettingsManifest.java
server/conf/env-var-docs.json

With server variable autogeneration turned on in the deployment system, any variables marked "required" will be expected to be in the `config.sh` file for that deployment. This PR removes "required" from vars that we don't want to add the `config.sh` file.
Right now deploying with server var autogeneration turned on results in the following error:

Remove "required" from vars we don't want in the config.sh

---

server/app/controllers/dev/seeding/DevDatabaseSeedTask.java
server/app/filters/ApiKeyUsageFilter.java
server/app/services/seeding/DatabaseSeedTask.java

`String.format` substitutes argument strings into a format string by replacing the `%s` char sequence.
`org.slf4j.Logger` substitutes argument strings into a format string by replacing the `{}` char sequence.
This PR fixes a few places where we are using the former syntax in calls to the latter method.

Fix string formatting in log messages

---

server/app/controllers/admin/AdminProgramTranslationsController.java
server/app/controllers/admin/AdminQuestionTranslationsController.java
server/app/services/program/ActiveAndDraftPrograms.java
server/app/views/admin/TranslationFormView.java
server/app/views/admin/programs/ProgramIndexView.java
server/app/views/admin/programs/ProgramStatusesView.java
server/app/views/admin/programs/ProgramTranslationView.java
server/app/views/admin/questions/QuestionTranslationView.java
server/app/views/admin/questions/QuestionsListView.java
server/conf/routes
server/test/controllers/admin/AdminProgramTranslationsControllerTest.java
server/test/controllers/admin/AdminQuestionTranslationsControllerTest.java

UI for editing translations use specific question/program (QP) IDs, so that when the form is rendered and submitted it is with regard to a specific version of a QP. This could potentially cause data inconsistency issues if a user has browser pages open to stale versions of the question since the code to update a translation calls [QuestionService#update](https://github.com/civiform/civiform/blob/use-canonical-references-for-programs-and-questions/server/app/services/question/QuestionService.java) which calls [createOrUpdateDraft](https://github.com/civiform/civiform/blob/use-canonical-references-for-programs-and-questions/server/app/services/question/QuestionService.java#L147) -- since the draft has a new ID, multiple drafts could be created this way.
This PR changes all IDs in URLs in …

Use canonical identifiers for question and program translations

---

server/app/repository/ApplicationRepository.java
server/app/services/applicant/ApplicantData.java
server/test/repository/ApplicationRepositoryTest.java
server/test/services/applicant/ApplicantDataTest.java

Detect applications that are duplicates (modulo timestamps).
This PR adds code to detect that a draft application being submitted contains identical answers to the currently-active application for this applicant and program. The scope of this PR is to log the condition; future PRs may affect the UX.
Though it would be cleanest to compare answers via their Java representations, these are not available at this point in the flow; only the JSON representation is available. Thus we compare the JSON representations of the applicant data, after clearing some timestamp metadata.
See [Design: Detecting Unintentional Duplicate Applications](https://docs.google.com/document/d/1nUGatPTxcL0bCuGY3e2hTajPAYufQJpXXnbpgXi4Xs4/edit?usp=sharing). …

Detect applications that are duplicates (modulo timestamps).

---

env-var-docs/parser-package/README.md

Added more details about "required" vars in the env-var-docs parser package.

add more details about required vars in env-var-docs

---

server/app/controllers/admin/AdminProgramController.java
server/app/controllers/dev/seeding/DevDatabaseSeedTask.java
server/app/repository/ProgramRepository.java
server/app/repository/QuestionRepository.java
server/app/repository/VersionRepository.java
server/app/services/ProgramBlockValidationFactory.java
server/app/services/program/ActiveAndDraftPrograms.java
server/app/services/program/ProgramServiceImpl.java
server/app/services/question/ActiveAndDraftQuestions.java
server/app/services/question/QuestionService.java
server/app/services/question/ReadOnlyCurrentQuestionServiceImpl.java
server/app/services/seeding/DatabaseSeedTask.java
server/test/controllers/admin/AdminProgramControllerTest.java
server/test/controllers/admin/AdminQuestionTranslationsControllerTest.java
server/test/models/VersionTest.java
server/test/repository/ProgramRepositoryTest.java
server/test/repository/QuestionRepositoryTest.java
server/test/repository/VersionRepositoryTest.java
server/test/services/ProgramBlockValidationTest.java
server/test/services/question/ActiveAndDraftQuestionsTest.java
server/test/services/question/QuestionServiceTest.java
server/test/support/ProgramBuilder.java

Renames `VersionRepository`'s `getDraftVersion` to `getDraftVersionOrCreate` as the method creates a global draft version if one doesn't already exist. 
Separating out this PR from a [child PR](https://github.com/civiform/civiform/pull/5310) because it is large (though simple) and relatively unrelated, and necessary for the child one.

Rename `getDraftVersion` to `getDraftVersionOrCreate`

---

server/app/services/CfJsonDocumentContext.java
server/app/services/export/JsonPrettifier.java
server/test/services/CfJsonDocumentContextTest.java
server/test/services/export/JsonPrettifierTest.java

Adds tests for JsonPrettifier and an `asPrettyJsonString()` to the CfJsonDocumentContext that prints the document below the specified path.
n/a
- [n/a] Followed steps to [internationalize new strings](https://docs.civiform.us/contributor-guide/developer-guide/internationalization-i18n#internationalization-for-application-strings)
- [n/a] Wrote browser tests using the [validateAccessibility](https://sourcegraph.com/github.com/civiform/civiform/-/blob/browser-test/src/support/index.ts?L437:14&s …

Add tests and overloads for JsonPrettifier and CfJsonDocumentContext

---

server/app/services/CfJsonDocumentContext.java
server/app/services/export/JsonPrettifier.java
server/test/controllers/api/ProgramApplicationsApiControllerTest.java
server/test/services/CfJsonDocumentContextTest.java
server/test/services/export/AbstractExporterTest.java
server/test/services/export/CsvExporterTest.java
server/test/services/export/JsonExporterTest.java
server/test/services/export/JsonPrettifierTest.java
server/test/support/TestQuestionBank.java

- Adds tests to JsonExporter for unanswered repeated questions
- Adds a `FakeProgramBuilder` to `AbstractExporterTest` to ease building fake programs to use for testing
- No changes are necessary to the actual exporter after #5225, but this should catch future regressions
n/a
- [n/a] Followed steps to [internationalize new strings](https://docs.civiform.us/contributor-guide/developer-guide/internationalization-i18n#internationalization-for-application-strings)
- [n/a] Wrote browser tests …

Add JsonExporter tests for unanswered repeated questions

---

server/app/auth/oidc/OidcClientProvider.java
server/app/controllers/admin/AdminProgramController.java
server/app/controllers/api/ApiDocsController.java
server/app/controllers/dev/seeding/DevDatabaseSeedTask.java
server/app/repository/UserRepository.java
server/app/services/CfJsonDocumentContext.java
server/app/views/components/FieldWithLabel.java
server/build.sbt

This PR enables ErrorProne's `CatchingUnchecked` bug pattern, which prevents us from having a `catch (Exception e)` style block. We do so by enabling `-Xep:CatchingUnchecked:ERROR` in `build.sbt`.
https://errorprone.info/bugpattern/CatchingUnchecked
> This catch block catches `Exception`, but can only catch unchecked exceptions. Consider catching RuntimeException (or something more specific) instead so it is more apparent that no checked exceptions are being handled.
While we're here, I also enabled `ThrowsUncheckedException`, which is less pressing but also enfoces better practice. It prevents us from declaring `throws RuntimeException` (and subclasses of it), which may misleadingly imply that callers will need to handle these exceptions at compile-time. …

Prohibit catching `Exception` or `throws`-ing `RuntimeException`

---

server/app/controllers/admin/AdminProgramBlocksController.java
server/app/controllers/admin/AdminQuestionTranslationsController.java
server/app/repository/VersionRepository.java
server/app/services/applicant/AnswerData.java
server/app/services/applicant/question/ApplicantQuestion.java
server/app/services/applicant/question/NullQuestion.java
server/app/services/applicant/question/Scalar.java
server/app/services/program/BlockDefinition.java
server/app/services/question/QuestionService.java
server/app/services/question/ReadOnlyCurrentQuestionServiceImpl.java
server/app/services/question/ReadOnlyVersionedQuestionServiceImpl.java
server/app/services/question/types/NullQuestionDefinition.java
server/app/services/question/types/NullQuestionDefinitionConfig.java
server/app/services/question/types/QuestionType.java
server/app/views/admin/programs/ProgramBlocksView.java
server/app/views/components/CreateQuestionButton.java
server/app/views/questiontypes/ApplicantQuestionRendererFactory.java
server/test/repository/VersionRepositoryTest.java
server/test/services/applicant/question/ApplicantQuestionTest.java
server/test/services/export/AbstractExporterTest.java
server/test/services/program/BlockDefinitionTest.java
server/test/services/question/ReadOnlyVersionedQuestionServiceImplTest.java
server/test/support/TestQuestionBank.java
server/test/support/TestQuestionBankTest.java
server/test/views/admin/question/QuestionConfigTest.java
server/test/views/questiontypes/ApplicantQuestionRendererFactoryTest.java

This allows the admin program view/edit screens to continue to load in the event the program question definition is pointing at a "missing" question. "Missing" questions so far have occurred because the active program is pointing at previous version (and now obsolete) questions.
Here is an example of what the civiform admin would see when viewing a program.
When creating a new draft of a program the system is able to find the correct active version and the draft ends up in the correct state. Publishing then fixes the problem.
Ideally no one should ever see these errors show on the screen, but at least now the screen will load.
Tester …

Allow admin view/edit to load with question definition errors

---

server/app/repository/ProgramRepository.java
server/test/repository/ProgramRepositoryTest.java

This mutation was intended for an old schema, this PR removes it. Mutations in getX methods are bad practice.
None.

Remove mutation in `getActiveProgramFromSlug`

---

server/app/services/settings/SettingsManifest.java
server/conf/env-var-docs.json

This was optional previously, setting it to required caused problems for deployments that do not have it set yet.

Revert APPLICANT_REGISTER_URI to optional

---

server/app/controllers/applicant/ApplicantProgramReviewController.java
server/test/controllers/HasBooleanHeaderArgumentMatcher.java
server/test/controllers/WithMockedProfiles.java
server/test/controllers/applicant/ApplicantProgramReviewControllerTest.java

In cases where the `ApplicantProgramReviewController` cannot fetch the user profile, or the user is unauthorized, redirect the user to the home page.
In cases where the user profile cannot be fetched, or the user is unauthorized, redirect the user to the home page. This case could occur if a tab is left open overnight and the browser session expires.
If a user profile is not available, then it doesn't make sense to create a guest browser session and try the action again, since the new account will not be authorized to see the application for the existing account. Sending the user to the homepage seems reasonable for this case.
Similarly, if the user fails authorization for any reason, we currently just return 401 and nothing shows in the browser. Redirecting to the home page also makes …

Redirect user to home on APRC failures

---

server/app/services/ProgramBlockValidation.java
server/app/services/ProgramBlockValidationFactory.java
server/test/services/ProgramBlockValidationTest.java
server/test/support/ResourceCreator.java

This is the second part of the bugfix. This PR ensures that every question displayed in the QuestionListView is always in Draft or Active State.
This is the second part of the bugfix for #5281. This PR ensures that every question displayed in the QuestionListView is always in Draft or Active State.
Fixes #5281

Bug fix Part-2 :Adding tombstoned questions to a program creates invalid state

---

server/app/services/seeding/DatabaseSeedTask.java

Remove log message that says canonical question exists at server start. Message saying it exists doesn't provide much use.

Removing log message that says canonical question exists

---

server/app/filters/SettingsFilter.java

Play Framework initializes instances of filters when the server starts. Since EBean initializes independently of the Play server, there may be a race condition between the database being available and Play attempting to create an instance of `SettingsFilter`. Since that the constructor dependency tree for that filter eventually calls `DB.getDefautl()` in `SettingsGroupRepository`, this may be the cause of recent crash-loop deployment failures.
By instead injecting a `Provider`, we delay the time that the constructor for `SettingsService` gets called until after the server boots and begins receiving requests, hopefully avoiding the race condition with EBean initialization.
I tested this fix by building a prod image (`SNAPSHOT-3e5665f-1691445630`) and deploying it to AWS eight times with …

Inject SettingsService into SettingsFilter via provider

---

server/app/filters/SettingsFilter.java

Requests to `/assets/` are handled by the Play Framework assets controller. Since that controller doesn't consume any of our code we can safely skip loading settings which saves a database query per request.

Don't load settings for assets requests

---

server/app/controllers/admin/ProgramAdminController.java

This fixes potential latency on the program admin page by using the function we created in https://github.com/civiform/civiform/pull/4589 to load the program data without the underlying questions.
Fixes #5414

Load program data without questions for program admins

---

server/app/controllers/admin/AdminProgramTranslationsController.java
server/test/controllers/admin/AdminProgramTranslationsControllerTest.java

Program Translations "Save" button will load the same translation program view on success. This was a bug from the previous work, where every click to the "Save" button will re-route the CiviForm admins back to the program list view. This fix will keep the admins on the same view. They can use "Back" button to go back to the list view. 
Program Translations Save button will load the same view on success
Fixes #5377

Program Translations Save button will load the same view on success

---

server/app/auth/oidc/OidcClientProvider.java
server/app/auth/oidc/applicant/GenericOidcClientProvider.java
server/app/auth/oidc/applicant/IdcsClientProvider.java

Allow CSRF behavior to be specified by subclasses of OidcClientProvider.
Allow CSRF behavior to be specified by subclasses of OidcClientProvider. This PR does not affect current behavior, but allows future subclasses to specify a value other than `false`.
Supports #5401

Allow CSRF behavior to be specified by subclasses of OidcClientProvider

---

server/app/auth/oidc/CiviformOidcProfileCreator.java
server/app/auth/oidc/OidcClientProvider.java
server/app/auth/oidc/admin/AdfsClientProvider.java
server/app/auth/oidc/admin/AdfsProfileCreator.java
server/app/auth/oidc/applicant/ApplicantProfileCreator.java
server/app/auth/oidc/applicant/Auth0ClientProvider.java
server/app/auth/oidc/applicant/GenericApplicantProfileCreator.java
server/app/auth/oidc/applicant/GenericOidcClientProvider.java
server/app/auth/oidc/applicant/IdcsApplicantProfileCreator.java
server/app/auth/oidc/applicant/IdcsClientProvider.java
server/app/auth/oidc/applicant/LoginGovClientProvider.java

Rename applicantRepositoryProvider to accountRepositoryProvider, as it is used for admins as well as applicants.
Supports #5401

Rename applicantRepositoryProvider to accountRepositoryProvider

---

server/app/auth/oidc/OidcClientProvider.java
server/app/auth/oidc/applicant/GenericOidcClientProvider.java
server/app/auth/oidc/applicant/IdcsClientProvider.java
server/app/auth/oidc/applicant/LoginGovClientProvider.java

Generalize attribute prefix so that a '.' is not required in the config var name.
Relates to #5401

Generalize attribute prefix

---

server/app/auth/oidc/OidcClientProvider.java
server/app/auth/oidc/admin/AdfsClientProvider.java
server/app/auth/oidc/admin/GenericOidcClientProvider.java
server/app/auth/oidc/admin/GenericOidcProfileCreator.java
server/test/auth/oidc/admin/GenericOidcClientProviderTest.java
server/test/auth/oidc/admin/GenericOidcProfileCreatorTest.java

Create a `GenericOidcClientProvider` for admins.
Create a `GenericOidcClientProvider` for admins. At present, it supports authentication and authorization. Support for logout is tracked in #4359.
This PR only creates the new class; wiring the new class into the `SecurityModule` based on new config will come in later PRs.
This class shares quite a bit of logic with the matching version for applicants; a refactoring will follow.
Relates to #5401

Create admin GenericOidcClientProvider

---

server/app/views/questiontypes/RadioButtonQuestionRenderer.java

Radio button list will now select the item no matter where on the item you click. Now works like the checkbox question
Click on the radio button itself, click on the text next to the radio button, or click on the whitespace in the box. These will all select the button now.

Radio button list now selects the item anywhere on the line

---

README.md

The UX contribution docs page no longer exists, so we should remove that legacy reference. 
Also linked the technical contribution guide instead of that section within the guide.

Update README to remove UX contribution guide

---

server/app/services/settings/SettingsManifest.java
server/conf/env-var-docs.json

Do not require env var `CIVIFORM_ADMIN_IDP` to be set, as this breaks existing deployments. Instead, rely on the [default value](https://github.com/civiform/civiform/blob/602b568e51b1dd039e78f988848f1ead2b0e1fb6/server/conf/helper/auth.conf#L4) of `"adfs"` if not set.
Relates to #5401

Do not require CIVIFORM_ADMIN_IDP to be set

---

server/app/services/settings/SettingsManifest.java
server/conf/application.conf
server/conf/env-var-docs.json

We currently use play's default HTTP thread count. We should make this configurable to optimize resource utilization. 
If unset, we use the akka defaults https://github.com/akka/akka/blob/main/akka-actor/src/main/resources/reference.conf#L357-L572
Allow for configurability of HTTP thread count settings
Related to [#4722
](https://github.com/civiform/civiform/issues/4722)

Add play http thread pool variables

---

browser-test/src/security.test.ts
server/app/controllers/applicant/ApplicantProgramsController.java
server/test/controllers/applicant/ApplicantProgramsControllerTest.java

Revised the behavior of `ApplicantProgramsController` to redirect user to home page if authorization fails. Getting a 401 response is not helping anyone.
I removed the browser tests, because the browser just shows the home page, and the test cannot tell if this is for an old session or the new one. The new behavior is covered by controller tests and has also been tested manually.
1. Go to CiviForm address (any environment)
1. Copy URL
1. Click end session
1. Create new tab
1. Paste the URL copied in step 2
1. Verify user is redirected to home page with a different numeric value in the URL
Fixes #5528

Redirect to home if user is not authorized in ApplicantProgramsController

---

server/app/services/question/QuestionOption.java
server/conf/evolutions/default/57.sql
server/test/services/question/types/QuestionOptionTest.java

Migrates the `question_options` fields of `questions` to have an admin name, which will be used when the answer is exported via the API. If an option doesn't have an `en_US` translation, the option id is used.
Previously, `question_options` field was a JSON array of options, each of which look like:
```js
{
"id": 1,
"displayOrder": 1,
"localizedOptionText": {
"isRequired": true,
"translations": {
"en_US": "SMEG blue retro toaster"
}
}
},
```
With this migration, each now has an additional `adminName` field that is set from the default locale's option text:
```js
{
"id": 1,
"adminName": "SMEG blue retro toaster",
"displayOrder": 1,
"localizedOptionText": {
"isRequired": true,
"translations": {
"en_US": "SMEG blue retro toaster"
}
}
},
```
For now, this is not exposed to the user; we just …

Add admin names to QuestionOptions

---

server/app/services/applicant/ApplicantService.java

We look up question data on the program admin page in order to determine eligibility status, but we don't need to do this if the user hasn't started any applications.
This reduces the number of question calls from 1x per program to 1x total.
There are further improvements we can make, but this is the first step.
This change also removes a call to get applicant info, which doesn't seem to be used.
#5514

Remove database call to get question data on index page if not needed

---

server/app/services/applicant/question/MultiSelectQuestion.java
server/app/services/applicant/question/SingleSelectQuestion.java
server/app/services/export/QuestionJsonPresenter.java
server/app/services/question/types/MultiOptionQuestionDefinition.java
server/app/views/api/ApiDocsView.java
server/test/services/applicant/question/MultiSelectQuestionTest.java
server/test/services/applicant/question/SingleSelectQuestionTest.java
server/test/services/export/AbstractExporterTest.java
server/test/services/export/JsonExporterTest.java
server/test/services/question/types/MultiOptionQuestionDefinitionTest.java

Updates the JSON API to use the new `adminName` field on QuestionOptions, instead of retrieving the localized user-facing text.
This is not a user facing change, as the `QuestionOption` still just sets the admin name to the default locale's text for now.
n/a - This is not a user-facing change.
n/a
n/a
n/a
This is part of #4862

Update JSON to use admin names

---

server/app/auth/oidc/CiviformOidcProfileCreator.java
server/app/filters/RecordCookieSizeFilter.java
server/conf/application.conf
server/test/filters/RecordCookieSizeFilterTest.java

Create filter to record the size of the `PLAY_SESSION` cookie.
There is an upper limit of 4096 bytes, and we'd like to be able to see where we stand.
Tested on a dev instance and can see recorded metrics.

Create filter to record PLAY_SESSION cookie size

---

server/app/models/Question.java
server/app/services/question/LocalizedQuestionOption.java
server/app/services/question/QuestionOption.java
server/app/services/question/types/QuestionDefinition.java
server/app/views/admin/questions/QuestionConfig.java
server/test/forms/translation/MultiOptionQuestionTranslationFormTest.java
server/test/models/QuestionTest.java
server/test/services/applicant/question/MultiSelectQuestionTest.java
server/test/services/applicant/question/SingleSelectQuestionTest.java
server/test/services/question/types/MultiOptionQuestionDefinitionTest.java
server/test/services/question/types/QuestionDefinitionTest.java
server/test/services/question/types/QuestionOptionTest.java

- Adds new `create()` methods to `QuestionOption` that take an `adminName`
- Updates the QuestionDefinitions and other nearby code to use admin names
We'll update code in phases, see #4862 for the work plan.
n/a - no user facing changes.
n/a
n/a
n/a
Part of #4862

Update QuestionDefinitions to use option adminNames

---

.github/pull_request_template.md

Fixing links that we moved from docs.civiform.us to the github wiki

Updating broken links on pull_request_template

---

server/app/services/program/predicate/PredicateValue.java
server/app/services/question/types/MultiOptionQuestionDefinition.java
server/test/services/program/predicate/PredicateExpressionNodeTest.java
server/test/services/program/predicate/PredicateValueTest.java

Updates the PredicateValue logic to use immutable question option admin names, instead of the user-facing text.
Changes tests back to using admin names (they were updated to use the user-facing text in #5573)
We're updating code in phases, see https://github.com/civiform/civiform/issues/4862 for the work plan and additional context.
n/a
n/a
n/a
n/a
This is part of #4862

Upate PredicateValue logic to use question option admin names

---

browser-test/src/admin_dropdown_create_and_edit.test.ts
server/app/controllers/admin/AdminQuestionController.java
server/app/forms/MultiOptionQuestionForm.java
server/app/services/question/QuestionOption.java
server/app/views/admin/questions/QuestionConfig.java
server/app/views/questiontypes/ApplicantQuestionRendererFactory.java
server/test/controllers/admin/AdminQuestionControllerTest.java
server/test/forms/CheckboxQuestionFormTest.java
server/test/forms/DropdownQuestionFormTest.java
server/test/forms/MultiOptionQuestionFormTest.java
server/test/forms/RadioButtonQuestionFormTest.java
server/test/services/applicant/ApplicantServiceTest.java
server/test/services/question/types/QuestionOptionTest.java
server/test/views/admin/question/QuestionConfigTest.java
server/test/views/questiontypes/CheckboxQuestionRendererTest.java
server/test/views/questiontypes/DropdownQuestionRendererTest.java
server/test/views/questiontypes/RadioButtonQuestionRendererTest.java

Updates question form processing logic to support admin names, and removes final uses of the deprecated `QuestionOption::create()` overloads that don't have `adminName` as a parameter.
Notes on the logic:
- The MultiOptionQuestionForm validates that it's provided a a form that can be turned into a valid `QuestionDefinition`, but not that the `QuestionDefinition` is one we'd want to save.
- The `AdminQuestionController` is responsible for merging the new `QuestionDefinition` with the existing one.
Also:
- Option admin names are included in the form itself, but the input is hidden. The next PR will be to update the form and all the browser tests support a user actually providing an option admin name.
- Because the admin name input box is hidden, when processing new options in the form we …

Update frontend related code to use admin names

---

server/app/views/BaseHtmlLayout.java

We currently restrict the `STAGING_ADD_NOINDEX_META_TAG` to only work in dev and staging, but we should allow this to work anytime it is set..
Fixes #5635

Allow production sites to set the no index meta tag

---

server/app/assets/javascripts/main.ts
server/app/views/admin/programs/ProgramApplicationListView.java

"Return" should trigger an action in Applications Search form
"Return" should trigger an action in Applications Search form
Fixes #5464

"Return" should trigger an action in Applications Search form

---

bin/remove-dev

Fix spelling in bin/remove-dev

Fix spelling in bin/remove-dev

---

docker-compose.yml
localstack/localstack.Dockerfile

Localstack was updated last Friday from v2.2.0 to [v2.3.0](https://github.com/civiform/civiform/pull/5690)/[v2.3.1](https://github.com/civiform/civiform/pull/5693); it is now returning 500 error codes. 
Tried switching to using their new S3 engine with env var `PROVIDER_OVERRIDE_S3=v3` no luck. Even using the our current settings `PROVIDER_OVERRIDE_S3=legacy` fails. 
We can get more details setting env vars `LS_LOG=trace` and `DEBUG=1` in the `docker-compose` file
Rollback back for now.

Localstack v2.3.x returning 500s

---

server/app/services/settings/SettingsManifest.java
server/conf/env-var-docs.json

This PR marks variables "required" in `env-var-docs.json` if they are required as a part of deployment. If a variable is marked as "required" here and is not present in the `civiform-config.sh` file, the deployment will exit with [an error](https://github.com/civiform/cloud-deploy-infra/blob/40c339725e080607a22708279e320ce656ff3cab/cloud/shared/bin/lib/config_loader.py#L293). 
The list of "required" vars is pulled from the shared [`variable_definitions.json`](https://github.com/civiform/cloud-deploy-infra/blob/main/cloud/shared/variable_definitions.json) file in `cloud-deploy-infra`. Variables that are listed in `env-var-docs.json` will be deleted from `variable_definitions.json` as a part of cleanup work.
Note: Marking vars as "required" was unblocked by the work to [sync variable …

Mark variables required for deployment as "required" in env-var-docs

---

.github/workflows/pr_server.yaml
.github/workflows/pr_server_skip.yaml

This ensures we don't introduce breaking changes by upgrading one of our docker image versions. It turns out https://github.com/civiform/civiform/pull/5715 wasn't the right file to change. That file will skip any path that isn't part of the list, so we do want Dockerfile in there, but we need "**" before in order for it to not skip any file that ends with Dockerfile. Removed 'prod.Dockerfile', since that's included in '**.Dockerfile'
Fixes https://github.com/civiform/civiform/issues/5705

Run server tests on dockerfile update

---

server/app/models/Version.java
server/app/repository/QuestionRepository.java
server/app/repository/VersionRepository.java
server/app/services/question/ActiveAndDraftQuestions.java
server/app/services/question/ReadOnlyCurrentQuestionServiceImpl.java
server/app/services/question/ReadOnlyVersionedQuestionServiceImpl.java

Refactors places that call `version.getQuestions()` to use a new function `getQuestionsForVersion()`. The new function calls `version.getQuestions()` for now, but in the future we'll set up caching for non-draft versions within that function. For now, no functionality is updated with this change. 
See more information in [doc](https://docs.google.com/document/d/1COr52i3ouS-hGcVL4SqoDLYDdrCwir3rGKbkjE3Tfgw/edit#heading=h.bknox3ib8wpb)
Related to https://github.com/civiform/civiform/issues/5724

Use new function to get questions for a version

---

server/app/auth/ProfileFactory.java
server/app/models/Version.java
server/app/repository/ProgramRepository.java
server/app/repository/VersionRepository.java
server/app/services/applicant/ApplicantService.java
server/app/services/program/ActiveAndDraftPrograms.java
server/app/services/program/ProgramServiceImpl.java

Refactors places that call `version.getPrograms()` to use a new function `getProgramsForVersion()`. The new function calls `version.getPrograms()` for now, but in the future we'll set up caching for non-draft versions within that function. For now, no functionality is updated with this change. 
This is very similar to https://github.com/civiform/civiform/pull/5711
See more information in [doc](https://docs.google.com/document/d/1COr52i3ouS-hGcVL4SqoDLYDdrCwir3rGKbkjE3Tfgw/edit#heading=h.bknox3ib8wpb)
Related to https://github.com/civiform/civiform/issues/5724

Refactor version.getPrograms to be called from versionRepository

---

server/app/controllers/LanguageUtils.java
server/app/services/settings/SettingsManifest.java
server/app/views/LanguageSelector.java
server/conf/application.conf
server/conf/env-var-docs.json
server/test/controllers/HomeControllerWithProfileTest.java
server/test/controllers/LanguageUtilsTest.java
server/test/controllers/applicant/DeepLinkControllerTest.java

This adds a new (optional) setting named `CIVIFORM_APPLICANT_ENABLED_LANGUAGES`. It is an array that takes a list of language codes that same way `CIVIFORM_SUPPORTED_LANGUAGES` does. Whereas `CIVIFORM_SUPPORTED_LANGUAGES` is the system-wide list of languages the platform can use `CIVIFORM_APPLICANT_ENABLED_LANGUAGES` represents the subset of the system-wide languages that are available for applicants to select.
This allows us to add new languages to the system and for program admins to start configuring `programs` and `questions` with new language strings, but not allow applicants to select them until the business deems them to be ready.
Settings are set upon deployment.
Additionally, the auto-selection of the language based on the browser preference has been updated to only allow for …

Adding applicant enabled language support

---

server/app/models/Version.java
server/app/repository/QuestionRepository.java
server/app/repository/VersionRepository.java
server/app/services/program/ProgramServiceImpl.java
server/app/services/question/ActiveAndDraftQuestions.java
server/app/services/question/QuestionService.java
server/app/services/question/ReadOnlyVersionedQuestionServiceImpl.java
server/conf/i18n/README.md
server/test/models/VersionTest.java
server/test/repository/VersionRepositoryTest.java
server/test/services/ProgramBlockValidationTest.java
server/test/services/question/ActiveAndDraftQuestionsTest.java
server/test/services/question/QuestionServiceTest.java
server/test/services/question/ReadOnlyVersionedQuestionServiceImplTest.java

https://github.com/civiform/civiform/pull/5711 refactored places that call `version.getQuestions()` to use a new function `getQuestionsForVersion()`. We'll want to do this in the version class as well and make the method an instance method, which is handled in this PR. By changing it into an instance method, we had to refactor and move some other functions as well. 
See more information in [doc](https://docs.google.com/document/d/1COr52i3ouS-hGcVL4SqoDLYDdrCwir3rGKbkjE3Tfgw/edit#heading=h.bknox3ib8wpb)
Related to https://github.com/civiform/civiform/issues/5724

Continue refactoring code to make getQuestionsForVersion an instance method

---

.github/workflows/tests.yaml

The output of the docker compose command used for the prod-simulator wasn't output the docker logs. I'm doing the same thing the [run-browser-test-env](https://github.com/civiform/civiform/blob/d269c7e1fdb45ebf060ffb4623a83a49e849080e/bin/run-browser-test-env#L150) script does here to redirect output to a file, then cat the file on error. This should give us more info when something fails.

Make the test_prod step output on failure

---

server/app/services/settings/SettingsManifest.java
server/conf/env-var-docs.json
server/conf/helper/feature-flags.conf

Add a feature flag to guard new logic required to support OIDC logout from certain identity providers.

Create feature flag to guard new OIDC logout logic

---

browser-test/src/admin_predicates.test.ts
server/app/assets/javascripts/admin_predicate_configuration.ts
server/app/views/admin/programs/ProgramPredicateConfigureView.java

Enables x-axis scrolling in predicate configurator to allow more than four questions to be used in a single predicate. The UX here is not ideal, but this change makes the feature more capable for the time being. We anticipate a holistic redesign of the predicate configuration UX to be prioritized within the next quarter or two.
Fixes https://github.com/civiform/civiform/issues/5758

Admin can use more than 4 questions in a predicate

---

.github/workflows/tests.yaml

Previous attempt is only outputting info up to when the containers come up and the current step ends. Going to dump the docker compose logs on failure instead. This job is on it's own node so it should only have the prod test related stuff in the logs.

Make the test_prod step output docker compose logs on failure

---

server/app/repository/VersionRepository.java
server/conf/application.conf
server/test/repository/VersionRepositoryTest.java

This change adds caching for for data associated with versions, including questions and programs (gated behind a feature flag). We aren't caching versions themselves, since we don't seem to be requesting any version data except previous version data (from admin flow) and active data. The questionList and programList calls are the most expensive, so going to begin by caching those.
See [doc](https://docs.google.com/document/d/1COr52i3ouS-hGcVL4SqoDLYDdrCwir3rGKbkjE3Tfgw/edit) for more information.

Add version cache implementation gated behind feature flag

---

server/app/auth/DefaultToGuestRedirector.java
server/app/filters/SessionIdFilter.java
server/conf/application.conf
server/test/controllers/HomeControllerAuthenticatedTest.java
server/test/controllers/HomeControllerTest.java
server/test/filters/SessionIdFilterTest.java
server/test/support/CfTestHelpers.java

Add a filter that stores a session id in the browser session.
For OIDC logout, we want to store ID tokens in the database for an applicant. If they are logged in from more than one browser, then we need to index the ID tokens so that the proper one can be retrieved at logout time. We will use this new session key for the key.
Relates to #4359.

Create filter to store a session id.

---

server/app/views/questiontypes/FileUploadQuestionRenderer.java

Make "Choose File" button keyboard accessible.
As an applicant, open a file upload question and verify keyboard tabbing includes the "Choose file" button.
Fixes #5523

Make "Choose File" button keyboard accessible.

---

.github/workflows/pr_server.yaml

Runs presubmits on all PRs, unless the branch starts with `spike/`

Run Presubmits on all PRs

---

server/app/services/geo/esri/EsriClient.java
server/test/resources/esri/findAddressCandidatesWithLine2.json
server/test/services/geo/esri/EsriTestHelper.java
server/test/services/geo/esri/RealEsriClientTest.java

Correctly carry forward address line 2 if populated.
Address line 2 (often considered the apt # line) should be carried forward if there is a value set by the user and no value is returned from address correction. This is because some installs ignore the line for the purpose of finding the location. Other mapping tests check for this, but that appears was at too low a level. Jackson will potentially have internal double quotes on what is really an empty string until you call the `asText` method. This changes adds an addition check for empty string when determining if it should use the default (existing, use supplied value) or the one from the service.
Fixed bug where Address Line 2 does not always get used with address correction. …

Fixing line2 bug

---

server/app/auth/oidc/CiviformOidcProfileCreator.java
server/app/auth/oidc/OidcClientProvider.java
server/app/auth/oidc/OidcClientProviderParams.java
server/app/auth/oidc/admin/AdfsClientProvider.java
server/app/auth/oidc/admin/AdfsProfileCreator.java
server/app/auth/oidc/admin/GenericOidcClientProvider.java
server/app/auth/oidc/admin/GenericOidcProfileCreator.java
server/app/auth/oidc/applicant/ApplicantProfileCreator.java
server/app/auth/oidc/applicant/Auth0ClientProvider.java
server/app/auth/oidc/applicant/GenericApplicantProfileCreator.java
server/app/auth/oidc/applicant/GenericOidcClientProvider.java
server/app/auth/oidc/applicant/IdcsApplicantProfileCreator.java
server/app/auth/oidc/applicant/IdcsClientProvider.java
server/app/auth/oidc/applicant/LoginGovClientProvider.java
server/app/modules/MainModule.java
server/test/auth/ProfileMergeTest.java
server/test/auth/oidc/CiviformOidcProfileCreatorTest.java
server/test/auth/oidc/OidcClientProviderTest.java
server/test/auth/oidc/admin/GenericOidcClientProviderTest.java
server/test/auth/oidc/admin/GenericOidcProfileCreatorTest.java
server/test/auth/oidc/applicant/Auth0ProviderTest.java
server/test/auth/oidc/applicant/GenericApplicantProfileCreatorTest.java
server/test/auth/oidc/applicant/GenericOidcClientProviderTest.java
server/test/auth/oidc/applicant/IdcsClientProviderTest.java
server/test/auth/oidc/applicant/LoginGovClientProviderTest.java

Create `OidcClientProviderParams` class to hold parameters for OidcClientProvider and related classes.
This pure refactoring will simplify upcoming PRs that require additional parameters to support enhanced OIDC logout.

Create class to hold parameters for OidcClientProvider and related classes

---

server/app/repository/ProgramRepository.java
server/app/services/program/ProgramService.java

Refactors places that call `program.getVersions()` to use a new function `getVersionsForProgram()`. The new function calls `program.getVersions()` for now, but in the future we'll set up caching within that function. For now, no functionality is updated with this change. 
See more information in [doc](https://docs.google.com/document/d/1COr52i3ouS-hGcVL4SqoDLYDdrCwir3rGKbkjE3Tfgw/edit#heading=h.bknox3ib8wpb)
Fixes #5833

Refactor program.getVersions to be called from programRepository

---

server/app/repository/ProgramRepository.java
server/app/repository/VersionRepository.java
server/conf/application.conf
server/test/repository/ProgramRepositoryTest.java
server/test/repository/VersionRepositoryTest.java

This change adds caching for for data associated with programs, including versions and program data (gated behind a feature flag).
See [doc](https://docs.google.com/document/d/1COr52i3ouS-hGcVL4SqoDLYDdrCwir3rGKbkjE3Tfgw/edit) for more information.
Fixes #5835

Add program cache implementation behind flag

---

bin/sync-failed-browser-test-images

Script will determine your branch and attempt download an image snapshot artifact. If it finds the archive unzips, places the files where they should be, and removes the "-received" filename extension. From there it's up to the developer to decide to commit them or not.
Pull into the same branch **(preferred)**
```bash
git switch branch-name-that-failed
bin/sync-failed-browser-test-images
```
Pull into your current **active**. Good for testing another branch, but you have to do the work to get the images committed to the correct branch.
```bash
bin/sync-failed-browser-test-images branch-name-that-failed
```
Fixes #4695

Add snapshot sync script

---

bin/sync-failed-browser-test-images

- Provides info on what scope the GITHUB_TOKEN needs.
- Adds extra error handling to give more feed back on artifact download failures

Adding some extra error trapping to aid in problem areas

---

server/app/controllers/dev/seeding/DevDatabaseSeedController.java
server/app/repository/ProgramRepository.java
server/app/repository/VersionRepository.java
server/conf/application.dev-browser-tests.conf

Enable program cache in browser tests. When looking up the program, we check if there is a draft version and in that case we don't use the cache, so an incorrect version doesn't get loaded. In the future, we can further optimize this by either: 
1. Only looking up data from the cache if we're in the applicant flow and calling a separate function from the admin flow that doesn't use the cache if there is a draft version
2. Checking if the user is an admin when attempting to lookup a program and if so then check if there is a draft version and only use the cache if so, and if not always using the cache
Related to #5845

Enable program cache in browser tests

---

bin/build-browser-tests
bin/build-dev
bin/build-dev-oidc
bin/build-formatter
bin/build-localstack-env
bin/build-mock-web-services
bin/build-prod

Adds an optional namespace override for the docker image build scripts. Also adds more details to the docs comment.
This will simplify the instructions listed in https://github.com/civiform/civiform/wiki/Deploy-System-Developer-Guide#building-your-docker-image-locally
Currently does not support pushing to alternate registries due to the `docker login` in `lib/docker.sh` logging into default registry (docker.io).
Since it defaults to the original value existing usage in GitHub actions do not need to be modified.
`bin/build-dev` defaults to current value of "civiform" and would be `civiform/civiform-dev:latest`
`NAMESPACE=alt-namespace bin/build-dev` will use "alt-namespace" and would be `alt_namespace/civiform-dev:latest` …

Adding optional namespace to image build scripts

---

.github/ISSUE_TEMPLATE/translations_rotation.md

Add a link to the transifex page that shows which strings are untranslated and include a section for the bug creator to add the last translated string
Also update the task to create the next translation bug when the translations are submitted (as opposed to after translation is complete) to avoid any lag

Update translation bug template

---

bin/build-and-push-image-for-testing

The deployment system needs to be able to resolve a specific commit from an image tag in order to generate configuration during the deployment. Adding the short SHA to images built for testing allows this to happen.
See https://github.com/civiform/cloud-deploy-infra/pull/269

Add short sha to images built for testing

---

server/app/controllers/dev/seeding/DevDatabaseSeedTask.java

The UI calls blocks "screens". We often use the dev seeded data for demos, which confuses non-technical users when they see the titles of the blocks as "Block 1" etc instead of "Screen 1".

Title dev seeded blocks "screen" not "block"

---

server/app/controllers/monitoring/MetricsController.java
server/app/repository/ProgramRepository.java
server/app/repository/QueryProfileLocationBuilder.java
server/app/repository/QueryUtils.java
server/app/repository/VersionRepository.java
server/test/controllers/monitoring/MetricsControllerTest.java

Add a profile location and class name to our database query metrics, so we can better see which queries are still being executed to analyze the benefit of the cache and how we can further optimize it.
This adds this data specifically to the VersionRepository and ProgramRepository class, but we will extend this to other repository files in the future. 
Fixes #5958

Add additional data to database query metrics for prometheus 

---

server/app/views/admin/programs/ProgramBaseView.java
server/app/views/admin/programs/ProgramBlocksView.java
server/app/views/admin/programs/ProgramPredicateConfigureView.java
server/app/views/admin/programs/ProgramPredicatesEditViewV2.java
server/app/views/style/AdminStyles.java

Updates `ProgramBaseView` to do all the header button rendering. Specific admin program views now just pass the buttons that they want to the render method.
For #5676 we're going to add a third "Edit program image" button, and this refactor helps add that button more easily.
As an admin:
1) View a program that doesn't have a draft -> verify button says "Edit program" not "Edit program details". Verify clicking on "Edit program" reloads the page to then show the program as editable.
2) View a draft program -> verify "Edit program details" and "Preview as applicant" buttons appear.
2) Add or edit a visibility condition -> verify "Edit program details" …

Put program header button rendering all in one place.

---

server/app/filters/SessionIdFilter.java
server/test/filters/SessionIdFilterTest.java

Populate session id unconditionally, rather than only when certain feature flags are enabled.
This prevents error messages due to a startup race condition like:
`[warn] SettingsManifest - Settings not found on request when looking up value for ADMIN_OIDC_ENHANCED_LOGOUT_ENABLED`

Populate session id unconditionally

---

server/app/auth/IdentityProviderType.java
server/app/auth/oidc/CiviformOidcProfileCreator.java
server/app/auth/oidc/admin/AdfsProfileCreator.java
server/app/auth/oidc/admin/GenericOidcProfileCreator.java
server/app/auth/oidc/applicant/ApplicantProfileCreator.java
server/test/auth/oidc/admin/GenericOidcProfileCreatorTest.java
server/test/auth/oidc/applicant/GenericApplicantProfileCreatorTest.java

Add a method that allows us to distinguish between admin and applicant profile creators.
Subsequent PRs will use this information during callback processing to check the appropriate feature flag for new logout processing.
I added test cases to existing test suites, but did not create any test suites just to test the new method.

Distinguish between admin and applicant profile creators

---

browser-test/src/auth.test.ts
server/app/auth/CiviFormProfileMerger.java
server/app/auth/TriFunction.java
server/app/auth/oidc/CiviformOidcLogoutActionBuilder.java
server/app/auth/oidc/CiviformOidcProfileCreator.java
server/app/auth/oidc/CustomOidcLogoutRequest.java
server/app/auth/oidc/OidcClientProvider.java
server/app/auth/oidc/OidcClientProviderParams.java
server/app/auth/oidc/admin/AdfsClientProvider.java
server/app/auth/oidc/admin/GenericOidcClientProvider.java
server/app/auth/oidc/applicant/ApplicantProfileCreator.java
server/app/auth/oidc/applicant/GenericOidcClientProvider.java
server/app/auth/oidc/applicant/IdcsClientProvider.java
server/app/modules/MainModule.java
server/app/repository/AccountRepository.java
server/test/auth/CiviFormProfileMergerTest.java
server/test/auth/ProfileMergeTest.java
server/test/auth/oidc/CiviformOidcLogoutActionBuilderTest.java
server/test/auth/oidc/CiviformOidcProfileCreatorTest.java
server/test/auth/oidc/CustomOidcLogoutRequestTest.java
server/test/auth/oidc/IdTokensTest.java
server/test/auth/oidc/OidcClientProviderTest.java
server/test/auth/oidc/admin/GenericOidcClientProviderTest.java
server/test/auth/oidc/admin/GenericOidcProfileCreatorTest.java
server/test/auth/oidc/applicant/Auth0ProviderTest.java
server/test/auth/oidc/applicant/GenericApplicantProfileCreatorTest.java
server/test/auth/oidc/applicant/GenericOidcClientProviderTest.java
server/test/auth/oidc/applicant/IdcsClientProviderTest.java
server/test/auth/oidc/applicant/LoginGovClientProviderTest.java
server/test/repository/AccountRepositoryTest.java

Conditionally populate OIDC ID token in logout request.
This PR has two major parts:
1. Store ID token in db upon successful authentication
2. Retrieve ID token from db upon logout
The bulk of the logic for (1) is in `CiviformOidcProfileCreator.java`. For (2), the changes are concentrated in `CiviformOidcLogoutActionBuilder`. Most of the other files are touched because of changes to constructors to inject additional dependencies or changes in method signatures to propagate additional parameters.
Note that the feature flags must be accessed from the context of the `pac4j` callbacks in order to get the appropriate `Request` object.
This PR adds new handling of identity provider logout for OIDC. The new behavior is guarded by feature flags (`ADMIN_OIDC_ENHANCED_LOGOUT_ENABLED` and …

Populate OIDC id token in logout request

---

server/app/filters/RecordCookieSizeFilter.java
server/app/services/cloud/aws/SimpleEmail.java
server/app/services/geo/esri/EsriClient.java
server/app/services/geo/esri/RealEsriClient.java
server/test/filters/RecordCookieSizeFilterTest.java

Do not guard collection of metrics with a server setting.
We have an existing server setting (`CIVIFORM_SERVER_METRICS_ENABLED`) which is used to enable a [controller action](https://github.com/civiform/civiform/blob/d501333d419bbfa177dfb716f461ca8f658e850d/server/app/controllers/monitoring/MetricsController.java#L61) that exposes metrics for scraping. Some existing code guards collection of metrics with this setting, which is unnecessary, as the cost is negligible and it introduces complexity.
Cleaning these occurrences up means that anyone looking for existing usages won't think they need to add the extra complexity.

Collect metrics unconditionally

---

docker-compose.yml
localstack/localstack.nginx.conf

We have a file upload question which allows users to upload a file. For prod instances, these files get uploaded to a cloud service provider, which is AWS S3 for all current deployments. For local instances, those files instead get uploaded to localstack, which is a local service that mimics AWS S3.
Note that localstack is in a separate Docker container from the rest of civiform.
Currently, some devs get an error when uploading a file and then clicking "Save and Next":
```
<Error>
<Code>InternalError</Code>
<Message>exception while calling s3.PostObject: MyHTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /applicants/19/programs/1/blocks/1/updateFile/false?key=applicant-19%2Fprogram-1%2Fblock-1%2Fgemma-stpjHJGqZyw-unsplash.jpg&bucket=civiform-local-s3 (Caused …
```

Update localstack service to have a link to the civiform service.

---

server/app/models/ProgramModel.java
server/app/models/Question.java
server/app/models/Version.java

We should include a JoinTable annotation to specify which table is the join table and JoinColumn annotations to specify which columns to use.
I was seeing failures with sbt test and these changes resolve those errors.
#5961

Specify additional JPA annotations in models with ManyToMany relationships

---

server/app/auth/ApiAuthenticator.java
server/app/auth/ApiKeyGrants.java
server/app/auth/ProfileFactory.java
server/app/auth/ProfileUtils.java
server/app/auth/UnauthorizedApiRequestException.java
server/app/controllers/api/CiviFormApiController.java
server/app/models/ApiKeyModel.java
server/app/models/Models.java
server/app/repository/ApiKeyRepository.java
server/app/services/apikey/ApiKeyCreationResult.java
server/app/services/apikey/ApiKeyService.java
server/app/views/admin/apikeys/ApiKeyCredentialsView.java
server/app/views/admin/apikeys/ApiKeyIndexView.java
server/test/auth/ApiAuthenticatorTest.java
server/test/controllers/api/ProgramApplicationsApiControllerTest.java
server/test/repository/ApiKeyRepositoryTest.java
server/test/services/apikey/ApiKeyServiceTest.java
server/test/support/ResourceCreator.java

Refactor the "ApiKey" class to be "ApiKeyModel", so it is clear when we may be accessing the database.
#5961

Refactor ApiKey to ApiKeyModel

---

server/app/models/ApplicationEventModel.java
server/app/models/ApplicationModel.java
server/app/models/Models.java
server/app/repository/ApplicationEventRepository.java
server/app/services/applicant/ApplicantService.java
server/app/services/applications/ProgramAdminApplicationService.java
server/test/controllers/admin/AdminApplicationControllerTest.java
server/test/models/ApplicationEventModelTest.java
server/test/models/ApplicationModelTest.java
server/test/repository/ApplicationEventRepositoryTest.java
server/test/repository/ProgramRepositoryTest.java
server/test/services/applicant/ApplicantServiceTest.java
server/test/services/applications/ProgramAdminApplicationServiceTest.java

Refactor the "ApplicationEvent" class to be "ApplicationEventModel", so it is clear when we may be accessing the database.
#5961

Refactor ApplicationEvent to ApplicationEventModel

---

server/app/durablejobs/DurableJob.java
server/app/durablejobs/DurableJobFactory.java
server/app/durablejobs/DurableJobName.java
server/app/durablejobs/DurableJobRegistry.java
server/app/durablejobs/DurableJobRunner.java
server/app/durablejobs/RecurringJobScheduler.java
server/app/durablejobs/jobs/FixApplicantDobDataPathJob.java
server/app/durablejobs/jobs/OldJobCleanupJob.java
server/app/durablejobs/jobs/ReportingDashboardMonthlyRefreshJob.java
server/app/durablejobs/jobs/UnusedAccountCleanupJob.java
server/app/models/Models.java
server/app/models/PersistedDurableJobModel.java
server/app/repository/PersistedDurableJobRepository.java
server/test/durablejobs/DurableJobRegistryTest.java
server/test/durablejobs/DurableJobRunnerTest.java
server/test/durablejobs/DurableJobSchedulerTest.java
server/test/durablejobs/jobs/FixApplicantDobDataPathJobTest.java
server/test/models/PersistedDurableJobModelTest.java
server/test/repository/PersistedDurableJobRepositoryTest.java

Refactor the "PersistedDurableJob" class to be "PersistedDurableJobModel", so it is clear when we may be accessing the database.
#5961

Refactor PersistedDurableJob to PersistedDurableJobModel

---

server/app/models/Models.java
server/app/models/SettingsGroupModel.java
server/app/repository/SettingsGroupRepository.java
server/app/services/applicant/AnswerData.java
server/app/services/settings/SettingsService.java
server/test/repository/SettingsGroupRepositoryTest.java
server/test/services/settings/SettingsServiceTest.java

Refactor the "SettingsGroup" class to be "SettingsGroupModel", so it is clear when we may be accessing the database.
#5961

Refactor SettingsGroup to SettingsGroupModel

---

server/app/auth/StoredFileAcls.java
server/app/controllers/FileController.java
server/app/controllers/applicant/ApplicantProgramBlocksController.java
server/app/models/Models.java
server/app/models/StoredFileModel.java
server/app/repository/StoredFileRepository.java
server/app/services/applicant/ApplicantService.java
server/test/controllers/FileControllerTest.java
server/test/controllers/applicant/ApplicantProgramBlocksControllerTest.java
server/test/repository/StoredFileRepositoryTest.java
server/test/services/applicant/ApplicantServiceTest.java

Refactor the "StoredFile" class to be "StoredFileModel", so it is clear when we may be accessing the database.
#5961

Refactor StoredFile to StoredFileModel

---

bin/build-mock-web-services
bin/pull-image
bin/run-browser-tests
docker-compose.yml

I found some discrepancies in how some scripts are referencing our Docker images. Based on what I've seen the original intent was to have things reference images by the local tag name.
The various `bin/build-*` scripts all add a local tag to the images they build. Example: `civiform/formatter` is locally tagged as `civiform-formatter`. The `bin/pull-image` script however was not consistent in applying the same tags.
Additionally, the `docker-compose.yml` file was referencing two images with the the remote/published name, and not the local tag like it does everything else. This was the source of a problem I noticed a while ago where I'd build the mock web services and it wasn't always using the expected image.
I also removed the `docker.io` registry from `bin/pull-image` as it's already …

Aligning local docker tag names

---

formatter/formatter.Dockerfile
server/app/auth/saml/SamlProfileCreator.java
server/app/controllers/admin/AdminApplicationController.java
server/app/controllers/applicant/ApplicantProgramReviewController.java
server/app/models/ApplicationEventModel.java
server/app/models/ProgramModel.java
server/app/services/ProgramBlockValidation.java
server/app/services/ProgramBlockValidationFactory.java
server/app/services/program/ProgramService.java
server/app/services/settings/SettingsManifest.java
server/app/views/admin/programs/ProgramApplicationListView.java
server/app/views/admin/programs/ProgramBaseView.java
server/app/views/admin/programs/ProgramBlocksView.java
server/test/auth/CiviFormProfileMergerTest.java
server/test/controllers/admin/AdminProgramBlocksControllerTest.java
server/test/controllers/applicant/ApplicantProgramBlocksControllerTest.java
server/test/controllers/applicant/ApplicantProgramReviewControllerTest.java
server/test/services/applicant/ApplicantServiceTest.java
server/test/services/export/AbstractExporterTest.java
server/test/support/ProgramBuilder.java
server/test/support/TestQuestionBank.java

This reduces the on disk size of the image from `1.16 GB` to `892 MB`.
And the size on DockerHub
arch|old size|new size
-|-|-
linux/amd64|474.8 MB|337.34 MB
linux/arm64|405.4 MB|267.6 MB
Changes:
* Base image is Temurin Alpine JDK, removed unneeded secondary java install via `apk`.
* Cleaning apk cache.
* Merging steps to reduce layers.
* Not size related, but also updated the google-java-format version from 1.9 to 1.18.1. The java files in the pr are due to minor changes in how the formatter formats.

Shrink Formatter Image Size

---

formatter/formatter.Dockerfile

Re-adding the `WORKDIR` command back before the `ENTRYPOINT` pointing at the `server` folder. I believe this is why prettier is crawling the `.git` directory in some cases.

Re-add last workdir to server folder

---

server/app/controllers/monitoring/MetricsController.java
server/test/controllers/monitoring/MetricsControllerTest.java

Make unit test pass under sbt-test.
Before this fix, the default `CollectorRegistry` was cleared between test cases, but only initialized statically in the controller. By moving the clear step to the static method in the controller, the counters are always re-initialized after the registry is cleared.
Fixes #5933

Make unit test pass under sbt-test

---

server/app/services/MessageKey.java
server/conf/i18n/messages

This PR adds text to be included in aria labels on links that open in a new tab.
Related to https://github.com/civiform/civiform/issues/5534

Add "opens in new tab" string to be translated for aria labels

---

server/app/auth/CiviFormProfileData.java

It is crucial that the serialization format of `CiviFormProfileData` does not change, so that existing user profiles continue to be honored and in-progress applications are not lost.
However, serialization is apparently quite sensitive to details of the class, beyond the actual data being serialized: see [Serializable (Java Platform SE 7)](https://docs.oracle.com/javase/7/docs/api/java/io/Serializable.html).
The value below corresponds to the value computed by the compiler for the current version of the class. Specifying this value will prevent us from introducing changes that break (de)serialization.
Relates to #5576, #6069

Add serialVersionUID to CiviFormProfileData

---

bin/help

The previous `bin/help` was getting crufty. 
- The formatting wasn't aligning if a file had multiple `#DOC` tokens
- Grepping wouldn't always show the filename
- Only one filename would be printed if there were multiple files with no `#DOC` help text
This replacement to `bin/help` now defaults to printing like this:
*Colors and fonts are subject to the system they are run on and may not match these screenshots*
Additionally the optional flags will allow:
- `-n` to not print colors
- `-s` to print the file name and help text on the same line
- `-h` prints info on these flags
Using `-n` prints in boring black and white. 
Using `-s` will allow for grepping (searching) the help text and have the file name always included. Files missing help text are not display when using this so excess noise …

Make bin/help more helpful

---

server/app/filters/SessionIdFilter.java
server/test/filters/SessionIdFilterTest.java

Add /metrics to exclusion list for SessionIdFilter, since the client does not support redirects.
Fixes #6112

Add /metrics to exclusion list for SessionIdFilter

---

server/app/controllers/monitoring/MetricsController.java
server/test/controllers/monitoring/MetricsControllerTest.java

It looks like we were clearing the default prometheus metrics by adding the clear method in the MetricsController
Reverts civiform/civiform#6010

Fix issue with prometheus metrics

---

server/app/controllers/admin/AdminQuestionController.java
server/app/services/question/QuestionService.java
server/app/services/question/types/MultiOptionQuestionDefinition.java
server/app/services/question/types/QuestionDefinition.java
server/test/services/question/types/QuestionDefinitionTest.java

Updates option admin name validation to only validate _new_ option admin names, so existing admin names don't have to be changed when updating a question.
Details:
- Updates `QuestionDefintion#validate()` to optionally take the previous question definition
- Only validates that new option admin names match the requirements in #5839, allowing existing admin names to be saved when the question is updated
Updates option admin name validation to only validate _new_ option admin names, so existing admin names don't have to be changed when updating a question.
- [n/a] Followed steps to [internationalize new …

Only validate new admin names

---

bin/run-browser-tests-local

Remove unconditional setting of `BASE_URL` from `run-browser-tests-local`.
Before this change, the script would overwrite the value of `BASE_URL` in the environment. Instead, we set it to a default value if it is unset.

Honor BASE_URL from environment in run-browser-tests-local

---

browser-test/src/api_docs.test.ts

Skipping unreliable api docs tests on probers for now so as not to block deployment, but intend to fix the problem with this issue: 
#6158

Skipping unreliable api docs tests on probers for now

---

browser-test/src/civiform_admin_question_list.test.ts
server/app/views/components/ProgramQuestionBank.java

Made question title break into next line when it is long and overflow, so we can see `Add` button on the screen.
Fixes ##5975

Fix text overflow issue on question title

---

server/test/services/cloud/aws/ApplicantSimpleStorageTest.java
server/test/services/cloud/aws/AwsApplicantStorageTest.java
test-support/unit-test-docker-compose.yml

Adds a test for the `AwsApplicantStorage` class. This will be useful because the program images feature will be making some changes to applicant file upload storage (to share code when possible), so this test can try and catch regressions.
#5676

Add AwsApplicantStorageTest

---

server/app/services/settings/SettingsManifest.java
server/conf/application.dev-browser-tests.conf
server/conf/application.dev.conf
server/conf/env-var-docs.json
server/conf/helper/feature-flags.conf

Add feature flag for new applicant URL schema. **Do not enable until further notice**

Add feature flag for new applicant URL schema

---

browser-test/src/support/index.ts
server/app/auth/CiviFormProfile.java
server/app/auth/CiviFormProfileData.java
server/app/auth/CiviFormProfileMerger.java
server/app/auth/ProfileFactory.java
server/app/auth/controllers/MissingOptionalException.java
server/app/controllers/CiviFormController.java
server/app/controllers/HomeController.java
server/app/controllers/applicant/ApplicantInformationController.java
server/app/controllers/applicant/ApplicantProgramReviewController.java
server/app/controllers/applicant/ApplicantProgramsController.java
server/app/controllers/applicant/ApplicantRoutes.java
server/app/controllers/applicant/UpsellController.java
server/app/views/applicant/ApplicantCommonIntakeUpsellCreateAccountView.java
server/app/views/applicant/ApplicantUpsellCreateAccountView.java
server/app/views/applicant/ApplicantUpsellView.java
server/app/views/applicant/IneligibleBlockView.java
server/app/views/applicant/PreventDuplicateSubmissionView.java
server/app/views/applicant/TrustedIntermediaryDashboardView.java
server/conf/routes
server/test/controllers/HomeControllerTest.java
server/test/controllers/HomeControllerWithProfileTest.java
server/test/controllers/admin/AdminApplicationControllerTest.java
server/test/controllers/applicant/ApplicantProgramsControllerTest.java
server/test/controllers/applicant/ApplicantRoutesTest.java

Currently, routes for applicant actions include the applicant id in the URL. We want to remove these for applicant actions to provide cleaner URLs for sharing and bookmarking. To accomplish this, we will store the applicant id in the user profile. A profile attribute is set in `ProfileFactory.createNewApplicant()` which will achieve the goal for every newly-created profile. If a user with an existing (legacy) profile authenticates successfully, then we also set the applicant id in the `CiviFormProfileMerger`.
This PR only affects the `ApplicantProgramsController.index()` action; subsequent PRs will address the other applicant actions.
This PR renames the existing `index()` method to `indexWithApplicantId()`. A new `index()` method extracts the applicant ID from the profile and then calls …

Remove applicant id from URLs for index action

---

server/app/controllers/CiviFormController.java
server/app/controllers/applicant/ApplicantProgramReviewController.java
server/app/controllers/applicant/ApplicantProgramsController.java
server/app/controllers/applicant/ApplicantRoutes.java
server/app/controllers/applicant/ProgramSlugHandler.java
server/app/modules/MainModule.java
server/app/views/admin/programs/ProgramAdministratorProgramListView.java
server/app/views/admin/programs/ProgramFormBuilder.java
server/app/views/admin/programs/ProgramIndexView.java
server/app/views/applicant/IneligibleBlockView.java
server/app/views/applicant/ProgramIndexView.java
server/conf/routes
server/test/controllers/applicant/ApplicantProgramsControllerTest.java
server/test/controllers/applicant/ApplicantRoutesTest.java
server/test/controllers/applicant/ProgramSlugHandlerTest.java

Remove applicant id from application programs view URL.
* define a new `ApplicantRoutes.view()` method that delegates to the existing method, 
* which is renamed to `viewWithApplicantId()`, and
This PR has a complication. Before this PR, the existing route was:
```
/applicants/:applicantId/programs/:programId
```
Since Play does not permit overloaded controller methods, when we remove the leading `/applicants/:applicantId` path components, that results in a conflict with this route:
```
/programs/:programSlug
```
Therefore the new `ApplicantProgramsController.view()` method needs to disambiguate between the two cases. At this point, we no longer need a separate `DeepLinkController`, so this class …

Remove applicant id from application programs view URL

---

server/app/repository/QuestionRepository.java
server/app/repository/VersionRepository.java
server/app/services/program/ProgramService.java

There are places we are calling getDraftVersionOrCreate when we really don't need to create a draft version, we just need to get it if it exists. This causes extra versions to be created unnecessarily.

Avoid creating a draft program when we don't need to

---

browser-test/src/support/index.ts

Revise `loginAsTestUserAwsStaging()` to match a full URL, not just a path.
The Playwright [docs](https://playwright.dev/docs/api/class-page#page-wait-for-url) for `Page.waitForUrl()` indicate that a full URL is expected. This test doesn't run in hermetic environments, so we only saw the failure when it ran as a prober test against AWS staging.
Tested via:
```
$ BASE_URL=https://staging-aws.civiform.dev bin/run-browser-tests admin_application_statuses.test.ts
```

Match full URL in loginAsTestUserAwsStaging()

---

browser-test/src/support/index.ts

Specify a better matching URL for `loginAsTestUserAwsStaging()`.
Before #5946, the test waited for this pattern, which matched all applicant routes: `**/applicants/**`. As we remove the applicant ID from routes (work in progress), this pattern no longer matches all applicant routes.
Replacing this with `**/programs/**` is not quite right either, as one of the routes is simply `/programs` without the trailing slash. Using `**/programs**` as the glob to be matched covers this case as well.

Specify a better matching URL for loginAsTestUserAwsStaging()

---

browser-test/src/support/index.ts

Replace (invalid) glob with regex.
The globstar pattern (`**`) only applies to path components (before or after a `/`).

Use regex instead of glob for URL pattern

---

server/app/controllers/applicant/ApplicantProgramReviewController.java
server/app/controllers/applicant/ApplicantProgramsController.java
server/app/controllers/applicant/ApplicantRoutes.java
server/app/views/applicant/ApplicantProgramSummaryView.java
server/conf/routes
server/test/controllers/applicant/ApplicantProgramsControllerTest.java
server/test/controllers/applicant/ApplicantRoutesTest.java

Remove applicant id from application programs edit URL.
* define a new `ApplicantRoutes.edit()` method that delegates to the existing method, 
* which is renamed to `editWithApplicantId()`, and

Remove applicant id from URLs for edit action

---

server/app/controllers/admin/AdminProgramPreviewController.java
server/app/controllers/applicant/ApplicantProgramBlocksController.java
server/app/controllers/applicant/ApplicantProgramReviewController.java
server/app/controllers/applicant/ApplicantProgramsController.java
server/app/controllers/applicant/ApplicantRoutes.java
server/app/controllers/applicant/ProgramSlugHandler.java
server/app/views/ApplicationBaseView.java
server/app/views/applicant/ApplicantCommonIntakeUpsellCreateAccountView.java
server/app/views/applicant/ApplicantProgramInfoView.java
server/app/views/applicant/IneligibleBlockView.java
server/app/views/applicant/PreventDuplicateSubmissionView.java
server/app/views/applicant/ProgramIndexView.java
server/conf/routes
server/test/controllers/admin/AdminProgramPreviewControllerTest.java
server/test/controllers/applicant/ApplicantProgramBlocksControllerTest.java
server/test/controllers/applicant/ApplicantProgramReviewControllerTest.java
server/test/controllers/applicant/ApplicantProgramsControllerTest.java
server/test/controllers/applicant/ApplicantRoutesTest.java
server/test/controllers/applicant/ProgramSlugHandlerTest.java

Remove applicant id from application programs review URL.
* define a new `ApplicantProgramReviewController.review()` method that delegates to the existing method, 
* which is renamed to `reviewWithApplicantId()`.
* Create a new `ApplicantRoutes.review()` method which determines which controller method to invoke, and

Remove applicant id from URL for review action

---

server/app/controllers/applicant/ApplicantProgramReviewController.java
server/app/controllers/applicant/ApplicantRoutes.java
server/app/views/applicant/ApplicantProgramSummaryView.java
server/conf/routes
server/test/controllers/applicant/ApplicantProgramReviewControllerTest.java
server/test/controllers/applicant/ApplicantRoutesTest.java

Remove applicant id from application programs submit URL.
* define a new `ApplicantProgramReviewController.submit()` method that delegates to the existing method, 
* which is renamed to `submitWithApplicantId()`.
* Create a new `ApplicantRoutes.submit()` method which determines which controller method to invoke, and

Remove applicant id from URLs for submit action

---

server/conf/i18n/messages
server/test/conf/MessagesTest.java

Add text to the messages file that we plan to use, based on suggestions from Leslie https://github.com/civiform/civiform/issues/5893. 
See full before and after text [here](https://docs.google.com/spreadsheets/d/1KkGB8AsvxuSEJipVXnZIuXqshMUSh6KjBldr-Zv_gkI/edit#gid=0)
These will be swapped in for the "before" texts once we get the translations back (likely in early - mid January)

Add main page text revisions to messages file for translation

---

server/app/controllers/applicant/ApplicantProgramBlocksController.java
server/app/controllers/applicant/ApplicantProgramsController.java
server/app/controllers/applicant/ApplicantRoutes.java
server/app/views/applicant/ApplicantProgramSummaryView.java
server/conf/routes
server/test/controllers/applicant/ApplicantProgramBlocksControllerTest.java
server/test/controllers/applicant/ApplicantProgramsControllerTest.java
server/test/controllers/applicant/ApplicantRoutesTest.java

Remove applicant id from application program block edit URL.
* define a new `ApplicantProgramBlockController.edit()` method that delegates to the existing method, 
* which is renamed to `editWithApplicantId()`.
* Create a new `ApplicantRoutes.blockEdit()` method which determines which controller method to invoke, and

Remove applicant id from URLs for block edit action

---

server/app/auth/ProfileUtils.java
server/app/controllers/admin/AdminProgramPreviewController.java
server/app/controllers/applicant/ApplicantInformationController.java
server/app/controllers/applicant/ApplicantProgramBlocksController.java
server/app/controllers/applicant/ApplicantProgramReviewController.java
server/app/controllers/applicant/ApplicantProgramsController.java
server/test/controllers/WithMockedProfiles.java

Introduce a convenience method to `ProfileUtils` to reduce code noise.
Note that this doesn't remove *all* existing cases of `profile.orElseThrow(() -> ...)`. There are places where a controller has already retrieved an `Optional<CiviFormProfile>` and redirected the user to the home page for the empty case. Since we've already gone to the trouble to locate the profile at that point, it didn't seem worth it to use the new convenience method.

Introduce ProfileUtils.currentProfileOrThrow()

---

server/conf/application.dev.conf
server/test/controllers/applicant/ApplicantProgramBlocksControllerTest.java
server/test/controllers/applicant/ApplicantProgramsControllerTest.java
server/test/controllers/applicant/ProgramSlugHandlerTest.java

Enable the new applicant URL schema for dev servers.
This also modifies behavior of unit tests, so a number of test cases were modified to reflect the schema revisions to date.

Enable new applicant URL schema for dev servers

---

server/app/auth/oidc/admin/GenericOidcProfileCreator.java
server/test/auth/oidc/admin/GenericOidcProfileCreatorTest.java

Before this change, `isGlobalAdmin()` would throw a `NullPointerException` if the OIDC profile did not contain the `groups` claim. Now we handle that case and return `false`.

Handle missing groups attribute in OIDC profile

---

server/app/controllers/applicant/ApplicantProgramBlocksController.java
server/app/controllers/applicant/ApplicantRoutes.java
server/app/views/applicant/AddressCorrectionBlockView.java
server/app/views/applicant/ApplicantProgramSummaryView.java
server/conf/routes
server/test/controllers/applicant/ApplicantRoutesTest.java

Remove applicant id from applicant block review URL.
* define a new `ApplicantProgramBlocksController.review()` method that delegates to the existing method, 
* which is renamed to `reviewWithApplicantId()`.
* Create a new `ApplicantRoutes.blockReview()` method which determines which controller method to invoke, and

Remove applicant id from URLs for block review action

---

browser-test/src/admin_program_image.test.ts

The program image tests are failing during the prober tests in a staging deploy because the program images are stored in a *new* cloud storage bucket but the deploy scripts haven't been correctly updated to create that new bucket: https://github.com/civiform/civiform-staging-deploy/actions/runs/7269688382.
Ignore the tests for now so that deploys can succeed.
Epic: #5676

Ignore program image tests

---

server/app/controllers/applicant/ApplicantProgramBlocksController.java
server/app/controllers/applicant/ApplicantRoutes.java
server/app/views/applicant/AddressCorrectionBlockView.java
server/conf/routes
server/test/controllers/applicant/ApplicantRoutesTest.java

Remove applicant id from applicant confirm address URL.
* define a new `ApplicantProgramBlocksController.confirmAddress()` method that delegates to the existing method, 
* which is renamed to `confirmAddressWithApplicantId()`.
* Create a new `ApplicantRoutes.confirmAddress()` method which determines which controller method to invoke, and

Remove applicant id from URLs for confirm address action

---

browser-test/src/civiform_admin_program_statuses.test.ts
server/app/forms/admin/ProgramStatusesForm.java
server/app/views/applicant/ApplicantProgramInfoView.java

Limiting the status of a program to 35 characters. With the change, issue #5000 will get fixed. Below is a screenshot of status being updated to a 35-character-length string not overflowing the banner.
Fixes #5000

Added character length limit of program status

---

server/app/controllers/applicant/ApplicantProgramBlocksController.java
server/app/controllers/applicant/ApplicantRoutes.java
server/app/views/applicant/ApplicantFileUploadRenderer.java
server/conf/routes
server/test/controllers/applicant/ApplicantProgramBlocksControllerTest.java
server/test/controllers/applicant/ApplicantRoutesTest.java
server/test/views/questiontypes/ApplicantQuestionRendererFactoryTest.java

Remove applicant id from applicant update file URL.
* define a new `ApplicantProgramBlocksController.updateFile()` method that delegates to the existing method, 
* which is renamed to `updateFileWithApplicantId()`.
* Create a new `ApplicantRoutes.updateFile()` method which determines which controller method to invoke, and

Remove applicant id from URLs for update file action

---

server/app/controllers/applicant/ApplicantProgramBlocksController.java
server/app/controllers/applicant/ApplicantRoutes.java
server/app/views/applicant/ApplicantFileUploadRenderer.java
server/app/views/applicant/ApplicantProgramBlockEditView.java
server/conf/routes
server/test/controllers/applicant/ApplicantProgramBlocksControllerTest.java
server/test/controllers/applicant/ApplicantProgramReviewControllerTest.java
server/test/controllers/applicant/ApplicantRoutesTest.java
server/test/views/applicant/ApplicantProgramBlockEditViewTest.java

Remove applicant id from applicant update block URL.
* define a new `ApplicantProgramBlocksController.update()` method that delegates to the existing method, 
* which is renamed to `updateWithApplicantId()`.
* Create a new `ApplicantRoutes.updateBlock()` method which determines which controller method to invoke, and

Remove applicant id from URLs for update block action

---

server/app/repository/VersionRepository.java
server/app/services/program/ProgramService.java
server/test/services/applicant/ApplicantServiceTest.java

When we load program associations (which we do whenever we load the program pages), if that program is active, we are currently doing a publishing dry run of an active and draft version each time that loads twice (which makes many db calls we don't need). We should only need to publish a dry run of a program in the admin flow. With this PR, we are now checking if the program is a draft in a way that doesn't make as many calls and if it is active, we don't load the extra data and do the publishing dry run. We also add some comments to make it more clear when this is happening and remove some print statements from a related test (and make some updates to publishing). We should take a holistic approach on how to separate applicant and admin calls, but this should be a big step in reducing …

Reduce unnecessary calls to create and publish a program

---

server/app/controllers/dev/seeding/DevDatabaseSeedController.java
server/app/repository/VersionRepository.java
server/app/services/program/ProgramService.java
server/test/repository/VersionRepositoryTest.java
server/test/services/applicant/ApplicantServiceTest.java

Remove cases where we're clearing the cache when we don't need to. We thought this was needed, but really we were making unnecessary calls to create and drafts when we didn't need to. Since we aren't doing that anymore after https://github.com/civiform/civiform/pull/6244, we can remove this here. Additionally, we should never clear the cache outside of the dev instance because if there is more than one task, this wouldn't work as intended (entity may exist in one cache even if it was cleared in another). Added a comment to make that clear.

Update cache clearing behavior

---

server/app/repository/QuestionRepository.java
server/app/repository/VersionRepository.java
server/app/services/question/ActiveAndDraftQuestions.java
server/app/services/question/QuestionService.java
server/app/services/question/ReadOnlyCurrentQuestionServiceImpl.java
server/app/services/question/ReadOnlyVersionedQuestionServiceImpl.java
server/test/repository/VersionRepositoryTest.java
server/test/support/ProgramBuilder.java

Refactors places that call `question.getQuestionDefinition()` to use a new function `getQuestionDefinition()`. The new function calls `question.getQuestionDefinition()` for now, but in the future we can set up caching for non-draft questions within that function. For now, no functionality is updated with this change. 
#6263

Refactor question.getQuestionDefinition to be called from questionRepository

---

browser-test/src/applicant_application_index.test.ts
server/app/views/applicant/ProgramCardViewRenderer.java

This PR uses the `ProgramDefinition.localizedSummaryImageDescription` field as the program image's alt-text if that description is set for the user's language. If not, we fall back to using the program name as the alt-text.
Epic #5676 
Fixes #6003 (sub task)

[Program Card Images] Add alt text when rendering program cards with images.

---

server/app/services/cloud/aws/AwsApplicantStorage.java
server/app/services/cloud/aws/AwsPublicStorage.java
server/app/services/cloud/aws/AwsStorageUtils.java
server/test/services/cloud/aws/AwsApplicantStorageTest.java
server/test/services/cloud/aws/AwsPublicStorageTest.java

After I got the new AWS bucket for program images working on a staging deployment, I noticed a bug with the formatting of the program image URL.
The image URL should be something like:
```
https://caitlinshk-test-permissions-bucket.s3.amazonaws.com/program-summary-image/program-1/my-program-image.png
```
but the actual URL getting created was:
```
https://caitlinshk-test-permissions-bucket.s3.amazonaws.com//program-summary-image/program-1/my-program-image.png
```
Notice the two `/`s after `amazonaws.com`. This is incorrect and causes the program image to not load. Removing one of the `/`s makes the image load correctly.
It looks like our fake version of AWS for local development (LocalStack) does *not* contain a `/` at the end of its base URL, whereas the prod version of AWS *does* …

[Program Card Images] Remove double "/" from program image URL

---

server/app/controllers/dev/seeding/DevDatabaseSeedController.java
server/app/views/dev/DatabaseSeedView.java
server/conf/routes
server/test/controllers/dev/seeding/DevDatabaseSeedControllerTest.java

Changes with this PR:
1. Created a new page - dev/seed/data where we load seed data
2. Added a button on dev/seed page to direct user(devs) to dev/seed/data page
3. Added a button on dev/seed/data page to direct user(devs) back to dev/seed page
dev/seed page
dev/seed/data page
Fixes #5210

Added dev/seed/data page to avoid loading data in dev/seed page

---

browser-test/src/admin_program_list.test.ts
server/app/views/admin/programs/ProgramIndexView.java

When the Universal Questions feature flag is turned on, single program publish doesn't work with program admin names that include invalid characters. These characters are no longer allowed to be saved as `adminName` but this breaks with legacy data which impacts at least Seattle.
This fix changes the logic to reference `program.slug` instead of `program.adminName` when creating the reference name for the modal. `program.slug` is a [created from the admin name](https://github.com/civiform/civiform/blob/5e665380c10d7db32b1e8f1abdc264ada2455f68/server/app/services/program/ProgramDefinition.java#L495) with special characters stripped out.
1. Login as an admin and create a program
2. From the admin program index …

Fix single program publish bug

---

server/app/views/admin/programs/ProgramPredicatesEditViewV2.java

On page load a random UUID is used for as the Id on the form to replace eligibility predicates. Sometimes the UUID would start with a digit. This is valid for an HTML Id, but not for CSS or Javascript's `document.querySelector`. This would cause an random error when trying use that form when the Id started with a digit.
This PR adds a fixed prefix to the Id before the UUID so this no long occurs.
Prevent admin program eligibility predicate form from getting an Id value that starts with a digit (0-9).
Related to #5372

Prevent form id from starting with a digit

---

server/app/services/cloud/PublicFileNameFormatter.java

This PR adds some documentation to the `PublicFileNameFormatter` class warning that if the file key format is changed, then the cloud storage bucket permissions may also need to be changed.
Epic #5676

[Program Card Images] Add warning to PublicFileNameFormatter about modifying file keys

---

.github/labeler.yml

Automatically label PRs with changed files in the .github directory with the ignore-for-release.

Auto label .github changes as ignore-for-release

---

formatter/fmt

This updates the prettier check in bin/fmt to include Markdown files in addition to TS and JSON. Additionally, it optimizes the call to prettier to only operate on changed and untracked files, speeding it up a bit.

Update fmt prettier check to include Markdown

---

formatter/fmt

EsLint was running on all files all the time when calling `bin/fmt`. This will limit it to only files that have been changed.

Filter eslint calls to only changed files

---

server/app/views/dev/DatabaseSeedView.java

The addition of new buttons over time made a giant list of buttons on the dev seed page. This adds some formatting to make it easier to read
Before
After
Fixes #6286

Format dev seed page

---

.github/workflows/tests.yaml

The artifact upload action no longer overwrites existing artifacts uploaded from a previous run attempt. This adds a counter to the upload to allow for additional uploads when re-running a run.
Related: https://github.com/civiform/civiform/pull/6320

Append Run Attempt Number to Artifact Uploads

---

server/app/views/questiontypes/EnumeratorQuestionRenderer.java

For enumeration questions in narrow screens (<640px), use 1 column for the grid instead of 2. This prevents the text from the remove button from overflowing the input for long question titles (either in English or translated).
Fixes #5822

When screen is very narrow, use 1 column instead of 2 to prevent text overflow

---

server/app/controllers/admin/AdminApplicationController.java
server/app/controllers/applicant/ApplicantProgramReviewController.java
server/app/services/applicant/ReadOnlyApplicantProgramService.java
server/app/services/applicant/ReadOnlyApplicantProgramServiceImpl.java
server/app/services/export/CsvExporter.java
server/app/services/export/CsvExporterService.java
server/app/services/export/JsonExporter.java
server/app/services/export/PdfExporter.java
server/test/services/applicant/ReadOnlyApplicantProgramServiceImplTest.java

Renaming `getSummaryData()` to `getSummaryDataOnlyActive()` since this function only returns summary data from active blocks in an application. There will be another function `getSummaryDataOnlyHidden()` in the next PR for hidden questions in pdf.
Part of Fixes ##6288

Renaming getSummaryData() function to getSummaryDataOnlyActive()

---

.github/workflows/sbom_generator.yaml

Triggers when a release is created (or manually) to generate a Software Bill of Materials (SBOM). It looks at the `civiform/civiform:VERSION` docker image. We can include additional files for each docker image if needed, but starting with the prod image for now.
I opted for a separate GH action in case we ever needed to re-run on a previous release.
The `anchore/sbom-action`, while not Maintained by GitHub, is listed in their [documentation](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/using-the-dependency-submission-api#generating-and-submitting-a-software-bill-of-materials-sbom). The GitHub maintained option hasn't been updated in over a year, and the Microsoft one is more complicated to run.
I tested this in a separate repo and …

Adding GitHub Action to Generate SBOM

---

server/app/services/cloud/aws/AwsApplicantStorage.java
server/app/services/cloud/aws/AwsStorageUtils.java
server/conf/helper/cloud.conf

This change is a minor improvement to how we create the URL to connect to LocalStack (a fake version of AWS used during local development):
1. Include the ".s3" part of the URI directly in the configuration file instead of adding it later in the Java code.
2. Have the `localStackEndpoint` method return a `URI` instead of a `String` so that `AwsApplicantStorage doesn't need to convert the `String` back to a `URI`. (And a future PR for program images also requires a `URI` object instead of a `String`.)
1. On a local server, verify uploading a file as an applicant still works.
2. On a local server, verify uploading a program image as an admin still works. …

Have better formatting for the LocalStack URL

---

.github/workflows/sbom_generator.yaml

Turns out the created trigger doesn't fire for drafts >_<
Switching to published which will trigger when the release is create immediately or in draft state
For [reference](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release)

Switch release trigger to published

---

server/app/views/questiontypes/PhoneQuestionRenderer.java
server/test/views/questiontypes/ApplicantQuestionRendererFactoryTest.java

Updates PhoneQuestionRenderer to use ApplicantCompositeQuestionRenderer instead of ApplicantSingleQuestionRenderer. This is because phone questions consist of 2 questions (country and phone number). By making it a composite question, the  ApplicantCompositeQuestionRenderer correctly adds the aria-describedby on the outer container (instead of being on just 1 of the two question elements). This makes it so the question is read when the user first enters the question, no matter which field they navigate to (similar to an address question).
Fixes #5526

Ensure phone questions have the correct aria-describedby

---

server/app/views/components/FieldWithLabel.java
server/app/views/questiontypes/AddressQuestionRenderer.java
server/app/views/questiontypes/CurrencyQuestionRenderer.java
server/app/views/questiontypes/EmailQuestionRenderer.java
server/app/views/questiontypes/PhoneQuestionRenderer.java
server/test/views/questiontypes/CurrencyQuestionRendererTest.java

Adds inputmode attribute for inputs so that an appropriate keyboard is used on mobile.
- numeric keyboard for zip
- decimal keyboard for currency
- email keyboard for email
- numeric keyboard for phone
Fixes #5867

Add appropriate inputmode attribute for questions

---

server/conf/helper/feature-flags.conf

Enable new applicant URL schema everywhere. Applicant URLs will no longer contain the leading `/applicants/:id` portion of the URL path.
The new schema is already enabled in staging (AWS and Seattle).
Fixes #5576

Enable new applicant URL schema

---

server/app/views/applicant/ApplicantLayout.java

Prevent header from overflowing the width of the screen on mobile.
Fixes #6388

Make header flow better on narrow screens

---

server/app/views/HtmlBundle.java
server/conf/routes

I've noticed an increase of 404's in my logs for requests to the `apple-touch-icon`. For reference the the `apple-touch-icon` gets called when the user attempts to bookmark the site, but there may be other times.
This is not an exhaustive addition for supporting various sized icons, but it'll be a quick win for serving something to the user. This will use the same image as the favicon.

Adding link for apple-touch-icon

---

server/app/views/applicant/ApplicantFileUploadRenderer.java

Add aria-live attribute to file upload label so it is announced when the file is uploaded
1) enable a screenreader (I tested with Chromevox)
2) Upload a file to a file upload question
3) When it is done uploading and the UI updates, the screenreader should read the updated text "File uploaded: file_name"
Fixes #3590

add aria-live attribute to file upload label

---

server/app/views/admin/programs/ProgramImageView.java

This is a small PR that restricts the mimetype for program images to be only PNGs or JPEGs. We don't want admins uploading SVGs because they don't render correctly in the `<img>` element (maybe we could make them render correctly but that doesn't seem worth the time), and we also don't want admins uploading GIFs because that would make the homepage too distracting.
1. Enable the PROGRAM_CARD_IMAGES flag.
2. As an admin, navigate to the edit program images page.
3. When uploading a file, verify that only the PNGs and JPEGs are the files allowed by the filepicker.
Epic #5676

[Program Card Images] Only allow PNGs and JPEGs for program card images

---

browser-test/src/support/ti_dashboard.ts
browser-test/src/trusted_intermediary.test.ts
server/app/services/ti/TrustedIntermediaryService.java
server/test/services/ti/TrustedIntermediaryServiceTest.java

When searching for clients on the TI dashboard, if the user cleared their search parameters, an empty list was returned.  This meant that if a TI searched for a client and then wanted to see the full list afterwards, they were not able to do that.  This PR fixes that bug so that when a client clears their search parameters, they are able to see the full list of clients.
1. Log in as a trusted intermediary and go to the TI dashboard.
2. Search for a client either by name or date of birth.
3. Delete the content from the search fields and click "Search".
4. Note that the full client list is shown.

Fixed TI client search bug so that cleared search parameters return the full client list

---

docker-compose.dev.yml

Set the pgadmin version to 8.2 (current release) for the dev docker compose file. It was stuck on an old version of 7.x. Renovatebot will keep it updated going forward.

Set the pgadmin version

---

server/app/services/MessageKey.java
server/conf/i18n/messages

Add new message to be translated for date validation (but don't use it yet). The existing message references an incorrect date format. See https://github.com/civiform/civiform/issues/3078 for details

add new date validation message for translation

---

server/app/services/MessageKey.java
server/conf/i18n/messages

Add message for "x of y" progress indicator so it can be translated. See https://github.com/civiform/civiform/issues/3068

Add message for x of y progress status for translation

---

server/app/assets/javascripts/file_upload.ts

The File uploaded: X text wasn't updating when the file was changed because we were only updating it when there was no existing file. This removes that condition
Go to a file upload question, upload a file, then upload a different file. Verify that the filename updates correctly
Fixes #6221

Update file upload file label even if there is an existing label

---

server/conf/helper/auth.conf

This is a standard we use for the different applicant authentication providers to either use the specific variable for that provider or to accept the APPLICANT_OIDC_DISCOVERY_URI.  i.e. you can see this done for [login.gov](https://github.com/civiform/civiform/blob/0087d5d017951ca45ff588c9d84ae1f080bbc037/server/conf/helper/auth.conf#L92)
Allow IDCS users to specify the discovery URI as the APPLICANT_OIDC_DISCOVERY_URI
Fixes #6445
and this should also resolve the issue with Seattle's prod deployment #4687

Update configuration file to accept APPLICANT_OIDC_DISCOVERY_URI for IDCS_DISCOVERY_URI

---

SECURITY.md

Our Releases now generate a Software Bill of Materials (SBOM) as recommended by the US Cybersecurity & Infrastructure Security Agency. The SBOM can be found on the Releases page for each release.
Related: #6371

Updating security document with info on SBOM

---

server/app/views/applicant/AddressCorrectionBlockView.java
server/app/views/applicant/ApplicantLayout.java
server/app/views/applicant/ApplicantProgramBlockEditView.java
server/app/views/applicant/ApplicantProgramSummaryView.java

Use the message created in https://github.com/civiform/civiform/pull/6431 . The translations aren't done yet, but it was already untranslated, so this won't change anything in the meantime
Fixes #3068

Use X of Y message in applicant layout

---

bin/sync-failed-browser-test-images

The github action upload-artifact changed at v4 to require all uploads to have separate file names. This fixes the script to get them all

Updating image sync script

---

SECURITY.md

Add details about patch rewards program to security page
Add link to [Patch Rewards Program](https://bughunters.google.com/about/rules/4928084514701312/patch-rewards-program-rules), which compensates for vulnerability fixes to CiviForm.
Fixes #6475

Add information about patch rewards program

---

server/app/views/admin/AdminLayout.java
server/app/views/admin/programs/ProgramApplicationView.java
server/app/views/admin/programs/ProgramFormBuilder.java
server/app/views/admin/questions/QuestionsListView.java
server/app/views/applicant/ApplicantLayout.java
server/app/views/applicant/ApplicantProgramInfoView.java
server/app/views/applicant/ProgramCardViewRenderer.java
server/app/views/components/ButtonStyles.java
server/app/views/components/LinkElement.java
server/app/views/questiontypes/CheckboxQuestionRenderer.java
server/app/views/questiontypes/RadioButtonQuestionRenderer.java
server/app/views/style/ApplicantStyles.java
server/app/views/style/BaseStyles.java

Renamed java fields named for Seattle. New names match other color class names.
- `BG_SEATTLE_BLUE` :point_right: `BG_CIVIFORM_BLUE`
- `TEXT_SEATTLE_BLUE` :point_right: `TEXT_CIVIFORM_BLUE`
- `BORDER_SEATTLE_BLUE` :point_right: `BORDER_CIVIFORM_BLUE`
CSS class names to be done later.

Renaming base style fields with Seattle in them

---

server/app/views/support/UnconfirmedIdcsEmailBugView.java

This page was created to handle legacy accounts created in Jan 2022 to handle Seattle accounts that didn't have an authority_id. This was back when we thought email was going to be unique. This was added about a month after Seattle went live with CiviForm. Uses that have logged back in since Jan 2022 would have gotten the authority_id added. Anyone that doesn't have one at this point hasn't been in the system for two years. We'll log for a little bit to see if anyone ends up here. Ultimately though we are fine remove this at this point.

Adding warning log message if this page is called

---

README.md

Seattle's Staging has been failing due to false positive on a toggle on the admin page for quite some time. It looks bad to keep having the red show on the project so I'm removing it, at least until it can be working. Sometimes it maybe have been green, but only when I skip running probers.

Removing Seattle Staging Badge

---

renovate.json

Default file matching for renovate does not catch all of our compose files. 
I think I have the format for this correct, but there may be a little churn to get it right.

Add Missing Compose Files to Renovate

---

server/app/auth/CiviFormProfile.java
server/app/auth/ProfileFactory.java
server/app/controllers/applicant/ApplicantProgramBlocksController.java
server/app/controllers/applicant/ApplicantProgramReviewController.java
server/app/controllers/applicant/ApplicantProgramsController.java
server/app/controllers/applicant/ApplicantRoutes.java
server/app/services/settings/SettingsManifest.java
server/conf/application.dev-browser-tests.conf
server/conf/application.dev.conf
server/conf/env-var-docs.json
server/conf/helper/feature-flags.conf
server/test/controllers/HomeControllerTest.java
server/test/controllers/HomeControllerWithProfileTest.java
server/test/controllers/applicant/ApplicantRoutesTest.java
server/test/views/applicant/ApplicantProgramBlockEditViewTest.java
server/test/views/questiontypes/ApplicantQuestionRendererFactoryTest.java

Retire new_applicant_url_schema_enabled feature flag. The default flag value was set to `true` in #6253.
Relates to #6270

Retire new_applicant_url_schema_enabled feature flag

---

renovate.json

Second try
Default file matching for renovate does not catch all of our compose files. 
I think I have the format for this correct, but there may be a little churn to get it right.

Second attempt to get missing compose files in renovate

---

server/app/services/applicant/ReadOnlyApplicantProgramService.java
server/app/services/applicant/ReadOnlyApplicantProgramServiceImpl.java
server/app/services/export/JsonExporter.java
server/test/services/export/AbstractExporterTest.java
server/test/services/export/JsonExporterTest.java

Includes questions hidden from applicants in the API response.
Previously, only questions shown to applicants were included in the API response. This means that if a question was skipped due to a visibility predicate, it wasn't included in the API.
That's proven to be an unexpected behavior, so with this change all questions will be included in the API response, regardless of visibility.
- [n/a] Followed steps to [internationalize new strings](https://github.com/civiform/civiform/wiki/Internationalization-%28i18n%29#internationalization-for-application-strings)
- [n/a] Wrote browser tests using the …

Include hidden questions in JSON API

---

browser-test/src/admin_program_image.test.ts
browser-test/src/support/admin_program_image.ts
server/app/controllers/admin/AdminProgramImageController.java
server/app/controllers/admin/ImageDescriptionNotRemovableException.java
server/app/services/program/ProgramService.java
server/app/views/admin/programs/ProgramImageView.java
server/test/controllers/admin/AdminProgramImageControllerTest.java
server/test/services/program/ProgramServiceTest.java

For program card images, we want to require admins to provide an alt-text description before providing an image. This PR also prevents admins from deleting the alt-text description if there's currently an image set.
1. Enable PROGRAM_CARD_IMAGES flag.
2. Edit a program then click "Edit program image".
3. Set a description.
4. Upload an image.
5. Try removing the description by deleting the text in the description box and clicking "Save image description".
6. Verify an error toast appears and the previously-set description is still there.
Part of epic #5676

[Program Card Images] Prevent admin from removing alt-text description if there's an image set

---

bin/run-browser-tests

The `bin/run-browser-tests` script currently  runs the browser tests and immediately and removes the container. This also removes the anonymous volume which stores the node_modules. This means it's downloading everything each time.
Changing this to:
* Smartly remove the container if the image has changed
* Run and detach the container and pop into a bash
* Then runs the tests in the resident container
This speeds up running tests when the container is already up and prevents re-downloading each time 

Making the browser test container stay resident

---

server/app/models/QuestionModel.java
server/conf/evolutions/default/63.sql
server/test/repository/QuestionRepositoryTest.java

The `questions` table contains the following columns: `legacy_question_text`, `legacy_question_help_text`, `legacy_question_options`.
These columns were removed prior to **June 2021**. Seattle's earliest production application is June 16th and all our questions records have these three columns set to null.
No other deployments would have occurred until well after this change. It's safe and time to clean this up.
Removing three obsolete columns from the questions table: legacy_question_text, legacy_question_help_text, and legacy_question_options.

Removing Legacy Question Columns

---

server/app/controllers/applicant/ApplicantProgramBlocksController.java
server/app/services/applicant/ApplicantService.java
server/test/services/applicant/ApplicantServiceTest.java

Fixing NullPointerException when address is invalid. This occurred when the address was configured for validation, and the user tried to move forward to the not eligible page.
Fixes #5831

Fixing NullPointerException When Address Is Invalid

---

server/app/controllers/admin/AdminApplicationController.java
server/app/controllers/api/ProgramApplicationsApiController.java
server/app/modules/DurableJobModule.java
server/app/services/DateConverter.java
server/app/services/apikey/ApiKeyService.java
server/test/repository/ApplicationRepositoryTest.java
server/test/services/DateConverterTest.java
server/test/services/apikey/ApiKeyServiceTest.java
server/test/services/reporting/ReportingServiceTest.java

Fix for Application count mismatch between CVS exports and Reporting.
Fix 1- Internally we store all submit time as UTC. On trying to the retrieve the records for dd-mm-yyyy, we should also covert it to UTC time zone so that we will get the same results.
Fix 2 - When converting java.sql.Timestamp into MM/yyyy format for reporting, there is no need to add time zone information as the time stamp is always set to the beginning of the month eg. 01-01-2024 00:00:000. So SimpleDateTimeFormatter is enough to extract the MM/yyyy format.  
Fix for Application count mismatch between CVS exports and Reporting.
If instructions are needed for manual testing by …

Fix for Application count mismatch between CVS exports and Reporting

---

server/app/controllers/admin/AdminApplicationController.java
server/app/services/DateConverter.java
server/test/services/DateConverterTest.java

Reverting changes in CSV export filter to use LocalDateTime. Commit Id - f6367df
In this PR I am reverting Fix-1.
Original Description  - 
Fix for Application count mismatch between CVS exports and Reporting.
Fix 1- Internally we store all submit time as UTC. On trying to the retrieve the records for dd-mm-yyyy, we should also covert it to UTC time zone so that we will get the same results.
Fix 2 - When converting java.sql.Timestamp into MM/yyyy format for reporting, there is no need to add time zone information as the time stamp is always set to the beginning of the month eg. 01-01-2024 00:00:000. So SimpleDateTimeFormatter is enough to extract the MM/yyyy format.
Reverting the Fix-1 from original PR - Commit Id - f6367df …

Reverting changes in CSV export filter to use LocalDateTime

---

server/conf/helper/feature-flags.conf
server/test/models/ProgramModelTest.java
server/test/services/applicant/ApplicantServiceTest.java

Turn on the program caching feature by default, since we've tested it in Seattle and on staging.
This change involved updating some tests to ensure programs have unique IDs.
Fixes #5745

Turn on cache for program data by default

---

browser-test/src/applicant_application_index.test.ts
server/app/controllers/admin/AdminProgramImageController.java
server/app/services/cloud/PublicStorageClient.java
server/app/services/cloud/aws/AwsPublicStorage.java
server/app/services/cloud/azure/AzurePublicStorage.java
server/app/views/admin/programs/ProgramImageView.java
server/test/controllers/admin/AdminProgramImageControllerTest.java
server/test/services/cloud/aws/AwsPublicStorageTest.java
server/test/services/cloud/azure/AzurePublicStorageTest.java
server/test/support/cloud/FakePublicStorageClient.java

When an admin uploads a program image, the image is first sent to AWS. Once AWS has successfully stored the image, it calls `AdminProgramImageController#updateFileKey` with the bucket the file was stored in and the key identifying the file. This PR updates that `#updateFileKey` method to verify that the bucket name in the request matches the public bucket name that we have in our config. The bucket names should always match, but this is an extra safeguard around keeping applicant data safe. Because applicant files are stored in a different bucket with a different name, this check should ensure that applicant-uploaded files are never stored as the program image key somehow.
Read the full guidelines for PRs [here](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#creatin …

[Program Card Images] Check bucket is correct before storing file key

---

browser-test/src/admin_program_creation.test.ts
server/app/controllers/admin/AdminProgramBlockQuestionsController.java
server/app/views/admin/programs/ProgramBlocksView.java
server/conf/routes

Toggling address correction on and off kept the next toggle state in a hidden field on the page. It lead to quite some confusion when trying to add a new test. This now toggles the value based on what's stored in the database. Technically we don't need to even store the hidden fields on the page, but it's the only good way in browser tests to check. How when you inspect the field it shows the current state.

Making Address Correction Toggle Value Show the Current State.

---

server/app/controllers/applicant/ApplicantRoutes.java
server/app/views/ApplicationBaseView.java
server/test/controllers/applicant/ApplicantRoutesTest.java

The "Previous" button in the application flow will redirect users to the previous block, or to the review page if they're at the first block. We'll need to reuse this logic in a future PR that changes the functionality of the "Previous" button, so this PR pulls out the logic into the `ApplicantRoutes` file so it can be reused.
- Click "Previous" while on the first block of an application. Verify it takes you to the review page.
- Click "Previous" while on a further block of an application. Verify it takes you to the previous block.
Related to #6450

Move logic for Previous button route to ApplicantRoutes

---

browser-test/src/application_navigation.test.ts
browser-test/src/support/admin_programs.ts
server/app/views/admin/programs/ProgramBlocksView.java

Adding these two tests to cover using Address eligibility as a Visibility Condition that is NOT gated. This works and I don't want to find it gets broken at some point. I'm not certain, but I don't think this is working because it was designed this way. Getting it working is quite convoluted. I suspect it's a happy accident of overlapping features. 
I'll write up some documentation in a separate PR. I'm attaching videos of the output for reference when I write docs.
Fixes #6505
[ admin setup of the program.webm](https://github.com/civiform/civiform/assets/195162/0730ddea-2d05-4b91-806e-0e599e724ac9)
[when address is eligible show hidden …

Adding tests to cover using address as a visibility condition

---

server/app/controllers/dev/seeding/DevDatabaseSeedController.java
server/app/repository/ProgramRepository.java
server/app/services/program/ProgramService.java
server/conf/application.conf
server/conf/application.dev-browser-tests.conf
server/conf/application.test.conf
server/test/repository/ProgramRepositoryTest.java
server/test/services/applicant/ApplicantServiceTest.java
server/test/services/program/ProgramServiceTest.java

The full program definition is an expensive database lookup operation, since it involves looking up question data.
We should set this program definition in the cache when the program is active or obsolete.
We can create a follow up PR to refactor programModel.getProgramDefinition() calls to use this cached program definition if it is present and also ensure syncProgramDefinitionQuestions and its callers use the cache if its available (if not a draft program).
This PR enables the question_cache_enabled feature flag in tests, and updates some tests to create draft programs instead of active ones when edits are still being made to the program (because otherwise it will be cached)
Get and set full program definition data from the cache (with the question data included), if the question cache …

Create a cache for the full program definition

---

server/app/repository/ApplicationRepository.java
server/app/repository/VersionRepository.java

https://github.com/civiform/civiform/pull/6611 created a new getProgramDefinition function, which uses the program def cache if available. 
This refactors the remaining repository files to use the new method.
https://github.com/civiform/civiform/issues/6466

[Refactor] Update repository files to use new getProgramDefinition function

---

browser-test/jest.config.js

Adds `verbose: true` to our browser test config so that browser test runs will print each test case they ran instead of just the test file name:

Add `verbose: true` to browser tests

---

server/app/auth/ProfileFactory.java
server/app/controllers/admin/ProgramAdminManagementController.java
server/app/models/ApplicationModel.java
server/app/services/applicant/ApplicantService.java
server/app/services/applications/ProgramAdminApplicationService.java
server/app/services/program/ProgramService.java
server/test/services/applications/ProgramAdminApplicationServiceTest.java

https://github.com/civiform/civiform/pull/6611 created a new getProgramDefinition function, which uses the program def cache if available. 
This refactors additional files to use the new method. We also remove a helper function on the ApplicationModel.
https://github.com/civiform/civiform/issues/6466

[Refactor] Update additional files to use new getProgramDefinition function

---

server/app/services/program/ActiveAndDraftPrograms.java

This just renames the getProgramDefinition in ActiveAndDraftQuestions to getFullProgramDefinition to make it clearer that this function gets the full program defintion with question data.

[Refactor] rename getProgramDefinition to getFullProgramDefinition when the definition includes all question data

---

browser-test/src/application_navigation.test.ts

These tests fail if not using the mock web services since data is different from live endpoints. Don't run them on staging environments.
All this does is wrap the tests in an `if (isLocalDevEnvironment())`. The diff looks busy, but the test itself remains unchanged.

Don't run address visiblity test on staging

---

server/app/views/HtmlBundle.java

I missed making this only point at the webroot when I added it originally so it was failing to load on any deep routes.

Make apple icon be at webroot

---

browser-test/src/admin_program_list.test.ts

Disable the `program list with different active and draft image` test on staging because it's only flaky on staging.
Run `admin_program_list` test locally and verify the `program list with different active and draft image` test still runs.
Related to #6624

Disable flaky program images test in staging

---

server/app/services/question/types/QuestionDefinition.java
server/test/services/question/types/QuestionDefinitionTest.java

Bug fix - On creating new Admin Names for question options, we do not check for case sensitivity with existing admin names.
Bug fix - On creating new Admin Names for question options, we do not check for case sensitivity with existing admin names.
(https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-reviewers).
Fixes #6605

Adding casing comparison to Option Admin names. 

---

browser-test/src/application_navigation.test.ts
server/app/controllers/applicant/ApplicantProgramBlocksController.java
server/app/views/applicant/AddressCorrectionBlockView.java
server/test/controllers/applicant/ApplicantProgramBlocksControllerTest.java

A bit of background: https://github.com/civiform/civiform/pull/6544 and https://github.com/civiform/civiform/pull/6547 updated the "Review" and "Previous" buttons on application screens to save the applicant's data or show an error modal if there are validation errors. However, the address correction view uses a different view than the typical application screen, so its "Review" and "Previous" buttons need special handling. https://github.com/civiform/civiform/pull/6589 updated the "Review" button to also save the selected suggested address when "Review" is clicked and this PR updates the "Previous" button.
This PR:
1) Updates `AddressCorrectionBlockView` to use the new "Previous" button that saves data.
2) In `ApplicantProgramBlocksController`, updates how the route for the "Previous" …

When "Previous" is clicked on address correction screen, go back to block with address question

---

server/app/views/components/Modal.java

This PR updates the Javadoc of `Modal.java` to say it's deprecated and encourages people to use `ViewUtils#makeUSWDSModal` instead.
Related to https://github.com/civiform/civiform/issues/6264

Update Modal.java Javadoc to say it's deprecated

---

server/app/services/PhoneValidationResult.java
server/app/services/PhoneValidationUtils.java
server/test/services/PhoneValidationUtilsTest.java

Adding ability to find country code based on phone number.
We will be removing the country dropdown from the phone question control in the future and this will test each of the supported countries and selects the one that is valid or returns the a validation error message.
Adding unit tests.

Find country code based on phone number

---

.github/workflows/auto_request_review.yml

Don't run auto request review on forks. This fails due to permissions problems. See #6681 for info on a likely better solution.

Don't run auto request review on forks

---

server/app/assets/javascripts/enumerator.ts

patch for this issue: https://issuetracker.google.com/issues/324680545
By using innerText, it will avoid the risk of HTML injection, as these properties automatically escape any HTML special characters in the provided text. This helps prevent cross-site scripting (XSS) vulnerabilities by treating the input as plain text rather than interpreted HTML. Always be cautious when dealing with user input or dynamic content to prevent security risks.

DOM text reinterpreted as HTML {Patch}

---

server/app/assets/javascripts/enumerator.ts

Set the button text via innerText instead of innerHTML.
Fixing incorrectly spelled words in comments.
This is related to #6677.

Swapping to use innertext

---

server/test/services/applicant/question/FileUploadQuestionTest.java
server/test/services/applicant/question/MultiSelectQuestionTest.java
server/test/services/applicant/question/NameQuestionTest.java
server/test/services/applicant/question/PhoneQuestionTest.java
server/test/services/applicant/question/SingleSelectQuestionTest.java

Adding `extends ResetPostgres` to these tests so they can successfully run on their own.

Fixing some tests to run individually

---

server/app/controllers/dev/seeding/DevDatabaseSeedController.java
server/app/repository/ProgramRepository.java
server/conf/application.conf
server/test/repository/ProgramRepositoryTest.java
server/test/services/program/ProgramServiceTest.java

Rename the program definition cache to be clear that it is the full version of the program definition.
https://github.com/civiform/civiform/issues/6711

[Refactor] Rename the program definition cache

---

browser-test/src/file.test.ts
server/app/assets/javascripts/file_upload.ts

If a user opens a file upload question and clicks "Save & next" without uploading a file, we display an error saying "Error: Please select a file" to inform them that they have to add a file before continuing. However, if a user then uploads a file, the "Error: Please select a file" text sticks around, which is confusing to the user.
This PR does two things:
1. Removes the error text once a file is uploaded.
2. Simplifies the logic around showing / hiding the error text. 
Doing item 2 means that the diff for `file_upload.ts` is pretty large, but it's mostly the same code, just refactored to be hopefully easier to read.
1. As an applicant, open a program …

Remove "Please select a file" error when a user uploads a file

---

server/app/controllers/admin/AdminReportingController.java
server/app/controllers/api/ApiDocsController.java
server/app/controllers/api/ProgramApplicationsApiController.java
server/app/controllers/applicant/ProgramSlugHandler.java
server/app/services/program/ProgramService.java
server/test/services/program/ProgramServiceTest.java

Rename getActiveProgramDefinitionAsync to getActiveFullProgramDefinitionAsync for clarity that we're getting the full program definition (with question data). See [TDD](https://docs.google.com/document/d/1out9Sg5y7gVQISzB5212P1SJB8saT9XDYFoEVcAkvZk/edit)
https://github.com/civiform/civiform/issues/6711

[Refactor] Rename getActiveProgramDefinitionAsync to getActiveFullProgramDefinitionAsync for clarity

---

server/app/controllers/admin/AdminApplicationController.java
server/app/services/export/CsvExporterService.java
server/app/services/program/ProgramService.java

Rename getAllProgramDefinitionVersions to getAllVersionsFullProgramDefinition for clarity that we're getting the full program definition (with question data). 
I thought `getAllVersionsFullProgramDefinition` sounded a little clearer than `getAllFullProgramDefinitionVersions`, but going back and forth a bit if you think the second is clearer
See [TDD](https://docs.google.com/document/d/1out9Sg5y7gVQISzB5212P1SJB8saT9XDYFoEVcAkvZk/edit)
https://github.com/civiform/civiform/issues/6711

[Refactor] Rename getAllProgramDefinitionVersions to getAllVersionsFullProgramDefinition for clarity 

---

server/app/auth/ProfileFactory.java
server/app/controllers/admin/ProgramAdminManagementController.java
server/app/models/ProgramModel.java
server/app/repository/ApplicationRepository.java
server/app/repository/ProgramRepository.java
server/app/repository/VersionRepository.java
server/app/services/applicant/ApplicantService.java
server/app/services/applications/ProgramAdminApplicationService.java
server/app/services/program/ProgramService.java
server/app/views/applicant/TrustedIntermediaryDashboardView.java

Update `ProgramRepository.getProgramDefinition` to get the program definition without the question data and rename this for clarity - see [TDD](https://docs.google.com/document/d/1out9Sg5y7gVQISzB5212P1SJB8saT9XDYFoEVcAkvZk/edit)
https://github.com/civiform/civiform/issues/6711

[Refactor] Rename getProgramDefinition to getShallowProgramDefinition for clarity

---

browser-test/src/file.test.ts

Disables the browser tests that are failing in staging due to behavior changes for the `SAVE_ON_ALL_ACTIONS` feature. See https://github.com/civiform/civiform/issues/6737 for more details.

Disable failing file upload browser tests when SAVE_ON_ALL_ACTIONS flag is enabled

---

.github/workflows/pr_env_var_docs.yaml
.github/workflows/tests.yaml

Adding codecov token to github actions to fix error introduced in upgrade to the codecov v4 github action

Adding codecov token to github actions

---

browser-test/package-lock.json
browser-test/package.json
browser-test/playwright.config.ts
browser-test/src/global-teardown.ts
browser-test/src/support/index.ts
server/app/views/admin/apikeys/ApiKeyNewOneView.java

This will populate the old folder structure of `diff_output` and `updated_snapshots` with files from Playwright image snapshot.

Correctly populate diff_output and updated_snapshots folders

---

.github/ISSUE_TEMPLATE/feature_flag.md

When I enabled the `PROGRAM_CARD_IMAGES` flag in dev and staging, I'd forgotten that I had overridden it to be false in the browser tests. This meant that the browser tests were passing locally and on GitHub actions, but failing on staging prober tests because staging now had the flag set to true (see https://civiform.slack.com/archives/C046D5BPVJ9/p1709061594232309). This PR updates our feature flag template to add a separate line item for explicitly re-enabling a flag in browser tests once it's ready.

In feature flag issue template, add separate line item for enabling the flag in browser tests

---

browser-test/src/global-teardown.ts

Fine tuning the paths when moving images to `updated_snapshots` and `diff_output` directories.

Fix image path

---

browser-test/src/application_download.test.ts
server/app/repository/ExportServiceRepository.java
server/app/services/applicant/question/FileUploadQuestion.java
server/app/services/export/CsvExporter.java
server/app/services/export/CsvExporterService.java
server/app/services/program/Column.java
server/app/services/program/CsvExportConfig.java
server/test/services/export/CsvExporterTest.java

Refactor CsvExporter to preserve option admin name casing during export.
Previously, all option admin names were lowercased during the CSV export, causing collisions and the data to appear differently then in the JSON export. Now, option admin name cases are preserved.
See the [Fix for case-insensitive option admin name collision](https://docs.google.com/document/d/15jyNeTn7NItfBM3n2SqvWebbY3WD7E5dD_hIkiuhU-k/edit) doc for more
Details:
- Updates CSV columns for checkbox options to use the heading format `question name (selections - option_admin_name)`
- The `Column` in the CsvExportConfig now optionally includes the option admin name, to support checkbox questions. Before, we were adding the column name to the end of the path, causing it to be lowercased because `Path`s are all …

Preserve option admin name casing in CSV export and update column header format

---

browser-test/src/address.test.ts
browser-test/src/checkbox.test.ts
browser-test/src/currency.test.ts
browser-test/src/phone.test.ts
browser-test/src/text.test.ts

Fixing eslint issues to align with playwright best practices. Rule: prefer-web-first-assertions.
Fun fact: The original code uses `page.isHidden(selector)` which returns the first match even if there are multiple. Probably not what most people would expect.
Both `page.isHidden` and `page.isVisible` are [deprecated](https://playwright.dev/docs/api/class-page#deprecated).

Linting: Prefer web-first assertions

---

server/app/services/MessageKey.java
server/conf/i18n/messages

Adds a string that'll be displayed if a user uploads a file that's too big (currently 100MB for AWS). A future PR will use this string once it's been translated.
String was approved by @sijiayam  and Shannon.
Part of #5675

Add string to warn user if their uploaded file is too large

---

renovate.json

Starting yesterday renovate began failing. After a lot of trial and error I found renovate is failing to parse `server/project/build.properties`. This was recently updated, but rolling back doesn't solve the problem. It seems more like a recent bug in renovate. I have an nearly empty repository that repros the error and I'll be submitting a ticket to the project.
For now I'm just having renovate ignore the build.properties file. I'll create an issue in civiform shortly.
Tested locally with:
```shell
npm install -g renovate
LOG_LEVEL=info npx renovate --platform=local
```

Hide build.properties from renovate

---

renovate.json

Stop ignoring build.properties in renovate. They pushed a fix and doing a dry run passes.
Fixes #6792

Stop ignoring build.properties in renovate

---

docker-compose.yml
server/build.sbt

Errorprone does a great job keeping us from writing code that could be problematic. However it can cause friction while actively developing. For example I can't quickly comment something out temporarily if it leaves an unused variable.
This will allow for running `DISABLE_ERRORPRONE=true bin/run-dev` and to disable error prone on your local machine thus bypassing Errorprone checks.
If not set, the default remains to enforce Errorprone and the CI environment won't override it thus catching anything if someone accidentally pushes code that doesn't pass Errorprone.

Allow disabling of errorprone

---

bin/summarize-release-messages

Script will pull commits since the supplied tag and output part of the commit messages. 
- It will cut out anything after the `Checklist` header.
- It will filter out PR authors of renovate and transifex
- It will filter out PRs tagged with ignore-for-release
- It will print the PR:
- author username
- title
- url
- labels
- text version of the body of the message

Adding script to summarize release messages

---

browser-test/src/admin_program_image.test.ts
browser-test/src/application_navigation.test.ts
browser-test/src/application_review.test.ts
browser-test/src/file.test.ts
browser-test/src/header.test.ts

Continuing the slog work through cleaning up playwright lint issues.
Fixing some lint errors: prefer-web-first-assertions

Fixing prefer-web-first-assertions lint errors #3

---

browser-test/src/admin_program_creation.test.ts
browser-test/src/admin_program_settings.test.ts
browser-test/src/admin_program_translation.test.ts
browser-test/src/number_input.test.ts
browser-test/src/question_lifecycle.test.ts
browser-test/src/support/admin_questions.ts

Continuing the slog work through cleaning up playwright lint issues.
Fixing some lint errors: prefer-web-first-assertions

Fixing prefer-web-first-assertion lint errors #4

---

browser-test/src/application_navigation.test.ts
browser-test/src/file.test.ts
browser-test/src/program_deep_link.test.ts
browser-test/src/support/applicant_questions.ts

Adds a new `validateQuestionIsOnPage` helper method to the `applicantQuestions` helper class so that we don't copy paste the `cf-applicant-question-text` class everywhere.

Add #validateQuestionIsOnPage helper method to browser tests

---

server/app/views/applicant/TrustedIntermediaryDashboardView.java

We call getApplications twice, which will make a database call each time. Instead, we can set this to a variable and use it in each place.
This won't fix the Seattle prod issue, but will reduce load on the database
#6813

Make one less db call on TI dashboard

---

.github/pull_request_template.md

Adds a checkbox to the PR checklist for adding someone from outside your organization (per our discussion in the eng weekly)

Add additional reviewer checkbox to general PR steps

---

.github/release.yml

Per discussion in our [eng weekly](https://docs.google.com/spreadsheets/d/1jXuOWl9TxssHh3A1AkmKi2gva9LRUhE0PQStJa-4yWs/edit#gid=657889699), we want to have a label we can use when a feature is being worked on but is hidden behind a feature flag and isn't yet ready for staging or production testing. I've added a label with the name `under-development` to our list of labels. This PR adds it to the list of labels used when generating our release notes.

Add under-development label

---

.github/pull_request_template.md

Add reference to new `under-development` label in the pr template.

reference under-development label

---

server/app/services/question/types/QuestionDefinition.java
server/app/views/admin/questions/QuestionEditView.java
server/test/services/question/types/QuestionDefinitionTest.java

Remove the requirement that a question that is part of an enumerator have help text containing the text `$this`. It can still be used, but isn't required. 
Updates the on screen instructions to align with the change. Also adds a modicum of formatting to make the instructions more legible.
Will update the docs repo after this goes in.
Example of the one screen Instructions 
Fixes #6784

Allow Question Help Text to Not Require $this

---

server/app/services/MessageKey.java
server/app/views/questiontypes/EnumeratorQuestionRenderer.java
server/conf/i18n/messages

If you're an applicant and you delete one of your answers to an enumerator question, the alert that currently appears only says that the data will be deleted when you click "Next". However, when the `SAVE_ON_ALL_ACTIONS` flag is on, the data will also be deleted if you click "Review" or "Previous". This PR adds a new string that also mentions those buttons. Once translations are on and the `SAVE_ON_ALL_ACTIONS` flag is enabled, we can use this new string and delete the old one.
Part of #6844

Add new string for confirmation message when deleting an enumerator answer

---

bin/generate-settings-manifest

Running `bin/fmt` makes a call to `bin/generate-settings-manifest` to rebuild the settings manifest java file. Most of the time this doesn't need to happen. This will now check if the `server/conf/env-var-docs.json` file has been modified (either in git's unstaged, staged, or committed states) compared to what is in `origin/main`. If it hasn't changed we won't waste the time running it. 
Not running it saves 1-1.5 seconds running `bin/fmt` when you already have the env-var-docs container running. It saves much more time if you don't have the container running.
Additionally this will run if the CI environment variable is set. This means it'll run via GitHub actions. I don't think we really need this, but it's more as a backup to catch changes if they make it in.
Read the full guidelines …

Only regenerate the settings manifest if it needs it

---

.github/workflows/tests.yaml
Dockerfile
bin/build-dev
bin/build-prod
prod.Dockerfile

Our dev and prod dockerfiles thought they were setting the sbt version from the environment variable defined in `bin/lib.sh`. Turns out they were not. This adds in the dockerfile arg needed as well as passing in the sbt version in the bin/build-nnnn scripts.
I am removing the fallback value. If it can't get the value from the SBT_VERSION environment variable (which comes from `server/project/build.properties`) I want it to fail to build. Not quietly use an old version.
In order for this to work in the GitHub actions I'm updating the test.yaml to call the build scripts instead of using direct docker build commands.

Pass in sbt version to dockerfiles

---

load-test/applicant_landing_page.jmx
load-test/applicant_submit_application.jmx
load-test/ti_landing_page.jmx

We created JMeter tests for load testing work and should ensure these are checked in to allow others to run tests on their work and in the future run performance tests automatically.
This also adds a new trusted intermediary test.
I'll plan to create documentation to explain how to run these tests.
Tested locally by running the following for each test:
- testing using jmeter: `jmeter  -n -t load-test/applicant_landing_page.jmx` (maybe needs jmeter install)
- testing using bzt: `pip install bzt` `bzt load-test/applicant_landing_page.jmx`
Fixes #6858, #6859

Check in JMeter tests

---

.github/workflows/run_jmeter_test.yaml

We added some jmeter tests to github, but these can currently only be run by installing jmeter and running locally. We should allow these to be run through a github action.
#6869

Add a github action to run jmeter test

---

bin/dev-show-trace-file

Fixes getting branch name in the playwright trace viewer script.
Not sure why it was working before, but failed now.

Fix Getting Branch Name
