- .github/workflows/run_jmeter_test.yaml
Our github JMeter action was failing because of the incorrect directory name and missing `runs-on`. Added these and tested the action and it now works as expected.
Fixes #6869
> Fix JMeter github action

- browser-test/src/trusted_intermediary.test.ts
- server/app/views/applicant/TrustedIntermediaryDashboardView.java
On the TI dashboard client cards, "# submitted applications" was showing all started applications rather than just the submitted ones.  This fixes that.
1. Log in as a TI.
2. Create a client if you don't already have one.
3. On the client card, click "View applications".
4. Submit an application.
5. Go back to the TI dashboard.
6. Note that the client card now says "1 application submitted" with the program name below.
7. Click "View applications" again.
8. Start an application and click "Save and Next" but don't click "Submit".
9. Go back to the TI dashboard.
10. Note that the client card still says "1 application submitted".
Fixes #6834
> Fix for TI dashboard client cards needing to only show submitted applications

- server/app/views/components/TextFormatter.java
- server/build.sbt
Update owasp Java HTML sanitizer to latest version. 
> [!NOTE]
> Fixing a bug that caused SVG files to render differently after the owasp upgrade. The sanitizer used to treat the SVG `viewBox` attribute as __case-insensitive__ and keep it. The latest version is more strict and the casing for this attribute is now __case-sensitive__.
Fixes #6355
> Updating owasp html sanitizer to latest release

- server/app/controllers/admin/AdminApplicationController.java
- server/app/controllers/api/ProgramApplicationsApiController.java
- server/app/services/export/JsonExporterService.java
- server/app/services/export/ProgramJsonSampler.java
- server/test/controllers/admin/AdminApplicationControllerTest.java
- server/test/services/export/JsonExporterServiceTest.java
Rename JsonExporter to JsonExporterService
This aligns it with the `CsvExporterService` class that does similar work.
n/a
Pre-work for [#5018](https://github.com/civiform/civiform/issues/5018)
> Rename JsonExporter to JsonExporterService

- server/app/controllers/admin/PredicateUtils.java
- server/app/controllers/admin/ReadablePredicate.java
- server/app/views/admin/programs/ProgramBaseView.java
- server/test/controllers/admin/PredicateUtilsTest.java
When a block has eligibility or visibility conditions, we display those predicates in a human-readable form. This PR refactors the logic that turns a `PredicateDefinition` into a human-readable form into a utility method, so that it can re-used for implementing https://github.com/civiform/civiform/issues/6440.
There shouldn't be any functionality change with this PR.
Verify eligibility and visibility conditions are still displayed to admins in the same way.
Part of #6440
> Move admin predicate display logic to helper method

- server/app/controllers/admin/AdminApplicationController.java
- server/app/controllers/admin/PredicateUtils.java
- server/app/controllers/admin/ReadablePredicate.java
- server/app/controllers/applicant/UpsellController.java
- server/app/services/applications/PdfExporterService.java
- server/app/services/export/PdfExporter.java
- server/app/views/admin/programs/ProgramBaseView.java
- server/test/controllers/admin/PredicateUtilsTest.java
- server/test/services/applications/PdfExporterServiceTest.java
- server/test/services/export/PdfExporterTest.java
This PR renames the PDF export methods to include "application". We're going to add new methods that will export a PDF of a program's current blocks and questions to help admins see the program setup (see  https://github.com/civiform/civiform/issues/6440), so we need the current PDF export methods to make it clear that they're about applications.
Part of #6440 .
> Rename PDF export methods to be application-specific

- browser-test/src/admin/admin_application_statuses.test.ts
- server/app/services/cloud/aws/SimpleEmail.java
Email messages sent from non-production environments will now prepend "[Test Message]" to the subject lines and the following to the body:
```
This email was generated from our test server.
If you didn't expect this message please disregard.
***************************************************
original email body here
```
Emails send from prod will remain unchanged.
Fixes #6907
> Prepend Notification to Non-prod generated emails

- browser-test/playwright.config.ts
Playwright lets you use `test.only()` and `test.describe.only()` as annotations to only run tests with that method. This is one way of many for a dev to specify a small set of tests to run. The downside is that this could be committed, thus blocking out most of the tests.
This sets the config property blocking the use of `only` when being run with the `CI` environment variable set, such as when running in a GitHub action.
> [!NOTE]
> Using the double bang `!!` is how the Playwright docs set the value.
> Error if Playwright 'Only' used in CI"

- .github/workflows/pr_env_var_docs.yaml
- .github/workflows/tests.yaml
The updated v4 codecov action still fails to upload. It's a known issue on their side. Rollback for now.
> Rollback codecov action to v3

- server/conf/helper/feature-flags.conf
Enable the QUESTION_CACHE_ENABLED by default. This has been enabled in staging and in Seattle for a while now.
Enable the QUESTION_CACHE_ENABLED flag by default. This doesn't change any functional behavior, but locally caches the full program definition for active programs to reduce calls to the database to increase the speed of page loads. 
#5746
> Enable QUESTION_CACHE_ENABLED flag by default

- server/test/services/export/AbstractExporterTest.java
- server/test/services/export/CsvExporterServiceTest.java
- server/test/services/export/JsonExporterServiceTest.java
Make `AbstractExporterTest`'s inner util classes static
- Makes inner util classes in `AbstractExporterTest` static so we can instantiate them with a factory-like pattern.
- Also renames `CsvExporterTest` to `CsvExporterServiceTest` to align it with the name of the class it tests.
n/a
N/A
Prework for #5018
> Make `AbstractExporterTest`'s inner util classes static

- server/app/repository/ProgramRepository.java
- server/app/services/export/CsvExporterService.java
- server/app/services/export/JsonExporterService.java
- server/test/services/export/AbstractExporterTest.java
- server/test/services/export/JsonExporterServiceTest.java
- server/test/support/ProgramBuilder.java
Export questions from all program versions in the JSON API
Details
- Retrieves all program versions from the database
- Updates the query to eagerly fetch applicant accounts to reduce n+1 queries
- Loops over every program definition and retrieves answers for all questions for all program versions from the applicants, storing the first `AnswerData` it encounters for each path
- Adds tests to `JsonExporterServiceTest`
- Adds methods for working with drafts and removing programs to `FakeProgramBuilder`
This is not a breaking API change because it only adds additional fields to the API response.
Applications exported via the JSON API now include all questions that have ever been part of a program, not just the questions in the most recent version of the program. This prevents changes to …
> Export questions from all program versions via JSON API

- server/app/repository/VersionRepository.java
- server/test/repository/ProgramRepositoryTest.java
- server/test/repository/VersionRepositoryTest.java
- server/test/services/applicant/ApplicantServiceTest.java
- server/test/services/program/ProgramServiceTest.java
Access program IDs directly instead of through the ProgramDefinition
Nothing in this PR should have a significant performance change, but it removes this pattern from our codebase so it doesn't get copied to somewhere where it might have a large cost.
As an example of somewhere with a large cost see:
https://github.com/civiform/civiform/commit/d280fe4c59650f44a8fabae73170fcc78388e370#diff-b96e47e7b318d0c8fbd715bfabd93bab7112c8994dcd46d64a13760cabb58ddaL140
The program ID is set on every exported application. It was originally accessed via `application.getProgram().getProgramDefinition().id()`, but is now accessed via `application.getProgram().id`
Details:
- In a few places, we only care about the program ID but we're loading a the full ProgramDefinition to get it
- If we only access the …
> Access program ids directly instead of through the ProgramDefinition

- server/app/services/export/PdfExporter.java
- server/test/services/export/PdfExporterTest.java
Adds the base URL to the PDF preview export so admins remember where the PDF came from.
Open a program page and click "Download PDF preview". Verify the PDF has "Origin of export: " and the URL at the top.
Fixes #6988
> Include URL origin of export on PDF preview

- .devcontainer/devcontainer.json
Got a message about the github extension being outdated, so removed that and adding graphite (from @avaleske's suggestion)
#6999
> Update devcontainer extensions to add graphite and remove legacy github extension

- browser-test/browser-test-compose.dev.yml
- browser-test/custom-postgres.conf
Configures browser test docker compose file to use custom postgres config file.
> [!CAUTION]
> These settings disable durability settings. Loss off data is possible. These settings **MUST NOT** be applied to staging or production environments, and this commit is specific local docker configuration and can't affect staging or production.
>
> Use on short lived data, such as running browser test, is the only acceptable use of these settings
This change turns off some of the durability settings in postgres on the browser test database. Changes are based on [postgres documentation](https://www.postgresql.org/docs/current/non-durability.html) and other writings on the internet. This speeds up clearing the database by an order of magnitude from around 250ms to around 25ms. This adds up quickly …
> Browser Test Postgres Performance

- browser-test/src/applicant/questions/number_input.test.ts
Add the north star tag to the number test so they don't get tested in staging
> Add north star tag to number input test

- browser-test/browser-test-compose.dev.yml
- browser-test/browser-test-compose.yml
Making the postgres perf settings available on all browser test compose files.
This worked locally fine, but turns out CI loaded a different browser test compose file. While the time savings from around 250ms to 25ms is accurate the run on GitHub that appeared faster was probably due to lower weekend usage of resources.
> Enable perf speed on all browser test compose files

- browser-test/src/footer.test.ts
- browser-test/src/support/civiform_fixtures.ts
- browser-test/src/support/index.ts
- browser-test/src/support/wait.ts
Migrates the footer browser tests to use Playwright fixtures.
Adding steps around various common functions
> [!TIP]
> You'll want to hide whitespace changes
>
> ![image](https://github.com/civiform/civiform/assets/195162/58417fc9-4a6b-4a04-8a86-8e06844086d1)
> Migrate footer tests to use fixtures

- server/conf/application.dev-browser-tests.conf
- server/conf/application.test.conf
Durable Jobs default to run every five seconds. This is unneeded in a unit test or browser test environment that will come and go frequently.
> Make the durable jobs run hourly in browser and unit tests

- browser-test/src/applicant/questions/address.test.ts
Migrates address tests to use fixtures. This solves an issue where some teardown issues were occurring.
> Migrate address tests to use fixtures

- browser-test/src/admin/admin_predicates.test.ts
- server/app/assets/javascripts/admin_predicate_configuration.ts
- server/app/services/DateConverter.java
- server/app/services/applicant/predicate/JsonPathPredicateGenerator.java
- server/app/services/program/predicate/Operator.java
- server/app/services/program/predicate/OperatorRightHandType.java
- server/app/services/program/predicate/PredicateGenerator.java
- server/app/services/program/predicate/PredicateValue.java
- server/test/services/applicant/predicate/JsonPathPredicateGeneratorTest.java
- server/test/services/program/predicate/PredicateGeneratorTest.java
Currently only a whole number is accepted for age younger than and age older than, but we should allow for decimals.
This is to allow Charlotte to create a predicate for lived in a house less than 6 months. The admin can create a date question "When did you move into your house?" and can set eligibility on that question for age less than .5.
Fixes #7049
> Allow decimals to be entered for age younger than / older than predicates

- server/app/services/applicant/Currency.java
- server/test/services/applicant/CurrencyTest.java
We store the currency value as a whole number. In some cases the multiplication by 100 was ending up with a floating point precision issue losing a cent value.
Example: 18000.01
Expected: 1800001
Actual: 1800000
> Fixing currency precision

- server/app/views/applicant/ApplicantBaseFragment.html
- server/app/views/applicant/NorthStarApplicantBaseView.java
We were mistakenly including the admin js bundle instead of the applicant bundle in North Star code. Also moves it to the footer to match non-north star implementation
> Include applicant bundle in north star

- server/app/views/errors/NotFound.java
Fix 404 page string parametrization
It wasn't inserting the link into the string, now it is:
Before:
Now:
n/a
- [n/a] Added context strings to new [messages](https://github.com/civiform/civiform/blob/main/server/conf/i18n/messages)
Fixes #7077
> Fix 404 page string parametrization

- .github/workflows/tests.yaml
- browser-test/src/pagination.test.ts
Current artifact containing Playwright trace and video files is also including the Playwright output working directory which is taking up space for no reason.
> Remove extra test-output folder in artifacts

- browser-test/src/security.test.ts
- server/app/auth/CiviFormHttpActionAdapter.java
- server/test/auth/CiviFormHttpActionAdapterTest.java
Redirect to home page if the request is not authorized.
This can be useful if (1) the server secret is rotated and (2) an admin user with an active session tries to access an admin page. Before this change, they would just be presented with a page with `403 Forbidden` and no hint about how to recover.
Note there is existing handling for API requests that is untouched.
1. Run a local instance of the server.
2. Authenticate as admin and load an admin page.
3. Modify `play.http.secret.key` in `server/conf/application.conf`.
4. Reload the admin page in the browser.
5. Verify that you are redirected to the home page.
6. Verify that the page says, "You're a …
> Redirect to home page if unauthorized (except for API requests)

- browser-test/src/admin/admin_publish.test.ts
- browser-test/src/admin/admin_question_references.test.ts
- browser-test/src/admin/admin_settings.test.ts
- browser-test/src/admin/dev_tools.test.ts
- browser-test/src/program_deep_link.test.ts
- browser-test/src/support/civiform_fixtures.ts
- browser-test/src/support/index.ts
Migrating more browser tests to use Playwright fixtures. Also removes obsolete references to `AdminApiKeys`.
Recommend you ignore whitespace when reviewing the diff
> Migrating more browser tests to use fixtures

- .devcontainer/devcontainer.json
- Forward the port needed for oidc from the dev container
- Fix the java version to 11 to avoid issues with Play
- Change `onCreateCommand` to `updateContentCommand`, so it will re-run when pre-caching containers when the source tree updates ([details](https://containers.dev/implementors/json_reference/))
Part of #6999
> Forward oidc port and fix java version to 11

- .github/workflows/tests.yaml
Sets the retention of the PR artifacts to just 3 days down from the default of 90. 
> Set retention days on artifacts

- browser-test/playwright.config.ts
The record video setting I had in the `playright.config.ts` was based on the presence of the `RECORD_VIDEO` environment variable. But it's possible we may use be passing in false in some places. This will handle both cases.
> Better check for recording video

- .devcontainer/devcontainer.json
We don't use terraform in our main repo (only in the deployment repo), so we don't need the extension in our codespaces. 
#6999
> Remove terraform from codespace dependencies

- .devcontainer/devcontainer.json
- .devcontainer/launch.json
It didn't seem the "launch" section was doing anything in the devcontainer, but moving this over into launch.json allows the settings for the debug panel to work for any codespace
https://github.com/civiform/civiform/issues/6999
> Move launch configuration to a separate file within devcontainer

- browser-test/browser-test-compose.dev.yml
- browser-test/browser-test-compose.dev_local.yml
- browser-test/browser-test-compose.yml
- docker-compose.dev.yml
- docker-compose.yml
- test-support/prod-simulator-compose.yml
The Version property in docker compose files has been optional for a while and now generates warnings when running. 
[Compose spec says](https://github.com/compose-spec/compose-spec/blob/master/04-version-and-name.md) it's only been used for informational purposes anyway.
```shell
docker compose version
Docker Compose version v2.25.0
docker --version
Docker version 26.0.0, build 2ae903e
```
> Removing version from docker compose files

- bin/build-and-push-image-for-testing
Passes in the sbt version or building the image fails. This script rare is used and I missed adding it here when I updated the sbt version last month.
For the curious `SBT_VERSION` is defined when sourcing `bin/lib.sh`.
> Set SBT_VERSION in script that pushes custom images

- server/app/modules/EsriModule.java
- server/app/services/geo/esri/RealEsriClient.java
- server/app/services/settings/SettingsManifest.java
- server/conf/application.dev.conf
- server/conf/application.test.conf
- server/conf/env-var-docs.json
- server/conf/helper/esri.conf
- server/test/resources/esri/findAddressCandidatesNo100PercentMatch.json
- server/test/services/geo/esri/EsriTestHelper.java
- server/test/services/geo/esri/RealEsriClientTest.java
This changes the env var `esri_find_address_candidates_url` from a string to a list and can now try to correct addresses from multiple sources. Each correction occurs sequentially and may not call all the options depending on the score in the correction results.
Address correction can now use multiple Esri sources. Each additional source is only checked if there either no results from the current source of if there are no results with a score 90 or higher. All results are combined and continue to show the top three options with the highest score to the applicant.
Read the full guidelines for …
> Change ESRI findAddressCandidiates url to a list or urls

- server/app/modules/EsriModule.java
- server/app/services/geo/esri/RealEsriClient.java
- server/app/services/settings/SettingsManifest.java
- server/conf/application.dev.conf
- server/conf/application.test.conf
- server/conf/env-var-docs.json
- server/conf/helper/esri.conf
- server/test/services/geo/esri/EsriTestHelper.java
- server/test/services/geo/esri/RealEsriClientTest.java
Added a new environment variable for the find address list. Swapped the old one back to a string. Now will conditionally load for backward compatibility. Updating the release notes on the previous PR to they align.
Related: #7177
> Re-add old find address url setting value and making backward compatible

- server/app/controllers/admin/AdminProgramController.java
- server/app/services/settings/SettingsManifest.java
- server/app/views/ProgramImageUtils.java
- server/app/views/admin/programs/ProgramBlocksView.java
- server/app/views/admin/programs/ProgramFormBuilder.java
- server/app/views/components/ProgramCardFactory.java
- server/conf/application.dev.conf
- server/conf/env-var-docs.json
- server/conf/helper/feature-flags.conf
- server/test/controllers/admin/AdminProgramControllerTest.java
- server/test/views/ProgramImageUtilsTest.java
The PROGRAM_CARD_IMAGES flag has been enabled in production for a month with no issues, so we can remove it! 🎉 
Fixes #5919
> Remove PROGRAM_CARD_IMAGES flag

- browser-test/src/applicant/questions/address.test.ts
- browser-test/src/applicant/questions/checkbox.test.ts
- browser-test/src/applicant/questions/currency.test.ts
- browser-test/src/applicant/questions/dropdown.test.ts
- browser-test/src/applicant/questions/email.test.ts
- browser-test/src/applicant/questions/id.test.ts
- browser-test/src/applicant/questions/name.test.ts
- browser-test/src/applicant/questions/number_input.test.ts
- browser-test/src/applicant/questions/phone.test.ts
- browser-test/src/applicant/questions/radio_button.test.ts
- browser-test/src/applicant/questions/static_text.test.ts
- browser-test/src/applicant/questions/text.test.ts
Migrate question type tests to use fixtures. This prevents the North Star screenshot tests from flaking because the DB is being reset after each test.
I haven't done Date and File Upload yet, since I'll update those tests when I add Thymeleaf implementations for those question types.
> Migrate question type tests to use fixtures

- server/app/services/program/ActiveAndDraftPrograms.java
There are some duplicated code for activeNameToProgram and draftNameToProgram. For this PR, I took out a helper function to avoid them.
I also added a `Predicate<ProgramDefinition> filter` parameter for future use when we need a filter for non disabled active programs. It will be used as below.
```
ImmutableMap<String, ProgramDefinition> nonDisabledActiveNameToProgram = nameToProgram(repository, service, active, program -> program.displayMode() != DisplayMode.DISABLED);
```
#7195
> [Disabled Programs] refactor ActiveAndDraftPrograms

- bin/localstack/mk-s3
Refactor and simplify mk-s3 script
* Inline single-use check_bucket and create_bucket functions to reduce lines of code and layers of indirection
* Rename create_bucket_if_needed to create_bucket_if_not_exists to be more explicit
> Simplify mk-s3 script

- browser-test/src/applicant/application_address_correction.test.ts
- server/app/services/applicant/question/AddressQuestion.java
An address question can be optional and also have address correction enabled. Previously address correction would run even if the user didn't enter any data, which led to an error loop that prevented the user from proceeding. Now address correction will only run if the question is answered (i.e. any address data is filled in).
Steps to reproduce are in issue #7138.
Fixes #7138
> Skip address correction if an optional question is not answered

- server/app/controllers/FileController.java
- server/test/controllers/FileControllerTest.java
- server/test/controllers/WithMockedProfiles.java
CiviForm admins that are allowed to review programs through the ALLOW_CIVIFORM_ADMIN_ACCESS_PROGRAMS flag should be able to access files
This also adds a method in WithMockedProfiles to allow for an additional mock to be bound.
Allow global admin with program privileges (through ALLOW_CIVIFORM_ADMIN_ACCESS_PROGRAMS) to download applicant files.
1. Create a program with a file upload question and fill it out as an applicant
2. Navigate to civiform admin view with ALLOW_CIVIFORM_ADMIN_ACCESS_PROGRAMS on
3. Able to download file from application view
Fixes https://github.com/civiform/civiform/issues/7204
> Allow global admin with program privileges to download applicant files

- .devcontainer/devcontainer.json
This is the port number exposed in the browser test compose file and gets mapped to the internal port 9000
https://github.com/civiform/civiform/issues/6999
> Add port to forwardPorts list for browser test issues in devcontainer

- server/app/assets/javascripts/radio.ts
- server/app/views/style/BaseStyles.java
- server/tailwind.config.js
Renames the tailwind color "seattle-blue" to "civiform-blue"
> Rename tailwind color seattle-blue to civiform-blue

- server/app/services/program/predicate/PredicateGenerator.java
- server/test/controllers/admin/AdminProgramBlockPredicatesControllerTest.java
- server/test/services/program/predicate/PredicateGeneratorTest.java
Make PredicateGenerator.parsePredicateValue package protected
* Move a unit test from AdminProgramBlockPredicatesControllerTest to PredicateGeneratorTest because it's testing PredicateGenerator
* Reduce visibility of PredicateGenerator.parsePredicateValue to package protected because it's now just used privately and in the unit tests
> Make PredicateGenerator.parsePredicateValue package protected

- .devcontainer/devcontainer.json
There have been some issues with codespaces showing weird errors and I'm wondering if increasing the memory would help. We can try it out and see if it helps at all. I have more resources on my docker desktop, so maybe we'd want to increase it further, but we should tweak so we don't over provision either.
#6999
> Increase the memory of the codespace

- server/app/assets/javascripts/admin_predicate_configuration.ts
- server/app/views/admin/programs/ProgramPredicateConfigureView.java
The trash button for an eligibility condition value was still clickable even when it was supposed to be hidden for the first row.
The svg was marked hidden, rather than the parent button div, so the button was blank but still clickable. Fixed by moving the hidden class from the svg to the parent button.
Fixes #7272
> Fix bug where the eligibility condition trash icon is clickable even when hidden

- server/app/views/admin/programs/ProgramPredicateConfigureView.java
The ProgramPredicateConfigureView.renderValueRow method had forked logic based on maybeAndNode.isPresent. Instead of duplicating the logic, we can just create an empty map if maybeAndNode is not present, and handle both cases inline, so the logic is only happening once and it's easier to see how the two cases differ.
> Refactor ProgramPredicateConfigureView.renderValueRow

- server/app/controllers/ErrorHandler.java
Normally the application handles 403s before this and redirects home. This is a failsafe for edge cases that would leave the user on a grey 403 page that is just builtin to Play. To be consistent with the rest of the app we redirect home.
This only known way to hit this is to have an active session, change the application secret, and try using your existing session.
- `bin/run-dev`
- start app as guest, fill out a page or two of data
- change secret
- reload
- wait for app to be fully loaded
- click save and next on open page
- get the 403 error, along with the warn/error in the console log
- runProd
- start app as guest, fill out a page or two of data
- …
> Redirect home on unauthorized

- server/app/services/geo/esri/RealEsriClient.java
Pass forStorage param to esri geocode. Need to set this value because we store the results in the database.
> Pass forStorage param to esri geocode

- server/app/durablejobs/DurableJobRunner.java
- server/test/durablejobs/DurableJobRunnerTest.java
We need a way to easily remove Durable Jobs from our codebase, but currently an error is thrown when you remove a job from the registry because the db expects the code to be there to run the job. Both the job runner and the job scheduler reference the same registry, so it doesn't work to remove the job from just the scheduler to prevent future runs.
After talking it over with @nb1701 , we think it is safe to remove a job from the db if it is no longer in the registry. The only way a job can get into the db is through the registry, so it stands to reason if it is no longer in the registry it should no longer be in the db.
This PR deletes the job from the db when it is not also found in the registry and lowers the log level from error to info when it does so.
1. Set the time resolver for …
> Remove jobs from the db that are not found in the job registry

- server/app/services/geo/esri/RealEsriClient.java
- server/test/services/geo/esri/RealEsriClientTest.java
Send api token when address correction calls to Arcgis Online (arcgis.com)
Contributes to: #6800
> Send token when calling arcgis.com

- browser-test/src/end_to_end_enumerators.test.ts
Replace toBeVisible(true) with toBeVisible(). The argument is unnecessary and the correct syntax would be toBeVisible({visible: true}). This fixes a warning.
> Fix erroneous toBeVisible(true)

- browser-test/src/end_to_end_enumerators.test.ts
- browser-test/src/support/applicant_questions.ts
- server/app/assets/javascripts/enumerator.ts
- server/app/views/questiontypes/EnumeratorQuestionRenderer.java
When filling out an enumerator question in an application, the Add button is supposed to be disabled if any of the entries are blank. This only worked for entries that were created in the current page load. If entries were saved and then the page was reloaded, they would no longer participate in the enable/disable logic. This fixes that inconsistency so if an existing entry is blanked out the add button will be disabled.
Steps to reproduce are in #7317.
Fixes #7317
> Fix add button enable/disable logic when answering enumerator questions

- server/app/services/question/types/DateQuestionDefinition.java
- server/app/services/question/types/EmailQuestionDefinition.java
- server/app/services/question/types/NullQuestionDefinition.java
- server/app/services/question/types/NumberQuestionDefinition.java
- server/app/services/question/types/PhoneQuestionDefinition.java
- server/app/services/question/types/StaticContentQuestionDefinition.java
Remove unnecessary qualifiers in QuestionDefinitions. They make the code harder to read.
> Remove unnecessary qualifiers in QuestionDefinitions

- server/app/durablejobs/DurableJobName.java
- server/app/durablejobs/DurableJobRunner.java
Removing `FIX_APPLICANT_DOB_DATA_PATH` from the `DurableJobName` enum in https://github.com/civiform/civiform/pull/7302 resulted in an `IllegalArgumentException` error being thrown when the job attempted to run because the logic expects all job names found in the db to also be found in the enum.
This is a quick fix to get rid of those errors. I created https://github.com/civiform/civiform/issues/7347 to track a more permanent solution.
1. Set one of the jobs to schedule recurring jobs a minute out from now.
2. Start the server and check that the jobs get scheduled.
3. Remove the code to run the job and remove the job from where it gets registered in `DurableJobModule`, but leave it in the enum
4. Restart the server and see that jobs that have not been run yet should be removed from the db …
> Add FIX_APPLICANT_DOB_DATA_PATH back into enum

- browser-test/src/admin/admin_dropdown_create_and_edit.test.ts
- browser-test/src/admin/admin_program_list.test.ts
- browser-test/src/admin/admin_program_preview.test.ts
- browser-test/src/admin/admin_program_viewing.test.ts
- browser-test/src/admin/admin_question_list.test.ts
- browser-test/src/applicant/application_previous_version.test.ts
- browser-test/src/pagination.test.ts
- browser-test/src/question_lifecycle.test.ts
Moves more tests over to using the playwright fixtures and not the custom createTestContext.
You'll want to ignore whitespace in the diff view.
> Moved to using fixtures

- server/test/services/question/types/QuestionDefinitionTest.java
Improve QuestionDefinitionTest:
* Remove specialized configs from builder, which is meant to be a valid base question definition builder
* Explicitly set all the fields being validated in newQuestionHasCorrectFields - the test should not rely on setup behavior
* Configure a proper EnumeratorQuestionDefinition in validate_enumeratorQuestion_withEmptyEntityString_returnsErrors
> Improve QuestionDefinitionTest

- server/project/WebAssetsBundler.scala
Both stdout and stderr were being sent to the logger error method. Some recent dependency update seems to be having something come from stdout now. Not sure which :woman_shrugging: 
But both css/sass and js/ts still look to be compiling fine.
> In webassetbundler, don't log stdout to the error method

- server/app/views/components/ToastFragment.html
- server/app/views/questiontypes/AddressQuestionFragment.html
- server/app/views/questiontypes/CheckboxQuestionFragment.html
- server/app/views/questiontypes/CurrencyQuestionFragment.html
- server/app/views/questiontypes/DateQuestionFragment.html
- server/app/views/questiontypes/DropdownQuestionFragment.html
- server/app/views/questiontypes/EmailQuestionFragment.html
- server/app/views/questiontypes/EnumeratorQuestionFragment.html
- server/app/views/questiontypes/FileUploadQuestionFragment.html
- server/app/views/questiontypes/IdQuestionFragment.html
- server/app/views/questiontypes/NameQuestionFragment.html
- server/app/views/questiontypes/NumberQuestionFragment.html
- server/app/views/questiontypes/PhoneQuestionFragment.html
- server/app/views/questiontypes/RadioButtonQuestionFragment.html
- server/app/views/questiontypes/TextQuestionFragment.html
Ensure that HTML element ids start with a letter not a number by prepending 'id-'. Thymeleaf has a method to generate random alphanumeric strings that we use to generate element ids.
Fixes #7384
> Prepend 'id-' before instances of randomAlphanumeric

- server/app/services/applicant/question/Scalar.java
Make Scalar more readable:
* Inline _SCALARS variables because they add an unnecessary layer of indirection
* Keep METADATA_SCALARS in order to define a new constant for METADATA_SCALAR_KEYS to avoid the unsafe way it was being lazily initialized (https://www.cs.umd.edu/~pugh/java/memoryModel/DoubleCheckedLocking.html)
> Make Scalar more readable

- .devcontainer/devcontainer.json
Added tmux to the devcontainer. This allows a tmux terminal window to be created. In order to save the tmux configuration setup, I also added the following to ~/.tmux.conf
```
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'
run '~/.tmux/plugins/tpm/tpm'
```
This allows your pane contents to appear when you stop and restart the codespaces, but the bash history isn't there. I also tried adding the following to my .bashrc to get the history:
```
export HISTFILE="$HOME/.bash_history"
export HISTSIZE=-1 
export HISTFILESIZE=-1 
```
And I tried some versions of what's described [here](https://github.com/tmux-plugins/tmux-resurrect/blob/cff343cf9e …
> Add tmux to dev container

- .devcontainer/devcontainer.json
- .devcontainer/onCreateCommand.sh
- Remove -contrib codespace features that I couldn't find a public repository for
- tmux we install manually
- the sdkman feature was redudant since we're already installing java with ghcr.io/devcontainers/features/java:1.4.1
- Manually installs tmux and moves other package installation to `onCreateCommand.sh`
Fixes #7412
> Remove -contrib features and install packages in onCreateCommand.sh

- server/app/services/applicant/ApplicantService.java
- server/app/services/applicant/question/Scalar.java
In https://github.com/civiform/civiform/pull/6703 , we accidentally added the year, month, and day scalars to the dropdown where we configure eligibility questions. This PR removes that part of the change, since those paths are only used on the frontend and not for storage
> Remove year, month, and day from predicate view dropdown

- server/app/assets/javascripts/admin_predicate_configuration.ts
Simplify help text logic:
* querySelectorAll never returns null so don't need to check for that
* Use NodeList.forEach instead of converting to Array
* Add a comment that each value input has its own help text, to explain why we need querySelectorAll in the first place
* Rename configurePredicateValueInput to configurePredicateValueInputs to also remind that there can be more than one value input
* Remove the comment about the help text maybe not being present, because it no longer matters for the logic
* Inline the hidden condition; it was named backwards anyway
> Simplify help text typescript

- server/app/services/program/ActiveAndDraftPrograms.java
- server/app/services/program/ProgramService.java
- server/test/services/program/ProgramServiceTest.java
- server/test/support/ProgramBuilder.java
Added functions to get disabled and non-disabled programs without the question load.
Changed the logic for `activePrograms` and `draftPrograms` in class ActiveAndDraftPrograms.
Added corresponding unit tests.
Part of #7315
> [Disabled Programs] update program service

- server/app/assets/javascripts/admin_predicate_configuration.ts
- server/app/views/admin/programs/ProgramPredicateConfigureView.java
Reduce string case shenanigans:
* The operator is always upper-case so it doesn't need to be upper-cased
* The scalar type is lower-cased to stuff into the element data, but otherwise it's clearer to use the upper case version, so return that from the backend and then lower-case it only where necessary in the frontend
> Reduce string case shenanigans

- server/app/assets/javascripts/admin_predicate_configuration.ts
Refactor configurePredicateValueInput:
* Pull out a method setInputAttributes that configures the input element based on the scalar and operator
* Remove unnecessary ?. on document
* Replace ?. and assertNotNull with ! for brevity
* Use .forEach instead of Array.from and a for loop
> Refactor configurePredicateValueInput

- browser-test/src/applicant/applicant_application_index.test.ts
Ports applicant_application_index.test.ts to fixtures. Also moves the north star tests into the overall test describe since it was just copying and pasting that setup anyway.
These tests could probably have been improved by doing less common setup in general (doing only the necessary setup for each test rather than adding the start programs for all of them), but keeping the scope to just porting to fixtures.
> Port applicant_application_index.test.ts to fixtures

- browser-test/src/admin/admin_predicates.test.ts
clickGoBackAndEditOnIneligiblePage doesn't take any arguments but the callers were passing one.
> Fix typescript error "expected 0 arguments, but got 1"

- server/app/controllers/admin/AdminApplicationController.java
- server/app/controllers/applicant/UpsellController.java
- server/app/services/applications/PdfExporterService.java
- server/app/services/export/PdfExporter.java
- server/app/views/admin/programs/ProgramApplicationView.java
- server/test/services/applications/PdfExporterServiceTest.java
- server/test/services/export/PdfExporterTest.java
This makes two main changes:
1) Change any links we expose to download files from the deprecated adminShow to acledAdminShow. This is no-op change since adminShow just redirects to acledAdminShow.
2) For PDF exports, if an applicant is exporting, use the applicant "show" route, rather than the admin show route. I think this was the primary cause of issue #7205.
Note if the applicant isn't logged in, the link will still fail. So there are probably more improvements we could do, but they're larger in scope. (Either prompting users for login for acl'd routes, or downloading all uploaded files along with the application, which is difficult because they'd need to be in a zip or some other package, which may be confusing for applicants.)
Fixed issue where applicant's could not download uploaded …
> Fix links to uploaded files to use correct routes

- browser-test/src/admin/admin_program_viewing.test.ts
- browser-test/src/support/admin_programs.ts
- server/app/views/admin/programs/ProgramBlocksView.java
Adding new method `editProgramBlockUsingSpec` to serve as the consolidated way of editing the admin program question block.
Removes a method that was only used in one place.
Deprecates the others.
> Consolidate editProgramBlock methods

- browser-test/src/support/admin_predicates.ts
It makes more sense for addValueRows to take a number to add, rather than a PredicateSpec. This way other users can add a specific number of rows if they don't have a PredicateSpec.
> Refactor addValueRows in admin_predicates.ts

- browser-test/src/admin/admin_application_statuses.test.ts
- browser-test/src/admin/admin_predicates.test.ts
- browser-test/src/applicant/navigation/application_navigation_address_visibility_condition.test.ts
- browser-test/src/applicant/navigation/application_navigation_common_intake.test.ts
- browser-test/src/applicant/navigation/application_navigation_with_eligibility_conditions.test.ts
- browser-test/src/support/admin_predicates.ts
- browser-test/src/trusted_intermediary.test.ts
The addPredicate and addPredicates test support methods in admin_predicates.ts were redundant with each other. Combine them, and use a rest parameter (...) to make the caller syntax simple for either case. This also has the benefit of labeling all the params on all callers, which was previously not readable for addPredicate.
Also waitForPageJsLoad seems to have been unnecessary since addPredicate had it but addPredicates does not.
> Combine redundant addPredicate and addPredicates test helper methods

- bin/dev-psql
The `bin/dev-psql` script only connected to the dev environment. This maintains the default, but allows passing an argument to point at the unit test or browser test databases.
> Allow easy connect to psql prompt

- server/app/views/applicant/ApplicantProgramSummaryView.java
Adds link decorator styling to the file upload link on the program summary page. 
> Add link decorating styling to the file upload link on the program summary page

- browser-test/src/applicant/application_review.test.ts
- browser-test/src/support/admin_programs.ts
- server/app/controllers/admin/AdminApplicationController.java
- server/app/services/DateConverter.java
- server/test/services/DateConverterTest.java
Fixes #6629
Fix bug where filtering applications by date excluded applications submitted on the "until" date
n/a
Fixes #6629
> Fix bug where filtering applications by date excluded applications submitted on the "until" date

- server/app/services/program/predicate/PredicateGenerator.java
- server/test/services/program/predicate/PredicateGeneratorTest.java
Improve PredicateGeneratorTest with best practices and more cases
* Make PredicateGenerator.parsePredicateValue private because it's only used internally and shouldn't be tested directly
* Replace testParsePredicateValue_currency that tested parsePredicateValue with singleQuestion_singleValue_currency which tests the public generatePredicateDefinition method
* Replace usages of parsePredicateValue in the test class with PredicateValue create methods
* Remove "generatePredicateDefinition_" from all the test names since it's the only public method and they all test it
> Improve PredicateGeneratorTest with best practices and more cases

- browser-test/src/applicant/application_address_correction.test.ts
Moving this large nested describe block up to the top level of the file. The nested beforeEach's were causing a significant performance hit that didn't need to occur. Fixes a bug that was incorrectly referencing a program. This cut the run time of the `address buttons` describe section and all child tests by a total of 4 minutes on my pc.
> Speed up address correction browser tests

- browser-test/src/applicant/navigation/application_navigation_address_visibility_condition.test.ts
- browser-test/src/support/admin_predicates.ts
The increment of groupNum should happen exactly once per loop iteration, but is executed in various places, which is flimsy because it could result in 0 or 2+ increments. This code will get more complicated in the future (for #6109), so I pulled out the value filling logic to a separate method to isolate it from the increment logic. Also moved the value calculation logic down to where the values are filled since that's where it's used, and gave it a new name instead of overwriting the parameter.
Also update application_navigation_address_visibility_condition.test.ts to use value instead of values for its single value.
> Refactor configurePredicate in admin_predicates.ts

- browser-test/src/admin/admin_program_creation.test.ts
- browser-test/src/support/admin_programs.ts
* Move test setup from the launchDeleteScreenModal helper to the test itself
* Rename launchDeleteScreenModal to launchRemoveProgramBlockModal so it matches the related removeProgramBlock method
* Use launchRemoveProgramBlockModal in removeProgramBlock
> Move "delete screen" test logic from helper to test

- browser-test/.eslintrc.json
New eslint playwright rule will complain if you have nested Playwright `test.step`. I'm disabling this. While we shouldn't go overboard it can be useful to be able to nest them. 
Also sorting the rules list.
> Turn off new no-nested-step eslint playwright rule

- browser-test/playwright.config.ts
Change the browser test timeout from 3 minutes to 90 seconds.
> Cut browser test timeout to 90 seconds

- browser-test/src/admin/admin_predicates.test.ts
- browser-test/src/applicant/applicant_application_index.test.ts
- browser-test/src/applicant/application_address_correction.test.ts
- browser-test/src/applicant/application_download.test.ts
- browser-test/src/applicant/application_review.test.ts
- browser-test/src/applicant/navigation/application_navigation_buttons.test.ts
- browser-test/src/applicant/navigation/application_navigation_flow.test.ts
Tagging slow tests with `test.slow()`. This is a step toward lowering the Playwright test timeout a bit more.
> Tagging slows tests with test.slow()

- browser-test/playwright.config.ts
Lower playwright test timeout to 45 seconds. Any tests that took more than 30 seconds against staging have already been annotated with `test.slow()` which gives them 3x bump in the timeout. We can tag more where needed.
> Set playwright test timeout to 45 seconds

- server/app/assets/javascripts/questionBank.ts
- server/app/assets/javascripts/sort_selector.ts
Extracts the sorting function to a generalized function. I'm adding a sorting mechanism to the TI list page and want to re-use the sorting functionality already created for sorting question banks. This change is expected to be a no-op. Separating out the refactor from the feature implementation is intended to make reviewing PRs easier. 
> Refactor questionBank sorting functionality to a more general utility function

- browser-test/playwright.config.ts
This reverts commit 91fd5b8623c738e50f69dd8544442e224ed427d6.
Too many timeout against staging; not going to take the time to try to tag things as slow.
> Revert "Set playwright test timeout to 45 seconds (#7596)"

- browser-test/src/admin/admin_predicates.test.ts
- browser-test/src/support/admin_programs.ts
Update admin_predicates.test.ts to use *UsingSpec helper methods
* Replace the deprecated editProgramBlock and addProgramBlock methods with their preferred equivalents editProgramBlockUsingSpec and addProgramBlockUsingSpec, respectively.
* Make BlockSpec.questions optional, and update the helper methods accordingly
* Refactor editProgramBlockWithOptional to be a little clearer
> Update admin_predicates.test.ts to use *UsingSpec helper methods

- browser-test/src/admin/admin_predicates.test.ts
I missed this one in #7609. The 'test predicates' test.describe group is unnecessary shared setup because it just defines some questions, which are used unevenly across the tests within the group.
* Move the 'multiple questions ineligible' outside the group and define the two questions it actually needs in the test.
* Update the question names to reflect the question type
> Isolate more admin_predicates tests

- browser-test/src/admin/admin_predicates.test.ts
Add missing cases to 'every visibility right hand type evaluates correctly'
The age predicates were added to the eligibility test ('every eligibility right hand type evaluates correctly') but not the visibility test.
> Add missing cases to 'every visibility right hand type evaluates correctly'

- browser-test/src/admin/admin_predicates.test.ts
Rearrange predicate tests:
* Group the three program configuration steps (add question, add screen, configure eligibility/visibility predicate) into one section per screen
* Add test.steps for the configuration and application sections with screen numbers so it's easier to match up the two sections
* Remove the test.describe('test predicates') group now that there is no shared state between the tests
> Rearrange predicate tests

- server/test/services/applicant/question/AddressQuestionTest.java
- server/test/services/applicant/question/EnumeratorQuestionTest.java
- server/test/services/applicant/question/IdQuestionTest.java
- server/test/services/applicant/question/MultiSelectQuestionTest.java
- server/test/services/applicant/question/NumberQuestionTest.java
- server/test/services/applicant/question/TextQuestionTest.java
Refactor ValidationErrorMessage assertions in question tests:
* containsOnly allows duplicates, which is not desirable
* getOrDefault is kind of kludgy when the value should always exist
* It's clearer to assert on the whole validation errors object, rather than certain attributes like its size and a value for a specific key. Most similar tests already used this approach.
* For parameterized tests, switch from inputs as strings to fully typed ValidationErrorMessage, so it matches non-parameterized versions and validates the underlying object rather than just its string representation (e.g. several MessageKeys have the same string "Must contain at most {0} characters."
Read the full guidelines for PRs [here](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#creating-a-p …
> Refactor ValidationErrorMessage assertions in question tests

- browser-test/src/admin/admin_application_statuses.test.ts
- browser-test/src/admin/admin_publish.test.ts
- browser-test/src/applicant/questions/phone.test.ts
Remove vacuous beforeAll references:
* Remove empty test.beforeAll
* Remove nonsense comments in admin_publish.test.test
* Fix comment that refers to beforeAll to refer correctly to beforeEach
> Remove vacuous beforeAll references

- browser-test/src/applicant/application_version_fast_forward.test.ts
Building out new tests to capture the current flows of an applicant and civiform admin dancing around the creation of different versions of the program while the same version stays in place for the applicant.
Precursor to upcoming updates for fast-forwarding draft applications to always using the latest version of a program.
This is also an example of creating a multi-page / multi-actor flow via Playwright.
The way it's broken down. The Playwright `test`s are the instructions to build the lego set. The individual actor classes are the larger assembled chunks of legos. The calls to existing `support` folder classes are individual legos. Not a perfect analogy, but close enough.
Read the full guidelines for PRs [here](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#crea …
> New Test to Capture Existing Application Flow When Program Version Changes

- browser-test/src/applicant/navigation/application_navigation_flow.test.ts
- browser-test/src/applicant/navigation/application_navigation_with_eligibility_conditions.test.ts
- server/app/controllers/applicant/ApplicantProgramReviewController.java
- server/app/views/applicant/ApplicantProgramSummaryTemplate.html
- server/app/views/applicant/NorthStarApplicantProgramSummaryView.java
- server/app/views/components/ToastFragment.html
Add toasts in the review/summary page to thymeleaf
- Not eligible [
](url)
- May be eligible
- Errors
Progress towards #7228
> Add toasts to summary/review page

- server/app/services/applicant/ApplicantData.java
When getting the ReadOnlyApplicantProgramService inside the JsonExporterService, we are passing it an ApplicantData object without the ApplicantModel inside it. We're doing this intentionally so that any questions not in the application's program version are exported as "unanswered". This caused the lookup of data for a PAI name question (and probably any other PAI question) to fail since it relies on that ApplicantModel object.
This modifies the getters in ApplicantData to handle when the ApplicantModel is null.
In the future, we should probably figure out how to untangle this a bit to standardize how the ApplicantData object is created and used, but this fixes the immediate issue.
Read the full guidelines for PRs [here](https://github.com/civiform/civiform/wiki/Technical-contribution-gui …
> Fix JSON export with PAI

- server/app/services/applicant/ApplicantData.java
- server/app/services/applicant/question/PhoneQuestion.java
Fixed a few more places where we were assuming the ApplicantModel object in ApplicantData is not null.
https://github.com/civiform/civiform/issues/7752
> More fixes for PAI and JSON export

- browser-test/src/end_to_end_enumerators.test.ts
- server/app/assets/javascripts/enumerator.ts
Refresh enumerator entity add button status on page load
Also refactor refreshAddButtonStatus so that it works when run on a page without an enumerator, and combines the two selector calls into one.
Fixes #7733
> Refresh enumerator entity add button status on page load

- browser-test/src/support/applicant_questions.ts
Add comments to clarify behavior of deleteEnumeratorEntity methods
> Add comments to clarify behavior of deleteEnumeratorEntity methods

- server/app/views/components/ToastFragment.html
Refactor ToastFragment to make it cleaner by having fragments for alert, success, and error specify default arguments, so we don't have to specify those options every time. Makes toasts that use non-default arguments call the "toast" fragment directly.
Progress towards #7228
> Refactor toast fragments to simplify logic and use default options where applicable

- browser-test/src/end_to_end_enumerators.test.ts
* Replace occurrences of toHaveAttribute('disabled') with toBeDisabled().
* Replace occurrences of not.toHaveAttribute('disabled') with toBeEnabled().
> Use toBeDisabled in browser test assertions

- server/app/views/applicant/AddressCorrectionBlockTemplate.html
- server/app/views/applicant/ApplicantProgramFileUploadBlockEditTemplate.html
- server/app/views/applicant/IneligibleTemplate.html
- server/app/views/applicant/NorthStarApplicantBaseView.java
- server/app/views/components/ToastFragment.html
Create toast shown on all pages warning not to submit real data to a dev or staging environment
Fixes #7228
> Create toast shown when the environment is dev or staging

- server/app/services/MessageKey.java
- server/conf/i18n/messages
Add the new applicant-facing strings for enumerator min/max limit validation (#7136). Implementation to follow once the strings are translated.
Preview:
> Add enumerator question setting validation strings for translation

- server/test/controllers/ApiPayloadWrapperTest.java
- server/test/services/export/JsonExporterServiceTest.java
- server/test/services/export/JsonPrettifierTest.java
- server/test/services/export/ProgramJsonSamplerTest.java
Updates string formats in tests to use Java text blocks for JSON assertions in the API code.
(Thank you @gwendolyngoetz for Java 17!)
Part of #5257
> Update tests to use java text blocks for JSON assertions

- server/app/services/apikey/ApiKeyService.java
- server/test/services/apikey/ApiKeyServiceTest.java
Correctly handles blocking the "global" subnet when the `CIVIFORM_API_KEYS_BAN_GLOBAL_SUBNET` setting is enabled.
Fixes #7777
> Fix API Key CIDR Validation Bug

- server/app/assets/javascripts/main.ts
- server/app/views/applicant/NavigationFragment.html
- server/app/views/applicant/NorthStarApplicantBaseView.java
We were mistakenly not piping in the /logout link for the end session button. This fixes that, and swaps the buttons for links so we don't have to rely on ts event listeners
Fixes #7792
> Fix broken end session button

- browser-test/src/applicant/applicant_application_index.test.ts
- browser-test/src/applicant/applicant_application_statuses.test.ts
- browser-test/src/applicant/questions/checkbox.test.ts
- browser-test/src/applicant/questions/id.test.ts
- browser-test/src/applicant/questions/name.test.ts
- browser-test/src/applicant/questions/number_input.test.ts
- browser-test/src/applicant/questions/radio_button.test.ts
- browser-test/src/applicant/questions/static_text.test.ts
- browser-test/src/applicant/questions/text.test.ts
We have a few cases in tests where we enabled/disabled the north_star_applicant_ui flag. Some were leftover from before we had a functional login/logout in the header and others were from before the fixtures migration.
> Remove unneeded calls to disableFeatureFlag

- server/app/repository/ProgramRepository.java
- server/test/repository/ProgramRepositoryTest.java
This new query can go get the latest active program id from any program id supplied.
We need for this to always get the most recent active program ID, thus we are unable to cache the value without building out a much more complicated caching solution. This will be called frequently enough (mostly once per page load of any applicant application edit/review page) that I'm electing to go with a native sql query.  Attempts to have ebeans build the sql resulted in slower queries and much more difficult to follow queries. 
This is taking less than 1ms locally in dev. Based on calling it 100,000 times passing in a random program id from a list of 50 candidate programs and using Seattle's real program data. …
> Adding query to get the most recent program id

- server/app/actions/RouteExtractor.java
- server/test/actions/RouteExtractorTest.java
Adding a class that can be used within custom Play Actions to pull out path parameter values. Play doesn't current provide an easy way to access these value natively.
> Adding route extractor

- server/test/forms/EnumeratorQuestionFormTest.java
Rewrite the unit tests in EnumeratorQuestionFormTest to:
* Get 100% test coverage of EnumeratorQuestionForm
* As much as possible only test functionality in the class itself (i.e. avoid testing QuestionForm, QuestionDefinitionConfig, and QuestionDefinition)
> Rewrite EnumeratorQuestionFormTest

- server/app/services/MessageKey.java
- server/conf/i18n/messages
Add a new string for the error when you select too many choices in a multi-select question. The current error message says "select fewer than X" which is inconsistent with all the other similar error messages that say "select at most X". This is the first step for fixing #7846.
> Add new string for multi-select validation error

- server/app/models/ApplicationModel.java
- server/app/repository/ApplicationRepository.java
- server/test/repository/ApplicationRepositoryTest.java
In most cases applications are fixed to a program when the record is initially created and never change.
This provides a method to update the program an application uses in the rare case we need it, such as the program fast forward feature.
> Add command to set application to another program

- server/app/actions/ProgramFastForwardApplicationAction.java
- server/test/actions/ProgramFastForwardApplicationActionTest.java
This adds a new custom Play Action that will be used for fast forwarding an application to the latest program version.
Right now this will not run. No controllers are configured to call it.
> Adding new fast forward action

- .github/pull_request_template.md
Update i18n checklist in pull request template:
- Fix broken link from rewrite of the wiki page (diff: https://github.com/civiform/civiform/wiki/Internationalization-(i18n)/_compare/892049cdb22a2d353338bbe598eede008622c46d...f91abad2a09ab0479b994de323c1300f918de143)
- Remove the checklist item for following the translation workflow, because translations are handled async by the Google.org team so the PR author just has to wait for them to be done. They can still find all the details about the translation process at the wiki linked in the parent checklist item.
> Update i18n checklist in pull request template

- server/app/forms/FileUploadQuestionForm.java
- server/app/services/question/types/FileUploadQuestionDefinition.java
- server/app/services/question/types/QuestionDefinitionBuilder.java
- server/app/views/admin/questions/QuestionConfig.java
- server/app/views/admin/questions/QuestionEditView.java
- server/test/forms/FileUploadQuestionFormTest.java
- server/test/views/admin/question/QuestionConfigTest.java
Adds "maxFiles" to FileUploadQuestionDefinition. Adds UI for setting it (protected by a flag). Doesn't actually use max files yet.
TDD: https://docs.google.com/document/d/1NQjkUjnY70dVMDSiG-wGNXZhqT4hjB58CHrLKsQ7-To/edit#heading=h.bknox3ib8wpb
> [Multiple File Upload] Add max files to questions, and admin UI to modify it

- server/app/controllers/admin/AdminProgramTranslationsController.java
- server/app/forms/BlockForm.java
- server/app/forms/translation/ProgramTranslationForm.java
- server/app/services/program/LocalizationUpdate.java
- server/app/services/program/ProgramService.java
- server/app/views/admin/programs/ProgramTranslationView.java
- server/test/forms/translation/ProgramTranslationFormTest.java
- server/test/services/program/ProgramServiceTest.java
Adds the plumbing to allow translations to be specified for block names/descriptions. A follow up PR will add the form inputs required for admins to specify those values
Progress towards #7606
> Add ability to update localized name/description for blocks (not added in UI yet)

- server/app/services/question/types/QuestionType.java
- server/test/services/question/types/QuestionTypeTest.java
- server/test/support/TestQuestionBank.java
Fix converting String to QuestionType for irregular enum names. This change supports question previews (#7490).
This PR is a part of #7835 being split off for ease of review. The code will be tested indirectly by browser tests, but feel free to request unit tests specific to QuestionType.
n/a
n/a
None
> Fix converting String to QuestionType for irregular enum names

- browser-test/src/admin/admin_program_translation.test.ts
- browser-test/src/support/admin_translations.ts
- server/app/views/admin/programs/ProgramTranslationView.java
https://github.com/civiform/civiform/pull/7702 introduced a bug where the translations for the block names and descriptions weren't applied because the inputs were improperly named. This fixes that and adds the corresponding test.
> Fix bug where block translations were not being applied

- server/app/services/MessageKey.java
- server/app/views/applicant/ApplicantProgramSummaryTemplate.html
- server/app/views/applicant/NavigationFragment.html
- server/conf/i18n/messages
Found a couple places where we were using untranslated text, so updated those spots
> Translate a couple missing messages

- server/app/actions/ApplicantAuthorizationAction.java
- server/test/actions/ApplicantAuthorizationActionTest.java
Many of the applicant controllers actions constantly do these two steps:
```java
applicantStage
.thenComposeAsync(v -> checkApplicantAuthorization(request, applicantId))
.thenComposeAsync(v -> checkProgramAuthorization(request, programId))
.thenBlah....()
```
This custom action now does the same checks, but can be reused. It'll cut down on boilerplate. Additionally when composed with other actions this action can be set to run first, which is something I need.
> [!NOTE]
> This new action is not yet wired into any controller.
Simplify authorization checks
> Adding ApplicantAuthorizationAction

- server/app/assets/javascripts/file_upload.ts
- server/app/controllers/applicant/ApplicantProgramBlocksController.java
- server/app/services/cloud/aws/AwsApplicantStorage.java
- server/app/services/settings/SettingsManifest.java
- server/app/views/ApplicationBaseView.java
- server/app/views/applicant/AddressCorrectionBlockView.java
- server/app/views/applicant/ApplicantFileUploadRenderer.java
- server/app/views/applicant/ApplicantProgramBlockEditTemplate.html
- server/app/views/applicant/ApplicantProgramBlockEditView.java
- server/conf/application.dev.conf
- server/conf/env-var-docs.json
- server/conf/helper/feature-flags.conf
- server/test/services/cloud/aws/AwsApplicantStorageTest.java
- server/test/views/applicant/ApplicantProgramBlockEditViewTest.java
- server/test/views/questiontypes/ApplicantQuestionRendererFactoryTest.java
Finish removing the SAVE_ON_ALL_ACTIONS feature flag.
Removed the SAVE_ON_ALL_ACTIONS feature flag from the codebase. This feature was enabled by default in April 2024, so the only change is it can no longer be overridden in the config file.
Fixes #6860
> Clean up SAVE_ON_ALL_ACTIONS feature flag

- server/app/services/MessageKey.java
- server/conf/i18n/messages
Adding new messages for eligibility alerts
> Adding new messages for eligibility alerts

- server/app/actions/ProgramFastForwardApplicationAction.java
Add a flash key message to be consumed at a later point. This is not currently active.
> Add flash key to fastforward action

- server/app/controllers/applicant/EligibilityAlertSettingsCalculator.java
- server/app/services/AlertSettings.java
- server/app/services/AlertType.java
- server/test/controllers/applicant/EligibilityAlertSettingsCalculatorTest.java
Calculate the correct alert settings to correctly display USWDS alert message based on eligibility, fastforwarding, etc.
> Adding eligibility alert settings

- server/app/views/ViewUtils.java
- server/test/views/ViewUtilsTest.java
Adding an overload to the `makeAlert` methods that uses the new `AlertType` enum.
Fixes #5541
> Adding new overload for creating alerts

- browser-test/src/support/index.ts
Setting the step on the `validateScreenshot` method to be "boxed". Which means it'll output the line(s) of code that called the method when it fails so we get something much more useful.
Instead of the error showing this:
```
375 |     .replace('.test.ts', '_test')
376 |
> 377 |   await expect(element).toHaveScreenshot(
|                         ^
378 |     [testFileName, fullScreenshotFileName + '.png'],
379 |     {
380 |       fullPage: fullPage,
```
You'll get this:
```
91 |         AdminQuestions.NUMBER_QUESTION_TEXT,
92 |       )
> 93 |       await validateScreenshot(
|                               ^
94 |         page,
95 |         'application-ineligible-same-application',
96 |         /* fullPage= */ true,
```
The formatter thinks it knows better than me so I recommend hiding …
> Box the validateScreenshot method

- browser-test/src/admin/admin_program_migration.test.ts
Force this to be disabled for the time being. I think it's causing intermittent issues because the flag may have been enabled in a different run.
> Force disable mf upload in test

- server/app/views/AlertComponent.java
- server/app/views/ViewUtils.java
- server/app/views/admin/migration/AdminImportViewPartial.java
- server/app/views/admin/programs/ProgramImageView.java
- server/app/views/admin/programs/ProgramIndexView.java
- server/app/views/admin/questions/QuestionEditView.java
- server/app/views/admin/questions/QuestionsListView.java
- server/app/views/applicant/ApplicantFileUploadRenderer.java
- server/app/views/applicant/EditTiClientView.java
- server/app/views/components/ProgramQuestionBank.java
- server/app/views/fileupload/FileUploadViewStrategy.java
- server/test/views/AlertComponentTest.java
- server/test/views/ViewUtilsTest.java
Refactoring the Alert generating code, updating tests, and adding the option to specify the header level.
Did not remove the styles from `BaseStyles`, I'm not sure if there are other USWDS components that may share the styles. We can clean that up later.
Related to #5541
> Refactor Alert Component

- server/test/services/question/types/QuestionDefinitionTest.java
Update QuestionDefinitionTest:
* To only set required fields on the default QuestionDefinitionBuilder and QuestionDefinitionConfig.Builder values in the `@Before` method
* To not rely on the default values from the `@Before` method
* To suppress the unused warning on the `@Parameters` method
> Tweak QuestionDefinitionTest

- browser-test/src/support/index.ts
This will make the errors show the calling location and not inside each method. 
Instead of the error showing this:
```
375 |     .replace('.test.ts', '_test')
376 |
> 377 |   await expect(element).toHaveScreenshot(
|                         ^
378 |     [testFileName, fullScreenshotFileName + '.png'],
379 |     {
380 |       fullPage: fullPage,
```
You'll get this:
```
91 |         AdminQuestions.NUMBER_QUESTION_TEXT,
92 |       )
> 93 |       await validateScreenshot(
|                               ^
94 |         page,
95 |         'application-ineligible-same-application',
96 |         /* fullPage= */ true,
```
> Adding step boxing to test methods

- server/app/views/questiontypes/EnumeratorQuestionFragment.html
In #7898 I changed the warning message from dialog.confirmDelete to dialog.confirmDeleteAllButtonsSave to fix #6844, but EnumeratorQuestionFragment was under development at the same time. So when I did a global find/replace I didn't find it, but it had already been copied, and the merge didn't create any conflicts.
> Fix localized string name in EnumeratorQuestionFragment

- server/app/services/settings/SettingsManifest.java
- server/app/views/components/PageNotProductionBanner.java
- server/conf/env-var-docs.json
- server/test/views/components/PageNotProductionBannerTest.java
- Remove the hard block on prod. Doing this because you have to run a test server in prod mode to hide the dev tools buttons. Default for the setting to show the banner is still false.
- Changing the prod link text to use the civic entity full name to make it more clear. Example "Go to Seattle CiviForm" vs "Go to City of Seattle CiviForm". The latter makes it more clear it's for the civic entity.
> Fit and finish for the not prod banner

- server/app/views/BaseHtmlView.java
Make the few methods in BaseHtmlView static that were not already, to enforce its self-description of being stateless.
> Make methods in BaseHtmlView static

- bin/dev-grafana
- docker-compose.dev.yml
- monitoring/grafana/dashboards/civiform-dashboard.json
- monitoring/grafana/provisioning/dashboards/dashboard.yaml
- monitoring/grafana/provisioning/datasources/prometheus.yaml
- monitoring/prometheus/prometheus.yml
Adds `bin/dev-grafana` and updates docker compose to allow side-loading grafana and prometheus in order to better make use of the `/metrics` endpoint locally in a dev environment.
The `CIVIFORM_SERVER_METRICS_ENABLED` environment variable is still disabled by default because it's pretty chatty.
Running the script will load grafana on http://localhost:8013. Login with the default username/password (printed by the script).
The prometheus datasource connection and dashboard from the [docs](https://docs.civiform.us/it-manual/sre-playbook/monitoring#configure-access) should automatically work. It may take a few minutes for the dashboards to start populating.
> Adding ability to run grafana to view the /metrics endpoint in dev environment

- server/app/assets/javascripts/applicant_entry_point.ts
- server/app/assets/javascripts/trusted_intermediary.ts
- server/app/views/applicant/TrustedIntermediaryClientListView.java
- server/app/views/style/ReferenceClasses.java
Move the javascript for the clear search button on the TI client view page from inline to a script
* Add a trusted_intermediary.ts script and load it in applicant_entry_point.ts
* Move the javascript from onclick on the <a> element to a click event listener
* Refactor to reduce duplicated code
This is a necessary step to enforce a content security policy (#7574), and it's also cleaner and more consistent with how the rest of the application works.
> Move TI clear search button javascript from inline to a script

- server/test/services/export/AbstractExporterTest.java
- server/test/services/export/JsonExporterServiceTest.java
Add tests for untested question types and address correction fields in the JSON export
n/a
Part of #6805
> Add tests for untested question types

- server/conf/application.test.conf
Sometimes the unit tests fail with `io.ebean.DuplicateKeyException: Error[ERROR: duplicate key value violates unique constraint "civiform_settings_create_time"`.
I don't think we need to do this in the unit tests.
This disables the `SettingsMigrationModule` in the application.test.conf.
> Disable SettingsMigrationModule in unit tests

- server/app/views/applicant/ApplicantProgramSummaryTemplate.html
- server/app/views/applicant/NavigationFragment.html
Fix some a11y issues detected by Parashu in North Star.
n/a
Part of #8019
> Fix some a11y issues detected by Parashu

- server/app/actions/ProgramFastForwardApplicationAction.java
- server/app/repository/ProgramRepository.java
- server/test/actions/ProgramFastForwardApplicationActionTest.java
- server/test/repository/ProgramRepositoryTest.java
In the case there a program is newly created and has never been published there will be no latest active version. This needs to not throw in that case and can be handled by the caller.
> Uses optional instead of throwing exception

- server/test/auth/ApiAuthenticatorTest.java
- server/test/auth/ClientIpResolverTest.java
- server/test/auth/FakeRequestBuilderTest.java
- server/test/services/settings/SettingsManifestTest.java
- server/test/support/FakeRequestBuilder.java
Move FakeRequestBuilder from the auth package to the support package so it can be used more broadly across tests rather than just for auth tests.
> Move FakeRequestBuilder from auth to support package

- server/test/auth/ApiAuthenticatorTest.java
- server/test/auth/ClientIpResolverTest.java
- server/test/auth/FakeRequestBuilderTest.java
- server/test/services/settings/SettingsManifestTest.java
- server/test/support/FakeRequestBuilder.java
Prepare FakeRequestBuilder to handle all request building in unit tests:
- Add factory methods and make the constructor private
- Update existing usages from the constructor to one of the factory methods
- Add CSRF to the request by default so that each test won't have to add CSRF
- Add a call() builder method that imitates the RequestBuilder(Call) constructor so it behaves like a builder
This supports #8046.
> Enhance FakeRequestBuilder to support unit test cases

- server/test/support/FakeRequestBuilderTest.java
Add unit tests for FakeRequestBuilder that I should have added in #8049
> Improve unit test coverage for FakeRequestBuilder

- server/app/controllers/dev/seeding/CategoryTranslationFileParser.java
- server/app/controllers/dev/seeding/DevDatabaseSeedTask.java
The `DevDatabaseSeedTask` was failing to seed categories because it couldn't resolve the path to the category translation files.  Using Play `Environment.getFile(<relative path>)` solves this problem.
> Use Play Environment to get program category translation directory

- server/test/auth/CiviFormProfileTest.java
- server/test/controllers/admin/AdminProgramBlocksControllerTest.java
- server/test/controllers/admin/AdminProgramControllerTest.java
- server/test/controllers/admin/AdminQuestionControllerTest.java
- server/test/controllers/applicant/ApplicantProgramBlocksControllerTest.java
- server/test/controllers/applicant/ApplicantProgramReviewControllerTest.java
- server/test/controllers/applicant/ApplicantProgramsControllerTest.java
- server/test/controllers/applicant/ProgramSlugHandlerTest.java
- server/test/controllers/applicant/UpsellControllerTest.java
- server/test/controllers/dev/FeatureFlagOverrideControllerTest.java
- server/test/controllers/dev/ProfileControllerTest.java
- server/test/controllers/ti/TrustedIntermediaryControllerTest.java
- server/test/services/applicant/ApplicantServiceTest.java
- server/test/support/CfTestHelpers.java
- server/test/support/FakeRequestBuilder.java
- server/test/views/BaseHtmlLayoutTest.java
- server/test/views/HtmlBundleTest.java
Replace the CfTestHelpers.requestBuilderWithSettings helper methods with FakeRequestBuilder.
* Replace CfTestHelpers.requestBuilderWithSettings().build() with FakeRequestBuilder.fakeRequest()
* Replace CfTestHelpers.requestBuilderWithSettings() with FakeRequestBuilder.fakeRequestBuilder()
* Replace CfTestHelpers.requestBuilderWithSettings(String... settings) with FakeRequestBuilder.fakeRequest().addCiviFormSetting(key, value)
* Replace CfTestHelpers.requestBuilderWithSettings(Call call) with FakeRequestBuilder.fakeRequest().call(call)
* Inline CfTestHelpers.EMPTY_REQUEST because it's not really an empty request and it's equivalent to fakeRequest() which is used most places.
* Remove the helpers from CfTestHelpers
This supports #8046. …
> Replace CfTestHelpers.requestBuilderWithSettings with FakeRequestBuilder

- browser-test/src/applicant/application_version_fast_forward.test.ts
- server/app/actions/RouteExtractor.java
- server/app/controllers/applicant/ApplicantProgramBlocksController.java
- server/app/controllers/applicant/ApplicantProgramReviewController.java
- server/app/repository/ApplicationRepository.java
- server/app/services/applicant/ApplicantService.java
- server/app/views/admin/programs/ProgramImageView.java
- server/app/views/applicant/ProgramCardViewRenderer.java
- server/test/controllers/applicant/ApplicantProgramReviewControllerTest.java
- server/test/controllers/applicant/ProgramSlugHandlerTest.java
- server/test/services/applicant/ApplicantServiceFastForwardEnabledTest.java
Final bit of work to enable application program fast forwarding feature. This will update draft applications to the latest published version if there is a new one.
The applicant program selection home page is now based on the latest version of the program as well; but the application is linked to the old program version which will kick off the fast forwarding process.
Applicants will always be presented with the most latest version of a program when applying. Draft applications will automatically be upgraded the next time the applicant loads the application. Eligibility tags when selecting programs are based on the latest version of the program.
If …
> Updating Existing Draft Application to Latest Program Version

- bin/dev-grafana
- docker-compose.dev.yml
I already got tired have having to login to the local instance all the time. Fixed it!
> Make the dev grafana require no auth

- server/test/controllers/admin/AdminApplicationControllerTest.java
- server/test/controllers/admin/AdminExportControllerTest.java
- server/test/controllers/admin/AdminImportControllerTest.java
- server/test/controllers/admin/AdminProgramBlocksControllerTest.java
- server/test/controllers/admin/AdminProgramControllerTest.java
- server/test/controllers/admin/AdminProgramImageControllerTest.java
- server/test/controllers/admin/AdminProgramStatusesControllerTest.java
- server/test/controllers/admin/AdminProgramTranslationsControllerTest.java
- server/test/controllers/admin/AdminQuestionControllerTest.java
- server/test/controllers/admin/AdminQuestionTranslationsControllerTest.java
- server/test/controllers/applicant/ApplicantInformationControllerTest.java
- server/test/controllers/applicant/ApplicantProgramBlocksControllerTest.java
- server/test/controllers/applicant/ApplicantProgramReviewControllerTest.java
- server/test/controllers/applicant/ApplicantProgramsControllerTest.java
- server/test/controllers/applicant/ProgramSlugHandlerTest.java
- server/test/controllers/applicant/UpsellControllerTest.java
- server/test/controllers/dev/ProfileControllerTest.java
- server/test/controllers/ti/TrustedIntermediaryControllerTest.java
- server/test/services/applicant/ApplicantServiceFastForwardEnabledTest.java
- server/test/services/ti/TrustedIntermediaryServiceTest.java
- server/test/support/FakeRequestBuilder.java
Remove calls to addCSRFToken in unit tests, except where the test is explicitly testing CSRF, because FakeRequestBuilder does it automatically since #8049.
This supports #8046.
> Remove redundant calls to addCSRFToken

- server/app/services/program/ProgramService.java
- server/test/services/program/ProgramServiceTest.java
Make the block name and block description fields on the Program translations page optional. This is a transitional step to give Civiform Admins time to get translations and update them, but not to block immediate changes to program name (and related fields).
Opened #8109 to track re-enabling them as required
Fixes #8107
> Make Program Blocks Optional for Translations (temporary)

- server/build.sbt
This adds the `code-coverage` folder to the list of things automatically clean with running `sbt clean`. It won't necessarily solve the problem, but will make it less manual to clean up. If people are in the habit of running `clean` already it'll probably lower the likelihood of it occurring.
[History on the problem](https://civiform.slack.com/archives/C01QKN2UNMA/p1700618715682069) from Slack.
> Delete code-coverage folder contents when running sbt clean

- server/app/assets/javascripts/applicant_entry_point.ts
- server/app/assets/javascripts/language_selector.ts
- server/app/views/applicant/ApplicantLayout.java
- server/app/views/applicant/NavigationFragment.html
Replace the inline onchange listener for the language selector dropdown with a static javascript listener in a new language_selector.ts file. This is necessary to enforce a content security policy (https://github.com/civiform/civiform/issues/7574), which disallows inline javascript.
> Replace inline javascript for language selector

- server/app/assets/javascripts/enumerator.ts
- server/app/views/questiontypes/EnumeratorQuestionFragment.html
- server/app/views/questiontypes/EnumeratorQuestionRenderer.java
Replace the "onclick" inline javascript for the enumerator entity delete button with static javascript. It requires a localized string, which is now plumbed in a data attribute on the button.
Fixes #8097
> Replace inline javascript for entity delete button

- server/app/services/export/PdfExporter.java
- server/test/services/export/PdfExporterTest.java
Added a line that describes whether the question is optional or not in the program preview pdf.
If the question is required, it should display "Required Question". Otherwise, it will display "Optional Question".
Added a line that describes whether the question is optional or not in the program preview pdf.
If the question is required, it should display "Required Question". Otherwise, it will display "Optional Question".
Fixes #7365
> PDF Download of a form should include information about "required" or "optional" questions

- server/app/controllers/admin/AdminProgramController.java
- server/app/controllers/dev/seeding/DevDatabaseSeedTask.java
- server/app/services/program/ProgramService.java
- server/app/services/settings/SettingsManifest.java
- server/app/views/admin/programs/ProgramAdministratorProgramListView.java
- server/app/views/admin/programs/ProgramBlocksView.java
- server/app/views/admin/programs/ProgramFormBuilder.java
- server/app/views/admin/programs/ProgramIndexView.java
- server/app/views/applicant/ApplicantProgramSummaryView.java
- server/app/views/applicant/NorthStarProgramIndexView.java
- server/app/views/applicant/ProgramIndexView.java
- server/app/views/components/ProgramCardFactory.java
- server/conf/env-var-docs.json
- server/conf/helper/feature-flags.conf
- server/test/controllers/admin/AdminProgramControllerTest.java
- server/test/services/program/ProgramServiceTest.java
Fully remove the INTAKE_FORM_ENABLED feature flag, now that it has been enabled in prod for a month.
Removed the INTAKE_FORM_ENABLED feature flag, so the pre-screener form feature is always available. Note that this does automatically create a pre-screener program, just makes the feature available to admins.
Fixes #7865
> Remove INTAKE_FORM_ENABLED feature flag

- server/app/controllers/dev/seeding/DevDatabaseSeedTask.java
- server/test/services/program/ProgramServiceTest.java
Replace the unnecessarily complicated ImmutableList.copyOf(new ArrayList<>()) with ImmutableList.of().
> Fix empty ImmutableList calls

- browser-test/src/dev/address_checker.test.ts
This address test expects the esri endpoint (or mock version) to be online. Making it only run locally, similarly to some other address tests.
Ignore whitespace for easier diff
> Only run address test locally

- .github/renovate.json5
Forgot to update the renovate config to allow for java 17.
> Update renovate to look for java 17

- .github/renovate.json5
Renovate's built in pattern for matching the bellsoft/liberica-open-jdk-alpine version we use doesn't match correctly. This pattern should work for both bellsoft and eclipse temurin.
Running the renovate cli in local mode I'm able to get it to see updates for both bellsoft and temurin 17.0.12 against a test dockerfile with the previous 17.0.11 version in it.
> Use a custom regex for matching docker java in renovate

- server/conf/application.conf
- server/test/support/FakeRequestBuilder.java
- server/test/support/FakeRequestBuilderTest.java
Define and enable a content security policy in report-only mode. No resources will be blocked; rather the browser will log an error to the console when it would have blocked an item.
This is for #7574.
Define a content security policy in report-only mode. This has no impact on application behavior but logs a console error when the policy would have blocked a resource.
> Enable CSP in report only mode

- server/app/views/CspUtil.java
- server/app/views/NorthStarBaseView.java
- server/app/views/applicant/ApplicantBaseFragment.html
- server/test/views/CspUtilTest.java
Add the CSP nonce to all thymeleaf templates so that the browser knows they are approved to load. This is for https://github.com/civiform/civiform/issues/7574.
> Add CSP nonce to Northstar views

- .devcontainer/devcontainer.json
- civiform.code-workspace
Bringing (recommended) extension lists into sync
- Remove obsolete extension; we already have the recommended replacement in the list
`knisterpeter.vscode-github`  ➡️  `github.vscode-pull-request-github`
- Remove `hashicorp.terraform` since it's not used in this repo
- Adding `graphite`, `playwright`, and `remote containers` as recommended extensions
- Sorting
> Align vscode extension lists

- server/app/controllers/applicant/ApplicantProgramBlocksController.java
- server/app/controllers/applicant/ApplicantProgramReviewController.java
- server/app/controllers/applicant/EligibilityAlertSettingsCalculator.java
- server/app/services/MessageKey.java
- server/conf/i18n/messages
- server/test/controllers/applicant/EligibilityAlertSettingsCalculatorTest.java
Adding new ineligible alert strings for North Star. This change was originally a part of #8104 but I wanted to split it up into smaller chunks for ease of review.
n/a
n/a
Part of #7996
> Prepare new ineligible alert strings for North Star

- server/app/modules/SecurityModule.java
This workaround was only necessary until pac4j 5.6.1, and we're [on 5.7.6](https://github.com/civiform/civiform/blob/65a5fea8918d08b6c668d480475a1d0d1dc11f66/server/build.sbt#L76-L84). 
> Remove obsolete security workaround

- .github/pull_request_template.md
Add step to PR template to remind SWEs to either make changes to the Thymeleaf version of a feature, or open an issue so we don't forget.
> Add thymeleaf step to PR template

- server/app/services/settings/SettingsManifest.java
- server/conf/application.conf
- server/conf/env-var-docs.json
Add a config variable to override CSP (content security policy) enforcement per environment. This allows us to execute an incremental rollout per instance without the additional work of implementing a feature flag. This is for #7574.
> Add a config variable to override CSP report only config

- server/app/auth/CiviFormProfile.java
We can link to the troubleshooting page in the authority ID error message, so people can see more information on what to do to fix the issue.
#8251
> Link to troubleshooting page in authority ID error message

- server/app/modules/DatabaseSeedModule.java
- server/app/modules/DurableJobModule.java
- server/app/modules/SettingsMigrationModule.java
Make custom modules that edit the database wait for evolutions to complete and also finish running before the app starts servicing clients.
Custom modules making changes to the database that are expected to be done before the app is live relied on Akka's ActorSystem, but this would result in work being completed after the app is live. The change checks that the evolutions have completed before moving on.
I've been told this didn't work back in the early days of the project which is why Akka was used. Later the delay was added to avoid a race condition. This was [considered hacky at the time](https://github.com/civiform/civiform/pull/3663).
> [!NOTE]
>The [recommended approach from Play](https://www.playframework.com/documentation/3.0.x/Migration27#Application-starts-when-evolutions-scripts …
> Have data accessing modules wait for evolutions to complete

- browser-test/src/support/admin_api_keys.ts
- server/app/assets/javascripts/admin_api_keys.ts
- server/app/assets/javascripts/admin_entry_point.ts
- server/app/views/admin/apikeys/ApiKeyIndexView.java
Replace the "onsubmit" inline javascript for the "retire key" button on the admin API keys page with static javascript. The message requires the key name, which is now plumbed in a data attribute on the form.
This is necessary to enforce a content security policy (https://github.com/civiform/civiform/issues/7574), which disallows inline javascript.
Also:
- Update the retireApiKey helper so that admin_api_keys.test.ts validates that the dialog actually appears
- Fix unused variable warnings that randomly popped up in admin_api_keys.ts
> Replace inline javascript for retire api key form

- browser-test/src/applicant/questions/file.test.ts
- browser-test/src/support/civiform_fixtures.ts
Update the Playwright browser test page fixture to fail any test that records a CSP (content security policy) violation in the browser console.
Also disable the three file upload tests in the Northstar UI that violate CSP due to #8143.
> Fail browser tests on any CSP error

- server/app/views/dev/DatabaseSeedView.java
Adding a missing '/' to the ses email link in devtools
Fixes #8307
> Adding a missing '/' to the ses email link in devtools

- server/test/services/question/types/EnumeratorQuestionDefinitionTest.java
- server/test/services/question/types/MultiOptionQuestionDefinitionTest.java
- server/test/services/question/types/QuestionDefinitionTest.java
Move unit tests that test specific question functionality from QuestionDefinitionTest to test classes specific to those question types.
This moves code without making any changes.
This is for #7919.
> Move unit tests from QuestionDefinitionTest to type-specific test classes 

- server/app/services/applicant/ApplicantService.java
- server/app/services/applicant/question/Scalar.java
- server/test/services/applicant/ApplicantServiceTest.java
Modified ApplicantService. It now takes nameSuffix as part of the answers to the applicantion's Primary Applicant Info questions into the Primary Applicant Info columns in the applicants table. 
part of #8267
> [Suffix] Add suffix to applicant service

- server/app/controllers/dev/seeding/DevDatabaseSeedController.java
- server/app/durablejobs/RecurringJobScheduler.java
- server/app/models/JobType.java
- server/app/models/PersistedDurableJobModel.java
- server/conf/evolutions/default/74.sql
- server/test/durablejobs/DurableJobRunnerTest.java
- server/test/durablejobs/jobs/MigratePrimaryApplicantInfoJobTest.java
- server/test/durablejobs/jobs/UnusedProgramImagesCleanupJobTest.java
- server/test/models/PersistedDurableJobModelTest.java
- server/test/repository/PersistedDurableJobRepositoryTest.java
Adding the new `job_type` column to the `persisted_durable_jobs` table, along with related model changes. All existing job code is defaulted the `JobType.RECURRING`.
> Add new job type column and update model

- server/app/services/question/types/EnumeratorQuestionDefinition.java
- server/app/services/question/types/IdQuestionDefinition.java
- server/app/services/question/types/MultiOptionQuestionDefinition.java
- server/app/services/question/types/NumberQuestionDefinition.java
- server/app/services/question/types/TextQuestionDefinition.java
- server/app/views/admin/questions/QuestionConfig.java
- server/test/services/question/types/IdQuestionDefinitionTest.java
- server/test/services/question/types/MultiOptionQuestionDefinitionTest.java
- server/test/services/question/types/NumberQuestionDefinitionTest.java
- server/test/services/question/types/TextQuestionDefinitionTest.java
For each question type that has min/max settings (Enumerator, Id, MultiOption, Number, Text), add constraints and validation that the input values are reasonable:
* Validate that min <= max if both are set (server-side)
* Require that min >= 0 (client-side and server-side)
* Require that max >= 1 since a max of 0 would prevent answering the question, except for Number where it validates max >= 0 since 0 is a valid Number answer (client-side and server-side)
Also included:
* Create unit test classes for several QuestionDefinition subclasses that didn't have them
* Add unit tests for the cases above
When an admin sets min/max settings for a question type that supports them (Number, Checkbox, ID, Text, Enumerator), CiviForm will now validate that the min <= max (if both are set), min >= 0, …
> Add constraints to min/max question settings

- server/app/services/applicant/ApplicantService.java
- server/test/services/applicant/ApplicantServiceFastForwardEnabledTest.java
- server/test/services/applicant/ApplicantServiceTest.java
- server/test/support/ResourceCreator.java
Only set the submitter email if TI is submitting for someone else. 
Details:
- When exporting we use the submitter_email field to determine if the application was submitted by an applicant or a TI, but this field is set even when the TI is submitting an application for themselves. (https://github.com/civiform/civiform/issues/5325 would fix this as well)
- Now, we check if the applicant's applicant ID is the same as the TI's applicant ID, and if they are, we don't set the `submitter_email` field
- This also requires fixing the mocks that don't fully set up the relationship between Accounts and Applicants.
When exporting applications that are submitted by a TI, for themselves, the `submitter_type` field will now say `APPLICANT`. …
> Only set submitter email if TI is submitting for someone else

- server/app/services/settings/SettingsManifest.java
- server/conf/env-var-docs.json
Update the description for the APPLICANT_OIDC_PROVIDER_LOGOUT config variable to clarify that it applies to both admin and applicant auth, despite the name.
> Clarify the description of the APPLICANT_OIDC_PROVIDER_LOGOUT config variable

- browser-test/src/applicant/application_version_fast_forward.test.ts
- server/app/actions/ProgramDisabledAction.java
- server/app/actions/RouteExtractor.java
- server/test/actions/ProgramDisabledActionTest.java
- server/test/actions/RouteExtractorTest.java
- server/test/support/FakeRequestBuilder.java
When fastforward is enabled, adds an additional check to have the `ProgramDisabledAction` see if the url path has a programId. If it does load the program and get the slug, then continue running following the existing rules.
Fixes a bug that occurs when the ProgramDisabled and FastForward features are both enabled.
Fixes #8290
> Add Additional Program Disabled Check

- server/app/auth/oidc/CiviformOidcProfileCreator.java
- server/app/repository/AccountRepository.java
- server/test/repository/AccountRepositoryTest.java
Refactor AccountRepository.updateSerializedIdTokens to take the idToken rather than the whole OidcProfile that it doesn't need. This makes the code easier to read and simplifies the test a bit.
> Refactor AccountRepository.updateSerializedIdTokens

- server/app/auth/oidc/applicant/GenericOidcClientProvider.java
- server/app/services/settings/SettingsManifest.java
- server/conf/env-var-docs.json
- server/conf/helper/auth.conf
- server/test/auth/oidc/applicant/GenericOidcClientProviderTest.java
Adding name suffix attribute for OIDC client provider.
Fixes #8381
> [Suffix] add name suffix attribute for OIDC client provider

- server/app/durablejobs/DurableJobName.java
- server/app/durablejobs/jobs/AddOperatorToLeafAddressServiceAreaJob.java
- server/app/durablejobs/jobs/RemoveOperatorFromLeafAddressServiceAreaJob.java
- server/app/modules/DurableJobModule.java
- server/app/services/program/predicate/LeafAddressServiceAreaExpressionNode.java
- server/app/services/program/predicate/PredicateGenerator.java
- server/app/views/admin/programs/ProgramPredicateConfigureView.java
- server/test/durablejobs/jobs/AddOperatorToLeafAddressServiceAreaJobTest.java
- server/test/durablejobs/jobs/RemoveOperatorFromLeafAddressServiceAreaJobTest.java
- server/test/repository/VersionRepositoryTest.java
- server/test/services/applicant/ApplicantServiceFastForwardEnabledTest.java
- server/test/services/applicant/ApplicantServiceTest.java
- server/test/services/applicant/BlockTest.java
- server/test/services/applicant/ServiceAreaUpdateResolverTest.java
- server/test/services/applicant/predicate/JsonPathPredicateGeneratorTest.java
- server/test/services/program/BlockDefinitionTest.java
- server/test/services/program/ProgramDefinitionTest.java
- server/test/services/program/predicate/PredicateAddressServiceAreaNodeExtractorTest.java
- server/test/services/program/predicate/PredicateExpressionNodeTest.java
- server/test/services/program/predicate/PredicateGeneratorTest.java
This adds the `Operator` enum to the `LeafAddressServiceAreaExpressionNode`. Originally it was made with a hard-coded assumption that this would only ever have a single option. Adding the operator will opens up related work to allow for doing eligibility not in an area.
There are two startup jobs being created. One adds the operator to existing `program.block_definitions` jsonb columns; the other removes it. The removal one should hopefully never be used and is guarded by the three-headed dog cerberus to prevent accidental use.
Related to #6800
> Adding Operator property to LeafAddressServiceArea

- server/app/services/export/QuestionJsonSampler.java
- server/app/services/question/QuestionAnswerer.java
- server/test/controllers/applicant/ApplicantProgramBlocksControllerTest.java
- server/test/services/applicant/ReadOnlyApplicantProgramServiceImplTest.java
- server/test/services/applicant/question/FileUploadQuestionTest.java
- server/test/services/export/AbstractExporterTest.java
- server/test/services/export/JsonExporterServiceTest.java
- server/test/services/export/PdfExporterTest.java
Following up from previous PR. Adding option to answer file uploads with a list, instead of index by index. 
> Add list method for answering multi-file upload questions

- server/app/services/export/JsonExporterService.java
- server/app/services/export/ProgramJsonSampler.java
Move parsing of all program versions outside of the loop that exports each application, so we're not re-parsing every version for every application.
This reduces JSON export time from `O(n * v)` to `O(n)`, where `n` is the number of applications being exported and `v` is the number of versions the program has.
On my local, with ~2000 applications to Comprehensive Sample Program, this reduces export time to ~10s, instead of 10-15s per version
This is a quick improvement for #8147, but more work will follow to further improve export performance.
As a result of these changes, the order of fields in the exported JSON objects may have changed. The order of objects themselves has not.
Read the full guidelines for PRs [here](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#c …
> Improve performance of JSON export by only parsing all program versions once

- server/app/controllers/admin/AdminExportController.java
- server/test/controllers/admin/AdminExportControllerTest.java
- server/test/support/ProgramBuilder.java
Currently, program import will break if the program being imported has categories on it. We want to remove the categories on export to get around this error for now. We will add handling of program categories at a later time.
1. Make sure the program migration and program filtering feature flags are one
2. Create a program with categories
3. Export it (categories should be an empty array in the json)
4. Attempt to import it
5. You should see the program preview with no errors
Fixes #8422
> [Program Migration] Ignore program categories

- server/app/repository/ProgramRepository.java
Add explicit joins to two programs queries:
- `getAllProgramVersions()`, which was not joining on the Categories table, resulting in additional queries when building a ProgramDefinition
- `getApplicationsForAllProgramVersions()`, which was not joining on the Applicants table. The applicants table is needed because the `ReadOnlyApplicantProgramService` needs a full `Applicant`.
These were especially impactful when exporting thousands of applications at a time.
Part of fixing #8147
> Add explicit joins to programs queries to reduce n+1 queries

- server/app/repository/ApplicationRepository.java
- server/app/services/export/CsvExporterService.java
- server/app/services/program/ProgramService.java
Use more efficient Application retrieval queries in CsvExporterService.
Details:
- Caches all ProgramDefinitions locally before exporting.
- Only fetch applications once, instead of once in `generateCsvConfig()` and again in `getProgramAllVersionsCsv()`.
- Retrieve applications with  `programService.getSubmittedProgramApplicationsAllVersions()`, which is optimized for export, instead of `programService.getSubmittedProgramApplications()`.
- Update `getDemographicsCsv()` to use the ProgramDefinition cache in CsvExporterService.
- Note: To enable `getProgramAllVersionsCsv()` and `getDemographicsCsv()` to use different caches, we had to pass the cache's retrieval method into `exportCsv()` instead of the cache itself. I don't love this, but I'm planning additional export improvements soon so …
> Use more efficient Application retrieval queries in CsvExporterService

- server/app/views/admin/programs/ProgramAdministratorProgramListView.java
- server/app/views/admin/programs/ProgramIndexView.java
- server/app/views/components/ProgramCardFactory.java
Currently, the CiviFormProfile is plumbed down through ProgramCardFactory.ProgramCardData.Builder, when all it really needs is isCiviFormAdmin. Instead, derive isCiviFormAdmin at the top and pass it down the call stack. This makes it clearer why the profile is needed, and moves the logic for handling missing profiles up to the views where there is other similar logic.
> Refactor ProgramCardFactory to plumb isCiviFormAdmin instead of CiviFormProfile

- server/app/controllers/admin/AdminImportController.java
- server/test/controllers/admin/AdminImportControllerTest.java
And and Or predicates didn't work with program migration, since we were assuming everything was a leaf. We now check the type and handle appropriately.
Tested the change with the program described in #8435
#8435
> Add support for additional predicates with program migration

- server/app/auth/ProfileUtils.java
Clean up Optional handling in ProfileUtils.getApplicantId:
* Remove an unnecessary call to Optional.map() - the result of map isEmpty iff the Optional itself was empty because getProfileData does not return Optional and map is not flatMap, so the map call is misleading and unnecessary.
* Remove the unnecessary orElseThrow - the conditional above already returns if the optional is empty, so it doesn't need to be handled again.
> Clean up Optional handling in ProfileUtils.getApplicantId

- server/app/auth/oidc/CiviformOidcLogoutActionBuilder.java
- server/app/auth/oidc/CiviformOidcProfileCreator.java
- server/test/auth/oidc/CiviformOidcProfileCreatorTest.java
Since March 2024, we have stored the session ID in the pac4j profile instead of the Play session. https://github.com/civiform/civiform/pull/6736 maintained backwards compatibility with existing sessions by continuing to read the session ID from the play session if it was there. Now that it's been 5 months, all sessions from March and earlier should have ended, and we no longer need to do that.
* Stop reading the session ID from the Play session (playWebContext.getNativeSession()) during login profile merge in CiviformOidcProfileCreator
* Stop reading the session ID from the Play session in order to get the id tokens for logout in CiviformOidcLogoutActionBuilder
* Update CiviformOidcProfileCreatorTest to actually test that the ID tokens are saved to the account during login when the …
> Remove backwards compatibility for session ID in Play session

- browser-test/src/applicant/questions/file.test.ts
- server/app/controllers/applicant/ApplicantProgramBlocksController.java
- server/test/controllers/applicant/ApplicantProgramBlocksControllerTest.java
Redirect instead of re-serving after adding/removing files. This is needed because otherwise we end up showing the URL of the re-directed Amazon request in the URL bar, which when refreshed tries to add/remove the file again (which is a no-op, but it's ugly).
Note this does change the behavior slightly, since before we retained error information and now we don't, I think this is OK since the errors will show up when they click "next" (like all the other questions do).
> [Multiple File Upload] Redirect instead of re-serving page

- browser-test/src/applicant/questions/name.test.ts
- server/app/views/applicant/NorthStarApplicantProgramBlockEditView.java
- server/app/views/questiontypes/NameQuestionFragment.html
Implement name suffix field in name question in thymeleaf. Name suffix is an optional dropdown field provided to the applicant when answering name question.
Enabled `NORTH_STAR_APPLICANT_UI` and `NAME_SUFFIX_DROPDOWN_ENABLED` flag as a civiform admin. Apply to a program and open name question as an applicant. Name suffix field should be there.
Fixes #7999
> [Suffix] implement name suffix field in thymeleaf

- server/test/controllers/ti/TrustedIntermediaryControllerTest.java
Several tests had two different calls to build() on the same builder, which is confusing to read and unnecessary extra work. Save the built object rather than the builder instead.
> Fix duplicate builder.build calls in TrustedIntermediaryControllerTest

- server/app/controllers/applicant/ApplicantProgramReviewController.java
- server/app/controllers/applicant/ApplicantProgramsController.java
- server/test/controllers/applicant/ApplicantProgramReviewControllerTest.java
#6809 created CiviFormProfileFilter which ensures that all user-facing requests have a CiviFormProfile. So all user-facing controllers should now be able to assume that the profile exists, rather than handling the case where it doesn't.
* Remove missing-profile handling from ApplicantProgramReviewController and ApplicantProgramsController
* Remove redundant calls to currentUserProfile() within the same method
This is similar to #8445.
This is for #5971.
> Remove more missing-profile redirects

- server/app/actions/ApplicantAuthorizationAction.java
- server/app/controllers/CiviFormController.java
- server/app/controllers/FileController.java
- server/app/controllers/admin/AdminApiKeysController.java
- server/app/controllers/admin/AdminApplicationController.java
- server/app/controllers/admin/AdminReportingController.java
- server/app/controllers/admin/AdminSettingsController.java
- server/app/controllers/admin/ProgramAdminController.java
- server/app/controllers/applicant/ApplicantInformationController.java
- server/app/controllers/applicant/ApplicantProgramBlocksController.java
- server/app/controllers/applicant/ApplicantProgramReviewController.java
- server/app/controllers/applicant/ProgramSlugHandler.java
- server/app/views/applicant/ProgramCardViewRenderer.java
- server/app/views/applicant/ProgramCardsSectionParamsFactory.java
- server/test/actions/ApplicantAuthorizationActionTest.java
- server/test/controllers/admin/AdminApplicationControllerTest.java
- server/test/controllers/ti/TrustedIntermediaryControllerTest.java
Replace:
* ProfileUtils.optionalCurrentUserProfile(request).get()
* ProfileUtils.optionalCurrentUserProfile(request).orElseThrow()
* ProfileUtils.optionalCurrentUserProfile(request) followed by throwing an exception if profileOptional.isEmpty()
all of which throw an exception if the profile is missing, with ProfileUtils.currentUserProfile which also throws an exception if the profile isn't present.
currentUserProfile throws MissingOptionalException whereas Optional.get and orElseThrow throw NoSuchElementException, so I changed checkProgramAdminAuthorization's javadoc and its callers accordingly.
> Replace optionalCurrentUserProfile with currentUserProfile where appropriate

- browser-test/src/support/index.ts
The `loginAsTestUserFakeOidc` was using `networkidle` on `waitForURL` calls. Playwright recommends avoiding the use of network idle. This PR removes it for the default of `load`. It cuts around `1000ms` from the call.
> 'networkidle' - DISCOURAGED consider operation to be finished when there are no network connections for at least 500 ms. Don't use this method for testing, rely on web assertions to assess readiness instead.
This will only affect the dev and ci. Going to let this run for a bit to make sure there no issues and look at doing the same to the other test user login methods.
> Remove the networkidle wait on test user logins

- server/app/controllers/admin/NorthStarQuestionPreviewController.java
- server/app/controllers/applicant/UpsellController.java
- server/app/controllers/ti/TrustedIntermediaryController.java
- server/app/views/api/ApiDocsView.java
- server/test/controllers/admin/AdminProgramImageControllerTest.java
#6809 created CiviFormProfileFilter which ensures that all user-facing requests have a CiviFormProfile. So all user-facing controllers should now be able to assume that the profile exists, rather than handling the case where it doesn't.
This is for https://github.com/civiform/civiform/issues/5971.
> Remove more missing-profile handling

- server/app/services/settings/SettingsManifest.java
- server/conf/env-var-docs.json
- server/conf/helper/feature-flags.conf
This will gate an alternate version of program migration, where no duplicate questions are created and instead we use existing questions when available. This should only be used on new environments or non-production environments.
https://github.com/civiform/civiform/issues/8533
> Create a feature flag for program migration without duplicate questions created

- server/app/views/admin/programs/ProgramFormBuilder.java
Update ProgramFormBuilder constructor to use immutable collections
Part of #8436
> Update ProgramFormBuilder constructor to use immutable collections

- server/app/assets/Images/uswds/icon-check-circle.svg
- server/app/assets/stylesheets/northstar/_uswds-theme-custom-styles.scss
- server/app/views/applicant/ProgramCardsSectionFragment.html
In North Star program cards, style the eligibility tag.
Add the USWDS check-circle icon to CiviForm.
[Mocks](https://www.figma.com/design/RmhVJCLgAKWGENJLWWAtNS/CiviForm%3A-Components%2C-Styles?node-id=3336-1526&m=dev)
Contributes to #8157
> Style eligibility tag. Add check-circle icon.

- server/app/services/applicant/ReadOnlyApplicantProgramServiceImpl.java
- server/test/services/applicant/ReadOnlyApplicantProgramServiceImplTest.java
- server/test/services/export/CsvExporterServiceTest.java
Export multiple file answers for CSV exports. This exports in the same format as other answers which are lists.
> [Multiple File Uploads] Add support for CSV exports for multiple file questions

- browser-test/src/support/ti_dashboard.ts
- browser-test/src/trusted_intermediary.test.ts
- server/app/services/ti/TrustedIntermediaryService.java
- server/app/views/applicant/EditTiClientView.java
- server/app/views/components/FieldWithLabel.java
- server/app/views/components/SelectWithLabel.java
- server/app/views/questiontypes/NameQuestionRenderer.java
1. Adds name suffix field to TI dashboard so that TI can add name suffix information for applicants. 
2. Making sure that the suffix field on TI dashboard fits USWDS standard.
Log in as a TI, add an new client,  fill out their info including suffix. Then try applying for an application for the applicant, when on name question page, suffix field should be filled with the value that was preset by the TI.
Fixes #8405
> [Suffix] add suffix field on ti dashboard

- server/app/controllers/dev/DevToolsController.java
- server/app/views/NorthStarBaseView.java
- server/app/views/dev/AddressCheckerView.java
- server/app/views/dev/DebugContent.java
- server/app/views/dev/DevToolsView.java
- server/conf/routes
- server/test/controllers/dev/DevToolsControllerTest.java
Rename these classes because they are not specific to seeding anymore and are rather general dev tools classes:
* controllers.dev.seeding.DevDatabaseSeedController -> controllers.dev.DevToolsController
* DatabaseSeedView -> DevToolsView
> Rename dev seed classes to dev tools

- browser-test/src/admin/admin_program_email_notifications.test.ts
- browser-test/src/support/admin_programs.ts
Add browser tests for program email notifications settings
Details:
- Until #8575 is complete, we can't add tests that verify the entire flow. That's captured in #8576.
- Here, we test that the setting is persisted to the database. There are unit tests verify that the email sending code works correctly when an application is submitted.
Part of #8436
> Add browser tests for program email notifications settings

- server/app/controllers/dev/AddressCheckerController.java
- server/app/controllers/dev/DevToolsController.java
- server/app/controllers/dev/FeatureFlagOverrideController.java
- server/app/controllers/dev/IconsController.java
- server/app/filters/DevRoutesFilter.java
- server/conf/application.conf
- server/test/controllers/dev/DevToolsControllerTest.java
- server/test/controllers/dev/FeatureFlagOverrideControllerTest.java
Add DevRoutesFilter, which returns 404 not found in prod for all /dev routes. Remove now-unnecessary checks in the relevant controller methods.
Fixes #8583
> Add DevRoutesFilter to ensure all /dev routes are only available in dev/staging

- browser-test/src/applicant/applicant_application_index.test.ts
- server/app/views/applicant/AddressCorrectionBlockTemplate.html
- server/app/views/applicant/ApplicantCommonIntakeUpsellTemplate.html
- server/app/views/applicant/ApplicantProgramBlockEditTemplate.html
- server/app/views/applicant/ApplicantProgramFileUploadBlockEditTemplate.html
- server/app/views/applicant/ApplicantProgramSummaryTemplate.html
- server/app/views/applicant/ApplicantUpsellTemplate.html
- server/app/views/applicant/IneligibleTemplate.html
- server/app/views/applicant/ModalFragment.html
- server/app/views/applicant/NavigationFragment.html
- server/app/views/applicant/PreventDuplicateSubmissionTemplate.html
- server/app/views/applicant/ProgramIndexTemplate.html
Separate fragments for different kinds of modals.
With this refactoring, it is no longer necessary to remove the modal container in issue #7880 (we just add id="modal-container" to each modal parent div and keep north_star_modal.ts unchanged)
Credit to Greg for paving the way with https://github.com/civiform/civiform/pull/7879
Fixes #7880.
> Refactor North Star modals to be easier to use

- server/app/models/ProgramModel.java
Remove unused `getSubmittedApplication()` method.
Details:
- It doesn't make sense to fetch applications for a single version, and we shouldn't do it this way anyway.
- Adds the @Keep annotation to supress Errorprone
- [n/a] Extended the README / documentation, if necessary. For user-facing features, consider updating [the user docs](https://github.com/civiform/docs). For "under-the-hood" changes or things more relevant to developers, consider updating [the dev …
> Remove unused getSubmittedApplication() method

- server/app/repository/ApplicationRepository.java
If a new guest account tries to load a deep link with an old program id it was hitting an error since the guest account may not have yet had an draft application created. This will just update drafts if found and stop erroring if one isn't found.
> Fast-forward deep link bug for guest

- server/app/views/components/TextFormatter.java
- server/test/views/components/TextFormatterTest.java
Allow `<ol>` elements to continue numbering as entered instead of resetting to 1 in places that use custom markdown.
> Allow OLs to continue numbering

- server/conf/application.conf
Fix the commented-out play.http.session.maxAge setting to have a value that actually works so future readers don't get confused like I did.
Relevant docs: https://www.playframework.com/documentation/2.9.x/ConfigFile#Duration-format
> Fix format on play.http.session.maxAge setting example

- browser-test/src/applicant/applicant_application_index.test.ts
- server/app/views/applicant/ModalFragment.html
- server/app/views/applicant/ProgramCardsSectionParamsFactory.java
In the North Star, if a program didn't have an external link, clicking on "View details" in the program card would redirect to the homepage.  The expected behavior is to open the program details page in a new tab.  This is the existing behavior pre-North Star.
1. Log in as a CiviForm admin.
2. Edit the details for a program, removing anything under "Link to program website".
3. Publish your changes.
4. Log out.
5. Find that program card on the homepage and click "View details".
6. Observe that a new tab opens with the program details view and this URL: "/programs/<program id>"
Fixes #8498
> Fix North Star bug when program has no external link

- browser-test/src/applicant/applicant_application_index.test.ts
- server/app/views/applicant/ModalFragment.html
- server/app/views/applicant/NorthStarProgramIndexView.java
- server/app/views/applicant/ProgramCardsSectionFragment.html
- server/app/views/applicant/ProgramIndexTemplate.html
1. User is NOT logged in
1. User opens program index (home) page for the first time in a session
1. User clicks "Apply"
* Before: Login modal appears
* After: CiviForm navigates directly to the application
Fixes #8496
> Remove login modal when clicking on "Apply" for the first time

- server/app/views/components/TextFormatter.java
- server/test/views/components/TextFormatterTest.java
When an empty string was passed to the markdown text formatting it would return `<p></p>`. This will now return an empty string if the input string is solely empty or whitespace so aberrant paragraph elements are not added. Normal formatting will remain as long as there is some content to show.
Fixes #8537
> Don't apply markdown formatting to empty/whitespace only text

- server/conf/application.conf
- server/conf/application.dev.conf
Change the reportOnly setting for CSP from true to false by default. The setting can still be overridden with the [CSP_REPORT_ONLY](https://github.com/civiform/civiform/blob/fb32344e118fc977609de00fd1deb34e44e7082f/server/conf/env-var-docs.json#L629) configuration variable.
Also remove the override in application.dev.conf since false is now the default.
This is for #7574.
> Enable CSP enforcement by default

- .github/pull_request_template.md
Updating the wording for the screen reader checklist item on the PR template to say "applicant-facing" rather than "resident-facing", for consistency.
> Update wording for screen reader checklist item on PR template

- server/app/services/settings/SettingsManifest.java
- server/app/views/NorthStarBaseView.java
- server/app/views/applicant/ApplicantLayout.java
- server/conf/env-var-docs.json
Charlotte would like the ability to hide the "demo tools" button, so they can share their staging programs without people logging in as an admin and changing things. This flag already existed, but was hidden, so this makes it admin writeable. This flag won't do anything in non demo / staging environments
> Make demo mode login button configurable in settings panel

- browser-test/src/admin/admin_application_statuses.test.ts
- server/app/auth/oidc/applicant/ApplicantProfileCreator.java
- server/app/controllers/admin/AdminApplicationController.java
- server/app/controllers/ti/TrustedIntermediaryController.java
- server/app/models/AccountModel.java
- server/app/models/TrustedIntermediaryGroupModel.java
- server/app/services/applicant/ApplicantData.java
- server/app/services/export/PdfExporter.java
- server/app/services/ti/TrustedIntermediaryService.java
- server/app/views/admin/programs/ProgramApplicationListView.java
- server/app/views/admin/ti/EditTrustedIntermediaryGroupView.java
- server/app/views/applicant/NorthStarApplicantUpsellView.java
- server/app/views/applicant/TrustedIntermediaryAccountSettingsView.java
- server/app/views/applicant/TrustedIntermediaryClientListView.java
- server/test/auth/oidc/applicant/GenericApplicantProfileCreatorTest.java
- server/test/services/applicant/ApplicantDataTest.java
- server/test/services/ti/TrustedIntermediaryServiceTest.java
Fixes #8344, we no longer populate applicant name with email if the auth provider fills in the name attribute with the same value as the email attribute. With this change, name is now empty if no name is provided, so we no longer populate an email  in the universal question first name field. Added a new "getApplicantDisplayName" which instead looks for name, and falls back to email if it's not there. 
Fixes #8344
> Don't set email as name when creating profiles

- server/test/auth/oidc/applicant/GenericApplicantProfileCreatorTest.java
Fix compile error from these two PRs being merged around the same time:
* https://github.com/civiform/civiform/pull/8685
* https://github.com/civiform/civiform/pull/8557
> Fix compile error from commit race condition

- server/app/controllers/admin/AdminImportController.java
- server/test/controllers/admin/AdminImportControllerTest.java
This change adds the ability to handle `LEAF_ADDRESS_SERVICE_AREA` type nodes for eligibility and visibility predicates which will allow importing programs that use service area validation in eligibility/visibility settings.
1. Enable the `PROGRAM_MIGRATION_ENABLED` flag
2. Create a program that uses service area validation on an address question to determine eligibility or visibility
3. Export the json for this program and test that you can successfully import this program.
Fixes #8450
> [Program Migration] Handle service area validation in program import

- browser-test/src/applicant/northstar_common_intake_upsell.test.ts
- browser-test/src/applicant/northstar_upsell.test.ts
- server/app/views/applicant/ApplicantCommonIntakeUpsellTemplate.html
- server/app/views/applicant/ApplicantUpsellTemplate.html
- server/app/views/applicant/CreateAccountAlertFragment.html
- server/app/views/applicant/NorthStarApplicantCommonIntakeUpsellView.java
- server/app/views/applicant/NorthStarApplicantUpsellView.java
Fix create account button and login link. This applies to:
* "Application Submitted" page
* "Common Intake Submitted" page
Fixes https://github.com/civiform/civiform/issues/8480
> Fix create account button and login link

- server/app/services/settings/SettingsManifest.java
- server/conf/env-var-docs.json
- server/conf/helper/feature-flags.conf
Add a feature flag for session replay protection. We don't want admins to change it so it's ADMIN_READABLE.
This is for #6975.
> Add config flag for session replay protection

- server/app/models/AccountModel.java
- server/app/models/SessionDetails.java
- server/conf/evolutions/default/77.sql
- server/test/models/AccountModelTest.java
Implement the active_sessions data model per the [session replay TDD](https://docs.google.com/document/d/1AOEebYiUVKnVfmO1JgutflyM3vZ_ltoVecH7TUhyhaE).
* Add activeSessions to AccountModel with a new SessionDetails class to store details about each session
* Mark idTokens with a TODO to remove later
* Implement methods in AccountModel to manage activeSessions, and add unit tests in AccountModelTest
* Define a database evolution to add the number column to the accounts table
This is for #6975.
> Implement active_sessions data model

- browser-test/src/admin/admin_program_image.test.ts
- browser-test/src/support/admin_program_image.ts
- server/app/controllers/admin/NorthStarProgramCardPreviewController.java
- server/app/views/admin/programs/NorthStarProgramCardPreview.java
- server/app/views/admin/programs/ProgramCardPreviewFragment.html
- server/app/views/admin/programs/ProgramImageView.java
- server/app/views/applicant/ProgramCardsSectionParamsFactory.java
- server/conf/routes
As admin, on the image upload page, show previews of North Star program cards.
- [n/a] Tested on mobile view. See [mobile device mode](https://developer.chrome.com/docs/devtools/device-mode/)
- [n/a] Manually tested at 200% size
- [n/a] Manually tested with a screen reader if the feature is applicant-facing. See [screen reader testing](https://github.com/civiform/civiform/wiki/Testing#screen-reader-testing)
1. Enable North Star
2. Log in as admin
3. Edit a program
4. …
> Support admin previews of NS program cards

- server/app/services/Address.java
- server/app/services/geo/esri/EsriClient.java
- server/app/services/geo/esri/FakeEsriClient.java
- server/app/services/geo/esri/RealEsriClient.java
- server/app/services/geo/esri/models/FindAddressCandidatesResponse.java
- server/test/services/geo/esri/EsriClientTest.java
- server/test/services/geo/esri/EsriTestHelper.java
- server/test/services/geo/esri/FakeEsriClientTest.java
- server/test/services/geo/esri/RealEsriClientTest.java
Fixes address correction bug that may occur if the response from calling ESRI is an empty JSON object. This bug can happen if the arcgis.com token is incorrect or if the arcgis.com token has expired or is out of credits.
> Fixing address correction spliterator bug

- mock-web-services/esri/__init__.py
- server/test/resources/esri/esriErrorResponse.json
Add a sample of the generic esri error response format to the mock web services.
> Adding esri error response to mock web services

- browser-test/src/applicant/questions/file.test.ts
- server/app/views/applicant/ApplicantFileUploadRenderer.java
Adds aria-labelled by to remove flie link so that screen readers alert which file will be removed.
Fixes #8721
> [Multiple File Upload] Add context for remove link for screen readers

- server/app/assets/stylesheets/styles.css
- server/app/assets/stylesheets/uswds/_uswds-theme-custom-styles.scss
- server/app/views/applicant/ProgramIndexView.java
Replace the filter chip `<div>` id with a CSS class for simplicity.  There was no other use of the id.
> Replace filter chip id with CSS class for simplicity

- server/app/services/geo/esri/RealEsriClient.java
Include the counts of usage of ESRI endpoint URIs in the `/metrics` output
> Include the uri endpoint called in metric counts

- browser-test/src/applicant/northstar_not_production_banner.test.ts
- server/app/services/AlertSettings.java
- server/app/services/AlertType.java
- server/app/views/NorthStarBaseView.java
- server/app/views/applicant/NavigationFragment.html
- server/app/views/components/AlertFragment.html
Add floating "Not Production" banner in North Star.
This component does not have mocks. See https://github.com/civiform/civiform/issues/8490
https://github.com/civiform/civiform/issues/8490
> Add floating "Not Production" banner in North Star

- browser-test/src/applicant/northstar_not_production_banner.test.ts
- server/app/views/NorthStarBaseView.java
- server/app/views/components/AlertFragment.html
Gwen noticed a bug in PR https://github.com/civiform/civiform/pull/8767: This doesn't work correctly if you've set CIVIC_ENTITY_PRODUCTION_URL back to an empty string at some point. The settings will return isPresent=true but with an empty string. Causing the second line to show a link with no href
This PR fixes said bug.
Fixes #8490
> Fix banner bug when civic entity production URL is an empty string

- browser-test/src/applicant/application_address_correction.test.ts
- server/app/services/geo/esri/RealEsriClient.java
- server/app/services/geo/esri/models/EsriError.java
- server/app/services/geo/esri/models/FindAddressCandidatesResponse.java
- server/test/services/geo/esri/EsriClientTest.java
- server/test/services/geo/esri/EsriTestHelper.java
There are cases where the Esri service may return a 200, but the response is in an error object format. I know this can happen if you are using arcgis.com and run out of credits. This will aid in troubleshooting by logging the details of the error response object.
> Handle Esri Error response

- browser-test/src/applicant/application_download.test.ts
- server/app/services/applicant/question/NameQuestion.java
- server/app/services/export/CsvExporterService.java
- server/test/services/export/AbstractExporterTest.java
- server/test/services/export/CsvExporterServiceTest.java
- server/test/services/export/PdfExporterTest.java
Uses `ApplicantQuestion`s to build `CsvExportConfig` instead of building `AnswerData` objects we mostly ignore, which reduces CSV export time.
This PR also:
- Changes the sort order for CSV columns. They are now sorted only by the question admin name.
- Adds the `file_urls` column to the CSV export, to align with the JSON export.
- Adds tests for the `name_suffix` field to the CSV tests.
Fixes #8843
> Use ApplicantQuestions directly to build CsvExportConfig

- docker-compose.dev.yml
This makes it so that we dont run into CSRF errors when running the tool in a web-only codespace.
Disabling CSRF should not have an impact on usages of the container in a local VS code or other environments.  Typically this would be a security issue for producion code, but since this is a dev-only tool that is only run against local dev databsaes, there should be no security concern.
This change has no impact on release components, and can be ignored in the release notes.
> Add flag PGADMIN_CONFIG_WTF_CSRF_ENABLED = False to the dev pgadmin docker container

- server/app/views/applicant/ProgramIndexView.java
Programs weren't being filtered in languages other than English because we were trying to match the localized names of the categories to the default category names (English) on programs.
1. If you haven't already, go to the Dev Tools and click "Seed programs and categories".
2. Log in as an admin and add a couple of categories to a program.
3. Publish your changes.
4. Logout
5. Use the language dropdown to switch to another language.
6. Click a program filter.
7. Any programs with that category should appear in the "Programs based on your selections" section.
Fixes #8865
> Fix bug in program filtering when user switches to another language

- .github/pull_request_template.md
The Downs script in https://github.com/civiform/civiform/pull/8664 has a syntax error, so it can't run. But fixing the syntax error in 78.sql prompts play to try to run the broken downs script it has stored in its database.
To help guard against this happening again, we should manually test the downs script, including comments.
> Add step to evolutions PR template to test downs

- browser-test/src/admin/admin_program_translation.test.ts
Un-skip translation test.
History:
1. The test is created. It checks that the review page contains a translated title and description.
1. PR #8782 changes navigation to bypass the review page in North Star. The test is skipped.
1. PR #8848 adds translated block titles to the applicant block edit page. This indirectly fixes the test since a translated title is now present on the first page that the applicant sees after clicking "Apply".
Should we check block descriptions? No, because block descriptions are not used in North Star.
Fixes #8796
> Un-skip translation test

- server/app/services/settings/SettingsManifest.java
- server/app/views/applicant/ApplicantFileUploadRenderer.java
- server/app/views/applicant/NorthStarApplicantProgramBlockEditView.java
- server/app/views/questiontypes/FileUploadQuestionFragment.html
- server/conf/application.conf
- server/conf/env-var-docs.json
File upload used a hard-coded accept list of file type specifiers. It was brought to my attention that a new program now live in Seattle requires applicants to submit a spreadsheet filled out from a template supplied by the program.
This change just allows setting the value from the config file.
There is a new, optional, configuration value to control the types of files that applicants are allowed to upload on file upload questions.
The default options remain as images and PDFs. To customize set the `FILE_UPLOAD_ALLOWED_FILE_TYPE_SPECIFIERS`. This uses any valid [file type specifiers](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/accept#unique_file_type_specifiers). Multiple are separated by commas. …
> Pull file upload file type specifiers from config

- server/app/durablejobs/AbstractDurableJobRunner.java
- server/app/durablejobs/RecurringDurableJobRunner.java
- server/app/durablejobs/StartupDurableJobRunner.java
- server/app/services/applicant/ApplicantService.java
- server/app/services/applications/ProgramAdminApplicationService.java
- server/app/services/email/aws/SimpleEmail.java
- server/test/durablejobs/RecurringDurableJobRunnerTest.java
- server/test/durablejobs/StartupDurableJobRunnerTest.java
- server/test/services/applicant/ApplicantServiceFastForwardEnabledTest.java
- server/test/services/applicant/ApplicantServiceTest.java
- server/test/services/applications/ProgramAdminApplicationServiceTest.java
Move SimpleEmail class from services/cloud/aws directory to services/email/aws directory. This makes email its own directory, so we are no longer 1:1 of cloud provider to email provider. This is based off the plan described in [TDD](https://docs.google.com/document/d/1rKkir5-9Y4Ka9icen_K2qCFCGOQ5BO2qtdROOl_002w/edit?tab=t.0#heading=h.bknox3ib8wpb)
https://github.com/civiform/civiform/issues/8810
> Refactor SimpleEmail to be in new services/email directory

- server/app/auth/oidc/admin/GenericOidcProfileCreator.java
Charlotte set up Okta and admins are able to login, but people added to their CiviForm admins group are not being recognized as global admins, and instead just seeing the program admin view.
https://github.com/civiform/civiform/issues/8965
> Add debugging to troubleshoot global admin permissions

- server/app/services/settings/SettingsManifest.java
- server/conf/application.conf
- server/conf/env-var-docs.json
Remove the CSP_REPORT_ONLY config variable, which allowed overriding the enablement of CSP enforcement.
CSP enforcement was enabled by default in #8218, and it has been in prod long enough that we are confident we won't need to disable it suddenly.
Fixes #7574
> Remove config variable for CSP enforcement

- browser-test/src/applicant/applicant_application_index.test.ts
- server/app/views/applicant/ProgramCardsSectionFragment.html
- server/app/views/applicant/ProgramCardsSectionParamsFactory.java
Adding category tags to program cards in the North Star.  This PR only includes basic styling.  Styling and accessibility considerations will be addressed in #8157. 
1. Enable the North Star and program filtering flags.
2. Go to Dev Tools, Additional Tools and click "Seed Programs and Categories", if you haven't already.
3. Log in as an admin.
4. Edit a few programs and add categories. 
5. Publish your changes.
6. Go to the homepage.
7. Categories should show on program cards that are in the "Programs and services" section, but should not show on those in the "My applications" section.
> Show categories on North Star program cards

- browser-test/src/applicant/questions/file.test.ts
There has been an intermittent file upload failure when both multi-file upload and northstar are enabled. Swapping to use a different (existing) way to check that the file name was added. The other method uses the older and not great  `expect->await` order and tries to check the entire page for the filename.
It's more involved right now to fix the other assert as older non-mfu/non-ns tests failed. Some of this will get cleaned up when northstar goes live so as long as the flaky test is working we should be fine.
> Fix intermittent test bug

- server/conf/application.dev.conf
- server/test/services/applicant/ApplicantServiceFastForwardEnabledTest.java
- server/test/services/applicant/ApplicantServiceTest.java
This reverts commit 3206db42ed6abe7c7fd0ba9eac1a81e6d90d6573.
Having it enabled by default right now results in tests failing on dev staging with CSP errors. Jeff's fix to USWDS is tentatively slated for November.
Related to: #8923
> Revert "Enable multi-file upload on dev (#8923)"

- browser-test/src/applicant/questions/file.test.ts
- server/app/views/applicant/ApplicantProgramFileUploadBlockEditTemplate.html
- server/app/views/fileupload/FileUploadViewStrategy.java
- server/test/views/fileupload/FileUploadViewStrategyTest.java
Support adding a file with the same name as an already uploaded file in north star.
> [Multiple File Upload] Add duplicate file handling to North Star

- server/app/services/MessageKey.java
- server/conf/i18n/messages
- server/conf/i18n/messages.am
- server/conf/i18n/messages.ar
- server/conf/i18n/messages.es-US
- server/conf/i18n/messages.fr
- server/conf/i18n/messages.ko
- server/conf/i18n/messages.lo
- server/conf/i18n/messages.so
- server/conf/i18n/messages.tl
- server/conf/i18n/messages.vi
- server/conf/i18n/messages.zh-TW
Delete button.print from messages since it's unused. It became obsolete in PR #8950.
Related to #8299
> Delete button.print from messages since it's unused

- server/app/controllers/admin/AdminImportController.java
- server/test/controllers/admin/AdminImportControllerTest.java
This is a bug fix to surface a user facing an error when a server error occurs. Previously nothing would show and it would just look like nothing was happening.
There were two cases during bug bash where testers triggered a server error:
- trying to save a program with a language that doesn't exist
- trying to save a program where the question id on the question and in the block definition do not match
This fix handles both of those cases and should handle any other server errors that occur when attempting to render the program preview.
1. Enable program migration flag
2. Copy program json into the import box
3. Edit the question id in the block definition to be different than the question ids on the questions
4. Click "Preview program"
5. See error message
Fixes #8653;
> [Program Migration] handle server errors

- Dockerfile
- formatter/formatter.Dockerfile
Renovate still seems to have issues updating the `bellsoft/liberica-openjdk-alpine` version.
> Update liberica openjdk to 17.0.13

- server/app/assets/stylesheets/northstar/_uswds-theme-custom-styles.scss
- server/app/views/applicant/NorthStarAnswerData.java
- server/app/views/applicant/QuestionSummaryFragment.html
Enable multi-line answers on the "Application Summary" page. This allows displaying multiple file names for file upload questions.
Fixes #8793
> Enable multi-line answers on the "Application Summary" page

- server/app/services/migration/ProgramMigrationService.java
- server/test/services/migration/ProgramMigrationServiceTest.java
This is a bug fix for program migration to prevent importing pre-screener/common intake programs. All programs should be imported with the "default" type and set to "pre-screener" explicitly in the import environment. 
Corresponding docs update: https://github.com/civiform/docs/pull/528
1. Turn on the program migration flag
2. Add a program and mark it as a pre-screener
3. Export the program -- should see "programType: DEFAULT" in the export json
4. Import the program -- program should not be imported as a pre-screener
Fixes #8652
> [Program Migration] Reset program type to default on export

- browser-test/src/applicant/applicant_application_index.test.ts
- browser-test/src/applicant/applicant_prevent_duplicate_submission.test.ts
- browser-test/src/applicant/navigation/northstar_application_navigation_buttons.test.ts
- browser-test/src/applicant/northstar_common_intake_upsell.test.ts
- browser-test/src/applicant/northstar_ineligible.test.ts
- browser-test/src/applicant/northstar_upsell.test.ts
- browser-test/src/support/admin_programs.ts
- server/app/controllers/applicant/ApplicantRoutes.java
- server/app/views/admin/programs/ProgramBlocksView.java
- server/app/views/applicant/ProgramCardsSectionParamsFactory.java
Fix navigation when applying to a program with admin-specified block order. (See #8876 and #8944 for details)
To manually test, follow the instructions in #8876 and #8944
Fixes #8876 and #8944
> Fix navigation when applying to a program with admin-specified block order

- .github/workflows/contributor_response.yml
Added a repository variable named `CONTRIBUTOR_COMMENT_AUTO_REPLY_IGNORE_LIST`. It is a csv of user or domain names.  If commenter's username is on the list or their email address ends with the domain, do not reply.
The email check is a best attempt. If the user did not set a public email address it will be empty.
I also moved the list of bots into the ignore list repository variable.
Fixes #9039
> Have contributor autoresponder check an ignore list

- server/app/views/applicant/ApplicantBaseFragment.html
Adding meta tag to set viewport so mobile works correctly.
Fixes #9035
> Adding Viewport to Northstar

- server/app/controllers/admin/AdminImportController.java
- server/app/views/admin/migration/AdminImportViewPartial.java
- server/test/controllers/admin/AdminImportControllerTest.java
This is a bug fix for program migration to prevent users from accidentally submitting negative block ids in the program json.
There are two other minor fixes here:
1. Including the original error text in the server error message so it is more informative
2. Redirecting to the first screen of the program when the user clicks the "View program" button, instead of the screen with block id "1" which could be in the middle of the program if the admin rearranged the screens.
Fixes #8649;
> [Program Migration ] Prevent negative block ids

- browser-test/src/applicant/applicant_application_index.test.ts
- browser-test/src/applicant/application_address_correction.test.ts
- browser-test/src/applicant/navigation/application_navigation_flow.test.ts
- browser-test/src/applicant/northstar_program_summary.test.ts
- browser-test/src/applicant/northstar_upsell.test.ts
- browser-test/src/support/applicant_questions.ts
- server/app/controllers/applicant/ApplicantProgramReviewController.java
- server/app/services/MessageKey.java
- server/app/views/NorthStarBaseView.java
- server/app/views/applicant/ApplicantBaseFragment.html
- server/app/views/applicant/NorthStarAddressCorrectionBlockView.java
- server/app/views/applicant/NorthStarApplicantCommonIntakeUpsellView.java
- server/app/views/applicant/NorthStarApplicantIneligibleView.java
- server/app/views/applicant/NorthStarApplicantProgramBlockEditView.java
- server/app/views/applicant/NorthStarApplicantProgramSummaryView.java
- server/app/views/applicant/NorthStarApplicantUpsellView.java
- server/app/views/applicant/NorthStarProgramIndexView.java
- server/conf/i18n/messages
Before: tab titles were "Title", in English, regardless of selected language
After: tab titles are the same as legacy pages (e.g. home page is "Find Programs", localized to the user's selected language)
Fixes #8734
> Set tab titles to match legacy tab titles

- server/app/views/applicant/ApplicantProgramSummaryTemplate.html
On the summary page, add spacing below the alert.
> On summary page, add spacing below alert

- browser-test/playwright.Dockerfile
Renovate updated nodejs from v20 to v22 recently. This updates the test runner to match versions.
- [x ] Added the correct label: < feature | enhancement | bug | under-development | dependencies | infrastructure | ignore-for-release | database >
- [x ] Assigned to a specific person, `civiform/developers`, or a [more specific round-robin list](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-reviewers)
> Update nodejs version in tests

- .github/pull_request_template.md
Based on discussion in eng weekly. Add reminder to not log PII in PR template
> Add logging PII reminder to PR template

- browser-test/src/northstar_trusted_intermediary.test.ts
- server/app/assets/stylesheets/northstar/_uswds-theme-custom-styles.scss
- server/app/views/NorthStarBaseView.java
- server/app/views/applicant/NavigationFragment.html
Implement TI banner in North Star. There are no official mocks. It's a simple re-implementation of this:
- [n/a] Tested on mobile view. See [mobile device mode](https://developer.chrome.com/docs/devtools/device-mode/)
- [n/a] Manually tested with a screen reader if the feature is applicant-facing. See [screen reader testing](https://github.com/civiform/civiform/wiki/Testing#screen-reader-testing)
Fixes #9020
> Implement TI banner in North Star

- server/app/assets/stylesheets/northstar/_uswds-theme-custom-styles.scss
- server/app/views/applicant/ProgramCardsSectionFragment.html
[View UX mocks](https://www.figma.com/design/RmhVJCLgAKWGENJLWWAtNS/CiviForm%3A-Components%2C-Styles?node-id=3764-4671&m=dev)
[View USWDS Tags](https://designsystem.digital.gov/components/tag/)
Guidance from Sijia: if the mocks and USWDS conflict in a small way, go with USDWS
Part of #8157
> Style category tags on program cards

- server/app/views/questiontypes/EnumeratorQuestionFragment.html
This is checked [here](https://github.com/civiform/civiform/blob/2415824fc94d99fa72f0632e6445160c45f65933/server/app/assets/javascripts/enumerator.ts#L201), but currently it does nothing since these values are unset. Tests for this case are in the end to end enumerator tests, so will be added in https://github.com/civiform/civiform/issues/9073. 
Set enumerator entity max and then check that the button gets disabled when approaching the max
https://github.com/civiform/civiform/issues/9068
> Add min and max entities to enum button for disabling functionality to work

- browser-test/src/applicant/northstar_program_summary.test.ts
- browser-test/src/support/applicant_questions.ts
- server/app/assets/stylesheets/northstar/_uswds-theme-custom-styles.scss
- server/app/views/applicant/NorthStarAnswerData.java
- server/app/views/applicant/NorthStarApplicantProgramSummaryView.java
- server/app/views/applicant/QuestionSummaryFragment.html
Applicant can click file names to download files on the North Star summary page.
Fixes #8985
> Click to download files on summary page

- server/app/views/questiontypes/AddressQuestionFragment.html
- server/app/views/questiontypes/CheckboxQuestionFragment.html
- server/app/views/questiontypes/CurrencyQuestionFragment.html
- server/app/views/questiontypes/EmailQuestionFragment.html
- server/app/views/questiontypes/NameQuestionFragment.html
- server/app/views/questiontypes/NumberQuestionFragment.html
- server/app/views/questiontypes/RadioButtonQuestionFragment.html
In legacy, each question has a cf-question-* class. Some browser tests use this class as a way to locate elements. Adding these classes are necessary to migrate browser tests such as #8896.
- [n/a] Extended the README / documentation, if necessary. For user-facing features, consider updating [the user docs](https://github.com/civiform/docs). For "under-the-hood" changes or things more relevant to developers, consider updating [the dev wiki](https://github.com/civiform/civiform/wiki).
- [n/a] Ensured PII wasn't added to any new logs, unless it was guarded by …
> Add cf-question-* classes to North Star question fragments

- browser-test/src/admin/admin_program_migration.test.ts
- browser-test/src/support/admin_program_migration.ts
- server/app/controllers/admin/AdminImportController.java
- server/app/services/question/types/MultiOptionQuestionDefinition.java
- server/test/services/question/types/MultiOptionQuestionDefinitionTest.java
Validating that admin names for options in multi-option questions only contain certain characters is blocking Arkansas from importing some programs. This PR removes that validation step when importing a program. All other validation remains the same.
See [slack convo](https://civiform.slack.com/archives/C03KLLQQGTT/p1731006158358299) for more info.
Attempt to import the program json in the linked slack conversation. It should work with no errors!
> [Program Migration] Skip multioption admin name validation in program import

- server/app/views/applicant/ModalFragment.html
Fixing nested dialog roles.
The USWDS modal javascript automatically adds role=dialog to their wrapper element. This means we can't use the dialog element in modals as it ends up with nested dialogs in the accessibility tree.
> Swap element dialog to div for USWDS compatibility

- server/app/views/applicant/ApplicantBaseFragment.html
The svg icons should have `aria-hidden=true`. They are decorative and are always wrapped in an element with an aria-label denoting the button action already.
> Mark icons as hidden

- server/app/controllers/dev/DevToolsController.java
- server/app/durablejobs/DurableJob.java
- server/app/durablejobs/DurableJobExecutionContext.java
- server/app/durablejobs/DurableJobRegistry.java
- server/app/filters/ApiKeyUsageFilter.java
- server/app/filters/CiviFormProfileFilter.java
- server/app/filters/SettingsFilter.java
- server/app/models/JobType.java
- server/app/modules/DurableJobModule.java
- server/app/repository/DatabaseExecutionContext.java
- server/app/services/program/ActiveAndDraftPrograms.java
- server/app/services/question/ActiveAndDraftQuestions.java
- server/build.sbt
- server/conf/application.conf
- server/project/plugins.sbt
- server/test/controllers/applicant/ApplicantRoutesTest.java
- server/test/filters/RecordCookieSizeFilterTest.java
- server/test/filters/UnsupportedBrowserFilterTest.java
- server/test/repository/ResetPostgres.java
[Play 2.9 -> 3.x Migration Guide](https://www.playframework.com/documentation/3.0.x/Migration30)
[Play Scala 3 Migration](https://www.playframework.com/documentation/3.0.x/Scala3Migration)
The primary change in Play 3 is that switch from Akka to the Apache fork named Pekko. 
There are some environment variables that have `Akka` in their name. It would be nice to rename them, but then we're having to verify all deployment config files are changed. There is no real downside in keeping the environment variables named as they are.
Prior version of the Prometheus library only had `applicant_id_in_profile_total`. With the new version there is an additionally generated option named `applicant_id_in_profile_created`. The tests were written assuming only the `applicant_id_in_profile_total` was …
> Play 3 Upgrade

- server/app/views/applicant/ProgramFiltersFragment.html
As requested by UX, we are scrolling to program filter results after the "Filter" button is clicked.
1. If you haven't done this yet, seed the default categories by going to the Dev Tools and click "Seed programs and categories".
2. Enable the program filtering and North Star flags if you haven't already.
3. Log in as an admin and add a few categories to various programs.
4. Publish your changes.
5. Go to the landing page.
6. Select some category filters and click the "Filter" button.
7. Notice that the page scrolls to the top of the "Programs based on your selections" section.  The scroll position on Chrome seems a bit inconsistent, but positioning is consistent on Firefox.  
Fixes #7813
> [North Star] Page scroll to filter results after selecting program filters

- server/app/repository/QuestionRepository.java
- server/app/services/question/QuestionService.java
- server/test/repository/QuestionRepositoryTest.java
- server/test/services/question/QuestionServiceTest.java
Tightens the question admin name validation to prevent colliding question keys.
Question keys are derived from the question admin name by:
1. Stripping all characters that are not letters or spaces
2. Converting spaces to underscores
3. Keys are then only ever used in a path, which also lowercases them.
This means that the admin names `phone number` and `Phone Number1` both get transformed to `phone_number` when using them in a Path, so they point to the same place in the ApplicantData despite being different questions.
Currently, question admin names with colliding key forms are allowed to be created if:
- They have different casing. Eg `Phone Number` and `phone number`. This is because we compared the questionNameKey before converting it to a Path, which lowercases it.
- One is an …
> Stop allowing questions with colliding keys

- browser-test/src/applicant/northstar_application_version_fast_forward.test.ts
- browser-test/src/support/applicant_program_list.ts
- browser-test/src/support/civiform_fixtures.ts
Adding a new fixture class to represent the applicant program list screen, i.e. `/programs`. Since this is being extracted from my fast forward tests, also update those.
This class is northstar only. I'm not going to label it that way as nothing can/will use it that isn't northstar and it'll just end up being another cleanup task.
I'm calling it a `CardGroup`, that is the container of `Card`s. Calling it CardList seemed like it would imply it's a list type element.
> Adding applicant program list class

- .github/workflows/tests.yaml
- .github/workflows/tests_skip.yaml
- browser-test/playwright.config.ts
Removes the disabled Azure job. Makes the AWS job generic. Dynamically builds the strategy matrix used to generate the browser test shards. Normal operation will remain running with localstack/aws. 
If your branch has `azure` in the name if will run 10 shards of the browser tests for AWS and 10 for Azure. This is done as a temporary measure to allow for CI to run Azure tests, but also to not block the rest of development.
All tests will be run now, and certain to fail at first. Once we get all the tests running we can remove the branch naming check and run them all the time.
I will have to re-jigger the requirements in the branch protection rules as the new name of the jobs are different.
I made some adjustments to the Playwright config. It should still only upload traces for failed …
> Re-enable Azure browser tests

- server/app/controllers/admin/AdminImportController.java
- server/app/repository/VersionRepository.java
- server/test/controllers/admin/AdminImportControllerTest.java
There was an issue Arkansas ran into where they had a draft question but no draft programs and received an error. This will ensure they never get into that case.
I also made a change to create a function in the repository class to make the query to check whether there are programs and questions in the draft more efficient. 
Fixes https://github.com/civiform/civiform/issues/9237
> Check for draft questions as well as draft programs

- server/app/views/applicant/ApplicantUpsellTemplate.html
- server/app/views/components/AlertFragment.html
…ion page
pass in appropriate aria role attribute value to AlertFragment 
- [N/A] Extended the README / documentation, if necessary. For user-facing features, consider updating [the user docs](https://github.com/civiform/docs). For "under-the-hood" changes or things more relevant to developers, consider updating [the dev wiki](https://github.com/civiform/civiform/wiki).
- [N/A] Ensured PII wasn't added to any new logs, unless it was guarded by `isDevOrStaging`
no database changes
Read the docs …
> issue-9031 Update aria role as status on success message on confirmation page

- server/app/services/export/CsvExporter.java
- server/app/services/export/JsonExporterService.java
- server/test/services/export/CsvExporterServiceTest.java
- server/test/services/export/JsonExporterServiceTest.java
Handle duplicate questions during export.
Details:
- There should not be questions with colliding keys but due to #9212 there sometimes are.
- If there's colliding keys, drop the first one and keep the second. This should not change the output, as colliding keys point to the same place in the applicant data.
Part of #9212
> Handle duplicate questions during export

- browser-test/src/admin/admin_program_migration.test.ts
- server/app/repository/QuestionRepository.java
- server/app/services/migration/ProgramMigrationService.java
- server/test/controllers/admin/AdminImportControllerTest.java
- server/test/repository/QuestionRepositoryTest.java
- server/test/services/migration/ProgramMigrationServiceTest.java
Use letters instead of numbers to de-dupe imported questions during program migration.
Details:
- Numbers are stripped from question names when generating keys[1], so they end up colliding when exported or used to access ApplicantData.
- Instead, we use "excel column name" style letters to de-duplicate questions with conflicting names.
[1] https://github.com/civiform/civiform/blob/0c57746d98eaba7471d65bd8fe50d792701c2990/server/app/services/question/types/QuestionDefinition.java#L60
- Try importing questions with duplicate names
- Also try importing a program with questions that both need to be deduplicated, to ensure they don't collide with each other. …
> Use letters to de-dupe imported questions

- server/app/services/MessageKey.java
- server/app/views/applicant/ProgramCardsSectionFragment.html
- server/conf/i18n/messages
Adds an aria label to the home page program card "View and apply" button so that each button's text is distinct in that it contains the specific program name.  The screen reader will announce "View and apply to 'program name'".
1. Go to the home page with the North Star flag on.
2. Turn on the screen reader.
3. Tab to the "View and apply" button.
4. The screen reader should announce "View and apply to 'program name'".
Part of #7686
> [North Star] Add aria label to "View and apply" program card button

- server/app/services/MessageKey.java
- server/app/views/applicant/NavigationFragment.html
- server/conf/i18n/messages
remove unnecessary wrapping nav element from guest login alert message and add appropriate Aria attributes.
- [N/A] Extended the README / documentation, if necessary. For user-facing features, consider updating [the user docs](https://github.com/civiform/docs). For "under-the-hood" changes or things more relevant to developers, consider updating [the dev wiki](https://github.com/civiform/civiform/wiki).
N/A
N/A
- [covered by existing tests] Wrote …
> issue-8942 remove unnecessary wrapping nav element from guest login alert

- server/app/controllers/admin/AdminImportController.java
- server/app/views/admin/migration/AdminImportViewPartial.java
This PR includes two bug fixes for Program Migration:
- Wrapping the `try` block just around the call to `renderProgramData` in `hxImportProgram` wasn't catching all server errors. Specifically it misses the error thrown when the default `en-US` translations can't be found. This PR expands the `try` block to wrap all failable calls in `hxImportProgram`. (Made a small docs update related to this as well: https://github.com/civiform/docs/pull/537)
- Large programs are still not able to be saved because we needed to use the large body parser on the save route as well. This PR adds that.
Ping me if you want json to test with.
Fixes #9286
> [Program Migration] Handle all server errors when previewing a program and allow saving large requests

- server/app/services/email/aws/SimpleEmail.java
- server/app/services/monitoring/EmailSendMetrics.java
This doesn't change any functionality, but refactors the metrics to a common class, which will be used by both the AWS SES and Graph API paths
[#9260](https://github.com/civiform/civiform/issues/9260)
> Extract metrics from AWS email sending class, so they could be reused for graph API

- server/app/services/cloud/azure/AzureApplicantStorage.java
- server/app/services/settings/SettingsManifest.java
- server/conf/env-var-docs.json
- server/conf/helper/cloud.conf
- server/test/services/cloud/azure/AzureApplicantStorageTest.java
Enables upload limits for applicant files on Azure.  Set to 100MB (same as AWS)
Fixes #7013
> Enable file upload limit for applicant files on Azure. (100 Mb)

- browser-test/src/support/applicant_questions.ts
Simplify logic in `expectCommonIntakeConfirmationPageNorthStar()`. This change was inadvertently left out of [#9300](https://github.com/civiform/civiform/pull/9300).
> Add createAccountHeading variable

- server/app/views/admin/programs/ProgramImageView.java
After clicking "Save Image" on the program image page, we're getting an error, which is causing our prober tests to fail. 
We recently added this CSRF token as part of getting azure program image to work, so we may need to set it conditionally if we need it there https://github.com/civiform/civiform/pull/9276/files.
We should probably see if there are any AWS tests that are missing that would have caught this.
https://github.com/civiform/civiform/issues/9315
> Fix prober tests

- server/app/services/MessageKey.java
- server/conf/i18n/messages
- server/conf/i18n/messages.am
- server/conf/i18n/messages.ar
- server/conf/i18n/messages.es-US
- server/conf/i18n/messages.fr
- server/conf/i18n/messages.ja
- server/conf/i18n/messages.ko
- server/conf/i18n/messages.lo
- server/conf/i18n/messages.ru
- server/conf/i18n/messages.so
- server/conf/i18n/messages.tl
- server/conf/i18n/messages.vi
- server/conf/i18n/messages.zh-TW
- server/test/views/components/FieldWithLabelTest.java
Remove the old error string that is no longer in use as of [this PR](https://github.com/civiform/civiform/pull/9093/files#diff-af62199d2460d043f58acb60ac16e512637af1cfae9cddd2f2f327a4776798f9).
Related to PR: https://github.com/civiform/civiform/pull/9093
> Remove old error string

- server/conf/routes
This PR adds a route for AdminProgramBlockPredicatesController to update eligibility message. The method [updateEligibilityMessage()](https://github.com/civiform/civiform/blob/30a945e7ebd3859d49e98a69c85e640380821e57/server/app/controllers/admin/AdminProgramBlockPredicatesController.java#L391) is built already.
Part of #9303
> [Eligibility message] adding the route for updating eligibility msg

- server/conf/application.test.conf
Disable the durable jobs from running during unit tests. There's no need to have these running in the background.
> Disable durable jobs module in unit tests

- server/app/services/MessageKey.java
- server/conf/i18n/messages
Add string for the northstar application status tag
Part of #9165
> Add string for application status tag

- server/app/views/CiviFormMarkdown.java
- server/app/views/components/LinkElement.java
- server/test/views/CiviFormMarkdownTest.java
- server/test/views/components/FieldWithLabelTest.java
Ensure we have these ref attributes on any link with target blank_. This is for security purposes.
Fixes https://github.com/civiform/civiform/issues/9406
> Add "noopener noreferrer" if we open a link in a new tab

- browser-test/src/admin/admin_application_statuses_bulkstatus.test.ts
- browser-test/src/admin/admin_predicates_bulkstatus.test.ts
Unskip admin_predicate tests and skip admin_application_status_bulkstatus.test.ts
Fixes #9426
> Unskip admin_predicate tests and skip admin_application_status_bulkstatus.test.ts

- browser-test/playwright.config.ts
When running probers against a deployed staging tests are failing at (seemingly) random sometimes with an error that the disk is full. It may be that playwright's `retain-on-failure` isn't deleting files in a timely manner causing all trace files to pile up filling the disk. Switching back to `on-first-retry` which will only create the traces when a test fails and it retries running that failed test.
Not sure this will fix it, but it's worth a shot, in an attempt to unblock staging prober failures.
> Revert to saving trace on first retry

- server/app/services/openapi/QuestionDefinitionNode.java
- server/test/services/openapi/QuestionDefinitionNodeTest.java
Adding a tree structure for questions in order to simplify building openapi output
Related to https://github.com/civiform/civiform/issues/5358, https://github.com/civiform/civiform/issues/5359
> Adding tree for building openapi output

- server/conf/application.conf
Since x-frame-headers is deprecated, this is the recommended approach for preventing clickjacking https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors. The reason we can't do "none" is because the program application list uses an iframe (https://github.com/civiform/civiform/blob/e441158503b1a965a22a1840e82d36e48edf91f1/server/app/views/admin/programs/ProgramApplicationListView.java#L142)
https://github.com/civiform/civiform/issues/9404
> Set frame ancestors to self for CSP

- server/app/services/openapi/AbstractOpenApiSchemaGenerator.java
- server/app/services/openapi/v2/Swagger2SchemaGenerator.java
- server/test/services/openapi/v2/Swagger2SchemaGeneratorTest.java
Add to allow for easy building of openapi schemas
Related to https://github.com/civiform/civiform/issues/5358, https://github.com/civiform/civiform/issues/5359
> Generate swagger2 without application questions

- server/app/modules/CiviFormLogoutLogic.java
- server/app/modules/SecurityModule.java
This is a no-op that just extends the default logic in a new class. See [TDD](https://docs.google.com/document/d/1edlqzDQUY0Df7alpuArt6FJYF_eLOm5jd7CaE1aZkHQ/edit?tab=t.0#heading=h.2xvuqlh0orl) for details. Next step is to add a step to clear the session.
https://github.com/civiform/civiform/issues/6975
> Create a logout class that extends the default logout

- browser-test/src/applicant/navigation/northstar_application_navigation_buttons.test.ts
- browser-test/src/support/applicant_questions.ts
- server/app/views/applicant/ModalFragment.html
- server/app/views/applicant/NorthStarApplicantProgramBlockEditView.java
Conditionally set navigation and display text on the error modal dialog to either previous block or review page based on whether user click on "back" or "review and exit" button the the page.
N/A
N/A
N/A
create a program with multiple steps, one of which contains required questions. Alternatively,  you can import the attached test program json.
start application, go the step which contains required questions, 
click on Back,  you should see the …
> Issue 9381 fix navigation on the error modal  for incomplete application step

- server/app/controllers/applicant/ApplicantProgramBlocksController.java
- server/app/controllers/applicant/ApplicantProgramReviewController.java
- server/app/views/applicant/IneligibleBlockView.java
This is an update to https://github.com/civiform/civiform/pull/9421/files to pass the blockDefinition through to the function to allow just the function that throws the exception to be wrapped in the try / catch. Seems more readable and also allows us to cut down on some code. 
> Pass block definition through to rendering ineligible block view

- server/app/filters/ValidAccountFilter.java
- server/app/modules/CiviFormLogoutLogic.java
- server/app/modules/SecurityModule.java
These are the final changes needed to fix the session replay issue (behind feature flag).
Remove the active session from the database on logout which follows [this section](https://docs.google.com/document/d/1edlqzDQUY0Df7alpuArt6FJYF_eLOm5jd7CaE1aZkHQ/edit?tab=t.0#heading=h.2xvuqlh0orl) of TDD. 
Check each request against valid session ID ([this section](https://docs.google.com/document/d/1edlqzDQUY0Df7alpuArt6FJYF_eLOm5jd7CaE1aZkHQ/edit?tab=t.0#heading=h.pompz7j8zql0) of TDD) - this will what we do to ensure the user has a valid session (behind a flag)
Turn on `session_replay_protection_enabled = true` and run pgadmin locally (bin/dev-pgadmin) while …
> Remove the session from the database on logout and check request against session ID behind a feature flag

- server/app/views/applicant/ApplicantProgramFileUploadBlockEditTemplate.html
- server/app/views/applicant/NorthStarApplicantProgramBlockEditView.java
- server/app/views/fileupload/FileUploadViewStrategy.java
Enables applicant multi-fiile uploads for Azure deployments with Northstar enabled.
- Adds the script tag to load the azure javascript library to file upload views.
This is not the final PR for this feature, outstanding items:
- #9444 File names for uploaded files are not properly displayed on azure deployments (UID shown instead)
Fixes #8108
> Enable multi-file upload for Azure deployments using Northstar

- server/app/auth/oidc/CiviformOidcProfileCreator.java
- server/app/repository/AccountRepository.java
- server/test/repository/AccountRepositoryTest.java
There seems to be an case with the session replay enabled flag where someone won't have a session created if they log in, log out and log back in. This causes an exception to be thrown [here](https://github.com/civiform/civiform/blob/343a7d9055ba9398a54f3b20e1c20e9d2b8a37f3/server/app/models/AccountModel.java#L210). I can't reproduce it locally, but we should create a session if it doesn't exist and log a warning, so we can better debug this case.
https://github.com/civiform/civiform/issues/6975
> Create a session if it doesn't exist and log these cases

- browser-test/src/admin/admin_application_download.test.ts
- browser-test/src/admin/admin_application_statuses.test.ts
- browser-test/src/admin/admin_bulk_update_statuses.test.ts
- browser-test/src/admin/admin_predicates.test.ts
- browser-test/src/applicant/applicant_application_index.test.ts
- browser-test/src/applicant/applicant_application_statuses.test.ts
- browser-test/src/applicant/application_download.test.ts
- browser-test/src/applicant/application_previous_version.test.ts
- browser-test/src/applicant/application_review.test.ts
- browser-test/src/applicant/northstar_applicant_application_statuses.test.ts
- browser-test/src/applicant/northstar_application_previous_version.test.ts
- browser-test/src/support/admin_programs.ts
Removing Application Card related functions from Browser tests and removing "ForBulkStatus" from common function names. 
Fixes #9499
> Removing Application Card related functions from Browser tests

- server/app/auth/ProfileFactory.java
We were previously just adding the active session to a civiform admin, which was making it so the other roles didn't work properly. Added the same handling for other roles 
Check fake roles work as intended
https://github.com/civiform/civiform/issues/6975
> Add active session to other fake roles

- browser-test/src/support/index.ts
Passing through optional mask settings for screenshots
> Pass through mask options

- browser-test/src/admin/admin_program_list.test.ts
- server/app/repository/ProgramRepository.java
- server/app/repository/VersionRepository.java
- server/app/services/program/ProgramService.java
- server/app/views/admin/programs/ProgramIndexView.java
- server/test/repository/VersionRepositoryTest.java
- server/test/services/program/ProgramServiceTest.java
- server/test/support/ProgramBuilder.java
- server/test/support/ResourceCreator.java
Hide the "In Use"/"Disabled" tabs from the Admin program list view when there are no disabled programs.
- Open program admin page
- Ensure that there are no existing programs
- Add a program that is not disabled.
- Make sure that "In Use/Disabled" tabs is not visible. 
- Add a new programs that is disabled.
- Verify that on Admin program list page, the "In Use/Disabled" tabs are now visible.
- Click on "Disabled" tab link to verify that the disabled program is listed.
- Click on "In Use" tab link to verify that the in-use program(non-disabled) is listed.
Fixes #9380
> Hide tabs when there are no disabled programs

- server/app/views/BaseHtmlView.java
- server/app/views/admin/programs/ProgramApplicationListView.java
- server/app/views/admin/programs/ProgramApplicationView.java
- server/app/views/admin/programs/ProgramImageView.java
- server/app/views/admin/programs/ProgramIndexView.java
- server/app/views/admin/programs/ProgramPredicatesEditView.java
- server/app/views/admin/programs/ProgramStatusesView.java
- server/app/views/admin/questions/QuestionsListView.java
- server/app/views/admin/settings/AdminSettingsIndexView.java
- server/app/views/admin/ti/EditTrustedIntermediaryGroupView.java
- server/app/views/admin/ti/TrustedIntermediaryGroupListView.java
- server/app/views/applicant/TrustedIntermediaryAccountSettingsView.java
- server/app/views/applicant/TrustedIntermediaryClientListView.java
This refactor removes duplicate code to setup toast messages in View classes by adding static helper methods in BaseHtmlView. 
This is a pure refactor and a basic manual testing of toast messages on all screens would suffice.
Fixes #6593
> Use add toast message helper methods in views

- browser-test/src/applicant/questions/file.test.ts
Multi file upload tests do not work on Azure if Northstar is disabled.
Disable the tests in file.test.ts until Northstar is the only test suite.
> Skip test suite file.test.ts on Azure

- .github/renovate.json5
Tailwind v4 is now out. This will prevent renovate from upgrading Tailwind past v3.x.
> Block renovate from update to tailwind v4

- server/app/controllers/applicant/ApplicantProgramBlocksController.java
- server/app/services/applicant/ReadOnlyApplicantProgramService.java
- server/app/services/applicant/question/FileUploadQuestion.java
- server/app/services/question/QuestionAnswerer.java
- server/app/views/applicant/ApplicantProgramFileUploadBlockEditTemplate.html
- server/test/controllers/applicant/ApplicantProgramBlocksControllerTest.java
- server/test/services/applicant/ReadOnlyApplicantProgramServiceTest.java
- server/test/services/applicant/question/FileUploadQuestionTest.java
This reverts commit 523ada102b5846fde838dba68cc39df18c0ae4a8.
Remove this section if the title of the pull request can be used as the default release notes description. If more detail is needed to communicate to partners the scope of the PR's changes, use this release notes section (and remove this placeholder text).
Fixes …
> Revert "Fix AWS Multifile Upload Bug (#9629)"

- browser-test/src/applicant/northstar_upsell.test.ts
- server/app/views/applicant/ApplicantUpsellCreateAccountView.java
- server/app/views/applicant/ApplicantUpsellTemplate.html
- server/app/views/applicant/NorthStarApplicantUpsellView.java
Only show program cards in the `ApplicantUpsell` page after submission of a program when the SUGGEST_PROGRAMS_ON_CONFIRMATION_PAGE feature is enabled for North Star.
Previously, we would only check for SUGGEST_PROGRAMS_ON_CONFIRMATION_PAGE when not using North Star.
- [n/a] Extended the README / documentation, if necessary. For user-facing features, consider updating [the user docs](https://github.com/civiform/docs). For "under-the-hood" changes or things more relevant to developers, consider updating [the dev wiki](https://github.com/civiform/civiform/wiki).
- [n/a] Ensured PII wasn't added to any new logs, unless it was guarded by `isDevOrStaging`
- [n/a] Followed steps to [internationalize](https://github.com/civiform/civiform/wiki/Internationalization-%28i18n%29#application-strings) …
> [North Star] Show program cards iff feature is enabled

- server/app/actions/ProgramDisabledAction.java
- server/test/actions/ProgramDisabledActionTest.java
Handle draft only program in program disabled action. Found that the program disabled tests were not clearing the database between each test leading to a false positive when there was only a draft version of the program. This only looks to have been an issue if an admin create a draft program and tried to previous it.
Handle draft only program in program disabled action.
> Handle draft only program in program disabled action

- server/conf/application.dev.conf
- server/test/controllers/applicant/ApplicantProgramReviewControllerTest.java
- server/test/controllers/applicant/ApplicantProgramsControllerTest.java
Enabled application fast forward feature in dev/test. Fixed a couple tests where needed.
Related #8047
> Set Fastforward flag as default in dev/test

- server/app/services/PhoneValidationUtils.java
- server/test/services/PhoneValidationUtilsTest.java
Adds phone validation to support for [E164 format numbers](https://www.twilio.com/docs/glossary/what-e164) ([E164 Spec](https://www.itu.int/rec/t-rec-e.164/en)).
Related to: #5461
> Adding phone validation for non-user interactive code with E.164 support

- server/build.sbt
Ignore SettingsManifest in code coverage since it's automatically generated we don't need to care about it.
> Ignore SettingsManifest in code coverage

- server/app/auth/oidc/StandardClaimsAttributeNames.java
- server/app/auth/oidc/applicant/ApplicantProfileCreator.java
- server/app/auth/oidc/applicant/GenericOidcClientProvider.java
- server/app/auth/oidc/applicant/IdcsApplicantProfileCreator.java
- server/app/auth/oidc/applicant/IdcsClientProvider.java
- server/app/auth/oidc/applicant/LoginGovClientProvider.java
- server/app/services/settings/SettingsManifest.java
- server/conf/env-var-docs.json
- server/conf/helper/auth.conf
- server/test/auth/ProfileMergeTest.java
- server/test/auth/oidc/CiviformOidcProfileCreatorTest.java
- test-support/test_oidc_provider.js
Populate phone number from the OIDC server if configured with the `phone` claim.
I'll update the docs in a later PR along with the release notes on how this gets enabled via the phone claim.
Fixes #5461
> Import OIDC phone number

- server/app/services/email/graph/GraphApiEmailClient.java
- server/app/services/settings/SettingsManifest.java
- server/conf/env-var-docs.json
- server/conf/helper/email.conf
- server/test/services/email/graph/GraphApiEmailClientTest.java
Using `.me()` throws an error `com.microsoft.graph.models.odataerrors.ODataError: /me request is only valid with delegated authentication flow.`. We don't have access to email sending yet in our account, but after changing this to the user email that owns our azure account, we see a message: `2025-02-11T20:05:08.3462368Z com.microsoft.graph.models.odataerrors.ODataError: The mailbox is either inactive, soft-deleted, or is hosted on-premise.`
https://github.com/civiform/civiform/issues/9260
> Add ability to set account for graph api email sending

- server/app/controllers/dev/seeding/DevDatabaseSeedTask.java
- server/app/services/seeding/DatabaseSeedTask.java
Change dev and prod database seed tasks to use `TxScope.required()` instead of `TxScope.requiresNew()`.
This way, any changes are part of an outer transaction rather than in their own, separate, concurrent transaction.
Part of #9643
> Use required() instead of requiresNew() when creating transaction in database seed tasks

- browser-test/src/applicant/applicant_application_index.test.ts
- browser-test/src/applicant/navigation/northstar_application_navigation_buttons.test.ts
- browser-test/src/applicant/navigation/northstar_application_navigation_common_intake.test.ts
- browser-test/src/applicant/navigation/northstar_application_navigation_with_eligibility_conditions.test.ts
- browser-test/src/applicant/northstar_applicant_question_translation.test.ts
- browser-test/src/applicant/northstar_common_intake_upsell.test.ts
- browser-test/src/applicant/northstar_program_summary.test.ts
- browser-test/src/northstar_trusted_intermediary.test.ts
- browser-test/src/support/applicant_questions.ts
- server/app/views/applicant/ProgramCardsSectionParamsFactory.java
- server/test/views/applicant/ProgramCardsSectionParamsFactoryTest.java
When applicants are applying to a common intake program, we want to skip the program overview page and go right into editing the application.
As an admin:
1. Create a common intake program and a regular program
As an applicant:
1. Click to apply to the common intake program -- should be taken directly into the application
2. Click to apply to the other program -- should be taken to the program overview page
3. Try out other scenarios like partially filling out the application (should be taken to where you left off) and submitting the application (should be taken to the review page)
As a TI:
1. Create a client and apply on behalf of them
2. Test out all the same steps as you did for the applicant above
3. The behavior should match that for the applicant and you should consistently see a …
> [North Star] Skip program overview page when applying to common intake program

- server/app/repository/QuestionRepository.java
- server/app/repository/VersionRepository.java
Remove remaining uses of `TxScope.requiresNew()` and replace them with `TxScope.required()`,  which is actually the behavior we want.
More details in #9643, but `.requiresNew()` is almost never the transaction isolation level we want, as it results in a separate, concurrent transaction whose changes are not visible to the outer transaction, rather than a nested "inner" transaction as one might expect.
Additionally, I verified all codepaths that call into these changes, and nothing expects the unusual behavior of `requiresNew()`.
- [n/a] Performed manual testing (Chrome …
> Remove remaining uses of `TxScope.requiresNew()`

- .github/workflows/tests.yaml
- server/app/repository/TransactionManager.java
- server/app/services/question/QuestionService.java
- server/test/repository/TransactionManagerTest.java
- server/test/services/question/QuestionServiceTest.java
Create a `TransactionManager` helper class and use it to wrap question creation flow in a transaction.
Note: I haven't tested that this works correctly with async flows. It probably doesn't because transactions are tracked on thread-local storage, and some repository methods use the DatabaseExecutionContext while other application code uses the ClassLoaderExecutionContext, and I don't know if the context is propagated between thread pools.
Part of #9509
> Create TransactionManager helper class and wrap question creation

- browser-test/src/applicant/applicant_application_index.test.ts
- browser-test/src/support/applicant_program_list.ts
- browser-test/src/support/applicant_questions.ts
An `applicant_application_index.test.ts` test was failing on probers. In different environments, Playwright was having trouble locating the Recommended and Other Programs `<section>` elements, possibly because they're rendered with HTMX.  The solution of using `first()` and `last()` was the only locator combination that worked in both the local/PR environment and in probers.
I added two helper functions to `applicant_program_list.ts` because these were working for probers, but I didn't end up using them because they didn't work locally and in the PR actions.  Leaving them in the PR because I think they could be useful in the future.
Part of #9767
> Getting a North Star test to pass on probers

- bin/lib/docker.sh
- bin/run-dev
- docker-compose.keycloak.yml
- init_postgres.sql
- server/app/auth/AuthIdentityProviderName.java
- server/app/auth/oidc/admin/KeycloakAdminClientProvider.java
- server/app/auth/oidc/applicant/KeycloakApplicantClientProvider.java
- server/app/modules/SecurityModule.java
- server/conf/application.dev.conf
- server/conf/helper/auth.conf
- test-support/keycloak/auth/import/README.md
- test-support/keycloak/auth/import/admin.realm.json
- test-support/keycloak/auth/import/applicant.realm.json
> [!NOTE]
> All keys/secrets/passwords are for local development environments and are safe to store.
Uses [keycloak](https://www.keycloak.org/) as a local OIDC server for both applicant and admin. Each have completely separate realms.
**The dev-oidc server we currently use is still here and is the default.** That is unlikely to change anytime soon.
One time setup step, but if you already have CiviForm running this should already be done. Must edit `/etc/hosts` and add
```
127.0.0.1 dev-oidc
```
Then run `bin/run-dev --keycloak`. Everything should just work.
Item | Value
-|-
Master realm URI | http://dev-oidc:3390
username | admin
password | password
Item | Value
-|-
Realm Name | admin-realm
Discovery URI | http://dev-oidc:3390/realms/admin-realm/.well-known/openid-configuration
Client ID …
> Working applicant and admin OIDC for dev env with Keycloak

- browser-test/src/northstar_meta_tags.test.ts
This test was checking for an explicit value of `dev`. Changing to just verify the meta tag exists and has a value so it works in dev and against deployed instances.
> Check that tag exists and has a value

- server/app/views/components/AlertFragment.html
Move duplicate variable evaluations into th:with for readability and less errorprone
> Cleanup - AlertFragment

- browser-test/src/applicant/northstar_applicant_application_statuses.test.ts
We can't assume the NS flag is on by default because it isn't yet the default in all testing environments.  This enables the flag before each test and passes `northstarEnabled=true` as a parameter on functions where needed.
Part of #9767
> Enabling North Star flag before application statuses test

- browser-test/bin/wait_for_server_start_and_run_tests.sh
- browser-test/src/applicant/applicant_application_index.test.ts
- browser-test/src/applicant/northstar_upsell.test.ts
Fixing North Star upsell test on probers.  It was using a hard-coded test user name.  Also fixing another in `applicant_application_index.test.ts`, which needed to call `normalizeElements` for the date.
Also, updating `bin/wait_for_server_start_and_run_tests.sh` so that it'll take those additional args rather than hard-coding them.
Part of #9767
> Fixing North Star upsell test on probers

- server/app/services/settings/SettingsManifest.java
- server/conf/application.conf
- server/conf/application.dev.conf
- server/conf/env-var-docs.json
Introduce configurations for browser session timeouts and warning threshold. This is part 1 of browser session timeout work. The feature is by default turned off by default. Since the feature can be configured as on or off, I have not created an explicit feature flag. All subsequent changes will be guarded on the feature being on or off effectively serving as a feature flag.
Login as admin and ensure that all the new server settings appears in the intended sections.
Fixes #9820
> [SessionTimeout][part1]Introduce the session timeout configurations and feature flag

- server/app/views/applicant/ProgramCardsSectionParamsFactory.java
This fixes a Northstar bug on the applicant program cards I came across by chance.
The adminName property was being use to build the url on the cards instead of the slug. In the past the adminName was pulled from the `programs.name` column, but was later changed to use the `programs.localized_name`. When creating new programs these days the adminName and the slug are the same thing, but programs created prior to this point might not be different. This causes the older programs to build a URL that doesn't work. Changing this to the slug as that is the correct value to be used in the URL.
Note, that even if the Civiform admin were to edit the program and change the program name it doesn't update the value in the `programs.name` column so it's not fixable from within the application. We …
> Use correct value for program slug

- server/app/controllers/monitoring/MetricsController.java
Adds better error handling and a retry when trying to collect server metrics for Prometheus.
> This exception can often be reproduced if you start running the full browser test suite and then spam calling `/metrics` until it sometimes will throw.
> 
> Basically this state can happen when calling `database.metaInfo().collectMetrics()` method and the metrics are either being updated or a lock can't be immediately gotten.
> 
> I'm trying to avoid using synchronize to force a lock on the database object as I'm concerned about adversely affecting performance.
> 
> Since the `/metrics` endpoint is called very frequently any data from a failed call gets rolled into the next successful call to `/metrics`. …
> Handle ConcurrentModificationException in MetricsController

- .github/ISSUE_TEMPLATE/oncall-rotation.md
Updated our on-call issue to reflect our new policy of publishing a release on Tuesdays or Wednesdays.
Based on discussion in our eng weekly meeting on 3/3/25. [See notes](https://docs.google.com/spreadsheets/d/1jXuOWl9TxssHh3A1AkmKi2gva9LRUhE0PQStJa-4yWs/edit?gid=1246619714#gid=1246619714)
Corresponding external docs update [here](https://github.com/civiform/docs/pull/550)
Corresponding internal wiki update [here](https://github.com/civiform/civiform/wiki/Releasing/_compare/10902d3af4b4927cd8555958d222d4c1316edf74)
> Update oncall issue to specify publishing release by Weds

- prod.Dockerfile
- server/build.sbt
Due to the pipeline order of `sbt update` and `sbt dist` the prod image wasn't including the swagger ui web assets. The webpack step happens long after the internal asset jar bundling. This adds a custom sbt task that is called before we do other sbt commands to build the application for the prod image. This only needs to happen for the prod image and not other times sbt update happens which is why I'm not making `update` depend on the new task.
Related: #4946
> Getting the swagger ui assets loading in deployed environments

- server/build.sbt
- server/conf/logback.xml
Adds the following:
- Dependency on logstash-logback-encoder library in build.sbt
- Defines a new appender in logback configuration for JSON console output
- Optionally use the value of the environment variable LOGBACK_CONSOLE_APPENDER to determine which appender to use for console logging in logback.
By default if LOGBACK_CONSOLE_APPENDER  is undefined, it will use the ASYNCSTDOUT appender, which is the way the current logback configuration works.  (this means no changes to existing civiform deployments).
In the GCP deployments, LOGBACK_CONSOLE_APPENDER will be set to ASYNCJSON
Tested by running the dev server with LOGBACK_CONSOLE_APPENDER  set and unset.  The proper appenders were loaded and the server ran normally. …
> Add structured JSON logging support for Google Cloud logging integration

- server/app/views/docs/SchemaView.java
Disable the online OpenApi validator badge. The generator OpenApi yaml files are not accessible outside of the application so claims to be invalid. This wasn't noticeable on localhost as you can reach the validator website. Setting validatorUrl to null disables the check and the badge [per the docs](https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration).
> Disable OpenApi Validator Badge

- server/app/repository/ProgramRepository.java
- server/app/services/program/ProgramService.java
- server/test/repository/ProgramRepositoryTest.java
- server/test/services/program/ProgramServiceTest.java
Looks up just the slug from the DB, using the cache if able.
This will support another in-flight PR
Remove this section if the title of the pull request can be used as the default release notes description. If more detail is needed to communicate to partners the scope of the PR's changes, use this release notes section (and remove this placeholder text).
Fixes …
> Adds efficient ProgramRepository::GetSlug() method

- browser-test/src/applicant/northstar_footer.test.ts
- server/app/views/NorthStarBaseView.java
- server/app/views/applicant/NavigationFragment.html
Use support email instead of a hardcoded email in the North Star footer
1. As an Admin, go to settings and add a support email
2. As an Applicant, verify that new support email is used in the footer
Fixes #9934
> [North Star] Use support email in footer

- browser-test/src/footer.test.ts
- server/app/services/settings/SettingsManifest.java
- server/app/views/applicant/ApplicantLayout.java
- server/app/views/dev/DebugContent.java
- server/conf/env-var-docs.json
- server/conf/helper/feature-flags.conf
Removes the option to show the CiviForm release number on the applicant home page. 
If you have `SHOW_CIVIFORM_IMAGE_TAG_ON_LANDING_PAGE` set in your deployment config file please remove it.
Fixes #9939
> Remove show cf image tag on landing page

- server/app/views/applicant/ProgramCardsSectionParamsFactory.java
- server/test/views/applicant/ProgramCardsSectionParamsFactoryTest.java
Program cards used the long description when short description is non existent. However, since we want to encourage admins to add a short description and make this consistent, we are taking out the long description as backup for short description in the program card. This aligns with #9719
Fixes #9798
> [North Star] Use only short description in program cards

- server/app/controllers/admin/AdminExportController.java
- server/app/controllers/admin/AdminImportController.java
- server/app/services/settings/SettingsManifest.java
- server/app/views/admin/programs/ProgramIndexView.java
- server/conf/env-var-docs.json
- server/conf/helper/feature-flags.conf
- server/test/controllers/admin/AdminExportControllerTest.java
- server/test/controllers/admin/AdminImportControllerTest.java
`PROGRAM_MIGRATION_ENABLED` has been enabled by default for three months and is now able to be removed.
Fixes #7088; #6783; #5034; #7087
> [Program Migration] Remove PROGRAM_MIGRATION_ENABLED feature flag

- browser-test/src/applicant/northstar_program_overview.test.ts
- browser-test/src/applicant/questions/northstar_date.test.ts
- browser-test/src/applicant/questions/northstar_file.test.ts
- browser-test/src/applicant/questions/northstar_name.test.ts
- server/app/views/ViewUtils.java
- server/app/views/questiontypes/AddressQuestionFragment.html
- server/app/views/questiontypes/DateQuestionFragment.html
- server/app/views/questiontypes/FileUploadQuestionFragment.html
- server/app/views/questiontypes/NameQuestionFragment.html
- server/test/views/components/TextFormatterTest.java
A few question types in North Star do not have an aria-required label set when the question is required. Adding the label so that the screen reader will recognize when the question is required.
Also hiding the required (*) from screen readers so that it does not get read as "star". The label will not have a required indication when read by a screen reader, but the input itself will. This change impacts both North Star and legacy UIs.
Go to a program with required questions, and use a screen reader to read the elements on the page aloud. It would be best to test multiple types of questions. The screen reader should not read the asterisks aloud, but inputs …
> Update screen reader behavior for required fields

- pdf-to-civiform/LLM_prompts.py
To improve accuracy coverage made a few changes to the prompt.
A few examples:
Improved help text parsing. ex text parsed with added change: 
condominium-special-assessments-program-application
```
{
"title": "Liabilities",
"help_text": "(For ALL Household Members 18 and Over, List Credit Card Debt, and Auto, real Estate and Mortgage Loans, etc.)",
....
```
New file upload section when needed
```
{
"title": "Attachments",
"help_text": "Upload any supporting documents here.",
"fields": [
{"label": "Supporting Documents","type": "file_upload","help_text": "Upload proof of income, social security cards, lease agreements, utility bills, and other relevant documents.","id": "form_attachments"}
]
}
]
```
Identifying number type correctly:
```
{"label": "Policy Number:","type": …
```
> Prompt tuning

- server/app/controllers/admin/AdminProgramTranslationsController.java
Increase allowed payload size when saving program translations.
Fixes #9992
> Increase allowed payload size when saving program translations

- .github/renovate.json5
Configure renovate to pin github actions to commit hashes instead of version tags.
This will do two things when renovate runs next.
1) Renovate will create a single PR that will update all tags to hashes for existing code. So we don't need to manually go change everything.
2) Renovate will continue to create PRs when github action versions change. 
Renovate will include the tag version as a comment so it's easier to determine what the version is.
Fixes #10016
> Configure Pinning GitHub Actions to Commit Hashes

- .github/renovate.json5
I can't think of a reason not to pin docker tags as well.
Example of before/after
> Update renovate to pin docker images to sha hashes

- test-support/unit-test-docker-compose.yml
This should have always been using the local tag the same way the rest of our images are used in compose files. Without this change we'll be constantly bombarded with renovate PRs to update the sha.
> Set the unit tests compose to use the local oidc image

- browser-test/src/applicant/northstar_applicant_application_index.test.ts
- server/app/services/MessageKey.java
- server/app/views/applicant/AddressCorrectionBlockTemplate.html
- server/app/views/applicant/ApplicantBaseFragment.html
- server/app/views/applicant/ApplicantCommonIntakeUpsellTemplate.html
- server/app/views/applicant/ApplicantProgramBlockEditTemplate.html
- server/app/views/applicant/ApplicantProgramFileUploadBlockEditTemplate.html
- server/app/views/applicant/ApplicantProgramSummaryTemplate.html
- server/app/views/applicant/ApplicantUpsellTemplate.html
- server/app/views/applicant/IneligibleTemplate.html
- server/app/views/applicant/ProgramIndexTemplate.html
- server/app/views/applicant/ProgramOverviewTemplate.html
- server/conf/i18n/messages
Adding a skip link so that keyboard and screen reader users can skip to main content.  The link is the first focusable element on the page and is visible on keyboard focus only.  Once the user has clicked the link, clicking "Tab" will go to the first focusable element in the main content, rather than back up to the top of the page.
The skip link needs to be present on every applicant-facing page of the North Star.
1. Turn the North Star flag on. 
2. From any applicant-facing page, press "Tab".
3. The "Skip to main content" link should become visible and should have focus.
4. Press "Enter".
5. Press "Tab".
6. Focus should be on the first interactive element of the main content of the page.
7. Refresh the page.
8. Turn the screen reader on.
9. Focus should go straight to the "Skip to main …
> [North Star] Adding a link to skip to main content of the page

- server/app/services/settings/SettingsManifest.java
- server/conf/env-var-docs.json
- server/conf/helper/feature-flags.conf
Add feature flag that to gate the External Program Cards feature, which will allow admins to add external program which will be shown to the applicants on North Star UI.
Part of #10062
> [External Program Cards] Add feature flag

- server/app/views/components/Icons.java
Adding extra svg attrs for two icons to this method. They got misplaced with the perf optimization to the question bank from last week. Cleaning up the duplicate switches. 
> Fix two broken icons

- server/app/assets/javascripts/admin_entry_point.ts
- server/app/assets/javascripts/applicant_entry_point.ts
- server/app/assets/javascripts/modal.ts
- server/app/assets/javascripts/session.test.ts
- server/app/assets/javascripts/session.ts
Frontend code to read the session_timeout_data cookie and display warning message in a modal dialog or logout user if the session has timed out due to inactivity or total session length above a threshold. The session cookie is only set when session timeout feature is enabled and therefore the SessionTimeoutHandler initialization is not under feature flag. Browser tests are coming in the next PR.
- Configure the session timeouts in server configuration file(in applicantion.conf). To test session inactivity warning dialog, set the session_inactivity_timeout_minutes to 2 minutes and session_inactivity_warning_threshold_minutes to 1 minute. Set …
> [SessionTimeout][part6]Display session timeout warning and enforcement in frontend JS

- browser-test/src/applicant/application_address_correction.test.ts
- browser-test/src/applicant/questions/file.test.ts
- browser-test/src/applicant/questions/northstar_file.test.ts
Reorders things in address correction test to remove unnecessary creation of questions and programs. Beforeeach code was creating everything all the tests needed all the time. 
Removes seeding of questions in file upload tests since the questions aren't used.
This is to help reduce test run duration. 
> Browser test performance improvements

- browser-test/src/admin/admin_settings.test.ts
We were getting an error:
Expected substring: "Settings updated"
Received string:    "No changes to save"
This is because we staging has this flag defaulted to one value and local has it defaulted to another. https://github.com/civiform/civiform/pull/9956 is the PR that updated the flag we use in this test
Changing the feature flag value before the test to ensure it is always consistent
> Fix test for staging run

- browser-test/src/applicant/northstar_ineligible.test.ts
- server/app/views/applicant/NorthStarApplicantIneligibleView.java
In the hyperlink on the ineligible page in North Star UI, link to the program overview page instead of the external program URL.
As an admin, create a program with a gating eligibility condition. As an applicant, apply to the program with an answer that does not meet the eligibility criteria. On the ineligible page, "program details" should link to the program overview page, whether or not an external program URL was set by the admin.
Fixes #10117
> Link to program overview page from eligibility message

- browser-test/src/admin/admin_program_translation.test.ts
- browser-test/src/applicant/northstar_applicant_application_index.test.ts
- browser-test/src/applicant/northstar_applicant_question_translation.test.ts
- browser-test/src/support/index.ts
- server/app/assets/stylesheets/northstar/_uswds-theme-custom-styles.scss
- server/app/views/applicant/NavigationFragment.html
Updates the language selector to use the same styling as the USWDS language selector.
Had to do some custom styling because the USWDS component expects the dropdown to have anchor tags and we need to use buttons.
NOTE: found an accessibility bug on mobile view but it's unrelated to a pr - if you are testing on an actual device, it won't tab into the menu
Fixes #9918;
> [North Star] use uswds styling in language selector

- server/app/views/applicant/ProgramCardsSectionFragment.html
Removing the aria-label will result in the screen reader reading the same text as what is on the button, vs. now the two are mismatched.
Fixes #9909
> Remove aria-label from prescreener card buttons

- server/app/views/applicant/ApplicantBaseFragment.html
Adds `aria-hidden=true` to the "Required fields are marked with an asterisk" explanation.
Turn on voiceover on your computer or your phone. Navigate through the page using Browse mode (Ctrl+Alt+Arrow keys). Confirm that the "Required fields are marked with an asterisk" text is skipped.
Fixes #10116
> [North Star a11y] remove voiceover for required fields text

- server/app/assets/stylesheets/northstar/_uswds-theme-custom-styles.scss
- server/app/views/applicant/NavigationFragment.html
On iOS voiceover, the menu options are being skipped. I _think_ this is due to some unneeded formatting that I removed in this pr.
Before: 
https://github.com/user-attachments/assets/fc74c50f-b0da-4e22-bd28-c77954a54221
After:
https://github.com/user-attachments/assets/94f920f2-4665-44d7-91ef-e91408e26790
> [A11y] Fix navigation menu voiceover in mobile view

- browser-test/src/admin/admin_program_email_notifications.test.ts
- browser-test/src/applicant/application_version_fast_forward.test.ts
- browser-test/src/applicant/northstar_application_version_fast_forward.test.ts
- browser-test/src/applicant/northstar_ineligible.test.ts
- server/app/services/applicant/ReadOnlyApplicantProgramService.java
- server/app/services/question/QuestionService.java
- server/app/views/admin/programs/ProgramAdministratorProgramListView.java
- server/app/views/admin/programs/ProgramApplicationListView.java
- server/app/views/admin/programs/ProgramApplicationTableView.java
- server/app/views/applicant/ApplicantProgramSummaryView.java
- server/app/views/applicant/TrustedIntermediaryClientListView.java
- server/app/views/components/TextFormatter.java
The = is necessary to trigger the param name mismatch linter
> Add missing = in inline param comments

- server/app/services/MessageKey.java
- server/app/views/applicant/ProgramCardsSectionFragment.html
- server/conf/i18n/messages
Adds a group around all the category tags in the program cards. Does this by
1. adding `role="group"` to the div
2. adding `aria-label="Categories"` to the div to be read out by the screen reader
Fixes #10120;
> [a11y] add a categories group label to the category tags on a program card

- server/test/repository/TransactionManagerTest.java
Replaces an artificially created SerializableConflictException by forcing a race-condition that will cause the database to generate it.
This helps reinforce that the Transaction semantics work as we actually believe they do rather than as we mock/fake tests.
> Update Transaction test to generate a real exception

- server/app/views/questiontypes/AddressQuestionFragment.html
- server/app/views/questiontypes/CheckboxQuestionFragment.html
- server/app/views/questiontypes/CurrencyQuestionFragment.html
- server/app/views/questiontypes/DateQuestionFragment.html
- server/app/views/questiontypes/DropdownQuestionFragment.html
- server/app/views/questiontypes/EmailQuestionFragment.html
- server/app/views/questiontypes/EnumeratorQuestionFragment.html
- server/app/views/questiontypes/FileUploadQuestionFragment.html
- server/app/views/questiontypes/IdQuestionFragment.html
- server/app/views/questiontypes/NameQuestionFragment.html
- server/app/views/questiontypes/NumberQuestionFragment.html
- server/app/views/questiontypes/PhoneQuestionFragment.html
- server/app/views/questiontypes/QuestionBaseFragment.html
- server/app/views/questiontypes/RadioButtonQuestionFragment.html
- server/app/views/questiontypes/TextQuestionFragment.html
This PR attaches error text to questions in the application form with `aria-describedBy` so that when there are validation errors, the screen reader will read the error text.  For example, it will say "What is your phone number?  Error:  this question is required."  Hearing the error text helps users know what they did wrong.
The question description (help text) is still read before the error description so that users have even more information to complete the question.
Radio, checkbox and enumerator questions are left out of this PR because these have another bug which needs to be fixed first.  (I will create that bug and put a reference to it here).  The bug is that the label and help text aren't being read by the screen reader when there are errors. There is also another bug with group …
> Attach error descriptions to form question inputs for screen readers

- browser-test/.eslintrc.json
- browser-test/src/admin/admin_program_creation.test.ts
- browser-test/src/admin/admin_program_migration.test.ts
- browser-test/src/admin/admin_question_translation.test.ts
- browser-test/src/applicant/northstar_applicant_application_index.test.ts
- browser-test/src/applicant/questions/number_input.test.ts
- browser-test/src/question_lifecycle.test.ts
- browser-test/src/support/admin_program_statuses.ts
- browser-test/src/support/admin_programs.ts
- browser-test/src/support/admin_questions.ts
- browser-test/src/support/admin_settings.ts
- browser-test/src/support/admin_translations.ts
- browser-test/src/support/ti_dashboard.ts
- browser-test/src/trusted_intermediary.test.ts
Updating old asserts that don't follow the web first assertion playwright recommendation. Enabled the check in eslint.
> Cleaning up web first assertions

- browser-test/src/admin/admin_program_creation.test.ts
- browser-test/src/admin/admin_program_statuses.test.ts
- browser-test/src/support/admin_program_statuses.ts
- browser-test/src/support/admin_questions.ts
- browser-test/src/support/applicant_questions.ts
Migrating `waitForAnyModal` which uses deprecated `ElementHandle<T>` calls for `waitForAnyModalLocator` that uses the modern Playwright `Locator` object.
> Updating calls to waitForAnyModal

- server/app/views/applicant/NavigationFragment.html
The support email has an extra ' at the end which makes it not work, as well this changes the string composition to use ThymeLeaf's built in [href composition](https://www.thymeleaf.org/doc/articles/standardurlsyntax.html)
> Fix extra ' in support email mailto and use ThymeLeaf href syntax

- .github/renovate.json5
The rules added to renovate to pin the GitHub Actions and Docker commit hashes ended up grouping all the detected changes into a single PR. This make it so each gets a separate PR, maintains pining to commit hash, and cleans up the PR title a bit.
Manually tested in a private test repository.
> Prevent grouping docker/github actions in single PRs

- browser-test/src/unsupported_browser.test.ts
- server/app/filters/OptionalProfileRoutes.java
When a browser user agent is detected to be that of Internet Explorer we redirect to the _unsupported browser page_. However it was discovered that this was in a redirect loop and never working. This was discovered in the logs from a demo site.
This will now not try to start a session for the unsupported browser page and let it load as expected.
Fixes #10222
> Fix Infinite Redirect from IE User Agent

- server/app/views/questiontypes/CheckboxQuestionFragment.html
- server/app/views/questiontypes/EnumeratorQuestionFragment.html
- server/app/views/questiontypes/QuestionBaseFragment.html
- server/app/views/questiontypes/RadioButtonQuestionFragment.html
Added an aria labeled by for enumerator, radio, and checkbox question types so that the title and description is read in voiceover when tabbing to the options.
Fixes #10219;
> [North Star a11y] add labeled by for question types

- server/package-lock.json
- server/package.json
Removes the @types/dompurify entry in the package.json file.
This package is deprecated and is only a stub in node.
https://www.npmjs.com/package/@types/dompurify
> Removing obsolete @types/dompurify stub

- server/app/assets/stylesheets/northstar/_uswds-theme-custom-styles.scss
- server/app/views/questiontypes/CheckboxQuestionFragment.html
When the screen reader is on and the user is NOT navigating the checkboxes by using "Tab", but, rather, by using other form navigation controls which vary by screen reader, a navigation outline surrounds the element that the screen reader is currently reading. Note that this outline is not the focus outline. It is a different color and width, depending on the screen reader.
The USWDS checkbox component is a custom component. It shifts the native checkbox outside the viewport and uses its own customized element as the visible checkbox. Since the screen reader navigation outline is based on the native element, it is also outside the viewport and is missing from view.
This PR places the native checkbox input element around the custom one, but sets the opacity to 0 so that it is only visible …
> Making screen reader linear navigation outline visible on checkbox questions

- server/app/services/settings/SettingsManifest.java
- server/conf/env-var-docs.json
- server/conf/helper/feature-flags.conf
Adding feature flag for [giving admins options of how to handle duplicate questions during import](https://docs.google.com/document/d/1-3Xhm7MmH-DREzbwu_yKV9tU3VjcbHKmnq_Ea2qYkGQ/edit?tab=t.0)
This feature flag is tracked in #10293 
Adding a feature flag that guard a new feature to allow admins to select how they want to handle duplicate questions when importing a new program via JSON: create a duplicate question, use the existing question, or overwrite the existing question's configuration.
> Duplicate-Options Feature Flag

- server/app/services/settings/SettingsManifest.java
- server/conf/env-var-docs.json
Make the `IMPORT_DUPLICATE_HANDLING_OPTIONS_ENABLED` feature flag admin writeable for ease of writing browser tests. 
FF tracked in #10293 
> Make IMPORT_DUPLICATE_HANDLING_OPTIONS_ENABLED writeable

- server/app/repository/TransactionManager.java
- server/app/services/question/QuestionService.java
- server/test/repository/TransactionManagerTest.java
- server/test/services/question/QuestionServiceTest.java
`InTransaction` in the method name is redundant with the entire classes purpose and the implementation of all methods. The longer name creates less readable code.
> Rename executeInTransaction() to execute()

- server/app/filters/OptionalProfileRoutes.java
This is an attempt to fix the memory leak issues that were introduced on March 14th here:  https://github.com/civiform/civiform/pull/9973.  We are adding the `/error` path to the list of routes which will be excluded from guest profile creation.
> Add /error path to optional profile routes 

- server/app/views/questiontypes/TextQuestionFragment.html
`aria-invalid` was being added to text questions when there were no errors, before the form was submitted.  This was likely a typo.  Now `aria-invalid` will only be added to the field when there are errors in the form field.
1. As an admin, create a program with a text question.
2. As an applicant, apply to the program.
3. Turn a screen reader on.
4. Go to the empty text field.  
5. You should not hear "required, invalid text".
6. You should only hear "required text".
Fixes #9734
> Add aria-invalid on text questions only when there are errors

- .github/workflows/run_jmeter_test.yaml
Add a param for number of users. Defaults to 10
Tested here: https://github.com/civiform/civiform/actions/runs/14542231643/job/40802248506
Meant to help with debugging https://github.com/civiform/civiform/issues/10330
> Make the number of users configurable in the github action

- load-test/applicant_landing_page.jmx
- load-test/applicant_submit_application.jmx
- load-test/ti_landing_page.jmx
Local testing needs to specify the port which can't be part of the hostname and specify the protocol as http
> Parameterize port and protocol in jmeter configs for local usage

- server/app/controllers/admin/AdminImportController.java
- server/app/controllers/admin/ProgramMigrationWrapper.java
- server/app/services/migration/ProgramMigrationService.java
- server/app/views/admin/migration/AdminProgramImportForm.java
- server/test/controllers/admin/AdminImportControllerTest.java
- server/test/services/migration/ProgramMigrationServiceTest.java
Creates the backend duplicate handling options for the new admin import flow (https://github.com/civiform/civiform/issues/10293 and https://github.com/civiform/civiform/issues/9628). This PR adds the [first two options](https://docs.google.com/document/d/1-3Xhm7MmH-DREzbwu_yKV9tU3VjcbHKmnq_Ea2qYkGQ/edit?tab=t.0) for handling duplicate imported questions. Wiring this to the UI/DB, and the third option will be forthcoming. No users should be currently impacted by this change, as it is predicated on UI components which are not present yet.
> Add backend options for duplicate handling

- server/app/filters/CiviFormProfileFilter.java
- server/test/filters/CiviFormProfileFilterTest.java
This PR prevents creating guest accounts for bad routes by checking if the route exists in our `routes` before creating a guest account.
1. Check the number of accounts currently in your local db (`select count(id) from accounts;`)
2. Without logging in, visit a bad route and see our 404 page
3. Check the number of accounts in your local db again and confirm it hasn't increased
Fixes #10358
> Avoid creating guest account for 404s

- server/app/repository/QueryProfileLocationBuilder.java
Previously, we were creating new ProfileLocation objects for every single database call we did where we used the .setProfileLocation(queryProfileLocationBuilder.create()) function. This caused the heap to fill up with these objects and they were never garbage collected. By creating a cache of these objects, we only create unique ones once each time the same repository function is called.
Remove this section if the title of the pull request can be used as the default release notes description. If more detail is needed to communicate to partners the scope of the PR's changes, use this release notes section (and remove this placeholder text).
Read the full guidelines for PRs [here](https://github.com/civiform/civiform/wiki/Technical-contribution-guide …
> Cache ProfileLocation per-repository

- browser-test/src/applicant/northstar_applicant_application_index.test.ts
- server/app/views/applicant/FilteredProgramsTemplate.html
- server/app/views/applicant/NorthStarFilteredProgramsViewPartial.java
- server/app/views/applicant/NorthStarProgramIndexView.java
- server/app/views/applicant/ProgramFiltersFragment.html
Currently in NS, when filters are applied, htmx is used to rerender part of the page to show filtered/unfiltered programs. This partial page is fetched through `/programs/hx/filter`. However, when clearing the filters, we currently fetch and rerender the whole page through `/programs`. 
We plan to update our content security policy to disallow inline styles (see https://github.com/civiform/civiform/issues/9980). However, this current behavior causes a CSP violation upon the page partially reloading when "Clear filters" is clicked, since htmx fetches and then attempts to parse the result for the whole page, which includes a `<style>` tag with a nonce in `<head>` and which fails to parse due to the new nonce not matching properly.
This change changes the "Clear filters" button to fetch just …
> Change htmx behavior to only reload part of the page on clearing filters

- browser-test/src/applicant/questions/northstar_file.test.ts
- server/app/services/MessageKey.java
- server/app/views/applicant/ApplicantProgramFileUploadBlockEditTemplate.html
- server/conf/i18n/messages
On file upload questions, there is a "Remove file" link next to each uploaded file.  When multiple files are uploaded, this means the links have duplicated names.  A screen reader user would have no way of knowing which file they were removing.  This adds an aria label which includes the name of the file in the link label so that users can differentiate between links.  For example: "Remove puppy.jpg file".
Also, semantically these should be buttons, not links. The purpose of a link would be to take the user to a different location, whereas the purpose of a button is for the user to take action.  So, this PR gives the anchor tags the aria role of "button" so that screen readers will treat them as buttons.
1. Create a program with a file upload question.
2. Turn the NS flag on.
3. Apply to …
> Adding aria-label to differentiate "Remove file" links and giving role of button

- browser-test/src/admin/admin_program_creation.test.ts
- browser-test/src/admin/admin_program_list.test.ts
- browser-test/src/admin/admin_program_migration.test.ts
- browser-test/src/admin/admin_program_translation.test.ts
- browser-test/src/admin/admin_program_visibility.test.ts
- browser-test/src/admin/northstar_admin_program_image.test.ts
- browser-test/src/applicant/applicant_application_index.test.ts
- browser-test/src/applicant/navigation/application_navigation_common_intake.test.ts
- browser-test/src/applicant/navigation/northstar_application_navigation_common_intake.test.ts
- browser-test/src/applicant/northstar_applicant_application_index.test.ts
- browser-test/src/applicant/northstar_common_intake_upsell.test.ts
- browser-test/src/support/admin_programs.ts
Change `addProgram()` in browser-test/src/support/admin_programs.ts to use `ProgramType` instead of a `isCommonIntake boolean`. This is wanted to support the introduction of external programs of a program type.
No functionality or UI changed.
Part of #10183
> [External Program Cards] Use ProgramType when adding programs on browser tests

- server/app/services/openapi/v2/Swagger2SchemaGenerator.java
- server/app/services/openapi/v3/OpenApi3SchemaGenerator.java
- server/test/services/openapi/v2/Swagger2SchemaGeneratorTest.java
- server/test/services/openapi/v3/OpenApi3SchemaGeneratorTest.java
Fix `toDate` parameter in the API (both v2 and v3) to be "on or before the provided date" instead of "on or after the provided date"
None
> Fix toDate API documentation

- server/test/services/export/CsvExporterServiceTest.java
- server/test/services/reporting/ReportingServiceTest.java
Fixes deprecation warnings in apache csv library. The `build` method is now `get`.
> Fix Apache CSV deprecation warnings

- server/app/controllers/dev/DevToolsController.java
ResetTables does multiple DB operations that should be atomic.
This is also a hopeful solution to #10416
> Wrap resetTables() in a transaction

- browser-test/src/admin/admin_settings.test.ts
- server/app/services/settings/SettingsManifest.java
- server/app/services/settings/SettingsService.java
- server/conf/env-var-docs.json
Allow admins to remove theme color settings by saving an empty string. If the setting is empty, the site will revert back to the default color(s).
Fixes #10423
> Allow empty strings when setting theme colors

- server/app/controllers/applicant/ApplicantProgramsController.java
- server/test/controllers/applicant/ApplicantProgramsControllerTest.java
In https://github.com/civiform/civiform/pull/8701/files, we added validation that the programName is not an ID for the `show` endpoint, which gets called from /programs/:programParam, but we didn't handle the `showWithApplicantId` case
For more context:
There are two identical endpoints:
- [/programs/:programParam](https://github.com/civiform/civiform/blob/main/server/conf/routes#L192) 
- calls [controllers.applicant.ApplicantProgramsController.show](https://github.com/civiform/civiform/blob/94d06b451ee15e5674690662c6e24b66a1ca44e3/server/app/controllers/applicant/ApplicantProgramsController.java#L201), which then calls [showWithApplicantId](https://github.com/civiform/civiform/blob/main/server/app/controllers/applicant/ProgramSlugHandler.java#L96)
- …
> Redirect to home page when applicants/:applicantId/programs/:programName has an invalid programName

- server/app/models/Models.java
When we truncate tables to reset the DB for tests, we don't clear the relational tables which build up defunct relations over time.   In Staging probers we're up to program ID 350k which means versions_programs has at least that many rows, and versions_questions likely even more.
Fixes #10441
> Truncate relational tables when tests clear the database

- server/app/views/admin/programs/ProgramBlocksView.java
- server/app/views/components/ProgramCardFactory.java
Small cleanups in the admin code:
- remove unnecessary `else` around `return` statements
- remove unnecessary `if/else` condition when adding properties to `blockDeleteModalButton`
None
> Small condition statements cleanups in admin code

- server/app/views/applicant/ProgramCardsSectionFragment.html
- server/app/views/applicant/ProgramCardsSectionParamsFactory.java
- server/test/views/applicant/ProgramCardsSectionParamsFactoryTest.java
Use `programType` instead of `isCommonIntake` in `ProgramCardParams`. This will allow for an easier introduction of  external program cards
No functionality or UI changed.
Part of #10184
> [External Program Cards] Use ProgramType in ProgramCardsParam

- server/test/controllers/LogoutAllSessionsControllerTest.java
Initialize LogoutAllSessionsController with the mocks. Previously this test wasn't actually using the mocks, but we didn't realize because the assertions were happening in a `thenAccept()`. This completes the future before asserting values. 
There was also a bug with decoding the authorityId, which I removed.
I recommend clicking the "Hide whitespace" setting when reviewing.
> Fixes for LogoutAllSessionsControllerTest

- browser-test/src/support/admin_programs.ts
- browser-test/src/support/applicant_questions.ts
- server/app/controllers/applicant/UpsellController.java
- server/app/services/MessageKey.java
- server/app/views/applicant/ApplicantPreScreenerUpsellCreateAccountView.java
- server/app/views/applicant/ApplicantPreScreenerUpsellTemplate.html
- server/app/views/applicant/ApplicantProgramSummaryView.java
- server/app/views/applicant/NorthStarApplicantPreScreenerUpsellView.java
- server/app/views/applicant/NorthStarApplicantProgramSummaryView.java
- server/app/views/applicant/ProgramCardsSectionParamsFactory.java
- server/app/views/applicant/ProgramIndexTemplate.html
- server/app/views/applicant/ProgramIndexView.java
- server/conf/i18n/messages
- server/conf/i18n/messages.am
- server/conf/i18n/messages.ar
- server/conf/i18n/messages.de
- server/conf/i18n/messages.es-US
- server/conf/i18n/messages.fr
- server/conf/i18n/messages.ja
- server/conf/i18n/messages.ko
- server/conf/i18n/messages.lo
- server/conf/i18n/messages.ru
- server/conf/i18n/messages.so
- server/conf/i18n/messages.tl
- server/conf/i18n/messages.vi
- server/conf/i18n/messages.zh-TW
Slowly renaming "common intake" to "pre-screener" to minimize confusion. This PR handles message keys and file names.
> Rename message keys and file names from "common intake" to "pre-screener"

- browser-test/src/applicant/northstar_applicant_application_index.test.ts
- server/app/views/applicant/ModalFragment.html
- server/app/views/applicant/ProgramCardsFragment.html
Use a unique ID for each external program modal to ensure clicking different external program cards opens their respective modals with the correct external link.
Changes in the PR include:
1. Modify the externalProgramModal fragment to accept a unique modalId, build from the program id, parameter alongside the existing externalLink parameter
2. Use this modalId to create unique IDs for each modal instance
3. Update the card's modal trigger button to reference its unique modal ID
Screencast: 
https://github.com/user-attachments/assets/7ae4d8e0-7d2e-4433-a190-4d2742d7b510
3. Create …
> [External Program Cards] Show external program modal based on program id

- browser-test/src/admin/admin_program_creation.test.ts
- server/app/assets/javascripts/admin_programs.ts
Disable 'confirmation message' text field when adding an external program, since an external program application is hosted outside of Civiform.
#10397 disabled the `confirmation message` text field when editing an external program, but there was a small bug when creating an external program. This should have been caught in the test, but test was missing! (this was part of a larger change so I may have split the files incorrectly.. ).
3. Start creation of a program
4. Select 'external program' on program type
5. Verify 'confirmation message' text field is disabled
6. Save program …
> [External Program Cards] Disable confirmation message on external program creation

- browser-test/src/admin/admin_program_list.test.ts
- browser-test/src/support/admin_programs.ts
- server/app/views/admin/programs/ProgramIndexView.java
Remove the buttons from the extra rows that are not applicable for external program on their program cards:
- On active mode: 'Applications'
- On draft mode: 'Manage application statutes'
3. Create an external program
4. Go to the admin dashboard, verify 'manage program applications' is not shown on the extra rows dropdown
5. Publish the external program, verify 'applications' is not shown on the extra rows dropdown
Part of #10183
> [External Program Cards] Remove application related extra actions for external program cards

- server/test/services/applicant/CurrencyTest.java
CurrencyTest Errorprone fixes remove unneeded boxing.
Related #10471
> CurrencyTest Errorprone fixes

- browser-test/src/admin/dev_tools.test.ts
- server/app/actions/DemoModeDisabledAction.java
- server/app/controllers/dev/DevToolsController.java
- server/test/actions/DemoModeDisabledActionTest.java
Ensure destructive DevTools actions can't be completed when staging_disable_demo_mode_logins is enabled. When someone navigates to a devtools URL, we will navigate to the home page.
Turn on flag and then attempt to navigate to one of the devtools URLs
Fixes https://github.com/civiform/civiform/issues/10548
> Disable DevTools actions when DevTools is disabled in settings

- browser-test/src/admin/admin_program_creation.test.ts
- browser-test/src/support/admin_programs.ts
- server/app/assets/javascripts/admin_programs.ts
We add the `readonly` attribute on initial render when a field should be disabled so it shows up as greyed out. Previously, we were dynamically adding and removing the `disabled` attribute, but not the `readonly` attribute which was causing fields to appear disabled when they should have been enabled. This PR fixes that by toggling the `readonly` attribute at the same time as the `disabled` attribute when admins are editing program details.
Create a program and try as many combos as you can think of for enabling/disabling fields for a pre-screener. Try:
- save a program as a pre-screener, edit it, check/un-check the "pre-screener" box and confirm fields …
> Remove readonly attribute when admin program fields are enabled

- server/app/controllers/applicant/ProgramSlugHandler.java
- server/test/controllers/applicant/ProgramSlugHandlerTest.java
Remove the program url for external programs.
External programs don't have a program overview or review page. Either giving the applicant a link that navigates to an external page or immediately shows a modal is a weird experience. Thus, we decided for program urls to be invalid for external programs. We use ProgramNotFoundException error to mimic the behavior when an invalid program url is provided, instead of re-directing to the base url.
3. Start creation of a program
4. Select 'external program' on program type
5. Copy the program url (e.g http://localhost:9000/programs/ext1) …
> [External Program Cards] Invalidate program URL for external programs

- browser-test/src/api_docs_schema_viewer.test.ts
- server/test/services/applicant/question/TextQuestionTest.java
See #10471. Fixing "unused variable" message.
> Fix errorprone message for TextQuestionTest

- browser-test/src/api_docs_schema_viewer.test.ts
- server/conf/application.dev.conf
https://github.com/civiform/civiform/pull/10316 was meant to set the style-src for dev environments but accidentally set the script-src twice.
https://github.com/civiform/civiform/issues/9980
> Fix typo in dev csp setting

- server/test/controllers/admin/AdminApplicationControllerTest.java
Fix the Errorprone errors for AdminApplicationControllerTest.
Removes unused start time variable and swaps out a local instance for the private instance of profileFactory.
See issue #10471
> Fix Errorprone errors for AdminApplicationControllerTest

- server/app/services/apibridge/ApiBridgeExecutionContext.java
- server/conf/application.conf
- server/conf/helper/api-bridge.conf
Adding in a new execution context for future api bridge stuff to work off of a separate threadpool
Related to: #10555
> Adding new execution context

- server/app/controllers/admin/AdminImportController.java
- server/app/services/migration/ProgramMigrationService.java
- server/test/services/migration/ProgramMigrationServiceTest.java
Add a validation method in the `ProgramMigrationService` to disallow importing questions whose keys (JSON API keys) conflict with each other, or with an existing question. If the key conflicts with an existing question, it is allowed as long the admin name also matches, so it can be handled "smartly" by the duplicate-handling logic. #9628
Try importing two questions in the same program with admin names `foo_bar01` and `foobar23`. 
Try saving a question named `foo_bar01` and then importing a question named `foobar23`, and a question named `foo_bar01`
Fixes #10552
> Disallow duplicate question keys during import

- browser-test/src/admin/admin_program_migration.test.ts
- browser-test/src/support/admin_programs.ts
Use `getProgramCard` instead of `programCardSelector` in browser tests. This reduces code complexity. Only instance left of `programCardSelector`  is by `withinProgramCardSelector`, which will be migrated along with its callers in a separate PR.
No functionality changed
Fixes #10513
> [Cleanup] Use getProgramCard instead of programCardSelector

- browser-test/src/admin/admin_program_list.test.ts
- browser-test/src/support/admin_programs.ts
- server/app/views/admin/programs/ProgramIndexView.java
Remove 'share' action from the program card for external program on active mode, since external programs don't have a program link.
3. Create an external program
4. Go to the admin dashboard
5. Publish the external program
6. Verify 'share link' is not shown on the external program card
Part of #10183
> [External Program Cards] Hide share actions for external program cards in admin panel

- browser-test/src/admin/admin_program_list.test.ts
- browser-test/src/support/admin_programs.ts
- server/app/views/admin/programs/ProgramAdministratorProgramListView.java
Remove 'share' and 'view' action from the external program card for program administrators (not civiform administrators) since external programs don't have a program link or overview.
Note: external programs shouldn't be visible for program administrators since there is no action they can take. For this we need to remove 'manage program administrators' from the cards in the CiviForm admin panel (will be done in separate PR). However, demo versions add a program fake admin even if we remove the control. Thus we still handle hiding the actions for external program cards for program admins
1. Log in as a CiviForm admin
2. Enable …
> [External Program Cards] Hide actions for external program cards for program admins

- browser-test/src/admin/admin_program_email_notifications.test.ts
- browser-test/src/admin/admin_program_migration.test.ts
- browser-test/src/applicant/application_review.test.ts
- browser-test/src/applicant/northstar_application_review.test.ts
- browser-test/src/applicant/northstar_program_overview.test.ts
- browser-test/src/support/admin_programs.ts
Use `getProgramCard()`, and methods which use it, instead of `withinProgramCardSelector()` in browser tests. This reduces code complexity.
With this we can remove `withinProgramCardSelector()` and `programCardSelector()`, which are no longer used.
No functionality changed
Part of #10513
> [Cleanup] Use getProgramCard instead of withinProgramCardSelector

- browser-test/src/applicant/northstar_applicant_application_index.test.ts
- server/app/assets/javascripts/north_star_modal.ts
- server/app/views/applicant/ProgramCardsFragment.html
External programs are displayed in the applicant home page as program cards. Currently
- A program card is added directly on [ProgramIndexTemplate](https://sourcegraph.com/github.com/civiform/civiform/-/blob/server/app/views/applicant/ProgramIndexTemplate.html?L75-79) 
- [Clicking](https://sourcegraph.com/github.com/civiform/civiform/-/blob/server/app/views/applicant/ProgramCardsFragment.html?L202-212) on an external program card shows the 'external program' modal.
- When a filter is selected, the [NorthStarFilteredProgramsViewPartial](https://sourcegraph.com/github.com/civiform/civiform/-/blob/server/app/views/applicant/NorthStarFilteredProgramsViewPartial.java?L125-127) renders the HTMX partial view containing the program cards and clicking the button doesn't show the modal
This PR …
> [External Program Cards] Show external program modal when triggered from HTMX card

- server/app/assets/javascripts/modal.ts
Remove error thrown when modal container is not found, since there is another modal ts file for northstar.
Seattle was still seeing issues with file upload (https://github.com/civiform/civiform/issues/10444) when northstar mode was enabled with prod.
We could consider logging something in the console still, but it didn't seem necessary, since there is another modal file for northstar that is being used instead.
I tested this by bringing back this line (https://github.com/civiform/civiform/pull/10542/files#diff-4899391bb04e0d72d4014d90b7aabcd5b501510dc4b6bdde08390757b98439baL3) and ensuring that the error no longer gets thrown but functionality works the …
> Remove error thrown when modal container is not found

- browser-test/src/admin/admin_program_list.test.ts
- server/app/views/admin/programs/ProgramIndexView.java
Remove 'manage admins' action from the program card for external program on active mode. Program admins can't edit anything on external programs, therefore there is no reason to add program admins to external programs.
3. Create an external program
4. Go to the admin dashboard
6. Verify 'manage admins' is not shown on the extra actions (clicking the three dot button) for an external program card
Part of #10183
> [External Program Cards] Hide 'manage program admin' for external program in civiform admin panel

- server/conf/application.dev.conf
- server/conf/application.test.conf
Typically we disallow the use of 0.0.0.0/0 in API keys for security reasons. This makes it more difficult to use the API locally for developers as it needs to be the Docker network IP which isn't guaranteed to be the same when starting a container.
This will let developers enter 0.0.0.0/0 when creating an API key on their local machine, which then the IP validation will allow any IP to connect.
This also reverts the unit tests config back to the stricter settings they already expect.
No changes to the browser tests config as they already allow any IP.
> Allow any IP to be used for API access in dev mode

- server/app/controllers/dev/seeding/SampleQuestionDefinitions.java
- server/app/services/seeding/DatabaseSeedTask.java
To help with testing, add Arabic translations to sample questions. 
This doesn't provide a translation for every single question/answer in Comprehensive Sample Program, but pretty close. I used Google Translate to source the Arabic translations and didn't verify accuracy, but that should be OK since it's a dev program, and we're only using the translations to determine whether or not the formatting looks correct in RTL mode.
#10606
> [RTL] Add arabic translations to seed questions

- server/app/repository/ProgramRepository.java
Expands the transaction in createOrUpdateDraft() which encompasses the Create flow to encompass the Update too so that both are consistent with the Draft program read that is used as the create or update switch.
Add comments about other transaction usage for future refinement.
Manually tested the "update" flow by changing which program is the pre-screener which requires the one being changed from to be a draft.
Manually tested the "create" flow by editing programs.
Improves data consistency by updating database transaction usage to Program database code.
Addresses: #10188
> Update Transaction usage in ProgramRepository

- server/test/services/applicant/ApplicantServiceTest.java
- server/test/support/TestProgramUtility.java
Making createProgramWithNongatingEligibility() public so we can use it in other test files. More specifically the test file about to be created to test the durable job for eligibility determination.
Part of https://github.com/civiform/civiform/issues/8852
> Making createProgramWithNongatingEligibility() a public method

- server/app/controllers/admin/AdminImportController.java
- server/app/repository/QuestionRepository.java
- server/app/services/migration/ProgramMigrationService.java
- server/test/repository/QuestionRepositoryTest.java
- server/test/services/migration/ProgramMigrationServiceTest.java
Since we are performing a series of sequential reads writes, we wrap all the business logic that interacts with the DB in a transaction. To do this, we had to tweak a few other classes, but it is pretty straightforward.
`bulkCreateQuestions` is only called from the `programMigrationService`, so since we added a top-level transaction, we can remove the transaction at that nested level.
#9628
> Wrap program import in a transaction

- server/app/repository/QuestionRepository.java
- server/app/services/migration/ProgramMigrationService.java
- server/test/repository/QuestionRepositoryTest.java
- server/test/services/migration/ProgramMigrationServiceTest.java
Only loop over newly saved Qs to update them.
Importing [this program](https://docs.google.com/document/d/16dVvxv2uVdHflDJK4N02AulcmyrtlvVMhc3kULY3q0k/edit?resourcekey=0-GaFLL5D1hJm8X5JCxDuNwQ&tab=t.0) then [this one](https://docs.google.com/document/d/1UYyVjizFc53RZ67JnO2-XnzvlaPrBEHYmvyAD34qWXs/edit?tab=t.0) yielded the following error upon saving with the default `use existing` option:
```
Error: java.lang.NullPointerException: Cannot invoke "services.question.types.QuestionDefinition.getName()" because the return value of "com.google.common.collect.ImmutableMap.get(Object)" is null
```
This error was because the `updateEnumeratorIdsAndSaveQuestions` method was trying to update enumerator IDs on all questions (including reused questions) but we should only be looping over the newly …
> Only update enumerator IDs for newly saved Qs

- browser-test/src/applicant/northstar_applicant_application_index.test.ts
- server/app/assets/javascripts/north_star_modal.ts
Program cards for external programs are rendered with HTMX when a filter is selected. Since the modal trigger is added after initialization via HTMX and doesn't have an event listener, 'htmx:afterSwap' listener adds a click listener to the modal trigger buttons to show the modal and listen for close actions to hide the modal.
This PR adds a click listener to the modal wrapper to close the modal if there is a click inside the wrapper but outside the actual dialog
Solution was suggested by AI, but fully verified by PR owner.
3. Create and publish an external program with a filter
4. …
> [External Program Cards] Close modal when clicking outside the modal for external program opened after HTMX initialization 

- browser-test/src/applicant/northstar_applicant_application_index.test.ts
- server/app/services/MessageKey.java
- server/app/views/applicant/ProgramCardsFragment.html
- server/conf/i18n/messages
Add aria label to the button in the card for external program that informs the user clicking the button will open the modal for that specific program
1. As an admin, create an external program
2. Go back to the applicant home page
3. Turn the screen reader on
4. Tab to the "View in new tab" button on the external program card
5. Verify screen reader says "View <program name> in new tab"
Fixes #10595
> [External Program Cards] Add aria label to external program card button

- browser-test/src/admin/admin_program_migration.test.ts
- browser-test/src/support/admin_program_migration.ts
- server/app/assets/stylesheets/uswds/_uswds-theme-custom-styles.scss
- server/app/views/admin/migration/AdminImportView.java
- server/app/views/admin/migration/AdminImportViewPartial.java
Adds styles to support a loading spinner, and adds the `htmx-request` class to USWDS submit buttons in the program import flow. Also disable the buttons during load. Note this change is *not* feature-flag guarded.
We add themes in `server/app/assets/stylesheets/uswds/_uswds-theme-custom-styles.scss` rather than `server/app/assets/stylesheets/northstar/_uswds-theme-custom-styles.scss`, since the admin bundle doesn't include northstar styles.
https://github.com/user-attachments/assets/460562a4-5ead-489f-86c5-1e7f5c45e9e0
Fixes #9289
> Add a loading spinner for HTMX button click

- browser-test/src/support/admin_program_migration.ts
Fixes a race condition with HTMX and the button disabled check. The awful formatting is out of my control.
> Fix test race condition

- browser-test/src/applicant/northstar_applicant_question_translation.test.ts
- server/app/views/applicant/NavigationFragment.html
This PR fixes a UI bug in the NorthStar applicant header where the language selector was being shown even when only one language was enabled.
- Updates the logic in `NavigationFragment.html` to conditionally render the language selector only if there are multiple enabled languages.
- Adds a browser test (`northstar_language_selector.test.ts`) to verify that the selector:
- Does appear when multiple languages are enabled.
- Fixed: Hide language selector when only one language is enabled in NorthStar UI
- Added: browser test to verify language selector visibility under multi-language conditions.
If instructions are needed for manual testing by reviewers, …
> (fix) Hide language selector when only one language is enabled (NorthStar Ui)

- browser-test/src/admin/admin_program_creation.test.ts
- browser-test/src/support/admin_programs.ts
- server/app/views/admin/programs/ProgramFormBuilder.java
- server/test/views/admin/programs/ProgramFormBuilderTest.java
Program ID field in the program create/edit form is used as a program identifier internally and to create the program URL for default programs and pre-screeners. Since external programs don't have URL, this PR updates the field to better communicate it.
String changes:
- Create page: _Create_ a program ID. This ID can only contain lowercase letters, numbers, and dashes. It will be used in the program’s applicant-facing URL (except for external programs), and it can’t be changed later._
- Edit page (default program / pre screener): _The URL for this program. This URL can't be changed._
- Edit page (external program): _The program ID. This ID can't be changed._
Field changes:
- Edit page (external program): show the program id instead of the URL, since there is no URL for external programs …
> [External Program Cards] Update strings for program slug field in program form

- server/app/views/admin/programs/ProgramFormBuilder.java
- server/test/views/admin/programs/ProgramFormBuilderTest.java
`buildApplicationStepDiv()` was declared as a static method in order to call it directly from the unit test. However, that's not a good practice since the method is no longer contained inside the class. #10640 introduced a setup method where a mock `ProgramFormBuilder` is built. Thus, we can use it to call `buildApplicationStepDiv()` which allows us to change the static method to a protected one.
No functionality or UI changed
None
> [Cleanup] Remove static from buildApplicationStepDiv() used only by tests

- server/app/services/applicant/ApplicantService.java
- server/test/services/applicant/ApplicantServiceTest.java
External program cards are only supported in North Star. Only add external programs to unapplied programs in ApplicantService if North Star is enabled. That way we don't display external programs in pre NS.
1. Login as a CiviForm admin
2. Enable EXTERNAL_PROGRAM_CARDS_ENABLED and NORTH_STAR_APPLICANT_UI
3. Create and publish an external program
4. Logout
5. Verify external program card is visible
6. Login as a CiviForm admin
7. Disable NORTH_STAR_APPLICANT_UI
8. Logout
9. Verify external program card is hidden
Part of #10184
> [External Program Cards] Don't include external program for cards in pre NS

- server/app/controllers/api/ProgramApplicationsApiController.java
- server/app/services/DateConverter.java
- server/app/services/openapi/v2/Swagger2SchemaGenerator.java
- server/app/services/openapi/v3/OpenApi3SchemaGenerator.java
- server/test/controllers/api/ProgramApplicationsApiControllerTest.java
- server/test/services/DateConverterTest.java
- server/test/services/openapi/v2/Swagger2SchemaGeneratorTest.java
- server/test/services/openapi/v3/OpenApi3SchemaGeneratorTest.java
List applications have `fromDate` and `toDate` parameters that receive an ISO-8601 date (YYYY-MM-DD). This PR updates the date parser to support time stamps, still with the ISO-8601 format.
In order to not break current calls, we need to continue supporting only date parameters. Therefore, we introduce `parseIso8601DateToLocalDateTimeInstant(dateString)` with three parsing scenarios in order of preference:
1.  Full ISO-8601 string with timezone information (e.g., "2023-12-25T10:30:00Z")
2.  ISO-8601 date-time without timezone (e.g., "2023-12-25T10:30:00"), converted using the configured local zone
3.  ISO-8601 date only (e.g., "2023-12-25"), defaulting to start of day in local timezone
Since we are maintaining existing functionality, this change is not under a feature flag
User-facing …
> [API] Support time filter for list applications

- server/app/services/applicant/ApplicantService.java
- server/app/views/applicant/NorthStarProgramIndexView.java
- server/app/views/applicant/ProgramIndexView.java
- server/test/services/applicant/ApplicantServiceTest.java
Updating to use pre-screener rather than common intake in the Applicant service methods to minimize confusion.
> Rename common intake to pre screener in ApplicantService.java

- browser-test/src/error_pages.test.ts
- server/app/services/settings/SettingsManifest.java
- server/app/views/errors/InternalServerError.java
- server/conf/env-var-docs.json
Use IT email address for internal server errors with fallback to support email and update description of IT email setting.
Demo: 
Fixes #8372
> Use IT email address for internal server errors

- mock-web-services/apibridge/__init__.py
- server/app/services/apibridge/RetryAfterHeaderParser.java
- server/app/services/apibridge/RetryingWSClient.java
- server/test/services/apibridge/RetryAfterHeaderParserTest.java
- server/test/services/apibridge/RetryingWSClientTest.java
Creates a new WSClient class that will retry on errors or handle the retry-after header for on throttled http 429 calls. Fully async future based.
Updates the mock web services to return a retry-after header when calling generates a 429 response.
Creates a class that can appropriately parse the value from the retry-after header as it can be either a date or number of seconds.
Related to [#10555](https://github.com/civiform/civiform/issues/10555)
> Adding wsclient retry capabilities

- browser-test/src/api_docs.test.ts
- browser-test/src/api_docs_schema_viewer.test.ts
- server/app/controllers/docs/ApiDocsController.java
- server/app/controllers/docs/OpenApiSchemaController.java
- server/app/repository/ProgramRepository.java
- server/app/services/apikey/ApiKeyService.java
- server/app/services/program/ProgramService.java
- server/test/controllers/docs/ApiDocsControllerTest.java
- server/test/controllers/docs/OpenApiSchemaControllerTest.java
- server/test/repository/ProgramRepositoryTest.java
- server/test/support/ResourceCreator.java
External programs are not available via the API so they should be removed as options from the dropdown on both pages of the API docs. If only external programs exist, "program not found" treatment is shown.
This approach replaces getAllProgramSlugs with getAllNonExternalProgramSlugs as the only usage was in API docs. Another approach considered was to allow passing in flexible program types as input: getProgramSlugsForType(programType), but this seemed unnecessary if filtering out external only would be the standard use case.
Also makes a small fix to an existing schema test that intended to test the schema root ui but was calling schemaBySlug instead (duplicate of another test).
Note: It's still possible to access external program docs directly via url, in which case the experience isn't …
> Exclude external programs from API docs

- server/app/controllers/admin/AdminApplicationController.java
- server/app/controllers/api/ProgramApplicationsApiController.java
- server/app/repository/ProgramRepository.java
- server/app/repository/SubmittedApplicationFilter.java
- server/test/repository/ProgramRepositoryTest.java
When retrieving applications with `getApplicationsForAllProgramVersions()`, all applications matching `ACTIVE` and `OBSOLETE` lifecycle stage are [returned](https://sourcegraph.com/github.com/civiform/civiform@519ec3bf4c4ddd0b24838d28c9c377fb53a5b7f8/-/blob/server/app/repository/ProgramRepository.java?L453-454). 
To support #499, we need to introduce retrieving application by lifecycle stage. Therefore, this PR 
- adds a list of lifecycle stages to `SubmittedApplicationFilter`. 
- moves the default value (active and obsolete applications) to the caller. While now all the callers have the same stages, this allows each controller to decide the stages (which could also add more granularity to the other places, like downloading JSON)
**Potential future improvements** …
> [API] Add lifecycleStages to SubmittedApplicationFilter

- .github/pull_request_template.md
Update our PR template with our latest guidance about when to tag an admin as an fyi reviewer.
> Add note about tagging eng-admin as fyi reviewer to pull request template

- server/app/controllers/docs/ApiDocsController.java
- server/app/controllers/docs/OpenApiSchemaController.java
- server/test/controllers/docs/ApiDocsControllerTest.java
- server/test/controllers/docs/OpenApiSchemaControllerTest.java
External programs are not available via the API so they should return not found in API docs when accessed by program slug directly in the url. This is a followup to #10728 which removed them from the UI program dropdowns.
Fixes #10755
> Don't return API docs for external programs

- server/app/controllers/api/ProgramApplicationsApiController.java
- server/app/services/openapi/v3/OpenApi3SchemaGenerator.java
- server/conf/routes
- server/test/controllers/api/ProgramApplicationsApiControllerTest.java
- server/test/services/openapi/v3/OpenApi3SchemaGeneratorTest.java
Currently, list applications API returns all submitted applications. That is, all applications that have `LifecycleStage.ACTIVE` or `Lifecycle.OBSOLETE`. This PR adds a `revisionState` filter, which maps to internal `LifecycleStage`, to the API.
Follow ups:
- Add `revisionState`  to Swagger schema (v2)
- Update public docs site page
Design doc: https://docs.google.com/document/d/1uwon5sEg2jHcjlDJ4qs0RZfiNMBTvHnKeJSDdKyf3Nw/edit?usp=sharing
**AI usage**
AI was used to generate unit tests for ProgramApplicationsApiController. Generated code was used as a reference, but actual PR code was implemented by PR owner.
Part of #4995
> [API] Support revisionState filter for list applications 

- .github/workflows/format.yaml
- bin/fmt
The `bin/fmt` script was running based off the docker hub tag version. Our scripts should reference the local tag, that is the one without the `/`. 
:+1:  `civiform-formatter`
:no_good: `civiform/formatter`
This also makes it so that changes to the `bin/fmt` script will trigger the `format` github action to re-build the formatter to take into account any changes that may have happened.
This should now always run the formatter based on the latest changes.
> Fixing formatter to call the local docker image

- server/app/services/openapi/v2/Swagger2SchemaGenerator.java
- server/test/services/openapi/v2/Swagger2SchemaGeneratorTest.java
Add `revisionState` to list applications API in Swagger 2.0 schema. Support for revision state was added on #10702
Part of #4995
> [API] Add revisionState to list applications in Swagger 2.0

- .github/renovate.json5
For a few packages Renovate will include static links to release notes which makes oncall easier.
Oncall: #10784
> Add links in Renovate PRs to release notes for a few packages

- browser-test/src/applicant/northstar_ineligible.test.ts
- server/app/actions/RouteExtractor.java
- server/app/views/NorthStarBaseView.java
- server/app/views/applicant/ApplicantLayout.java
- server/app/views/applicant/NavigationFragment.html
- server/test/views/applicant/ApplicantLayoutTest.java
Changing the language on an eligibility alert page currently throws an error. This is because the eligibility page is shown after POST requests to submit an application or page and redirecting back to a POST endpoint results in a 404.
This change fixes the issue by checking if the current request is a submit/update url and replaces it with the associated GET endpoint instead. Ex: `/submit` redirects to `/review` and `/blocks/:blockId/../` redirects to `/blocks/:blockId/review` or `/blocks/:blockId/edit`. See [applicant routes](https://github.com/civiform/civiform/blob/bd055a1627d14503d01d1cb075f938c4c1b0dfca/server/conf/routes#L178-L187). This duplicates the logic in both NS and legacy for consistency but this seems acceptable since it's a relatively simple change and legacy paths may be …
> Redirect to review or edit when changing language during submit/update

- server/app/controllers/applicant/ApplicantProgramsController.java
- server/app/services/monitoring/MonitoringMetricCounters.java
- server/test/controllers/applicant/ApplicantProgramsControllerTest.java
#10763 is introducing a feature where URLs use programSlug instead of programId. When the feature is enabled, we redirect to the main page if programId is used on the public facing URL. To decide whether we should make such URL invalid, we are adding metrics for this.
This PR adds metrics to the `/edit` route. 
Part of #10763
> [ProgramSlugUrl] Add metrics to /edit

- browser-test/src/support/admin_programs.ts
`await locator(...).isVisible()` doesn't actually assert anything, it gets the boolean value and discard it. Instead, we should use `toBeVisible()` so test will fail if the element is not visible. Similarly for `isHidden()` to `toBeHidden()`
This fixes calls in admin_programs.ts
None
> [Bug] Use toBeVisible instead of isVisible in admin_programs.ts

- .github/ISSUE_TEMPLATE/oncall-rotation.md
Update our oncall instructions to document the new process around how we should handle broken dependency updates.
[Docs](https://docs.civiform.us/governance-and-management/project-management/on-call-guide) will also be updated with this info.
> Add new dependency update process to oncall

- browser-test/src/applicant/northstar_application_version_fast_forward.test.ts
- server/app/actions/ProgramDisabledAction.java
- server/test/actions/ProgramDisabledActionTest.java
`ProgramDisabledAction` is an action filter that intercepts requests for disabled programs and redirects users
to an appropriate disabled program info page. As part of #10763, URLs are being changed to use `programParam` instead of `programId`, where program param can be the program id or the program slug.
This PR adds functionality to extract the program slug from the request's programParam (if existent), since we want to keep the same redirect functionality for disabled programs.
Part of #10763
> [ProgramSlugUrl] Retrieve slug from programParam in ProgramDisabledAction

- server/app/forms/DateQuestionForm.java
- server/app/services/question/types/DateQuestionDefinition.java
- server/app/services/question/types/QuestionDefinitionBuilder.java
- server/test/forms/DateQuestionFormTest.java
This change adds validation predicates for min/max dates to the date question definition and admin edit form:
1. Add min/maxDate fields to `DateQuestionDefinition`. Define new`DateValidationOption` which encapsulates a pair of `DateType` and optional LocalDate for custom dates.
2. Add min/max date type and custom date fields to `DateQuestionForm`. These are separated out to correspond with each input field (select for date type and date picker for custom date).
3. Populate `DateQuestionForm` fields from `DateQuestionDefinition` and, vice versa, build `DateQuestionDefinition.DateValidationPredicates` from the form fields.
This change defines the new fields but does not yet expose them in any UI or support setting them in the admin form. Verified no change to date question behavior locally. …
> [Date Validation] Add DateValidationOption to date question definition and form

- server/app/services/settings/SettingsManifest.java
- server/conf/env-var-docs.json
- server/conf/helper/feature-flags.conf
Adds an admin readable feature flag, MAP_QUESTION_ENABLED, for development of new map question.
Fixes #10713;
> [Maps] Add feature flag for map question

- server/app/assets/stylesheets/uswds/_uswds-theme-custom-styles.scss
- server/app/forms/DateQuestionForm.java
- server/app/services/question/types/QuestionDefinition.java
- server/app/views/admin/questions/QuestionConfig.java
- server/test/views/admin/question/QuestionConfigTest.java
Add Memorable datepickers for min/max date validation to date question config. Also includes fix to DateQuestionForm to include separate day/month/year params and getters/setters since these are separate input fields in the Memorable date component. This adds the datepicker elements but does not yet handle toggling show/hide interactions based on whether the date type dropdown is "custom".
Changes:
- Add min/max MemorableDate to Date `QuestionConfig`
- Populate with values from `DateQuestionForm` if present
- Set initial hidden tag if question's saved date type is not `CUSTOM`
- Expand min/maxDate in `DateQuestionForm` to handle individual day/month/year fields
- Register missing JavaTimeModule for json parsing
- Adds tests for QuestionConfig, intend to add browser tests when full …
> [Date validation] Render date picker for custom min/max date validation

- server/app/controllers/applicant/ApplicantProgramBlocksController.java
Fix the label value for some of the program slug URL metrics, which were using the wrong path.
Part of #/10763
> [ProgramSlugUrls]: Fix label value in metrics

- server/app/services/question/types/DateQuestionDefinition.java
- server/test/services/question/types/DateQuestionDefinitionTest.java
Now that admin can create date questions with validation parameters, we need to validate that the provided parameters represent a valid date range.
This change adds a `validateInternal` method to `DateQuestionDefinition` which performs the following checks:
- if at least one of start/end is provided then both must be present
- a custom date is provided iff date type is custom
- if minDate is custom and maxDate is application date, then minDate < today
- if maxDate is custom and minDate is application date, then maxDate > today
- if minDate and maxDate are both custom, then minDate < maxDate
- custom dates are valid dates -> in `DateQuestionDefinition` this is done by checking that the date is non-empty, since at this point the date has already been converted to `LocalDate` which has to …
> [DateValidation] Add validation checks to ensure admin provided date validation parameters create possible date ranges

- server/test/controllers/admin/AdminProgramControllerTest.java
Creates North Star counterparts for the tests for which NORTH_STAR_APPLICANT_UI had to be disabled for them to pass.
Part of #10971 ;
> [North Star] Write North Star tests for AdminProgramControllerTest.java

- formatter/fmt
Only run eslint when needed.
/server was running against all files which was slow. So I fixed it.
> Only run eslint when needed

- server/app/services/question/types/DateQuestionDefinition.java
- server/test/services/question/types/DateQuestionDefinitionTest.java
Add server validation for admin year values. This is currently done in the client, but it's possible to remove the client validation and still enter and submit a non 4 digit year.
Part of #5677
> [Date validation] Add server validation for admin start/end year settings

- browser-test/src/support/admin_predicates.ts
Use `getByRole` instead of `[getByText](button:has-text)` because it tests elements the way users (including those using assistive technologies) actually interact with them, making tests  more accessible and robust against UI changes.
None
> [Refactor] Use getByRole in admin_predicates.ts

- browser-test/src/applicant/application_version_fast_forward.test.ts
- browser-test/src/applicant/northstar_application_version_fast_forward.test.ts
Adding test.slow to a couple of tests that were timing out in aws staging prober tests.
> Add test.slow to fast forward tests

- server/app/services/settings/SettingsManifest.java
- server/conf/env-var-docs.json
- server/conf/helper/feature-flags.conf
Creates a feature flag to guard the rollout of the settings cache. #11130 #11042
Creates the SETTINGS_CACHE_ENABLED feature flag which will enable reading settings from a cache rather than from the database directly.
> Create SETTINGS_CACHE_ENABLED feature flag

- server/app/services/settings/SettingsManifest.java
- server/app/views/ProgramImageUtils.java
- server/app/views/admin/programs/ProgramBaseView.java
- server/app/views/admin/programs/ProgramFormBuilder.java
- server/app/views/admin/programs/ProgramImageView.java
- server/app/views/applicant/ProgramCardViewRenderer.java
- server/app/views/applicant/ProgramIndexView.java
- server/app/views/components/ProgramCardFactory.java
- server/conf/env-var-docs.json
- server/conf/helper/feature-flags.conf
- server/test/views/ProgramImageUtilsTest.java
The program filtering feature is complete.  This PR removes the feature flag entirely.
Program filtering is now always available in CiviForm.  It is no longer behind a feature flag.
> Remove the program filtering feature flag and all of its uses

- server/app/models/QuestionDisplayMode.java
- server/app/models/QuestionModel.java
- server/app/services/question/types/NullQuestionDefinitionConfig.java
- server/app/services/question/types/QuestionDefinition.java
- server/app/services/question/types/QuestionDefinitionBuilder.java
- server/app/services/question/types/QuestionDefinitionConfig.java
- server/conf/evolutions/default/89.sql
- server/test/controllers/admin/AdminImportControllerTest.java
Adds Display Mode to database and `QuestionModel` at related Question objects. Defaults existing data and objects to `VISIBLE`. Not editable by the application at this time.
Related to #10555
> Adding Display Mode to QuestionModel

- server/app/models/GeoJsonDataModel.java
- server/app/models/Models.java
- server/conf/evolutions/default/90.sql
- server/test/repository/GeoJsonDataRepositoryTest.java
Updates the `GeoJsonDataModel` to use our `BaseModel` class, adds the `id` column to the `geo_json_data` table, and makes sure the table is truncated in unit tests.
Updates GeoJsonDataModel base class and related dependencies.
> Update GeoJsonDataModel Base Class

- server/app/durablejobs/jobs/CalculateEligibilityDeterminationJob.java
- server/app/modules/DurableJobModule.java
- server/test/durablejobs/jobs/CalculateEligibilityDeterminationTest.java
`CalculateEligibilityDeterminationJob` job runs have been failing because Program Definitions are not fully hydrated with Question Definitions and underlying code that expects Question Definitions is erroring out. This change updates `CalculateEligibilityDeterminationJob` to fetch the program definition with `programService.getFullProgramDefinition` so that nested code which requires question definitions will run successfully.
1. Create a program with an eligibility condition and publish it
2. Apply to the program as an applicant
3. Update the data in …
> Fully hydrate program defintions in CalculateEligibilityDeterminationJob

- server/test/services/settings/SettingsCacheTest.java
This PR removes a test that relied on running immediately upon cache construction, within a few `ms`. This was obviously flaky, given that there is no determinism in the exact amount of time between `@Before` and `@Test` running. #11042 
> Remove flaky Settings Cache test

- server/app/auth/oidc/CiviformOidcLogoutActionBuilder.java
- server/test/auth/oidc/CiviformOidcLogoutActionBuilderTest.java
Add null check on ID Tokens for OidcLogoutAction
To prevent error on logout, add a check if the tokens returned from account.get().getIdTokens() are null  and return Optional.empty if so
Added additional test coverage for other cases that return Optional.empty
Fixes #10310
> Add null check on ID Tokens for OidcLogoutAction

- server/test/repository/GeoJsonDataRepositoryTest.java
Save test data within the `DatabaseExecutionContext`. The intermittent issue appears to be due to saving the models outside of the standard `DatabaseExecutionContext` that the repository uses. I've had this run multiple times now without failure so I think we are good.
> Save test data within the DatabaseExecutionContext

- server/app/views/admin/programs/ProgramBlocksView.java
- server/package-lock.json
- server/package.json
https://github.com/civiform/civiform/pull/10851 has been failing and it seems to be because of the type when we're using hx-post. This idea came from gemini. I can also just make the change here and then re-run https://github.com/civiform/civiform/pull/10851
Related to: https://github.com/civiform/civiform/pull/10851
> Update dependency htmx.org to v2.0.6 

- server/app/models/ApiBridgeConfigurationModel.java
- server/app/services/JsonUtils.java
- server/app/services/apibridge/AbstractPayloadMapper.java
- server/app/services/apibridge/ApiBridgeServiceDto.java
- server/app/services/apibridge/RequestPayloadMapper.java
- server/app/services/apibridge/ResponsePayloadMapper.java
- server/test/repository/ApiBridgeConfigurationRepositoryTest.java
- server/test/services/apibridge/RequestPayloadMapperTest.java
- server/test/services/apibridge/ResponsePayloadMapperTest.java
Adding payload mappers that converts between Api Bridge requests/responses and `ApplicantData`.
Related to #10555
> Adding payload mapper

- server/app/views/admin/AdminLayout.html
Making CSRF token always visible to HTMX. This removes the need to include it as a hidden element on a form for an HTMX. This is for the admin thymeleaf pages.
> Make csrf token always visible to htmx

- browser-test/src/northstar_question_lifecycle.test.ts
Map tests will only work in the dev environment because they rely on mock web services. They're currently failing in probers:  https://github.com/civiform/civiform-staging-deploy/actions/runs/17006670032
> Skip map tests for probers

- formatter/.sql-formatter.json
- formatter/fmt
- formatter/package-lock.json
- formatter/package.json
Adding a sql formatter to `bin/fmt`. As noted in the shell script, I'm ignoring sql files 1-91 (the existing sql files). Technically this is unnecessary as unmodified files in git are not included already, it's just an extra defense to prevent accidental changes to existing scripts.
[Sql formatter approval doc](https://docs.google.com/document/d/11P61Ef1biBH1t3jlqMnW9DmUXkBvTDvf_b2HkCTCmu8/edit?tab=t.0#heading=h.bknox3ib8wpb).
> Adding sql formatter

- browser-test/src/admin/northstar_admin_application_statuses.test.ts
- browser-test/src/support/admin_programs.ts
Addressed timing issues in the new northstar_admin_application_statuses by using newer playwright syntax. 
> Update tests and utilities to remove timing issues

- server/app/services/migration/ProgramMigrationService.java
- server/app/services/migration/QuestionValidationUtils.java
- server/test/services/migration/ProgramMigrationServiceTest.java
- server/test/services/migration/QuestionValidationUtilsTest.java
Implement validation for YES/NO questions during program import to ensure data integrity.
- Added `validateYesNoQuestions()` method to `QuestionValidationUtils` to validate that YES/NO questions only contain allowed options: 'yes', 'no', 'maybe', and 'not-sure'
- Integrated validation into both preview flow (`validateQuestions`) and save flow (`saveImportedProgram`) in `ProgramMigrationService`
- Added comprehensive test coverage for both `QuestionValidationUtils` and `ProgramMigrationService`
- Validation uses fast-fail approach, returning clear error messages for the first invalid option found
- Non-YES/NO questions are unaffected and can continue using custom options
Added validation for YES/NO question imports to prevent invalid option configurations. During program import, YES/NO …
> feat: Add YES/NO question validation for program import flow

- .github/renovate.json5
Add release notes link for awssdk renovate PRs. For example, for https://github.com/civiform/civiform/pull/11345 it should link https://github.com/aws/aws-sdk-java-v2/compare/2.32.24...2.32.29.  I used the template parameter names found from https://docs.renovatebot.com/configuration-options/#prbodydefinitions
I'm not really sure how to test this
> Add release notes link in awssdk renovate PRs

- server/app/repository/PersistedDurableJobRepository.java
- server/test/repository/PersistedDurableJobRepositoryTest.java
Change `getRecurringJobForExecution` to check UTC rather than local time to better match against the database. Database timestamps are stored in UTC.
This will change when existing jobs will run because they'll now be run at UTC instead of local time. If I'm correct, they were previously getting run at the wrong time. For example, the REPORTING_DASHBOARD_MONTHLY_REFRESH was getting stored in the DB with the execution time 9am UTC, and probably getting run at 9am PDT for Seattle. I will verify this with Swathi.
> Start recurring jobs on utc time

- .github/renovate.json5
Adds release note link for microsoft graph and sass-embedded. Also updates the aws link to just go to CHANGELOG.md.
> Add more release note links in renovate

- server/app/auth/CiviFormProfile.java
- server/app/auth/CiviFormProfileMerger.java
- server/app/repository/AccountRepository.java
- server/test/auth/CiviFormProfileMergerTest.java
The documentation around getting an `Applicant` from an `Account` are wrong and some of the method names are misleading as such.  This fixes the docs, adds references to an inprogress issue, and makes a method more explicit for clarity.
Addresses: #11304
> Clarify docs and naming around applicant selection

- browser-test/src/support/admin_programs.ts
- server/app/views/components/ProgramCardFactory.java
Currently the browser tests only allow selecting the extra actions button for draft mode or active mode when no draft exists. Tests will fail if you have a draft and try to get the active mode action buttons because Playwright is matching two elements. There isn't a great way to get the correct locator as is because looking for the text "active/draft" would need to find an ancestor element. Playwright isn't great at walking up the tree to a specific element.
This adds a data- attribute to inject the active/draft state on the correct parent element and has it filtering for that instead of the text of the inner child span.
I've tested this with Anna's sample test which passes.
Big note: This isn't ideal. In the future we should have a better way where we can find these using web first …
> Allow tests to select the extra buttons for active programs when draft and active are present

- server/app/services/export/QuestionJsonSampler.java
- server/test/services/export/QuestionJsonSamplerTest.java
Map questions are causing a bug with API documentation. Map questions will be implemented for the API later, but they will need a little tweaking to make it up to spec (API needs to send ids, but user review needs to display names). For now, just use an empty sample.
> [Maps] Handle map question api implementation (until it is actually implemented)

- server/app/services/CfJsonDocumentContext.java
- server/test/models/ApplicantModelTest.java
* Fixed a test-only impacting bug in the code. `this.read(path, Object.class).equals(...)` compares an Optional to not an optional which is always false.
* Fixed the related existing test setup
* Expanded the testing to include a list.
> Fix and expand ApplicantData test

- browser-test/src/admin/admin_application_download.test.ts
We can't set the NS flag in tests anymore, and no longer need to.
> Fix download flag browser test

- server/app/views/HtmlBundle.java
- server/conf/routes
A recent release of Firefox has started calling the `apple-touch-icon` image because of the new PWA support. It doesn't load on dev because we're using a `data-image` and because of that it is printing a lot of excessive noise to the console. This will just directly set the URL instead of the roundabout excessive routes that I've been meaning to remove anyway.
> Fix apple-touch-icon error

- docker-compose.dev.yml
- docker-compose.yml
Moving the definition of ports from the base compose file to the dev compose file to allow for dev and browser tests to run at the same time. This broke when we removed the custom localstack docker image.
> Fixing docker compose to run multiple localstack instances

- server/app/assets/javascripts/mapquestion/map_question_selection.ts
- server/app/services/applicant/predicate/JsonPathPredicateGenerator.java
- server/app/services/applicant/predicate/PredicateEvaluator.java
- server/app/services/applicant/question/MapQuestion.java
- server/app/services/applicant/question/MapSelection.java
- server/app/services/program/predicate/PredicateGenerator.java
- server/app/views/admin/programs/ProgramPredicateConfigureView.java
- server/app/views/questiontypes/MapQuestionFragment.html
- server/test/services/applicant/predicate/PredicateEvaluatorTest.java
The visibility and eligibility predicates for map questions got broken because of a switch to store the name and id of in the applicant data.
This handles that and also allows selecting ids rather than having to input them.
Continued development of map question.
1. Set `map_question_enabled=true` in `application.dev.conf`
2. Create a map question (can use one of Seattle's public endpoint to test: `https://earlylearning.powerappsportals.us/provider-list-ccap/`)
3. Make sure to fill out all the question settings.
Fixes #11443
> [Maps] Visibility and eligibility predicates for map question

- formatter/fmt
Adding `--silent` to `npx` calls in the formatter.
I'm tired of seeing excess noise when formatting. This will make `npx` proper stop outputting extra text, but leave the tool it is running (ex. prettier) to output as normal.
> Silent NPX

- bin/lib.sh
Supports a user setting `USE_PODMAN_FOR_CIVIFORM=1` or `USE_PODMAN_FOR_CIVIFORM=true` in their shell which will cause bin scripts to alias docker to podman.
Ran `USE_LOCAL_CIVIFORM=0 bin/pull-image`, `bin/run-dev`, and `bin/docker-reset`
> Support USE_PODMAN_FOR_CIVIFORM environment variable

- server/app/services/export/CsvColumnFactory.java
- server/app/services/export/QuestionJsonPresenter.java
- server/app/services/export/enums/QuestionTypeExternal.java
- server/test/services/export/AbstractExporterTest.java
- server/test/services/export/CsvExporterServiceTest.java
- server/test/services/export/JsonExporterServiceTest.java
Adds support for yes/no question in api/json/csv.
Fixes #11596
> Fix yes/no question in api

- .github/pull_request_template.md
Updating the manual accessibility test checklist item in the PR template to use the most current link to the wiki accessibility page. 
> Update pull request template for accessibility test checklist item
