civiform/civiform

.github/actions/test/action.yaml, .github/workflows/pr.yaml, .gitignore
This will create a "Check" on the PR, which will mean that every PR needs to pass tests.
=> Run tests on pr branch.

bin/fmt, universal-application-tool-0.0.1/app/Module.java, universal-application-tool-0.0.1/app/controllers/AsyncController.java, universal-application-tool-0.0.1/app/controllers/CountController.java, universal-application-tool-0.0.1/app/controllers/HomeController.java, universal-application-tool-0.0.1/app/filters/ExampleFilter.java, universal-application-tool-0.0.1/app/services/ApplicationTimer.java, universal-application-tool-0.0.1/app/services/AtomicCounter.java, universal-application-tool-0.0.1/app/services/Counter.java, universal-application-tool-0.0.1/project/plugins.sbt, universal-application-tool-0.0.1/test/BrowserTest.java, universal-application-tool-0.0.1/test/FunctionalTest.java, universal-application-tool-0.0.1/test/UnitTest.java
Adds google java formatter to the sbt project
Adds a command which runs the formatter locally.
Runs it for the first time so we can submit the linter in #16.
=> Formatter and formatting.

universal-application-tool-0.0.1/project/build.properties
Intellij was telling me to update this - looks like a minor version, may as well - it'll be automatically tested by the GHA integration on this PR.
=> Update sbt to newest version available.

.gitignore, universal-application-tool-0.0.1/app/assets/demo.ts, universal-application-tool-0.0.1/app/assets/javascripts/demo.ts, universal-application-tool-0.0.1/app/views/index.scala.html, universal-application-tool-0.0.1/build.sbt, universal-application-tool-0.0.1/conf/application.conf, universal-application-tool-0.0.1/project/plugins.sbt, universal-application-tool-0.0.1/tsconfig.json
Referred to https://www.scala-sbt.org/1.x/docs/Community-Plugins.html to choose which plugin to use.
Completes part one of #26 . Though I will wait to close that that issue completely until after adding an initial TypeScript file to see that things work.
=> Add plugin for TypeScript compilation support

universal-application-tool-0.0.1/app/models/Applicant.java, universal-application-tool-0.0.1/app/models/Program.java, universal-application-tool-0.0.1/app/models/Question.java, universal-application-tool-0.0.1/conf/evolutions/default/1.sql
We prefer to self-manage these!
=> Remove DDL generation to prevent issue with autocreating model tables

universal-application-tool-0.0.1/test/FunctionalTest.java, universal-application-tool-0.0.1/test/repository/ApplicantRepositoryTest.java, universal-application-tool-0.0.1/test/repository/ProgramRepositoryTest.java, universal-application-tool-0.0.1/test/repository/QuestionRepositoryTest.java, universal-application-tool-0.0.1/test/repository/WithPostgresContainer.java
[Merge timing issue] Update newest unit tests to mirror /app/ directory structure (see unit test best practices in README for more info)
=> Update newest unit tests to mirror /app/ structure

.github/pull_request_template.md
Modeled after https://github.com/go-sql-driver/mysql/blob/master/.github/PULL_REQUEST_TEMPLATE.md
Fixes #33
=> Create starter PR template

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Add issue templates (followed https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository)
Fixes #64
=> Add issue templates for features and bugs

infra/database.yaml
Save some money with a much cheaper DB during dev/test.
=> Get a cheaper database for dev.

infra/stack.yaml
Whoops, missed that comment in #70, and totally missed actually using the variable!  Sorry about that!
=> Followup to secrets change

infra/database.yaml, universal-application-tool-0.0.1/app/services/question/AddressQuestionDefinition.java, universal-application-tool-0.0.1/app/services/question/NameQuestionDefinition.java, universal-application-tool-0.0.1/app/services/question/QuestionDefinition.java, universal-application-tool-0.0.1/app/services/question/QuestionType.java, universal-application-tool-0.0.1/app/services/question/ScalarType.java, universal-application-tool-0.0.1/test/services/question/QuestionDefinitionTest.java
Added a basic QuestionDefinition with only getters, and a test.
Paired with: @AWBaumann
=> Add QuestionDefinition and test

universal-application-tool-0.0.1/app/services/question/InvalidPathException.java, universal-application-tool-0.0.1/app/services/question/PathType.java, universal-application-tool-0.0.1/app/services/question/QuestionService.java
Added QuestionService interface with basic get, set, and lookup abstract methods.
Eventually [Fixes] #99
=> Create QuestionService interface

universal-application-tool-0.0.1/app/services/program/BlockDefinition.java, universal-application-tool-0.0.1/app/services/program/ProgramService.java, universal-application-tool-0.0.1/test/services/program/BlockDefinitionTest.java, universal-application-tool-0.0.1/test/services/program/ProgramDefinitionTest.java
Adds a very basic interface for programs that only allows getting and create (basic).
Bug Fixes: add ID to BlockDefinition and fix failing test
Fixes #98
=> Create a basic Program Interface

infra/monitoring.yaml
Fix broken reference in monitoring stack.
=> Update ticketalerts reference in monitoring.yaml

infra/containers.yaml, infra/database.yaml, infra/load_balancer.yaml, infra/monitoring.yaml, infra/network.yaml, infra/secrets.yaml, infra/security_groups.yaml, infra/stack.yaml
One-liners saying what's in each file.
Looking for a review just to make sure the sentences make sense.
=> Minor documentation strings in each stack file.

.github/workflows/docker_build.yaml, .github/workflows/push.yaml, bin/build-and-push, bin/deploy-prod, infra/containers.yaml, infra/stack.yaml
Just run `bin/deploy-prod` - the ubuntu-18 environment runs it just fine, which is great and lucky for us.
=> Deploy to prod when we merge to main.

universal-application-tool-0.0.1/app/services/program/ProgramService.java
Added async methods to the program service for getting a single program and getting the list of programs.
These will be implemented in a future PR
=> Add async methods to ProgramService

README.md, universal-application-tool-0.0.1/app/views/ViewUtils.java
Add a section for technology overview of the UAT, with some extra information about views and using J2Html and utilities.
=> Add Technology overview README

README.md, universal-application-tool-0.0.1/app/controllers/J2HtmlDemoController.java, universal-application-tool-0.0.1/app/views/BaseHtmlView.java, universal-application-tool-0.0.1/app/views/J2HtmlDemo.java, universal-application-tool-0.0.1/app/views/ViewUtils.java, universal-application-tool-0.0.1/conf/application.conf, universal-application-tool-0.0.1/conf/routes, universal-application-tool-0.0.1/test/views/ViewUtilsTest.java
Demo shows how to attach a CSRF token to a form to successfully POST.
Paired with @bion
=> Create a working demo of a POST request with CSRF token

universal-application-tool-0.0.1/app/services/program/test/FakeProgramService.java, universal-application-tool-0.0.1/test/services/program/test/FakeProgramServiceTest.java
Implements a fake ProgramService for use in testing that just uses a map instead of the database
Want approval from any one reviewer
=> Create a fake ProgramService for testing

README.md
=> Add to testing guidelines in README

universal-application-tool-0.0.1/app/services/program/ProgramServiceImpl.java, universal-application-tool-0.0.1/app/views/BaseHtmlView.java, universal-application-tool-0.0.1/app/views/LoginForm.java, universal-application-tool-0.0.1/test/BrowserTest.java, universal-application-tool-0.0.1/test/controllers/HomeControllerAuthenticatedTest.java, universal-application-tool-0.0.1/test/views/BaseHtmlViewTest.java
Adds a unit test for an authenticated page (which overrides the security configuration so that prod and test are different).
Adds a browser test for the login page to show that submitting the form logs you in.
=> Testing (unit and browser) for basic authentication scheme.

universal-application-tool-0.0.1/test/repository/WithPostgresContainer.java
Identical to https://github.com/seattle-uat/universal-application-tool/pull/195 but with code formatted
=> Re-use application for tests in the same class

universal-application-tool-0.0.1/app/auth/GuestClient.java, universal-application-tool-0.0.1/app/controllers/HomeController.java, universal-application-tool-0.0.1/app/controllers/PostgresController.java, universal-application-tool-0.0.1/app/controllers/ProfileController.java, universal-application-tool-0.0.1/app/filters/LoggingFilter.java, universal-application-tool-0.0.1/app/repository/AmazonS3Client.java, universal-application-tool-0.0.1/app/repository/ApplicantRepository.java, universal-application-tool-0.0.1/app/repository/DatabaseExecutionContext.java, universal-application-tool-0.0.1/app/repository/PersonRepository.java, universal-application-tool-0.0.1/app/repository/ProgramRepository.java, universal-application-tool-0.0.1/app/repository/QuestionRepository.java, universal-application-tool-0.0.1/app/repository/StoredFileRepository.java, universal-application-tool-0.0.1/app/services/question/ReadOnlyQuestionServiceImpl.java
=> Add checkNotNull to all constructors

universal-application-tool-0.0.1/app/services/question/QuestionNotFoundException.java, universal-application-tool-0.0.1/app/services/question/ReadOnlyQuestionService.java, universal-application-tool-0.0.1/app/services/question/ReadOnlyQuestionServiceImpl.java, universal-application-tool-0.0.1/test/services/question/ReadOnlyQuestionServiceImplTest.java
Add and implement getQuestionDefinition(long id) to ReadOnlyQuestionService.
=> Add getQuestionDefinition(long) to ReadOnlyQuestionService.

universal-application-tool-0.0.1/app/services/program/ProgramService.java, universal-application-tool-0.0.1/app/services/program/ProgramServiceImpl.java, universal-application-tool-0.0.1/app/services/program/test/FakeProgramService.java, universal-application-tool-0.0.1/test/services/program/ProgramServiceImplTest.java, universal-application-tool-0.0.1/test/services/program/test/FakeProgramServiceTest.java
We'll want the ability to add a block with name, description and questions
=> Add a method to ProgramService to allow adding a block with questions

bin/fmt, formatter.Dockerfile
Also move bin/fmt to use an ECR image.
=> Don't format unnecessary files.

.github/workflows/pr.yaml, Dockerfile, universal-application-tool-0.0.1/app/auth/Roles.java, universal-application-tool-0.0.1/app/auth/UatProfileData.java, universal-application-tool-0.0.1/app/controllers/HomeController.java, universal-application-tool-0.0.1/app/models/EbeanServerConfigStartup.java, universal-application-tool-0.0.1/app/modules/MainModule.java, universal-application-tool-0.0.1/app/repository/AmazonS3Client.java, universal-application-tool-0.0.1/app/repository/PersonRepository.java, universal-application-tool-0.0.1/app/services/program/ProgramServiceImpl.java, universal-application-tool-0.0.1/app/services/question/QuestionDefinition.java, universal-application-tool-0.0.1/app/services/question/QuestionService.java, universal-application-tool-0.0.1/app/services/question/QuestionServiceImpl.java, universal-application-tool-0.0.1/app/services/question/ReadOnlyQuestionService.java, universal-application-tool-0.0.1/app/services/question/ReadOnlyQuestionServiceImpl.java, universal-application-tool-0.0.1/app/services/question/ScalarType.java, universal-application-tool-0.0.1/app/views/BaseHtmlView.java, universal-application-tool-0.0.1/app/views/ProfileView.java, universal-application-tool-0.0.1/build.sbt, universal-application-tool-0.0.1/conf/application.conf, universal-application-tool-0.0.1/test/app/BrowserTest.java, universal-application-tool-0.0.1/test/app/FunctionalTest.java, universal-application-tool-0.0.1/test/models/ApplicantTest.java, universal-application-tool-0.0.1/test/repository/StoredFileRepositoryTest.java, universal-application-tool-0.0.1/test/services/program/BlockDefinitionTest.java, universal-application-tool-0.0.1/test/services/question/QuestionServiceImplTest.java
=> Add ErrorProne to our compiler, and also fix all existing ErrorProne warnings and errors.

universal-application-tool-0.0.1/app/models/Question.java, universal-application-tool-0.0.1/app/services/question/AddressQuestionDefinition.java, universal-application-tool-0.0.1/app/services/question/NameQuestionDefinition.java, universal-application-tool-0.0.1/app/services/question/QuestionDefinition.java, universal-application-tool-0.0.1/app/services/question/QuestionDefinitionBuilder.java, universal-application-tool-0.0.1/app/services/question/ReadOnlyQuestionServiceImpl.java, universal-application-tool-0.0.1/app/services/question/TextQuestionDefinition.java, universal-application-tool-0.0.1/test/models/ProgramTest.java, universal-application-tool-0.0.1/test/models/QuestionTest.java, universal-application-tool-0.0.1/test/repository/QuestionRepositoryTest.java, universal-application-tool-0.0.1/test/services/applicant/ApplicantServiceImplTest.java, universal-application-tool-0.0.1/test/services/program/ProgramServiceImplTest.java, universal-application-tool-0.0.1/test/services/question/QuestionDefinitionTest.java, universal-application-tool-0.0.1/test/services/question/QuestionServiceImplTest.java, universal-application-tool-0.0.1/test/services/question/ReadOnlyQuestionServiceImplTest.java, universal-application-tool-0.0.1/test/support/ResourceFabricator.java
We want ebean to auto-generate question id for us.
=> do not manually set question id

universal-application-tool-0.0.1/app/models/Question.java, universal-application-tool-0.0.1/app/repository/QuestionRepository.java, universal-application-tool-0.0.1/app/services/question/QuestionServiceImpl.java, universal-application-tool-0.0.1/test/models/QuestionTest.java, universal-application-tool-0.0.1/test/repository/ApplicantRepositoryTest.java, universal-application-tool-0.0.1/test/repository/QuestionRepositoryTest.java, universal-application-tool-0.0.1/test/services/question/QuestionServiceImplTest.java
=> Add path validation for creating new questions

universal-application-tool-0.0.1/test/controllers/admin/AdminProgramBlocksControllerTest.java, universal-application-tool-0.0.1/test/controllers/admin/AdminProgramControllerTest.java, universal-application-tool-0.0.1/test/controllers/applicant/ApplicantProgramBlocksControllerTest.java, universal-application-tool-0.0.1/test/controllers/applicant/ApplicantProgramsControllerTest.java, universal-application-tool-0.0.1/test/repository/ProgramRepositoryTest.java, universal-application-tool-0.0.1/test/repository/QuestionRepositoryTest.java, universal-application-tool-0.0.1/test/repository/WithPostgresContainer.java, universal-application-tool-0.0.1/test/support/ResourceCreator.java, universal-application-tool-0.0.1/test/support/ResourceFabricator.java
Uses new `ResourceFabricator` methods in all tests
Fixes #234
=> Update ResourceFabricator and tests to use new methods

universal-application-tool-0.0.1/app/controllers/admin/AdminProgramBlocksController.java, universal-application-tool-0.0.1/app/services/program/ProgramService.java, universal-application-tool-0.0.1/app/services/program/ProgramServiceImpl.java, universal-application-tool-0.0.1/test/services/program/ProgramServiceImplTest.java
`addBlockToProgram(long)` adds an empty block to a program.
=> Add `addBlockToProgram(long)` to `ProgramService`

universal-application-tool-0.0.1/app/services/program/ProgramService.java, universal-application-tool-0.0.1/app/services/program/ProgramServiceImpl.java, universal-application-tool-0.0.1/test/services/program/ProgramServiceImplTest.java
Add ProgramService.deleteBlock method.
At least one.
=> Add ProgramService.deleteBlock method.

universal-application-tool-0.0.1/app/services/applicant/ApplicantQuestion.java, universal-application-tool-0.0.1/app/views/questiontypes/AddressQuestionRenderer.java, universal-application-tool-0.0.1/app/views/questiontypes/ApplicantQuestionRendererFactory.java
Implement the rendering logic for address questions
#277
=> Implement the address question renderer

Dockerfile, bin/run-test
We don't want to refetch dependencies every time we run the tests.
[Fixes]
=> compile and save dependencies in docker image

README.md, universal-application-tool-0.0.1/app/assets/stylesheets/styles.css, universal-application-tool-0.0.1/app/controllers/admin/AdminProgramBlocksController.java, universal-application-tool-0.0.1/app/controllers/admin/AdminProgramController.java, universal-application-tool-0.0.1/app/forms/BlockForm.java, universal-application-tool-0.0.1/app/forms/ProgramForm.java, universal-application-tool-0.0.1/app/services/program/BlockDefinition.java, universal-application-tool-0.0.1/app/services/program/ProgramDefinition.java, universal-application-tool-0.0.1/app/services/program/ProgramService.java, universal-application-tool-0.0.1/app/services/program/ProgramServiceImpl.java, universal-application-tool-0.0.1/app/views/admin/AdminLayout.java, universal-application-tool-0.0.1/app/views/admin/programs/ProgramBlockEditView.java, universal-application-tool-0.0.1/app/views/admin/programs/ProgramEditView.java, universal-application-tool-0.0.1/app/views/admin/programs/ProgramIndexView.java, universal-application-tool-0.0.1/app/views/admin/programs/ProgramNewOneView.java, universal-application-tool-0.0.1/conf/routes, universal-application-tool-0.0.1/test/app/BaseBrowserTest.java, universal-application-tool-0.0.1/test/app/ProgramAdministrationBrowserTest.java, universal-application-tool-0.0.1/test/controllers/admin/AdminProgramBlocksControllerTest.java, universal-application-tool-0.0.1/test/controllers/admin/AdminProgramControllerTest.java, universal-application-tool-0.0.1/test/services/program/ProgramDefinitionTest.java, universal-application-tool-0.0.1/test/services/program/ProgramServiceImplTest.java
=> Block edit view form

universal-application-tool-0.0.1/app/controllers/admin/QuestionController.java, universal-application-tool-0.0.1/app/forms/QuestionForm.java, universal-application-tool-0.0.1/app/repository/QuestionRepository.java, universal-application-tool-0.0.1/app/services/question/InvalidUpdateException.java, universal-application-tool-0.0.1/app/services/question/QuestionDefinition.java, universal-application-tool-0.0.1/app/services/question/QuestionService.java, universal-application-tool-0.0.1/app/services/question/QuestionServiceImpl.java, universal-application-tool-0.0.1/app/views/admin/questions/QuestionsListView.java, universal-application-tool-0.0.1/conf/logback.xml, universal-application-tool-0.0.1/conf/routes, universal-application-tool-0.0.1/test/controllers/admin/QuestionControllerTest.java, universal-application-tool-0.0.1/test/repository/QuestionRepositoryTest.java, universal-application-tool-0.0.1/test/services/question/QuestionServiceImplTest.java
- We update the existing question without changing its version. Path and id cannot be changed.
- handle any exceptions by surfacing them to users with flash
- disallow blank path
[Fixes] #103
=> Support editing existing questions

universal-application-tool-0.0.1/app/services/applicant/ApplicantQuestion.java, universal-application-tool-0.0.1/app/services/question/AddressQuestionDefinition.java, universal-application-tool-0.0.1/app/services/question/NameQuestionDefinition.java, universal-application-tool-0.0.1/app/services/question/QuestionDefinition.java, universal-application-tool-0.0.1/app/services/question/ReadOnlyQuestionServiceImpl.java, universal-application-tool-0.0.1/app/services/question/TextQuestionDefinition.java, universal-application-tool-0.0.1/test/services/question/QuestionDefinitionTest.java, universal-application-tool-0.0.1/test/services/question/ReadOnlyQuestionServiceImplTest.java
- Use named method for scalar paths
- Change semantics of getScalars to use full path as key
- Remove getFullyQualifiedScalars
=> Applicant question type

universal-application-tool-0.0.1/app/export/CsvExporter.java, universal-application-tool-0.0.1/app/export/Exporter.java, universal-application-tool-0.0.1/app/export/ExporterFactory.java, universal-application-tool-0.0.1/app/export/PdfExporter.java, universal-application-tool-0.0.1/app/services/program/Column.java, universal-application-tool-0.0.1/app/services/program/CsvExportConfig.java, universal-application-tool-0.0.1/app/services/program/ExportDefinition.java, universal-application-tool-0.0.1/app/services/program/PdfExportConfig.java, universal-application-tool-0.0.1/build.sbt, universal-application-tool-0.0.1/test/export/CsvExporterTest.java, universal-application-tool-0.0.1/test/export/PdfExporterTest.java, universal-application-tool-0.0.1/test/export/base.pdf
Fill in details about the generation of PDFs and CSVs, and add tests.
Related to #205 and #206.
=> Build logic to write PDFs and CSVs

universal-application-tool-0.0.1/app/auth/FakeAdminClient.java, universal-application-tool-0.0.1/app/auth/GuestClient.java, universal-application-tool-0.0.1/app/auth/UatProfile.java, universal-application-tool-0.0.1/app/controllers/HomeController.java, universal-application-tool-0.0.1/app/controllers/ProfileController.java, universal-application-tool-0.0.1/app/views/LoginForm.java, universal-application-tool-0.0.1/app/views/ProfileView.java, universal-application-tool-0.0.1/conf/routes, universal-application-tool-0.0.1/test/app/BaseBrowserTest.java, universal-application-tool-0.0.1/test/app/SecurityBrowserTest.java, universal-application-tool-0.0.1/test/controllers/HomeControllerAuthenticatedTest.java, universal-application-tool-0.0.1/test/controllers/HomeControllerTest.java
Added redirect logic to the landing page as follows:
- if you're not logged in, redirect to the login form
- if you're logged in as an admin, redirect to the admin programs index
- if you're not logged in as an admin, redirect to the applicant programs index
=> Landing page redirects

.github/workflows/push.yaml, bin/build-dev, bin/run-dev
This will mean we don't have to broadcast "make sure to update your container" every time it's needed.
=> Build the dev container on each merge, and pull it with run-dev.

universal-application-tool-0.0.1/app/views/admin/AdminLayout.java, universal-application-tool-0.0.1/app/views/admin/programs/ProgramIndexView.java, universal-application-tool-0.0.1/app/views/admin/questions/QuestionEditView.java, universal-application-tool-0.0.1/app/views/admin/questions/QuestionsListView.java, universal-application-tool-0.0.1/test/app/ProgramAdministrationBrowserTest.java
Add an admin nav header in the admin layout with anchors to questions, programs, and logout.
=> Add admin nav header.

infra/load_balancer.yaml
=> Fix health check url

universal-application-tool-0.0.1/app/assets/stylesheets/styles.css, universal-application-tool-0.0.1/app/views/BaseStyles.java, universal-application-tool-0.0.1/app/views/admin/AdminLayout.java, universal-application-tool-0.0.1/app/views/components/FieldWithLabel.java, universal-application-tool-0.0.1/test/app/ProgramAdministrationBrowserTest.java
- Added background and foreground colors to nav bar.
- Made nav bar fixed.
- Made main content scrollable.
=> Add basic styling and layout to the admin pages

universal-application-tool-0.0.1/app/services/program/BlockDefinition.java, universal-application-tool-0.0.1/app/services/program/ProgramDefinition.java, universal-application-tool-0.0.1/app/services/program/ProgramQuestionDefinition.java
=> Remove unused json annotations, and add in other places for clarity

universal-application-tool-0.0.1/app/auth/AdfsProfileAdapter.java, universal-application-tool-0.0.1/app/auth/IdcsProfileAdapter.java, universal-application-tool-0.0.1/app/auth/ProfileFactory.java, universal-application-tool-0.0.1/app/auth/UatProfileAdapter.java, universal-application-tool-0.0.1/app/auth/UatProfileData.java, universal-application-tool-0.0.1/app/modules/SecurityModule.java, universal-application-tool-0.0.1/app/repository/ApplicantRepository.java, universal-application-tool-0.0.1/app/services/applicant/ApplicantData.java, universal-application-tool-0.0.1/conf/evolutions/default/6.sql, universal-application-tool-0.0.1/conf/logback.xml, universal-application-tool-0.0.1/test/app/BaseBrowserTest.java, universal-application-tool-0.0.1/test/app/SecurityBrowserTest.java, universal-application-tool-0.0.1/test/auth/ProfileMergeTest.java, universal-application-tool-0.0.1/test/models/ApplicantTest.java, universal-application-tool-0.0.1/test/repository/WithPostgresContainer.java
Follow-up to #383.  Fixes #385.
=> Ensure that it is possible to log back in - to re-access an old account.

universal-application-tool-0.0.1/app/controllers/applicant/ApplicantProgramBlocksController.java, universal-application-tool-0.0.1/test/app/ApplicantProgramBrowserTest.java
These changes were meant to make it into #382 , but I accidentally merged without pushing up these changes.
=> Slightly improve tests and bad request responses based on feedback on previous PR

universal-application-tool-0.0.1/app/services/applicant/ApplicantData.java, universal-application-tool-0.0.1/test/services/applicant/ApplicantDataTest.java
Impelemented `readInteger` in ApplicantData and added test for method
Closes #491
=> Implement read integer in applicant data

.gitattributes
issue501
Updates default line endings to be LF
[Fixes] #501
=> Add git attributes file to set default line endings

universal-application-tool-0.0.1/app/services/ErrorAnd.java
Changed the scope modifiers for ErrorAnd class constructor
[Fixes] #443
=> Issue #443 constructor scope changes

universal-application-tool-0.0.1/app/views/BaseHtmlView.java, universal-application-tool-0.0.1/app/views/admin/AdminLayout.java, universal-application-tool-0.0.1/app/views/admin/programs/ProgramBlockEditView.java, universal-application-tool-0.0.1/app/views/admin/programs/ProgramEditView.java, universal-application-tool-0.0.1/app/views/admin/programs/ProgramIndexView.java, universal-application-tool-0.0.1/app/views/admin/questions/QuestionEditView.java, universal-application-tool-0.0.1/app/views/admin/questions/QuestionsListView.java, universal-application-tool-0.0.1/app/views/components/FieldWithLabel.java, universal-application-tool-0.0.1/app/views/components/LinkElement.java, universal-application-tool-0.0.1/app/views/components/QuestionBank.java, universal-application-tool-0.0.1/app/views/dev/DatabaseSeedView.java, universal-application-tool-0.0.1/app/views/style/BaseStyles.java, universal-application-tool-0.0.1/app/views/style/ReferenceClasses.java, universal-application-tool-0.0.1/app/views/style/ReferenceStyles.java, universal-application-tool-0.0.1/app/views/style/StyleUtils.java, universal-application-tool-0.0.1/app/views/style/Styles.java, universal-application-tool-0.0.1/test/app/BaseBrowserTest.java, universal-application-tool-0.0.1/test/views/style/StyleUtilsTest.java
=> Make style/class usage smarter

bin/build-and-push, bin/check-cfn-change, bin/deploy-prod, docker-compose.yml, infra/containers.yaml, infra/database.yaml, infra/filestorage.yaml, infra/load_balancer.yaml, infra/monitoring.yaml, infra/network.yaml, infra/prod-simulator-compose.yml, infra/security_groups.yaml, infra/stack.yaml
Make AWS resource names more readable.
Fixes #521 
#465
=> Add human readable names to AWS resources

universal-application-tool-0.0.1/app/assets/javascripts/main.js, universal-application-tool-0.0.1/app/assets/javascripts/main.ts, universal-application-tool-0.0.1/app/controllers/admin/QuestionController.java, universal-application-tool-0.0.1/app/services/question/QuestionType.java, universal-application-tool-0.0.1/app/views/BaseHtmlView.java, universal-application-tool-0.0.1/app/views/ViewUtils.java, universal-application-tool-0.0.1/app/views/admin/AdminLayout.java, universal-application-tool-0.0.1/app/views/admin/questions/QuestionEditView.java, universal-application-tool-0.0.1/app/views/admin/questions/QuestionsListView.java, universal-application-tool-0.0.1/app/views/components/Icons.java, universal-application-tool-0.0.1/app/views/components/LinkElement.java, universal-application-tool-0.0.1/conf/routes, universal-application-tool-0.0.1/test/app/BaseBrowserTest.java, universal-application-tool-0.0.1/test/controllers/admin/QuestionControllerTest.java
Added a dropdown menu button so that we can specify QuestionType before the user gets to the new question page. This will allow us to include QuestionType specific validation and configuration options.
Mock @ https://play.tailwindcss.com/RXrG7TohJW
https://user-images.githubusercontent.com/77127160/111602339-7a30f000-8790-11eb-9420-c54015d50c63.mov
=> Add new question type button

universal-application-tool-0.0.1/app/controllers/admin/AdminApplicationController.java, universal-application-tool-0.0.1/app/repository/ApplicationRepository.java, universal-application-tool-0.0.1/app/services/applicant/ApplicantService.java, universal-application-tool-0.0.1/app/services/applicant/ApplicantServiceImpl.java, universal-application-tool-0.0.1/app/views/admin/programs/ProgramApplicationListView.java, universal-application-tool-0.0.1/app/views/admin/programs/ProgramApplicationView.java, universal-application-tool-0.0.1/app/views/style/ReferenceClasses.java, universal-application-tool-0.0.1/conf/routes, universal-application-tool-0.0.1/test/app/ApplicationReviewBrowserTest.java
Follow-on to #531.  Fixes #192 by displaying applicant's answers to an admin in an HTML page.
=> Display answers to admins in HTML page.

universal-application-tool-0.0.1/app/views/components/FieldWithLabel.java
=> Fix bug (but doesn't update tests because they weren't breaking 👎 )

.github/workflows/pr.yaml, bin/build-dev, bin/fmt, bin/npm, bin/run-dev, bin/run-test, bin/sbt, docker-compose.yml, infra/prod-simulator-compose.yml, prod.Dockerfile
Rename docker image and ECR repository names.
#465
=> Rename docker image from UAT to CiviForm

universal-application-tool-0.0.1/app/views/admin/programs/ProgramNewOneView.java
Tiny nit, no impact to functioning.
=> Use correct name for redirect.

universal-application-tool-0.0.1/app/assets/javascripts/main.ts
=> Format typescript files

test-support/test_oidc_provider.js, universal-application-tool-0.0.1/app/views/LoginForm.java, universal-application-tool-0.0.1/test/app/SecurityBrowserTest.java
Just some additional cleanups on top of #531.
=> Link to IDCS / ADFS logins from login page, test name extraction.

.github/workflows/pr.yaml, bin/pull-image, bin/run-browser-tests-ci
=> Run browser tests in CI

infra/containers.yaml
Add environment variables to hook 'prod' up to city idcs and adfs.
=> Add IDCS / ADFS client ids and secrets to our semi-prod env.

universal-application-tool-0.0.1/app/controllers/admin/AdminProgramController.java, universal-application-tool-0.0.1/app/models/Program.java, universal-application-tool-0.0.1/app/repository/ProgramRepository.java, universal-application-tool-0.0.1/app/services/program/ProgramDefinition.java, universal-application-tool-0.0.1/app/services/program/ProgramService.java, universal-application-tool-0.0.1/app/services/program/ProgramServiceImpl.java, universal-application-tool-0.0.1/app/views/admin/programs/ProgramIndexView.java, universal-application-tool-0.0.1/app/views/components/LinkElement.java, universal-application-tool-0.0.1/conf/routes, universal-application-tool-0.0.1/test/controllers/admin/AdminProgramControllerTest.java, universal-application-tool-0.0.1/test/export/CsvExporterTest.java, universal-application-tool-0.0.1/test/export/PdfExporterTest.java, universal-application-tool-0.0.1/test/models/ProgramTest.java, universal-application-tool-0.0.1/test/repository/ProgramRepositoryTest.java, universal-application-tool-0.0.1/test/services/applicant/ReadOnlyApplicantProgramServiceImplTest.java, universal-application-tool-0.0.1/test/services/program/ProgramDefinitionTest.java, universal-application-tool-0.0.1/test/services/program/ProgramServiceImplTest.java, universal-application-tool-0.0.1/test/support/ProgramBuilder.java
- Adds `lifecycleStage` to `ProgramDefinition`.
- Adds `publishProgram` and `newDraftFromExistingProgram` to the service - and `publishProgram` to the repository.
- Adds buttons in the UI for new-from-existing and publish, conditional on correct states.
- disables editing for published programs
Related to #508.
=> Program side of form system versioning

universal-application-tool-0.0.1/app/services/question/AddressQuestionDefinition.java, universal-application-tool-0.0.1/app/services/question/NameQuestionDefinition.java, universal-application-tool-0.0.1/app/services/question/NumberQuestionDefinition.java, universal-application-tool-0.0.1/app/services/question/QuestionDefinition.java, universal-application-tool-0.0.1/app/services/question/TextQuestionDefinition.java
=> Refactor metadata paths into QuestionDefinition.

universal-application-tool-0.0.1/app/controllers/admin/AdminProgramBlocksController.java, universal-application-tool-0.0.1/app/services/applicant/ApplicantServiceImpl.java, universal-application-tool-0.0.1/app/services/program/ProgramDefinition.java, universal-application-tool-0.0.1/app/services/program/ProgramNeedsABlockException.java, universal-application-tool-0.0.1/app/services/program/ProgramServiceImpl.java, universal-application-tool-0.0.1/test/services/program/ProgramServiceImplTest.java
Refactor logic finding block definitions in a program definition into `ProgramDefinition.java`.
=> Refactor program definition

README.md
The wiki was recently reorganized. This change updates the README to refer to the new links.
=> Update README with new wiki links

infra/containers.yaml, infra/load_balancer.yaml, infra/stack.yaml, universal-application-tool-0.0.1/app/modules/SecurityModule.java, universal-application-tool-0.0.1/conf/application.conf, universal-application-tool-0.0.1/test/support/TestConstants.java
Add HTTPS.  Add domain name and DNS record.
Fixes #555.
=> HTTPS / Domain name / DNS record

bin/localstack/mk-s3, bin/localstack/purge-s3
When creating s3 bucket with localstack, use docker image if AWS CLI is not installed.
=> Run AWS cli in docker container if not installed

universal-application-tool-0.0.1/app/assets/javascripts/main.ts, universal-application-tool-0.0.1/app/views/BaseHtmlLayout.java, universal-application-tool-0.0.1/app/views/admin/AdminLayout.java, universal-application-tool-0.0.1/app/views/applicant/ApplicantLayout.java, universal-application-tool-0.0.1/app/views/components/Icons.java, universal-application-tool-0.0.1/app/views/style/Styles.java
Show the demo warning on every page and make it dismissible. 
#555
=> Create dismissible warning for demo site.

browser-test/bin/truncate_tables.sh
Don't set BASE_URL so psql within docker container connects to correct destination
=> Fix docker command for local browser tests

bin/localstack/mk-s3, bin/localstack/purge-s3
Make sure to run `pwd` in the right dir.
=> Fix localstack command take 2

universal-application-tool-0.0.1/app/controllers/applicant/ApplicantProgramBlocksController.java, universal-application-tool-0.0.1/app/services/applicant/ApplicantService.java, universal-application-tool-0.0.1/app/services/applicant/ApplicantServiceImpl.java, universal-application-tool-0.0.1/app/services/applicant/Block.java, universal-application-tool-0.0.1/app/services/applicant/ReadOnlyApplicantProgramService.java, universal-application-tool-0.0.1/app/services/applicant/ReadOnlyApplicantProgramServiceImpl.java, universal-application-tool-0.0.1/app/services/program/ProgramBlockNotFoundException.java, universal-application-tool-0.0.1/app/services/program/ProgramDefinition.java, universal-application-tool-0.0.1/conf/routes, universal-application-tool-0.0.1/test/controllers/applicant/ApplicantProgramBlocksControllerTest.java, universal-application-tool-0.0.1/test/controllers/applicant/ApplicantProgramsControllerTest.java, universal-application-tool-0.0.1/test/services/applicant/ApplicantServiceImplTest.java, universal-application-tool-0.0.1/test/services/applicant/BlockTest.java, universal-application-tool-0.0.1/test/services/applicant/ReadOnlyApplicantProgramServiceImplTest.java
=> Convert block IDs to strings

universal-application-tool-0.0.1/app/services/program/BlockDefinition.java, universal-application-tool-0.0.1/app/services/question/QuestionDefinitionBuilder.java, universal-application-tool-0.0.1/app/services/question/RepeaterQuestionDefinition.java, universal-application-tool-0.0.1/test/services/program/BlockDefinitionTest.java
=> Repeated block definitions

.github/workflows/pr.yaml
Should help with https://civiform.slack.com/archives/C01QKN2UNMA/p1617648040264500?thread_ts=1617475235.256900&cid=C01QKN2UNMA.
=> Print docker-compose logs if we fail in pr.yaml.

universal-application-tool-0.0.1/conf/evolutions/default/9.sql
This is to fix columns in db that have null lifecycle_stage.
=> Set all legacy entities' lifecycle_stage to 'active'

universal-application-tool-0.0.1/app/services/Path.java, universal-application-tool-0.0.1/test/services/PathTest.java
Added unit testing for pathJoin & fixed path.join segments
=> Added unit testing for pathJoin & fixed path.join segments

universal-application-tool-0.0.1/conf/evolutions/default/12.sql
Retrofit db column for existing programs.
=> Set existing programs to have empty export

browser-test/src/admin_program_creation.test.ts, browser-test/src/landing_page.test.ts, browser-test/src/other_page.test.ts, browser-test/src/support/admin_programs.ts, browser-test/src/support/index.ts
- Close browser after test
- Compare label string case insensitively when their style change case
- Click the right button to add questions to a program
- Fix a bug in awaiting
=> Deflake browser tests

.github/workflows/push.yaml, bin/check-cfn-change, bin/deploy-staging, infra/containers.yaml, infra/database.yaml, infra/filestorage.yaml, infra/load_balancer.yaml, infra/network.yaml, infra/secrets.yaml, infra/security_groups.yaml, infra/stack.yaml
Change names to avoid conflicts, swap the URLs around a bit.  :)
Note: the staging logins aren't going to work yet - I have meetings upcoming to get those working.
=> Create staging environment, separate from prod environment.

universal-application-tool-0.0.1/app/auth/FakeAdminClient.java, universal-application-tool-0.0.1/app/modules/SecurityModule.java, universal-application-tool-0.0.1/app/views/LoginForm.java
This enables the admin button in staging.
=> Enable the admin button in staging (for probers, when we have them).

.github/workflows/cron.yaml, bin/deploy-prod, bin/run-prober, browser-test/package.json, infra/containers.yaml
This will run the tests that are prober-compatible (idempotent / can run even if we don't truncate the database).
=> Add prober-compatible tests.

.github/workflows/cron.yaml
=> Allow manual triggering of probe-and-deploy.

.github/workflows/cron.yaml
=> Fix prober config: Need secret key.

universal-application-tool-0.0.1/app/services/applicant/ApplicantQuestion.java, universal-application-tool-0.0.1/app/views/questiontypes/CheckboxQuestionRenderer.java, universal-application-tool-0.0.1/test/views/questiontypes/CheckboxQuestionRendererTest.java
We need the format to be `path.selection[]`, not `path.selection.[]`, which is what I accidentally did with my last change
=> Fix input label name for checkboxes

universal-application-tool-0.0.1/app/controllers/dev/DatabaseSeedController.java, universal-application-tool-0.0.1/app/controllers/dev/DevController.java, universal-application-tool-0.0.1/app/controllers/dev/FileUploadController.java
Allow file upload to be tested with a real S3 bucket.
=> Enable dev controllers in staging

bin/build-and-push, bin/check-cfn-change
The stack is recently renamed to civiform-staging
=> Push to civiform-staging on merge

universal-application-tool-0.0.1/test/controllers/HomeControllerTest.java, universal-application-tool-0.0.1/test/services/export/PdfExporterTest.java
=> Remove all wildcard imports

.github/workflows/cron.yaml, bin/run-prober, browser-test/jest.config.js, browser-test/src/delete_database.ts, browser-test/src/support/index.ts, universal-application-tool-0.0.1/app/controllers/dev/DatabaseSeedController.java, universal-application-tool-0.0.1/app/views/dev/DatabaseSeedView.java
Make the prober empty the database then run all the tests, instead of just the no-op ones.
Make the prober run at predictable times.
=> Prober improvements

universal-application-tool-0.0.1/app/controllers/admin/AdminProgramBlocksController.java, universal-application-tool-0.0.1/app/services/question/ReadOnlyQuestionService.java, universal-application-tool-0.0.1/app/services/question/ReadOnlyQuestionServiceImpl.java, universal-application-tool-0.0.1/test/controllers/admin/AdminProgramBlocksControllerTest.java, universal-application-tool-0.0.1/test/services/question/ReadOnlyQuestionServiceImplTest.java
Instead of putting all the questions in the block editor, use only the most recent version of every question.
=> Only show up-to-date version of questions in editor.

browser-test/src/support/admin_questions.ts, universal-application-tool-0.0.1/app/views/admin/questions/QuestionsListView.java
Allow viewing a published question
=> Allow viewing a published question

bin/dev-psql, browser-test/browser-test-compose.yml
- Use different container names for dev and browser test env
- Fix a dev psql script
=> Avoid dev env and browser test env to conflict

universal-application-tool-0.0.1/app/repository/ProgramRepository.java, universal-application-tool-0.0.1/app/services/program/ProgramServiceImpl.java, universal-application-tool-0.0.1/test/services/program/ProgramServiceImplTest.java
Now we make sure we don't have multiple drafts by updating and returning the old draft if we accidentally do!
=> Ensure we cannot have multiple drafts of the same program

universal-application-tool-0.0.1/app/services/question/ReadOnlyQuestionService.java, universal-application-tool-0.0.1/app/services/question/ReadOnlyQuestionServiceImpl.java, universal-application-tool-0.0.1/test/services/question/ReadOnlyQuestionServiceImplTest.java, universal-application-tool-0.0.1/test/support/TestQuestionBank.java
Add a method to `ReadOnlyQuestionService` that constructs a `Path` based on a repeater question id, and a `String name` that is formatted.
=> Add `ReadOnlyQuestionService.makePath`.

browser-test/src/support/admin_programs.ts, browser-test/src/support/admin_questions.ts, universal-application-tool-0.0.1/app/views/admin/programs/ProgramApplicationListView.java, universal-application-tool-0.0.1/app/views/admin/programs/ProgramApplicationView.java, universal-application-tool-0.0.1/app/views/admin/programs/ProgramIndexView.java, universal-application-tool-0.0.1/app/views/admin/questions/QuestionsListView.java, universal-application-tool-0.0.1/app/views/style/ReferenceClasses.java
- Add reference classes for browser test
- Also fix a bug in selector
=> Add reference classes for browser test

universal-application-tool-0.0.1/app/models/Program.java
Default block 1 has no description, but a description is required for an update, so now it has a default description.
=> Automatic initial block gets a description.

browser-test/src/admin_program_creation.test.ts, browser-test/src/question_lifecycle.test.ts, universal-application-tool-0.0.1/app/assets/javascripts/preview.ts, universal-application-tool-0.0.1/app/views/BaseHtmlLayout.java, universal-application-tool-0.0.1/app/views/admin/questions/QuestionEditView.java
During usability testing, a suggestion was given that the question preview should update to based on user input. This is something that I wanted to do but wasn't currently in the scope. After hearing potential end users mention it, I decided to quickly add the functionality.
=> Update question previews

universal-application-tool-0.0.1/app/controllers/admin/QuestionController.java
* Refactor some `try`/`catch` blocks
* Make bad request messages more consistent for the same exceptions
=> Clean up exceptions and `badRequest` results in `QuestionController`

browser-test/package.json, browser-test/src/admin_program_creation.test.ts, browser-test/src/application_review.test.ts, browser-test/src/support/admin_questions.ts, browser-test/src/support/applicant_questions.ts, universal-application-tool-0.0.1/app/controllers/admin/QuestionController.java, universal-application-tool-0.0.1/app/forms/FileUploadQuestionForm.java, universal-application-tool-0.0.1/app/services/applicant/question/ApplicantQuestion.java, universal-application-tool-0.0.1/app/services/applicant/question/FileUploadQuestion.java, universal-application-tool-0.0.1/app/services/question/types/FileUploadQuestionDefinition.java, universal-application-tool-0.0.1/app/services/question/types/QuestionDefinitionBuilder.java, universal-application-tool-0.0.1/app/services/question/types/QuestionType.java, universal-application-tool-0.0.1/app/views/admin/questions/QuestionConfig.java, universal-application-tool-0.0.1/app/views/admin/questions/QuestionEditView.java, universal-application-tool-0.0.1/app/views/components/Icons.java, universal-application-tool-0.0.1/app/views/questiontypes/ApplicantQuestionRendererFactory.java, universal-application-tool-0.0.1/app/views/questiontypes/FileUploadQuestionRenderer.java, universal-application-tool-0.0.1/test/forms/FileUploadQuestionFormTest.java, universal-application-tool-0.0.1/test/services/applicant/question/ApplicantQuestionTest.java, universal-application-tool-0.0.1/test/services/applicant/question/FileUploadQuestionTest.java, universal-application-tool-0.0.1/test/views/admin/question/QuestionConfigTest.java, universal-application-tool-0.0.1/test/views/questiontypes/ApplicantQuestionRendererFactoryTest.java
- Add fileupload question definition and update builder
- Add fileupload question and update applicant question
- Add fileupload question form and renderer and update controller and views
- For now, use a text input as dummy answer
Work toward #404
=> Add file upload question type

universal-application-tool-0.0.1/app/services/question/types/QuestionDefinition.java
This is causing error code 7jebcdo0p
=> Ensure that question help text can be accessed by IDCS users as well.

universal-application-tool-0.0.1/app/controllers/dev/DatabaseSeedController.java, universal-application-tool-0.0.1/app/services/program/ProgramService.java, universal-application-tool-0.0.1/app/services/program/ProgramServiceImpl.java, universal-application-tool-0.0.1/test/services/applicant/ApplicantServiceImplTest.java, universal-application-tool-0.0.1/test/services/program/ProgramServiceImplTest.java
Deleted unnecessary `ProgramService#addBlockToProgram` methods.
We only need to add empty blocks to programs. Everything else was just used for testing or for /dev/seed, but /dev/seed works without those methods.
=> Delete extra ProgramService#addBlockToProgram methods.

universal-application-tool-0.0.1/app/controllers/admin/QuestionController.java, universal-application-tool-0.0.1/app/forms/QuestionFormBuilder.java, universal-application-tool-0.0.1/app/views/admin/questions/QuestionEditView.java
Add a question form builder so that we have one place to update when we create a new question form type.
=> Add question form builder

browser-test/src/support/index.ts, universal-application-tool-0.0.1/app/views/applicant/ApplicantLayout.java, universal-application-tool-0.0.1/app/views/applicant/ProgramIndexView.java
- Make Navigation bar to be shared with all applicant pages
- Add a logout button for applicants
=> Add a logout button for applicant pages

universal-application-tool-0.0.1/app/filters/HSTSFilter.java, universal-application-tool-0.0.1/conf/application.conf, universal-application-tool-0.0.1/conf/application.dev.conf
Adding HSTS via a filter in the application.
Addresses point 1 of https://github.com/seattle-uat/civiform/issues/837.
=> Add HSTS to production only.

infra/load_balancer.yaml
Disable insecure ciphers, disable TLS 1.0.
Combined with #872, fixes #837.
=> Use the good ciphers and not the bad ones

.github/workflows/cron.yaml, bin/run-prober, browser-test/src/application_csv_download.test.ts, browser-test/src/application_review.test.ts, browser-test/src/support/index.ts, universal-application-tool-0.0.1/app/controllers/dev/DatabaseSeedController.java
Log into the test IDCS account in staging - while maintaining code compatibility for dev.
=> Allow us to log in to the test IDCS account in staging.

universal-application-tool-0.0.1/app/controllers/dev/DatabaseSeedController.java, universal-application-tool-0.0.1/app/services/program/ActiveAndDraftPrograms.java, universal-application-tool-0.0.1/app/services/program/ProgramDefinition.java, universal-application-tool-0.0.1/app/views/dev/DatabaseSeedView.java
- Only show current draft and active programs in dev seed controller.
- Ignore getSupportedLocales field because it cannot be serialized without further loading question definitions.
=> Dev seed to only include current programs

universal-application-tool-0.0.1/app/services/program/ActiveAndDraftPrograms.java, universal-application-tool-0.0.1/app/services/program/ProgramDefinition.java, universal-application-tool-0.0.1/app/services/program/ProgramServiceImpl.java
Hydrate the program definition with questions for easy of use
=> Hydrate program definitions in ActiveAndDraftPrograms

universal-application-tool-0.0.1/app/auth/AdfsProfileAdapter.java, universal-application-tool-0.0.1/app/auth/IdcsProfileAdapter.java, universal-application-tool-0.0.1/app/auth/UatProfileAdapter.java, universal-application-tool-0.0.1/app/models/Account.java, universal-application-tool-0.0.1/app/models/TrustedIntermediaryGroup.java, universal-application-tool-0.0.1/conf/evolutions/default/18.sql, universal-application-tool-0.0.1/test/models/TrustedIntermediaryGroupTest.java
Add the model for a TI organization and assign roles correctly on login.
Relates to #251.
=> Add TI organizations and the models for TIs.

browser-test/src/support/index.ts
Assert page by URL, rather than elements that may or may not be there immediately
Ran @kendrickt's script and it passed 10/10 times
=> Improve language select in browser tests

universal-application-tool-0.0.1/app/controllers/admin/AdminProgramBlockQuestionsController.java, universal-application-tool-0.0.1/app/controllers/admin/AdminProgramBlocksController.java, universal-application-tool-0.0.1/app/services/applicant/ApplicantServiceImpl.java, universal-application-tool-0.0.1/app/services/program/ProgramBlockDefinitionNotFoundException.java, universal-application-tool-0.0.1/app/services/program/ProgramBlockNotFoundException.java, universal-application-tool-0.0.1/app/services/program/ProgramDefinition.java, universal-application-tool-0.0.1/app/services/program/ProgramService.java, universal-application-tool-0.0.1/app/services/program/ProgramServiceImpl.java, universal-application-tool-0.0.1/app/views/components/QuestionBank.java, universal-application-tool-0.0.1/test/services/applicant/ApplicantServiceImplTest.java, universal-application-tool-0.0.1/test/services/program/ProgramServiceImplTest.java, universal-application-tool-0.0.1/test/support/ResourceCreator.java
Create a new `ProgramBlockDefinitionNotFoundException` and use that instead of `ProgramBlockNotFoundException`.
Also deleted unused things in `ResourceCreator`.
=> Disambiguate between `ProgramBlockNotFoundException` and `ProgramBlockDefinitionNotFoundException`

universal-application-tool-0.0.1/app/services/applicant/question/ApplicantQuestion.java, universal-application-tool-0.0.1/app/views/questiontypes/ApplicantQuestionRendererFactory.java, universal-application-tool-0.0.1/test/services/applicant/BlockTest.java, universal-application-tool-0.0.1/test/services/applicant/question/AddressQuestionTest.java, universal-application-tool-0.0.1/test/services/applicant/question/ApplicantQuestionTest.java, universal-application-tool-0.0.1/test/services/applicant/question/FileUploadQuestionTest.java, universal-application-tool-0.0.1/test/services/applicant/question/MultiSelectQuestionTest.java, universal-application-tool-0.0.1/test/services/applicant/question/NameQuestionTest.java, universal-application-tool-0.0.1/test/services/applicant/question/NumberQuestionTest.java, universal-application-tool-0.0.1/test/services/applicant/question/SingleSelectQuestionTest.java, universal-application-tool-0.0.1/test/services/applicant/question/TextQuestionTest.java, universal-application-tool-0.0.1/test/views/questiontypes/CheckboxQuestionRendererTest.java, universal-application-tool-0.0.1/test/views/questiontypes/RadioButtonQuestionRendererTest.java, universal-application-tool-0.0.1/test/views/questiontypes/TextQuestionRendererTest.java
Delete the old `ApplicantQuestion` constructor.
Works toward #783
=> Delete old applicant question constructor

universal-application-tool-0.0.1/app/auth/AdfsProfileAdapter.java, universal-application-tool-0.0.1/app/auth/IdcsProfileAdapter.java, universal-application-tool-0.0.1/app/auth/UatProfileAdapter.java, universal-application-tool-0.0.1/app/controllers/admin/TrustedIntermediaryManagementController.java, universal-application-tool-0.0.1/app/controllers/applicant/ApplicantInformationController.java, universal-application-tool-0.0.1/app/modules/SecurityModule.java, universal-application-tool-0.0.1/app/repository/ApplicationRepository.java, universal-application-tool-0.0.1/app/repository/UserRepository.java, universal-application-tool-0.0.1/app/services/applicant/ApplicantServiceImpl.java, universal-application-tool-0.0.1/app/views/admin/ti/TrustedIntermediaryGroupListView.java, universal-application-tool-0.0.1/conf/routes, universal-application-tool-0.0.1/test/app/SecurityBrowserTest.java, universal-application-tool-0.0.1/test/auth/ProfileMergeTest.java, universal-application-tool-0.0.1/test/controllers/applicant/ApplicantInformationControllerTest.java, universal-application-tool-0.0.1/test/models/ApplicantTest.java, universal-application-tool-0.0.1/test/repository/UserRepositoryTest.java, universal-application-tool-0.0.1/test/services/applicant/ApplicantServiceImplTest.java
Add view - which doesn't do anything yet - to display the TI organizations to admins.  Next up will be adding a button to add a new group.  :)
Related to #251.
=> Add page displaying TI groups.

universal-application-tool-0.0.1/app/services/applicant/ApplicantData.java, universal-application-tool-0.0.1/app/services/applicant/ApplicantService.java, universal-application-tool-0.0.1/app/services/applicant/ApplicantServiceImpl.java, universal-application-tool-0.0.1/app/services/applicant/question/ApplicantQuestion.java, universal-application-tool-0.0.1/app/services/question/types/QuestionDefinition.java, universal-application-tool-0.0.1/app/views/admin/programs/ProgramApplicationListView.java, universal-application-tool-0.0.1/app/views/admin/programs/ProgramApplicationView.java, universal-application-tool-0.0.1/test/services/question/types/QuestionDefinitionTest.java
Trying to get rid of all scalars from `QuestionDefinition`. It remains to be used in CSV export.
Also move applicant name method out of `ApplicantService` into ApplicantData.
Works toward #783
=> Use Block and ApplicantQuestion in ProgramApplicationView.

universal-application-tool-0.0.1/app/views/admin/programs/ProgramTranslationView.java
Add labels to the translation forms
=> Add labels to forms.

universal-application-tool-0.0.1/app/repository/AmazonS3Client.java
The credentials rotate so we get fresh ones every time.
=> Use fresh credentials for signing requests

universal-application-tool-0.0.1/test/support/TestQuestionBank.java
Change atomic counter to be non static.
=> Minor fix to test question bank

universal-application-tool-0.0.1/conf/evolutions/default/18.sql
I changed the name of this table *almost* everywhere.  🤦 
This might be a problem since staging and prod might try (and refuse) to apply this down statement, due to the "never delete anything" posture we adopted a few weeks ago.  We'll see!
=> pluralize table so it properly deletes.

browser-test/src/dev_file_upload.test.ts
Make sure we click the right link.
=> Fix file upload probe

universal-application-tool-0.0.1/app/services/program/ActiveAndDraftPrograms.java
Yet another small change to make errors a bit more readable.
=> Use checkNotNull in ActiveAndDraftPrograms constructor.

universal-application-tool-0.0.1/app/auth/UatProfileAdapter.java, universal-application-tool-0.0.1/app/repository/UserRepository.java
Make sure we merge applicants into the existing account, identified by email.
=> Ensure we merge guest account to existing account

browser-test/src/support/admin_ti_groups.ts, browser-test/src/support/index.ts, browser-test/src/ti_group.test.ts, universal-application-tool-0.0.1/app/controllers/admin/TrustedIntermediaryManagementController.java, universal-application-tool-0.0.1/app/controllers/dev/DatabaseSeedController.java, universal-application-tool-0.0.1/app/forms/CreateTrustedIntermediaryGroupForm.java, universal-application-tool-0.0.1/app/repository/UserRepository.java, universal-application-tool-0.0.1/app/views/admin/AdminLayout.java, universal-application-tool-0.0.1/app/views/admin/ti/TrustedIntermediaryGroupListView.java, universal-application-tool-0.0.1/conf/routes, universal-application-tool-0.0.1/test/repository/WithPostgresContainer.java
Adds a form to the bottom of the page that lets you add a new TI group.
Screenshot: 
Related to #251.
=> Add new trusted intermediary groups.

browser-test/src/support/admin_ti_groups.ts, browser-test/src/ti_group.test.ts, universal-application-tool-0.0.1/app/controllers/admin/TrustedIntermediaryManagementController.java, universal-application-tool-0.0.1/app/forms/AddTrustedIntermediaryForm.java, universal-application-tool-0.0.1/app/forms/RemoveTrustedIntermediaryForm.java, universal-application-tool-0.0.1/app/models/Account.java, universal-application-tool-0.0.1/app/repository/UserRepository.java, universal-application-tool-0.0.1/app/services/ti/NoSuchTrustedIntermediaryError.java, universal-application-tool-0.0.1/app/services/ti/NoSuchTrustedIntermediaryGroupError.java, universal-application-tool-0.0.1/app/views/admin/ti/EditTrustedIntermediaryGroupView.java, universal-application-tool-0.0.1/app/views/admin/ti/TrustedIntermediaryGroupListView.java, universal-application-tool-0.0.1/app/views/components/LinkElement.java, universal-application-tool-0.0.1/app/views/style/ReferenceClasses.java, universal-application-tool-0.0.1/conf/routes
This makes it so that admins can add TIs to TI groups, and includes a browser test.
=> Enable adding TIs to TI groups.

universal-application-tool-0.0.1/app/views/admin/questions/QuestionPreview.java, universal-application-tool-0.0.1/app/views/applicant/ApplicantProgramBlockEditView.java, universal-application-tool-0.0.1/app/views/questiontypes/AddressQuestionRenderer.java, universal-application-tool-0.0.1/app/views/questiontypes/ApplicantQuestionRenderer.java, universal-application-tool-0.0.1/app/views/questiontypes/ApplicantQuestionRendererParams.java, universal-application-tool-0.0.1/app/views/questiontypes/CheckboxQuestionRenderer.java, universal-application-tool-0.0.1/app/views/questiontypes/DropdownQuestionRenderer.java, universal-application-tool-0.0.1/app/views/questiontypes/FileUploadQuestionRenderer.java, universal-application-tool-0.0.1/app/views/questiontypes/NameQuestionRenderer.java, universal-application-tool-0.0.1/app/views/questiontypes/NumberQuestionRenderer.java, universal-application-tool-0.0.1/app/views/questiontypes/RadioButtonQuestionRenderer.java, universal-application-tool-0.0.1/app/views/questiontypes/RepeaterQuestionRenderer.java, universal-application-tool-0.0.1/app/views/questiontypes/TextQuestionRenderer.java, universal-application-tool-0.0.1/test/views/questiontypes/ApplicantQuestionRendererFactoryTest.java, universal-application-tool-0.0.1/test/views/questiontypes/CheckboxQuestionRendererTest.java, universal-application-tool-0.0.1/test/views/questiontypes/RadioButtonQuestionRendererTest.java, universal-application-tool-0.0.1/test/views/questiontypes/TextQuestionRendererTest.java
This is in preparation for file upload question as it will need more context passed down to renderer.
=> Use a class to hold necessary info for question renderer

browser-test/src/support/admin_ti_groups.ts, universal-application-tool-0.0.1/app/views/admin/ti/TrustedIntermediaryGroupListView.java
- Moved the create button to the top
- Reworded some of the terms on the page
Fixes #956
=> Minor formatting changes on Intermediaries page

universal-application-tool-0.0.1/conf/evolutions/default/18.sql
This should combine with #961 to fix the logjam in staging...
=> Since the old down will apply, need to be tolerant of table existing already

browser-test/src/support/admin_ti_groups.ts, universal-application-tool-0.0.1/app/views/admin/ti/EditTrustedIntermediaryGroupView.java, universal-application-tool-0.0.1/app/views/admin/ti/TrustedIntermediaryGroupListView.java
- moving create to top
- changing labels
Fixes #965
=> layout improvements to edit TI

universal-application-tool-0.0.1/app/views/admin/ti/TrustedIntermediaryGroupListView.java
Text changes
Managed accounts -> Clients
Trusted Intermediaries (which are orgs) have members which have IDCS accounts
Fixes #981
=> wording changes on TI screen

universal-application-tool-0.0.1/app/services/applicant/ApplicantServiceImpl.java, universal-application-tool-0.0.1/app/services/applicant/question/Scalar.java
It is much more straightforward now.
Also, I organized `Scalar` enum and put a comment on it so hopefully people only append to it.
=> Simplify how metadata conflicts are caught.

universal-application-tool-0.0.1/app/services/program/BlockDefinition.java
Add TODO comments for #993
Comments for #993
=> Add TODO comments for #993

universal-application-tool-0.0.1/app/controllers/admin/TrustedIntermediaryManagementController.java, universal-application-tool-0.0.1/app/controllers/applicant/ApplicantProgramsController.java, universal-application-tool-0.0.1/app/controllers/ti/TrustedIntermediaryController.java, universal-application-tool-0.0.1/app/forms/AddApplicantToTrustedIntermediaryGroupForm.java, universal-application-tool-0.0.1/app/models/Account.java, universal-application-tool-0.0.1/app/repository/UserRepository.java, universal-application-tool-0.0.1/app/services/applicant/ApplicantData.java, universal-application-tool-0.0.1/app/services/ti/EmailAddressExistsException.java, universal-application-tool-0.0.1/app/views/applicant/ApplicantInformationView.java, universal-application-tool-0.0.1/app/views/applicant/ApplicantLayout.java, universal-application-tool-0.0.1/app/views/applicant/ApplicantProgramBlockEditView.java, universal-application-tool-0.0.1/app/views/applicant/ApplicantProgramSummaryView.java, universal-application-tool-0.0.1/app/views/applicant/ProgramIndexView.java, universal-application-tool-0.0.1/app/views/applicant/TrustedIntermediaryDashboardView.java, universal-application-tool-0.0.1/app/views/components/FieldWithLabel.java, universal-application-tool-0.0.1/conf/routes
This also adds a TI dashboard link to the header whenever a TI signs in.  That dashboard will eventually allow the TI to act as any applicant.
Fixes #771 
Fixes #252 
Fixes #251
=> Add applicant to TI group, via a form + controller endpoint.

universal-application-tool-0.0.1/app/models/Question.java
Migrate existing REPEATER questionType to ENUMERATOR 
Fixes issue in staging where we crash when there is no QuestionType.REPEATER
=> Migrate REPEATER to ENUMERATOR on load

browser-test/src/application_csv_download.test.ts, browser-test/src/application_review.test.ts, browser-test/src/support/applicant_questions.ts, universal-application-tool-0.0.1/app/controllers/applicant/ApplicantProgramReviewController.java
Added applicant title to the review page and the confirmation toast.
Fixes #914
=> Add application title to applicant review page.

universal-application-tool-0.0.1/app/auth/UatProfile.java, universal-application-tool-0.0.1/app/models/Account.java, universal-application-tool-0.0.1/app/views/applicant/TrustedIntermediaryDashboardView.java
Mostly an update to the auth rules so TIs can act as their users but not other users.  Also adds a button to the TI dashboard.
Updated table screenshot:
Fixes #248.
=> TIs can act as their associated applicants

infra/load_balancer.yaml
See https://docs.aws.amazon.com/elasticloadbalancing/latest/application/create-https-listener.html#tls-security-policies for the chart of supported ciphers.
Should fix the final security issue open from the City.
=> Remove even more ciphers.

universal-application-tool-0.0.1/app/repository/SignedS3UploadRequest.java
Increase file upload size up to 1GB per file.
=> Increase file upload size up to 1GB

.github/workflows/push.yaml, bin/build-and-push, bin/deploy-prod, bin/deploy-staging
This will prevent the sort of issue we had last Thursday->Monday.
=> Ensure that we run the prober after pushing to staging.

universal-application-tool-0.0.1/app/controllers/applicant/DeepLinkController.java, universal-application-tool-0.0.1/app/models/Program.java, universal-application-tool-0.0.1/app/repository/ProgramRepository.java, universal-application-tool-0.0.1/app/services/program/ProgramDefinition.java, universal-application-tool-0.0.1/app/services/program/ProgramNotFoundException.java, universal-application-tool-0.0.1/app/views/applicant/ProgramIndexView.java, universal-application-tool-0.0.1/build.sbt, universal-application-tool-0.0.1/conf/evolutions/default/20.sql, universal-application-tool-0.0.1/conf/routes, universal-application-tool-0.0.1/test/repository/ProgramRepositoryTest.java
Create a new deeplinking controller whose sole job is to redirect to the correct place.  You do need to be logged in to hit the deep link, but if you aren't, you're redirected to the login page.  
Two follow-ups:
- We need to get the login-page redirects to work the way they're supposed to - at the moment they're broken and you're always redirected to the home page.
- We need to build the details/landing page.
Towards #846.
=> Beginning of deep linking - creates deep links, but not landing pages.

universal-application-tool-0.0.1/app/views/applicant/TrustedIntermediaryDashboardView.java
Text changes:
- Create New Applicant -> Add Client
- Managed Applicants -> Clients
- Group Members -> Trusted Intermediary Members
Reordered sections
Fixes #1045
=> Text changes to TI dashboard

universal-application-tool-0.0.1/app/controllers/applicant/ApplicantProgramBlocksController.java, universal-application-tool-0.0.1/app/services/applicant/ReadOnlyApplicantProgramService.java, universal-application-tool-0.0.1/app/services/applicant/ReadOnlyApplicantProgramServiceImpl.java, universal-application-tool-0.0.1/app/views/applicant/ApplicantLayout.java, universal-application-tool-0.0.1/app/views/applicant/ApplicantProgramBlockEditView.java, universal-application-tool-0.0.1/app/views/applicant/ApplicantProgramSummaryView.java, universal-application-tool-0.0.1/test/services/applicant/ReadOnlyApplicantProgramServiceImplTest.java
Added a progress bar so the applicant knows how far along they are in the process.
=> Add progress bar to applicant pages

universal-application-tool-0.0.1/app/services/applicant/AnswerData.java, universal-application-tool-0.0.1/app/services/applicant/ReadOnlyApplicantProgramServiceImpl.java, universal-application-tool-0.0.1/app/services/applicant/question/MultiSelectQuestion.java, universal-application-tool-0.0.1/app/services/applicant/question/SingleSelectQuestion.java, universal-application-tool-0.0.1/test/services/applicant/ReadOnlyApplicantProgramServiceImplTest.java
Add fields to `AnswerData` that will be helpful for rendering answers to admins.
Progress towards #665
=> Add question id and scalar answers in default locale to AnswerData.

universal-application-tool-0.0.1/app/assets/javascripts/main.ts, universal-application-tool-0.0.1/app/views/admin/questions/QuestionConfig.java
=> Fix removing already-persisted options from a QD

universal-application-tool-0.0.1/conf/evolutions/default/22.sql
Get rid of the column types in the column drop statements.
=> Fix 22.sql down.

universal-application-tool-0.0.1/conf/evolutions/default/23.sql
Migrate the existing column rather than create a new one.
This fixes SQL from #1065
=> Fix question options in database

bin/localstack/ses-verify-identity
Fix running locally (e.g. bin/run-dev, bin/run-browser-test-env)
=> Add region in the AWS SES command

universal-application-tool-0.0.1/app/controllers/admin/AdminQuestionController.java, universal-application-tool-0.0.1/app/controllers/admin/AdminQuestionTranslationsController.java, universal-application-tool-0.0.1/app/views/admin/AdminLayout.java, universal-application-tool-0.0.1/app/views/admin/questions/QuestionEditView.java, universal-application-tool-0.0.1/app/views/admin/questions/QuestionsListView.java, universal-application-tool-0.0.1/conf/routes, universal-application-tool-0.0.1/test/app/BaseBrowserTest.java, universal-application-tool-0.0.1/test/controllers/admin/AdminQuestionControllerTest.java
Rename admin question controller to match convention
=> Rename admin question controller

universal-application-tool-0.0.1/app/models/Question.java, universal-application-tool-0.0.1/app/services/question/types/EnumeratorQuestionDefinition.java, universal-application-tool-0.0.1/app/services/question/types/QuestionDefinitionBuilder.java, universal-application-tool-0.0.1/conf/evolutions/default/24.sql, universal-application-tool-0.0.1/test/forms/EnumeratorQuestionFormTest.java, universal-application-tool-0.0.1/test/models/QuestionTest.java, universal-application-tool-0.0.1/test/services/applicant/question/EnumeratorQuestionTest.java, universal-application-tool-0.0.1/test/services/question/types/QuestionDefinitionBuilderTest.java, universal-application-tool-0.0.1/test/services/question/types/QuestionDefinitionTest.java, universal-application-tool-0.0.1/test/support/TestQuestionBank.java
Add column in DB for admin-configurable localized enumerator question entity types.
Progress towards #859 #425
=> Add db column and method to builder

universal-application-tool-0.0.1/app/assets/javascripts/ga.ts, universal-application-tool-0.0.1/app/views/BaseHtmlLayout.java, universal-application-tool-0.0.1/app/views/LoginForm.java, universal-application-tool-0.0.1/app/views/ViewUtils.java, universal-application-tool-0.0.1/app/views/admin/AdminLayout.java, universal-application-tool-0.0.1/app/views/admin/programs/ProgramApplicationListView.java, universal-application-tool-0.0.1/app/views/admin/programs/ProgramApplicationView.java, universal-application-tool-0.0.1/app/views/admin/programs/ProgramIndexView.java, universal-application-tool-0.0.1/app/views/applicant/ApplicantLayout.java, universal-application-tool-0.0.1/app/views/dev/DatabaseSeedView.java, universal-application-tool-0.0.1/app/views/dev/FileUploadView.java
Adds support for Google Analytics tagging.  This is part 1.  Part 2, issue #1100, will enable the measurement ID to be configured in containers.yaml
Fixes #575
=> Support for Google Analytics tagging

browser-test/src/application_csv_download.test.ts, browser-test/src/support/index.ts, universal-application-tool-0.0.1/app/auth/FakeAdminClient.java, universal-application-tool-0.0.1/app/auth/ProfileFactory.java, universal-application-tool-0.0.1/app/controllers/CallbackController.java, universal-application-tool-0.0.1/app/views/LoginForm.java, universal-application-tool-0.0.1/conf/routes
New debug button that makes you an admin of all currently active programs.
=> Add a browser test for program admins by adding new kind of debug admin button

universal-application-tool-0.0.1/app/views/BaseHtmlView.java, universal-application-tool-0.0.1/app/views/admin/questions/QuestionConfig.java, universal-application-tool-0.0.1/app/views/admin/questions/QuestionEditView.java
=> Small visual changes to the admin question edit view

universal-application-tool-0.0.1/app/services/applicant/question/AddressQuestion.java, universal-application-tool-0.0.1/app/views/applicant/ApplicantProgramSummaryView.java, universal-application-tool-0.0.1/test/services/applicant/ReadOnlyApplicantProgramServiceImplTest.java, universal-application-tool-0.0.1/test/services/applicant/question/AddressQuestionTest.java
This was previously missing from the answer summary.
=> Display Address Line 2 in answer summary

browser-test/src/support/applicant_questions.ts, universal-application-tool-0.0.1/app/controllers/applicant/ApplicantProgramReviewController.java, universal-application-tool-0.0.1/app/views/applicant/ApplicantProgramConfirmationView.java, universal-application-tool-0.0.1/conf/messages.en-US, universal-application-tool-0.0.1/conf/routes
=> Give users a nice page confirming they applied

infra/containers.yaml
=> Swap ADFS admin group config

universal-application-tool-0.0.1/app/auth/AdfsProfileAdapter.java
This reverts commit b2405e17d98f1c25ba91efd72a4feaea78e17df6.
=> Revert "Log ADFS attributes for debug (#1125)"

universal-application-tool-0.0.1/app/views/applicant/ApplicantLayout.java, universal-application-tool-0.0.1/app/views/applicant/ProgramIndexView.java, universal-application-tool-0.0.1/app/views/style/ApplicantStyles.java, universal-application-tool-0.0.1/app/views/style/BaseStyles.java, universal-application-tool-0.0.1/tailwind.config.js
Also factored some styles out into ApplicanStyles.java.
Works toward #1016
=> Add CiviForm and Seattle colors and update Applicant's Program Index view to better match mocks

infra/containers.yaml
=> Remove unnecessary tokens in measurement id

universal-application-tool-0.0.1/app/services/applicant/ApplicantServiceImpl.java
Avoid spamming people from staging.
#193
=> Send email to staging mailing list instead of real addresses in staging

universal-application-tool-0.0.1/app/views/applicant/ApplicantProgramBlockEditView.java
Delete the block name from applicant views.
=> No block name in titles.

universal-application-tool-0.0.1/app/services/aws/SimpleEmail.java, universal-application-tool-0.0.1/app/services/program/ProgramServiceImpl.java
Don't send emails if the list is empty
=> Ignore empty email list

universal-application-tool-0.0.1/app/views/applicant/ApplicantLayout.java, universal-application-tool-0.0.1/app/views/style/ApplicantStyles.java
=> Improve Applicant UI nav bar

browser-test/src/admin_program_creation.test.ts, browser-test/src/end_to_end_enumerators.test.ts, universal-application-tool-0.0.1/app/services/question/types/QuestionDefinition.java, universal-application-tool-0.0.1/test/controllers/admin/AdminQuestionControllerTest.java, universal-application-tool-0.0.1/test/services/question/QuestionServiceImplTest.java, universal-application-tool-0.0.1/test/services/question/types/QuestionDefinitionTest.java, universal-application-tool-0.0.1/test/support/TestQuestionBank.java
Repeated questions are now required to have "$this" in their text and help text, for all translations.
=> Add question validation check for $this in question text and help text for repeated questions.

bin/breakglass-db-access
Add prod DB secret id and allow breakglass to switch on env
=> Connect to prod db if necessary

browser-test/src/admin_program_translation.test.ts, browser-test/src/application_review.test.ts, browser-test/src/support/applicant_questions.ts, universal-application-tool-0.0.1/app/views/BaseHtmlLayout.java, universal-application-tool-0.0.1/app/views/HtmlBundle.java, universal-application-tool-0.0.1/app/views/applicant/ApplicantLayout.java
Thank goodness for `HtmlBundle`, amirite?
Partially addresses #1148
Fixes #1145
=> Adding basic page data (html lang and meta viewport)

universal-application-tool-0.0.1/app/controllers/UntrailingController.java, universal-application-tool-0.0.1/conf/routes
Adds a simple controller to redirect URLs with trailing backslashes.
Fixes #1078
=> untrail trailing slashes

universal-application-tool-0.0.1/app/views/style/ApplicantStyles.java
=> Applicant UI: Add responsive widths for the form flow

universal-application-tool-0.0.1/app/controllers/applicant/ApplicantInformationController.java, universal-application-tool-0.0.1/app/controllers/applicant/ApplicantProgramBlocksController.java, universal-application-tool-0.0.1/app/controllers/applicant/ApplicantProgramReviewController.java, universal-application-tool-0.0.1/app/controllers/applicant/ApplicantProgramsController.java, universal-application-tool-0.0.1/app/controllers/ti/TrustedIntermediaryController.java, universal-application-tool-0.0.1/app/services/applicant/ApplicantService.java, universal-application-tool-0.0.1/app/services/applicant/ApplicantServiceImpl.java, universal-application-tool-0.0.1/app/views/applicant/ApplicantInformationView.java, universal-application-tool-0.0.1/app/views/applicant/ApplicantLayout.java, universal-application-tool-0.0.1/app/views/applicant/ApplicantProgramBlockEditView.java, universal-application-tool-0.0.1/app/views/applicant/ApplicantProgramConfirmationView.java, universal-application-tool-0.0.1/app/views/applicant/ApplicantProgramSummaryView.java, universal-application-tool-0.0.1/app/views/applicant/ProgramIndexView.java, universal-application-tool-0.0.1/app/views/applicant/TrustedIntermediaryDashboardView.java
If the user is signed in as a TI, show the name of the user they're currently applying on behalf of.
Fixes #1104.
=> Add the username in the header for signed-in TIs.

universal-application-tool-0.0.1/app/services/applicant/ApplicantServiceImpl.java, universal-application-tool-0.0.1/app/views/admin/programs/ProgramApplicationListView.java
- Change email subject to include applicant id
- Include applicant id in program application review page
=> Add more information to make reviewing application easier

universal-application-tool-0.0.1/app/views/applicant/ApplicantLayout.java
=> CiviForm top left logo links to the home page

browser-test/src/support/admin_questions.ts, universal-application-tool-0.0.1/app/assets/javascripts/preview.ts, universal-application-tool-0.0.1/app/views/admin/questions/QuestionEditView.java
Give the admins information about repeated questions when they create one
Adds some help for #1123
=> Add information for repeated questions when the admin is creating one.

browser-test/src/support/applicant_questions.ts, universal-application-tool-0.0.1/app/controllers/admin/AdminApplicationController.java, universal-application-tool-0.0.1/app/views/admin/programs/ProgramApplicationView.java
Add more information to the application review page for a single applicant so landing directly on this page gives enough context to the program admin. Specifically, these are
- program name
- applicant name with id
=> Add more information in application review page

universal-application-tool-0.0.1/conf/messages.en-US
(now they show up)
https://www.playframework.com/documentation/2.8.x/ScalaI18N#Notes-on-apostrophes
=> Quotes are used as an escape character.

universal-application-tool-0.0.1/app/services/MessageKey.java, universal-application-tool-0.0.1/app/views/questiontypes/EnumeratorQuestionRenderer.java, universal-application-tool-0.0.1/app/views/style/ApplicantStyles.java, universal-application-tool-0.0.1/conf/messages, universal-application-tool-0.0.1/conf/messages.en-US, universal-application-tool-0.0.1/conf/messages.es-US
* Make the button styles consistent with other styles in the page
* Replace the garbage can icon with "Remove {entity name}"
On hover of "remove" button:
Works toward #1016
=> Applicant UI: Update styles for enumerator question buttons

universal-application-tool-0.0.1/app/views/applicant/ApplicantLayout.java, universal-application-tool-0.0.1/app/views/style/ApplicantStyles.java
I just wanted the brand to have a hover effect.
=> Make civiform brand have a hover effect.

universal-application-tool-0.0.1/app/assets/javascripts/radio.ts, universal-application-tool-0.0.1/app/views/style/BaseStyles.java, universal-application-tool-0.0.1/tailwind.config.js
Because I'm occasionally pedantic and hated seeing `bg-seattleBlue`
=> Make custom colors selector-case.

universal-application-tool-0.0.1/app/views/applicant/ProgramIndexView.java, universal-application-tool-0.0.1/app/views/style/ApplicantStyles.java
@AWBaumann - I saw your comment on using line clamp in the issue. Please see issue linked below for my reply.
Desktop:
Mobile (not the greatest experience as a scrollbar... but OK for now):
Old behavior:
Fixes #1180
=> Add scrollbar when program description is too long for program card

universal-application-tool-0.0.1/app/views/applicant/ApplicantProgramBlockEditView.java, universal-application-tool-0.0.1/app/views/style/ApplicantStyles.java
=> Applicant UI: Update location and style of "Review" button

universal-application-tool-0.0.1/app/auth/AccountNonexistentException.java, universal-application-tool-0.0.1/app/auth/ProfileUtils.java, universal-application-tool-0.0.1/app/auth/UatProfile.java, universal-application-tool-0.0.1/app/filters/ValidAccountFilter.java, universal-application-tool-0.0.1/conf/application.conf
- If the account referenced in cookie is nonexistent, auto redirect the user to log out
=> Auto logout if account is nonexistent

universal-application-tool-0.0.1/app/assets/javascripts/preview.ts, universal-application-tool-0.0.1/app/assets/javascripts/questionBank.ts, universal-application-tool-0.0.1/app/views/admin/AdminLayout.java, universal-application-tool-0.0.1/app/views/admin/programs/ProgramBlockEditView.java, universal-application-tool-0.0.1/app/views/admin/questions/QuestionEditView.java, universal-application-tool-0.0.1/app/views/components/QuestionBank.java, universal-application-tool-0.0.1/app/views/style/ReferenceClasses.java
The filter is not case-sensitive, everything is converted to upper case.
"hidden" is toggled if the search string is not empty and there is a match on `innerText`, which contains the question name and description.
Enables #1030 for story acceptance.
=> Make question bank filter work.

universal-application-tool-0.0.1/app/auth/IdcsProfileAdapter.java, universal-application-tool-0.0.1/conf/logback.xml
We have persistent issues with IDCS not allowing us to fetch the jwk - we need to find out what's going on there.  This logging, while very verbose, will help us do that.
=> add more logs.

universal-application-tool-0.0.1/app/assets/javascripts/preview.ts, universal-application-tool-0.0.1/app/views/applicant/ApplicantLayout.java, universal-application-tool-0.0.1/app/views/style/BaseStyles.java
Now using the shades recommended by UX. Also update progress bar border according to UX mocks.
=> Fix the grays used in form fields for a11y

universal-application-tool-0.0.1/app/services/question/types/QuestionType.java
Enumerator question type needed to be alphabetized after being renamed from repeater.
=> Alphabetize enumerator question type enum.

universal-application-tool-0.0.1/app/views/admin/questions/QuestionEditView.java
Move question enumerator id and name to the top of the question form, and disable them if the form isn't for question creation.
In CiviForm, the question name and enumerator id are the two things that should not ever change between drafts and versions of a question. Putting them together at the top seems like a sensible thing to do.
=> Move enumerator to the top of the form, and then disable it like the name field is disabled

universal-application-tool-0.0.1/app/views/BaseHtmlLayout.java
We only need to show the privacy banner for staging.
Fixes #1190
=> Only show privacy banner for staging.seattle.civiform.com.

universal-application-tool-0.0.1/app/views/admin/programs/ProgramFormBuilder.java, universal-application-tool-0.0.1/app/views/admin/programs/ProgramNewOneView.java
Talia recommended different phrasing for the program form - updated with her suggestions
=> Update copy for program form

browser-test/src/application_review.test.ts, browser-test/src/support/admin_programs.ts, universal-application-tool-0.0.1/app/services/applicant/AnswerData.java, universal-application-tool-0.0.1/app/services/applicant/ApplicantServiceImpl.java, universal-application-tool-0.0.1/app/services/applicant/ReadOnlyApplicantProgramServiceImpl.java, universal-application-tool-0.0.1/app/services/applicant/question/FileUploadQuestion.java, universal-application-tool-0.0.1/app/services/aws/SimpleStorage.java, universal-application-tool-0.0.1/app/views/admin/programs/ProgramApplicationView.java, universal-application-tool-0.0.1/app/views/applicant/ApplicantProgramSummaryView.java, universal-application-tool-0.0.1/test/services/applicant/ReadOnlyApplicantProgramServiceImplTest.java
Render the presigned link in application review pages for both the applicant and program admins so they can download and view content.
=> Render download links in review page for uploaded files

universal-application-tool-0.0.1/app/controllers/ti/TrustedIntermediaryController.java, universal-application-tool-0.0.1/app/models/TrustedIntermediaryGroup.java, universal-application-tool-0.0.1/app/views/applicant/ApplicantLayout.java, universal-application-tool-0.0.1/app/views/applicant/TrustedIntermediaryDashboardView.java, universal-application-tool-0.0.1/conf/routes
TIs can search through their list of clients.
Implements #775
=> Implement search and pagination for TI clients.

universal-application-tool-0.0.1/app/controllers/admin/AdminApplicationController.java, universal-application-tool-0.0.1/app/controllers/ti/TrustedIntermediaryController.java, universal-application-tool-0.0.1/app/repository/ProgramRepository.java, universal-application-tool-0.0.1/app/services/PaginationInfo.java, universal-application-tool-0.0.1/app/services/program/ProgramService.java, universal-application-tool-0.0.1/app/services/program/ProgramServiceImpl.java, universal-application-tool-0.0.1/app/views/BaseHtmlView.java, universal-application-tool-0.0.1/app/views/admin/programs/ProgramAdministratorProgramListView.java, universal-application-tool-0.0.1/app/views/admin/programs/ProgramApplicationListView.java, universal-application-tool-0.0.1/app/views/admin/programs/ProgramIndexView.java, universal-application-tool-0.0.1/app/views/applicant/TrustedIntermediaryDashboardView.java, universal-application-tool-0.0.1/conf/routes
=> Allow users to see old applications, add search + pagination for apps.

universal-application-tool-0.0.1/app/services/applicant/question/ApplicantQuestion.java, universal-application-tool-0.0.1/app/services/question/types/QuestionDefinition.java
Give QuestionDefinition a getContextualizedPath method.
=> Give QuestionDefinition a getContextualizedPath method.

universal-application-tool-0.0.1/app/views/admin/ti/TrustedIntermediaryGroupListView.java, universal-application-tool-0.0.1/app/views/style/ApplicantStyles.java
Submit button made green
Fixes #1251
=> Submit button made green

universal-application-tool-0.0.1/app/views/admin/programs/ProgramAdministratorProgramListView.java, universal-application-tool-0.0.1/app/views/admin/programs/ProgramIndexView.java
=> Display program deep link to admin

universal-application-tool-0.0.1/conf/evolutions/default/27.sql, universal-application-tool-0.0.1/test/repository/QuestionRepositoryTest.java
Fixes #1085.  tested by building things before this change, then making this change, then clicking around in `run-dev` - should work.
=> path column no longer needed.

universal-application-tool-0.0.1/conf/application.conf
Reordered the languages in the configuration file to alphabetize all languages
Fixes [#1253](https://github.com/seattle-uat/civiform/issues/1253) Alphabetize all languages besides English
@neel-a-mehta
=> Alphabetize all languages besides English

universal-application-tool-0.0.1/app/views/BaseHtmlView.java, universal-application-tool-0.0.1/app/views/questiontypes/ApplicantQuestionRenderer.java
Add links to question descriptions.
Fixes #1002
=> Links & text escaping in questions.

.gitignore, bin/find-flakey-browser-tests, bin/run-browser-tests
Add a script to run browser tests a bunch of times, and stores the errors in `/flakes`.
=> Add a script to run browser tests a bunch.

browser-test/src/question_delete.test.ts, browser-test/src/support/admin_questions.ts, universal-application-tool-0.0.1/app/controllers/admin/AdminQuestionController.java, universal-application-tool-0.0.1/app/models/Question.java, universal-application-tool-0.0.1/app/models/Version.java, universal-application-tool-0.0.1/app/repository/VersionRepository.java, universal-application-tool-0.0.1/app/services/DeletionStatus.java, universal-application-tool-0.0.1/app/services/question/ActiveAndDraftQuestions.java, universal-application-tool-0.0.1/app/services/question/QuestionService.java, universal-application-tool-0.0.1/app/services/question/QuestionServiceImpl.java, universal-application-tool-0.0.1/app/services/question/ReadOnlyQuestionServiceImpl.java, universal-application-tool-0.0.1/app/views/admin/questions/QuestionsListView.java, universal-application-tool-0.0.1/app/views/components/LinkElement.java, universal-application-tool-0.0.1/conf/evolutions/default/28.sql, universal-application-tool-0.0.1/conf/routes
Introduces three new actions for questions - archive, restore, and discard draft.
Implements #997.
=> Allow archiving of questions.

universal-application-tool-0.0.1/app/views/admin/programs/ProgramApplicationView.java
Hide a button that was already meant to be hidden.
=> Apply the hidden class, rather than the hidden attribute - to actually hide it

universal-application-tool-0.0.1/app/modules/SecurityModule.java
Staging currently broken due to https://ocistatus.oraclecloud.com/incidents/ldz134xqx4yg - this will make the error much much clearer if this ever happens again.
=> eagerly load config so we'll fail to deploy rather than fail to load if idcs or ad is down.

universal-application-tool-0.0.1/app/controllers/applicant/RedirectController.java, universal-application-tool-0.0.1/app/views/applicant/ApplicantUpsellCreateAccountView.java
When TI applies on behalf of the applicant, show applicant's name, not TI's.
=> Use correct applicant name in upsell page

browser-test/src/support/applicant_questions.ts, browser-test/src/support/index.ts, universal-application-tool-0.0.1/app/services/MessageKey.java, universal-application-tool-0.0.1/app/views/applicant/ApplicantUpsellCreateAccountView.java, universal-application-tool-0.0.1/conf/messages, universal-application-tool-0.0.1/conf/messages.en-US, universal-application-tool-0.0.1/conf/messages.es-US
Use the same wording for the link of returning to applicant program page so the browser test passes.
=> Use the same wording for returning to applicant program page

.github/workflows/cron.yaml, .github/workflows/push.yaml
Use the correct secret names to get the credentials
=> Prober uses correct credentials

universal-application-tool-0.0.1/app/services/export/CsvExporter.java, universal-application-tool-0.0.1/app/services/export/ExporterService.java, universal-application-tool-0.0.1/app/services/program/ColumnType.java, universal-application-tool-0.0.1/test/services/export/CsvExporterTest.java
Record applicant's language in CSV export
=> Record applicant's language in CSV export

universal-application-tool-0.0.1/app/services/MessageKey.java, universal-application-tool-0.0.1/app/views/applicant/ApplicantLayout.java, universal-application-tool-0.0.1/conf/application.conf, universal-application-tool-0.0.1/conf/messages
=> Add technical support contact email to applicant footer

universal-application-tool-0.0.1/app/views/applicant/ApplicantLayout.java
=> Remove unneeded injected param

universal-application-tool-0.0.1/app/controllers/admin/ProgramAdminController.java, universal-application-tool-0.0.1/app/views/admin/AdminLayout.java, universal-application-tool-0.0.1/app/views/admin/programs/ProgramAdministratorProgramListView.java, universal-application-tool-0.0.1/app/views/admin/programs/ProgramApplicationListView.java, universal-application-tool-0.0.1/app/views/admin/programs/ProgramApplicationView.java, universal-application-tool-0.0.1/app/views/admin/programs/ProgramIndexView.java
=> Don't render nav links for program admin

universal-application-tool-0.0.1/app/controllers/dev/FileUploadController.java, universal-application-tool-0.0.1/app/models/StoredFile.java, universal-application-tool-0.0.1/app/repository/StoredFileRepository.java, universal-application-tool-0.0.1/app/views/dev/FileUploadView.java
We don't need the presigned URL in the StoredFile.java.
=> Remove unnecessary fields in StoredFile.java

browser-test/src/support/index.ts
Seattle's IDCS page changed, which caused browser tests to fail. This change changes query selectors for logging into IDCS.
=> Update browser tests to match Seattle's new IDCS page

universal-application-tool-0.0.1/app/services/program/ProgramServiceImpl.java, universal-application-tool-0.0.1/app/views/components/FieldWithLabel.java
Cleaning up redundant type specification in generics.
=> Remove redundant type specification.

browser-test/src/application_review.test.ts, universal-application-tool-0.0.1/app/services/applicant/ApplicantData.java
When an applicant does not select any items in a checkbox question, it counts as being answered
#931
=> Non-selected checkbox questions are counted as answered

universal-application-tool-0.0.1/project/TailwindBuilder.scala, universal-application-tool-0.0.1/tailwindbuilder.sbt
The old command is deprecated and stops working.
=> Update tailwindcss cli command

universal-application-tool-0.0.1/app/views/admin/programs/ProgramBlockPredicatesEditView.java
=> Update the copy in the admin predicate UI

universal-application-tool-0.0.1/app/auth/IdcsProfileAdapter.java
Remove a race condition where two db operations could overwrite each other.
We have a prober flake where test user name sometimes is missed. This is an attempt to fix the flake.
=> Login name is stored correctly

browser-test/src/admin_dropdown_create_and_edit.test.ts
Make sure javascripts are loaded before clicking.
=> Fix a flake in browser test

universal-application-tool-0.0.1/package-lock.json, universal-application-tool-0.0.1/package.json, universal-application-tool-0.0.1/tailwind.config.js
Address npm warnings by updating version of tailwindcss and dependencies.
The version update does not affect our current styles.
release notes: https://github.com/tailwindlabs/tailwindcss/releases
=> Update Tailwindcss version

universal-application-tool-0.0.1/package-lock.json, universal-application-tool-0.0.1/package.json, universal-application-tool-0.0.1/project/TailwindBuilder.scala, universal-application-tool-0.0.1/tailwind.config.js, universal-application-tool-0.0.1/tailwindbuilder.sbt
Update tailwind cli command according to https://tailwindcss.com/docs/installation#building-for-production
=> Minify prod css

universal-application-tool-0.0.1/project/TailwindBuilder.scala, universal-application-tool-0.0.1/tailwindbuilder.sbt
Reverts seattle-uat/civiform#1386
Styles are broken in staging:
=> Revert "Minify prod css"

universal-application-tool-0.0.1/app/services/applicant/ApplicantServiceImpl.java, universal-application-tool-0.0.1/app/services/applicant/ReadOnlyApplicantProgramServiceImpl.java, universal-application-tool-0.0.1/test/services/applicant/ReadOnlyApplicantProgramServiceImplTest.java, universal-application-tool-0.0.1/test/services/export/CsvExporterTest.java
This ensures the link in CSV export is the full (absolute) link.
#664
=> Full link for file download in CSV

universal-application-tool-0.0.1/app/assets/javascripts/main.ts, universal-application-tool-0.0.1/app/repository/QuestionRepository.java
Make demographic export have a deterministic order by question name.
=> Deflake a browser test

universal-application-tool-0.0.1/app/assets/javascripts/main.ts, universal-application-tool-0.0.1/app/repository/QuestionRepository.java, universal-application-tool-0.0.1/app/services/program/predicate/PredicateValue.java, universal-application-tool-0.0.1/test/services/program/predicate/PredicateValueTest.java
Reverts seattle-uat/civiform#1409
This is exactly the same as #1395, but updates `JsonCreator` for `PredicateValue` and adds a `PredicateValueTest` for old version of value
=> Bring back pretty printing, but this time handle null `type`

universal-application-tool-0.0.1/conf/messages
I forgot some comments in the messages file for #1400
=> Add comments to messages file for login page

universal-application-tool-0.0.1/app/controllers/admin/AdminProgramBlockPredicatesController.java
Include show/hide action in success toast
#322
=> Fix wording on success toast to include show/hide action

infra/containers.yaml
=> Redirect staging to QA registration page.

universal-application-tool-0.0.1/app/services/MessageKey.java, universal-application-tool-0.0.1/app/services/WellKnownPaths.java, universal-application-tool-0.0.1/app/views/applicant/ApplicantLayout.java, universal-application-tool-0.0.1/conf/messages
=> Add an indicator to say what your name is in the top right of the applicant view

universal-application-tool-0.0.1/app/views/questiontypes/FileUploadQuestionRenderer.java
=> Allow upload only images and pdfs

universal-application-tool-0.0.1/app/views/applicant/ApplicantProgramBlockEditView.java, universal-application-tool-0.0.1/app/views/style/ApplicantStyles.java
Application nav buttons stack in mobile views
=> mobile responsive file upload view

universal-application-tool-0.0.1/app/assets/javascripts/validation.ts, universal-application-tool-0.0.1/app/services/MessageKey.java, universal-application-tool-0.0.1/app/services/applicant/question/FileUploadQuestion.java, universal-application-tool-0.0.1/app/views/applicant/ApplicantProgramBlockEditView.java, universal-application-tool-0.0.1/app/views/questiontypes/EnumeratorQuestionRenderer.java, universal-application-tool-0.0.1/app/views/questiontypes/FileUploadQuestionRenderer.java, universal-application-tool-0.0.1/app/views/style/ReferenceClasses.java, universal-application-tool-0.0.1/conf/messages, universal-application-tool-0.0.1/conf/messages.en-US
Block upload if no file is selected. Note: it is still possible to skip the upload by clicking the skip button.
#1210
=> File selection is required to upload

universal-application-tool-0.0.1/app/assets/javascripts/main.ts
=> Use a switch statement instead of big if/else

universal-application-tool-0.0.1/app/services/program/ProgramDefinition.java, universal-application-tool-0.0.1/test/services/program/ProgramDefinitionTest.java
The same will need to be done for static questions once https://github.com/seattle-uat/civiform/pull/1406 is in. Left a TODO for that.
=> Filter out file upload questions from potential predicate questions

universal-application-tool-0.0.1/app/controllers/applicant/ApplicantProgramBlocksController.java
Add docstring and minor refactor to make ApplicantProgramBlocksController more readable
=> Add docstring for ApplicantProgramBlocksController

universal-application-tool-0.0.1/app/views/LoginForm.java, universal-application-tool-0.0.1/app/views/applicant/ProgramIndexView.java
These don't need to be read by screen readers.
Fixes #1473.
=> Add alt text (and aria-hidden) for seattle logos.

universal-application-tool-0.0.1/app/assets/javascripts/main.ts
Set focus to the new enumerator field when it is created.
Fixes #1483
=> Set focus to the new enumerator field

universal-application-tool-0.0.1/app/views/applicant/ProgramIndexView.java
It'll be `Get benefits - CiviForm` in english.
Addresses #1465.
=> Give title to main page.

browser-test/src/support/admin_programs.ts, universal-application-tool-0.0.1/app/assets/javascripts/modal.ts, universal-application-tool-0.0.1/app/views/admin/programs/ProgramIndexView.java
The "publish all programs" button has too many consequences that it should have a confirmation dialog to protect it. This PR adds a confirmation modal, and updates the browser tests.
=> Protect "publish all program" with a confirmation modal

universal-application-tool-0.0.1/app/services/MessageKey.java, universal-application-tool-0.0.1/app/views/applicant/ApplicantInformationView.java, universal-application-tool-0.0.1/app/views/applicant/ApplicantLayout.java, universal-application-tool-0.0.1/app/views/applicant/ApplicantProgramBlockEditView.java, universal-application-tool-0.0.1/conf/messages
=> Add screen-reader-only H1s to pages that don't have them.

universal-application-tool-0.0.1/app/assets/javascripts/validation.ts
Empty optional questions are valid. Otherwise they need to meet the question's validation criteria.
Fixes #1418
=> Update validation.ts to differentiate between required and optional questions.

universal-application-tool-0.0.1/app/services/MessageKey.java, universal-application-tool-0.0.1/app/views/applicant/ProgramIndexView.java, universal-application-tool-0.0.1/conf/messages, universal-application-tool-0.0.1/conf/messages.en-US, universal-application-tool-0.0.1/conf/messages.es-US
Add an sr-only h4 title to program cards with the format "Program {n} of {m} -- {programTitle}"
Fixes #1522
=> Add an sr-only title for the applicants program cards

browser-test/src/admin_predicates.test.ts, universal-application-tool-0.0.1/app/assets/javascripts/main.ts, universal-application-tool-0.0.1/app/controllers/admin/AdminProgramBlockPredicatesController.java, universal-application-tool-0.0.1/app/services/program/predicate/Operator.java
1. Enable IN and NOT_IN operators for number questions
2. We now need to combine scalar type and operator type in order to determine the value input type
#322 #1532
=> Include LIST_OF_LONGS as an option for the IN and NOT_IN operators

universal-application-tool-0.0.1/app/services/applicant/ApplicantServiceImpl.java, universal-application-tool-0.0.1/app/services/applicant/JsonPathProvider.java, universal-application-tool-0.0.1/app/services/applicant/ReadOnlyApplicantProgramServiceImpl.java, universal-application-tool-0.0.1/app/services/applicant/Update.java, universal-application-tool-0.0.1/app/services/applicant/exception/ApplicantNotFoundException.java, universal-application-tool-0.0.1/app/services/applicant/exception/ApplicationSubmissionException.java, universal-application-tool-0.0.1/app/services/applicant/exception/InvalidPredicateException.java, universal-application-tool-0.0.1/app/services/applicant/exception/ProgramBlockNotFoundException.java, universal-application-tool-0.0.1/app/services/applicant/question/AddressQuestion.java, universal-application-tool-0.0.1/app/services/applicant/question/DateQuestion.java, universal-application-tool-0.0.1/app/services/applicant/question/EmailQuestion.java, universal-application-tool-0.0.1/app/services/applicant/question/EnumeratorQuestion.java, universal-application-tool-0.0.1/app/services/applicant/question/FileUploadQuestion.java, universal-application-tool-0.0.1/app/services/applicant/question/MultiSelectQuestion.java, universal-application-tool-0.0.1/app/services/applicant/question/NameQuestion.java, universal-application-tool-0.0.1/app/services/applicant/question/NumberQuestion.java, universal-application-tool-0.0.1/app/services/applicant/question/PresentsErrors.java, universal-application-tool-0.0.1/app/services/applicant/question/SingleSelectQuestion.java, universal-application-tool-0.0.1/app/services/applicant/question/StaticContentQuestion.java, universal-application-tool-0.0.1/app/services/applicant/question/TextQuestion.java
=> Add Javadoc to applicant service classes

universal-application-tool-0.0.1/app/services/DeletionStatus.java, universal-application-tool-0.0.1/app/services/PaginationInfo.java, universal-application-tool-0.0.1/app/services/TranslationNotFoundException.java, universal-application-tool-0.0.1/app/services/WellKnownPaths.java, universal-application-tool-0.0.1/app/services/aws/AwsRegion.java, universal-application-tool-0.0.1/app/services/aws/Credentials.java, universal-application-tool-0.0.1/app/services/aws/SignedS3UploadRequest.java, universal-application-tool-0.0.1/app/services/aws/SimpleEmail.java, universal-application-tool-0.0.1/app/services/aws/SimpleStorage.java, universal-application-tool-0.0.1/app/services/export/CsvExporter.java, universal-application-tool-0.0.1/app/services/export/ExporterFactory.java, universal-application-tool-0.0.1/app/services/export/ExporterService.java, universal-application-tool-0.0.1/app/services/export/NotConfiguredException.java, universal-application-tool-0.0.1/app/services/export/PdfExporter.java, universal-application-tool-0.0.1/app/services/export/PdfMapAssistant.java, universal-application-tool-0.0.1/app/services/ti/EmailAddressExistsException.java, universal-application-tool-0.0.1/app/services/ti/NoSuchTrustedIntermediaryError.java, universal-application-tool-0.0.1/app/services/ti/NoSuchTrustedIntermediaryGroupError.java
=> Add Javadoc for more service classes

universal-application-tool-0.0.1/app/auth/FakeAdminClient.java, universal-application-tool-0.0.1/app/controllers/dev/DevController.java, universal-application-tool-0.0.1/app/controllers/ti/TrustedIntermediaryController.java, universal-application-tool-0.0.1/app/modules/SecurityModule.java, universal-application-tool-0.0.1/app/services/applicant/ApplicantServiceImpl.java, universal-application-tool-0.0.1/app/views/BaseHtmlLayout.java, universal-application-tool-0.0.1/app/views/LoginForm.java, universal-application-tool-0.0.1/conf/application.conf
Removes hard-coded references to seattle-specific domains in application code and moves them into the application.conf file
=> Remove hard-coded references to seattle.gov domains

browser-test/src/admin_predicates.test.ts, browser-test/src/admin_program_creation.test.ts, browser-test/src/admin_program_translation.test.ts, browser-test/src/application_csv_download.test.ts, browser-test/src/application_optional_questions.test.ts, browser-test/src/application_previous_version.test.ts, browser-test/src/application_review.test.ts, browser-test/src/end_to_end_enumerators.test.ts, browser-test/src/question_lifecycle.test.ts, browser-test/src/support/admin_questions.ts
This is a broader change based on a comment about clarity of these types of functions (https://github.com/seattle-uat/civiform/pull/1627/files#r718926833). 
=> Refactor functions to take in object arguments

bin/build-dev, bin/localstack/wait
Update build dev script to push images to docker hub container registry: https://hub.docker.com/repository/docker/civiform/civiform/general
=> Push dev builds to docker hub

bin/build-dev
Reverts seattle-uat/civiform#1679
=> Revert "Push dev builds to docker hub"

bin/build-dev, bin/localstack/wait
Trying again, this time with specifying the docker hub domain and turning verbose logging on
=> Push to docker hub

universal-application-tool-0.0.1/app/views/admin/programs/ProgramAdministratorProgramListView.java, universal-application-tool-0.0.1/app/views/admin/programs/ProgramIndexView.java
We have misleading static "Last updated" strings, commenting them out until they can be made correct as part of #1657
=> Comment out static "Last updated 2 hours ago" messages

universal-application-tool-0.0.1/build.sbt, universal-application-tool-0.0.1/project/plugins.sbt
Upgrade play 2.8.7 -> 2.8.8
Dependencies required upgrading Jackson as well
=> Upgrade play version

browser-test/src/admin_program_translation.test.ts, universal-application-tool-0.0.1/conf/messages.es-US, universal-application-tool-0.0.1/test/controllers/applicant/ApplicantProgramBlocksControllerTest.java
Updated Spanish language translation for UI text.
Copied Spanish translation for each UI text item
=> Spanish Translation for UI text

browser-test/src/application_csv_download.test.ts, browser-test/src/support/applicant_questions.ts, browser-test/src/support/index.ts, universal-application-tool-0.0.1/app/models/Program.java, universal-application-tool-0.0.1/test/services/export/CsvExporterTest.java
Currently, only the most recent application submission is showed to program admins, but they'd like to see all submissions by an applicant. "OBSOLETE" applications are older versions of an application submitted. We will show these too in order to show all submitted applications. There is another issue with submission time getting updated when an application is marked as obsolete, but this will be handled in a separate PR.
#1711
=> Show previously submitted applications by an applicant

cloud/azure/main.tf
State of progress: was able to get the server up and connected to the database with both configured to allow public network access. That's not an acceptable security posture long term so currently trying to get everything running inside a virtual network. The current config seems to run fine and create all resources.
Next need to work on the application gateway (i think?)
=> developing Azure terraform template

browser-test/src/application_navigation.test.ts, browser-test/src/end_to_end_enumerators.test.ts, browser-test/src/support/applicant_questions.ts, universal-application-tool-0.0.1/app/controllers/applicant/ApplicantProgramBlocksController.java, universal-application-tool-0.0.1/app/services/MessageKey.java, universal-application-tool-0.0.1/app/views/applicant/ApplicantProgramBlockEditView.java, universal-application-tool-0.0.1/app/views/style/ApplicantStyles.java, universal-application-tool-0.0.1/conf/messages, universal-application-tool-0.0.1/conf/messages.en-US, universal-application-tool-0.0.1/conf/messages.es-US, universal-application-tool-0.0.1/conf/routes, universal-application-tool-0.0.1/test/controllers/applicant/ApplicantProgramBlocksControllerTest.java
Add previous button, so applicants can navigate to the previous page without going through the review page. 
Fixes #1650
=> Add previous button to programs

universal-application-tool-0.0.1/app/assets/javascripts/validation.ts, universal-application-tool-0.0.1/app/services/program/ProgramServiceImpl.java
Adds some more detail exceptions thrown when a question isn't available through a Version association with a program that expects it.
Intended to help with investigating https://github.com/seattle-uat/civiform/issues/1797
Also an autoformatter change in a TS file.
=> More logging around missing questions

bin/deploy-prod, bin/deploy-staging
=> Cache seattle staging deploy from correct image

universal-application-tool-0.0.1/app/controllers/dev/FileUploadController.java, universal-application-tool-0.0.1/app/services/MessageKey.java, universal-application-tool-0.0.1/app/views/dev/FileUploadView.java, universal-application-tool-0.0.1/conf/messages
Adding string from previous PR to messages for i18n.
Fixes #1792
=> Add string from Azure dev upload PR to Messages

universal-application-tool-0.0.1/app/controllers/dev/FileUploadController.java
/dev/fileUpload works on staging as well as on the dev environment. will be helpful for confirming this functionality works properly on the deployed instance
=> allow dev upload screen to show in staging

universal-application-tool-0.0.1/app/services/cloud/azure/BlobStorage.java
Running into a null pointer when this code is on azure staging instance. We were not instantiating the var before calling it 🤦
=> Fix AzureBlobClient null pointer

universal-application-tool-0.0.1/app/services/cloud/azure/BlobStorage.java
One more null pointer in the blob storage code
=> confirm userDelegationKey exists before calling it

cloud/azure/modules/app/main.tf
Without these app services cannot talk to the storage resource. 
=> Adding in the correct role assignments for storage account

cloud/azure/modules/app/main.tf
- needed for the CORS setting within the blob client.
=> Adding the Storage Account Contributor role to the terraform config

cloud/azure/modules/app/main.tf, cloud/azure/modules/app/variables.tf, cloud/deploys/staging_azure/main.tf, cloud/deploys/staging_azure/variables.tf
- Adding the staging host name variables
- adding the terraform code to create a the ssl cert + custom domain
=> Adding the staging hostname and cert 

cloud/azure/modules/app/main.tf, cloud/azure/modules/app/variables.tf, cloud/deploys/staging_azure/main.tf, cloud/deploys/staging_azure/variables.tf
- adding a var for custom hostname
- replace the hard coded staging/base urls with the variable ones
=> Custom Hostname variable

universal-application-tool-0.0.1/build.sbt
Upgrade AutoValue 1.7.4 -> 1.8.2
=> Upgrade deps: AutoValue

universal-application-tool-0.0.1/build.sbt
Upgrade jackson `2.12.5` -> `2.13.1`
=> Upgrade deps: jackson

cloud/azure/modules/app/locals.tf, cloud/azure/modules/app/main.tf, cloud/azure/modules/app/outputs.tf, cloud/azure/modules/app/variables.tf, cloud/azure/modules/custom_hostname/main.tf, cloud/azure/modules/custom_hostname/outputs.tf, cloud/azure/modules/custom_hostname/variables.tf, cloud/deploys/dev_azure/README.md, cloud/deploys/dev_azure/main.tf, cloud/deploys/dev_azure/outputs.tf, cloud/deploys/dev_azure/providers.tf, cloud/deploys/dev_azure/variables.tf, cloud/deploys/staging_azure/main.tf
- Refactors the custom hostname into it's own module 
- Creates a new deploy folder for dev, which does not use shared state (so can individually deploy to your own dev resource group)
=> Allow for a Dev Terraform

bin/dump-dev-program-config
Dev bin script that dumps question and program configuration from the local dev environment into postgres archive file, dev_programs.dump.
=> Add bin/dump-dev-program-config

universal-application-tool-0.0.1/project/plugins.sbt
upgrade play `2.8.8` -> `2.8.13`
=> Upgrade deps: play 2.8.8 -> 2.8.13

test-support/README.md, test-support/test_oidc_provider.js
Add doc link and comments to the existing code
=> OIDC test docs

cloud/deploys/bin/azure/README.md, cloud/deploys/bin/azure/key-vault-setup, cloud/deploys/bin/azure/key-vault.sh, cloud/deploys/bin/azure/lib.sh
Create a setup script and functions to set up and store generated secrets in Azure Key vault. This will be used by the setup script in the [civiform/civiform-deploy](https://github.com/civiform/civiform-deploy) repo.
=> Create setup script for Azure Key Vault

cloud/deploys/staging_azure/README.md
adding doc for setting the dns domain for staging
- [ x] Extended the README / documentation, if necessary
=> Adding doc for setting the dns domain for staging

cloud/azure/modules/app/locals.tf, cloud/azure/modules/app/main.tf, cloud/azure/modules/app/variables.tf, cloud/deploys/bin/azure/README.md, cloud/deploys/bin/azure/key-vault-setup, cloud/deploys/dev_azure/main.tf, cloud/deploys/dev_azure/variables.tf, cloud/deploys/staging_azure/README.md, cloud/deploys/staging_azure/main.tf, cloud/deploys/staging_azure/variables.tf, universal-application-tool-0.0.1/app/modules/SecurityModule.java, universal-application-tool-0.0.1/conf/application.conf
- Adds some support for AD to the terraform file
- Adds line by line comments on how the AD config is set up 
- support for configuring Azure AD with our staging set up 
=> Adding ad support to our terraform set up 

cloud/azure/modules/app/locals.tf, cloud/azure/modules/app/main.tf, cloud/azure/modules/app/variables.tf, cloud/deploys/dev_azure/main.tf, cloud/deploys/dev_azure/variables.tf, cloud/deploys/staging_azure/README.md, cloud/deploys/staging_azure/main.tf, cloud/deploys/staging_azure/variables.tf, universal-application-tool-0.0.1/conf/application.conf
Sets up SES to send email via civiform
=> Adding the Terraform Code to Set up SES

cloud/deploys/staging_azure/README.md
=> adding in a comment for how to generate the bastion rsa keys

cloud/azure/modules/app/locals.tf, cloud/azure/modules/app/main.tf, cloud/azure/modules/app/variables.tf, cloud/deploys/dev_azure/main.tf, cloud/deploys/dev_azure/variables.tf, cloud/deploys/staging_azure/main.tf, cloud/deploys/staging_azure/variables.tf
Not sure if this is necessary but might make deployment a lil faster, depending on how we do the script writing for deployment
=> Put AWS key id into the keyvault

browser-test/src/application_review.test.ts
temporary hack to fix the build, TODO has link to follow-up issue
=> Fix iframe bug with browser test

universal-application-tool-0.0.1/app/auth/saml/SamlCiviFormProfileAdapter.java, universal-application-tool-0.0.1/test/auth/ProfileMergeTest.java
=> Add unit tests for SAML profile adapter

cloud/shared/bin/doctor, cloud/shared/bin/doctor_impl, cloud/shared/bin/validate_cloud_provider
Add a script that checks for critical dependencies needed on the host computer for running deployment scripts. Checks for:
=> Create deployment doctor script

universal-application-tool-0.0.1/app/auth/CiviFormProfile.java, universal-application-tool-0.0.1/app/forms/QuestionForm.java, universal-application-tool-0.0.1/app/services/ErrorAnd.java, universal-application-tool-0.0.1/app/services/applicant/question/CurrencyQuestion.java, universal-application-tool-0.0.1/app/services/applicant/question/SingleSelectQuestion.java
Fixes to prefer Optional over nulls.
=> Various Null fixes including moving to Optional

cloud/azure/bin/input-secrets-to-keystore, cloud/azure/bin/lib/key_vault.sh, cloud/azure/modules/app/locals.tf, cloud/azure/modules/app/main.tf, cloud/azure/modules/app/variables.tf, cloud/azure/templates/azure_saml_ses/bin/setup.py, cloud/azure/templates/azure_saml_ses/main.tf, cloud/azure/templates/azure_saml_ses/variables.tf, cloud/deploys/dev_azure/main.tf, cloud/deploys/dev_azure/variables.tf, cloud/shared/bin/lib/setup.py
Adds the adfs post terraform setup to the setup script
=> Adding the part of the setup script that gets the ad user inputs

cloud/azure/bin/configure-slot-settings, cloud/azure/templates/azure_saml_ses/bin/setup.py
Adds the configure slot settings cript to the setup script
=> Adding the configure slot settings call to the setup script

cloud/azure/modules/app/locals.tf
=> Removing the .id from the adfs_secret var 

cloud/shared/bin/lib/setup.py
=> remove unneeded line in config

cloud/azure/templates/azure_saml_ses/bin/setup.py
=> Create resource group before logs

cloud/azure/bin/db-connection
=> Fix the db-connection script sourcing

cloud/azure/bin/lib/azure_log.sh
=> Adding the overwrite, required by the new version of the azure CLI

universal-application-tool-0.0.1/app/views/LoginForm.java, universal-application-tool-0.0.1/conf/application.conf, universal-application-tool-0.0.1/conf/messages
Removing Seattle specific language
=> Login Prompt accepts an argument

bin/build-and-push, prod.Dockerfile, universal-application-tool-0.0.1/app/views/BaseHtmlLayout.java, universal-application-tool-0.0.1/conf/application.conf
Adds a meta tag with name `civiform-build-tag` containing the docker image tag for the container.
=> Add HTML meta tag containing CiviForm image tag

cloud/azure/templates/azure_saml_ses/main.tf, cloud/azure/templates/azure_saml_ses/variables.tf, cloud/deploys/dev_azure/main.tf, cloud/deploys/dev_azure/variables.tf
=> removing docker_tag in favor of IMAGE_TAG

universal-application-tool-0.0.1/app/auth/oidc/OidcCiviFormProfileAdapter.java, universal-application-tool-0.0.1/app/models/Applicant.java, universal-application-tool-0.0.1/app/repository/ProgramRepository.java, universal-application-tool-0.0.1/app/repository/QuestionRepository.java, universal-application-tool-0.0.1/app/repository/StoredFileRepository.java, universal-application-tool-0.0.1/app/repository/UserRepository.java, universal-application-tool-0.0.1/test/repository/UserRepositoryTest.java
=> Misc format cleanups

cloud/shared/bin/lib/config_loader.py
the setup expects there to be properties not functions!
=> Need to Be properties to run config_loader

renovate.json
Adding package rules to group dependencies that should be updated together
=> Add grouping to renovatebot config

renovate.json
fixes https://github.com/seattle-uat/civiform/issues/2210
=> Fix renovate.json syntax

universal-application-tool-0.0.1/build.sbt
We're not using React, so let's remove the React dependencies.
=> Remove unused webjar dependencies

cloud/azure/modules/bastion/main.tf
=> does not update the bastion when deploying

cloud/azure/bin/lib/azure.sh, cloud/azure/templates/azure_saml_ses/main.tf
When deploying staging, ran into these issues! Adding the fixes for them.
=> Lil Terraform Fixes

universal-application-tool-0.0.1/app/repository/ProgramRepository.java
=> ProgramRepository Formatting/comment updates.

universal-application-tool-0.0.1/app/views/admin/programs/ProgramApplicationView.java
The question ID field in the Admin application page was needed to be removed for better readability. 
https://github.com/seattle-uat/civiform/issues/2008
=> Murthis/remove Question ID from admin application page

cloud/azure/modules/app/file-storage.tf, cloud/azure/modules/app/logs.tf, cloud/azure/modules/app/main.tf, cloud/azure/modules/app/role-assignments.tf
the log retention is a misnomer setting it to zero and making it less noisy
=> Setting the TF to have a storage policy for files

Dockerfile, prod.Dockerfile
bump openjdk version `jdk-11.0.10_9-alpine-slim` -> `jdk-11.0.11_9-alpine-slim`
=> Bump openjdk version

universal-application-tool-0.0.1/app/repository/VersionRepository.java
=> Remove unnecessary else nesting after a if-return.

.github/ISSUE_TEMPLATE/dependency_update.md
Issue Template for filing issues for dependency changes
=> Adding new issue template for dependencies

universal-application-tool-0.0.1/app/services/question/types/QuestionDefinition.java, universal-application-tool-0.0.1/test/controllers/admin/AdminQuestionControllerTest.java, universal-application-tool-0.0.1/test/services/question/types/QuestionDefinitionTest.java
Remove validation on question description
Fixes #1902
=> Remove validation on question description

universal-application-tool-0.0.1/package-lock.json
=> add package-lock.json

cloud/azure/bin/lib/azure.sh
Need to adapt the code a lil to allow for service principals to create role assignments
Part of Fix for #1805
=> Allowing for service principals to get role assignments

browser-test/src/dev_file_upload.test.ts, prod.Dockerfile, universal-application-tool-0.0.1/build.sbt
Part of moving away from the uat name.
Also includes a fix for the file upload test that only fails in CI.
=> Rename Play project to "civiform-server"

.github/workflows/scorecards.yml
[OSSF Scorecard](https://github.com/ossf/scorecard)
=> Set up OSSF Scorecard for security scanning

README.md
https://bestpractices.coreinfrastructure.org/en/projects/6008
=> Add OpenSSF best practices badge to README

bin/refresh-styles, server/package-lock.json, server/package.json
1. Fixing the name of the docket container. 
2. Fixing the version of tailwindcss (not sure why, but it fails to install with current setup). 
=> Fix refresh-styles script.

cloud/deploys/dev_azure/bin/terraform, cloud/shared/bin/terraform
Make a terraform command script that sets up your config and project directory
Allows running  `cloud/deploys/dev_azure/bin/terraform destroy` to remove your remote resources, or any other terraform command.
=> Make a terraform command script that sets up your config and project directory

cloud/azure/bin/lib/azure.sh, cloud/shared/bin/lib/setup.py, cloud/shared/bin/lib/terraform.sh
We need to auto approve `terraform apply` when using a service principal and not use that if it's a user input
=> Add auto approve for Service Prinicipals in TF 

README.md
Changing the readme to use new docs links and test out if i can submit these while not being on the proejct
- [ x Extended the README / documentation, if necessary
=> Update Readme to use the new docs links

cloud/deploys/dev_azure/bin/terraform, cloud/shared/bin/terraform
Per the style guide, '$@' should be quoted
=> Quote the arguments in the terraform command

server/app/services/question/types/QuestionType.java, server/app/views/admin/questions/QuestionsListView.java, server/app/views/components/Icons.java
This PR updates all the question type icons and labels in the Create New Question menu, in accordance with this proposal from @rahaghas: https://github.com/seattle-uat/civiform/issues/1904#issuecomment-1114249486
This PR doesn't remove the static question type as that would be out of scope.
Fixes #1904
=> Updated all QuestionType icons and labels for clarity

bin/sbt-test, server/app/controllers/FileController.java, test-support/unit-test-docker-compose.dev.yml, test-support/unit-test-docker-compose.yml
Also rename the last couple usages of universal-application-tool-0.0.1/ dir to server/
=> Make sure unit tests correctly use the server/ directory for tests

server/app/repository/ApplicationRepository.java, server/test/repository/ApplicationRepositoryTest.java
If there are multiple drafts for an application - throw an error. This should not happen. 
Also refactored tests to make them clearer.
=> if there are multiple drafts for an application throw an error. This should not happen.

server/app/repository/ApplicationRepository.java, server/test/repository/ApplicationRepositoryTest.java
Addressing @shanemc-goog's comments from https://github.com/seattle-uat/civiform/pull/2445. 
I tried to give better names to variables in tests, but let me know if you have better ideas.
=> Variable Naming and Test improvements for Application Repository

server/test/modules/MainModuleTest.java
TearDown may happen when unnecessary otherwise.
=> Reset the Optional for each test.

cloud/deploys/dev_azure/bin/docker-build-tag-push
=> changing the pull to to be the latest cache not the test cache

cloud/shared/bin/lib/terraform.sh
In order to debug the deploy in github actions (seeing a failure to find a file), I am adding some comments that should help 
=> Commenting some comments to deploy code

cloud/shared/bin/lib/terraform.sh
Incorrect call to terraform and incorrect env var. Fix for the deploy
=> Call chdir and use correct env var

server/conf/messages.tl
=> Updates to Tagalog

server/conf/messages.so
=> Update Somali UI text

server/conf/messages.ko
=> Update Korean messages

browser-test/browser-test-compose.dev.yml, browser-test/browser-test-compose.yml, browser-test/jest-playwright.config.js, browser-test/jest.config.js, browser-test/src/application_download.test.ts, browser-test/src/name.test.ts, browser-test/src/question_lifecycle.test.ts, browser-test/src/support/admin_programs.ts, browser-test/src/support/admin_questions.ts, browser-test/src/support/wait.ts, formatter.Dockerfile
The autoformatter was only running prettier for `server`, this changes it to also run for `browser-test`.
=> Autoformat browser-test files

server/app/repository/QuestionRepository.java, server/app/services/question/QuestionServiceImpl.java
Naming tweaks, this matches ProgramRepository
=> Normalize updateOrCreate naming to createOrUpdate

.github/workflows/azure-saml-ses-deploy-test.yaml, cloud/azure/bin/cli-login, cloud/azure/bin/deploy, cloud/azure/bin/lib/azure_log.sh, cloud/shared/bin/lib.sh, cloud/shared/bin/lib/civiform_mode.sh, cloud/shared/bin/lib/terraform.sh, cloud/shared/bin/resolve-latest-snapshot-tag, cloud/shared/variable_definitions.json
Adds a github action that will execute a deploy to staging which just 'plans' the terraform. this should do everthing outside of actually deploying. this should be reasonably fast and cost less than deploying. we can ideally run this on changes to the cloud directory to confirm if we are doing something to the deploy system.
=> Add a deploy test for azure saml ses

cloud/azure/templates/azure_saml_ses/bin/setup.py
(Sorry should have ran the deploy script again before submitting the previous PR.)
=> Add missing double quotes in setup.py for deploy script.

cloud/deploys/dev_azure/civiform_config.example.sh, server/conf/application.conf
It took me couple hours to figure this out today, leaving some comments for future self.
(It would be better to be uniform about this, but that's a bigger change).
=> add comment to staging/base urls

browser-test/src/support/admin_api_keys.ts, server/app/views/admin/AdminLayout.java
=> Add admin nav link for API key index

.github/workflows/push.yaml
Removing Seattle staging deploy and probers.
=> Removing the Seattle staging deploy and probers from ci action

.github/workflows/azure-saml-ses-deploy-test.yaml
Updating aws secret keys used in this workflow to the new ones in the github secrets
=> Updating aws secret keys used in this workflow

server/app/annotations/FeatureFlags.java, server/app/modules/FeatureFlagsModule.java, server/app/views/LoginForm.java, server/conf/application.conf, server/test/modules/FeatureFlagsModuleTest.java
Adds Injectable annotations and a Module provider that surfaces the system application configuration for features that should be on or off across the entire application.
Fixes #1943
=> Add support for Feature Flags.

cloud/aws/templates/aws_oidc/providers.tf, cloud/azure/templates/azure_saml_ses/main.tf
Fixes https://github.com/seattle-uat/civiform/issues/2305
=> upgrade tf to 4.16.0

.github/workflows/tests.yml, bin/run-browser-tests-ci-batch
Runs the CI browser tests in parallel batches.
fixes https://github.com/seattle-uat/civiform/issues/1936
=> Run CI browser tests in parallel batches

bin/pull-image
Pull the images in bin/pull-images in parallel to speed it up.   
Also allow flags to specify multiple images to pull (instead of only using the first)
=> Pull docker images in parallel 

browser-test/src/file.test.ts
Fixing typo in test. Adding type annotations and a few optional chaining (the ?.) to resolve some syntax errors.
=> Fixing typo, adding type annotions, and optional chaining.

bin/dev-dump-program-config, bin/dev-pgadmin, bin/dev-psql, bin/dev-restore-db, bin/lib/docker.sh, bin/remove-browser-test-env, bin/remove-dev, bin/remove-test-env, bin/run-browser-test-env, bin/run-dev, bin/run-test-ci, bin/sbt-test, bin/stop-dev, bin/vscode-setup
Avoids using variables for commands, removed use of exec.
=> Change the docker compose commands to be functions

browser-test/src/file.test.ts, browser-test/src/support/applicant_questions.ts
Ran bin/fmt, since there were ts files that needed formatting.
=> Run the formatter

.github/workflows/format.yaml, bin/build-and-push-formatter, bin/run-browser-tests-ci-batch, browser-test/src/file.test.ts, browser-test/src/support/applicant_questions.ts, cloud/aws/templates/aws_oidc/bin/setup.py, cloud/azure/templates/azure_saml_ses/bin/setup.py, cloud/shared/bin/doctor_impl, cloud/shared/bin/lib/check.py, cloud/shared/bin/lib/check_test.py, cloud/shared/bin/lib/config_loader.py, cloud/shared/bin/lib/config_loader_test.py, cloud/shared/bin/lib/setup.py, cloud/shared/bin/lib/setup_class_loader.py, cloud/shared/bin/lib/setup_template.py, cloud/shared/bin/lib/tf_apply_setup.py, cloud/shared/bin/lib/variable_definition_loader.py, cloud/shared/bin/lib/write_tfvars.py, cloud/shared/bin/lib/write_tfvars_test.py, cloud/shared/validate_variable_definitions.py, cloud/shared/validate_variable_definitions_test.py, formatter/fmt, formatter/formatter.Dockerfile
Use the https://github.com/google/yapf Google Python styleguide formatter for python code.  Added to bin/fmt, and as a github action on pull requests.
=> Add google/yapf python formatter

.github/workflows/tests.yml, bin/run-test-ci, bin/run-test-coverage, server/build.sbt, test-support/unit-test-docker-compose.dev.yml, test-support/unit-test-docker-compose.yml
use server/jacoco for the report directory, map it in the ci tests (already mapped in dev)
also make bin/run-test-coverage for local jacoco testing
=> Test if jacoco works remotely

.github/workflows/tests.yml, server/build.sbt
They weren't being picked up in Test/
=> Change jacoco settings to global scope

.github/workflows/tests.yml
Added generate-branches-badge: true as it defaults to false
=> update generate-badge to true

server/app/views/LoginForm.java
This mode gets used a lot by non-technical folks for demo purposes. Calling it "debug mode" looks a little less professional in that context.
=> Change header 'DEBUG MODE' -> 'DEMO MODE'

cloud/aws/modules/setup/secrets.tf
=> Fix postgres_username resource

cloud/aws/modules/setup/logbucket.tf, cloud/aws/templates/aws_oidc/filestorage.tf
=> Encrypt all s3 buckets we use

server/app/services/cloud/aws/SimpleStorage.java
Amazon switched long time ago:
https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-bucket-intro.html
https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/ 
=> switch to new s3 address

cloud/aws/templates/aws_oidc/bin/setup.py, cloud/azure/templates/azure_saml_ses/bin/setup.py, cloud/shared/bin/lib/setup.py, cloud/shared/bin/lib/setup_template.py
Switching up the setup script to remove an azure specific command
=> Get Current User for aws and azure

.github/workflows/format.yaml, bin/fmt, browser-test/bin/fmt, browser-test/src/application_download.test.ts, browser-test/src/question_lifecycle.test.ts, formatter/fmt
Make sure the formatter uses the latest config during pr tests, so it picks up any changes.
Also add trilom/file-changes-action, since steps using "contains(toJSON(steps.file_changes.outputs.files)" were never running.
browser-test/bin/fmt was broken by #2603
=> Run bin/fmt and browser-test/bin/fmt in pr tests

browser-test/src/application_download.test.ts, browser-test/src/question_lifecycle.test.ts, cloud/aws/modules/setup/backend_storage.tf, cloud/aws/modules/setup/logbucket.tf, cloud/aws/modules/setup/secrets.tf, cloud/aws/templates/aws_oidc/aim.tf, cloud/aws/templates/aws_oidc/autoscaling.tf, cloud/aws/templates/aws_oidc/filestorage.tf, cloud/aws/templates/aws_oidc/main.tf, cloud/aws/templates/aws_oidc/setup/main.tf, cloud/aws/templates/aws_oidc/setup/variables.tf, cloud/aws/templates/aws_oidc/variable_definitions.json, cloud/aws/templates/aws_oidc/variables.tf, cloud/aws/templates/aws_oidc/vpc.tf
Currently we have some hard coded values-- using an app_prefix value so that we can have multiple dev instances on the same account. 
=> Adding app_prefix var when creating instance

browser-test/src/application_download.test.ts, browser-test/src/question_lifecycle.test.ts, cloud/aws/templates/aws_oidc/bin/setup.py, cloud/shared/bin/lib/setup.py, cloud/shared/bin/lib/setup_template.py
Making some fixes to the tfvars script so that we create it before we do any setup script (AWS setupscript uses terraform). Also grabs the backend_override so that the dev upload works
=> Write TFVars before setup script

cloud/aws/modules/secrets_manager/secrets.tf, cloud/aws/modules/secrets_manager/variables.tf, cloud/aws/templates/aws_oidc/bin/setup.py, cloud/aws/templates/aws_oidc/main.tf, cloud/shared/bin/lib/config_loader.py
=> need to add a few more app_prefixes

server/app/auth/AuthIdentityProviderName.java, server/app/controllers/LoginController.java, server/app/modules/SecurityModule.java, server/app/services/MessageKey.java, server/app/views/LoginForm.java, server/conf/messages
By setting CIVIFORM_APPLICANT_IDP to "disabled", remove all checks for auth provider configuration, and remove the main login button from the home screen.
=> Allow disabling of applicant auth

server/app/controllers/admin/AdminApplicationController.java, server/app/controllers/api/ProgramApplicationsApiController.java, server/app/repository/ProgramRepository.java, server/app/repository/TimeFilter.java, server/app/services/export/ExporterService.java, server/app/services/export/JsonExporter.java, server/app/services/program/ProgramService.java, server/app/services/program/ProgramServiceImpl.java, server/test/repository/ApplicationRepositoryTest.java, server/test/repository/ProgramRepositoryTest.java, server/test/services/export/CsvExporterTest.java
Follow-on to #2749, where the TimeFilter was originally introduced.
#1743
=> Using TimeFilter in API requests for consistency.

server/conf/messages, server/conf/messages.en-US
* Fixing the button.nextScreen text to be "Save and next" which is what the messages.en-US file was changed to a while back
* Diffing the messages and messages.en-US files and updating messages.en-US where out of sync
Related to #2275 and #2712
=> Syncing messages/messages.en-US files

cloud/aws/modules/secrets_manager/outputs.tf, cloud/aws/modules/secrets_manager/secrets.tf, cloud/aws/modules/setup/secrets.tf, cloud/aws/templates/aws_oidc/bin/setup.py, cloud/aws/templates/aws_oidc/main.tf, cloud/aws/templates/aws_oidc/variable_definitions.json, cloud/aws/templates/aws_oidc/variables.tf
=> Add OIDC secrets and variables for resident auth

server/conf/application.conf
Fixes https://github.com/seattle-uat/civiform/issues/2800
=> Add env variable for list of supported langs

cloud/aws/templates/aws_oidc/main.tf, cloud/aws/templates/aws_oidc/variable_definitions.json, cloud/aws/templates/aws_oidc/variables.tf, cloud/aws/templates/aws_oidc/vpc.tf, cloud/azure/modules/app/variables.tf, server/app/auth/oidc/OidcProvider.java, server/app/auth/oidc/applicant/GenericOidcProvider.java
Needed to help make auth work on AWS
=> Allow apprunner to access internet & add other auth variables

.github/pull_request_template.md
Per the new release process, add a section for release notes in the PR template.
=> Add Release notes section to template

cloud/aws/modules/setup/backend_storage.tf, cloud/aws/templates/aws_oidc/filestorage.tf, cloud/aws/templates/aws_oidc/main.tf, cloud/aws/templates/aws_oidc/secrets.tf, cloud/aws/templates/aws_oidc/vpc.tf
Implement features suggested in #2934:
* Database can accept traffic only from withing VPC.
* Enabled key rotatation for KMS keys.
* Enabled database log export to CloudWatch. Checked that logs are indeed exported to CloudWatch after deployment.
Fixes #2934.
=> Few AWS TF security improvements

browser-test/src/address.test.ts, browser-test/src/admin_dropdown_create_and_edit.test.ts, browser-test/src/admin_program_admins.test.ts, browser-test/src/admin_program_hidden.test.ts, browser-test/src/admin_program_list.test.ts, browser-test/src/application_navigation.test.ts, browser-test/src/application_optional_questions.test.ts, browser-test/src/checkbox.test.ts, browser-test/src/currency.test.ts, browser-test/src/date.test.ts, browser-test/src/dropdown.test.ts, browser-test/src/email.test.ts, browser-test/src/file.test.ts, browser-test/src/id.test.ts, browser-test/src/number_input.test.ts, browser-test/src/program_deep_link.test.ts, browser-test/src/question_delete.test.ts, browser-test/src/question_lifecycle.test.ts, browser-test/src/radio_button.test.ts, browser-test/src/static_text.test.ts, browser-test/src/support/index.ts, browser-test/src/text.test.ts, browser-test/src/trusted_intermediary.test.ts
Adds explicit types to variables which otherwise treated as `any`. This required to enable strict type checking. Plus it might also improve auto-suggestion when using IDEs. 
Related #2955
=> Improve typing in browser tests

.github/workflows/tests.yaml
Reverts civiform/civiform#2977
Fixes #2976
=> Revert "Temporarily marking code coverage upload failures as non-blocking."

bin/create-release
For handling the repository org change from seattle-uat/civiform to civiform/civiform
=> Updating url for github api calls

.github/workflows/build_push_ci.yaml, Dockerfile, formatter/formatter.Dockerfile, prod.Dockerfile
OpenJDK doesn't successfully compile for arm (it randomly times out).  Move back to the bellsoft image re: https://github.com/adoptium/containers/issues/158#issuecomment-1046890267
n/a
=> Move back to bellsoft image for arm

cloud/aws/templates/aws_oidc/variable_definitions.json
=> add validation to more variables

browser-test/src/admin_predicates.test.ts, browser-test/src/static_text.test.ts
Found them using eslint. Once https://github.com/civiform/civiform/pull/2777 is in it will be a presubmit error.
=> Add missing awaits to browser tests

cloud/aws/templates/aws_oidc/main.tf, cloud/shared/bin/lib/destroy.py
Add availability zones, deletion protection, final snapshot and encryption to database.
Fixes #3054
=> add prod db params

server/test/controllers/dev/DatabaseSeedControllerTest.java
Per this [help doc](https://docs.civiform.us/contributor-guide/developer-guide/troubleshooting#database) stop the Application and free up threads that are made.
NA
=> Fix Dev Seed test to clean up its Application and db connections

cloud/aws/bin/deploy.py, cloud/aws/templates/aws_oidc/bin/aws_template.py, cloud/aws/templates/aws_oidc/bin/destroy.py, cloud/aws/templates/aws_oidc/bin/setup.py, cloud/azure/templates/azure_saml_ses/bin/destroy.py, cloud/azure/templates/azure_saml_ses/bin/setup.py, cloud/shared/bin/lib/civiform_mode.sh, cloud/shared/bin/lib/config_loader.py, cloud/shared/bin/lib/terraform.py, cloud/shared/bin/lib/terraform.sh, cloud/shared/variable_definitions.json
Needed to automatically deploy staging.
=> add option for civiform that auto approves terraform

cloud/shared/bin/lib/terraform.py
It helps to reduce amount of warnings messages when running deploy scripts. Properly fixing warnings is tricky as we'll need to generate tfvars file specific to cloud provider. With compact warnings they look less scary. 
Before:
```
Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
╷
│ Warning: Value for undeclared variable
│
│ The root module does not declare a variable named "civic_entity_full_name" but a value was found in file "setup.auto.tfvars". If you meant to use this value, add a "variable" block to the
│ configuration.
│
│ To silence these warnings, use TF_VAR_... environment variables to provide certain "global" settings to all configurations in your organization. To reduce the verbosity of these …
```
=> Set compact-warnings option on terraform

cloud/aws/modules/ses/main.tf, cloud/aws/templates/aws_oidc/app.tf
=> add ses permissions

server/app/views/admin/questions/QuestionsListView.java
=> Repointing a TODO at a more appropriate issue.

cloud/aws/templates/aws_oidc/app.tf, cloud/aws/templates/aws_oidc/secrets.tf
Add API salt secret. Value is autogenerated.
=> Add API salt secret

.github/workflows/aws-oidc-deploy-test.yaml, cloud/aws/templates/aws_oidc/bin/setup.py, cloud/shared/bin/lib/terraform.py
Copies config from https://github.com/civiform/staging-aws-deploy/blob/main/civiform_config.sh and runs setup and deploy in test mode.
=> add test for aws oidc template

cloud/azure/bin/setup-keyvault, cloud/azure/modules/app/locals.tf, cloud/azure/modules/app/secrets.tf
Add API secret salt variable. 
=> add api secret salt to azure setup

cloud/shared/bin/lib/setup.py
=> Add link to the troubleshooting page when setup fails

README.md
=> Add AWS staging deploy badge

server/app/controllers/dev/DatabaseSeedController.java
Add one of each question type for /dev/seed mock program. The file upload question is added as optional since there is some additional friction to getting it working for local dev ([link](https://docs.civiform.us/contributor-guide/developer-guide/file-storage-backend)).
N/A - ignore for release (testing only change)
=> Add one of each question type for /dev/seed mock program

server/app/controllers/admin/AdminProgramStatusesController.java
=> Removing already implemented TODO for status tracking translations.
